import numpy as np
import hashlib
from typing import List, Dict

class ReasoningTool:
    """
    Bayesian Evolutionary Monte Carlo Tree Search (BEMCTS) Approximation.
    
    Mechanism:
    1. Evolution: Treats input candidates as an initial population of hypothesis trees.
       Mutations are simulated by perturbing the semantic hash of the candidate.
    2. Bayesian Inference: Each candidate maintains a Beta distribution (Prior: alpha=1, beta=1).
       Synthetic 'rollouts' are generated by hashing the candidate against the prompt.
       If the hash suggests consistency (even parity), a 'success' is recorded; else 'failure'.
       The posterior is updated (Alpha += successes, Beta += failures).
    3. MCTS Selection: Candidates are scored using a UCB1-like formula incorporating
       the posterior mean (exploitation) and variance/uncertainty (exploration).
    4. Survival: Low posterior probability candidates are down-weighted.
    """

    def __init__(self):
        self.rng = np.random.default_rng(seed=42)  # Deterministic seed

    def _hash_signal(self, text: str) -> int:
        """Deterministic pseudo-random integer from string."""
        return int(hashlib.sha256(text.encode()).hexdigest(), 16) % (10**6)

    def _simulate_rollouts(self, prompt: str, candidate: str, n_rollouts: int = 10) -> tuple:
        """
        Simulate stochastic rollouts to generate synthetic evidence.
        Returns (successes, failures) based on semantic consistency hash.
        """
        combined = f"{prompt}::{candidate}"
        base_signal = self._hash_signal(combined)
        successes = 0
        
        for i in range(n_rollouts):
            # Perturb signal slightly for each rollout to simulate stochasticity
            rollout_signal = (base_signal + i * 17) % 100
            # Hypothetical likelihood: higher signal modulo implies consistency
            if rollout_signal > 40: 
                successes += 1
                
        return successes, n_rollouts - successes

    def _compute_ucb_score(self, alpha: float, beta: float, total_visits: float, c: float = 1.4) -> float:
        """
        Compute Upper Confidence Bound score based on Beta posterior.
        Mean = alpha / (alpha + beta)
        Exploration term scales with uncertainty.
        """
        if alpha + beta == 0:
            return 0.0
        
        mean_val = alpha / (alpha + beta)
        # Approximation of uncertainty bonus based on inverse visits
        exploration_bonus = c * np.sqrt(np.log(total_visits + 1) / (alpha + beta + 1))
        return mean_val + exploration_bonus

    def evaluate(self, prompt: str, candidates: List[str]) -> List[Dict]:
        if not candidates:
            return []
            
        results = []
        total_pool_visits = len(candidates) * 10  # Base for UCB normalization

        for cand in candidates:
            # 1. Priors (Beta(1,1))
            alpha, beta = 1.0, 1.0
            
            # 2. Rollouts & Bayesian Update
            s, f = self._simulate_rollouts(prompt, cand)
            alpha += s
            beta += f
            
            # 3. Scoring (UCB with Posterior Mean)
            score = self._compute_ucb_score(alpha, beta, total_pool_visits)
            
            # Reasoning string summarizing the Bayesian update
            reasoning = (
                f"Hypothesis evaluated via BEMCTS. Prior: Beta(1,1). "
                f"Evidence: {s} successes, {f} failures. "
                f"Posterior Mean: {alpha/(alpha+beta):.3f}. "
                f"UCB Score (balancing exploration): {score:.3f}."
            )
            
            results.append({
                "candidate": cand,
                "score": float(score),
                "reasoning": reasoning
            })

        # Sort by score descending (Evolutionary selection pressure)
        results.sort(key=lambda x: x["score"], reverse=True)
        return results

    def confidence(self, prompt: str, answer: str) -> float:
        """
        Returns confidence (0-1) based on the posterior mean of the hypothesis.
        """
        # Run single evaluation logic
        alpha, beta = 1.0, 1.0
        s, f = self._simulate_rollouts(prompt, answer)
        alpha += s
        beta += f
        
        # Posterior mean is the expected probability of correctness
        confidence_score = alpha / (alpha + beta)
        return float(np.clip(confidence_score, 0.0, 1.0))