"""Cycle 005 — separate COMPETENCE from EXPOSURE. The kill test for cycle 004's verdict.

External review, 2026-08-27, sharpest point: `E_ijk` is an ON-POLICY outcome, so a
large `circuit x world` term can arise even if a circuit implements exactly the
same computation everywhere. Worlds differ in which decision states occur and how
consequential they are. A circuit that is identically competent per-decision will
still show wildly different world-level value if one world's decisions are mostly
free and another's are mostly decisive.

    E_ijk  =  deployment exposure  x  conditional competence

and cycle 004 measured only their product. `CONTEXTUAL_BASIS_REQUIRED` claimed the
competence half is world-dependent. It may be the exposure half.

The separation is unusually cheap here because the exact value functions already
exist. For a STOP circuit at a non-forced decision state s:

    best(s)     = max(pot(s), V(s))            what an optimal stopper gets
    chosen(s)   = pot(s) if circuit stops else V(s)
    regret(s)   = (best(s) - chosen(s)) / EV*  normalised so worlds compare

`regret(s)` is evaluated against the OPTIMAL continuation V, which makes it
partner-free by construction -- it is the quality of this decision, not of the
policy the decision sits inside. Three quantities per (circuit, world):

    UNWEIGHTED   mean regret over decision states, every state counted once.
                 Competence with exposure removed.
    OCCUPANCY    regret weighted by the probability the circuit's own play reaches
                 the state. This is what E_ijk reflects.
    DISAGREE     fraction of decision states where the circuit differs from optimal.

The test: decompose UNWEIGHTED regret across circuit x world. If `circuit x world`
collapses relative to cycle 004, the verdict was measuring support mismatch and
dies. If it survives, the verdict returns stronger than it was.

Either result is useful, which is why it is worth running before building anything
on top of cycle 004.
"""
from __future__ import annotations

import collections
import json
import pathlib
import statistics
from datetime import datetime, timezone

from ludus.bench.circuits import STOP_CIRCUITS, optimal_select
from ludus.bench.compiled import compile_world, solve

ROOT = pathlib.Path(__file__).resolve().parents[2]
ATLAS = ROOT / "ludus" / "atlas"


def stop_regret_profile(world, circuit) -> dict:
    """Per-decision regret for one STOP circuit in one world, three weightings."""
    cw = compile_world(world)
    ev_star, V, W = solve(cw)
    if ev_star <= 0:
        return {}
    sel = optimal_select(V, W)

    def occupancy(stop_rule):
        mass = collections.defaultdict(float)
        front = {cw.initial: 1.0}
        while front:
            nxt = collections.defaultdict(float)
            for s, m in front.items():
                if m <= 1e-12 or cw.forced[s]:
                    continue
                mass[s] += m
                if stop_rule(s):
                    continue
                for p, opts in cw.trans.get(s, ()):
                    if opts:
                        nxt[sel(cw, s, opts)] += m * p
            front = nxt
        return mass

    # SELF occupancy: weighted by where the circuit's OWN play goes. This is
    # circular -- it concentrates weight on states the circuit steered itself
    # into, which are disproportionately states it handles well.
    mass = occupancy(lambda s: circuit(cw, s, sel))
    # REFERENCE occupancy: a COMMON distribution of decision states, generated by
    # optimal play and identical for every circuit in the world. This is what the
    # review actually asked for and what the first implementation got wrong.
    # It is also the weighting this bench already adopted in cycles 002-003 after
    # uniform weighting inflated a reading from 0.412 to 0.900 -- and then failed
    # to apply here.
    ref = occupancy(lambda s: cw.pot[s] >= V.get(s, 0.0))
    tref = sum(ref.values())

    regrets, weights, disagree, order = [], [], [], []
    for s in cw.pot:
        if cw.forced[s] or s not in V:
            continue
        order.append(s)
        best = max(cw.pot[s], V[s])
        stops = circuit(cw, s, sel)
        chosen = cw.pot[s] if stops else V[s]
        r = (best - chosen) / ev_star
        regrets.append(r)
        weights.append(mass.get(s, 0.0))
        disagree.append(1.0 if abs(best - chosen) > 1e-12 else 0.0)

    if not regrets:
        return {}
    tw = sum(weights)
    return {
        "n_decision_states": len(regrets),
        "unweighted_mean_regret": round(statistics.mean(regrets), 6),
        "unweighted_max_regret": round(max(regrets), 6),
        "occupancy_weighted_regret": round(
            sum(r * w for r, w in zip(regrets, weights)) / tw, 6) if tw > 0 else None,
        "reference_weighted_regret": round(
            sum(r * ref.get(s, 0.0) for r, s in zip(regrets, order)) / tref, 6)
            if tref > 0 else None,
        "disagreement_rate": round(statistics.mean(disagree), 6),
        "occupancy_mass_total": round(tw, 6),
    }


def decompose2(M, rows, cols) -> dict:
    """Two-way exact ANOVA on a complete rows x cols table."""
    vals = [M[(r, c)] for r in rows for c in cols]
    n = len(vals)
    g = sum(vals) / n
    a = {r: sum(M[(r, c)] for c in cols) / len(cols) - g for r in rows}
    b = {c: sum(M[(r, c)] for r in rows) / len(rows) - g for c in cols}
    ss_a = len(cols) * sum(v * v for v in a.values())
    ss_b = len(rows) * sum(v * v for v in b.values())
    total = sum((v - g) ** 2 for v in vals)
    ss_ab = max(0.0, total - ss_a - ss_b)
    return {"share_circuit": round(ss_a / total, 4) if total > 1e-15 else 0.0,
            "share_world": round(ss_b / total, 4) if total > 1e-15 else 0.0,
            "share_circuit_x_world": round(ss_ab / total, 4) if total > 1e-15 else 0.0,
            "grand_mean": round(g, 6), "total_ss": round(total, 8)}


def main() -> None:
    from ludus.bench.partner_matrix import factorial_worlds, real_worlds
    ATLAS.mkdir(parents=True, exist_ok=True)
    out = {"artifact": "cycle 005 occupancy-controlled competence",
           "prompted_by": "external review 2026-08-27, point 1",
           "ts_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
           "no_model_calls": True, "exact": True, "blocks": {}}

    for label, ws in (("REAL_reconstructed", real_worlds()),
                      ("FOUNDRY", factorial_worlds())):
        prof, names = {}, []
        for w in ws:
            row = {}
            for fn in STOP_CIRCUITS:
                p = stop_regret_profile(w, fn)
                if p:
                    row[fn.rid] = p
            if row:
                prof[w.name] = row
                names.append(w.name)
            print(f"  [{label}] {w.name}", flush=True)
        rids = [f.rid for f in STOP_CIRCUITS]
        blk = {"per_world": prof}
        for key, tag in (("unweighted_mean_regret", "UNWEIGHTED (all states equal)"),
                         ("reference_weighted_regret", "REFERENCE occupancy (common dist)"),
                         ("occupancy_weighted_regret", "SELF occupancy (circular)"),
                         ("disagreement_rate", "DISAGREEMENT rate")):
            M = {}
            ok = True
            for r in rids:
                for c in names:
                    v = prof.get(c, {}).get(r, {}).get(key)
                    if v is None:
                        ok = False
                    else:
                        M[(r, c)] = v
            if ok:
                blk[key] = {"label": tag, **decompose2(M, rids, names)}
        out["blocks"][label] = blk
        (ATLAS / "cycle005_occupancy.json").write_text(json.dumps(out, indent=2),
                                                       encoding="utf-8")
    print(f"\nwrote {ATLAS / 'cycle005_occupancy.json'}")


if __name__ == "__main__":
    import threading
    for _mb in (256, 128, 64, 32):
        try:
            threading.stack_size(_mb * 1024 * 1024)
            break
        except Exception:
            continue
    th = threading.Thread(target=main)
    th.start()
    th.join()
