#!/usr/bin/env python3
"""
Task C: Hit Rate Audit Trail
Aletheia self-audit of the 35 predictions in discoveries table.

CRITICAL: Every number is backed by an exact SQL query printed inline.
"""

import duckdb
import json
from pathlib import Path
from datetime import datetime

DB_PATH = "F:/Prometheus/noesis/v2/noesis_v2.duckdb"
OUTPUT_PATH = "F:/Prometheus/audit/data/hit_rate_audit_trail.json"

def main():
    con = duckdb.connect(DB_PATH, read_only=True)

    # ── Step 1: Query ALL 35 rows ──────────────────────────────────────
    sql_all = """
    SELECT
        discovery_id,
        hub_id,
        damage_operator,
        resolution_name,
        description,
        tensor_score,
        tensor_rebuild_number,
        verification_status,
        verified_as,
        discovery_method,
        timestamp
    FROM discoveries
    ORDER BY discovery_id
    """
    print(f"SQL [all rows]:\n{sql_all.strip()}\n")
    rows = con.execute(sql_all).fetchall()
    cols = [
        "discovery_id", "hub_id", "damage_operator", "resolution_name",
        "description", "tensor_score", "tensor_rebuild_number",
        "verification_status", "verified_as", "discovery_method", "timestamp"
    ]
    print(f"Total rows returned: {len(rows)}")
    assert len(rows) == 35, f"Expected 35 rows, got {len(rows)}"

    # ── Step 2: Classify each prediction ───────────────────────────────
    audit_rows = []
    for row in rows:
        rec = dict(zip(cols, row))

        # Determine verification source
        vstatus = rec["verification_status"]
        vmethod = rec["discovery_method"]

        if vstatus is None or vstatus == "PREDICTED":
            # 30 rows have status='PREDICTED' with verified_as=NULL
            # These were generated by archaeological_prediction but never
            # independently verified. They are tensor-score ranked hypotheses.
            verification_source = "UNVERIFIED"
            audit_classification = "UNVERIFIED"
            self_referential = False
        elif vstatus == "VERIFIED_EXACT":
            # 4 rows: DISC_001 through DISC_004
            # These were generated by tensor_consensus_prediction and then
            # verified_as references a known external result (Newton-Raphson,
            # PGM, weak measurement, Stirling cycles).
            # However: the verification was performed BY Aletheia during the
            # same pipeline run that generated the predictions. No external
            # human or third-party tool confirmed these independently.
            # The verified_as names ARE real techniques, so the mapping is
            # correct — but the verification act was self-referential.
            verification_source = "aletheia_self_verification"
            audit_classification = "EXACT"
            self_referential = True  # Aletheia verified her own predictions
        elif vstatus == "STRUCTURALLY_IMPOSSIBLE":
            # 1 row: DISC_005 (Mostow rigidity)
            # Correctly identified as structurally impossible — no resolution
            # exists because rigidity IS the point. This is a correct
            # classification, not a miss.
            verification_source = "aletheia_structural_analysis"
            audit_classification = "EXACT"
            self_referential = True  # Still self-verified
        else:
            verification_source = "unknown"
            audit_classification = "UNVERIFIED"
            self_referential = False

        audit_rows.append({
            "prediction_id": rec["discovery_id"],
            "hub_id": rec["hub_id"],
            "damage_operator": rec["damage_operator"],
            "resolution_name": rec["resolution_name"],
            "description": rec["description"],
            "tensor_score": rec["tensor_score"],
            "tensor_rebuild_number": rec["tensor_rebuild_number"],
            "verification_status": vstatus,
            "verified_as": rec["verified_as"],
            "discovery_method": vmethod,
            "audit_classification": audit_classification,
            "verification_source": verification_source,
            "self_referential_flag": self_referential,
        })

    # ── Step 3: Compute hit rate transparently ─────────────────────────

    # Count by classification
    sql_status_counts = """
    SELECT verification_status, COUNT(*) AS cnt
    FROM discoveries
    GROUP BY verification_status
    ORDER BY verification_status
    """
    print(f"\nSQL [status counts]:\n{sql_status_counts.strip()}\n")
    status_counts = con.execute(sql_status_counts).fetchall()
    for s, c in status_counts:
        print(f"  {s}: {c}")

    exact_count = sum(1 for r in audit_rows if r["audit_classification"] == "EXACT")
    approximate_count = sum(1 for r in audit_rows if r["audit_classification"] == "APPROXIMATE")
    spurious_count = sum(1 for r in audit_rows if r["audit_classification"] == "SPURIOUS")
    miss_count = sum(1 for r in audit_rows if r["audit_classification"] == "MISS")
    unverified_count = sum(1 for r in audit_rows if r["audit_classification"] == "UNVERIFIED")

    print(f"\n=== Audit Classification Counts ===")
    print(f"  EXACT:        {exact_count}")
    print(f"  APPROXIMATE:  {approximate_count}")
    print(f"  SPURIOUS:     {spurious_count}")
    print(f"  MISS:         {miss_count}")
    print(f"  UNVERIFIED:   {unverified_count}")

    # Hit rate formula: (EXACT + APPROXIMATE) / (EXACT + APPROXIMATE + SPURIOUS + MISS)
    # Exclude UNVERIFIED from denominator
    numerator = exact_count + approximate_count
    denominator = exact_count + approximate_count + spurious_count + miss_count

    if denominator > 0:
        hit_rate = numerator / denominator
    else:
        hit_rate = None  # No verified predictions to compute from

    print(f"\n=== Hit Rate Calculation ===")
    print(f"  Numerator (EXACT + APPROXIMATE): {exact_count} + {approximate_count} = {numerator}")
    print(f"  Denominator (excl. UNVERIFIED):  {exact_count} + {approximate_count} + {spurious_count} + {miss_count} = {denominator}")
    if hit_rate is not None:
        print(f"  Hit Rate: {numerator}/{denominator} = {hit_rate:.4f} ({hit_rate*100:.1f}%)")
    else:
        print(f"  Hit Rate: UNDEFINED (denominator is 0)")

    # ── Critical audit notes ───────────────────────────────────────────
    self_ref_count = sum(1 for r in audit_rows if r["self_referential_flag"])
    notes = []

    notes.append(
        f"SELF-REFERENTIAL WARNING: All {self_ref_count} 'verified' predictions "
        f"were verified by Aletheia herself during the same pipeline run that "
        f"generated them. No external human expert, Gemini cross-check, or "
        f"independent tool confirmed these results. The verified_as names "
        f"(Newton-Raphson, PGM, weak measurement, Stirling cycles, Mostow "
        f"rigidity) are real techniques and the mappings appear correct, but "
        f"the verification process was NOT independent."
    )

    notes.append(
        f"UNVERIFIED BULK: {unverified_count} of 35 predictions ({unverified_count/35*100:.0f}%) "
        f"have status='PREDICTED' with no verification attempted. These are "
        f"archaeological predictions ranked by tensor score but never checked."
    )

    if denominator > 0 and hit_rate == 1.0:
        notes.append(
            "PERFECT SCORE SUSPICION: A 100% hit rate on self-verified "
            "predictions is not meaningful. The 5/5 'verified' predictions "
            "were cherry-picked (highest tensor scores from tensor_consensus_prediction) "
            "and verified by the same agent. True hit rate requires external validation."
        )

    for n in notes:
        print(f"\n  NOTE: {n}")

    # ── Step 4: Save output ────────────────────────────────────────────
    output = {
        "audit_metadata": {
            "auditor": "Aletheia",
            "timestamp": datetime.now().isoformat(),
            "database": DB_PATH,
            "total_predictions": len(rows),
            "sql_all_rows": sql_all.strip(),
            "sql_status_counts": sql_status_counts.strip(),
        },
        "classification_counts": {
            "EXACT": exact_count,
            "APPROXIMATE": approximate_count,
            "SPURIOUS": spurious_count,
            "MISS": miss_count,
            "UNVERIFIED": unverified_count,
        },
        "hit_rate": {
            "numerator": numerator,
            "denominator": denominator,
            "rate": hit_rate,
            "formula": "(EXACT + APPROXIMATE) / (EXACT + APPROXIMATE + SPURIOUS + MISS)",
            "note": "UNVERIFIED excluded from denominator",
        },
        "audit_notes": notes,
        "predictions": audit_rows,
    }

    Path(OUTPUT_PATH).parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        json.dump(output, f, indent=2, ensure_ascii=False)

    print(f"\nSaved audit trail to {OUTPUT_PATH}")
    con.close()


if __name__ == "__main__":
    main()
