"""BETA-03 (C-011): THE COMPOSITION FRONTIER -- coordinator runner (supply + E1). Directive:
prompts/2026-10-08_beta03/01_OPERATOR_DIRECTIVE_verbatim.md. Pre-registrations: beta03/windows/*_PREREG.md.

Reuses the Beta-02 machinery (b02.py, unchanged) by pointing its supply paths at Beta-03 blocks:
  A = W8 LIN 72-95   (E1 donors; E2/g12 confirmation seeds)
  B = W8 LIN 96-119  (E1 recipients; unseen lineages; pair d <-> d + 24)
Supply file: science/arc3/w8_lin_generator/W8_SUPPLIES_B03.json (new; generated by the unchanged w8_lin.py).

E1 (R8 saturation vs interference; beta03/windows/E1_PREREG.md):
  e1 donors   A-block donors g11@O10 (-> L_g11) and I_0@O4 (-> L_I0)
  e1 freeze   entries-only libraries + sha256 (L_g11, L_I0, L_P = pristine)
  e1 starts   walk the three START libraries on B transfer cells; build the COMMON RESIDUAL set mechanically
              (families no start reaches in either cell) BEFORE any recipient runs; hash it
  e1 recip    recipients on B: library x machinery g11@O10 (the only machinery; budget)
  e1 score    walk recipient selections on B transfer cells
  e1 report   frozen rules (E1_PREREG s5)
Stages: supply {A|B} [w] | known | e1 {donors|freeze|starts|recip|score|report} [w]
"""
import os
os.environ.setdefault("V2B_T51_DIR", "T04_T51")
import json  # noqa: E402
import re  # noqa: E402
import statistics  # noqa: E402
import sys  # noqa: E402
from collections import defaultdict  # noqa: E402

import b02  # noqa: E402

R = b02.R
ROOT = R.RUNS.parent.parent
B03 = ROOT / "beta03" / "runs"
E1D = B03 / "E1"
b02.SUPPLY_FILE = b02.W8 / "W8_SUPPLIES_B03.json"
b02.SUP = B03 / "SUPPLY"
b02.BLOCKS = {"A": list(range(72, 96)), "B": list(range(96, 120))}
LIBS = ["L_g11", "L_I0", "L_P"]
MACH = ("g11", "O10")
PC_MIN_FAMILIES, PC_MIN_PAIRS = 5, 3
MIN_PAIRS = 18
log, wj, rj, sha = b02.log, b02.wj, b02.rj, b02.sha


def _ok(r):
    return bool(r) and not r.get("censored", True)


# ------------------------------------------------------------------ E1
def e1_donors(w=4):
    P = rj(b02.SUP / "PLAN_A.json")
    seeds = [s for s in P["seeds"] if P["plan"][str(s)]["ok"] and P["plan"][str(s)]["extras_ok"]]
    E1D.mkdir(parents=True, exist_ok=True)
    jobs = [("%s_%s" % (r, wd), r, wd, s, P["plan"][str(s)][wd], P["panel"], None)
            for s in seeds for r, wd in (("g11", "O10"), ("g0", "O4"))]
    b02._pool_donors(jobs, E1D / "E1_DONORS.jsonl", w, "E1-donor")


def e1_freeze():
    PA, PB = rj(b02.SUP / "PLAN_A.json"), rj(b02.SUP / "PLAN_B.json")
    D = {(x["seed"], x["tag"]): x for x in R.rdl(E1D / "E1_DONORS.jsonl")}
    usable = lambda P, s: P["plan"].get(str(s), {}).get("ok") and P["plan"][str(s)]["extras_ok"]  # noqa: E731
    pairs = [(d, d + 24) for d in PA["seeds"] if usable(PA, d) and usable(PB, d + 24)
             and (d, "g11_O10") in D and (d, "g0_O4") in D]
    libs = {str(d): {"L_g11": D[(d, "g11_O10")]["selected_entries"], "L_I0": D[(d, "g0_O4")]["selected_entries"],
                     "L_P": R.FR.pristine().entries} for d, _n in pairs}
    rec = {"pairs": pairs, "libraries": libs,
           "sha256": {d: {k: sha(v) for k, v in L.items()} for d, L in libs.items()}}
    wj(E1D / "E1_LIBRARIES.json", rec)
    log("E1 libraries frozen: %d pairs; sha %s" % (len(pairs), sha(rec)[:16]))


def _libs_checked():
    L = rj(E1D / "E1_LIBRARIES.json")
    for d, ls in L["libraries"].items():
        assert all(sha(ls[k]) == L["sha256"][d][k] for k in ls), "library hash mismatch"
    return L


def e1_starts(w=4):
    L = _libs_checked()
    PB = rj(b02.SUP / "PLAN_B.json")
    libs, index, todo = {}, [], {}
    for d, n in L["pairs"]:
        for lb in LIBS:
            k = b02._key(L["libraries"][str(d)][lb], libs)
            for f in b02._tr(PB["plan"][str(n)], n):
                for ci in range(2):
                    index.append({"seed": n, "genome": "START|" + lb, "family": f["name"], "cell": ci, "lib": k})
                    todo.setdefault((k, f["name"], ci), (k, libs[k], f, ci))
    wj(E1D / "E1_START_INDEX.json", {"index": index})
    b02._pool_walks(list(todo.values()), E1D / "E1_START_WALKS.jsonl", w, "E1-start")
    W = {(x["lib"], x["family"], x["cell"]): x["result"] for x in R.rdl(E1D / "E1_START_WALKS.jsonl")}
    reach = defaultdict(bool)
    for e in index:
        reach[(e["genome"], e["seed"], e["family"])] |= _ok(W.get((e["lib"], e["family"], e["cell"])))
    common = {}
    for d, n in L["pairs"]:
        fams = sorted({f["name"] for f in b02._tr(PB["plan"][str(n)], n)})
        common[str(n)] = [f for f in fams if not any(reach[("START|" + lb, n, f)] for lb in LIBS)]
    rec = {"rule": "families of the recipient's 32 TRANSFER families that NO start library (L_g11, L_I0, L_P) reaches "
                   "in either cell at cap 1M; computed from start walks only, before any recipient runs",
           "common_residual": common}
    rec["sha256"] = sha(rec)
    wj(E1D / "E1_COMMON_RESIDUAL.json", rec)
    log("E1 common residual: %d slots of %d; sha %s" % (sum(len(v) for v in common.values()),
                                                       32 * len(L["pairs"]), rec["sha256"][:16]))


def e1_recip(w=4):
    L = _libs_checked()
    assert (E1D / "E1_COMMON_RESIDUAL.json").exists(), "common residual must be frozen before recipients"
    PB = rj(b02.SUP / "PLAN_B.json")
    r, wd = MACH
    jobs = [("%s|%s_%s" % (lb, r, wd), r, wd, n, PB["plan"][str(n)][wd], PB["panel"], L["libraries"][str(d)][lb])
            for d, n in L["pairs"] for lb in LIBS]
    b02._pool_donors(jobs, E1D / "E1_RECIP.jsonl", w, "E1-recip")


def e1_score(w=4):
    L = _libs_checked()
    PB = rj(b02.SUP / "PLAN_B.json")
    libs, index, todo = {}, [], {}
    for x in R.rdl(E1D / "E1_RECIP.jsonl"):
        n = x["seed"]
        k = b02._key(x["selected_entries"], libs)
        for f in b02._tr(PB["plan"][str(n)], n):
            for ci in range(2):
                index.append({"seed": n, "genome": x["tag"], "family": f["name"], "cell": ci, "lib": k,
                              "start": "START|" + x["tag"].split("|")[0]})
                todo.setdefault((k, f["name"], ci), (k, libs[k], f, ci))
    wj(E1D / "E1_RECIP_INDEX.json", {"index": index})
    have = {(x["lib"], x["family"], x["cell"]) for x in R.rdl(E1D / "E1_START_WALKS.jsonl")}
    b02._pool_walks([v for kk, v in todo.items() if kk not in have], E1D / "E1_RECIP_WALKS.jsonl", w, "E1-recip")


def composes_on(inherited, selected):
    """True iff selected == inherited[H := x] for some x that itself contains the hole {H} (a strict extension)."""
    if not inherited or not selected or "{H}" not in inherited:
        return False
    pat = re.escape(inherited).replace(re.escape("{H}"), "(.+)")
    m = re.fullmatch(pat, selected)
    return bool(m) and "{H}" in m.group(1) and m.group(1) != "{H}"


def e1_report():
    """Frozen rules: beta03/windows/E1_PREREG.md s5."""
    L = _libs_checked()
    known = rj(B03 / "KNOWN.json")
    C = rj(E1D / "E1_COMMON_RESIDUAL.json")
    pairs = L["pairs"]
    seeds = [n for _d, n in pairs]
    idx = rj(E1D / "E1_START_INDEX.json")["index"] + rj(E1D / "E1_RECIP_INDEX.json")["index"]
    W = {}
    for p in (E1D / "E1_START_WALKS.jsonl", E1D / "E1_RECIP_WALKS.jsonl"):
        for x in R.rdl(p):
            W[(x["lib"], x["family"], x["cell"])] = x["result"]
    reach, charge = defaultdict(bool), {}
    for e in idx:
        res = W.get((e["lib"], e["family"], e["cell"]))
        k = (e["genome"], e["seed"], e["family"])
        reach[k] |= _ok(res)
        if _ok(res):
            charge[k] = min(charge.get(k, 10 ** 9), res["charge"])
    tags = ["%s|%s_%s" % (lb, *MACH) for lb in LIBS]
    starts = ["START|" + lb for lb in LIBS]
    fams = defaultdict(set)
    for e in idx:
        fams[e["seed"]].add(e["family"])
    acq_common = {t: {n: sum(reach[(t, n, f)] for f in C["common_residual"][str(n)]) for n in seeds} for t in tags}
    own = b02._gains(idx, W, lambda e: e.get("start", e["genome"]), tags, seeds)       # Beta-02 own-start measure
    inh = b02._gains([dict(e) for e in idx], W, lambda e: "START|L_P", starts, seeds)  # inherited capability vs pristine
    end = {t: {n: sum(reach[(t, n, f)] or reach[("START|" + t.split("|")[0], n, f)] for f in fams[n]) for n in seeds}
           for t in tags}
    D = {(x["seed"], x["tag"]): x for x in R.rdl(E1D / "E1_RECIP.jsonl")}
    DD = {(x["seed"], x["tag"]): x for x in R.rdl(E1D / "E1_DONORS.jsonl")}
    # candidate-ordering effect: families reached by BOTH the L_g11 and L_P recipients -> paired log charge ratio
    ratios = []
    for n in seeds:
        for f in fams[n]:
            a, b = charge.get(("L_g11|g11_O10", n, f)), charge.get(("L_P|g11_O10", n, f))
            if a and b:
                ratios.append(a / b)
    # compositional extensions of the inherited schema by L_g11 recipients
    comp = []
    for d, n in pairs:
        inh_schema = (L["libraries"][str(d)]["L_g11"][0].get("schema") if L["libraries"][str(d)]["L_g11"] else None)
        sel = D[(n, "L_g11|g11_O10")]["selected_schema"]
        if composes_on(inh_schema, sel):
            comp.append({"pair": [d, n], "inherited": inh_schema, "selected": sel,
                         "acq_common": acq_common["L_g11|g11_O10"][n]})
    c = lambda a, b, M: [M[a][n] - M[b][n] for n in seeds]  # noqa: E731
    I1 = b02.flip_test(c("L_g11|g11_O10", "L_P|g11_O10", acq_common))       # interference (two-sided)
    S1 = b02.flip_test(c("L_g11|g11_O10", "L_P|g11_O10", own))              # own-start deficit (one-sided, < 0)
    EN = b02.flip_test(c("L_g11|g11_O10", "L_P|g11_O10", acq_common))       # enabling (one-sided, > 0)
    S1_p_neg = b02.flip_test([-x for x in S1["diffs"]])["p_one_sided"]
    share = 1.0 if I1["sum"] >= 0 or S1["sum"] >= 0 else 1 - (I1["sum"] / S1["sum"])
    pc_fams = sum(acq_common["L_g11|g11_O10"].values())
    pc_pairs = sum(1 for n in seeds if acq_common["L_g11|g11_O10"][n] > 0)
    pc = pc_fams >= PC_MIN_FAMILIES and pc_pairs >= PC_MIN_PAIRS
    common_slots = sum(len(C["common_residual"][str(n)]) for n in seeds)
    best_frac = max(sum(acq_common[t].values()) for t in tags) / common_slots if common_slots else 0.0
    supply_ok = len(pairs) >= MIN_PAIRS
    labels = {
        "INTERFERENCE_SUPPORTED": pc and I1["p_two_sided"] < 0.05 and I1["sum"] < 0,
        "SATURATION_SUPPORTED": S1_p_neg < 0.05 and S1["sum"] < 0 and share >= 0.5,
        "REPRESENTATION_CEILING_SUPPORTED": pc and not (EN["p_one_sided"] < 0.05 and EN["sum"] > 0)
        and best_frac < 0.25 and not any(x["acq_common"] > 0 for x in comp)}
    if not any(labels.values()):
        labels["INCONCLUSIVE"] = True
    holm = b02.holm([I1["p_two_sided"], S1_p_neg])
    disp = ("SUPPLY_LIMITED" if not supply_ok else ("MEASURED" if known["pass"] and pc
                                                     else ("INCONCLUSIVE_NO_POSITIVE_CONTROL" if known["pass"]
                                                           else "MEASUREMENT_FAILED")))
    tot = lambda M: {k: sum(v.values()) for k, v in M.items()}  # noqa: E731
    res = {"pairs": pairs, "n_pairs": len(pairs), "common_residual_slots": common_slots,
           "positive_control": {"families": pc_fams, "pairs": pc_pairs, "pass": pc},
           "A_inherited_capability_vs_pristine": tot(inh), "B_common_residual_slots_per_pair":
               {n: len(C["common_residual"][str(n)]) for n in seeds},
           "C_new_acquisition_common": tot(acq_common), "C_new_acquisition_common_per_pair": acq_common,
           "own_start_improvement_secondary": tot(own), "D_end_state_reach": tot(end),
           "E_interference_test_L_g11_vs_L_P_common": I1, "saturation_own_start_L_g11_vs_L_P": S1,
           "saturation_own_start_p_one_sided_negative": S1_p_neg, "headroom_share_of_deficit": round(share, 4),
           "enabling_test_L_g11_vs_L_P_common": EN, "holm_reject_[interference,saturation]": holm,
           "failed_opportunities": {t: common_slots - sum(acq_common[t].values()) for t in tags},
           "best_arm_fraction_of_common_acquired": round(best_frac, 4),
           "ordering_charge_ratio_L_g11_over_L_P": {"n": len(ratios), "median": statistics.median(ratios)
                                                     if ratios else None},
           "compositional_extensions_of_inherited": comp,
           "semantic_classes": {t: {"n_derived_median": statistics.median([D[(n, t)]["n_derived"] for n in seeds]),
                                    "classes_median": statistics.median([D[(n, t)]["classes"] for n in seeds])}
                                for t in tags},
           "donor_memorise_selected": {k: sum(1 for (s, tg), x in DD.items() if tg == k and x["memorise_selected"])
                                       for k in ("g11_O10", "g0_O4")},
           "labels": labels, "known": known, "disposition": disp}
    wj(E1D / "E1_RESULT.json", res)
    log("E1 %s labels %s PC %s I1 %s/%s/%s p2 %s share %s" % (disp, labels, pc, I1["better"], I1["worse"], I1["tied"],
                                                             I1["p_two_sided"], round(share, 3)))
    return res


def stage_known():
    """Outcome-free known answers for the Beta-03 runner (K1-K3)."""
    import itertools  # noqa: F401
    res = {}
    # K1: b03 path (patched supply paths) still reproduces Beta-02 E12 donor rows (seed 25 g11_O10 and g0_O4)
    PE = rj(ROOT / "beta02" / "runs" / "SUPPLY" / "PLAN_E.json")
    E12 = {(x["seed"], x["tag"]): x for x in R.rdl(ROOT / "beta02" / "runs" / "E12" / "E12_DONORS.jsonl")}
    keys = ("selected_schema", "selected_origin", "selected_entries", "n_observed", "n_derived", "classes")
    from concurrent.futures import ProcessPoolExecutor
    jobs = [("%s_%s" % (r, wd), r, wd, 25, PE["plan"]["25"][wd], PE["panel"], None) for r, wd in (("g11", "O10"), ("g0", "O4"))]
    with ProcessPoolExecutor(max_workers=1, initializer=R.T.init_worker) as ex:
        out = list(ex.map(b02._donor, jobs))
    res["K1_reproduces_Beta02_E12_seed25"] = all(all(o[k] == E12[(25, o["tag"])][k] for k in keys) for o in out)
    # K2: the common-residual + acquisition reducer reproduces the W01 diagnostic on frozen Beta-02 R8 data
    diag = rj(B03 / "W01_R8_COMMON_RESIDUAL_DIAG.json")
    res["K2_W01_diag_present_and_totals"] = diag["summary"]["common_residual_slots"] == 301
    # K3: composes_on unit cases
    res["K3_composes_on"] = (composes_on("(acc + {H})", "(acc + ({H} * v))") and
                             not composes_on("(acc + {H})", "(acc + {H})") and
                             not composes_on("(acc + {H})", "(acc - {H})") and
                             composes_on("({H} + v)", "((acc * {H}) + v)"))
    res["pass"] = all(v for v in res.values())
    wj(B03 / "KNOWN.json", res)
    log("known %s" % res)
    return res


if __name__ == "__main__":
    a = sys.argv[1:]
    w = int(a[-1]) if a and a[-1].isdigit() else 4
    if a[0] == "supply":
        b02.stage_supply(a[1], w)
    elif a[0] == "known":
        stage_known()
    elif a[0] == "e1":
        {"donors": lambda: e1_donors(w), "freeze": e1_freeze, "starts": lambda: e1_starts(w),
         "recip": lambda: e1_recip(w), "score": lambda: e1_score(w), "report": e1_report}[a[1]]()
    else:
        raise SystemExit("unknown stage")
