"""TEST-4 (Beta-01): T51 -- NATURAL-RECURRENCE DONOR STAGE (TH-019). Frozen spec: beta01/windows/T04_T51_SPEC.md.

Lineage-generated supply (W8 CG-1 LIN, seeds 0-7, 144 families each; regenerated byte-for-byte = W8 F1) replaces
constructed recurrence. The estimand is a POOLED dose relationship (W8 F4, W1 WP-2): across seeds x panel
schemas S, does reuse of the inherited schema's selected library rise with the natural recurrence dose X_S (W8
genuine COND_8)? G1 is one point in the pool, never the hypothesis.

Pipeline (escrow 30k everywhere inside the engine: a declared change from A19/A23's 250k, required by W8 F5/F6):
  foundry   a18_c1.qualify_family (Q2 + T4 v1 + PRISTINE/L1 pilots at 30k) for all 8 x 144 families
  roles     A19 NAT rule (seeded per seed): OBSERVE 4 (0 < p_PRISTINE <= .75), VALIDATE 4 (p <= .75),
            TRANSFER 32 (p <= .75; W1 WP-3 breadth)
  donors    a18_c1._donor_job, unchanged, for arms G1, PA, PB, PC, PD (held = arm, composition ON), P, G1_NC
  transfer  v2b D endpoint: walk.first_qualified at cap 1,000,000, tribunal T4 v1a; libraries SEL_<arm>,
            START_<held>, PRISTINE; 2 cells per TRANSFER family
Stages: plan | foundry [w] | roles | donors [w] | transfer [w] | report.
"""
import os
import json
import math
import random
import sys
import time
from collections import defaultdict
from concurrent.futures import ProcessPoolExecutor

os.environ["A18_TAG"] = "T51"
import paths  # noqa: E402
import a17  # noqa: E402
import fair  # noqa: E402

ESC = 30_000
a17.ESCROW = ESC
fair.ESCROW = ESC
import a18  # noqa: E402
import a18_c1 as C  # noqa: E402
from a18 import FR  # noqa: E402
import identity as I  # noqa: E402

import apparatus  # noqa: E402
import instruments as INS  # noqa: E402
import supply as SUP  # noqa: E402
import walk  # noqa: E402

W8 = paths.ROOT / "science" / "arc3" / "w8_lin_generator"
OUTDIR = paths.ROOT / "beta01" / "runs" / os.environ.get("V2B_T51_DIR", "T04_T51")
SEEDS = [int(x) for x in os.environ.get("V2B_T51_SEEDS", "0,1,2,3,4,5,6,7").split(",")]
PANEL_KEYS = ["G1", "PA", "PB", "PC", "PD"]
ARMS = os.environ.get("V2B_T51_ARMS", ",".join(PANEL_KEYS + ["P", "G1_NC"])).split(",")
HELD = dict({k: k for k in PANEL_KEYS}, P="P", G1_NC="G1")
COMPOSE = dict({k: True for k in PANEL_KEYS}, P=True, G1_NC=False)
CAP = int(os.environ.get("V2B_T51_CAP", 1_000_000))
TCELLS = 2
N_OBS, N_VAL, N_TR = 4, 4, int(os.environ.get("V2B_T51_NTR", 32))


def init_worker():
    a17.ESCROW = ESC
    fair.ESCROW = ESC
    a18.worker_init()
    a18.use_world("W5")


def log(m):
    print("[T51 %s] %s" % (time.strftime("%H:%M:%S", time.gmtime()), m), flush=True)


def wr(name, obj):
    OUTDIR.mkdir(parents=True, exist_ok=True)
    (OUTDIR / name).write_text(json.dumps(obj, sort_keys=True, default=str), encoding="utf-8")


def rd(name):
    return json.loads((OUTDIR / name).read_text(encoding="utf-8"))


def rdl(name):
    p = OUTDIR / name
    return [json.loads(x) for x in p.read_text(encoding="utf-8").splitlines() if x.strip()] if p.exists() else []


def panel():
    res = json.loads((W8 / "W8_RESULTS.json").read_text(encoding="utf-8"))
    pn = {"G1": a18.G1}
    for k in ("PA", "PB", "PC", "PD"):
        pn[k] = res["panel"][k]["schema"]
    return pn


def stage_plan():
    init_worker()
    sup = json.loads((W8 / "W8_SUPPLIES.json").read_text(encoding="utf-8"))
    res = json.loads((W8 / "W8_RESULTS.json").read_text(encoding="utf-8"))
    draws = []
    for s in SEEDS:
        for name, init, body, final in sup["LIN:%d" % s]["families"]:
            draws.append((name, body, init, final, "LIN:%d" % s))
    xs = {"LIN:%d|%s" % (s, k): res["per_seed"]["LIN:%d" % s]["X_genuine"][k]["COND"] for s in SEEDS for k in PANEL_KEYS}
    plan = {"escrow": ESC, "cap": CAP, "seeds": SEEDS, "panel": panel(), "draws": draws, "X_S": xs,
            "apparatus": apparatus.manifest("v1a", "v2.1"), "w8_supplies_sha": C.sha(draws)}
    wr("T51_PLAN.json", plan)
    log("plan: %d families, X_S range %.3f..%.3f" % (len(draws), min(xs.values()), max(xs.values())))


def _qual(d):
    init_worker()
    return C.qualify_family(d)


def stage_foundry(workers=4):
    plan = rd("T51_PLAN.json")
    done = {x["name"] for x in rdl("T51_FOUNDRY.jsonl")}
    todo = [tuple(d) for d in plan["draws"] if d[0] not in done]
    log("foundry todo %d" % len(todo))
    with open(OUTDIR / "T51_FOUNDRY.jsonl", "a", encoding="utf-8") as fh, \
            ProcessPoolExecutor(max_workers=workers, initializer=init_worker) as ex:
        for i, row in enumerate(ex.map(_qual, todo, chunksize=4)):
            fh.write(json.dumps(row, sort_keys=True, default=str) + "\n")
            fh.flush()
            if i % 100 == 0:
                log("foundry %d/%d" % (i, len(todo)))


def assign(rows, seed):
    rng = random.Random(I._seed("APHRODITE/T51/ROLES/%d" % seed))
    q = sorted([r for r in rows if r.get("T4_qualified") and r["source"] == "LIN:%d" % seed], key=lambda r: r["name"])
    head = [r for r in q if r.get("p_PRISTINE", 0) <= 0.75]
    floor = [r for r in head if r.get("p_PRISTINE", 0) > 0]
    used, fams, ok = set(), [], True

    def take(pool_, k, role):
        nonlocal ok
        c = [r for r in pool_ if r["name"] not in used]
        rng.shuffle(c)
        if len(c) < k:
            ok = False
        for r in c[:k]:
            used.add(r["name"])
            fams.append(dict(r, role=role, qualified_dev_size=r["Q2_size"]))
    take(floor, N_OBS, "OBSERVE")
    take(head, N_VAL, "VALIDATE")
    take(head, N_TR, "TRANSFER")
    return fams, ok


def stage_roles():
    rows = rdl("T51_FOUNDRY.jsonl")
    roles = {}
    for s in SEEDS:
        fams, ok = assign(rows, s)
        roles["LIN:%d" % s] = {"ok": ok, "families": [{k: f[k] for k in ("name", "role", "body", "init", "final",
                                                                         "Q2_size", "p_PRISTINE")} for f in fams]}
    receipt = SUP.screen("T51", [r for r in rows if r.get("T4_qualified")],
                         lambda _rows, i: (None, roles["LIN:%d" % SEEDS[i]]["ok"]), len(SEEDS), max(1, math.ceil(0.75 * len(SEEDS))))
    roles["_supply"] = receipt.as_dict()
    wr("T51_ROLES.json", roles)
    log("roles: fillable %d/%d (quota 6) -> %s" % (receipt.replicates_fillable, len(SEEDS),
                                                   "OK" if receipt.passed else "SUPPLY_LIMITED"))


def _donor(a):
    init_worker()
    seed, arm, fams, pn = a
    specs = {f["name"]: (f["body"], f["final"], f["init"]) for f in fams}
    fl = [dict(f, qualified_dev_size=f["Q2_size"]) for f in fams]
    d = C._donor_job(("LIN%d" % seed, HELD[arm], seed, fl, specs, pn, COMPOSE[arm], arm))
    return d


def stage_donors(workers=4):
    plan, roles = rd("T51_PLAN.json"), rd("T51_ROLES.json")
    if not roles["_supply"]["passed"]:
        log("SUPPLY_LIMITED: donors not run")
        return
    done = {(x["catalog"], x["arm"]) for x in rdl("T51_DONORS.jsonl")}
    jobs = [(s, arm, roles["LIN:%d" % s]["families"], plan["panel"]) for s in SEEDS if roles["LIN:%d" % s]["ok"]
            for arm in ARMS if ("LIN%d" % s, arm) not in done]
    log("donor jobs %d" % len(jobs))
    with open(OUTDIR / "T51_DONORS.jsonl", "a", encoding="utf-8") as fh, \
            ProcessPoolExecutor(max_workers=workers, initializer=init_worker) as ex:
        for d in ex.map(_donor, jobs):
            fh.write(json.dumps(d, sort_keys=True, default=str) + "\n")
            fh.flush()
            log("donor %s %-6s sel=%s COMP=%s %ss" % (d["catalog"], d["arm"], d["selected_schema"], d["COMPOSES_held"],
                                                    d["seconds"]))


def _walk(a):
    init_worker()
    key, entries, fam, cell = a
    prov = a17.Prov({fam["name"]: (fam["body"], fam["final"], fam["init"])})
    a17.M.use_provider(prov)
    c = FR.Cell(prov, fam["name"], cell, fam["Q2_size"], label="T51-%s-rx" % fam["seed"])
    try:
        r = walk.first_qualified(FR.KLib(entries), c, CAP, INS.qualifier(prov, fam["name"], "v1a", "BOTH"))
        st = "OK"
    except INS.EvaluatorDisagreement as e:
        r, st = {"error": str(e)}, "EVALUATOR_DISAGREEMENT"
    return {"lib": key, "family": fam["name"], "cell": cell, "status": st, "result": r}


def stage_transfer(workers=4):
    import hashlib
    plan, roles = rd("T51_PLAN.json"), rd("T51_ROLES.json")
    donors = rdl("T51_DONORS.jsonl")
    libs, jobs = {}, []

    def key(entries):
        k = hashlib.sha256(json.dumps(entries, sort_keys=True).encode()).hexdigest()[:16]
        libs.setdefault(k, entries)
        return k
    P = key(FR.pristine().entries)
    index = []
    for d in donors:
        s = int(d["catalog"][3:])
        fams = [dict(f, seed="LIN%d" % s) for f in roles["LIN:%d" % s]["families"] if f["role"] == "TRANSFER"]
        start = a18.start_library(HELD[d["arm"]], plan["panel"])[0]
        ks = {"SEL": key(d["selected_entries"]), "START": key(start), "PRISTINE": P}
        for f in fams:
            for i in range(TCELLS):
                for lab, k in ks.items():
                    index.append({"catalog": d["catalog"], "arm": d["arm"], "family": f["name"], "cell": i,
                                  "lib_role": lab, "lib": k})
                    jobs.append((k, f, i))
    wr("T51_TRANSFER_INDEX.json", {"index": index, "libs": libs})
    done = {(x["lib"], x["family"], x["cell"]) for x in rdl("T51_WALKS.jsonl")}
    uniq = {}
    for k, f, i in jobs:
        uniq.setdefault((k, f["name"], i), (k, libs[k], f, i))
    todo = [v for kk, v in sorted(uniq.items()) if kk not in done]
    log("unique walks %d todo %d" % (len(uniq), len(todo)))
    with open(OUTDIR / "T51_WALKS.jsonl", "a", encoding="utf-8") as fh, \
            ProcessPoolExecutor(max_workers=workers, initializer=init_worker) as ex:
        for n, r in enumerate(ex.map(_walk, todo, chunksize=2)):
            fh.write(json.dumps(r, sort_keys=True, default=str) + "\n")
            fh.flush()
            if n % 200 == 0:
                log("walks %d/%d" % (n, len(todo)))
    log("transfer done")


def _ols(x, y):
    n = len(x)
    mx, my = sum(x) / n, sum(y) / n
    sxx = sum((a - mx) ** 2 for a in x)
    return (sum((a - mx) * (b - my) for a, b in zip(x, y)) / sxx) if sxx else 0.0, mx, my


def stage_report():
    """Frozen rules: T04_T51_SPEC.md s4."""
    init_worker()
    plan, roles = rd("T51_PLAN.json"), rd("T51_ROLES.json")
    if not roles["_supply"]["passed"]:
        res = {"disposition": "SUPPLY_LIMITED", "supply": roles["_supply"]}
        wr("T51_RESULT.json", res)
        log(res)
        return res
    idx = rd("T51_TRANSFER_INDEX.json")["index"]
    walks = {(w["lib"], w["family"], w["cell"]): w for w in rdl("T51_WALKS.jsonl")}
    tech = [k for k, w in walks.items() if w["status"] != "OK"]
    cell = defaultdict(dict)
    for e in idx:
        w = walks.get((e["lib"], e["family"], e["cell"]))
        if w:
            cell[(e["catalog"], e["arm"], e["family"], e["cell"])][e["lib_role"]] = w["result"]
    fams_of = {}
    for s in SEEDS:
        tr = [f for f in roles["LIN:%d" % s]["families"] if f["role"] == "TRANSFER"]
        fams_of["LIN%d" % s] = SUP.distinct_classes([dict(f) for f in tr])
    per = defaultdict(lambda: {"reused_classes": 0, "solved_any": 0})
    for cat, classes in fams_of.items():
        for arm in ARMS:
            k = 0
            for cl in classes:
                hit = False
                for f in cl:
                    for ci in range(TCELLS):
                        x = cell.get((cat, arm, f["name"], ci), {})
                        sel, st = x.get("SEL"), x.get("START")
                        if sel and st and not sel.get("censored", True) and st.get("censored"):
                            hit = True
                if hit:
                    k += 1
            per[(cat, arm)]["reused_classes"] = k
            per[(cat, arm)]["n_classes"] = len(classes)
    pts = []
    for (cat, arm), v in per.items():
        if arm in PANEL_KEYS:
            pts.append((cat, arm, plan["X_S"]["LIN:%s|%s" % (cat[3:], arm)], v["reused_classes"] / max(1, v["n_classes"])))
    x = [p[2] for p in pts]
    y = [p[3] for p in pts]
    slope, mx, my = _ols(x, y)
    # seed-clustered permutation: shuffle X_S among schemas WITHIN each seed (10,000, seeded)
    rng = random.Random(I._seed("APHRODITE/T51/PERM/v1"))
    by_seed = defaultdict(list)
    for p in pts:
        by_seed[p[0]].append(p)
    ge = 0
    NP = 10000
    for _ in range(NP):
        xx, yy = [], []
        for sd, ps in by_seed.items():
            xs_ = [p[2] for p in ps]
            rng.shuffle(xs_)
            xx += xs_
            yy += [p[3] for p in ps]
        ge += _ols(xx, yy)[0] >= slope
    p_slope = (ge + 1) / (NP + 1)
    # G1 residual above the pooled line
    g1 = [p for p in pts if p[1] == "G1"]
    res_g1 = [p[3] - (my + slope * (p[2] - mx)) for p in g1]
    ctrl = {arm: sum(per[(c, arm)]["reused_classes"] for c in fams_of) for arm in ("P", "G1_NC")}
    on = {arm: sum(per[(c, arm)]["reused_classes"] for c in fams_of) for arm in PANEL_KEYS}
    xr = max(x) - min(x) if x else 0
    if tech:
        disp = "TECHNICAL_FAILURE"
    elif xr < 0.10:
        disp = "UNTESTABLE_NO_DOSE_RANGE"
    elif sum(on.values()) == 0 and sum(ctrl.values()) == 0:
        disp = "MEASURED_NO_REUSE_ANYWHERE"
    else:
        disp = "MEASURED"
    res = {"disposition": disp, "n_points": len(pts), "X_range": xr, "pooled_slope": slope, "p_slope_one_sided": p_slope,
           "G1_residuals": res_g1, "reused_classes_by_arm": on, "controls": ctrl, "per": {"%s|%s" % k: v for k, v in per.items()},
           "points": pts, "technical": tech[:20],
           "readouts": {"NATURAL_DOSE_SLOPE": ("POSITIVE" if (slope > 0 and p_slope < 0.05) else "NOT_SHOWN"),
                        "G1_SPECIFIC": ("YES" if res_g1 and sum(1 for r in res_g1 if r > 0) >= math.ceil(7 / 8 * len(res_g1))
                                        else "NO")}}
    wr("T51_RESULT.json", res)
    log("disposition %s slope %.4f p %.4f on %s ctrl %s" % (disp, slope, p_slope, on, ctrl))
    return res


if __name__ == "__main__":
    st = sys.argv[1]
    w = int(sys.argv[2]) if len(sys.argv) > 2 else 4
    {"plan": stage_plan, "foundry": lambda: stage_foundry(w), "roles": stage_roles, "donors": lambda: stage_donors(w),
     "transfer": lambda: stage_transfer(w), "report": stage_report}[st]()
