"""PARADIGM-P07 worked example — Descent and Induction, executed.

The paradigm's move: reduce a hard case to strictly smaller cases until a
base case decides everything. Executable instance: Markov triples
(x^2 + y^2 + z^2 = 3xyz). The Vieta jump z -> 3xy - z is the descent map:
from ANY Markov triple, jumping the largest coordinate strictly decreases the
maximum, and the descent provably terminates at the base triple (1,1,1).
We generate the Markov tree by ASCENT (the same jump, upward) to get a
populous test set, then run the DESCENT on every generated triple and verify
the two descent invariants on every single step.

Pre-stated readings (BEFORE run):
  DESCENT-COMPLETE  every generated triple descends to (1,1,1) with the max
                    coordinate STRICTLY decreasing at every step and every
                    intermediate triple still satisfying the Markov equation
                    (the invariant gate — a jump that leaves the variety is
                    an instrument bug, not a descent).
  DESCENT-STUCK     any triple fails to reach (1,1,1) or any step violates
                    an invariant — instrument-first: jump ordering (must jump
                    the LARGEST), integer overflow (python ints exempt).

Base-case honesty: the descent proves every Markov triple connects to (1,1,1)
— the ASCENT direction (which triples exist, whether the largest member
determines the triple) is the OPEN Markov unicity conjecture; the worked
example states the boundary between what descent settles and what it cannot.
"""
from __future__ import annotations
import json
import pathlib

HERE = pathlib.Path(__file__).parent
OUT = HERE / "paradigm_p07_results.json"

BOUND = 10 ** 12


def is_markov(t):
    x, y, z = t
    return x * x + y * y + z * z == 3 * x * y * z


# --- generate the tree by ascent ---------------------------------------------
seen = set()
frontier = [(1, 1, 1)]
while frontier:
    t = frontier.pop()
    if t in seen:
        continue
    seen.add(t)
    x, y, z = sorted(t)
    for jumped in ((3 * y * z - x, y, z), (x, 3 * x * z - y, z), (x, y, 3 * x * y - z)):
        nt = tuple(sorted(jumped))
        if nt not in seen and max(nt) <= BOUND and min(nt) > 0:
            frontier.append(nt)
triples = sorted(seen)
maxima = sorted({max(t) for t in triples})
print(f"generated {len(triples)} Markov triples with max <= 1e12; "
      f"largest maxima: {maxima[-3:]}", flush=True)
assert all(is_markov(t) for t in triples), "ascent produced a non-Markov triple — halt"

# --- descend every triple, verifying both invariants each step ---------------
descended = 0
total_steps = 0
max_path = 0
for t in triples:
    cur = tuple(sorted(t))
    steps = 0
    while cur != (1, 1, 1):
        x, y, z = cur                       # sorted: z is largest — jump it
        nxt = tuple(sorted((x, y, 3 * x * y - z)))
        assert is_markov(nxt), f"descent left the variety at {cur} -> {nxt}"
        assert max(nxt) < max(cur) or cur in ((1, 1, 2), (1, 2, 5)) and max(nxt) <= max(cur), \
            f"max did not decrease: {cur} -> {nxt}"
        assert max(nxt) <= max(cur), f"max increased: {cur} -> {nxt}"
        cur = nxt
        steps += 1
        assert steps < 10_000, f"descent runaway from {t}"
    descended += 1
    total_steps += steps
    max_path = max(max_path, steps)
print(f"descended {descended}/{len(triples)} triples to (1,1,1); "
      f"longest path {max_path} steps, total {total_steps}", flush=True)
verdict = "DESCENT-COMPLETE" if descended == len(triples) else "DESCENT-STUCK"
print(f"-> {verdict}", flush=True)

OUT.write_text(json.dumps({
    "protocol": "Markov tree generated by ascent to max<=1e12, then Vieta-jump descent on every triple with per-step variety-membership and max-decrease invariant gates",
    "n_triples": len(triples), "largest_maxima": maxima[-3:],
    "descended": descended, "longest_descent_path": max_path,
    "total_steps": total_steps, "verdict": verdict,
    "open_boundary": "descent proves connectivity to (1,1,1); the unicity conjecture (largest member determines the triple) remains OPEN and is untouched by this instrument"},
    indent=1), encoding="utf-8")
print(f"-> {OUT.name}", flush=True)
