-- Atlas migration 003: controlled vocabulary seed. New terms are added by
-- later migrations (INSERT ... ON CONFLICT DO NOTHING), never by renaming.

INSERT INTO atlas.vocab(domain, term, meaning) VALUES
 ('validity','VALID','the attempt ran as designed and its instruments were qualified by its own controls'),
 ('validity','UNKNOWN','not established from the evidence seen'),
 ('validity','INVALID_ATTEMPT','the source marks the attempt invalid, void or unusable'),
 ('validity','INSTRUMENT_FAILURE','a control/ruler/detector failed; the execution may still be evidence about the instrument'),
 ('validity','PARTIAL_EVIDENCE','ran in part (crash, truncation, missing rows) or evidence only partly visible'),
 ('validity','CONTRADICTORY','sources disagree about what happened'),
 ('validity','SUPERSEDED','a later attempt of record replaces it; it is kept, never overwritten'),

 ('fact_layer','RAN','what executed: budgets, timings, seeds, host, code'),
 ('fact_layer','OBSERVED','what was measured: named measurements, controls, detector firings, descriptors'),
 ('fact_layer','CONCLUDED','what someone concluded: dispositions, mechanism claims, decisions'),

 ('fact_kind','measurement','a named measured value'),
 ('fact_kind','parameter','an input setting'),
 ('fact_kind','metric_summary','a summary statistic over rows'),
 ('fact_kind','control','a positive/negative/cheat control declaration or outcome'),
 ('fact_kind','comparison_group','an arm, treatment/control pairing or population'),
 ('fact_kind','detector_firing','a detector/predicate/gate that fired or did not'),
 ('fact_kind','interval','a confidence interval or reported band'),
 ('fact_kind','anomaly','an anomaly label'),
 ('fact_kind','stasis_status','stasis / escape state of a trajectory'),
 ('fact_kind','world_descriptor','describes the world'),
 ('fact_kind','organism_descriptor','describes the organism / substrate'),
 ('fact_kind','representation_descriptor','describes the representation / genome encoding'),
 ('fact_kind','pressure_descriptor','describes selection pressure'),
 ('fact_kind','population_descriptor','describes a population'),
 ('fact_kind','search_descriptor','describes the mutation/search process'),
 ('fact_kind','ruler_descriptor','describes the ruler / measurement geometry'),
 ('fact_kind','telemetry_availability','which telemetry exists for this execution'),
 ('fact_kind','failure_mode','how it failed'),
 ('fact_kind','instrumentation_defect','a defect in an instrument'),
 ('fact_kind','mechanism_claim','a claimed mechanism'),
 ('fact_kind','contradiction','an observation that contradicts another'),
 ('fact_kind','open_question','a question left open'),
 ('fact_kind','followup_proposal','a proposed next experiment or intervention'),
 ('fact_kind','campaign_decision','a decision recorded by the driver'),
 ('fact_kind','budget','resources used or reserved'),
 ('fact_kind','timing','wall/CPU time'),
 ('fact_kind','prediction','a preregistered prediction'),
 ('fact_kind','condition','a preregistered kill/falsification/replacement condition'),

 ('fact_status','REPORTED','as the source states it'),
 ('fact_status','UNKNOWN','the source names it without a value'),
 ('fact_status','CONTRADICTORY','another fact on the same subject+name disagrees'),
 ('fact_status','PARTIAL_EVIDENCE','value present but its evidence incomplete'),
 ('fact_status','UNRESOLVED','open by the source''s own account'),
 ('fact_status','SUPERSEDED_INTERPRETATION','a later statement replaced this reading; kept'),

 ('lineage_kind','EXECUTION','attempts, reruns, resumes, continuations of the same specification'),
 ('lineage_kind','SCIENTIFIC','ideas: descendants, deformations, transplants, overturnings'),
 ('lineage_kind','ORGANISM','organism / genome ancestry'),
 ('lineage_kind','PROVENANCE','defects, sources, decisions affecting an entity'),

 ('edge_relation','RERUN_OF','a new attempt of the same specification'),
 ('edge_relation','RESUMED_FROM','an attempt that continued another attempt''s state'),
 ('edge_relation','CONTINUATION_OF','continues an experiment or trajectory'),
 ('edge_relation','DESCENDANT_OF','a changed specification derived from the parent'),
 ('edge_relation','DEFORMATION_OF','a deliberate variant along a named axis'),
 ('edge_relation','REPLICATION_OF','replicates the parent'),
 ('edge_relation','TRANSPLANT_OF','the parent''s question moved to another world/substrate/engine'),
 ('edge_relation','SUPERSEDES','replaces the parent (the parent is kept)'),
 ('edge_relation','AMENDS','amends the parent'),
 ('edge_relation','TESTS','an experiment testing an idea'),
 ('edge_relation','ORIGINATES_FROM','an idea that originated in an experiment/observation'),
 ('edge_relation','CO_PARENT','a secondary parent'),
 ('edge_relation','AFFECTED_BY','an entity affected by a defect'),
 ('edge_relation','EXPLAINS','an observation offered as the explanation of another'),
 ('edge_relation','CONTRADICTS','disagrees with'),
 ('edge_relation','SAME_MEASUREMENT_AS','ATLAS_DERIVED: the same quantity under another name'),
 ('edge_relation','CALIBRATION_CANDIDATE_FOR','ATLAS_DERIVED: a historical control usable as a calibration specimen'),

 ('edge_reason','BUG_FIX',NULL),('edge_reason','INSTRUMENTATION_REPAIR',NULL),('edge_reason','MORE_TELEMETRY',NULL),
 ('edge_reason','SEED_EXPANSION',NULL),('edge_reason','PARAMETER_DEFORMATION',NULL),('edge_reason','WORLD_DEFORMATION',NULL),
 ('edge_reason','ORGANISM_DEFORMATION',NULL),('edge_reason','PRESSURE_DEFORMATION',NULL),('edge_reason','REPRESENTATION_CHANGE',NULL),
 ('edge_reason','CONTROL_REPAIR',NULL),('edge_reason','RULER_REPAIR',NULL),('edge_reason','REPLICATION',NULL),
 ('edge_reason','CONTINUATION',NULL),('edge_reason','CROSS_SUBSTRATE_TRANSPLANT',NULL),('edge_reason','STASIS_ESCAPE',NULL),
 ('edge_reason','INVALID_RERUN',NULL),('edge_reason','DECLARED_PARENT','the source names the parent without a reason'),
 ('edge_reason','UNKNOWN',NULL),

 ('basis','DECLARED','a field in the source states the relation'),
 ('basis','INFERRED','deduced by a named rule from names, times or paths; confidence stated'),
 ('basis','ATLAS_DERIVED','computed by an Atlas query/method; method + version recorded'),

 ('confidence','HIGH',NULL),('confidence','MEDIUM',NULL),('confidence','LOW',NULL),

 ('visibility','GIT_REMOTE','in a commit reachable from a remote ref: visible from any host after a fetch'),
 ('visibility','GIT_LOCAL','in a commit only on a host-local branch'),
 ('visibility','FS','a file on one host''s filesystem'),
 ('visibility','PG','rows in the M1 Postgres cluster'),
 ('visibility','EXPECTED','referenced by another source on a host Atlas has not inspected; NOT evidence of absence'),

 ('signal_kind','WEAK_SIGNAL','effect at/under its own threshold, or claim ceiling says weak'),
 ('signal_kind','REPEATED_WEAK_EFFECT','weak effects recurring across unrelated experiments'),
 ('signal_kind','SIGN_REVERSAL','the same named quantity changes sign across experiments'),
 ('signal_kind','CONCLUSION_CHANGED','a rerun/attempt after a fix carries a different disposition'),
 ('signal_kind','NULL_WITH_TELEMETRY','a null/negative with rich secondary measurements'),
 ('signal_kind','UNRESOLVED_QUESTION','an open question/defect with no closing evidence'),
 ('signal_kind','RARELY_CROSSED','a world x organism x pressure combination tried once or never'),
 ('signal_kind','VISITED_ONCE','a parameter region visited in one experiment only'),
 ('signal_kind','CALIBRATION_SPECIMEN','a historical control reusable as a calibration specimen'),
 ('signal_kind','RECURRING_MEASUREMENT','a measurement name recurring across campaigns/engines'),
 ('signal_kind','CROSS_ENGINE_LINEAGE','a scientific lineage spanning engines'),
 ('signal_kind','INSTRUMENT_FAILURE_CLUSTER','repeated detector/ruler failures of one class'),
 ('signal_kind','RERUN_OPPORTUNITY','an experiment whose re-execution under a changed axis is cheap and informative'),
 ('signal_kind','DATA_GAP','evidence referenced but not visible from any inspected host')
ON CONFLICT DO NOTHING;
