"""WP-C1 tests C1-a .. C1-d, plus purity and drift checks.

The oracle in C1-a is a SECOND, deliberately naive implementation written
from the convention text rather than from `core.py`. It uses plain Python
loops and no numpy, so a shared vectorisation mistake cannot hide in both.
"""
from __future__ import annotations

import json
import os
import subprocess
import sys

import numpy as np
import pytest

from herakles import evca
from herakles.evca import genomes as G

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__),
                                    "..", "..", ".."))


# ---------------------------------------------------------------------------
# The independent oracle. Written from the convention, not from core.py.
# ---------------------------------------------------------------------------

def oracle_index(cells, i):
    """Neighbourhood index of cell i, leftmost neighbour as MSB, ring."""
    n = len(cells)
    idx = 0
    for j, off in enumerate(range(-3, 4)):
        bit = cells[(i + off) % n]
        idx += bit << (6 - j)
    return idx


def oracle_step(cells, table_bits):
    n = len(cells)
    return [table_bits[oracle_index(cells, i)] for i in range(n)]


def oracle_evolve(cells, table_bits, steps):
    cur = list(cells)
    for _ in range(steps):
        cur = oracle_step(cur, table_bits)
    return cur


def oracle_decode(hex_string):
    bits = bin(int(hex_string, 16))[2:].zfill(128)
    return [int(b) for b in bits]


# ---------------------------------------------------------------------------
# C1-a. Hand-computed tiny states, and the oracle on real rules.
# ---------------------------------------------------------------------------

def test_c1a_hand_computed_neighbourhood_index():
    """One state, indices worked out by hand from the pinned bit order."""
    # N = 7, a single 1 at position 3. For cell 3 the neighbourhood is the
    # whole ring, 0001000, so idx = 1 << 3 = 8.
    s = np.array([[0, 0, 0, 1, 0, 0, 0]], dtype=np.uint8)
    idx = evca.neighbourhood_index(s)
    assert idx[0, 3] == 0b0001000 == 8
    # For cell 0 the neighbourhood is cells 4,5,6,0,1,2,3 = 0,0,0,0,0,0,1,
    # so the single 1 sits in the LEAST significant position.
    assert idx[0, 0] == 0b0000001 == 1
    # For cell 6 the neighbourhood is 3,4,5,6,0,1,2 = 1,0,0,0,0,0,0.
    assert idx[0, 6] == 0b1000000 == 64


def test_c1a_uniform_states_have_the_extreme_indices():
    n = 9
    zeros = np.zeros((1, n), dtype=np.uint8)
    ones = np.ones((1, n), dtype=np.uint8)
    assert (evca.neighbourhood_index(zeros) == 0).all()
    assert (evca.neighbourhood_index(ones) == evca.TABLE_BITS - 1).all()


@pytest.mark.parametrize("name", G.NAMES)
def test_c1a_step_matches_the_independent_oracle(name):
    h = G.rule_hex(name)
    table = evca.decode_table(h)
    bits = oracle_decode(h)
    assert list(table) == bits, "decoders disagree before dynamics"
    rng = np.random.default_rng(20260908)
    for n_cells in (7, 9, 15, 21):
        cells = rng.integers(0, 2, size=n_cells).astype(np.uint8)
        got = evca.evolve(cells[None, :], table, 5)[0].tolist()
        want = oracle_evolve(cells.tolist(), bits, 5)
        assert got == want, (name, n_cells)


def test_c1a_msb_convention_is_forced_not_assumed():
    """Re-earn the bit-order convention instead of trusting the record.

    `maj` and `GKL` are derivable from their definitions. Under the pinned
    order both reproduce the published hex in all 32 digits; under the
    reversed order neither does. The convention is therefore identified by
    the data, not chosen.
    """
    assert evca.encode_table(evca.majority_rule_table()) == G.rule_hex("maj")
    assert evca.encode_table(evca.gkl_rule_table()) == G.rule_hex("GKL")
    # the mirrored convention must NOT also fit, or the test proves nothing
    flipped = evca.reflect_table(evca.gkl_rule_table())
    assert evca.encode_table(flipped) != G.rule_hex("GKL")


def test_c1a_encode_decode_round_trip():
    for name in G.NAMES:
        h = G.rule_hex(name)
        assert evca.encode_table(evca.decode_table(h)) == h


# ---------------------------------------------------------------------------
# C1-b. Golden results for the six genomes on small fixed ICs.
# ---------------------------------------------------------------------------

#: Small, fixed, cheap. These are REGRESSION anchors for this implementation,
#: NOT a claim about the published figures. Generated by
#: `tools/make_golden.py` and checked in; regenerate only with a recorded
#: reason.
GOLDEN_CONFIG = {"n_ics": 64, "n_cells": 21, "steps": 42, "seed": 20260908}

GOLDEN = {
    "maj": None, "exp": None, "par": None,
    "particle1": None, "particle2": None, "GKL": None,
}


def _load_golden():
    path = os.path.join(os.path.dirname(__file__), "golden_c1b.json")
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


def test_c1b_golden_results_are_stable():
    gold = _load_golden()
    assert gold["config"] == GOLDEN_CONFIG, "golden config drifted"
    ics = evca.make_ics(GOLDEN_CONFIG["n_ics"], GOLDEN_CONFIG["n_cells"],
                        GOLDEN_CONFIG["seed"])
    for name in G.NAMES:
        r = evca.classify(evca.decode_table(G.rule_hex(name)), ics,
                          GOLDEN_CONFIG["steps"])
        want = gold["rules"][name]
        assert r["accuracy"] == pytest.approx(want["accuracy"], abs=0.0), name
        assert r["correct_mask_digest"] == want["correct_mask_digest"], name
        assert r["n_incorrect"] == want["n_incorrect"], name
        assert r["uniform_fixed_points"] == want["uniform_fixed_points"], name


def test_c1b_selected_trajectory_digest_is_stable():
    gold = _load_golden()
    sel = evca.selected_trajectory(**gold["selected_trajectory"]["inputs"])
    assert sel["digest"] == gold["selected_trajectory"]["digest"]
    assert sel["shape"] == gold["selected_trajectory"]["shape"]


# ---------------------------------------------------------------------------
# C1-c. Malformed input fails explicitly. Never coerced, never defaulted.
# ---------------------------------------------------------------------------

def test_c1c_unsupported_radius_refused():
    for r in (1, 2, 4, 0, -1):
        with pytest.raises(evca.EvcaError) as e:
            evca.require_radius(r)
        assert "r = 3" in str(e.value)


def test_c1c_malformed_rule_tables_refused():
    bad = [
        ("", "31 digits"), ("00", "too short"),
        ("0" * 31, "one short"), ("0" * 33, "one long"),
        ("0" * 31 + "g", "non-hex"), (None, "not a string"), (123, "not a str"),
    ]
    for value, _why in bad:
        with pytest.raises(evca.EvcaError):
            evca.decode_table(value)
    with pytest.raises(evca.EvcaError):
        evca.require_table(np.zeros(127, dtype=np.uint8))
    with pytest.raises(evca.EvcaError):
        evca.require_table(np.full(128, 2, dtype=np.uint8))


def test_c1c_even_lattice_refused_rather_than_tie_broken():
    with pytest.raises(evca.EvcaError) as e:
        evca.require_lattice(148)
    assert "ODD" in str(e.value)
    with pytest.raises(evca.EvcaError):
        evca.make_ics(4, 20, seed=1)


def test_c1c_tiny_lattice_refused():
    with pytest.raises(evca.EvcaError) as e:
        evca.require_lattice(5)
    assert "neighbourhood" in str(e.value)


def test_c1c_invalid_density_and_steps_refused():
    for d in (-0.01, 1.01, 2.0, "half", None.__class__):
        with pytest.raises(evca.EvcaError):
            evca.require_density(d)
    with pytest.raises(evca.EvcaError):
        evca.require_steps(-1)
    with pytest.raises(evca.EvcaError):
        evca.require_steps(1.5)
    with pytest.raises(evca.EvcaError):
        evca.make_ics(0, 21, seed=1)


def test_c1c_bad_state_shape_refused():
    with pytest.raises(evca.EvcaError):
        evca.neighbourhood_index(np.zeros(21, dtype=np.uint8))   # 1-D


# ---------------------------------------------------------------------------
# C1-d. Joint reflection and complement equivariance, on NORMALISED
# trajectories. Never a raw hash of differently oriented arrays.
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("name", G.NAMES)
def test_c1d_reflection_equivariance(name):
    table = evca.decode_table(G.rule_hex(name))
    ics = evca.make_ics(16, 21, seed=7)
    steps = 12

    base = evca.evolve(ics, table, steps, record=True)
    mirrored = evca.evolve(evca.reflect_states(ics),
                           evca.reflect_table(table), steps, record=True)

    # The naive check would compare raw bytes and fail. Prove that first, so
    # the normalisation is doing real work rather than hiding a mismatch.
    assert evca.trajectory_digest(base) != evca.trajectory_digest(mirrored)

    undone = evca.normalise_trajectory(mirrored, reflected=True)
    assert evca.trajectory_digest(undone) == evca.trajectory_digest(base)


@pytest.mark.parametrize("name", G.NAMES)
def test_c1d_complement_equivariance(name):
    table = evca.decode_table(G.rule_hex(name))
    ics = evca.make_ics(16, 21, seed=11)
    steps = 12

    base = evca.evolve(ics, table, steps, record=True)
    flipped = evca.evolve(evca.complement_states(ics),
                          evca.complement_table(table), steps, record=True)
    assert evca.trajectory_digest(base) != evca.trajectory_digest(flipped)

    undone = evca.normalise_trajectory(flipped, complemented=True)
    assert evca.trajectory_digest(undone) == evca.trajectory_digest(base)


@pytest.mark.parametrize("name", G.NAMES)
def test_c1d_joint_reflection_and_complement(name):
    table = evca.decode_table(G.rule_hex(name))
    ics = evca.make_ics(16, 21, seed=13)
    steps = 12
    base = evca.evolve(ics, table, steps, record=True)

    both_table = evca.complement_table(evca.reflect_table(table))
    both_ics = evca.complement_states(evca.reflect_states(ics))
    both = evca.evolve(both_ics, both_table, steps, record=True)

    undone = evca.normalise_trajectory(both, reflected=True, complemented=True)
    assert evca.trajectory_digest(undone) == evca.trajectory_digest(base)


@pytest.mark.parametrize("name", G.NAMES)
def test_c1d_correctness_mask_is_invariant_under_both_symmetries(name):
    """The scientific invariant: WHICH ICs are misclassified must not move.

    Complement also flips the majority target, which is why the mask is the
    right object to compare and the accuracy alone is not.
    """
    table = evca.decode_table(G.rule_hex(name))
    ics = evca.make_ics(64, 21, seed=17)
    steps = 42

    base = evca.classify(table, ics, steps, witness_limit=64)
    refl = evca.classify(evca.reflect_table(table),
                         evca.reflect_states(ics), steps, witness_limit=64)
    comp = evca.classify(evca.complement_table(table),
                         evca.complement_states(ics), steps, witness_limit=64)

    assert refl["correct_mask_digest"] == base["correct_mask_digest"], name
    assert comp["correct_mask_digest"] == base["correct_mask_digest"], name
    assert refl["witness"] == base["witness"]
    assert comp["witness"] == base["witness"]


def test_c1d_symmetry_transforms_are_involutions():
    for name in G.NAMES:
        t = evca.decode_table(G.rule_hex(name))
        assert (evca.reflect_table(evca.reflect_table(t)) == t).all()
        assert (evca.complement_table(evca.complement_table(t)) == t).all()
    s = evca.make_ics(4, 21, seed=3)
    assert (evca.reflect_states(evca.reflect_states(s)) == s).all()
    assert (evca.complement_states(evca.complement_states(s)) == s).all()


# ---------------------------------------------------------------------------
# Replay, purity, and drift.
# ---------------------------------------------------------------------------

def test_seed_and_configuration_replay():
    a = evca.make_ics(32, 21, seed=99)
    b = evca.make_ics(32, 21, seed=99)
    assert (a == b).all()
    c = evca.make_ics(32, 21, seed=100)
    assert not (a == c).all()
    t = evca.decode_table(G.rule_hex("GKL"))
    r1 = evca.classify(t, a, 30)
    r2 = evca.classify(t, b, 30)
    assert r1 == r2


def test_inputs_are_not_mutated():
    ics = evca.make_ics(8, 21, seed=5)
    before = ics.copy()
    table = evca.decode_table(G.rule_hex("par"))
    tb = table.copy()
    evca.evolve(ics, table, 10)
    evca.classify(table, ics, 10)
    assert (ics == before).all()
    assert (table == tb).all()


def test_witness_bound_is_declared_and_truncation_is_visible():
    """Uses a rule whose failures are known EXACTLY, by construction.

    An earlier version of this test used `maj` and assumed it scores zero,
    because the published figure is 0.000. That figure is for N = 149. On a
    21-cell ring `maj` scores about 0.36, so the assumption was wrong and the
    test failed for a reason that had nothing to do with the witness. The
    all-zeros table is unambiguous: every lattice becomes all zeros, so the
    misclassified set is exactly the ICs whose majority is 1.
    """
    t = np.zeros(evca.TABLE_BITS, dtype=np.uint8)
    ics = evca.make_ics(40, 21, seed=2)
    expected_wrong = int(evca.majority_target(ics).sum())
    assert 0 < expected_wrong < 40, "seed gives a degenerate split"

    r = evca.classify(t, ics, 30, witness_limit=5)
    assert r["n_incorrect"] == expected_wrong
    assert len(r["witness"]) == 5
    assert r["witness_truncated"] is True
    assert r["witness_limit"] == 5

    r2 = evca.classify(t, ics, 30, witness_limit=1000)
    assert r2["witness_truncated"] is False
    assert len(r2["witness"]) == expected_wrong
    assert r2["witness"] == sorted(r2["witness"])


def test_published_figures_are_lattice_specific_not_rule_properties():
    """`maj` is published at 0.000, and that is an N = 149 statement.

    Recorded as a test because it is a live trap: a small-lattice fixture that
    expects the published number will fail, and the natural reading of that
    failure is that the rule table is wrong when it is not.
    """
    t = evca.decode_table(G.rule_hex("maj"))
    small = evca.classify(t, evca.make_ics(64, 21, seed=20260908), 42)
    assert small["accuracy"] > 0.2, (
        "majority is NOT near zero on a small ring; the published 0.000 is a "
        "large-lattice figure")
    assert G.GENOMES["maj"]["published_P"][149] == 0.0


def test_import_has_no_side_effects():
    """No file writes, no stdout, no global-RNG consumption, on import."""
    code = (
        "import numpy as np, io, sys\n"
        "np.random.seed(1234)\n"
        "before = np.random.random()\n"
        "np.random.seed(1234)\n"
        "buf = io.StringIO(); old = sys.stdout; sys.stdout = buf\n"
        "import herakles.evca as m\n"
        "sys.stdout = old\n"
        "after = np.random.random()\n"
        "assert before == after, 'global RNG was consumed at import'\n"
        "assert buf.getvalue() == '', 'import wrote to stdout'\n"
        "print('OK')\n"
    )
    out = subprocess.run([sys.executable, "-c", code], cwd=REPO,
                         capture_output=True, text=True)
    assert out.returncode == 0, out.stderr
    assert out.stdout.strip().endswith("OK")


def test_embedded_genomes_match_the_specimen():
    """The drift check that lets the library embed rather than load."""
    path = os.path.join(REPO, *G.SPECIMEN_JSON.split("/"))
    with open(path, encoding="utf-8") as fh:
        spec = json.load(fh)
    by_name = {r["name"]: r for r in spec["rules"]}
    assert set(by_name) == set(G.GENOMES), "genome set drifted"
    for name, rec in G.GENOMES.items():
        src = by_name[name]
        assert src["hex"] == rec["hex"], name
        for n_cells, p in rec["published_P"].items():
            assert src["published_P"][str(n_cells)] == p, (name, n_cells)


def test_uniform_fixed_points_are_reported_per_rule():
    """The accuracy definition depends on this, so it must be visible."""
    for name in G.NAMES:
        t = evca.decode_table(G.rule_hex(name))
        f = evca.fixes_uniform_states(t)
        assert set(f) == {"all_zeros_fixed", "all_ones_fixed"}
        assert isinstance(f["all_zeros_fixed"], bool)


# ---------------------------------------------------------------------------
# The third criterion (2026-09-10). Its whole purpose is that its attainable
# range for random tables is an INTERVAL, so these tests check the range, not
# just that the function runs.
# ---------------------------------------------------------------------------

CM_N, CM_T, CM_NIC = 149, 298, 100


def _cm_ics():
    return evca.make_ics(CM_NIC, CM_N, seed=20260910)


def test_random_tables_do_not_collapse_to_a_point():
    """The defect this criterion exists to fix, stated as a measurement.

    Under `at_T` every random table scores exactly 0.0, so the attainable
    range is the single point {0}. Under cell match the twenty tables spread
    around 0.5 and can be ranked.
    """
    ics = _cm_ics()
    means = [evca.cellwise_majority_match(evca.random_table(1000 + i), ics,
                                          CM_T)["mean_cell_match"]
             for i in range(20)]
    assert len(set(means)) > 1, "the range is still a point"
    assert 0.45 < min(means) and max(means) < 0.55
    assert abs(sum(means) / len(means) - 0.5) < 0.02


def test_constant_rules_sit_at_the_analytic_half():
    """Predicted BEFORE measurement: mean 0.5, dispersion 0.5, values 0 or 1."""
    ics = _cm_ics()
    for tab in (np.zeros(evca.TABLE_BITS, dtype=np.uint8),
                np.ones(evca.TABLE_BITS, dtype=np.uint8)):
        r = evca.cellwise_majority_match(tab, ics, CM_T)
        assert abs(r["mean_cell_match"] - 0.5) < 0.06
        assert r["sd_across_ics"] > 0.49
        assert (r["fraction_all_cells_match"]
                + r["fraction_no_cells_match"]) == 1.0


def test_the_mean_alone_cannot_separate_constants_from_random():
    """The blind spot, asserted rather than left for someone to discover."""
    ics = _cm_ics()
    const = evca.cellwise_majority_match(
        np.zeros(evca.TABLE_BITS, dtype=np.uint8), ics, CM_T)
    rand = evca.cellwise_majority_match(evca.random_table(11), ics, CM_T)
    assert abs(const["mean_cell_match"] - rand["mean_cell_match"]) < 0.06
    # Dispersion tells them apart. NOTE the two dispersions are different
    # quantities and an earlier version of this test confused them:
    #   sd_across_ics   IC-to-IC spread within ONE table  (const 0.50, rand 0.10)
    #   table-to-table  spread of the MEAN over many tables (rand about 0.005)
    # The threshold below is on the first. The second is what makes the
    # attainable RANGE for random tables narrow, and it is checked separately
    # in test_random_tables_do_not_collapse_to_a_point.
    assert const["sd_across_ics"] > 0.45
    assert rand["sd_across_ics"] < 0.20
    assert const["sd_across_ics"] > 4 * rand["sd_across_ics"]


def test_maj_is_separated_from_random_where_at_T_cannot_separate_it():
    """The live fact that motivated the criterion, closed.

    maj scores 0.0 under at_T, exactly like a random table. Under cell match
    it sits well above the random band, and its per-IC values are strictly
    interior because it never reaches a uniform configuration.
    """
    ics = _cm_ics()
    m = evca.cellwise_majority_match(evca.decode_table(G.rule_hex("maj")),
                                     ics, CM_T)
    rand = [evca.cellwise_majority_match(evca.random_table(2000 + i), ics,
                                         CM_T)["mean_cell_match"]
            for i in range(10)]
    assert m["mean_cell_match"] > max(rand) + 0.03
    assert m["fraction_all_cells_match"] == 0.0
    assert m["fraction_no_cells_match"] == 0.0
    # and at_T really does give it zero, so the two criteria disagree by design
    assert evca.classify(evca.decode_table(G.rule_hex("maj")), ics,
                         CM_T)["accuracy"] == 0.0


def test_identity_mean_equals_at_T_for_rules_that_always_reach_uniform():
    """The only case where the new number may be compared with a published P."""
    ics = _cm_ics()
    for name in ("exp", "par", "GKL"):
        t = evca.decode_table(G.rule_hex(name))
        cm = evca.cellwise_majority_match(t, ics, CM_T)
        at_t = evca.classify(t, ics, CM_T)["accuracy"]
        if (cm["fraction_all_cells_match"]
                + cm["fraction_no_cells_match"]) == 1.0:
            assert abs(cm["mean_cell_match"] - at_t) < 1e-12, name


def test_random_table_is_seeded_and_replayable():
    assert (evca.random_table(5) == evca.random_table(5)).all()
    assert not (evca.random_table(5) == evca.random_table(6)).all()
    with pytest.raises(evca.EvcaError):
        evca.random_table("five")


# ---------------------------------------------------------------------------
# The synchronisation task (2026-09-10). A SECOND target for the collider.
# ---------------------------------------------------------------------------

def test_synchronisation_instrument_control_fires():
    """Without this, a score of 0 everywhere cannot be read.

    The blinker rule from a UNIFORM start alternates in phase forever, so the
    detector must return exactly 1.0. That separates a hard task from a broken
    measurement.
    """
    uni = np.zeros((4, 149), dtype=np.uint8)
    uni[2:] = 1
    r = evca.synchronisation_score(evca.blinker_rule_table(), uni, 298)
    assert r["score"] == 1.0
    assert r["fraction_frozen_uniform"] == 0.0


def test_the_instrument_control_does_not_SOLVE_the_task():
    """It blinks from uniform starts only, which is why it is a control."""
    mixed = evca.make_ics(200, 149, seed=5)
    r = evca.synchronisation_score(evca.blinker_rule_table(), mixed, 298)
    assert r["score"] == 0.0
    assert r["fraction_non_uniform"] == 1.0


def test_a_fixed_point_is_not_an_oscillation():
    """The constants reach uniform and STAY, so they must score exactly 0."""
    ics = evca.make_ics(100, 149, seed=20260910)
    for tab in (np.zeros(evca.TABLE_BITS, dtype=np.uint8),
                np.ones(evca.TABLE_BITS, dtype=np.uint8)):
        r = evca.synchronisation_score(tab, ics, 298)
        assert r["score"] == 0.0
        assert r["fraction_frozen_uniform"] == 1.0


def test_density_classifiers_score_zero_on_synchronisation():
    """Predicted before measuring: they drive to a FIXED uniform state."""
    ics = evca.make_ics(200, 149, seed=20260910)
    for name in G.NAMES:
        r = evca.synchronisation_score(evca.decode_table(G.rule_hex(name)),
                                       ics, 298)
        assert r["score"] == 0.0, name
    # and the diagnostic distinguishes WHY maj is zero from why the rest are
    maj = evca.synchronisation_score(evca.decode_table(G.rule_hex("maj")),
                                     ics, 298)
    gkl = evca.synchronisation_score(evca.decode_table(G.rule_hex("GKL")),
                                     ics, 298)
    assert maj["fraction_non_uniform"] == 1.0     # never uniform at all
    assert gkl["fraction_frozen_uniform"] == 1.0  # uniform but frozen
