"""Render a triplicate program as the charter's per-triplicate dossier
(OUTPUT PER TRIPLICATE). program.json is the machine-readable version; this
is the human one. Every claim line carries its honesty layer.

    python -m hecate.dossier            # all programs
    python -m hecate.dossier HT-xxxx    # one
"""

from __future__ import annotations

import glob
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROGS = os.path.join(ROOT, "hecate", "programs")

NOT_YET = "_none yet_"


def _l(items):
    return "\n".join(f"- {x}" for x in items) if items else NOT_YET


def render(p):
    tid = p["id"]
    hyps = p.get("hypotheses") or []
    interps = [h for h in hyps if h.get("kind") == "interpretation"]
    mechs = [h for h in hyps if h.get("kind") == "mechanism"]
    worlds = p.get("experiments") or []
    prov = p.get("provenance") or {}
    passes = p.get("passes") or []
    last = passes[-1] if passes else {}
    out = [f"# {tid}: {' x '.join(c['name'] for c in p['concepts'])}", ""]
    out += ["Generated by hecate/dossier.py from program.json; do not edit by hand.",
            "Layers: [spec] speculation, [impl] implemented candidate, "
            "[obs] experimental observation, [sup] supported conclusion.", ""]
    tag = {"speculation": "[spec]", "implemented_candidate": "[impl]",
           "experimental_observation": "[obs]", "supported_conclusion": "[sup]"}

    out += ["## TRIPLICATE", _l([f"{c['name']} ({c.get('field')}, {c.get('mechanism')})"
                                 for c in p["concepts"]]), ""]
    out += ["## ORIGINAL PROVENANCE", _l([
        f"source: {prov.get('source')}",
        f"sourceArtifact: {prov.get('sourceArtifact')}",
        f"historicalId: {prov.get('historicalId')}",
        f"upstream Nous: {len(prov.get('upstream_nous') or [])} response(s); "
        f"ledger lines: {prov.get('ledger_lines')}",
        f"selected by: {prov.get('selected_by')} (stratum {p.get('stratum')})",
    ]), ""]
    out += ["## RAW INTERPRETATIONS", _l([f"{tag.get(h.get('layer'), '[?]')} {h['id']}: {h.get('statement')}"
                                         for h in interps]), ""]
    out += ["## CANDIDATE PHYSICS", _l([f"{tag.get(h.get('layer'), '[?]')} {h['id']} ({h.get('form')}): "
                                       f"{h.get('statement')}" for h in mechs]), ""]
    out += ["## LENSES", _l([f"{l['id']} {l.get('name')}: {l.get('rationale')} "
                             f"(targets {', '.join(l.get('targets') or [])})"
                             for l in p.get("lenses") or []]), ""]
    out += ["## EXPERIMENTS", _l([f"{w['id']} [{w.get('substrate')}] {w.get('hypothesis')} "
                                  f"| success: {w.get('success_criterion')} "
                                  f"| null twin: {w.get('null_twin')} "
                                  f"| cost: {w.get('cost_estimate')}" for w in worlds]), ""]
    obs = [f"{w['id']}: {w.get('outcome')} ({w.get('rows')})" for w in worlds if w.get("outcome")]
    out += ["## OBSERVATIONS", _l(obs), ""]
    out += ["## FALSIFICATIONS", _l([f"{w['id']}: {x}" for w in worlds
                                     for x in (w.get("rejected_explanations") or [])]), ""]
    out += ["## SURVIVING ANOMALIES", _l([f"{w['id']}: {a.get('text')}" for w in worlds
                                          for a in (w.get("anomalies") or [])]), ""]
    out += ["## CROSS-SUBSTRATE RESULTS", _l(p.get("cross_substrate") or []), ""]
    out += ["## ENGINE PROPOSALS", _l([f"{e.get('name')}: {e.get('uniqueQuestion')}"
                                       for e in p.get("candidateEngines") or []]), ""]
    out += ["## VISUAL-CORTEX SPEC", _l(p.get("visual_cortex") or []), ""]
    out += ["## PRIOR ART", _l([f"{h['id']}: {h['prior_art'].get('label')} -- {h['prior_art'].get('evidence')}"
                               for h in hyps if h.get("prior_art")]), ""]
    out += ["## OPEN QUESTIONS", _l(last.get("unexplained") or []), ""]
    ev = p.get("evidenceSummary") or {}
    out += ["## CURRENT VERDICT",
            f"{p.get('currentVerdict')} (an allocation state, not a truth claim). "
            f"{ev.get('note', '')}", ""]
    out += ["## NEXT PASS", f"decision after {last.get('id', '-')}: {last.get('decision', '-')}", ""]
    return "\n".join(out)


def write(tid=None):
    paths = [os.path.join(PROGS, tid, "program.json")] if tid else sorted(
        glob.glob(os.path.join(PROGS, "*", "program.json")))
    for path in paths:
        with open(path, encoding="utf-8") as fh:
            p = json.load(fh)
        with open(os.path.join(os.path.dirname(path), "DOSSIER.md"), "w",
                  encoding="utf-8", newline="\n") as fh:
            fh.write(render(p))
    return len(paths)


if __name__ == "__main__":
    print(write(sys.argv[1] if len(sys.argv) > 1 else None), "dossiers written")
