"""prometheus_math.algebraic_geometry — Singular-backed AG/CA facade.

Categorical entry point for commutative-algebra operations that require
heavy CAS support: Groebner bases, ideal arithmetic, primary
decomposition, polynomial factorization over extensions, free
resolutions, Hilbert series.

Backend
-------
This module is a thin facade over Singular
(https://www.singular.uni-kl.de/), invoked as a subprocess via
``prometheus_math.backends._singular``. Singular is *not bundled* —
it must be installed separately. Common install paths the wrapper
will discover:

- Native Linux/macOS install on PATH
- Windows: Cygwin under ``C:\\cygwin64\\bin\\``
- Bundled with SageMath
- WSL2 (the wrapper detects ``wsl.exe`` and dispatches automatically)

If Singular is missing, every operation raises ``ValueError`` with
the install hint. Use ``installed()`` to gate calls cheaply.

Forged: 2026-04-22 | Backend: singular | Category: AG
"""
from __future__ import annotations

from typing import Sequence

from .backends import _singular

# ---------------------------------------------------------------------------
# Availability
# ---------------------------------------------------------------------------

_INSTALL_MSG = (
    "Singular not installed. Install via https://www.singular.uni-kl.de/ "
    "or as a SageMath component, then ensure 'Singular' is on PATH or in "
    r"C:\cygwin64\bin\."
)


def installed() -> bool:
    """Convenience: re-export ``_singular.is_installed()``."""
    return _singular.is_installed()


def _require_singular() -> None:
    if not _singular.is_installed():
        raise ValueError(_INSTALL_MSG)


# ---------------------------------------------------------------------------
# Script-builder helpers
# ---------------------------------------------------------------------------

def _ring_decl(variables: Sequence[str], order: str = "lp", char: int = 0) -> str:
    """Build a ``ring R = char,(vars),order;`` declaration."""
    if not variables:
        raise ValueError("at least one variable required")
    vs = ",".join(variables)
    return f"ring R = {char},({vs}),{order};"


def _ideal_decl(name: str, generators: Sequence[str]) -> str:
    """Build ``ideal name = g1, g2, ...;``."""
    if not generators:
        return f"ideal {name};"
    body = ", ".join(generators)
    return f"ideal {name} = {body};"


def _normalize_polynomials(polys: Sequence[str]) -> list[str]:
    """Convert Python ``**`` syntax to Singular ``^`` syntax."""
    out = []
    for p in polys:
        if not isinstance(p, str):
            raise ValueError(f"polynomials must be strings, got {type(p).__name__}")
        out.append(p.replace("**", "^"))
    return out


def _parse_ideal_output(text: str) -> list[str]:
    """Parse ``print(I);`` output into a list of polynomial strings.

    Singular's ``print(I);`` emits one generator per line, each
    prefixed with ``I[i]=``.
    """
    gens = []
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("//"):
            continue
        # Singular formats as "I[1]=x2-y" — drop the prefix
        if "=" in line and "[" in line.split("=", 1)[0]:
            line = line.split("=", 1)[1].strip()
        gens.append(line)
    return [g for g in gens if g]


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def groebner_basis(
    polynomials: list[str],
    variables: list[str],
    order: str = "lp",
) -> list[str]:
    """Compute a Groebner basis of the ideal generated by ``polynomials``.

    Parameters
    ----------
    polynomials:
        Generators of the ideal, as Singular-syntax strings (Python
        ``**`` is auto-converted to ``^``).
    variables:
        Variable names, in the order they should appear in the ring.
    order:
        Monomial order: ``"lp"`` (lex), ``"dp"`` (degrevlex),
        ``"Dp"`` (deglex), ``"ls"``, ``"ds"``, etc.

    Returns
    -------
    List of polynomial strings forming the Groebner basis.
    """
    _require_singular()
    polys = _normalize_polynomials(polynomials)
    script = "\n".join([
        _ring_decl(variables, order=order),
        _ideal_decl("I", polys),
        "ideal G = std(I);",
        'print(G);',
    ])
    out = _singular.run_session(script)
    return _parse_ideal_output(out)


def ideal_quotient(
    I: list[str],
    J: list[str],
    variables: list[str],
) -> list[str]:
    """Compute the ideal quotient ``I:J``.

    The quotient ``I:J = {f : f*J subset I}`` is the saturation of
    ``I`` with respect to ``J``.
    """
    _require_singular()
    Ip = _normalize_polynomials(I)
    Jp = _normalize_polynomials(J)
    script = "\n".join([
        _ring_decl(variables, order="dp"),
        _ideal_decl("I", Ip),
        _ideal_decl("J", Jp),
        "ideal Q = quotient(I, J);",
        "print(Q);",
    ])
    out = _singular.run_session(script)
    return _parse_ideal_output(out)


def primary_decomposition(
    I: list[str],
    variables: list[str],
) -> list[list[str]]:
    """Primary decomposition of an ideal.

    Uses Singular's ``primdec.lib`` (Gianni-Trager-Zacharias). Returns
    a list of primary components, each a list of generators.
    """
    _require_singular()
    polys = _normalize_polynomials(I)
    script = "\n".join([
        'LIB "primdec.lib";',
        _ring_decl(variables, order="dp"),
        _ideal_decl("I", polys),
        "list pd = primdecGTZ(I);",
        "int i; for (i = 1; i <= size(pd); i++) {",
        '  print("=== component"); print(i); print("===");',
        "  print(pd[i][1]);",
        "}",
    ])
    out = _singular.run_session(script)
    components: list[list[str]] = []
    current: list[str] = []
    for raw in out.splitlines():
        line = raw.strip()
        if line.startswith("=== component"):
            if current:
                components.append(current)
                current = []
            continue
        if not line or line.startswith("//"):
            continue
        if "=" in line and "[" in line.split("=", 1)[0]:
            line = line.split("=", 1)[1].strip()
        current.append(line)
    if current:
        components.append(current)
    return components


def factorize_polynomial(
    poly: str,
    variables: list[str],
) -> list[tuple[str, int]]:
    """Factor a polynomial over the rationals.

    Returns a list of ``(factor_string, multiplicity)`` pairs. The
    leading constant factor (if any) is returned as a 0-degree
    "factor" with multiplicity 1.
    """
    _require_singular()
    p = poly.replace("**", "^")
    script = "\n".join([
        _ring_decl(variables, order="dp"),
        f"poly f = {p};",
        "list F = factorize(f);",
        "int i; for (i = 1; i <= size(F[1]); i++) {",
        '  print("--- factor ---");',
        "  print(F[1][i]);",
        "  print(F[2][i]);",
        "}",
    ])
    out = _singular.run_session(script)
    factors: list[tuple[str, int]] = []
    pending: list[str] = []
    for raw in out.splitlines():
        line = raw.strip()
        if line.startswith("--- factor"):
            if len(pending) >= 2:
                try:
                    factors.append((pending[0], int(pending[1])))
                except ValueError:
                    factors.append((pending[0], 1))
            pending = []
            continue
        if not line or line.startswith("//"):
            continue
        pending.append(line)
    if len(pending) >= 2:
        try:
            factors.append((pending[0], int(pending[1])))
        except ValueError:
            factors.append((pending[0], 1))
    return factors


def hilbert_series(
    I: list[str],
    variables: list[str],
) -> str:
    """Compute the Hilbert series numerator of a homogeneous ideal.

    Returns the raw Singular output as a string. The denominator is
    ``(1-t)^n`` where ``n = len(variables)``.
    """
    _require_singular()
    polys = _normalize_polynomials(I)
    script = "\n".join([
        _ring_decl(variables, order="dp"),
        _ideal_decl("I", polys),
        "ideal G = std(I);",
        "intvec h = hilb(G, 1);",
        "print(h);",
    ])
    out = _singular.run_session(script)
    return _singular.strip_singular_chatter(out)


def free_resolution(
    I: list[str],
    variables: list[str],
    length: int = 4,
) -> list[str]:
    """Compute a free resolution of ``S/I`` up to homological degree ``length``.

    Returns a list of strings — one per module in the chain — with the
    raw Singular ``print`` output. The wrapper does not parse module
    ranks; callers can post-process if needed.
    """
    _require_singular()
    polys = _normalize_polynomials(I)
    script = "\n".join([
        _ring_decl(variables, order="dp"),
        _ideal_decl("I", polys),
        f"resolution R = res(I, {int(length)});",
        "int i; for (i = 0; i <= size(R); i++) {",
        '  print("--- module ---");',
        "  print(R[i]);",
        "}",
    ])
    out = _singular.run_session(script)
    modules: list[str] = []
    pending: list[str] = []
    for raw in out.splitlines():
        line = raw.strip()
        if line.startswith("--- module"):
            if pending:
                modules.append("\n".join(pending))
                pending = []
            continue
        if not line or line.startswith("//"):
            continue
        pending.append(line)
    if pending:
        modules.append("\n".join(pending))
    return modules


def is_radical(
    I: list[str],
    variables: list[str],
) -> bool:
    """Return True iff ``I`` equals its radical.

    Checks ``I == radical(I)`` via Singular's ``primdec.lib``.
    """
    _require_singular()
    polys = _normalize_polynomials(I)
    script = "\n".join([
        'LIB "primdec.lib";',
        _ring_decl(variables, order="dp"),
        _ideal_decl("I", polys),
        "ideal R = radical(I);",
        "ideal SI = std(I);",
        "ideal SR = std(R);",
        # Two ideals are equal iff their reduced std bases coincide.
        # A practical check: reduce one against the other in both directions.
        "ideal D1 = reduce(SR, SI);",
        "ideal D2 = reduce(SI, SR);",
        'if (size(D1) == 0 and size(D2) == 0) { print("RADICAL_TRUE"); }',
        'else { print("RADICAL_FALSE"); }',
    ])
    out = _singular.run_session(script)
    return "RADICAL_TRUE" in out


__all__ = [
    "installed",
    "groebner_basis",
    "ideal_quotient",
    "primary_decomposition",
    "factorize_polynomial",
    "hilbert_series",
    "free_resolution",
    "is_radical",
]
