"""prometheus_math.doc — auto-generates ARSENAL.md, the researcher-facing
single-page reference for the unified math API.

Usage:
    import prometheus_math
    prometheus_math.doc.arsenal()                    # write ARSENAL.md
    prometheus_math.doc.arsenal(out_path='custom.md')

ARSENAL.md is regenerated by CI on every push touching prometheus_math/**.
"""
from __future__ import annotations

import datetime
import importlib
import inspect
from pathlib import Path
from typing import Iterable

from .registry import all_backends, installed, summary

# Categorical modules to enumerate. Keep in sync with package __init__.py.
_CATEGORIES = [
    ("number_theory", "Number theory & polynomials"),
    ("elliptic_curves", "Elliptic curves over Q"),
    ("number_fields", "Number-field-specific operations"),
    ("topology", "Knot, link, 3-manifold, TDA"),
    ("combinatorics", "Graphs, polytopes, integer matrices"),
    ("optimization", "LP, MIP, CP, SAT, SMT, convex"),
    ("numerics", "Arbitrary precision and special functions"),
    ("symbolic", "Symbolic computation (CAS)"),
]


def _enumerate_module(modname: str) -> list[tuple[str, str]]:
    """Return [(funcname, one-line summary), ...] for everything in module's __all__."""
    full = f"prometheus_math.{modname}"
    try:
        m = importlib.import_module(full)
    except Exception as e:
        return [("(import failed)", str(e))]
    names = getattr(m, "__all__", None) or [
        n for n in dir(m) if not n.startswith("_")
    ]
    out = []
    for name in names:
        obj = getattr(m, name, None)
        if obj is None:
            continue
        if not callable(obj):
            continue
        doc = (inspect.getdoc(obj) or "").splitlines()
        first = doc[0].strip() if doc else ""
        try:
            sig = str(inspect.signature(obj))
        except (TypeError, ValueError):
            sig = "(...)"
        out.append((f"{name}{sig}", first))
    return out


def arsenal(out_path: str | Path | None = None) -> str:
    """Generate ARSENAL.md content. Writes to out_path if given, returns the
    Markdown either way.

    Default out_path: prometheus_math/ARSENAL.md (next to this file).
    """
    inv = installed()
    backends = all_backends()
    n_avail = sum(1 for b in backends if b.available)
    n_total = len(backends)

    lines: list[str] = []
    lines.append("# Prometheus Math Arsenal")
    lines.append("")
    lines.append("**Single-page researcher reference for the unified mathematical-software API.**")
    lines.append("")
    lines.append(f"Generated: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')} · "
                 f"Status: {summary()}")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Quick start")
    lines.append("")
    lines.append("```python")
    lines.append("import prometheus_math as pm")
    lines.append("")
    lines.append("# Number theory")
    lines.append("pm.number_theory.class_number('x^2+5')             # 2")
    lines.append("pm.elliptic_curves.analytic_sha([0,-1,1,-10,-20])   # {'rounded': 1, ...}")
    lines.append("")
    lines.append("# Topology")
    lines.append("pm.topology.hyperbolic_volume('4_1')                # 2.0298832...")
    lines.append("pm.topology.knot_shape_field('5_2')                 # {disc: -23, ...}")
    lines.append("")
    lines.append("# Optimization (auto-dispatches to best installed backend)")
    lines.append("pm.optimization.solve_mip(c, A_ub, b_ub, integrality=[1,1])")
    lines.append("")
    lines.append("# Numerics")
    lines.append("pm.numerics.zeta(0.5 + 14.13j, prec=50)")
    lines.append("")
    lines.append("# Capability check")
    lines.append("pm.registry.installed()")
    lines.append("```")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Capability matrix
    lines.append("## Backend capability matrix")
    lines.append("")
    lines.append(f"**{n_avail}/{n_total} backends available** as of generation.")
    lines.append("")
    lines.append("| Backend | Status | Version | Kind | Category | Description |")
    lines.append("|---|---|---|---|---|---|")
    for b in backends:
        status = "✅" if b.available else "❌"
        ver = b.version or "—"
        lines.append(f"| `{b.name}` | {status} | {ver} | {b.kind} | {b.category} | {b.description} |")
    lines.append("")

    # Categorical operations
    lines.append("---")
    lines.append("")
    lines.append("## Operations by category")
    lines.append("")
    for modname, label in _CATEGORIES:
        lines.append(f"### `prometheus_math.{modname}` — {label}")
        lines.append("")
        ops = _enumerate_module(modname)
        if not ops:
            lines.append("(no operations registered)")
            lines.append("")
            continue
        lines.append("| Function | Summary |")
        lines.append("|---|---|")
        for sig, summary_line in ops:
            cell_summary = summary_line.replace("|", "\\|")
            lines.append(f"| `{sig}` | {cell_summary} |")
        lines.append("")

    # Roadmap pointer
    lines.append("---")
    lines.append("")
    lines.append("## What's not yet wrapped")
    lines.append("")
    lines.append("See `techne/ARSENAL_ROADMAP.md` for the long-term tracker covering:")
    lines.append("")
    lines.append("- Tools installed but not yet exposed via this API")
    lines.append("- Heavy native installs queued (GAP, Macaulay2, Lean 4, Julia, SageMath)")
    lines.append("- Linux-only / WSL2 tools (Regina, polymake, nauty, fpLLL)")
    lines.append("- Web service wrappers (LMFDB, OEIS, KnotInfo, arXiv, zbMATH)")
    lines.append("- AI/ML integrations (DeepSeek-Prover, Lean Copilot)")
    lines.append("- Reverse-engineered paywalled functionality (Magma algorithms)")
    lines.append("- Novel tools we've identified as needed but don't yet exist")
    lines.append("")

    # Footer
    lines.append("---")
    lines.append("")
    lines.append("*Auto-generated by `prometheus_math.doc.arsenal()`. "
                 "Re-run after adding new operations or backends.*")
    lines.append("")

    content = "\n".join(lines)

    if out_path is None:
        out_path = Path(__file__).parent / "ARSENAL.md"
    Path(out_path).write_text(content, encoding="utf-8")
    return content


def installed_table() -> dict:
    """Return the raw `installed()` registry dict (caller-friendly summary)."""
    return installed()


__all__ = ["arsenal", "installed_table"]
