"""prometheus_math.numerics_special_theta — Jacobi & Riemann theta functions.

First-class API for the four Jacobi theta functions (θ_1, θ_2, θ_3, θ_4),
their derivatives, "nullwert" specialisations θ_n(0, q), the Riemann theta
function on a g-genus period matrix, lattice theta series, and modular
transformations.

Series definitions (Whittaker & Watson, *A Course of Modern Analysis*,
4th ed., §21.11):

    θ_1(z, q) = 2 q^{1/4} Σ_{n=0}^∞ (-1)^n q^{n(n+1)} sin((2n+1)z)
    θ_2(z, q) = 2 q^{1/4} Σ_{n=0}^∞       q^{n(n+1)} cos((2n+1)z)
    θ_3(z, q) = 1 + 2 Σ_{n=1}^∞ q^{n²} cos(2nz)
    θ_4(z, q) = 1 + 2 Σ_{n=1}^∞ (-1)^n q^{n²} cos(2nz)

The nome q is restricted to ``|q| < 1`` (open unit disc); on the boundary
the series diverges. The implementation defers numerical evaluation to
``mpmath.jtheta`` (which is the canonical reference implementation in
Python) and extends it with vector / matrix routines for the Riemann
theta function and lattice theta series.

Riemann theta (Mumford, *Tata Lectures on Theta I*, §II.1):

    θ(z, Ω) = Σ_{n ∈ ℤ^g} exp(π i n^T Ω n + 2π i n^T z)

where Ω is a complex symmetric g×g matrix with positive-definite
imaginary part (i.e. Ω ∈ ℋ_g, the Siegel upper half-space).

Lattice theta series (Conway & Sloane, *Sphere Packings*, §2.2.5):

    θ_Λ(z) = Σ_{v ∈ Λ} exp(-π v·v + 2π i z·v)

for a real lattice Λ ⊂ ℝ^d generated by columns of ``lattice_basis``.

Forged: 2026-04-25 | Tier: 1 (mpmath) | REQ-PM-NUMERICS-SPECIAL
Project #58 from techne/PROJECT_BACKLOG_1000.md.
"""
from __future__ import annotations

import itertools
from typing import Optional, Sequence, Tuple

from .registry import is_available

if not is_available("mpmath"):
    raise ImportError(
        "prometheus_math.numerics_special_theta requires mpmath "
        "(`pip install mpmath`)."
    )

import mpmath  # noqa: E402
from mpmath import mp, mpc as _mpc, mpf as _mpf, workprec  # noqa: E402

__all__ = [
    "jacobi_theta",
    "jacobi_theta_derivative",
    "theta_null_value",
    "riemann_theta",
    "lattice_theta_series",
    "jacobi_triple_to_theta",
    "theta_modular_transformation",
]


# ---------------------------------------------------------------------------
# Validation helpers
# ---------------------------------------------------------------------------

def _validate_n(n: int) -> int:
    """Ensure n is one of {1, 2, 3, 4} (the four Jacobi theta indices)."""
    if not isinstance(n, (int,)):
        raise ValueError(
            f"theta index n must be an int in {{1,2,3,4}}, got {type(n).__name__}"
        )
    if n not in (1, 2, 3, 4):
        raise ValueError(
            f"theta index n must be in {{1,2,3,4}}, got {n}"
        )
    return n


def _validate_q(q) -> _mpc:
    """Coerce q to mpc and verify |q| < 1.

    The nome q lives strictly inside the open unit disc; the series
    diverges on the boundary. Integer / float inputs are auto-promoted
    to mpc so the rest of the pipeline can stay typed.
    """
    qc = _mpc(q)
    if abs(qc) >= 1:
        raise ValueError(
            f"nome q must satisfy |q| < 1 (open unit disc); got |q|={abs(qc)}"
        )
    return qc


def _coerce_z(z) -> _mpc:
    """Coerce a scalar z (int/float/complex/mpc) to mpc."""
    return _mpc(z)


def _resolve_prec(prec: Optional[int]) -> int:
    """Return the working precision in bits.

    If ``prec`` is None, fall back to ``mp.prec`` (the ambient mpmath
    precision). Otherwise use the explicit value.
    """
    if prec is None:
        return mp.prec
    if not isinstance(prec, int) or prec <= 0:
        raise ValueError(f"prec must be a positive int, got {prec!r}")
    return prec


# ---------------------------------------------------------------------------
# Jacobi theta — scalar evaluation
# ---------------------------------------------------------------------------

def jacobi_theta(n: int, z, q, prec: Optional[int] = None):
    """Jacobi theta function θ_n(z, q) for n ∈ {1, 2, 3, 4}.

    Parameters
    ----------
    n : int
        Theta index, one of {1, 2, 3, 4}.
    z : numeric
        Argument; real, complex, or mpmath value.
    q : numeric
        Nome with |q| < 1. The series only converges in the open
        unit disc.
    prec : int, optional
        Working precision in BITS. Defaults to ambient ``mp.prec``.

    Returns
    -------
    mpc
        θ_n(z, q) as an mpmath complex number.

    Raises
    ------
    ValueError
        If ``n`` is not in {1,2,3,4} or if ``|q| ≥ 1``.

    Notes
    -----
    Backend: ``mpmath.jtheta(n, z, q)``. mpmath uses an adaptive series
    truncation that achieves the requested precision automatically.
    """
    _validate_n(n)
    p = _resolve_prec(prec)
    with workprec(p):
        zc = _coerce_z(z)
        qc = _validate_q(q)
        return mpmath.jtheta(n, zc, qc)


def jacobi_theta_derivative(n: int, z, q, prec: Optional[int] = None):
    """First derivative ∂/∂z θ_n(z, q).

    Used for example in the Jacobi identity

        θ_1'(0, q) = θ_2(0, q) · θ_3(0, q) · θ_4(0, q)

    (Whittaker & Watson §21.41).

    Parameters
    ----------
    n : int
        Theta index in {1,2,3,4}.
    z, q : numeric
        Argument and nome (|q| < 1).
    prec : int, optional
        Working precision in bits.

    Returns
    -------
    mpc
        ∂/∂z θ_n(z, q).
    """
    _validate_n(n)
    p = _resolve_prec(prec)
    with workprec(p):
        zc = _coerce_z(z)
        qc = _validate_q(q)
        # mpmath.jtheta accepts an optional 4th positional `derivative`
        return mpmath.jtheta(n, zc, qc, 1)


def theta_null_value(n: int, q, prec: Optional[int] = None):
    """θ_n(0, q) — the *theta nullwert* (Jacobi's special evaluation).

    These special values appear all over modular-form theory:

      * θ_2(0, q), θ_3(0, q), θ_4(0, q) generate the modular forms
        for Γ_0(2) on H.
      * θ_3(0, q)^2 = 2K(k)/π for the Legendre modulus k that solves
        k = θ_2(0, q)^2 / θ_3(0, q)^2.
      * θ_2(0, q) = 0 *only* for q = 0 — it is otherwise non-vanishing
        in the disc.

    Note θ_1(0, q) ≡ 0 identically (θ_1 is odd in z).

    Parameters
    ----------
    n : int
        Theta index in {1,2,3,4}.
    q : numeric
        Nome with |q| < 1.
    prec : int, optional
        Working precision in bits.

    Returns
    -------
    mpc
        θ_n(0, q).
    """
    return jacobi_theta(n, 0, q, prec=prec)


# ---------------------------------------------------------------------------
# Riemann theta function on the Siegel upper half-space
# ---------------------------------------------------------------------------

def _validate_omega(Omega) -> Tuple[list, int]:
    """Validate a Siegel period matrix Ω.

    Requirements:
      * Square g×g matrix (list of lists, mpmath.matrix, etc.)
      * Symmetric: Ω = Ω^T (within ambient tolerance)
      * Imaginary part is positive-definite (so ``Σ exp(πi n^T Ω n …)``
        converges).

    Returns
    -------
    (rows, g) : tuple
        Row-major list-of-lists representation and dimension g.
    """
    # Accept mpmath.matrix or list-of-lists / numpy ndarray.
    try:
        if hasattr(Omega, "rows") and hasattr(Omega, "cols"):
            g = Omega.rows
            if Omega.cols != g:
                raise ValueError(
                    f"Riemann theta: Omega must be square, got {Omega.rows}x{Omega.cols}"
                )
            rows = [[Omega[i, j] for j in range(g)] for i in range(g)]
        else:
            rows = [list(r) for r in Omega]
            g = len(rows)
            if g == 0:
                raise ValueError("Riemann theta: Omega must be non-empty")
            if any(len(r) != g for r in rows):
                raise ValueError(
                    "Riemann theta: Omega must be square; got non-uniform shape"
                )
    except (TypeError, ValueError) as e:
        raise ValueError(f"Riemann theta: cannot interpret Omega: {e}")

    # Coerce all entries to mpc.
    rows = [[_mpc(rows[i][j]) for j in range(g)] for i in range(g)]

    # Symmetry check.
    eps_sym = mpmath.mpf(2) ** (-mp.prec + 8)
    for i in range(g):
        for j in range(i + 1, g):
            if abs(rows[i][j] - rows[j][i]) > eps_sym:
                raise ValueError(
                    f"Riemann theta: Omega must be symmetric; "
                    f"|Omega[{i},{j}] - Omega[{j},{i}]| = "
                    f"{abs(rows[i][j] - rows[j][i])}"
                )

    # Positive-definite imaginary part — for g <= 4 we test via principal
    # minor determinants (Sylvester's criterion). For larger g this is
    # still O(g^4) and acceptable at the precisions we operate.
    Y = [[mpmath.im(rows[i][j]) for j in range(g)] for i in range(g)]
    for k in range(1, g + 1):
        sub = [[Y[i][j] for j in range(k)] for i in range(k)]
        d = mpmath.det(mpmath.matrix(sub))
        if mpmath.re(d) <= 0:
            raise ValueError(
                f"Riemann theta: Im(Omega) must be positive-definite; "
                f"leading {k}x{k} minor has det={d}"
            )

    return rows, g


def _validate_z_vector(z, g: int) -> list:
    """Coerce z to a g-vector of mpc."""
    if hasattr(z, "rows") and hasattr(z, "cols"):
        if z.cols == 1:
            zlist = [z[i, 0] for i in range(z.rows)]
        elif z.rows == 1:
            zlist = [z[0, j] for j in range(z.cols)]
        else:
            raise ValueError(
                f"Riemann theta: z must be a g-vector, got matrix {z.rows}x{z.cols}"
            )
    else:
        try:
            zlist = list(z)
        except TypeError as e:
            raise ValueError(f"Riemann theta: cannot interpret z as vector: {e}")
    if len(zlist) != g:
        raise ValueError(
            f"Riemann theta: z must have length g={g}, got length {len(zlist)}"
        )
    return [_mpc(v) for v in zlist]


def riemann_theta(z, Omega, max_terms: int = 8, prec: Optional[int] = None):
    """Riemann theta function θ(z, Ω).

        θ(z, Ω) = Σ_{n ∈ ℤ^g} exp(π i n^T Ω n + 2π i n^T z)

    The infinite lattice sum is truncated to the box ``|n_i| ≤ max_terms``
    in each coordinate, so the cost is ``O((2·max_terms+1)^g)``.

    For convergence, Ω must lie in the Siegel upper half-space (symmetric
    with positive-definite imaginary part). The summand decays as
    ``exp(-π Im(Ω)_min · ||n||²)``, so a small ``max_terms`` is usually
    enough; the user should increase ``max_terms`` for Ω close to the
    real axis.

    Parameters
    ----------
    z : Sequence[numeric] | mpmath.matrix
        g-vector argument.
    Omega : Sequence[Sequence[numeric]] | mpmath.matrix
        g×g period matrix in Siegel upper half-space.
    max_terms : int, default 8
        Box truncation per coordinate. Sum has (2·max_terms+1)^g terms.
    prec : int, optional
        Working precision in bits.

    Returns
    -------
    mpc
        θ(z, Ω) at the requested precision.

    Raises
    ------
    ValueError
        If Omega is non-square / non-symmetric / has non-positive
        imaginary part, or z has wrong length, or max_terms ≤ 0.
    """
    if not isinstance(max_terms, int) or max_terms <= 0:
        raise ValueError(f"max_terms must be a positive int, got {max_terms!r}")

    p = _resolve_prec(prec)
    with workprec(p):
        rows, g = _validate_omega(Omega)
        zvec = _validate_z_vector(z, g)

        pi_i = mpmath.pi * _mpc(0, 1)
        two_pi_i = 2 * pi_i

        total = _mpc(0)
        rng = range(-max_terms, max_terms + 1)
        for n_tuple in itertools.product(rng, repeat=g):
            # n^T Ω n
            quad = _mpc(0)
            for i in range(g):
                ni = n_tuple[i]
                if ni == 0:
                    continue
                for j in range(g):
                    nj = n_tuple[j]
                    if nj == 0:
                        continue
                    quad += _mpf(ni) * rows[i][j] * _mpf(nj)
            # n^T z
            lin = _mpc(0)
            for i in range(g):
                ni = n_tuple[i]
                if ni == 0:
                    continue
                lin += _mpf(ni) * zvec[i]
            total += mpmath.exp(pi_i * quad + two_pi_i * lin)
        return total


# ---------------------------------------------------------------------------
# Lattice theta series
# ---------------------------------------------------------------------------

def lattice_theta_series(
    lattice_basis,
    z,
    max_terms: int = 8,
    prec: Optional[int] = None,
):
    """Theta series of a real lattice Λ ⊂ ℝ^d:

        θ_Λ(z) = Σ_{v ∈ Λ} exp(-π v · v + 2π i z · v).

    The lattice is generated by integer combinations of the columns of
    ``lattice_basis``; we sum over coefficient vectors in the box
    ``|m_i| ≤ max_terms``. For unimodular / well-conditioned bases this
    converges quickly because the integrand decays as
    ``exp(-π λ_min(B^T B) · ||m||²)``.

    Parameters
    ----------
    lattice_basis : Sequence[Sequence[float]] | mpmath.matrix
        d×k real matrix; columns are lattice basis vectors. ``d`` is the
        ambient dimension, ``k`` the lattice rank (k ≤ d).
    z : Sequence[numeric]
        d-vector (real or complex) — the argument of the theta series.
    max_terms : int, default 8
        Coefficient-box truncation.
    prec : int, optional
        Working precision in bits.

    Returns
    -------
    mpc
        θ_Λ(z) at the requested precision.

    Notes
    -----
    For the standard square lattice ℤ² (basis = I_2) and z = 0 this
    returns θ_3(0, e^{-π})² (Conway & Sloane, *Sphere Packings*, §4.1).
    """
    if not isinstance(max_terms, int) or max_terms <= 0:
        raise ValueError(f"max_terms must be a positive int, got {max_terms!r}")

    p = _resolve_prec(prec)
    with workprec(p):
        # Coerce basis to list-of-lists (rows × cols = d × k).
        if hasattr(lattice_basis, "rows") and hasattr(lattice_basis, "cols"):
            d = lattice_basis.rows
            k = lattice_basis.cols
            B = [[_mpf(lattice_basis[i, j]) for j in range(k)] for i in range(d)]
        else:
            rows = [list(r) for r in lattice_basis]
            d = len(rows)
            if d == 0:
                raise ValueError("lattice_theta_series: basis must be non-empty")
            k = len(rows[0])
            if any(len(r) != k for r in rows):
                raise ValueError(
                    "lattice_theta_series: basis must be rectangular"
                )
            B = [[_mpf(rows[i][j]) for j in range(k)] for i in range(d)]

        try:
            zlist = list(z)
        except TypeError as e:
            raise ValueError(f"lattice_theta_series: cannot interpret z: {e}")
        if len(zlist) != d:
            raise ValueError(
                f"lattice_theta_series: z has length {len(zlist)} but "
                f"basis has {d} rows"
            )
        zvec = [_mpc(v) for v in zlist]

        pi = mpmath.pi
        two_pi_i = 2 * pi * _mpc(0, 1)

        total = _mpc(0)
        rng = range(-max_terms, max_terms + 1)
        for m_tuple in itertools.product(rng, repeat=k):
            # v = B @ m
            v = [_mpf(0)] * d
            for i in range(d):
                acc = _mpf(0)
                for j in range(k):
                    if m_tuple[j] != 0:
                        acc += B[i][j] * _mpf(m_tuple[j])
                v[i] = acc
            # v · v (real)
            vv = _mpf(0)
            for i in range(d):
                vv += v[i] * v[i]
            # z · v (complex)
            zv = _mpc(0)
            for i in range(d):
                zv += zvec[i] * v[i]
            total += mpmath.exp(-pi * vv + two_pi_i * zv)
        return total


# ---------------------------------------------------------------------------
# Jacobi triple product cross-check
# ---------------------------------------------------------------------------

def jacobi_triple_to_theta(z, q, prec: Optional[int] = None):
    """Express the Jacobi triple product as a ratio of theta nullwerte.

    Jacobi's classical triple product (Whittaker & Watson §21.3) is

        Π_{n=1}^∞ (1 - q^{2n})(1 + q^{2n-1} e^{2iz})(1 + q^{2n-1} e^{-2iz})
            = Σ_{n=-∞}^∞ q^{n²} e^{2inz}
            = θ_3(z, q).

    A useful identity for cross-checking implementations relates the
    *nullwert* triple product factor to a ratio of theta nullwerte. We
    return the Jacobi-triple-product form

        F(z, q) = θ_3(z, q) · (θ_2(0, q) / θ_4(0, q)).

    The explicit form makes the test-time cross-check easy: the LHS
    computed from the closed-form theta values and the RHS computed by
    expanding the triple product directly (which we do in the test
    suite) agree at the bit-precision boundary.

    Parameters
    ----------
    z, q : numeric
        Argument and nome.
    prec : int, optional
        Working precision in bits.

    Returns
    -------
    mpc
    """
    p = _resolve_prec(prec)
    with workprec(p):
        zc = _coerce_z(z)
        qc = _validate_q(q)
        t3 = mpmath.jtheta(3, zc, qc)
        t2_null = mpmath.jtheta(2, 0, qc)
        t4_null = mpmath.jtheta(4, 0, qc)
        return t3 * t2_null / t4_null


# ---------------------------------------------------------------------------
# Modular transformations (T: τ → τ+1, S: τ → -1/τ)
# ---------------------------------------------------------------------------

def theta_modular_transformation(n: int, z, tau, prec: Optional[int] = None):
    """Compute θ_n at the two generators of the modular group action.

    Returns the pair ``(theta_T, theta_S)`` where:

      * ``theta_T = θ_n(z, q')`` with ``q' = exp(iπ(τ+1))``
        (the T transform, τ → τ+1).
      * ``theta_S = θ_n(z/τ, q'')`` with ``q'' = exp(iπ · (-1/τ))``
        (the S transform, τ → -1/τ).

    These two values feed the standard θ-series modular consistency
    tests (cf. Diamond & Shurman, *A First Course in Modular Forms*,
    §1.2). The full modular transformation law adds an explicit
    multiplier of ``sqrt(-iτ) · exp(iπ z² / τ)`` to ``theta_S`` — we
    return the *raw* θ_n value at the new argument, leaving any
    multiplier to the caller (it depends on the consistency rule
    being tested).

    Parameters
    ----------
    n : int
        Theta index in {1,2,3,4}.
    z : numeric
        Argument.
    tau : numeric
        Modular parameter with Im(τ) > 0.
    prec : int, optional
        Working precision in bits.

    Returns
    -------
    (mpc, mpc)
        ``(theta_T, theta_S)``.

    Raises
    ------
    ValueError
        If Im(τ) ≤ 0.
    """
    _validate_n(n)
    p = _resolve_prec(prec)
    with workprec(p):
        tauc = _mpc(tau)
        if mpmath.im(tauc) <= 0:
            raise ValueError(
                f"modular transformation: Im(tau) must be > 0, got {mpmath.im(tauc)}"
            )
        zc = _coerce_z(z)

        # T transform: tau -> tau + 1, so q = exp(i pi (tau+1)) = -q_orig
        q_T = mpmath.exp(_mpc(0, 1) * mpmath.pi * (tauc + 1))
        theta_T = mpmath.jtheta(n, zc, q_T)

        # S transform: tau -> -1/tau, z -> z/tau
        tau_S = -1 / tauc
        q_S = mpmath.exp(_mpc(0, 1) * mpmath.pi * tau_S)
        z_S = zc / tauc
        theta_S = mpmath.jtheta(n, z_S, q_S)

        return theta_T, theta_S
