"""W2-AD: funnel counts, admitted-cell list and blocking-dial analysis from out/ceil_*.jsonl + out/plant_*.jsonl.
-> out/census_summary.json and out/census_tables.md. Pure post-processing (no engine)."""
import json, pathlib, collections, math
O = pathlib.Path(__file__).resolve().parent / "out"
DIALS = ["topology", "n_sites", "radius", "k_random", "rewire", "fanout", "dest_mode", "loss", "loss_per_hop",
         "lat_base", "lat_hop", "lat_jitter", "dup", "noise", "cap", "collision", "decay_shift", "update_mode",
         "update_period", "update_p", "plastic_route", "adapt_shift", "wimm", "mut_site"]
ENVD = ["d", "delta", "block"]


def load(p):
    return [json.loads(l) for l in p.read_text().splitlines() if l.strip()] if p.exists() else []


def lv(c, k):
    if k in ENVD:
        return c["env_levels"][k]
    return c["levels"].get(k, c["physics"].get(k))


def relevant(c, k):
    """dials that do nothing at a cell are not counted (k_random off random, rewire off smallworld,
    collision without cap, update_p under sync, update_period under async, block off FLIP)."""
    p = c["physics"]
    if k == "k_random": return p["topology"] == "random"
    if k == "rewire": return p["topology"] == "smallworld"
    if k == "radius": return p["topology"] in ("ring", "torus")
    if k == "collision": return p["cap"] > 0
    if k == "update_p": return p["update_mode"] == "async"
    if k == "update_period": return p["update_mode"] == "sync"
    if k == "adapt_shift": return bool(p["plastic_route"])
    if k == "loss_per_hop": return p["loss"] > 0
    if k == "dest_mode": return p["topology"] != "global"
    if k == "block": return c["family"] == "FLIP"
    return True


def blocking(rows, stage_key):
    """per dial level: n, pass rate at stage_key. Rank dials by (best-level rate - worst-level rate) and list
    levels with ZERO passes among >= 8 candidates (absolute blockers in this sample)."""
    out = {}
    tot = len(rows); npass = sum(r[stage_key] for r in rows)
    base = npass / tot if tot else 0
    for k in DIALS + ENVD:
        by = collections.defaultdict(lambda: [0, 0])
        for r in rows:
            if not relevant(r, k):
                continue
            v = str(lv(r, k)); by[v][0] += 1; by[v][1] += int(r[stage_key])
        if len(by) < 2:
            continue
        rates = {v: (n, p, p / n) for v, (n, p) in by.items() if n >= 4}
        if len(rates) < 2:
            continue
        spread = max(x[2] for x in rates.values()) - min(x[2] for x in rates.values())
        zero = [v for v, (n, p, _) in rates.items() if p == 0 and n >= 8]
        # failures attributable: candidates at zero-pass levels
        out[k] = {"spread": round(spread, 3), "levels": {v: f"{p}/{n}" for v, (n, p, _) in sorted(rates.items())},
                  "zero_pass_levels": zero}
    rank = sorted(out, key=lambda k: -out[k]["spread"])
    return {"n": tot, "pass": npass, "base_rate": round(base, 3), "ranked": [(k, out[k]) for k in rank]}


def main():
    summ, md = {}, ["# W2-AD C2 admission census tables (generated by tabulate.py)", ""]
    for fam in ("RELAY", "FLIP", "MAJ", "XOR"):
        C = load(O / f"ceil_{fam}.jsonl")
        if not C:
            continue
        Pl = {r["cid"]: r for r in load(O / f"plant_{fam}.jsonl")}
        for c in C:
            c["plant_done"] = c["cid"] in Pl
            pr = Pl.get(c["cid"])
            c["plant_pass"] = bool(pr and pr["plant_pass"])
            c["plants"] = pr["plants"] if pr else None
            c["admitted"] = bool(c["survivor"] and c["plant_pass"])
            c["sr"] = bool(c["stratum_ok"] and c["reach_ok"])
        n = len(C)
        f = {"candidates": n,
             "stratum_ok": sum(c["stratum_ok"] for c in C),
             "reach_ok": sum(c["stratum_ok"] and c["reach_ok"] for c in C),
             "ceiling_pass": sum(c["survivor"] for c in C),
             "plant_scored": sum(c["survivor"] and c["plant_done"] for c in C),
             "plant_pass(admitted)": sum(c["admitted"] for c in C)}
        f["ceiling_only_pass_ignoring_stratum"] = sum(c["ceil_ok"] for c in C)
        if fam == "MAJ":
            f["integration_claimed_survivors"] = sum(c["survivor"] and c.get("integration_claimed") for c in C)
            f["admitted_integration"] = sum(c["admitted"] and c.get("integration_claimed") for c in C)
            f["hop1_all_survivors"] = sum(c["survivor"] and c.get("hop1_all") for c in C)
            f["admitted_hop1_all"] = sum(c["admitted"] and c.get("hop1_all") for c in C)
        # per design pass counts among scored survivors
        dp = collections.Counter(); both = 0
        for c in C:
            if c["survivor"] and c["plants"]:
                ps = [k for k, v in c["plants"].items() if v["pass"]]
                for k in ps: dp[k] += 1
                both += len(ps) >= 2
        f["design_pass"] = dict(dp); f["passes_with_>=2_designs"] = both
        f["above_ceiling_violations"] = sum(1 for c in C if c["plants"] and any(v.get("above_ceiling") for v in c["plants"].values()))
        f["binding_ceiling_component(all)"] = dict(collections.Counter(c["binding"] for c in C))
        adm = []
        for c in C:
            if not c["admitted"]:
                continue
            p, e = c["physics"], c["env"]
            adm.append({"cid": c["cid"], "ceiling": round(c["ceiling"], 3), "binding": c["binding"],
                        "q": round(c["q"], 3) if c.get("q") is not None else None,
                        "integration_claimed": c.get("integration_claimed"),
                        "hops": [c["hops"]["min_hops"], c["hops"]["max_hops"]],
                        "plants": {k: {kk: (round(vv, 3) if isinstance(vv, float) else vv) for kk, vv in v.items()
                                       if kk in ("acc", "lo99", "B", "B_lo99", "DICT", "diff_lo99", "teacher_off", "pass")}
                                   for k, v in c["plants"].items()},
                        "physics": {k: p[k] for k in ("topology", "n_sites", "radius", "k_random", "rewire", "fanout",
                                                       "dest_mode", "loss", "loss_per_hop", "lat_base", "lat_hop",
                                                       "lat_jitter", "dup", "noise", "cap", "collision", "decay_shift",
                                                       "update_mode", "update_period", "update_p", "plastic_route",
                                                       "adapt_shift", "wimm", "mut_site", "state_dim", "payload_width",
                                                       "channels", "prog_len", "rules", "setrule", "topo_seed")},
                        "env": {k: e[k] for k in ("family", "d", "delta", "block", "trials", "cue_len")}})
        # blocking dials: stage A = ceiling+stratum+reach (all candidates); stage B = plant | survivor
        for c in C:
            c["_A"] = c["survivor"]; c["_B"] = c["admitted"]
        bA = blocking(C, "_A")
        S = [c for c in C if c["survivor"] and c["plant_done"]]
        bB = blocking(S, "_B") if S else None
        bAll = blocking(C, "_B")
        # first failing clause per candidate
        clause = collections.Counter()
        for c in C:
            if not c["stratum_ok"]: clause["stratum"] += 1
            elif not c["reach_ok"]: clause["reach"] += 1
            elif not c["ceil_ok"]: clause["ceiling"] += 1
            elif not c["plant_done"]: clause["plant_not_scored"] += 1
            elif not c["plant_pass"]: clause["plant"] += 1
            else: clause["ADMITTED"] += 1
        summ[fam] = {"funnel": f, "first_failing_clause": dict(clause), "admitted": adm,
                     "blocking_ceiling_stage": bA, "blocking_plant_stage": bB, "blocking_overall": bAll}
        md += [f"## {fam}", "", "funnel: " + json.dumps(f), "", "first failing clause: " + json.dumps(dict(clause)), ""]
        md += ["top blocking dials, overall admission (dial: spread; levels pass/n; zero-pass levels):"]
        for k, v in bAll["ranked"][:10]:
            md.append(f"- {k}: {v['spread']} {v['levels']} zero={v['zero_pass_levels']}")
        md += ["", "top blocking dials, ceiling+stratum stage:"]
        for k, v in bA["ranked"][:8]:
            md.append(f"- {k}: {v['spread']} {v['levels']} zero={v['zero_pass_levels']}")
        if bB:
            md += ["", "top blocking dials, plant stage (among ceiling survivors):"]
            for k, v in bB["ranked"][:8]:
                md.append(f"- {k}: {v['spread']} {v['levels']} zero={v['zero_pass_levels']}")
        md += ["", f"admitted cells ({len(adm)}):"]
        for a in adm:
            p = a["physics"]; e = a["env"]
            md.append(f"- {a['cid']} ceil {a['ceiling']} ({a['binding']}) | {p['topology']} N{p['n_sites']} r{p['radius']} "
                      f"k{p['k_random']} rw{p['rewire']} F{p['fanout']} {p['dest_mode']} loss{p['loss']}/{p['loss_per_hop']} "
                      f"lat{p['lat_base']}+{p['lat_hop']}j{p['lat_jitter']} dup{p['dup']} noise{p['noise']} cap{p['cap']}{p['collision'][0]} "
                      f"decay{p['decay_shift']} {p['update_mode']}{p['update_period'] if p['update_mode']=='sync' else p['update_p']} "
                      f"pr{p['plastic_route']} wimm{p['wimm']} mut{p['mut_site']} | d{e['d']} delta{e['delta']} block{e['block']} "
                      f"| hops {a['hops']} q {a['q']} int {a['integration_claimed']} | "
                      + "; ".join(f"{k} {v.get('acc')}/{v.get('lo99')}" + (f" B{v.get('B_lo99')}" if 'B_lo99' in v else "")
                                  + (f" dDICT{v.get('diff_lo99')}" if 'diff_lo99' in v else "") + ("*" if v['pass'] else "")
                                  for k, v in a["plants"].items()))
        md.append("")
    (O / "census_summary.json").write_text(json.dumps(summ, indent=1, default=str))
    (O / "census_tables.md").write_text("\n".join(md))
    for fam, s in summ.items():
        print(fam, s["funnel"], s["first_failing_clause"])


if __name__ == "__main__":
    main()
