"""Generates ensorain/PREREG_WTP_LM01_TABLES.md from dev/margins_reduced_v2.json (the operator-ruled reduction). It is
frozen together with PREREG_WTP_LM01.md. No number in the tables is hand-copied."""
import json
import os

import numpy as np

HERE = os.path.dirname(__file__)
OUT = os.path.join(HERE, "..", "PREREG_WTP_LM01_TABLES.md")
N_CAMPAIGN = 48


def fmt(x, p=2):
    return "-" if x is None else (f"{x:.{p}f}" if isinstance(x, float) else str(x))


def main():
    R = json.load(open(os.path.join(HERE, "dev", "margins_reduced_v2.json")))
    walls = {}
    for sub in ("margins", "margins_f5real"):
        d = os.path.join(HERE, "dev", sub)
        if not os.path.isdir(d):
            continue
        for fn in os.listdir(d):
            key = fn[:-6].replace("__", "|")
            if sub == "margins" and key.startswith("F5_nuisance"):
                continue
            w = [json.loads(l).get("wall") for l in open(os.path.join(d, fn))]
            walls[key] = float(np.median([x for x in w if x])) if any(w) else 0.0
    L = ["# PREREG_WTP_LM01 -- per-stratum tables (generated by ensorain/lm01/prereg_tables.py; frozen with the prereg)", "",
         "Source: ensorain/lm01/dev/margins_reduced_v2.json (operator rules 2026-09-26: DELTA = 0.30 AC governing; D9; F5",
         "real-cells scale). CI = 90% t-interval over the 16 dev margin worlds. Sensitivity columns (0.15 / 0.60) are",
         "DESCRIPTIVE ONLY and never replace 0.30.", "",
         "Columns: frame | N_MIN | median n_test | gain CI lower bound (max arm - N1) | E6 posctl CI lo | posctl pass |",
         "N_REP (replication block; floor 8, cap 64) | warm-full minus L-R (mean) | visits/cell | frame@.15 | frame@.60 |",
         "unstable arms (replicate p97.5 > 1 AC)", "",
         "```"]
    n_test_strata = 0
    est = 0.0
    for k, v in R.items():
        if v.get("delta") is None:
            L.append(f"{k:<27} UNTESTED  ({v.get('reason')})")
            continue
        s = v["sensitivity"]
        unst = ",".join(f for f, st in v["stability"].items() if st["p975"] > 1.0) or "-"
        pc = v["posctl_ci"]
        end = v["end_warm_minus_LR"]
        L.append(f"{k:<27} {v['frame']:<9} {fmt(v['n_min']):>4} {v['median_n_test']:>5.0f} {fmt(v['gain_ci']['lo']):>6} "
                 f"{fmt(pc['lo'] if pc else None):>6} {str(v['posctl_pass']):>5} {fmt(v['n_rep']):>3} "
                 f"{fmt(end['mean'] if end else None):>6} {fmt(v['visits_per_cell'], 1):>4} "
                 f"{s['0.15']['frame'][:4]:>4} {s['0.6']['frame'][:4]:>4} {unst}")
        if v["frame"] == "TESTABLE":
            n_test_strata += 1
            est += walls.get(k, 0.0) * N_CAMPAIGN
    L.append("```")
    tested = [v for v in R.values() if v.get("frame") == "TESTABLE"]
    L += ["", f"TESTABLE strata at 0.30: {n_test_strata} of {len(R)}. Positive control (E6) passing among TESTABLE: "
          f"{sum(1 for v in tested if v['posctl_pass'])}.",
          f"Campaign compute estimate: {N_CAMPAIGN} worlds x TESTABLE strata x the dev median wall per world "
          f"(8-way parallel, margin-sweep walls) = {est / 3600:.1f} worker-hours = {est / 3600 / 8:.1f} h wall at 8 workers, "
          "before replication blocks. The campaign job omits replicate b but adds the SELECTIVE ladder and L-K "
          "(similar cost; smoke 23-106 s/world at 1 worker)."]
    open(OUT, "w").write("\n".join(L) + "\n")
    return n_test_strata, est


if __name__ == "__main__":
    print(main())
