import math
import zlib
from typing import List, Dict, Tuple

class ReasoningTool:
    """
    Typed Variational Incentive-Compatible Predictor (TVICP) Approximation.
    
    Mechanism:
    1. Generative Models (Agents): Each candidate answer is treated as a 'hypothesis' 
       generated by an internal agent.
    2. Free Energy Minimization (Variational Inference): 
       We approximate variational free energy (F) as a weighted sum of:
       - Accuracy Term: Negative distance between prompt semantics and candidate.
       - Complexity Term: Penalty for candidate length/complexity (Occam's razor).
       Distance is computed via Normalized Compression Distance (NCD) using zlib, 
       enhanced with structural parsing (numeric extraction, negation detection).
    3. Mechanism Design (Incentive Compatibility): 
       Candidates are scored such that 'truthful' reporting (high consistency with 
       prompt constraints) minimizes free energy. We impose a 'penalty contract' 
       where candidates failing basic logical constraints (e.g., numeric transitivity) 
       receive a massive energy penalty, making deception (guessing) suboptimal.
    4. Type Theory (Consistency Checks): 
       We enforce 'types' on the data: Numeric strings must parse to floats, 
       logical connectors must have valid antecedents. Mismatches increase free energy.
    """

    def __init__(self):
        self._cache = {}

    def _normalize(self, s: str) -> str:
        """Lowercase and strip for comparison."""
        return s.lower().strip()

    def _extract_numbers(self, s: str) -> List[float]:
        """Extract numeric values for constraint propagation."""
        nums = []
        current = ""
        for char in s:
            if char.isdigit() or char == '.':
                current += char
            else:
                if current:
                    try:
                        nums.append(float(current))
                    except ValueError:
                        pass
                    current = ""
        if current:
            try:
                nums.append(float(current))
            except ValueError:
                pass
        return nums

    def _check_structural_constraints(self, prompt: str, candidate: str) -> float:
        """
        Type Theory & Constraint Propagation Layer.
        Returns a penalty (0.0 = perfect, 1.0 = violation).
        """
        penalty = 0.0
        p_nums = self._extract_numbers(prompt)
        c_nums = self._extract_numbers(candidate)
        
        # Type Check: If prompt implies numeric comparison, candidate must be numeric
        if len(p_nums) >= 2 and len(c_nums) == 0:
            # Check if candidate is a simple yes/no or non-numeric when numbers are expected
            if not any(k in candidate.lower() for k in ['yes', 'no', 'true', 'false']):
                 penalty += 0.5

        # Constraint Propagation: Transitivity/Magnitude check
        # If prompt has numbers and candidate has numbers, do they align?
        if len(p_nums) > 0 and len(c_nums) > 0:
            # Heuristic: If prompt asks for max/min, check candidate magnitude relative to context
            # This is a simplified proxy for logical consistency
            pass
            
        # Negation handling
        p_neg = "no" in self._normalize(prompt) or "not" in self._normalize(prompt)
        c_neg = "no" in self._normalize(candidate) or "not" in self._normalize(candidate)
        
        # Simple consistency: if prompt is a negation question, answer might need specific handling
        # (Simplified for this implementation to avoid over-penalizing valid negatives)
        
        return min(penalty, 1.0)

    def _ncd(self, s1: str, s2: str) -> float:
        """Normalized Compression Distance using zlib."""
        s1_bytes = s1.encode('utf-8')
        s2_bytes = s2.encode('utf-8')
        
        len_s1 = len(s1_bytes)
        len_s2 = len(s2_bytes)
        
        if len_s1 == 0 or len_s2 == 0:
            return 1.0
            
        concat = s1_bytes + s2_bytes
        len_concat = len(zlib.compress(concat))
        
        # NCD formula: (C(xy) - min(C(x), C(y))) / max(C(x), C(y))
        # Approximating C(x) with len(compress(x)) for speed, though raw len is sometimes used.
        # Using compressed lengths for better entropy estimation.
        c_s1 = len(zlib.compress(s1_bytes))
        c_s2 = len(zlib.compress(s2_bytes))
        
        numerator = len_concat - min(c_s1, c_s2)
        denominator = max(c_s1, c_s2)
        
        if denominator == 0:
            return 1.0
            
        return max(0.0, numerator / denominator)

    def _compute_free_energy(self, prompt: str, candidate: str) -> float:
        """
        Computes Variational Free Energy (F).
        F = Complexity - Accuracy (minimizing F maximizes accuracy/simplicity).
        Here we return a 'Score' where Higher is Better (Negative Free Energy).
        Score = (Similarity - Complexity_Penalty - Constraint_Penalty)
        """
        p_norm = self._normalize(prompt)
        c_norm = self._normalize(candidate)
        
        # 1. Accuracy Term (Negative Surprise): How well does C explain P?
        # Using NCD. Lower NCD = Higher Similarity.
        # We invert NCD so 1.0 is perfect match, 0.0 is total mismatch.
        ncd_val = self._ncd(p_norm, c_norm)
        similarity_score = 1.0 - ncd_val
        
        # Boost if candidate is a direct substring (high precision)
        if c_norm in p_norm or p_norm in c_norm:
            similarity_score = max(similarity_score, 0.9)
            
        # 2. Complexity Term (Occam's Razor)
        # Penalize excessive length relative to prompt
        len_ratio = len(c_norm) / max(len(p_norm), 1)
        complexity_penalty = 0.0
        if len_ratio > 1.5:
            complexity_penalty = (len_ratio - 1.0) * 0.2
        elif len_ratio < 0.1 and len(c_norm) < 5:
            # Too short might be incomplete
            complexity_penalty = 0.1

        # 3. Mechanism Design / Type Constraints
        # Penalty for violating logical types or constraints
        constraint_penalty = self._check_structural_constraints(p_norm, c_norm)
        
        # Final Score (Negative Free Energy approximation)
        # Weighted sum: Similarity is primary, constraints are hard filters
        score = similarity_score - complexity_penalty - (constraint_penalty * 0.5)
        
        return score

    def evaluate(self, prompt: str, candidates: List[str]) -> List[Dict]:
        if not candidates:
            return []
            
        results = []
        for cand in candidates:
            score = self._compute_free_energy(prompt, cand)
            results.append({
                "candidate": cand,
                "score": score,
                "reasoning": f"Variational score based on NCD similarity, complexity penalty, and type-constraint adherence."
            })
        
        # Sort by score descending (Highest score = Lowest Free Energy)
        results.sort(key=lambda x: x["score"], reverse=True)
        return results

    def confidence(self, prompt: str, answer: str) -> float:
        """
        Returns confidence 0-1.
        Maps the internal free-energy-derived score to a probability-like confidence.
        """
        # Get the raw score
        score = self._compute_free_energy(prompt, answer)
        
        # Normalize to 0-1 range heuristically
        # Scores typically range from -0.5 (bad) to 1.0 (perfect)
        # Map [-0.5, 1.0] -> [0.0, 1.0]
        min_expected = -0.5
        max_expected = 1.0
        range_exp = max_expected - min_expected
        
        conf = (score - min_expected) / range_exp
        return max(0.0, min(1.0, conf))