"""Bellerophon COUPLING CAMPAIGN driver (physics v3; roles/Bellerophon/coupling_2026-09-24/COUPLING_CAMPAIGN_PREREG.md).

Phase 1: a FIXED plan (plan()) of seed-matched lanes; YOKED arms depend on their ON partner's per-tick bonus schedule
and run after it. Phase 2: automatic causal follow-ups generated from Phase 1 results by the frozen rule in
phase2_plan() (hashed when generated). Extension blocks: generated by the frozen rule in extension_plan().
Stop: Phase 1 cap 18 h after the first start; Phases 1+2+extensions cap 22 h; no run is re-seeded; a restart
re-executes only runs without a result line (each run is a pure function of its spec).
    python -m prometheus.z80atlas.coupling_campaign --plan-only --inputs <json>
    python -m prometheus.z80atlas.coupling_campaign --workdir <dir> --inputs <json> --workers 20
    python -m prometheus.z80atlas.coupling_campaign --workdir <dir> --status"""
from __future__ import annotations

import argparse
import hashlib
import json
import multiprocessing as mp
import os
import pathlib
import random
import shutil
import statistics as st
import time
from typing import Dict, List, Optional

SEED_BASE = 11_000_000_000_000        # campaign seeds lie in [1.6e11, 2.2e12], grounding 9e12.., pilots 7e12..: disjoint
TICKS, CELLS, BUDGET = 500, 256, 256
COMMON = dict(world="GRID", representation="Z80_64", layout="SHARED", reproduction="ENDOGENOUS_COPY", pressure="IMPLICIT",
              spatial="LOCAL", task="INC", scoring="NEUTRAL", read_gate="ABR", env_dynamics="FIXED", mutation="BYTE",
              mutation_rate="MED", recombination="NONE", init="RANDOM")
K = {"K16": {"base_income": 16, "bonus": 64}, "K40": {"base_income": 40, "bonus": 64}}
V3 = {"physics": "v3", "copy_cost": 1, "resource_cap": 256, "delay": 60}
PHASE1_CAP_H, TOTAL_CAP_H = 18.0, 22.0
# Amendment 1 (2026-09-25, operator-authorised, operational only): when STATUS carries time_rule
# "active_runtime_v1" the caps above are measured in ACTIVE campaign runtime (the sum of execution segments), not wall
# clock from the first start. Suspensions (host OOM, reboot) do not count. A crashed segment is closed at its last
# heartbeat. Scientific content (plan, seeds, physics, detectors, analysis, readiness) is unchanged.
RECYCLE_TASKS = 6                     # Amendment 1: a pool worker is replaced after this many runs (bounds RSS growth)
HEARTBEAT_S = 30
SEED_SHIFT = 0                        # --smoke only: moves every seed (phase 1, AUTO, EXT) off the preregistered streams
LANE_PRIORITY = {"A": 0, "I": 1, "C": 2, "E2": 3, "F": 4, "G": 5, "B-cop": 6, "B-rand": 7, "J": 8, "AUTO": 9, "EXT": 10}


# ---- fixtures ----------------------------------------------------------------------------------------------------
def task_k(seed: int) -> int:
    return random.Random(seed * 7 + 1).randrange(256)        # world.Environment's base_k for this seed (CONST target)


def witness(task: str, k: int = 42) -> bytes:
    from prometheus.z80atlas import vm
    return {"CONST": lambda: vm.witness_const(k), "ECHO": vm.witness_echo, "INC": vm.witness_inc, "COND_ONE": vm.witness_cond_one,
            "COND_MULTI": vm.witness_cond_multi, "SUM2": vm.witness_sum2}[task]()


def fixtures(task: str, seed: int, L: int = 64) -> Dict[str, str]:
    from prometheus.z80atlas import vm
    rep = vm.replicator(L); w = witness(task, task_k(seed))
    hyb = vm.hybrid_relocated(rep, w)
    nocomp = bytes(vm.NOP if b == vm.OUT_A and i >= len(rep) - 1 else b for i, b in enumerate(hyb))
    nocopy = bytes(vm.NOP if b == vm.LDIR else b for b in hyb)
    randout = rep[:-1] + bytes([vm.LD_A_n, 0x33, vm.OUT_A, vm.HALT])
    bad_routine = bytes([vm.LD_T_n, L & 0xFF, vm.LDIR])                   # C = 0: a 256-byte sweep that wrecks the inputs
    bad = bad_routine + vm.relocate(w, len(bad_routine))
    corrupt = bytes([vm.LD_T_n, vm.IN_BASE, vm.LD_A_n, 7, vm.LD_pT_A]) + vm.relocate(vm.hybrid_relocated(rep, w), 5)
    multi = rep[:-1] + vm.relocate(bytes([vm.IN_A, vm.INC_A, vm.OUT_A, vm.OUT_A, vm.OUT_A, vm.HALT]), len(rep) - 1)
    return {"REP": rep.hex(), "HYB": hyb.hex(), "NOCOMP": nocomp.hex(), "NOCOPY": nocopy.hex(), "RANDOUT": randout.hex(),
            "BAD": bad.hex(), "CORRUPT": corrupt.hex(), "MULTI": multi.hex(), "SLIDER": bytes(L).hex()}


# ---- plan ---------------------------------------------------------------------------------------------------------
def plan(inputs: Optional[Dict] = None) -> List[Dict]:
    inputs = inputs or {}
    P: List[Dict] = []
    lanes = {}

    def add(lane, block, cell, arm, k, vec=None, over=None, tapes=(), kname="K16", depends=None):
        ln = lanes.setdefault(lane, len(lanes))
        seed = SEED_BASE + ln * 10 ** 9 + block * 10 ** 5 + k
        o = dict(V3, **K[kname]); o.update(over or {})
        P.append({"lane": lane, "block": block, "cell": cell, "arm": arm, "K": kname, "k": k, "pair": "%s|%d|%d" % (lane, block, k),
                  "vec": dict(COMMON, **(vec or {})), "config_overrides": o, "init_tapes": list(tapes), "seed": seed, "depends": depends})
        return P[-1]

    def seed_of(lane, block, k):
        return SEED_BASE + lanes.setdefault(lane, len(lanes)) * 10 ** 9 + block * 10 ** 5 + k

    # Lane A -- physics qualification (fixture populations: 32 fixture copies in a random majority)
    for bi, kn in enumerate(("K16", "K40")):
        for k in range(40):
            F = fixtures("INC", seed_of("A", bi, k))
            for arm, tape, over in (("A1_hyb_ON", "HYB", {"coupling": "ON"}), ("A2_hyb_OFF", "HYB", {"coupling": "OFF"}),
                                    ("A3_nocomp_ON", "NOCOMP", {"coupling": "ON"}), ("A4_nocopy_ON", "NOCOPY", {"coupling": "ON"}),
                                    ("A5_hyb_SHUFFLED", "HYB", {"coupling": "SHUFFLED"}), ("A6_randout_ON", "RANDOUT", {"coupling": "ON"}),
                                    ("A7_rep_ON", "REP", {"coupling": "ON"})):
                add("A", bi, arm, arm, k, over=over, tapes=[F[tape]], kname=kn)
            if kn == "K16":
                add("A", bi, "A8_rep_v2", "A8_rep_v2", k, over={"physics": "v2", "coupling": "NONE"}, tapes=[F["REP"]], kname=kn)
    # Lane I -- exploit probes (K16, ON)
    for k in range(30):
        F = fixtures("INC", seed_of("I", 0, k))
        add("I", 0, "I1_slider_with_hyb", "ON", k, over={"coupling": "ON"}, tapes=[F["SLIDER"], F["HYB"]])
        add("I", 0, "I2_input_corrupter", "ON", k, over={"coupling": "ON"}, tapes=[F["CORRUPT"]])
        add("I", 0, "I3_multi_output", "ON", k, over={"coupling": "ON"}, tapes=[F["MULTI"]])
    # Lane C -- ablation of the computation -> reproduction edge (mixed REP + HYB, INC)
    for bi, kn in enumerate(("K16", "K40")):
        for k in range(150):
            F = fixtures("INC", seed_of("C", bi, k))
            on = add("C", bi, "C_ON", "ON", k, over={"coupling": "ON"}, tapes=[F["REP"], F["HYB"]], kname=kn)
            for arm in ("OFF", "RANDOM_REWARD", "DELAYED", "IRRELEVANT"):
                add("C", bi, "C_" + arm, arm, k, over={"coupling": arm}, tapes=[F["REP"], F["HYB"]], kname=kn)
            add("C", bi, "C_YOKED", "YOKED", k, over={"coupling": "YOKED"}, tapes=[F["REP"], F["HYB"]], kname=kn, depends=on)
    # Lane E2 -- a damaging hybrid (C = 0 sweep wrecks its own task) + pure copiers: can evolution repair the conflict?
    for bi, kn in enumerate(("K16", "K40")):
        for k in range(60):
            F = fixtures("INC", seed_of("E2", bi, k))
            on = add("E2", bi, "E2_ON", "ON", k, over={"coupling": "ON"}, tapes=[F["REP"], F["BAD"]], kname=kn)
            add("E2", bi, "E2_OFF", "OFF", k, over={"coupling": "OFF"}, tapes=[F["REP"], F["BAD"]], kname=kn)
            add("E2", bi, "E2_YOKED", "YOKED", k, over={"coupling": "YOKED"}, tapes=[F["REP"], F["BAD"]], kname=kn, depends=on)
    # Lane F -- task generality (mixed REP + HYB(task), K16)
    for bi, task in enumerate(("CONST", "ECHO", "INC", "COND_ONE", "SUM2", "COND_MULTI")):
        for k in range(80):
            F = fixtures(task, seed_of("F", bi, k))
            on = add("F", bi, "F_%s_ON" % task, "ON", k, vec={"task": task}, over={"coupling": "ON"}, tapes=[F["REP"], F["HYB"]])
            add("F", bi, "F_%s_OFF" % task, "OFF", k, vec={"task": task}, over={"coupling": "OFF"}, tapes=[F["REP"], F["HYB"]])
            add("F", bi, "F_%s_YOKED" % task, "YOKED", k, vec={"task": task}, over={"coupling": "YOKED"}, tapes=[F["REP"], F["HYB"]], depends=on)
    # Lane G -- substrate dependence (mixed INC, K16, ON vs OFF), one factor at a time
    for bi, (name, vec, over) in enumerate((("copy_cost2", {}, {"copy_cost": 2}), ("ldir_cost4", {}, {"ldir": "cost4"}),
                                             ("undefined_halt", {}, {"undefined_op": "HALT"}), ("mut_low", {"mutation_rate": "LOW"}, {}),
                                             ("mut_vlow", {}, {"mutation_rate": "VLOW"}), ("VM_COPY", {"representation": "VM_COPY"}, {}),
                                             ("BYTECODE32", {"representation": "BYTECODE32"}, {}), ("CONSTRUCTIVE", {"reproduction": "CONSTRUCTIVE"}, {}))):
        for k in range(80):
            sd = seed_of("G", bi, k)
            F = fixtures("INC", sd, L=32 if name == "BYTECODE32" else 64)
            for arm in ("ON", "OFF"):
                add("G", bi, "G_%s_%s" % (name, arm), arm, k, vec=vec, over=dict(over, coupling=arm), tapes=[F["REP"], F["HYB"]])
    # Lane B -- fresh evolution: from random populations (B-rand) and from pure copiers (B-cop)
    for lane, init, tasks, n in (("B-rand", "RANDOM", ("INC", "CONST"), 200), ("B-cop", "SEEDED_REPLICATOR", ("ECHO", "CONST"), 150)):
        bi = 0
        for task in tasks:
            for kn in ("K16", "K40"):
                for k in range(n):
                    on = add(lane, bi, "%s_%s_%s_ON" % (lane, task, kn), "ON", k, vec={"task": task, "init": init}, over={"coupling": "ON"}, kname=kn)
                    add(lane, bi, "%s_%s_%s_OFF" % (lane, task, kn), "OFF", k, vec={"task": task, "init": init}, over={"coupling": "OFF"}, kname=kn)
                    add(lane, bi, "%s_%s_%s_SHUFFLED" % (lane, task, kn), "SHUFFLED", k, vec={"task": task, "init": init}, over={"coupling": "SHUFFLED"}, kname=kn)
                    add(lane, bi, "%s_%s_%s_YOKED" % (lane, task, kn), "YOKED", k, vec={"task": task, "init": init}, over={"coupling": "YOKED"}, kname=kn, depends=on)
                bi += 1
    # Lane J -- historical specimens (each alone as the fixture; ON vs OFF, K16)
    for k, sp in enumerate(inputs.get("historical") or []):
        for arm in ("ON", "OFF"):
            add("J", 0, "J_%s_%s" % (sp["kind"], arm), arm, k, vec={"task": sp["task"], "representation": sp["representation"]},
                over={"coupling": arm}, tapes=[sp["tape"]])
    for i, p in enumerate(P):
        p["id"] = "c%06d" % (i + 1); p["priority"] = LANE_PRIORITY[p["lane"]]
        if p["depends"] is not None:
            p["depends"] = p["depends"]["id"] if isinstance(p["depends"], dict) and "id" in p["depends"] else p["depends"]
    # resolve dependencies to ids (ON partners were appended before their YOKED arms)
    for p in P:
        if isinstance(p["depends"], dict):
            p["depends"] = p["depends"]["id"]
    return P


def plan_hash(P: List[Dict]) -> str:
    return hashlib.sha256(json.dumps(P, sort_keys=True, separators=(",", ":")).encode()).hexdigest()


# ---- one run ----------------------------------------------------------------------------------------------------------
def _run(p: Dict) -> Dict:
    from prometheus.z80atlas.runner import run_spec
    from prometheus.z80atlas import adjudication as A
    from prometheus.z80atlas.world import Config
    rd = pathlib.Path(p["workdir"]) / p["id"]
    if rd.exists():
        shutil.rmtree(rd)
    over = dict(p["config_overrides"])
    if over.get("coupling") == "YOKED":
        over["yoke"] = tuple(p["yoke"])
    spec = {"id": p["id"], "family": "%s:%s" % (p["lane"], p["cell"]), "vec": p["vec"], "seed": p["seed"], "ticks": TICKS, "cells": CELLS,
            "budget": BUDGET, "parents": [], "reason": "coupling %s %s arm=%s pair=%s" % (p["lane"], p["cell"], p["arm"], p["pair"]),
            "stage": "coupling", "workdir": p["workdir"], "init_tapes": p["init_tapes"], "config_overrides": over, "geometry": False}
    t0 = time.time()
    try:
        res = run_spec(spec)
    except Exception as e:                                     # a VOID: recorded, never silently dropped
        return {k: p[k] for k in ("id", "lane", "cell", "arm", "K", "k", "pair", "seed")} | {"void": repr(e)[:500]}
    s = res["summary"]
    cfg_d = json.loads((rd / "config.json").read_text(encoding="utf-8"))["config"]
    cfg = Config(**{k: (tuple(v) if k in ("init_tapes", "yoke") else v) for k, v in cfg_d.items()})
    comp = s.get("competence") or {}
    dom = comp.get("dominant_competent_sr_tape")
    coup = dict(s.get("coupling") or {})
    sched = coup.pop("bonus_schedule", None)
    out = {k: p[k] for k in ("id", "lane", "cell", "arm", "K", "k", "pair", "seed")}
    out.update({"wall_s": round(time.time() - t0, 1), "extinct": s["extinct"], "extinct_tick": s.get("extinct_tick"), "final_alive": s["final_alive"],
                "endogenous_births": s["endogenous_births"], "self_rep_births": s["self_rep_births"], "sr_max_depth": s["sr_max_depth"],
                "sr_alive_end": s["sr_alive_end"], "sr_variants_transmitted": s["sr_variants_transmitted"], "captures": s["captures"],
                "world_copies_under_endogenous": s["world_copies_under_endogenous"], "coupling": coup, "competence": comp,
                "first_self_replication": {k: (s.get("first_self_replication") or {}).get(k) for k in ("tick", "seeded", "tape")} if s.get("first_self_replication") else None,
                "dominant_sr_tape": s.get("dominant_sr_tape"), "verified": s.get("verified"),
                "dominant_competent_arch": A.arch_descriptor(bytes.fromhex(dom), cfg) if dom else None,
                "dominant_sr_arch": A.arch_descriptor(bytes.fromhex(s["dominant_sr_tape"]), cfg) if s.get("dominant_sr_tape") else None,
                "fixture_tapes": p["init_tapes"], "config_sha256": s.get("config_sha256")})
    if p["arm"] == "ON":
        out["bonus_schedule"] = sched
    shutil.rmtree(rd, ignore_errors=True) if p.get("drop_rundir") else None
    return out


# ---- phase 2 and extensions (frozen rules) ------------------------------------------------------------------------------
def _nop(tape_hex: str, ops) -> str:
    return bytes(0 if b in ops else b for b in bytes.fromhex(tape_hex)).hex()


def phase2_plan(results: Dict[str, Dict], P1: List[Dict]) -> List[Dict]:
    """AUTO: candidates = the dominant competent self-replicating tape at the end of an ON run in lanes B-rand, B-cop,
    E2 that is NOT byte-identical to any fixture tape of that run and self-copies AND is fully competent alone
    (arch descriptor self_copy and task_accuracy == 1). First 8 per (lane, cell) by run id; cap 120. Each candidate
    is transplanted ALONE into fresh random populations, 3 seeds, arms: ON, OFF, RANDOM_REWARD, ON with its OUT
    instructions NOPed (task ablation), ON with its copy instructions NOPed (copy ablation)."""
    from prometheus.z80atlas import vm
    by = {}
    for pid in sorted(results):
        r = results[pid]
        if r.get("void") or r["lane"] not in ("B-rand", "B-cop", "E2") or r["arm"] != "ON":
            continue
        a = r.get("dominant_competent_arch"); tape = (r.get("competence") or {}).get("dominant_competent_sr_tape")
        if not a or not tape or tape in r["fixture_tapes"] or not a["self_copy"] or a["task_accuracy"] < 1.0:
            continue
        by.setdefault((r["lane"], r["cell"]), []).append(r)
    cands = []
    for key in sorted(by):
        cands += by[key][:8]
    cands = cands[:120]
    spec_of = {p["id"]: p for p in P1}
    P: List[Dict] = []
    for ci, r in enumerate(cands):
        src = spec_of[r["id"]]; tape = r["competence"]["dominant_competent_sr_tape"]
        variants = (("ON", tape, "ON"), ("OFF", tape, "OFF"), ("RANDOM_REWARD", tape, "RANDOM_REWARD"),
                    ("TASK_ABLATED_ON", _nop(tape, (vm.OUT_A,)), "ON"), ("COPY_ABLATED_ON", _nop(tape, tuple(vm.COPY_OPS)), "ON"))
        for s in range(3):
            seed = SEED_BASE + 50 * 10 ** 9 + ci * 100 + s + SEED_SHIFT
            for arm, t, mode in variants:
                P.append({"lane": "AUTO", "block": ci, "cell": "AUTO_" + arm, "arm": arm, "K": src["K"], "k": s, "pair": "AUTO|%d|%d" % (ci, s),
                          "vec": src["vec"], "config_overrides": dict(src["config_overrides"], coupling=mode), "init_tapes": [t], "seed": seed,
                          "depends": None, "candidate": {"source_run": r["id"], "tape": tape}})
    for i, p in enumerate(P):
        p["id"] = "a%06d" % (i + 1); p["priority"] = LANE_PRIORITY["AUTO"]
    return P


def _paired_halfwidth(xs: List[float]) -> Optional[float]:
    if len(xs) < 5:
        return None
    return 1.96 * st.pstdev(xs) / (len(xs) ** 0.5)


def comp_frac(r: Dict) -> float:
    c = r.get("competence") or {}
    return (c.get("final_competent") or 0) / 256.0


def extension_plan(results: Dict[str, Dict], P1: List[Dict]) -> List[Dict]:
    """EXT: for Lane C K16 and Lane B-cop (each K16 cell), if the 95% CI half-width of the paired ON - YOKED difference
    in final competent fraction exceeds 0.10, add one block of 60 new seeds for every arm of that cell (max one block)."""
    P: List[Dict] = []
    groups = {}
    for p in P1:
        if p["lane"] in ("C", "B-cop") and p["K"] == "K16":
            groups.setdefault((p["lane"], p["block"]), []).append(p)
    for (lane, block), ps in sorted(groups.items()):
        pairs = {}
        for p in ps:
            r = results.get(p["id"])
            if r and not r.get("void"):
                pairs.setdefault(p["k"], {})[p["arm"]] = r
        d = [comp_frac(v["ON"]) - comp_frac(v["YOKED"]) for v in pairs.values() if "ON" in v and "YOKED" in v]
        hw = _paired_halfwidth(d)
        if hw is None or hw <= 0.10:
            continue
        protos = {}
        for p in ps:
            protos.setdefault(p["arm"], p)
        for k in range(1000, 1060):
            seed = SEED_BASE + 60 * 10 ** 9 + (hash_lane(lane) * 100 + block) * 10 ** 5 + k + SEED_SHIFT
            on_id = None
            for arm in sorted(protos, key=lambda a: a != "ON"):
                q = dict(protos[arm]); q = json.loads(json.dumps(q))
                q.update({"lane": "EXT", "k": k, "seed": seed, "pair": "EXT|%s|%d|%d" % (lane, block, k), "ext_of": lane})
                if lane == "C" or lane == "B-cop":
                    ft = fixtures(q["vec"]["task"], seed)
                    q["init_tapes"] = [ft[n] for n in ("REP", "HYB")] if lane == "C" else []
                q["depends"] = on_id if arm == "YOKED" else None
                P.append(q)
                if arm == "ON":
                    on_id = len(P) - 1
    for i, p in enumerate(P):
        p["id"] = "e%06d" % (i + 1); p["priority"] = LANE_PRIORITY["EXT"]
    for p in P:
        if isinstance(p["depends"], int):
            p["depends"] = P[p["depends"]]["id"]
    return P


def hash_lane(lane: str) -> int:
    return int(hashlib.sha256(lane.encode()).hexdigest()[:4], 16) % 97


# ---- execution ---------------------------------------------------------------------------------------------------------
def save_status(st_: Dict, st_path: pathlib.Path) -> None:
    """atomic STATUS write (a kill mid-write can never leave a torn STATUS.json)"""
    tmp = st_path.with_suffix(".tmp")
    tmp.write_text(json.dumps(st_, indent=1), encoding="utf-8")
    os.replace(tmp, st_path)


def _beat(st_: Dict, st_path: pathlib.Path, force: bool = False) -> None:
    now = time.time()
    if force or now - st_.get("heartbeat_ts", 0) >= HEARTBEAT_S:
        st_["heartbeat_ts"] = now
        segs = st_.get("active_segments")
        if segs and segs[-1][1] is None:
            st_["active_elapsed_s"] = round(active_used(st_) + (now - segs[-1][0]), 1)
        save_status(st_, st_path)


def active_used(st_: Dict) -> float:
    """active seconds in CLOSED segments"""
    return sum(e - b for b, e, *_ in st_.get("active_segments") or [] if e is not None)


def repair_tail(res_path: pathlib.Path, st_: Dict) -> None:
    """a line cut by a kill mid-write is not an observation: truncate it (recorded), never merge it with the next"""
    if not res_path.exists():
        return
    raw = res_path.read_bytes()
    if raw and not raw.endswith(b"\n"):
        cut = raw.rfind(b"\n") + 1
        with res_path.open("r+b") as fh:
            fh.truncate(cut)
        st_.setdefault("tail_repairs", []).append({"utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()), "bytes_removed": len(raw) - cut})


def execute(P: List[Dict], wd: pathlib.Path, workers: int, deadline: float, st_: Dict, st_path: pathlib.Path) -> str:
    """Continuous submission: up to 2*workers runs in flight; a YOKED arm is released as soon as its ON partner's result
    is written. Order of release: lane priority, then plan order. Scheduling only -- every run is a pure function of
    its spec, so the order cannot change any result."""
    res_path = wd / "results.jsonl"
    repair_tail(res_path, st_)
    done: Dict[str, Dict] = load_results(wd)
    runs_dir = wd / "runs"; runs_dir.mkdir(exist_ok=True)
    pending = sorted((p for p in P if p["id"] not in done), key=lambda p: (p["priority"], p["id"]))
    stopped = "complete"; inflight = {}; n_written = 0
    import queue as _q
    q: "_q.Queue" = _q.Queue()
    with mp.Pool(workers, maxtasksperchild=RECYCLE_TASKS) as pool, res_path.open("a", encoding="utf-8", newline=chr(10)) as fh:
        while pending or inflight:
            if time.time() < deadline:
                i = 0
                while i < len(pending) and len(inflight) < 2 * workers:
                    p = pending[i]
                    dep = p.get("depends")
                    if dep and dep not in done:
                        if dep not in inflight and not any(x["id"] == dep for x in pending):
                            p["yoke"] = []; p["yoke_partner_void"] = True          # partner never ran (cap): empty yoke
                        else:
                            i += 1; continue
                    elif dep:
                        d = done[dep]
                        if d.get("void") or not d.get("bonus_schedule"):
                            p["yoke"] = []; p["yoke_partner_void"] = True
                        else:
                            p["yoke"] = d["bonus_schedule"]
                    p["workdir"] = str(runs_dir); p["drop_rundir"] = True
                    inflight[p["id"]] = pool.apply_async(_run, (p,), callback=q.put,
                                                         error_callback=lambda e, pid=p["id"]: q.put({"id": pid, "void": "pool: " + repr(e)[:400]}))
                    pending.pop(i)
            elif pending:
                stopped = "wall_cap"; pending = []
            if not inflight:
                if pending:
                    raise RuntimeError("dependency deadlock")
                break
            out = q.get()
            if out["id"] in inflight:
                src = next((p for p in P if p["id"] == out["id"]), {})
                for k in ("lane", "cell", "arm", "K", "k", "pair", "seed"):
                    out.setdefault(k, src.get(k))
                fh.write(json.dumps(out, sort_keys=True, default=str) + chr(10)); fh.flush()
                done[out["id"]] = out; inflight.pop(out["id"])
                n_written += 1
                st_["last_write_utc"] = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()); st_["done"] = len(done)
                _beat(st_, st_path)
    st_["done"] = len(done); _beat(st_, st_path, force=True)
    return stopped


def load_results(wd: pathlib.Path) -> Dict[str, Dict]:
    done = {}
    p = wd / "results.jsonl"
    if p.exists():
        for line in p.read_text(encoding="utf-8").splitlines():
            try:
                r = json.loads(line); done[r["id"]] = r
            except (ValueError, KeyError):
                pass
    return done


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--workdir"); ap.add_argument("--inputs", default=None); ap.add_argument("--workers", type=int, default=20)
    ap.add_argument("--plan-only", action="store_true"); ap.add_argument("--status", action="store_true")
    ap.add_argument("--smoke", type=int, default=0, help="pipeline smoke test: a stratified subset of N runs on seeds shifted off-plan")
    a = ap.parse_args(argv)
    inputs = json.loads(pathlib.Path(a.inputs).read_text(encoding="utf-8")) if a.inputs else {}
    P1 = plan(inputs); h = plan_hash(P1)
    if a.smoke:
        global SEED_SHIFT, PHASE1_CAP_H, TOTAL_CAP_H
        SEED_SHIFT = -3_500_000_000_000
        keep = set(p["pair"] for p in P1[:: max(1, len(P1) // a.smoke)])
        P1 = [dict(p, seed=p["seed"] + SEED_SHIFT) for p in P1 if p["pair"] in keep]
        h = "SMOKE-" + plan_hash(P1)
    if a.plan_only:
        by = {}
        for p in P1:
            by[p["lane"]] = by.get(p["lane"], 0) + 1
        print(json.dumps({"plan_sha256": h, "runs": len(P1), "by_lane": by}, indent=1)); return 0
    wd = pathlib.Path(a.workdir); wd.mkdir(parents=True, exist_ok=True)
    st_path = wd / "STATUS.json"
    st_ = json.loads(st_path.read_text(encoding="utf-8")) if st_path.exists() else {}
    if a.status:
        print(json.dumps(dict(st_, done=len(load_results(wd))), indent=1)); return 0
    if st_.get("phase1_sha256") and st_["phase1_sha256"] != h:
        raise SystemExit("phase-1 plan hash changed since the campaign started: refusing")
    st_.setdefault("phase1_sha256", h); st_.setdefault("first_start_ts", time.time())
    st_.setdefault("starts", []).append(time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()))
    st_.setdefault("workers_by_start", []).append([time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()), a.workers, RECYCLE_TASKS])
    t0 = st_["first_start_ts"]
    if st_.get("time_rule") == "active_runtime_v1":
        segs = st_["active_segments"]
        if segs and segs[-1][1] is None:                      # previous segment crashed: close it at its last heartbeat
            segs[-1][1] = max(segs[-1][0], st_.get("heartbeat_ts") or segs[-1][0]); segs[-1].append("closed at last heartbeat after an interruption")
        now = time.time(); used = active_used(st_)
        segs.append([now, None, "segment %d" % (len(segs) + 1)])
        p1_deadline = now + PHASE1_CAP_H * 3600 - used
        tot_deadline = now + TOTAL_CAP_H * 3600 - used
    else:
        p1_deadline = t0 + PHASE1_CAP_H * 3600
        tot_deadline = t0 + TOTAL_CAP_H * 3600
    _beat(st_, st_path, force=True)
    if st_.get("phase1_stopped") is None:
        st_["phase1_stopped"] = execute(P1, wd, a.workers, p1_deadline, st_, st_path)
        st_["phase1_stopped_utc"] = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()); save_status(st_, st_path)
    done = load_results(wd)
    P2 = phase2_plan(done, P1)
    if st_.get("phase2_sha256") and st_["phase2_sha256"] != plan_hash(P2):
        raise SystemExit("phase-2 plan hash changed: refusing")
    st_["phase2_sha256"] = plan_hash(P2); st_["phase2_runs"] = len(P2)
    (wd / "PHASE2_PLAN.json").write_text(json.dumps(P2, sort_keys=True), encoding="utf-8")
    st_["phase2_stopped"] = execute(P2, wd, a.workers, tot_deadline, st_, st_path)
    done = load_results(wd)
    PE = extension_plan(done, P1)
    st_["ext_sha256"] = plan_hash(PE); st_["ext_runs"] = len(PE)
    (wd / "EXT_PLAN.json").write_text(json.dumps(PE, sort_keys=True), encoding="utf-8")
    st_["ext_stopped"] = execute(PE, wd, a.workers, tot_deadline, st_, st_path)
    st_["stopped_utc"] = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()); st_["stopped"] = True
    if st_.get("time_rule") == "active_runtime_v1" and st_["active_segments"][-1][1] is None:
        st_["active_segments"][-1][1] = time.time()
        st_["active_elapsed_s"] = round(active_used(st_), 1)
    save_status(st_, st_path)
    print(json.dumps({"stopped": True, "phase1": st_["phase1_stopped"], "phase2": st_["phase2_stopped"], "ext": st_["ext_stopped"]}))
    return 0


if __name__ == "__main__":
    mp.freeze_support()
    raise SystemExit(main())
