"""Cut: arduino-pid (Beauregard's Arduino PID library v1; ancestry-aware, Stage A DEEP; SOURCE_READ on M3; position 55 of the
2026-09-17 NOT_CUT order). Read: PID_v1.cpp in full (224 lines). NOT read: PID_v1.h (declarations), keywords.txt. Nothing ran
(C++ for a microcontroller; the arithmetic is host-independent).
"""
from nyx.atlas.author import Cut

P = "vault:arduino-pid/upstream/tree/PID_v1.cpp"
c = Cut("arduino-pid", mode="ANCESTRY_AWARE", inspected=["PID_v1.cpp 1-224"], evidence=[("SOURCE_READ", P + ":1-224")],
        note="a PID whose engineering is in five small decisions, each a separate mechanism: a fixed sample time enforced by a clock check with gains pre-scaled by it; the integral kept as an accumulated OUTPUT term clamped to the output limits (anti-windup) rather than an accumulated error; the derivative taken on the measurement, not the error (no derivative kick on setpoint change); an optional proportional-on-measurement mode folded into the same accumulator; and bumpless transfer by initialising the accumulator from the current output when switching to automatic")

samp = c.organ("fixed_sample_time_enforced_by_a_clock_check_with_integral_and_derivative_gains_pre_scaled_by_the_period", human_name="Compute(): timeChange >= SampleTime gate; SetTunings: ki = Ki * SampleTimeInSec, kd = Kd / SampleTimeInSec; SetSampleTime rescales ki and kd by the ratio", status="ACCEPTED",
    mechanism="Compute returns without acting unless at least SampleTime milliseconds have passed since the last computation; because the period is fixed, the integral gain is multiplied by it and the derivative gain divided by it once at tuning time, so the loop body has no dt arithmetic; changing the sample time rescales the two gains by the ratio so the user's Ki and Kd keep their meaning",
    input="millis(); Kp, Ki, Kd; SampleTime", output="internal kp, ki, kd", state="lastTime, SampleTime", update="per call / per retune", assumptions=["a fixed period is achievable on the target (the loop is called more often than the period); pre-scaling is cheaper than per-call division on an 8-bit micro"],
    fitness_value_in_ancestor="a loop body of a dozen operations with correct units", failure_landscape="by reading: if the loop is called less often than SampleTime the period is whatever the caller gives, and the pre-scaled gains are then wrong (the library does not measure the actual dt)", human_prior="discrete PID with a fixed period (any controls textbook)", evidence_ref=P + ":29-35, 54-62, 72-81", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="the gate and the two rescalings",
    coverage={"input_topology": "SCALAR", "output_topology": "SCALAR", "state_amount": "CONSTANT", "stochasticity": "DETERMINISTIC", "update_topology": "EVENT_DRIVEN", "resource_dependence": "TIME"})

wind = c.organ("integral_kept_as_an_accumulated_output_term_clamped_to_the_output_limits", human_name="Compute(): outputSum += ki * error; clamp outputSum to [outMin, outMax]; SetOutputLimits re-clamps outputSum when limits change", status="ACCEPTED",
    mechanism="instead of summing the error and multiplying by Ki at output time, the integral term is accumulated already multiplied (so retuning Ki does not jump the output) and is clamped to the same limits as the output; when the actuator saturates the accumulator cannot grow past the limit, so there is no wind-up to unwind; the final output is clamped again after adding the P and D terms",
    input="ki * error per sample", output="outputSum", state="outputSum", update="per sample", assumptions=["an actuator at its limit cannot benefit from a larger integral; clamping the term itself is simpler than back-calculation"],
    fitness_value_in_ancestor="no overshoot after saturation; retuning without a bump", failure_landscape="by reading: clamping the sum to the output limits (not to limits minus the P term) means the sum can sit at the limit while the P term pushes the output beyond, which the final clamp absorbs", human_prior="clamping anti-windup (Astrom & Hagglund); the 'accumulate ki*error' trick is the library's blog series", evidence_ref=P + ":36-41, 86-95", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="outputSum's updates and clamps",
    coverage={"input_topology": "SCALAR", "output_topology": "SCALAR", "state_amount": "CONSTANT", "memory": "SUMMARY_STATISTIC", "stochasticity": "DETERMINISTIC", "failure_mode": "NONE_KNOWN"})

dmeas = c.organ("derivative_on_measurement_and_optional_proportional_on_measurement_folded_into_the_accumulator", human_name="Compute(): dInput = input - lastInput; output -= kd * dInput; if (!pOnE) outputSum -= kp * dInput; P_ON_E vs P_ON_M (pOnE)", status="ACCEPTED",
    mechanism="the derivative term uses the change in the measured input, not in the error, so a step in the setpoint produces no derivative spike (derivative kick) while disturbances are still differentiated; with proportional-on-measurement the P term too is accumulated as -kp * dInput into outputSum (integrating the negative of the measurement's change), which removes the proportional jump on setpoint changes for processes where that is wanted",
    input="input, lastInput", output="the D (and optionally P) contribution", state="lastInput", update="per sample", assumptions=["setpoint changes are steps chosen by the user, disturbances are not; only the latter should be differentiated"],
    fitness_value_in_ancestor="smooth response to setpoint changes with the same disturbance rejection", failure_landscape="UNKNOWN by run", human_prior="derivative on measurement is standard practice; P-on-M is the 2017 addition (the blog's 'Introducing Proportional on Measurement')", evidence_ref=P + ":36-46, 56-58", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="the dInput lines and the pOnE switch",
    coverage={"input_topology": "SCALAR", "output_topology": "SCALAR", "state_amount": "CONSTANT", "memory": "LAST_VALUE", "stochasticity": "DETERMINISTIC"})

bump = c.organ("bumpless_manual_to_automatic_transfer_by_initialising_the_accumulator_from_the_current_output_and_the_last_input_from_the_current_input", human_name="SetMode / Initialize(): outputSum = *myOutput; lastInput = *myInput; clamp; SetControllerDirection negates the gains in place", status="ACCEPTED",
    mechanism="when the mode switches from manual to automatic the integral accumulator is set to whatever the output currently is (so the first automatic output equals the last manual one) and the derivative memory to the current input (so no spurious derivative); reversing the controller direction negates the three gains rather than the error",
    input="the current output and input", output="a consistent initial state", state="outputSum, lastInput", update="on mode change", assumptions=["the operator's manual output is the right starting point for the integral"],
    fitness_value_in_ancestor="no jump at hand-over, the property industrial controllers advertise", failure_landscape="UNKNOWN by run", human_prior="bumpless transfer (Astrom & Hagglund)", evidence_ref=P + ":101-116", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="SetMode and Initialize",
    coverage={"input_topology": "EVENT", "output_topology": "EVENT", "state_amount": "CONSTANT", "stochasticity": "DETERMINISTIC", "recovery": "SELF_RESETS"})

c.reject("the getters, the two constructors, the Arduino include guard", reason="GENERIC_LANGUAGE_MECHANICS", evidence=P + ":1-27, 117-124")
c.reject("'PID' as one organ", reason="NAME_HAS_NO_EXECUTABLE_BOUNDARY", evidence="the four decisions are separable and each has its own history (anti-windup, derivative kick, bumpless transfer, sample-time scaling)")

c.edge(samp, wind, "feeds"); c.edge(samp, dmeas, "feeds"); c.edge(bump, wind, "updates"); c.edge(wind, dmeas, "feeds", note="shared accumulator under P_ON_M")

c.pressure("a_feedback_controller_on_a_saturating_actuator_must_track_setpoint_steps_without_overshoot_from_integral_wind_up_or_spikes_from_differentiating_the_step_and_must_hand_over_from_manual_control_without_a_jump",
    condition="an organism drives an actuator with hard limits toward a setpoint that steps; the process has lag; the loop runs at a fixed period on a small processor; hand-over from manual happens mid-run", resource_or_constraint="the actuator's range; one multiply-add budget per sample",
    failure_condition="overshoot after saturation, a derivative spike on a setpoint step, or a jump at hand-over", world_punishes="a textbook PID (error-based integral and derivative, no limits)", world_rewards="clamped output-space integral, derivative on measurement, initialisation from the current output",
    observable_consequence="overshoot, settling time and peak actuator demand on a first-order-plus-lag plant with a saturated actuator, for the four organs enabled one at a time", vacuity_condition="an unsaturated actuator and a constant setpoint", trivial_shortcuts="feedforward from the setpoint (which the world withholds)",
    cheat_control="an organism given the plant model (an exact inverse) must track with zero overshoot at zero derivative kick; the textbook PID must overshoot after saturation; derivative-on-error must spike on the step: the world must show all three",
    cost_class="CPU-scale", source_evidence="PID_v1.cpp Compute, SetTunings, SetMode", purpose="PURPOSE: embedded feedback control (Beauregard 2011-)")

c.ancestry("reimplementation_of", "discrete PID with anti-windup and bumpless transfer (Astrom & Hagglund 1995); the accumulator-in-output-space form is the author's", note="from the record and the author's blog as cited there")
c.residue("EXPLAINED_BY_CURRENT_CUT", ["nothing unread of substance", "nothing ran"], note="224 lines; five decisions, four organs, all located")
c.save(state="DEEP")
