"""Cut: asal-sakana-2024 (SakanaAI ASAL, Automating the Search for Artificial Life, pin 677ba0ea; ancestry-aware, Stage NARROW per the
operator's 2026-09-18 refinery directive s2 -- two mechanisms only, each supporting an intervention; SOURCE_READ on M3; the fossil landed
2026-09-18, census 127). Read: asal_metrics.py calc_open_endedness_score 52-64 (the score) and calc_illumination_score 66-79 (its
sibling); rollout.py rollout_simulation 5-95 (the time-sampling that turns a 256-step rollout into the 8 frames the score sees). NOT read:
the substrates (Lenia, Boids, particle life, NCA), the foundation-model wrappers, the search drivers (asal_search), the JAX plumbing.
Nothing ran here (the JAX path needs AVX, absent on M3; Techne's TECHNE-107 ran a numpy/torch port, and Harmonia's asal_ruler is a
descendant of that port -- both are instruments, not the fossil). This cut binds the mechanism to the fossil's own lines for
MECH-ASAL-LEGIT-SEARCH-001.
"""
from nyx.atlas.author import Cut

M = "vault:asal-sakana-2024/upstream/tree/asal_metrics.py"; R = "vault:asal-sakana-2024/upstream/tree/rollout.py"
c = Cut("asal-sakana-2024", mode="ANCESTRY_AWARE", inspected=["asal_metrics.py 52-79", "rollout.py 5-95"], evidence=[("SOURCE_READ", M + ":52-64"), ("SOURCE_READ", M + ":66-79"), ("SOURCE_READ", R + ":78-95")],
        note="ASAL replaces hand-written artificial-life metrics with a foundation-model observer: a simulation is rolled out, a few frames are embedded by a vision-language model, and 'open-endedness' is scored purely in that embedding space. The score at asal_metrics.py:52-64 is: build the T x T matrix of frame-embedding inner products, keep for each frame only its similarity to STRICTLY EARLIER frames (lower triangle, k=-1), take each frame's maximum such similarity, and average; lower is 'more open-ended'. So the metric rewards a trajectory whose every frame is embedding-dissimilar from all earlier ones -- a property of the frame sequence in the observer's space, not of the underlying dynamics. Techne's TECHNE-107 showed scene-level and colour-level garbage beats living Lenia by this score through CLIP; the open question the operator poses is whether a search over LEGITIMATE Lenia parameters can reach the same exploit")

score = c.organ("open_endedness_as_the_mean_over_frames_of_each_frame_s_maximum_embedding_similarity_to_any_strictly_earlier_frame_minimised", human_name="calc_open_endedness_score (asal_metrics.py:52-64): kernel = z @ z.T; kernel = tril(kernel, k=-1); return kernel.max(axis=-1).mean()", status="ACCEPTED",
    mechanism="the T frame embeddings z (unit vectors from the foundation model) form a T x T inner-product matrix; the strict lower triangle keeps, for frame t, its similarities to frames 0..t-1 only; the row max is the closest earlier frame; the mean of those maxima is the score, minimised, so a low score means every frame is far in embedding space from all its predecessors; frame 0 contributes 0 (empty row) by construction; the sibling calc_illumination_score does the same across simulations (diagonal set to -inf) to spread a POPULATION rather than a trajectory",
    input="z, a T x D array of frame embeddings", output="a scalar (lower = more open-ended)", state="none", update="per rollout", assumptions=["embedding-space dissimilarity between successive frames is a usable proxy for open-ended novelty (ASAL's thesis); the foundation model's geometry is trusted as the arbiter of 'different'"],
    fitness_value_in_ancestor="ALife phenomena searchable by phenotype without hand-authored features; the paper's contribution", failure_landscape="by reading, and confirmed by TECHNE-107 (E1): the metric rewards any process that makes embeddings drift, whether or not the underlying system is alive or novel; scene garbage (0.817) and a colour cycle (0.837) beat a living Orbium (0.847) through CLIP; the observer regularises pixel noise (0.866) but not structured garbage; recurrence (a 2-frame cycle) is punished, so the exploit is drift, not mere change",
    human_prior="Kumar, Lu, Lange, Tang, Ha et al. 2024 (ASAL); the max-cosine-to-earlier-frame form is asal_metrics.py's", evidence_ref=M + ":52-64", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="calc_open_endedness_score (and its illumination sibling)",
    coverage={"input_topology": "SEQUENCE", "output_topology": "SCALAR", "state_amount": "NONE", "stochasticity": "DETERMINISTIC", "representation_sensitivity": "SENSITIVE", "uncertainty": "POINT"})

samp = c.organ("rollout_reduced_to_k_frames_by_sampling_at_fixed_intervals_so_the_observer_sees_a_short_evenly_spaced_summary_of_a_long_simulation", human_name="rollout_simulation time_sampling branch (rollout.py:78-95): chunk_steps = rollout_steps // K; scan the substrate for rollout_steps; idx_sample = arange(0, rollout_steps, chunk_steps) (or arange(chunk_steps-1, ...) if chunk_ends); render and embed the K sampled states", status="ACCEPTED",
    mechanism="the substrate is stepped for the full rollout (256 steps by default), every state kept; then K evenly spaced indices (K=8 in the default score call) select the frames actually rendered, embedded and scored, either from the interval starts (chunk_ends False) or ends; 'final' returns only the last state and 'video' all of them; so the score sees a fixed-length, evenly-spaced sub-sample of the trajectory, and what happens between samples is invisible to the observer",
    input="an initial state, the substrate, K", output="K rendered frames and their embeddings", state="the rollout's state video", update="per rollout", assumptions=["K evenly spaced frames summarise the trajectory well enough for the embedding metric; the substrate is deterministic given params and rng"],
    fitness_value_in_ancestor="one cheap fixed-size summary per candidate for the search to score", failure_landscape="by reading: sub-sampling means a trajectory that is dynamically rich between samples but embedding-similar at the sample points scores as non-open-ended, and vice versa; the number and placement of samples is a hidden knob of the metric", human_prior="the ASAL rollout API (rollout.py)", evidence_ref=R + ":78-95", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="the K-interval branch of rollout_simulation",
    coverage={"input_topology": "SEQUENCE", "output_topology": "SET", "state_amount": "LINEAR_IN_INPUT", "stochasticity": "SEEDED_RANDOM", "update_topology": "SWEEP"})

c.reject("the substrates (Lenia, Boids, particle life, particle Lenia, NCA, Game-of-Life-like), the foundation-model embedding wrappers (CLIP/DINO), the search drivers (asal_search: supervised, open-endedness, illumination), the published .npz datasets, the JAX plumbing", reason="OTHER", evidence="NOT READ; residue", note="the substrate parameter domain is defined by Harmonia's ruler independently of the score (directive s2); the search driver is the mechanism a downstream bench would inherit if the metric survives")
c.reject("'ASAL' / 'open-ended search' as one organ", reason="NAME_HAS_NO_EXECUTABLE_BOUNDARY", evidence="the observer-metric, the rollout sampling and the search driver are separable; this cut binds the two the operator's question is about")

c.edge(samp, score, "feeds", note="the K frames the score sees")

c.pressure("an_open_ended_search_scored_only_by_an_observer_s_embedding_of_a_few_sampled_frames_must_be_shown_either_to_reward_genuine_dynamical_novelty_or_to_be_crossable_by_drift_producing_configurations_within_the_legitimate_substrate",
    condition="an organism searches a substrate's parameters to minimise the ASAL open-endedness score (mean max-cosine-to-earlier-frame over 8 sampled frames); the score cannot see the dynamics between samples or anything the observer's embedding discards; the question is whether a legitimate (ALIVE) configuration can reach a score at or below what scene-level garbage achieves",
    resource_or_constraint="a fixed rollout-and-embed budget; the substrate's real parameter envelope", failure_condition="for the metric-as-novelty claim: a legitimate ALIVE rollout crossing below the garbage score by drift rather than by any property one would call novelty", world_punishes="trusting an observer-embedding score as a novelty measure without a substrate-side control", world_rewards="a search that finds embedding-dissimilar frame sequences, alive or not",
    observable_consequence="the minimum ALIVE score reached by a preregistered search over the Lenia catalogue and its parameter envelope, versus the garbage score (0.8167) and versus the catalogue with no search; and the class (genuine / metric-exploit / observer-exploit) of the best crosser", vacuity_condition="a substrate too small to produce embedding drift", trivial_shortcuts="free images not tied to any substrate (Harmonia's C-POS-SEARCH control, which is exactly the shortcut the legitimate-search question excludes)",
    cheat_control="feeding fixed garbage frames scores the fixed value regardless of the Lenia parameters (the score depends only on the frames); a free-image search must reach below the garbage score (the channel works); a blank world must score the (T-1)/T ceiling and be NOT_ALIVE: Harmonia's fixture shows all three",
    cost_class="GPU-scale", source_evidence="asal_metrics.py:52-64; rollout.py:78-95; TECHNE-107 (E1); Harmonia's PREREG_ASAL_LEGIT_SEARCH_2026-09-18", purpose="PURPOSE: automated open-ended ALife search (SakanaAI 2024)")

c.ancestry("original", "SakanaAI ASAL (Kumar, Lu, Lange, Tang, Ha, Clune et al. 2024); the substrates descend from Lenia (Chan 2019), Boids (Reynolds 1987), particle life; the observer from CLIP (Radford et al. 2021)", note="from the record and the source")
c.residue("PARTIALLY_EXPLAINED", ["the substrates, the search drivers and the datasets unread (the metric and its frame sampling are what MECH-ASAL-LEGIT-SEARCH-001 tests)", "the JAX path did not run on M3 (no AVX); Harmonia's ruler is a descendant port", "the operator's open falsifier -- a legitimate Lenia search never crossing below garbage -- is the packet's negative outcome"], note="the two mechanisms the operator's question is about are located and bound to the fossil's lines; the packet is the next object")
c.save(state="COARSE")
