"""Cut: basic-computer-games-1978 (HAMURABI and SUPER STAR TREK, BASIC listings from Ahl's 1978 collection; Stage A COARSE; SOURCE_READ
on M3; position 52 of the 2026-09-17 NOT_CUT order). Read: hammurabi.bas in full (119 lines); superstartrek.bas by grep (RND sites,
phaser code 4250-4550, damage 2880-3000). NOT read: the Star Trek program line by line (425 lines). Nothing ran (no BASIC on M3).
"""
from nyx.atlas.author import Cut

HB = "vault:basic-computer-games-1978/upstream/hammurabi.bas"; ST = "vault:basic-computer-games-1978/upstream/superstartrek.bas"
c = Cut("basic-computer-games-1978", mode="ANCESTRY_AWARE", inspected=["hammurabi.bas 10-999", "superstartrek.bas (grep: 370, 475, 820-980, 2880-3000, 4250-4550)"], evidence=[("SOURCE_READ", HB + ":10-999"), ("SOURCE_READ", ST + ":4250-4550")],
        note="two small resource games whose mechanism is a scoring rule over a stochastic resource loop: HAMURABI is a ten-round allocation problem (buy/sell land, feed, plant) with a uniform random yield, a rat loss on even yields, a plague with a fixed probability, population growth from stored grain, and an impeachment rule on starvation; STAR TREK is a grid game where every action costs energy from a shared budget and every hit is a random fraction of the energy committed. They are worlds, not organisms: the cut records the pressure each defines")

loop = c.organ("ten_round_allocation_loop_with_uniform_random_yield_rat_loss_on_even_yields_a_fixed_plague_chance_population_growth_from_stored_grain_and_an_impeachment_threshold_on_starvation", human_name="hammurabi.bas: 310 (land price 17-26), 800 (C = RND*5+1 yield / rats / babies), 515-533 (harvest, rats when C even: E = S/C, immigrants), 540-555 (fed = Q/20; starved D; impeach if D > 0.45 P), 542 (plague: Q < 0 with probability 0.15), 860-896 (final grading by starvation percent and acres per person)", status="ACCEPTED",
    mechanism="each year: report; halve the population on a plague (15 percent); price land at 17-26 per acre (uniform); take buy/sell, feed and plant decisions, each validated against stock, acreage and one tender per ten acres; draw one uniform 1-5 that serves as the yield per acre, then redraw: if the draw is even, rats eat stock/C; immigration = C * (20 A + S) / P / 100 + 1; people fed = Q/20; if more than 45 percent starve the game ends with impeachment; after ten years grade on average starvation percent and acres per person",
    input="three integers per year", output="a report and a grade", state="P, S, A, Y, and the two running tallies", update="per year", assumptions=["one uniform draw reused for yield, rats and immigration is enough randomness for a game; the grade thresholds (3, 10, 33 percent; 7, 9, 10 acres) define what good governance means"],
    fitness_value_in_ancestor="the most copied 'resource management under uncertainty' toy of the era; every constant is visible", failure_landscape="by reading: the same draw C drives yield and immigration, so a bad harvest also means few immigrants (a correlation the player cannot see); plague is independent of everything", human_prior="Ahl 1973 from Dyment's 1968 'The Sumer Game' (record)", evidence_ref=HB + ":310-555, 800, 860-896", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="hammurabi.bas",
    coverage={"input_topology": "VECTOR", "output_topology": "SCALAR", "state_amount": "CONSTANT", "state_persistence": "PER_EPISODE", "feedback": "CLOSED_LOOP", "stochasticity": "SEEDED_RANDOM", "update_topology": "SINGLE_STEP"})

trek = c.organ("shared_energy_budget_spent_by_movement_shields_and_phasers_with_hits_as_a_random_fraction_of_energy_committed_and_random_damage_to_named_subsystems", human_name="superstartrek.bas: 370 (E = 3000, Klingons and stardates random), 475 (FNR), 2880-3000 (damage: a random device D(R1) gains or loses a random amount), 4250-4550 (phasers: X units split over Klingons, hit H = (X/K3 / distance) * (RND + 2), a hit below 15 percent of the target's energy is absorbed)", status="CANDIDATE",
    mechanism="one energy pool pays for warp movement, shields and phaser fire; a phaser volley of X units is divided among the Klingons in the quadrant and scaled by inverse distance and a random factor in [2, 3); a hit smaller than 15 percent of the target's remaining energy does no damage; after actions, with probability 0.2 a random subsystem is damaged or repaired by a random amount, disabling the corresponding command until repaired; Klingons return fire when the ship moves",
    input="commands", output="state changes and messages", state="E, shields, K(I,3), D(1..8)", update="per command", assumptions=["a single budget makes every choice a trade-off; random subsystem damage forces plan changes"],
    fitness_value_in_ancestor="the most copied game of the 1970s (the record); a budget-and-risk loop in 425 lines", failure_landscape="UNKNOWN by run", evidence_ref=ST + ":370, 475, 2880-3000, 4250-4550", confidence="MEDIUM", portability="YES", compatibility="UNKNOWN", utility="UNKNOWN", source_boundary="superstartrek.bas; CANDIDATE because read by grep, not line by line",
    coverage={"input_topology": "EVENT", "output_topology": "MIXED", "state_amount": "CONSTANT", "state_persistence": "PER_EPISODE", "feedback": "CLOSED_LOOP", "stochasticity": "SEEDED_RANDOM", "update_topology": "EVENT_DRIVEN"})

c.reject("the text of the reports, the input validation subroutines (710, 720), the galaxy setup and display code of Star Trek", reason="GENERIC_LANGUAGE_MECHANICS", evidence=HB + ":710-730; " + ST + ":820-1300", note="presentation")
c.reject("'game' as one organ", reason="NAME_HAS_NO_EXECUTABLE_BOUNDARY", evidence="the loop, the random draws and the grading rule are separable constants and could be varied independently")

c.pressure("a_steward_must_allocate_a_stock_across_consumption_investment_and_reserve_under_multiplicative_random_yields_and_rare_catastrophes_when_the_score_is_a_threshold_rule_on_the_worst_year_and_an_average",
    condition="an organism controls three allocations per round of a stock that grows by a random multiplier; a rare catastrophe halves the population; the score punishes any single year above a starvation threshold (game over) and grades the average; the horizon is ten rounds", resource_or_constraint="the stock; ten rounds",
    failure_condition="impeachment (one year over 45 percent starvation) or a low grade", world_punishes="maximising expected growth without a reserve (one bad draw ends the game); hoarding (low grade)", world_rewards="a reserve sized to the worst plausible draw",
    observable_consequence="grade distribution over seeds for greedy, fixed-reserve and adaptive-reserve policies; probability of impeachment per policy", vacuity_condition="deterministic yields", trivial_shortcuts="knowing the seed",
    cheat_control="an organism given next year's draw must never be impeached and score 'fantastic'; a greedy organism must show impeachments in the seed distribution; the adaptive reserve must sit between: the world must show all three",
    cost_class="CPU-scale", source_evidence="hammurabi.bas 310-555, 800, 860-896", purpose="PURPOSE: a teaching game (Ahl 1973 / Dyment 1968)")

c.ancestry("historical_version_of", "Dyment 1968 'The Sumer Game' (DEC FOCAL) -> Ahl 1973 HAMURABI; Mayfield 1971 Star Trek -> Leedom / Ahl 1974-78 Super Star Trek", note="from the record")
c.residue("PARTIALLY_EXPLAINED", ["Star Trek read by grep only", "nothing ran (no BASIC interpreter on M3; the vault's bwbasic would be the world)"], note="both programs are WORLDS in this atlas's sense; recorded so a bench can lift HAMURABI's constants as a pressure definition")
c.save(state="COARSE")
