"""Cut: bdwgc-8.2.6 (the Boehm-Demers-Weiser conservative collector; ancestry-aware, Stage A COARSE; SOURCE_READ on M3; position 39 of
the 2026-09-17 NOT_CUT order). Read: mark.c GC_mark_from 518-640 (the mark loop over descriptors), GC_mark_and_push /
GC_mark_and_push_stack 1343-1420 (the pointer validity test); headers.c GC_find_header / header cache miss / get_index 28-262 (the
two-level block-header index); alloc.c min_bytes_allocd + GC_should_collect 309-456 (the collection trigger), GC_expand_hp_inner
1562-1628 (heap growth and the plausible-address bounds); reclaim.c GC_reclaim_clear 180-212 (sweep to free lists); allchblk.c
GC_freehblk 934-993 (large-block coalescing); blacklst.c 1-60 (comment). NOT read: incremental/generational marking (dirty bits, os_dep.c
5,430 lines), the parallel marker (mark.c 807-1140), finalisation, thread support (pthread_*/win32_threads), typed allocation, the
malloc front ends, the 110 other files. Nothing ran (C; no compiler on M3).
"""
from nyx.atlas.author import Cut

M = "vault:bdwgc-8.2.6/upstream/tree/bdwgc-8.2.6/mark.c"; HD = "vault:bdwgc-8.2.6/upstream/tree/bdwgc-8.2.6/headers.c"; A = "vault:bdwgc-8.2.6/upstream/tree/bdwgc-8.2.6/alloc.c"
R = "vault:bdwgc-8.2.6/upstream/tree/bdwgc-8.2.6/reclaim.c"; AB = "vault:bdwgc-8.2.6/upstream/tree/bdwgc-8.2.6/allchblk.c"; BL = "vault:bdwgc-8.2.6/upstream/tree/bdwgc-8.2.6/blacklst.c"
c = Cut("bdwgc-8.2.6", mode="ANCESTRY_AWARE", inspected=["mark.c 518-640, 1343-1420", "headers.c 28-262", "alloc.c 309-456, 1562-1628", "reclaim.c 180-212", "allchblk.c 934-993", "blacklst.c 1-60"],
        evidence=[("SOURCE_READ", M + ":518-640"), ("SOURCE_READ", M + ":1343-1420"), ("SOURCE_READ", HD + ":28-262"), ("SOURCE_READ", A + ":309-456"), ("SOURCE_READ", A + ":1562-1628"), ("SOURCE_READ", R + ":180-212"), ("SOURCE_READ", AB + ":934-993"), ("SOURCE_READ", BL + ":1-60")],
        note="a mark-sweep collector that never knows which words are pointers: every word in a reachable object (or the stack) whose value falls inside the heap's plausible address range and resolves through a two-level block index to a live block header is treated as a pointer; the cost of that guess is bounded by black-listing pages that false pointers have hit; collection is triggered by bytes allocated since the last GC exceeding a fraction of the estimated scan work")

mark = c.organ("mark_loop_over_a_work_stack_of_ranges_and_descriptors_with_a_credit_budget_and_range_splitting", human_name="GC_mark_from (518-640): mse_start / mse_descr; GC_DS_LENGTH (split at 128 words), GC_DS_BITMAP (one bit per word says 'may be a pointer'), GC_DS_PROC; credit = HBLKSIZE", status="ACCEPTED",
    mechanism="the mark stack holds (start, descriptor) entries; a descriptor is a length (scan every word), a bitmap (scan flagged words: the 'typed' allocation hook), or a procedure; long ranges are split so the stack does not explode (and, under PARALLEL_MARK, halved for stealing); each candidate word is range-checked against the least/greatest plausible heap address, prefetched, then pushed via the header lookup; the loop runs until the stack is empty or a byte credit is spent, so marking can be resumed (the incremental hook)",
    input="roots and grey objects", output="mark bits set in block headers", state="the mark stack (grown on overflow, GC_signal_mark_stack_overflow)", update="per grey object", assumptions=["a fast range test rejects most non-pointers before the header lookup; splitting ranges bounds stack depth independently of object size"],
    fitness_value_in_ancestor="marking cost is per candidate word with a cheap first filter; the same loop serves precise (bitmap) and conservative (length) objects", failure_landscape="by reading: everything that looks like a pointer is retained (the conservative premise); large integer-heavy objects (GC_DS_LENGTH) are scanned in full unless allocated atomic",
    human_prior="Boehm & Weiser 1988 'Garbage collection in an uncooperative environment'", evidence_ref=M + ":518-640", confidence="HIGH", portability="YES", compatibility="UNKNOWN", utility="UNKNOWN", source_boundary="GC_mark_from",
    coverage={"input_topology": "GRAPH", "output_topology": "SET", "state_amount": "LINEAR_IN_INPUT", "state_persistence": "PER_EPISODE", "stochasticity": "DETERMINISTIC", "update_topology": "RECURSIVE", "resource_dependence": "MEMORY"})

ptr = c.organ("pointer_identification_by_a_two_level_block_index_that_maps_any_word_to_a_block_header_or_to_nothing_with_interior_pointers_resolved_by_backward_search", human_name="headers.c GC_find_header / GC_header_cache_miss / get_index (28-262): GC_top_index[hi] -> bottom_index -> hdr; IS_FORWARDING_ADDR_OR_NIL; GC_all_interior_pointers -> GC_base; mark.c GC_mark_and_push (1343-1360) with HBLK_IS_FREE and the black-list add", status="ACCEPTED",
    mechanism="the address space is indexed in two levels (a top array by high bits, optionally hashed, and per-top-entry bottom arrays of per-block header pointers); a candidate word's block is looked up; a nil or forwarding entry means not a heap object (or, for large objects spanning blocks, the forwarding count walks back to the first block); if interior pointers are allowed, GC_base finds the object start; a free block or no header means the word was not a pointer, and the (page, source) pair is added to a black list; otherwise the object's mark bit is set and it is pushed; a small header cache fronts the index",
    input="a word", output="an object to mark, or nothing", state="the index; the header cache; the black lists", update="per candidate", assumptions=["block headers are allocated out of line so a stray write cannot corrupt them; the index answers 'is this a heap pointer' in O(1) for any word, which is what makes conservatism affordable"],
    fitness_value_in_ancestor="no cooperation from the compiler or the program: any C object can be collected", failure_landscape="by reading: false retention is the known cost, bounded by the black lists and by the allocator avoiding black-listed pages for large objects (the comment: false hits from the stack 'can pin a large object that spans the block')",
    human_prior="the 1988 paper's 'page table' plus Boehm's later black-listing (1993 'Space efficient conservative garbage collection')", evidence_ref=HD + ":28-262; " + M + ":1343-1420; " + BL + ":1-60", confidence="HIGH", portability="YES", compatibility="UNKNOWN", utility="UNKNOWN", source_boundary="headers.c + the push functions + blacklst.c's interface",
    coverage={"input_topology": "SCALAR", "output_topology": "DECISION", "state_amount": "LINEAR_IN_INPUT", "state_persistence": "PERSISTENT", "memory": "SUMMARY_STATISTIC", "stochasticity": "DETERMINISTIC", "failure_mode": "DEGRADES"})

trig = c.organ("collection_triggered_when_bytes_allocated_since_the_last_gc_exceed_the_estimated_scan_work_over_a_divisor_and_heap_grown_with_a_slop_that_forces_a_gc_before_it_is_used", human_name="alloc.c min_bytes_allocd (309-350): scan_size = 2 composite + atomic/4 + 2 stack + roots; result = scan_size / GC_free_space_divisor (halved if incremental); GC_should_collect (430-456); GC_expand_hp_inner (1562-1628): expansion_slop, GC_collect_at_heapsize, the plausible-address bounds", status="ACCEPTED",
    mechanism="a collection is due when the adjusted bytes allocated since the last GC reach an estimate of the marking work (composite bytes counted twice, atomic bytes a quarter, stacks twice, roots once) divided by the free-space divisor (default 3), or when the heap reaches a size set at the last expansion; expanding the heap adds a slop (the same estimate plus a constant) to the plausible-address bounds so black-listing keeps working, and schedules the next forced collection just before the slop would be consumed; a maximum heap size can refuse expansion",
    input="allocation counters; the heap size", output="collect now / not yet; grow / refuse", state="GC_bytes_allocd, GC_collect_at_heapsize, the bounds", update="per allocation that finds no free object", assumptions=["the cost of a GC is proportional to what must be scanned, so amortising it against allocation keeps GC time a bounded fraction of mutator time (the divisor is that fraction's knob)"],
    fitness_value_in_ancestor="no explicit GC calls; the heap grows only when collection did not free enough", failure_landscape="by reading: a program whose live set grows steadily collects more and more often before each expansion (the 'GC before growing' policy); GC_free_space_divisor trades space for time explicitly",
    human_prior="the standard allocation-triggered policy; the scan-work weighting is Boehm's", evidence_ref=A + ":309-456, 1562-1628", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="the trigger and expansion functions",
    coverage={"input_topology": "SCALAR", "output_topology": "DECISION", "state_amount": "CONSTANT", "feedback": "CLOSED_LOOP", "stochasticity": "DETERMINISTIC", "resource_dependence": "MEMORY", "update_topology": "EVENT_DRIVEN"})

sweep = c.organ("lazy_sweep_that_rebuilds_a_free_list_per_object_size_from_the_mark_bits_of_one_block_at_a_time_and_coalesces_free_large_blocks_with_their_neighbours", human_name="reclaim.c GC_reclaim_clear (180-212): walk a block by sz, unmarked objects linked onto the free list and cleared; allchblk.c GC_freehblk (934-993): merge with successor and predecessor free blocks", status="ACCEPTED",
    mechanism="small objects live in blocks of a single size class; after marking, a block is swept only when its size class's free list is empty (lazy), by walking the block and threading every unmarked object onto the list (optionally clearing it); a block with no marks is returned whole; large blocks are freed into a free list keyed by size and merged with a free successor (by address) and a free predecessor (found via the header index), with the merged header removed",
    input="mark bits; freed large blocks", output="free lists; coalesced blocks", state="the free lists per size class; the large-block lists", update="per allocation miss / per large free", assumptions=["sweeping on demand spreads the cost across allocations; size-segregated blocks make the sweep a stride walk"],
    fitness_value_in_ancestor="no sweep pause; allocation from a free list is a pop", failure_landscape="UNKNOWN by run", evidence_ref=R + ":180-212; " + AB + ":934-993", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="the two functions",
    coverage={"input_topology": "SET", "output_topology": "SET", "state_amount": "LINEAR_IN_INPUT", "state_persistence": "PERSISTENT", "stochasticity": "DETERMINISTIC", "update_topology": "EVENT_DRIVEN"})

c.reject("incremental and generational collection (dirty-page tracking in os_dep.c, GC_collect_a_little), the parallel marker (mark.c 807-1140: work stealing from a shared mark stack), finalisation (finalize.c), thread stop-the-world (pthread_stop_world.c, win32_threads.c), typed and gcj allocation, the malloc/realloc front ends, leak detection, dyn_load", reason="OTHER", evidence="NOT READ (~40,000 lines); residue", note="the parallel marker and the incremental dirty-bit scheme are each a mechanism family; a DEEP pass should take them separately")
c.reject("'garbage collector' as one organ", reason="NAME_HAS_NO_EXECUTABLE_BOUNDARY", evidence="marking, pointer identification, triggering and sweeping are four files with four separable policies")

c.edge(ptr, mark, "gates", note="which words are pointers"); c.edge(trig, mark, "feeds", note="starts a cycle"); c.edge(mark, sweep, "feeds", note="mark bits"); c.edge(sweep, ptr, "feeds", note="free blocks are non-pointers")

c.pressure("live_memory_must_be_reclaimed_without_knowing_which_words_are_pointers_while_keeping_false_retention_and_collection_time_bounded_fractions_of_the_heap_and_the_mutator",
    condition="an organism manages a heap for a program that gives no type information and may hold pointers anywhere in registers, stacks and objects; it must free unreachable memory, never free reachable memory, and keep its own time and the memory it wrongly retains bounded", resource_or_constraint="the heap; a per-word test budget",
    failure_condition="freeing a reachable object (unsafe), or retention/pause growing with heap size", world_punishes="treating every word as a pointer with no index (unbounded scan); treating none (leaks everything)", world_rewards="a range filter plus an O(1) block index; black-listing false hits; allocation-proportional triggering",
    observable_consequence="bytes falsely retained and GC time fraction vs heap size, on a program that stores random integers in large arrays (the conservative worst case), with black-listing on and off and with the free-space divisor varied", vacuity_condition="a program that keeps no integers that look like addresses", trivial_shortcuts="a precise collector with compiler cooperation (which the world must withhold)",
    cheat_control="an organism given precise pointer maps must retain zero false bytes (the bound); with black-listing disabled false retention on the integer-array program must rise; with the divisor at 1 GC time must dominate: the world must show all three",
    cost_class="CPU-scale", source_evidence="mark.c; headers.c; alloc.c 309-456; blacklst.c", purpose="PURPOSE: memory management for uncooperative languages (Boehm, Demers, Weiser 1988-)")

c.ancestry("algorithm_from", "Boehm & Weiser 1988; black lists Boehm 1993; parallel and incremental extensions later (Boehm, Demers, Shenker 1991 for the incremental scheme)", note="from the source headers and the record")
c.residue("LARGE_RESIDUE", ["incremental, generational, parallel and threaded paths unread", "finalisation and typed allocation unread", "nothing ran"], note="the four mechanisms of the base collector are located; the rest of the 47,000 lines is platform support and extensions")
c.save(state="COARSE")
