"""Cut: bsd-tcp-4.3-tahoe-1988 (the 4.3BSD-Tahoe TCP, netinet/tcp_*.c; ancestry-aware, Stage A DEEP; SOURCE_READ on M3; position 67 of the
2026-09-17 NOT_CUT order). Read: tcp_input.c 768-826 (the RTT mean-and-deviation update with Karn's rule), 720-760 (three-duplicate-ACK
retransmission), 835-852 (window opening), tcp_timer.c 163-225 (backoff and the slow-start reset), tcp_var.h 132-140. Compared by reading
against the atlas's bsd-tcp-4.2-1983 (BEFORE) and bsd-tcp-4.3-reno-1990 (AFTER) cuts. NOT read: tcp_output.c, tcp_reass, the state
machine, tcp_mss. Nothing ran (kernel C).
"""
from nyx.atlas.author import Cut

I = "vault:bsd-tcp-4.3-tahoe-1988/upstream/tcp_input.c"; T = "vault:bsd-tcp-4.3-tahoe-1988/upstream/tcp_timer.c"; V = "vault:bsd-tcp-4.3-tahoe-1988/upstream/tcp_var.h"
c = Cut("bsd-tcp-4.3-tahoe-1988", mode="ANCESTRY_AWARE", inspected=["tcp_input.c 720-852", "tcp_timer.c 163-225", "tcp_var.h 132-140"], evidence=[("SOURCE_READ", I + ":768-826"), ("SOURCE_READ", I + ":720-760"), ("SOURCE_READ", I + ":835-852"), ("SOURCE_READ", T + ":163-225")],
        note="the REDESIGN in the congestion lineage, read against both neighbours: everything 4.2BSD had is still here, and three things are new -- (1) the retransmit timer is srtt plus twice a smoothed mean deviation, both kept in fixed point, with Karn's rule (a measured sample cancels the backoff; the timer is not restarted on retransmitted data); (2) a congestion window opened exponentially below ssthresh and linearly above it, reset to one segment on timeout; (3) three duplicate ACKs retransmit the missing segment and set cwnd to one segment (fast retransmit WITHOUT fast recovery). Reno two years later added the mss/8 term to the linear increase and the inflate/deflate that keeps the pipe full after a fast retransmit; both are absent here by reading")

rtt = c.organ("retransmit_timer_from_a_smoothed_rtt_plus_twice_a_smoothed_mean_deviation_in_fixed_point_with_karn_s_rule", human_name="tcp_input.c 768-826: delta = t_rtt - 1 - (t_srtt >> 3); t_srtt += delta; delta = |delta| - (t_rttvar >> 2); t_rttvar += delta; first sample: srtt = rtt << 3, rttvar = rtt << 1; t_rxtshift = 0 on a measured sample; RTO = ((srtt >> 2) + rttvar) >> 1 bounded by TCPTV_MIN / REXMTMAX; the comment 'This replaces rfc793's wired-in beta'", status="ACCEPTED",
    mechanism="each measured round trip updates the smoothed RTT by one eighth of the error (srtt kept scaled by 8 so the update is an integer shift) and a smoothed mean deviation by one quarter of the absolute error (scaled by 4); the retransmit timeout is srtt + 2 rttvar; a sample is taken only for a segment that was not retransmitted (the timer is not restarted on retransmission) and a measured sample resets the exponential backoff shift, which is Karn's algorithm; the first sample seeds the deviation at half the RTT so the first timeout is 2 RTT",
    input="one timed segment at a time", output="t_rxtcur", state="t_srtt, t_rttvar, t_rxtshift", update="per measured round trip", assumptions=["a fixed multiplier (4.2's beta = 2) under-estimates the timeout on variable paths and over-estimates it on stable ones; a variance term tracks the path's variability; integer shifts are cheap on 1988 hardware"],
    fitness_value_in_ancestor="the spurious retransmissions that fed the 1986 collapse stop; the estimator every TCP still uses (RFC 6298)", failure_landscape="by reading: the mean deviation under-estimates the standard deviation (Jacobson chose it for cost); the sample granularity is the 500 ms tick, so RTTs below it are all 'one tick'", human_prior="Jacobson 1988 appendix A; Karn & Partridge 1987", evidence_ref=I + ":768-826; " + V + ":132-140", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="the RTT block",
    coverage={"input_topology": "EVENT", "output_topology": "SCALAR", "state_amount": "CONSTANT", "memory": "SUMMARY_STATISTIC", "feedback": "DELAYED_CLOSED_LOOP", "stochasticity": "ENVIRONMENT_RANDOM", "update_topology": "EVENT_DRIVEN"})

cwnd = c.organ("congestion_window_opened_by_one_segment_per_ack_below_ssthresh_and_by_mss_squared_over_cwnd_above_it_reset_to_one_segment_on_timeout", human_name="tcp_input.c 835-852: incr = mss; if cwnd > ssthresh then incr = max(mss^2 / cwnd, 1); cwnd = min(cwnd + incr, IP_MAXPACKET); tcp_timer.c 216-223: on REXMT, ssthresh = max(2, min(wnd, cwnd) / 2 / mss) * mss, cwnd = mss", status="ACCEPTED",
    mechanism="the sender's window is capped by snd_cwnd; each new ACK adds one segment while cwnd is at or below ssthresh (doubling per round trip) and mss^2 / cwnd above it (one segment per round trip); on a retransmit timeout the threshold is set to half the outstanding window (at least two segments) and cwnd to one segment; no mss/8 term (Reno's addition) and the increase is applied at the ACK site only",
    input="ACKs; timeouts", output="the send window", state="snd_cwnd, snd_ssthresh", update="per ACK / per timeout", assumptions=["packet loss means congestion; the network's capacity is found by exponential probing and held by linear probing (the AIMD argument of Jacobson 1988 and Chiu & Jain 1989)"],
    fitness_value_in_ancestor="the end of congestion collapse on the 1986-88 ARPANET; this file is the origin of the mechanism", failure_landscape="by reading: after any loss the window restarts from one segment (slow start), so a single loss on a long path costs the whole pipe (Reno's motivation)", human_prior="Jacobson 1988", evidence_ref=I + ":835-852; " + T + ":216-223", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="the cwnd arithmetic",
    coverage={"input_topology": "EVENT", "output_topology": "SCALAR", "state_amount": "CONSTANT", "feedback": "DELAYED_CLOSED_LOOP", "stochasticity": "ENVIRONMENT_RANDOM", "update_topology": "EVENT_DRIVEN", "failure_mode": "OSCILLATES"})

fast = c.organ("three_duplicate_acks_retransmit_the_missing_segment_and_restart_slow_start_from_one_segment_without_fast_recovery", human_name="tcp_input.c 720-760: t_dupacks; tcprexmtthresh 3; on the third: ssthresh = half the window, snd_nxt = ack, cwnd = mss, tcp_output, snd_nxt restored; the comment 'Leave here with the congestion window set to allow 2 packets on the next real ack'; NO cwnd inflation branch, NO deflate on the next new ACK", status="ACCEPTED",
    mechanism="a pure duplicate ACK increments a counter; at three, the sender infers a loss without waiting for the timer, sets the threshold to half the window, pulls snd_nxt back to retransmit exactly the missing segment, and sets cwnd to one segment so that the following ACKs open the window by slow start from scratch; the counter resets on any non-duplicate ACK; nothing inflates the window during the duplicates and nothing deflates it after",
    input="duplicate ACKs", output="one early retransmission and a slow-start restart", state="t_dupacks", update="per ACK", assumptions=["three duplicates mean a loss, not reordering; the pipe is allowed to drain (the cost Reno removed)"],
    fitness_value_in_ancestor="a loss costs one round trip of detection rather than a timer expiry", failure_landscape="by reading: the pipe empties after every fast retransmit; throughput on lossy long paths is bounded by slow-start restarts (Fall & Floyd 1996 measured the gap to Reno)", human_prior="Jacobson's fast retransmit (1988 revision); fast recovery is the 1990 Reno addition", evidence_ref=I + ":720-760", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="the duplicate-ACK block",
    coverage={"input_topology": "EVENT", "output_topology": "EVENT", "state_amount": "CONSTANT", "feedback": "DELAYED_CLOSED_LOOP", "stochasticity": "ENVIRONMENT_RANDOM", "update_topology": "EVENT_DRIVEN", "recovery": "RETRIES"})

c.reject("the 1983 organs still present (windows, persist, keepalive, delayed ACK, the 500 ms tick, the backoff table with the srtt clobber)", reason="OTHER", evidence="cut as organs of bsd-tcp-4.2-1983 in this atlas; unchanged here by grep", note="the backoff table and the ten-strike drop survive verbatim")
c.reject("tcp_output.c, tcp_reass, the state machine, tcp_mss, header prediction (present at 4.3-Reno; NOT checked here)", reason="OTHER", evidence="NOT READ; residue")
c.reject("'TCP' as one organ", reason="NAME_HAS_NO_EXECUTABLE_BOUNDARY", evidence="the three additions are separately motivated in Jacobson 1988 and were separately extended by Reno")

c.edge(rtt, cwnd, "feeds", note="timeouts trigger the reset"); c.edge(fast, cwnd, "updates", note="ssthresh and cwnd"); c.edge(cwnd, fast, "gates", note="the window state the dupack block halves")

c.pressure("a_sender_must_avoid_both_spurious_retransmissions_on_a_variable_path_and_congestion_collapse_on_a_shared_one_using_only_ack_timing_and_absence_and_must_recover_from_a_single_loss_faster_than_a_timer",
    condition="many senders share bottlenecks whose delay varies by a factor of several within a connection; the only feedback is ACKs and their absence; the score is goodput under load and the count of unnecessary retransmissions", resource_or_constraint="one timed segment; integer arithmetic",
    failure_condition="collapse (goodput falls as load rises) or a high spurious-retransmission rate on variable paths", world_punishes="a fixed timer multiplier; sending the advertised window; timing retransmitted segments", world_rewards="a variance-aware timer, Karn's rule, AIMD with slow start, early retransmit on duplicates",
    observable_consequence="goodput of N flows vs offered load, and spurious retransmissions vs RTT variance, for the 1983, Tahoe and Reno bodies on the same emulated network", vacuity_condition="one flow on a constant-delay link", trivial_shortcuts="explicit congestion signals from the routers (withheld)",
    cheat_control="an organism told the bottleneck rate and the RTT distribution must show zero spurious retransmissions and full goodput; the 1983 body must collapse under N flows; Tahoe must show the slow-start dip after each fast retransmit that Reno's recovery removes: the world must show all three",
    cost_class="CPU-scale", source_evidence="tcp_input.c 720-852; tcp_timer.c 163-225; Jacobson 1988; Fall & Floyd 1996 as cited by the record", purpose="PURPOSE: end-to-end congestion control, the original (Jacobson & Karels 1988)")

c.ancestry("derived_from", "bsd-tcp-4.2-1983 (in this atlas) with Jacobson & Karels' 1988 additions; bsd-tcp-4.3-reno-1990 (in this atlas) is its successor: the lineage's three source bodies are now all cut", note="by reading all three")
c.residue("PARTIALLY_EXPLAINED", ["tcp_output and the state machine unread", "nothing ran; the three bodies would make a three-arm world on an emulated network (an M2 world)"], note="the middle of the lineage; the three organs are exactly the 1988 paper's three contributions, located line by line, with Reno's two later additions confirmed absent")
c.save(state="DEEP")
