"""Cut: bsd-tcp-4.3-reno-1990 (the 4.3BSD-Reno TCP, netinet/tcp_*.c; ancestry-aware, Stage A DEEP; SOURCE_READ on M3; position 35
of the 2026-09-17 NOT_CUT order). Read: tcp_input.c header prediction 355-420, the ACK processing 775-905 (duplicate ACKs, fast
retransmit, fast recovery, cwnd opening), tcp_timer.c TCPT_REXMT 147-232 (backoff, slow-start reset). NOT read: tcp_reass, the
state machine below 905, tcp_output.c (493 lines), tcp_subr.c, tcp_usrreq.c, tcp_mss. The 4.2BSD (1983) body is cut in this atlas
(bsd-tcp-4.2-1983) and the comparison below is by reading both. Nothing ran (kernel C).
"""
from nyx.atlas.author import Cut

I = "vault:bsd-tcp-4.3-reno-1990/upstream/tcp_input.c"; T = "vault:bsd-tcp-4.3-reno-1990/upstream/tcp_timer.c"
c = Cut("bsd-tcp-4.3-reno-1990", mode="ANCESTRY_AWARE", inspected=["tcp_input.c 355-420, 775-905", "tcp_timer.c 147-232"], evidence=[("SOURCE_READ", I + ":355-420"), ("SOURCE_READ", I + ":775-905"), ("SOURCE_READ", T + ":147-232")],
        note="the SUCCESSOR in the congestion-control lineage: everything the 4.2BSD cut found (RTT smoothing, backoff, windows, persist, keepalive, delayed ACK, the 500 ms tick) is still here; what is NEW is a congestion window snd_cwnd distinct from the peer's window, opened exponentially below a threshold and linearly above it, reset to one segment on timeout, and (Reno's own addition) a duplicate-ACK counter that retransmits and halves the window without waiting for the timer while keeping the pipe full ('fast recovery')")

cwnd = c.organ("congestion_window_separate_from_the_advertised_window_opened_exponentially_below_a_threshold_and_linearly_above", human_name="tcp_input.c 885-900 (cw > ssthresh ? incr = mss^2/cw + mss/8 : incr = mss); tcp_output.c 89 (win = min(snd_wnd, snd_cwnd)); tcp_timer.c 222-229 (reset on timeout)", status="ACCEPTED",
    mechanism="the sender's usable window is the minimum of the receiver's advertisement and a local snd_cwnd; each new ACK adds one segment to cwnd while cwnd < ssthresh (doubling per round trip), and mss^2/cwnd plus mss/8 above it (about one segment per round trip); on a retransmit timeout ssthresh becomes half the window in flight (at least two segments) and cwnd becomes one segment, restarting the exponential phase",
    input="ACKs; timeouts", output="the send window", state="snd_cwnd, snd_ssthresh", update="per ACK / per timeout", assumptions=["packet loss signals congestion; the network's capacity is discovered by probing upward and backing off multiplicatively on loss (the AIMD premise)"],
    fitness_value_in_ancestor="the 1986 congestion collapse ended; the sender no longer dumps a full window after a loss", failure_landscape="by reading: loss is the only signal, so the window oscillates around the bottleneck (the sawtooth); the mss/8 term ('to help larger windows open quickly enough') is a tuning constant without derivation",
    human_prior="Jacobson 1988 'Congestion Avoidance and Control' (the Tahoe algorithms); this file is the Reno release of them", evidence_ref=I + ":885-900; " + T + ":222-229", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="the cwnd arithmetic in the three files",
    coverage={"input_topology": "EVENT", "output_topology": "SCALAR", "state_amount": "CONSTANT", "state_persistence": "PERSISTENT", "feedback": "DELAYED_CLOSED_LOOP", "stochasticity": "ENVIRONMENT_RANDOM", "update_topology": "EVENT_DRIVEN", "failure_mode": "OSCILLATES"})

fast = c.organ("three_duplicate_acks_trigger_retransmission_and_window_halving_before_the_timer_then_inflate_the_window_per_further_duplicate_to_keep_the_pipe_full", human_name="tcp_input.c 790-855: t_dupacks, tcprexmtthresh = 3, the 'Kludge snd_nxt & the congestion window so we send only this one packet' block, the inflate branch, and the deflate on the next new ACK", status="ACCEPTED",
    mechanism="a pure duplicate ACK (no data, unchanged window, ack == snd_una, retransmit timer running) increments t_dupacks; at exactly three: ssthresh = half the flight (min 2 segments), snd_nxt is pulled back to the acked point, cwnd is set to ONE segment so tcp_output sends exactly the missing segment, then cwnd is set to ssthresh + 3 segments and snd_nxt restored; each further duplicate adds one segment to cwnd and calls tcp_output (new data flows as duplicates confirm departures); the first ACK that advances snd_una deflates cwnd back to ssthresh and zeroes the counter; any non-duplicate resets the counter",
    input="duplicate ACKs", output="one retransmission; a temporarily inflated window", state="t_dupacks; the saved snd_nxt", update="per ACK", assumptions=["three duplicates mean a loss rather than reordering (tcprexmtthresh is a global tunable); each duplicate ACK proves one packet left the network, so the window may grow by one without adding load ('packet conservation')"],
    fitness_value_in_ancestor="a single loss no longer costs a timeout and a slow-start from one segment; throughput on lightly lossy paths roughly doubled (Fall & Floyd 1996 measured the lineage)", failure_landscape="by reading: the mechanism assumes one loss per window; two losses in a window leave the second to the timer (the NewReno / SACK problem, not addressed in this body); the deflate to ssthresh on the first new ACK is the 'Reno' step Tahoe lacked",
    human_prior="Jacobson's 1990 fast recovery (email to end2end-interest); fast retransmit is Tahoe's", evidence_ref=I + ":790-855", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="the duplicate-ACK block and the deflate lines",
    coverage={"input_topology": "EVENT", "output_topology": "EVENT", "state_amount": "CONSTANT", "feedback": "DELAYED_CLOSED_LOOP", "stochasticity": "ENVIRONMENT_RANDOM", "update_topology": "EVENT_DRIVEN", "recovery": "RETRIES"})

pred = c.organ("header_prediction_fast_path_for_in_sequence_pure_acks_and_pure_data_that_skips_the_state_machine", human_name="tcp_input.c 355-420 (tcppredack / tcppreddat)", status="ACCEPTED",
    mechanism="if the connection is established, the segment has only ACK set, is in sequence, carries the same window and nothing is being retransmitted, then: a zero-length segment whose ACK advances (and cwnd >= snd_wnd, i.e. not in slow start) is handled as a pure ACK (drop acked data, update RTT, restart or stop the timer, wake the writer) and returns; a data segment at the expected ack with an empty reassembly queue and buffer space is appended and a delayed ACK noted; everything else falls through to the full input processing",
    input="a segment", output="handled or fall-through", state="none", update="per segment", assumptions=["bulk transfer in one direction is the common case; the checks are cheaper than the general path"],
    fitness_value_in_ancestor="per-packet processing cost cut for the common case (Van Jacobson's 'header prediction')", failure_landscape="by reading: the fast path bypasses the cwnd opening, which is why it is guarded by cwnd >= snd_wnd (only when cwnd is no longer the constraint)", human_prior="Jacobson 1988 (the header-prediction note)", evidence_ref=I + ":355-420", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="the prediction block",
    coverage={"input_topology": "EVENT", "output_topology": "DECISION", "state_amount": "NONE", "stochasticity": "DETERMINISTIC", "update_topology": "EVENT_DRIVEN"})

c.reject("RTT smoothing (tcp_xmit_timer), timer backoff with the srtt clobber at rxtshift > MAXRXTSHIFT/4 (tcp_timer.c 182-192), persist, keepalive, delayed ACK, the 500 ms tick", reason="OTHER", evidence="present here; cut as organs of bsd-tcp-4.2-1983 in this atlas (the RTT estimator now keeps a variance term, Jacobson 1988: NOT re-read)", note="the variance-based RTO (srtt + 4 rttvar) is the one 1983-to-1990 change in the shared organs that this cut did not read; flagged for a DEEP pass")
c.reject("tcp_reass, the state machine (SYN/FIN handling below 905), tcp_output.c's send decision, tcp_mss (path MTU / route metrics), tcp_subr, tcp_usrreq", reason="OTHER", evidence="NOT READ; residue")
c.reject("'TCP' as one organ", reason="NAME_HAS_NO_EXECUTABLE_BOUNDARY", evidence="the 1983 cut's nine organs plus these three are separable and were added in two documented steps (Tahoe 1988, Reno 1990)")

c.edge(fast, cwnd, "feeds", note="sets ssthresh and cwnd"); c.edge(pred, cwnd, "gates", note="fast path only when cwnd is not the constraint"); c.edge(cwnd, fast, "gates", note="the inflate/deflate arithmetic is on cwnd")

c.pressure("a_sender_sharing_an_unknown_bottleneck_with_others_must_find_its_fair_rate_from_loss_alone_and_recover_from_a_single_loss_without_draining_the_pipe",
    condition="many organisms send through a bottleneck of unknown capacity; the only feedback is ACKs and their absence; a drained pipe costs a round trip of idle capacity; fairness and stability are scored", resource_or_constraint="the bottleneck's capacity and queue; one RTT of feedback delay",
    failure_condition="congestion collapse (goodput falls as load rises), or a single loss costing a timeout-length idle period", world_punishes="sending the advertised window regardless of loss (4.2BSD); waiting for the timer after a loss (Tahoe without fast retransmit)", world_rewards="multiplicative decrease on loss, additive increase between losses, retransmission on duplicate-ACK evidence with the window kept full",
    observable_consequence="goodput and fairness index of N flows vs offered load, and time-to-recover after a single dropped segment, for the 1983, Tahoe and Reno rules on the same queue", vacuity_condition="one flow with a known capacity", trivial_shortcuts="explicit rate signalling from the bottleneck (which the world must withhold)",
    cheat_control="an organism told the bottleneck rate must hold it with zero loss; the 1983 rule must collapse under N flows; Tahoe must show the timeout gap on a single loss that Reno closes: the world must show all three",
    cost_class="CPU-scale", source_evidence="tcp_input.c 790-900; tcp_timer.c 147-232; the record's lineage (Fall & Floyd 1996)", purpose="PURPOSE: end-to-end congestion control (Jacobson 1988-1990)")

c.ancestry("derived_from", "bsd-tcp-4.2-1983 (in this atlas) via 4.3BSD-Tahoe (1988, Jacobson's slow start / congestion avoidance / fast retransmit; body not in the vault); Reno adds fast recovery", note="by reading both bodies; the Tahoe step is inferred from the record and Jacobson 1988")
c.residue("PARTIALLY_EXPLAINED", ["tcp_output's send decision and tcp_mss unread", "the RTT variance estimator not re-read against the 1983 organ", "nothing ran"], note="the three mechanisms that the successor adds are located and bounded; the shared organs are inherited from the 1983 cut")
c.save(state="DEEP")
