"""Cut: buddy-bdd (BuDDy 2.4, Lind-Nielsen; ancestry-aware, Stage A DEEP; SOURCE_READ on M3; position 44 of the 2026-09-17 NOT_CUT
order). Read: src/kernel.c bdd_makenode 1258-1330; src/bddop.c apply_rec 539-644; src/reorder.c reorder_sift_bestpos 468-572 and
reorder_swap 1170-1233. NOT read: bdd_gbc (mark-sweep of the node table), bdd_noderesize, ite_rec and the other operators
(restrict, constrain, compose, exist), the cache structure, the variable-block tree, fdd.c / bvec.c (finite domains, bit vectors),
bddio.c. Nothing ran (C; no compiler on M3).
"""
from nyx.atlas.author import Cut

K = "vault:buddy-bdd/upstream/tree/buddy-2.4/src/kernel.c"; O = "vault:buddy-bdd/upstream/tree/buddy-2.4/src/bddop.c"; R = "vault:buddy-bdd/upstream/tree/buddy-2.4/src/reorder.c"
c = Cut("buddy-bdd", mode="ANCESTRY_AWARE", inspected=["kernel.c 1258-1330", "bddop.c 539-644", "reorder.c 468-572, 1170-1233"], evidence=[("SOURCE_READ", K + ":1258-1330"), ("SOURCE_READ", O + ":539-644"), ("SOURCE_READ", R + ":468-572"), ("SOURCE_READ", R + ":1170-1233")],
        note="reduced ordered BDDs as three mechanisms: a unique table that makes structurally equal nodes the same integer (canonicity is a hash-consing invariant, not a check), a recursive apply on the top variable with a computed-result cache so the recursion is bounded by the product of the operand sizes, and dynamic variable reordering by sifting each variable to the position that minimises the node count, implemented as in-place adjacent-level swaps that preserve every external reference")

uniq = c.organ("unique_table_that_returns_the_existing_node_for_equal_level_low_high_and_collapses_a_node_whose_children_are_equal", human_name="bdd_makenode (kernel.c 1258-1330): low == high -> low; NODEHASH chain walk; free-list pop; on exhaustion bdd_gbc, then reorder via longjmp if node usage crossed usednodes_nextreorder, then resize if free nodes fall below minfreenodes percent", status="ACCEPTED",
    mechanism="a node request (level, low, high) first returns low if the children are equal (the reduction rule), then walks the hash chain for an existing node with the same triple and returns its index; otherwise a node is taken from the free list; if none is free, garbage collect; if the collection reveals the node count has crossed the reorder trigger and reordering is enabled, abandon the current operation by longjmp to the operator entry (which restarts it after reordering); if free nodes are still scarce, grow the table and rehash",
    input="(level, low, high)", output="a node index", state="the node array with hash chains and refcounts; the free list", update="per node creation", assumptions=["hash-consing every node makes equality of functions equality of integers (the ROBDD canonicity theorem, Bryant 1986); the free/gc/resize/reorder ladder keeps the invariant under memory pressure"],
    fitness_value_in_ancestor="satisfiability, equivalence and counting become O(1) or linear in the DAG; the table is the whole representation", failure_landscape="by reading: the longjmp restart of an operation mid-recursion is the cost of reordering from inside makenode; the panic path returns 0 (false) with an error code when nothing can be freed",
    human_prior="Bryant 1986; the unique table with a free list and gc is Brace, Rudell, Bryant 1990 (the CUDD lineage)", evidence_ref=K + ":1258-1330", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="bdd_makenode and the gc/resize hooks it calls",
    coverage={"input_topology": "TREE", "output_topology": "SCALAR", "state_amount": "LINEAR_IN_INPUT", "state_persistence": "PERSISTENT", "memory": "ARCHIVE", "stochasticity": "DETERMINISTIC", "resource_dependence": "MEMORY"})

apply = c.organ("apply_recursion_on_the_lower_top_variable_with_terminal_rules_per_operator_and_a_computed_cache_keyed_by_both_operands_and_the_operator", human_name="apply_rec (bddop.c 539-644): the switch of terminal cases per applyop; oprres for constants; BddCache_lookup(applycache, APPLYHASH(l, r, applyop)); the three level cases; PUSHREF/POPREF around the recursive results", status="ACCEPTED",
    mechanism="for two BDDs and a Boolean operator: apply operator-specific terminal rules (l == r, a constant operand), then consult the cache for (l, r, op); on a miss recurse on the cofactors of whichever operand has the lower level (both if equal), build the result node through makenode, record it in the cache; intermediate results are pushed on a reference stack so a garbage collection inside the recursion cannot free them",
    input="two node indices and an operator code", output="a node index", state="the computed cache (direct-mapped, overwritten on collision)", update="per call", assumptions=["subproblems repeat (shared sub-DAGs), so caching bounds the work by |l| x |r| instead of the exponential recursion tree"],
    fitness_value_in_ancestor="every Boolean operation in time proportional to the product of the operand sizes", failure_landscape="by reading: the cache is direct-mapped, so a collision drops an entry (bdd_setcacheratio tunes it); the cache is cleared on reordering", human_prior="Bryant 1986's Apply; the cache from Brace et al.",
    evidence_ref=O + ":539-644", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="apply_rec (ite_rec and the others share the pattern; not read)",
    coverage={"input_topology": "GRAPH", "output_topology": "GRAPH", "state_amount": "LINEAR_IN_INPUT", "memory": "SUMMARY_STATISTIC", "stochasticity": "DETERMINISTIC", "update_topology": "RECURSIVE"})

sift = c.organ("sifting_reorder_that_moves_each_variable_block_through_all_positions_by_in_place_adjacent_swaps_accepting_a_20_percent_growth_bound_and_returning_to_the_best", human_name="reorder_sift_bestpos (reorder.c 468-572): maxAllowed = best/5 + best; direction by position; blockdown; bestpos; reorder_swap (1170-1233): the four cofactors f00..f11, reorder_makenode, in-place VAR/LOW/HIGH update, rehash", status="ACCEPTED",
    mechanism="for a variable (block): starting toward the nearer end, move it one level at a time (blockdown) as long as the total node count stays within 20 percent above the best seen (or a global cap), recording the best position; then sweep the other direction; finally move back to the best; an adjacent swap of levels v0 < v1 rewrites every v0 node in place as a v1 node over new v0 children built from the four grand-cofactors, so external references (indices) stay valid, and rehashes the node; dead nodes are reclaimed by a local gc afterwards",
    input="the current order", output="a new order with (locally) fewer nodes", state="the node table, rewritten in place", update="per reorder event", assumptions=["node count is unimodal enough along one variable's position that a bounded sweep finds a good position; keeping indices stable is worth the in-place rewrite"],
    fitness_value_in_ancestor="orders of magnitude in size for real circuits without user-chosen orders", failure_landscape="by reading: reordering is O(n^2) swaps in the worst case and blocks all other work; the 20 percent slack is a heuristic constant", human_prior="Rudell 1993 (sifting); the in-place swap is Rudell's / CUDD's",
    evidence_ref=R + ":468-572, 1170-1233", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="the sift and swap functions (win2/win3 and random reorders are variants, not read)",
    coverage={"input_topology": "SEQUENCE", "output_topology": "SEQUENCE", "state_amount": "LINEAR_IN_INPUT", "stochasticity": "DETERMINISTIC", "update_topology": "SWEEP", "order_sensitivity": "SENSITIVE"})

c.reject("bdd_gbc (mark from the reference stack and external refs, sweep to the free list), bdd_noderesize, the cache table, ite_rec / restrict / constrain / compose / exist / simplify, satcount / allsat, the variable block tree, fdd.c and bvec.c, bddio.c", reason="OTHER", evidence="NOT READ; residue", note="satcount and the quantifiers are each a small mechanism on the same recursion pattern")
c.reject("'BDD' as one organ", reason="NAME_HAS_NO_EXECUTABLE_BOUNDARY", evidence="the representation invariant (unique table), the operation (apply + cache) and the optimisation (reorder) are separable and were published in three papers")

c.edge(apply, uniq, "feeds", note="every result node"); c.edge(uniq, sift, "triggers", note="longjmp on the node-count threshold"); c.edge(sift, uniq, "updates", note="rewrites the table in place"); c.edge(sift, apply, "forgets", note="cache cleared")

c.pressure("boolean_functions_over_many_variables_must_be_stored_compared_and_combined_canonically_with_a_size_that_depends_on_a_variable_order_the_organism_must_choose_itself",
    condition="an organism holds many Boolean functions (a circuit, a transition relation) and must answer equivalence and satisfiability and build new functions by AND/OR/NOT; memory is bounded; the representation's size can vary exponentially with the variable order", resource_or_constraint="the node table; the order",
    failure_condition="two equal functions stored differently (a missed equivalence), operations exponential in the DAG size, or a size blow-up under a bad order", world_punishes="tree representations; uncached recursion; a fixed order", world_rewards="hash-consing, a computed cache, and dynamic reordering",
    observable_consequence="node count and operation time on ISCAS-style circuits and on the classic worst case (a multiplier) with reordering on and off", vacuity_condition="functions of few variables", trivial_shortcuts="an order supplied by the world (which it must withhold)",
    cheat_control="an organism given the optimal order must show the minimum node count; a fixed-order organism on a permuted input must show the blow-up; sifting must recover within 20 percent of the given-order size: the world must show all three",
    cost_class="CPU-scale", source_evidence="kernel.c bdd_makenode; bddop.c apply_rec; reorder.c sift", purpose="PURPOSE: symbolic Boolean manipulation (Bryant 1986; Rudell 1993)")

c.ancestry("algorithm_from", "Bryant 1986 (ROBDD, apply); Brace, Rudell, Bryant 1990 (unique table, cache); Rudell 1993 (sifting)", note="from the source and the record")
c.residue("PARTIALLY_EXPLAINED", ["gc, the other operators, quantification and counting unread", "finite-domain and bit-vector layers unread", "nothing ran"], note="the three defining mechanisms are located")
c.save(state="DEEP")
