"""Cut: cosell-eliza-bbn-lisp-1969 (Bernie Cosell's ELIZA in BBN-LISP, 1969 and 1972 versions, transcribed and made to run in Common
Lisp by Shrager et al.; Stage A COARSE; SOURCE_READ on M3; position 53 of the 2026-09-17 NOT_CUT order). Read: the transcription
notes and the BBN-LISP compatibility layer 1-345 (structure), the 1969 DOCFNS DOCTOR and MAKESENTENCE 382-500 and the function
inventory of the 1969 code (DOCTOR, MAKESENTENCE, ANALYZE, TEST, TEST4, ADVANCE, RECONSTRUCT, MEMORY, BCONC, RPLQQ, SETNONE). NOT read:
ANALYZE / TEST / RECONSTRUCT bodies in full, the 1969 script (752-1834), the 1972 version (1835-2922), the transcript. Nothing ran
(a Common Lisp implementation would be needed; none on M3).
"""
from nyx.atlas.author import Cut

L = "vault:cosell-eliza-bbn-lisp-1969/upstream/coselleliza1969and1972.lisp"
c = Cut("cosell-eliza-bbn-lisp-1969", mode="ANCESTRY_AWARE", inspected=["coselleliza1969and1972.lisp 1-345 (compatibility layer), 382-500 (DOCTOR, MAKESENTENCE), function inventory 382-751"], evidence=[("SOURCE_READ", L + ":1-345"), ("SOURCE_READ", L + ":382-500"), ("SOURCE_READ", L + ":500-751")],
        note="an ELIZA written from the CACM paper, not the code: the reader splits input into sentences and keeps a KEYSTACK of keywords ranked by a PRIORITY property; the sentence with the highest-priority keyword is the one analysed; a MEMORY stack holds transformations to use when no keyword fires; the body is the 1969 printout plus a 1972 revision, wrapped in a compatibility package that re-creates BBN-LISP's semantics (optional arguments filled with NIL, CDR of a symbol as its property list, TCONC) so the original text runs unaltered")

read = c.organ("input_split_into_sentences_with_a_keyword_stack_ordered_by_a_priority_property_so_that_the_sentence_carrying_the_top_keyword_is_the_one_analysed", human_name="MAKESENTENCE (441-500): RATOM word loop; TRMLIS ends input; PCTLIS starts a new sentence; on a new sentence the KEYSTACKs are compared by (GETP ... PRIORITY) and the higher one wins; DOCTOR (395-440): the loop, GOODBYE, the elapsed-time sign-off", status="ACCEPTED",
    mechanism="words are read one at a time; numbers are packed with a marker; a terminal symbol ends the input; punctuation ends a sentence and recursively reads the next; when two sentences exist the one whose keyword stack's top has the greater PRIORITY property survives (the other is dropped), which is the paper's rule that only one sentence is answered; the doctor loop prints a prompt, builds a sentence, exits on GOODBYE with the session length in minutes, else calls ANALYZE",
    input="typed text", output="one sentence and its keyword stack", state="FLIPFLOP, the clock", update="per input line", assumptions=["keywords carry a numeric priority on their property list (the script sets it); one sentence per turn is enough"],
    fitness_value_in_ancestor="the selection of WHICH sentence to answer is done at read time, before any matching", failure_landscape="by reading: priority ties resolve to the earlier sentence; a sentence with no keyword is answered from MEMORY or with a none-response (SETNONE)", human_prior="Weizenbaum 1966 CACM (the keyword ranking); this is an independent implementation of the paper's description",
    evidence_ref=L + ":395-500", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="DOCTOR and MAKESENTENCE",
    coverage={"input_topology": "SEQUENCE", "output_topology": "SEQUENCE", "state_amount": "CONSTANT", "stochasticity": "DETERMINISTIC", "update_topology": "PRIORITY", "order_sensitivity": "SENSITIVE"})

match = c.organ("decomposition_rules_tried_per_keyword_with_a_cyclic_choice_among_reassembly_rules_and_a_memory_stack_consulted_when_no_keyword_matches", human_name="ANALYZE (503-545), TEST / TEST4 / ADVANCE (546-620: the decomposition matcher over the keyword's rule list), RECONSTRUCT (620-670: reassembly and printing), MEMORY (669-688), SETNONE (715-751)", status="CANDIDATE",
    mechanism="for the top keyword, its rules are tried in order; a decomposition pattern is matched against the sentence by a segment matcher (TEST/TEST4 advance through the sentence, ADVANCE moves the pattern); on success one reassembly rule is chosen by rotating a pointer (RPLQQ rotates the rule list in place so successive uses cycle) and RECONSTRUCT substitutes the captured segments and prints; certain keywords also push a transformed sentence onto MEMORY; when no keyword matches, a memory entry is popped, else a content-free response is given",
    input="a sentence, a keyword", output="a printed response", state="the rotated rule lists (destructive), MEMSTACK", update="per turn", assumptions=["the paper's decomposition/reassembly scheme; rotation of the rule list is the cheapest way to avoid repeating a response"],
    fitness_value_in_ancestor="the second, independent ELIZA; behaviour reproduced from prose alone", failure_landscape="UNKNOWN by run", evidence_ref=L + ":503-751 (names and structure; bodies skimmed)", confidence="MEDIUM", portability="YES", compatibility="UNKNOWN", utility="UNKNOWN", source_boundary="the 1969 DOCFNS beyond MAKESENTENCE; CANDIDATE because bodies were skimmed",
    coverage={"input_topology": "SEQUENCE", "output_topology": "SEQUENCE", "state_amount": "LINEAR_IN_INPUT", "state_persistence": "PER_EPISODE", "memory": "WINDOW", "stochasticity": "DETERMINISTIC", "update_topology": "RECURSIVE"})

compat = c.organ("host_language_semantics_re_created_by_a_compatibility_package_so_a_1969_listing_runs_unaltered", human_name="package :bbn-lisp (70-345): DEFINEQ with optional arguments filled with NIL, CDR of a symbol as its plist, TCONC, PUT/GETP, the readtables for the patient's input; the transcription notes (1-65)", status="ACCEPTED",
    mechanism="rather than editing the printout, the transcribers wrote a package that shadows the Common Lisp symbols whose 1969 semantics differ (CONS with no arguments, CDR/RPLACD on symbols, NLAMBDA as a macro, optional arguments) and a reader for the patient's punctuation; the 1969 and 1972 codes are loaded into separate packages with separate scripts",
    input="the 1969 text", output="a running program", state="none", update="at load", assumptions=["preserving the artifact matters more than idiomatic code; the differences between dialects are enumerable"],
    fitness_value_in_ancestor="the original bytes are the body; every deviation is in one place and documented", failure_landscape="by reading: the TODO list names three unresolved semantics (CLOCK in 1972, nlistp, MEMB vs member)", human_prior="the same discipline this atlas calls C9 (faithful branch first)", evidence_ref=L + ":1-345", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="the :bbn-lisp package",
    coverage={"input_topology": "SEQUENCE", "output_topology": "SEQUENCE", "state_amount": "NONE", "stochasticity": "DETERMINISTIC", "representation_sensitivity": "SENSITIVE"})

c.reject("the 1969 script (752-1834) and the 1972 script (2246-2922): the keyword / decomposition / reassembly data", reason="OTHER", evidence="NOT READ; data, not mechanism", note="the script is where the behaviour lives; a Stage C comparison against the 1965 MAD-SLIP script (in this atlas) would be a data diff")
c.reject("the 1972 DOCTOR (1871-2245)", reason="OTHER", evidence="NOT READ", note="a second body; the record says the two are separate and complete")
c.reject("'ELIZA' as one organ", reason="NAME_HAS_NO_EXECUTABLE_BOUNDARY", evidence="reading/selection, matching/reassembly and the memory are separable, and the compatibility layer is a fourth thing")

c.edge(read, match, "feeds"); c.edge(compat, read, "feeds", note="the runtime")

c.pressure("a_conversational_responder_must_choose_which_of_several_input_sentences_to_answer_and_avoid_repeating_itself_with_only_a_keyword_table_and_a_bounded_memory",
    condition="an organism receives multi-sentence input; it has a table of keywords with priorities and rules; the score is a human's willingness to continue and the absence of verbatim repetition; the organism has no model of meaning", resource_or_constraint="a small script; a memory stack",
    failure_condition="answering the wrong sentence, repeating a response, or silence when no keyword fires", world_punishes="first-sentence-always; a fixed reassembly per rule; no memory", world_rewards="priority selection at read time, rotation of reassembly rules, a memory stack",
    observable_consequence="transcript length and repetition count with human subjects (the body ships a 1969 transcript) for the priority rule vs first-sentence and rotation vs fixed", vacuity_condition="single-sentence, single-keyword input", trivial_shortcuts="a scripted human",
    cheat_control="an organism given the human's next line must be indistinguishable from the transcript; first-sentence-always must answer the wrong sentence on the transcript's multi-sentence inputs; rotation off must repeat within the transcript's length: the world must show all three",
    cost_class="CPU-scale", source_evidence="MAKESENTENCE's priority comparison; RPLQQ; MEMORY; the transcript file", purpose="PURPOSE: conversational program (Cosell 1966-1972 after Weizenbaum 1966)")

c.ancestry("reimplementation_of", "Weizenbaum 1966 (from the paper, not the code); the atlas's eliza-weizenbaum-mad-slip-1965 is the original", note="from the record and the file header")
c.residue("PARTIALLY_EXPLAINED", ["ANALYZE / TEST / RECONSTRUCT bodies skimmed (one CANDIDATE organ)", "both scripts and the 1972 version unread", "nothing ran"], note="the reading/selection mechanism and the compatibility layer are located; a recurrence candidate against the 1965 cut and PAIP's patmatch")
c.save(state="COARSE")
