"""Cut: emcee-3.1.6 (Foreman-Mackey et al., the affine-invariant ensemble sampler; ancestry-aware, Stage A DEEP; SOURCE_READ on M3;
position 64 of the 2026-09-17 NOT_CUT order). Read: src/emcee/moves/stretch.py in full, moves/red_blue.py propose 37-106, autocorr.py
42-120, ensemble.py (the moves list 85-130 and sample's signature 258-290). NOT read: the other moves (walk, DE, DE-snooker, KDE,
Gaussian), backends (HDF5), the State / Model classes, the tests. Nothing ran; the body is pure Python + numpy: an M3-runnable packet
candidate (recorded in the residue).
"""
from nyx.atlas.author import Cut

ST = "vault:emcee-3.1.6/upstream/tree/emcee-3.1.6/src/emcee/moves/stretch.py"; RB = "vault:emcee-3.1.6/upstream/tree/emcee-3.1.6/src/emcee/moves/red_blue.py"
AC = "vault:emcee-3.1.6/upstream/tree/emcee-3.1.6/src/emcee/autocorr.py"; EN = "vault:emcee-3.1.6/upstream/tree/emcee-3.1.6/src/emcee/ensemble.py"
c = Cut("emcee-3.1.6", mode="ANCESTRY_AWARE", inspected=["moves/stretch.py 1-30", "moves/red_blue.py 37-106", "autocorr.py 42-120", "ensemble.py 85-130, 258-290"], evidence=[("SOURCE_READ", ST + ":1-30"), ("SOURCE_READ", RB + ":37-106"), ("SOURCE_READ", AC + ":42-120"), ("SOURCE_READ", EN + ":85-130")],
        note="MCMC with an ensemble of walkers where the proposal for one walker is built from the positions of the others: the stretch move draws a scale z from a density proportional to 1/sqrt(z) on [1/a, a], proposes along the line from a randomly chosen other walker through the current one, and corrects acceptance by z^(ndim-1); the ensemble is split into halves updated alternately so the 'other' walkers are fixed during a half-update (detailed balance and parallel evaluation); convergence is judged by an integrated autocorrelation time estimated with Sokal's automatic window; the whole thing needs no tuning of a proposal covariance because the moves are affine invariant")

stretch = c.organ("stretch_move_proposing_along_the_line_through_a_random_complementary_walker_with_a_scale_drawn_from_g_z_proportional_to_one_over_sqrt_z_and_an_acceptance_factor_of_z_to_the_ndim_minus_one", human_name="StretchMove.get_proposal (stretch.py): zz = ((a - 1) rand + 1)^2 / a; factors = (ndim - 1) log zz; rint random complementary index; q = c[rint] - (c[rint] - s) zz", status="ACCEPTED",
    mechanism="for each walker in the active half, pick a walker from the other half at random, draw z by squaring a uniform on [1, sqrt(a)] scaled by 1/a (which yields the density proportional to 1/sqrt(z) on [1/a, a], symmetric under z -> 1/z), and propose x' = y + z (x - y): the point on the line through y and x at stretch z; the Metropolis ratio includes z^(ndim - 1) so the move satisfies detailed balance; a = 2 by default",
    input="the active half, the complementary half, a random state", output="proposals and log correction factors", state="none", update="per half-step", assumptions=["the ensemble's spread approximates the target's covariance, so proposals along inter-walker lines are automatically scaled and oriented (affine invariance, Goodman & Weare 2010)"],
    fitness_value_in_ancestor="no proposal tuning; the same code works on a badly scaled, correlated posterior as on a spherical one", failure_landscape="by reading: in high dimension the acceptance falls (the z^(ndim-1) factor) and the ensemble needs at least 2 ndim walkers; multimodal targets trap walkers in modes (the ensemble does not mix between modes)",
    human_prior="Goodman & Weare 2010; Christen & Fox 2010 for the earlier 'walk' idea", evidence_ref=ST + ":14-30", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="StretchMove",
    coverage={"input_topology": "SET", "output_topology": "SET", "state_amount": "NONE", "stochasticity": "SEEDED_RANDOM", "update_topology": "PARALLEL_ROUNDS", "representation_sensitivity": "INVARIANT"})

rb = c.organ("ensemble_split_into_sub_ensembles_updated_in_turn_so_the_complementary_set_is_fixed_during_a_half_update_allowing_parallel_likelihood_evaluation_and_preserving_detailed_balance", human_name="RedBlueMove.propose (red_blue.py 52-106): inds = all_inds % nsplits (shuffled if randomize_split); for each split: s = active, c = the others; get_proposal; compute_log_prob_fn(q) on the whole half at once; lnpdiff = factor + new - old; accept if lnpdiff > log(rand); state.update", status="ACCEPTED",
    mechanism="walkers are assigned to nsplits groups (two by default, reshuffled each step); each group in turn proposes new positions using only walkers from the other groups, evaluates all its proposals' log-probabilities in one vectorised (or pooled) call, and accepts each independently by the Metropolis rule with the move's correction factor; because the complementary walkers do not move during a group's update, the update is a valid Markov transition and the group's evaluations are embarrassingly parallel",
    input="the ensemble state", output="a new state and an accepted mask", state="none", update="per step", assumptions=["updating all walkers simultaneously from each other would break detailed balance (Foreman-Mackey et al. 2013 section 3); two halves are enough"],
    fitness_value_in_ancestor="one likelihood call per half-ensemble per step: the reason the sampler scales to clusters", failure_landscape="UNKNOWN by run", human_prior="Foreman-Mackey, Hogg, Lang & Goodman 2013 (the parallel red-blue scheme)", evidence_ref=RB + ":37-106", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="RedBlueMove.propose",
    coverage={"input_topology": "SET", "output_topology": "SET", "state_amount": "NONE", "stochasticity": "SEEDED_RANDOM", "update_topology": "PARALLEL_ROUNDS"})

acor = c.organ("integrated_autocorrelation_time_from_the_fft_autocorrelation_with_sokal_automatic_windowing_and_a_reliability_flag_when_the_chain_is_shorter_than_tol_times_tau", human_name="autocorr.integrated_time (49-130): function_1d by FFT; taus = 2 cumsum(f) - 1; auto_window(taus, c = 5): the first M with M >= c tau(M); flag if tol * tau > n", status="ACCEPTED",
    mechanism="the normalised autocorrelation function of each chain (averaged over walkers) is computed by FFT; the integrated time is 2 times the running sum minus one; the window M is the first lag at which M exceeds c times the estimate at M (Sokal's rule, c = 5 by default), which balances bias against variance; if the chain is shorter than tol (50) autocorrelation times the estimate is flagged as unreliable (a warning or an exception)",
    input="chains of shape (n_steps, n_walkers, n_dim)", output="tau per dimension", state="none", update="on request", assumptions=["the autocorrelation function decays; the automatic window is the standard estimator (Sokal 1997); 50 tau is the recommended minimum chain length"],
    fitness_value_in_ancestor="a convergence diagnostic that says when it cannot be trusted", failure_landscape="by reading: the estimate itself is biased low for short chains, which is why tol exists", human_prior="Sokal 1997 (Monte Carlo methods in statistical mechanics, the windowing lecture); Goodman & Weare 2010 acor", evidence_ref=AC + ":42-130", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="autocorr.py",
    coverage={"input_topology": "SEQUENCE", "output_topology": "VECTOR", "state_amount": "NONE", "stochasticity": "DETERMINISTIC", "uncertainty": "INTERVAL"})

mix = c.organ("moves_as_a_weighted_list_sampled_per_step", human_name="EnsembleSampler.__init__ (ensemble.py 85-130): moves as a move, a list, or [(move, weight), ...]; the default [StretchMove()]", status="CANDIDATE",
    mechanism="at each step one move is drawn from the list with the given weights and applied to the whole ensemble; the other shipped moves (walk, differential evolution, DE snooker, KDE, Gaussian) share the red-blue interface, so mixtures of proposals are a configuration", input="a list of moves and weights", output="one move per step", state="none", update="per step",
    assumptions=["mixing proposals helps on multimodal targets (DE snooker is the paper's remedy)"], fitness_value_in_ancestor="the sampler is a framework for ensemble moves, not one move", failure_landscape="UNKNOWN by run", evidence_ref=EN + ":85-130 (the per-step draw not read)", confidence="MEDIUM", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="the moves argument; CANDIDATE because sample's draw was not read",
    coverage={"input_topology": "SET", "output_topology": "DECISION", "state_amount": "NONE", "stochasticity": "SEEDED_RANDOM"})

c.reject("the other moves (walk, de, de_snooker, kde, gaussian, mh), the HDF5 backend, State / Model / interruptible pool, the progress bar, the tests", reason="OTHER", evidence="NOT READ; residue", note="DE-snooker is the second mechanism of interest (Ter Braak & Vrugt 2008) and should be a DEEP item")
c.reject("'MCMC' as one organ", reason="NAME_HAS_NO_EXECUTABLE_BOUNDARY", evidence="the move, the parallel update scheme and the diagnostic are separable and separately published")

c.edge(stretch, rb, "feeds", note="get_proposal"); c.edge(rb, acor, "feeds", note="chains"); c.edge(mix, rb, "selects")

c.pressure("a_posterior_with_unknown_scale_and_strong_linear_correlations_must_be_sampled_without_any_hand_tuned_proposal_while_likelihood_evaluations_are_expensive_and_parallelisable_and_the_sampler_must_say_when_its_chain_is_too_short",
    condition="an organism draws samples from a log-density it can only evaluate; the density is a badly scaled, correlated Gaussian (the Rosenbrock or the 'ill-conditioned' tests) of moderate dimension; evaluations can run in parallel; the score is effective samples per evaluation and a correct statement of the autocorrelation time", resource_or_constraint="evaluations; walkers",
    failure_condition="acceptance near zero or one (untuned Metropolis), correlated chains reported as converged, or a serial evaluation pattern that wastes the parallel budget", world_punishes="isotropic random-walk Metropolis; simultaneous ensemble updates (biased); reporting tau without a length check", world_rewards="affine-invariant moves, red-blue halves, windowed autocorrelation with a reliability flag",
    observable_consequence="effective samples per evaluation on a 10-d Gaussian with condition number 1e4, for isotropic Metropolis vs the stretch move; bias of the simultaneous-update variant on the mean; the tol flag's false-negative rate on short chains", vacuity_condition="a spherical target", trivial_shortcuts="the target's covariance handed to the proposal (which the world withholds)",
    cheat_control="an organism given the covariance must match the stretch move's efficiency; isotropic Metropolis must fall by the condition number; the simultaneous update must bias the mean on a two-walker test: the world must show all three",
    cost_class="CPU-scale", source_evidence="stretch.py; red_blue.py; autocorr.py; the paper's tests", purpose="PURPOSE: affine-invariant ensemble MCMC (Foreman-Mackey et al. 2013)")

c.ancestry("algorithm_from", "Metropolis 1953 / Hastings 1970; Goodman & Weare 2010 (stretch move); Foreman-Mackey et al. 2013 (parallel red-blue); Sokal 1997 (windowing)", note="from the docstrings and the record")
c.residue("PARTIALLY_EXPLAINED", ["the other moves and the backends unread", "nothing ran", "M3-RUNNABLE PACKET CANDIDATE: pure numpy; the analytic Gaussian is an exact oracle for the mean, covariance and, via the known spectrum, the autocorrelation time"], note="the three published mechanisms are located; the sampler is the third pure-Python body with a self-contained oracle found in this pass (after sgp4 and backoff)")
c.save(state="DEEP")
