"""Cut: eprover-2.6 (Schulz's E theorem prover; ancestry-aware, Stage A COARSE; SOURCE_READ on M3; position 51 of the 2026-09-17
NOT_CUT order). Read: CONTROL/cco_proofproc.c function inventory, ProcessClause 1560-1700 (the given-clause step, filtered read) and
Saturate 1738-1800 (the outer loop and its limits); HEURISTICS/che_hcb.c HCBStandardClauseSelect 903-940 and the hcb struct comment
(che_hcb.h 259-271); HEURISTICS/che_proofcontrol.c DefaultWeightFunctions 35-90 (names). NOT read: the inference rules
(superposition, paramodulation, equality resolution/factoring in CLAUSES/ and CONTROL/cco_*), term orderings (ORDERINGS/), the
term bank and rewriting (TERMS/), literal selection (che_litselection.c 7,110 lines), the auto-schedule, the SAT check (PicoSAT),
the TPTP front end, 1,400 other files. Nothing ran (C; no compiler on M3). An inventory-level map of a 300,000-line prover.
"""
from nyx.atlas.author import Cut

P = "vault:eprover-2.6/upstream/tree/CONTROL/cco_proofproc.c"; H = "vault:eprover-2.6/upstream/tree/HEURISTICS/che_hcb.c"; HH = "vault:eprover-2.6/upstream/tree/HEURISTICS/che_hcb.h"; PC = "vault:eprover-2.6/upstream/tree/HEURISTICS/che_proofcontrol.c"
c = Cut("eprover-2.6", mode="ANCESTRY_AWARE", inspected=["CONTROL/cco_proofproc.c 1560-1800 (ProcessClause, Saturate)", "HEURISTICS/che_hcb.c 903-940", "HEURISTICS/che_hcb.h 259-271", "HEURISTICS/che_proofcontrol.c 35-90"],
        evidence=[("SOURCE_READ", P + ":1560-1800"), ("SOURCE_READ", H + ":903-940"), ("SOURCE_READ", HH + ":259-271"), ("SOURCE_READ", PC + ":35-90")],
        note="saturation as the given-clause loop: pick one unprocessed clause by a heuristic, simplify it against the processed set (forward contraction), use it to simplify the processed set (backward), then generate every inference between it and the processed set and put the children back into the unprocessed set; the loop runs until the empty clause appears, the unprocessed set empties, or a limit trips; the heuristic is a round-robin over several weighted priority queues so that a cheap clause order (FIFO) and a small-clause order interleave")

given = c.organ("given_clause_loop_processing_one_selected_clause_per_step_with_forward_simplification_backward_simplification_and_generation_into_the_unprocessed_set", human_name="ProcessClause (1560-1700): select from state->unprocessed; ForwardContractClause; ClauseIsSemFalse / empty clause; eliminate_backward_rewritten / subsumed / unit_simplified; insert into processed_pos_rules / pos_eqns / neg_units / non_units by shape; generate_new_clauses; Saturate (1738-1800): the while over TimeIsUp, set sizes, step / proc / unproc / total / generated / term-bank limits, then cleanup_unprocessed_clauses and the periodic SATCheck",
    status="ACCEPTED",
    mechanism="each step removes the heuristically best clause from the unprocessed set, rewrites and simplifies it against the processed set (returning the empty clause if it collapses to a contradiction), removes processed clauses it now subsumes or rewrites, files it in one of four processed sub-sets by shape (oriented rewrite rule, unorientable equation, negative unit, non-unit) so later inferences can index by shape, and generates all inferences (superposition, paramodulation, resolution, factoring) between it and the processed set into the unprocessed set; the outer loop repeats while time and eight size/count limits allow, periodically grounding a sample of clauses for a SAT check",
    input="a clause set", output="the empty clause (proof) or a saturated set / limit", state="processed (4 indexed sets), unprocessed (evaluated), the term bank, demodulator dates", update="per given clause", assumptions=["completeness of the calculus requires every inference between processed clauses to be performed eventually (the Otter loop's invariant); simplification is allowed because superposition with orderings is a saturation calculus (Bachmair & Ganzinger)"],
    fitness_value_in_ancestor="the loop is complete for first-order logic with equality and stops on many satisfiable sets; every CASC-winning prover has this loop at its centre", failure_landscape="by reading: the unprocessed set grows quadratically with the processed set (the limits exist because of it); the loop's power is entirely in which clause is chosen next",
    human_prior="Otter (McCune 1988) given-clause algorithm; E's 'DISCOUNT loop' variant (Denzinger et al. 1997) where the processed set is kept fully interreduced", evidence_ref=P + ":1560-1800", confidence="MEDIUM", portability="YES", compatibility="UNKNOWN", utility="UNKNOWN", source_boundary="ProcessClause and Saturate; MEDIUM because the inference and simplification bodies were not read",
    coverage={"input_topology": "SET", "output_topology": "DECISION", "state_amount": "UNBOUNDED", "state_persistence": "PER_EPISODE", "memory": "ARCHIVE", "stochasticity": "DETERMINISTIC", "update_topology": "PRIORITY", "resource_dependence": "MEMORY"})

hcb = c.organ("clause_selection_by_round_robin_over_several_weighted_priority_queues_with_a_switch_schedule_per_queue", human_name="HCBStandardClauseSelect (che_hcb.c 903-940): ClauseSetFindBest(set, current_eval); orphan removal; select_count vs select_switch[current_eval]; wrap at wfcb_no; DefaultWeightFunctions (che_proofcontrol.c 35-90): FIFOWeight, ClauseWeight, RefinedWeight, ConjectureRelativeSymbolWeight, OrientLMaxWeight ... combined as '5*X, 1*FIFO'",
    status="ACCEPTED",
    mechanism="every unprocessed clause carries one evaluation per weight function (a heuristic control block holds a list of them); selection takes the best clause under the CURRENT function, then advances a counter; when the counter reaches that function's switch value the next function becomes current, wrapping around, so a specification like '5*symbol-weight, 1*FIFO' picks five clauses by weight for every one by age; clauses whose parents were deleted (orphans) are dropped on the way; weight functions range from clause size to conjecture-relative symbol weights that favour symbols occurring in the goal",
    input="the unprocessed set with evaluations", output="the next given clause", state="current_eval, select_count", update="per selection", assumptions=["no single ordering is good for all problems: small clauses first is strong but starves old clauses (incomplete in practice), age first is fair but slow; interleaving fixed ratios gets both"],
    fitness_value_in_ancestor="fairness (every clause is eventually selected, via the FIFO share) with the strength of size-based orders", failure_landscape="by reading: the ratios are tuned per problem class (the auto mode, che_new_autoschedule.c, chooses them from clause-set features: unread)", human_prior="Schulz 2002 'E -- a brainiac theorem prover'; the pick-given ratio of Otter", evidence_ref=H + ":903-940; " + HH + ":259-271; " + PC + ":35-90", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="the HCB selection functions and the weight-function registry",
    coverage={"input_topology": "SET", "output_topology": "SCALAR", "state_amount": "CONSTANT", "stochasticity": "DETERMINISTIC", "update_topology": "PRIORITY", "order_sensitivity": "SENSITIVE"})

c.reject("the inference rules and their indexing (superposition / paramodulation / equality resolution and factoring, CLAUSES/ and CONTROL/cco_*), term orderings (ORDERINGS/: KBO, LPO), the shared term bank and rewriting (TERMS/), literal selection strategies (che_litselection.c), clause-set features and the auto schedule (che_new_autoschedule.c), the PicoSAT-based SAT check, proof object extraction (PCL2/), the TPTP/CNF front end, the learning modules (LEARN/)", reason="OTHER", evidence="NOT READ (~290,000 lines); residue", note="orderings + superposition are the calculus (Bachmair & Ganzinger 1994) and deserve a DEEP pass of their own; the term bank (perfect sharing) is a representation mechanism worth a cut")
c.reject("'theorem prover' / 'saturation' as one organ", reason="NAME_HAS_NO_EXECUTABLE_BOUNDARY", evidence="the loop, the selection heuristic, the calculus, the orderings and the indexing are separable and separately switchable by options")

c.edge(hcb, given, "selects")

c.pressure("a_refutation_must_be_found_in_an_infinite_space_of_derived_clauses_where_the_useful_derivation_is_a_vanishing_fraction_and_fairness_must_be_preserved_so_that_completeness_is_not_lost",
    condition="an organism derives consequences from a clause set; the set of derivable clauses is infinite; a proof exists among them; the score is proofs found within a time and memory budget on a problem library; the organism must also terminate on some satisfiable sets", resource_or_constraint="time; the unprocessed set's memory",
    failure_condition="starvation (a needed old clause never selected) or drowning (the useful clause buried under quadratic generation)", world_punishes="pure FIFO (slow) and pure smallest-first (unfair); no simplification (drowning)", world_rewards="interleaved queues, interreduction of the processed set, conjecture-directed weights",
    observable_consequence="problems solved within the budget on a TPTP slice with the selection heuristic set to FIFO only, weight only, and the default mix; and with backward simplification disabled", vacuity_condition="propositional or Horn problems solvable by unit propagation", trivial_shortcuts="a proof oracle (the world withholds it)",
    cheat_control="an organism given the proof's clauses as a watchlist (E has one: PreferWatchlist) must solve every problem quickly; FIFO-only must time out where the mix succeeds; the mix without simplification must exhaust memory on equational problems: the world must show all three",
    cost_class="CPU-scale", source_evidence="cco_proofproc.c Saturate / ProcessClause; che_hcb.c; che_proofcontrol.c weight-function defaults", purpose="PURPOSE: first-order theorem proving with equality (Schulz 1998-)")

c.ancestry("algorithm_from", "Robinson 1965 (resolution); McCune 1988 (Otter, given clause); Bachmair & Ganzinger 1994 (superposition); Denzinger et al. 1997 (DISCOUNT loop); Schulz 2002 (E)", note="from the record and the source's DOC")
c.residue("LARGE_RESIDUE", ["the calculus, orderings, indexing, term bank and auto-schedule unread (~97 percent of the body)", "the two organs read are the control loop and its selector", "nothing ran"], note="a map with two mechanisms located; the prover's substance is in the residue")
c.save(state="COARSE")
