"""Cut: espresso-logic (Espresso-II two-level logic minimiser, Berkeley, as re-released; ancestry-aware, Stage A COARSE; SOURCE_READ on M3;
position 69 of the 2026-09-17 NOT_CUT order). Read: espresso-src/espresso.c espresso() 1-70 (the outer iteration), expand.c 1-70 (header
comment and the entry of expand), reduce.c 1-30 (header), irred.c 1-25 (entry). NOT read: expand1 and the covering heuristics, the
reduce and irredundant bodies, essential.c, gasp.c, sparse.c, the cube/set representation (set.c, cubestr.c), cvrin.c (PLA input),
the 200 other files. Nothing ran (C; no compiler on M3).
"""
from nyx.atlas.author import Cut

E = "vault:espresso-logic/upstream/tree/espresso-src/espresso.c"; X = "vault:espresso-logic/upstream/tree/espresso-src/expand.c"; R = "vault:espresso-logic/upstream/tree/espresso-src/reduce.c"; IR = "vault:espresso-logic/upstream/tree/espresso-src/irred.c"
c = Cut("espresso-logic", mode="ANCESTRY_AWARE", inspected=["espresso-src/espresso.c 1-70", "expand.c 1-70", "reduce.c 1-30", "irred.c 1-25"], evidence=[("SOURCE_READ", E + ":1-70"), ("SOURCE_READ", X + ":1-70"), ("SOURCE_READ", R + ":1-30"), ("SOURCE_READ", IR + ":1-25")],
        note="heuristic minimisation of a Boolean cover by iterating three operations on the set of cubes until the cube count stops falling: EXPAND each cube to a prime against a representation of the OFF-set so it covers as many other cubes as possible, IRREDUNDANT drop cubes not needed for the cover (a covering problem on a table), REDUCE shrink each cube to the smallest that still covers its essential points so the next expansion can move; essential primes are removed first and appended at the end; two escape moves (last_gasp, super_gasp) try once more when the loop stalls; a final make_sparse pass; the cost is (cubes, total literals) compared lexicographically")

loop = c.organ("expand_irredundant_reduce_iterated_until_the_cube_count_stops_falling_with_essential_primes_removed_first_and_gasp_escapes_on_a_stall", human_name="espresso() (espresso.c 1-70): EXPAND, IRREDUNDANT, essential(&F, &D) removed; do { do { copy_cost; REDUCE; EXPAND; IRREDUNDANT } while (cost.cubes < best_cost.cubes); super_gasp / last_gasp } while (cubes fall or, at equal cubes, total falls); append E; make_sparse", status="ACCEPTED",
    mechanism="after an initial expand and irredundant pass, cubes that no other prime can replace (essential) are set aside so the loop works on the rest; the inner loop reduces, expands and makes irredundant while the cube count decreases; when it stalls, a gasp step (reduce each cube, expand it in a different direction, and keep any that let another cube be dropped) is tried and the outer loop repeats if it helped; the cost compares cube count first and literal count second; the essentials are appended and a sparse-variable clean-up runs",
    input="a cover F (and don't-cares D, off-set R)", output="a smaller cover of the same function", state="F, best_cost", update="per pass", assumptions=["a local minimum of the expand/reduce/irredundant cycle is close to the global one on real PLAs; reduce moves the cover off a plateau by shrinking cubes in a new order each time (the toggle in reduce.c)"],
    fitness_value_in_ancestor="near-minimal two-level logic for PLAs in seconds, when exact minimisation (Quine-McCluskey) was infeasible; the algorithm every logic synthesis tool inherited", failure_landscape="by reading: a heuristic with no optimality bound; order-dependent (use_random_order exists); the literal count is a tie-breaker only",
    human_prior="Brayton, Hachtel, McMullen, Sangiovanni-Vincentelli 1984 (Logic Minimization Algorithms for VLSI Synthesis); MINI (Hong, Cain, Ostapko 1974) as the ancestor of the expand/reduce idea", evidence_ref=E + ":1-70", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="espresso()",
    coverage={"input_topology": "SET", "output_topology": "SET", "state_amount": "LINEAR_IN_INPUT", "feedback": "CLOSED_LOOP", "stochasticity": "DETERMINISTIC", "update_topology": "SWEEP", "failure_mode": "STALLS"})

exp = c.organ("expansion_of_each_cube_to_a_prime_against_a_representation_of_the_off_set_choosing_the_parts_to_raise_so_as_to_cover_the_most_other_cubes_in_an_order_that_chews_from_the_edges", human_name="expand (expand.c 30-70 and expand1, not read): mini_sort(F, ascend) or random_order; RAISE / FREESET / INIT_LOWER / SUPER_CUBE / OVEREXPANDED_CUBE; the header: 'we do NOT require an unwrapped version of the OFF-set'", status="CANDIDATE",
    mechanism="cubes are processed in an order that starts from the cover's edges; for each non-prime cube the free parts (those that can be raised without hitting the off-set) are determined against the off-set cover directly; parts are raised preferentially so that the expanded cube covers other cubes of the on-set (which then become redundant); when no cube can be covered, a covering heuristic picks a large prime; the overexpanded cube (all individually raisable parts) and the supercube of coverable cubes bound the choices",
    input="F, R", output="a cover of primes", state="the covered marks", update="per pass", assumptions=["testing containment against the off-set cover is cheaper than complementing (the Espresso-II improvement over the manuscript); covering other cubes is the right greedy objective"],
    fitness_value_in_ancestor="primes without enumeration; the step that does the minimisation", failure_landscape="UNKNOWN by run", evidence_ref=X + ":1-70", confidence="MEDIUM", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="expand / expand1; CANDIDATE because expand1 was not read",
    coverage={"input_topology": "SET", "output_topology": "SET", "state_amount": "LINEAR_IN_INPUT", "stochasticity": "DETERMINISTIC", "update_topology": "SWEEP", "order_sensitivity": "SENSITIVE"})

red = c.organ("reduction_of_each_cube_to_the_supercube_of_its_essential_points_in_an_alternating_order_and_irredundant_cover_by_a_covering_table", human_name="reduce (reduce.c header: 'the smallest cube contained in the cube which can replace the cube ... the super cube of all of the essential points'; two orderings alternated by a toggle); irredundant / mark_irredundant (irred.c: relatively essential Rt / partially redundant Rp; an sm_matrix covering table solved by minimum_cover)", status="CANDIDATE",
    mechanism="reduce replaces each cube by the smallest cube that still covers the points no other cube covers (computed directly as a supercube), processing cubes in one of two orders alternately so successive passes explore different directions; irredundant partitions the cover into relatively essential cubes (kept), totally redundant (dropped) and partially redundant cubes, and solves a set-covering problem over the last group with a heuristic minimum-cover routine to keep a minimal subset",
    input="F, D", output="a reduced or minimal cover", state="the toggle", update="per pass", assumptions=["shrinking cubes toward their essential points frees room for a different expansion (the escape from local minima); minimum cover is NP-hard, so a heuristic is used"],
    fitness_value_in_ancestor="the two steps that turn a greedy expand into an iterative improvement", failure_landscape="UNKNOWN by run", evidence_ref=R + ":1-30; " + IR + ":1-25", confidence="MEDIUM", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="reduce.c, irred.c; CANDIDATE because bodies were not read",
    coverage={"input_topology": "SET", "output_topology": "SET", "state_amount": "LINEAR_IN_INPUT", "stochasticity": "DETERMINISTIC", "update_topology": "SWEEP"})

c.reject("the cube and set representation (set.c, cubestr.c: bit-vector cubes with per-variable masks), the PLA reader/writer, the complementation and tautology routines (compl.c, cofactor.c: unate recursive paradigm), essential.c, gasp.c, sparse.c, the exact minimiser (exact.c, mincov), the multiple-valued extensions, the manual and examples", reason="OTHER", evidence="NOT READ; residue", note="the unate recursive paradigm (cofactoring until unate) is the second mechanism family in the body and should be its own DEEP item")
c.reject("'logic minimiser' as one organ", reason="NAME_HAS_NO_EXECUTABLE_BOUNDARY", evidence="the loop and its three operators are separately described chapters of the 1984 book")

c.edge(exp, loop, "feeds"); c.edge(red, loop, "feeds"); c.edge(loop, exp, "triggers"); c.edge(loop, red, "triggers")

c.pressure("a_boolean_function_given_as_a_cube_cover_must_be_re_expressed_with_the_fewest_cubes_when_exact_minimisation_is_exponential_and_the_local_optimum_of_greedy_prime_expansion_is_poor",
    condition="an organism rewrites a cover of a multi-output Boolean function (with don't-cares) into another cover; the score is cube count, then literal count, against the exact minimum on the standard PLA benchmarks; time is bounded", resource_or_constraint="polynomial passes over the cover; a covering-table heuristic",
    failure_condition="covers far from the exact minimum, or time exponential in inputs", world_punishes="Quine-McCluskey prime enumeration (exponential); a single greedy expansion (local optimum)", world_rewards="expand/reduce alternation with order changes, irredundant covering, gasp escapes",
    observable_consequence="cube count vs exact (where computable) on the Berkeley PLA set, for expand-only, expand+irredundant, and the full loop with and without gasps; run time vs inputs", vacuity_condition="functions whose primes are all essential", trivial_shortcuts="the exact minimiser on small cases (a bound, not a competitor)",
    cheat_control="an organism given the exact minimum cover must reproduce it; expand-only must show a larger cover on the benchmarks; the full loop must close most of the gap: the world must show all three",
    cost_class="CPU-scale", source_evidence="espresso.c; expand.c; reduce.c; irred.c; the examples directory as the benchmark set", purpose="PURPOSE: two-level logic minimisation (Brayton et al. 1984)")

c.ancestry("algorithm_from", "MINI (Hong, Cain, Ostapko 1974); Espresso-II (Brayton, Hachtel, McMullen, Sangiovanni-Vincentelli 1984); this body is a later re-release of the Berkeley code", note="from the record and the source headers")
c.residue("LARGE_RESIDUE", ["expand1, reduce, irredundant, the complementation machinery and the representation unread", "nothing ran; the examples directory is the benchmark oracle"], note="the loop is located and its three operators named; two are CANDIDATE")
c.save(state="COARSE")
