"""Cut: filterpy-labbe (Labbe's FilterPy; ancestry-aware, Stage A COARSE; SOURCE_READ on M3; position 87 of the 2026-09-17 NOT_CUT order).
Read: filterpy/kalman/sigma_points.py MerweScaledSigmaPoints 24-207 (the scaled sigma set and its weights), filterpy/kalman/
unscented_transform.py 22-110 (mean and covariance of transformed sigma points, with pluggable mean and residual functions). NOT read:
kalman_filter.py (the linear KF), UKF.py (the filter that drives these), the particle filter, the g-h filter, stats, the tests.
Nothing ran; the body is pure Python (numpy/scipy): an M3-runnable packet candidate (a linear-Gaussian system is an exact oracle;
residue).
"""
from nyx.atlas.author import Cut

S = "vault:filterpy-labbe/upstream/tree/filterpy/kalman/sigma_points.py"; U = "vault:filterpy-labbe/upstream/tree/filterpy/kalman/unscented_transform.py"
c = Cut("filterpy-labbe", mode="ANCESTRY_AWARE", inspected=["kalman/sigma_points.py 24-207", "kalman/unscented_transform.py 22-110"], evidence=[("SOURCE_READ", S + ":99-207"), ("SOURCE_READ", U + ":60-110")],
        note="the unscented Kalman filter's two reusable pieces, read as the mechanism the library is cited for: a deterministic set of 2n+1 sigma points placed by the matrix square root of the covariance and scaled by (alpha, beta, kappa), and an unscented transform that pushes those points through a nonlinear function and recovers a mean and covariance by weighted sums, with hooks so that quantities living on a manifold (angles) can supply their own mean and residual operators")

sig = c.organ("scaled_sigma_points_placed_by_the_matrix_square_root_of_the_covariance_with_merwe_weights_from_alpha_beta_kappa", human_name="MerweScaledSigmaPoints.sigma_points (124-178): lambda_ = alpha^2 (n + kappa) - n; U = cholesky((lambda_ + n) P); point 0 = x, points i = x +/- U_i; _compute_weights (180-195): Wm and Wc with Wc[0] adding (1 - alpha^2 + beta)", status="ACCEPTED",
    mechanism="for an n-dimensional Gaussian (x, P) the filter forms 2n+1 points: the mean, and the mean plus and minus each column of the scaled matrix square root sqrt((lambda_ + n) P) (Cholesky by default); the spread is set by alpha (small = tight around the mean), the extra weight on the zeroth point's covariance by beta (2 is optimal for a Gaussian), and kappa is a secondary scaling; the mean weights Wm and covariance weights Wc differ only in the zeroth entry",
    input="a mean and covariance", output="2n+1 points and their weights", state="none", update="per prediction/update", assumptions=["a Gaussian is captured to second order by these deterministic points, so a nonlinear map's output mean and covariance are recovered without a Jacobian (the unscented transform's premise, Julier & Uhlmann 1997)"],
    fitness_value_in_ancestor="a derivative-free nonlinear filter: no Jacobian, better than the EKF on strong nonlinearities", failure_landscape="by reading: a non-positive-definite P makes the Cholesky fail (a known UKF fragility; the sqrt_method hook exists to swap in a more robust root)", human_prior="Julier & Uhlmann 1997; Wan & van der Merwe 2000 (the scaled form)", evidence_ref=S + ":124-195", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="MerweScaledSigmaPoints",
    coverage={"input_topology": "MATRIX", "output_topology": "SET", "state_amount": "NONE", "stochasticity": "DETERMINISTIC", "representation_sensitivity": "SENSITIVE"})

ut = c.organ("unscented_transform_recovering_a_mean_and_covariance_of_transformed_points_by_weighted_sums_with_pluggable_mean_and_residual_operators_for_manifold_states", human_name="unscented_transform (22-110): x = Wm . sigmas (or mean_fn); P = sum Wc (y - x)(y - x)^T + noise_cov, with residual_fn for the (y - x) so angular states subtract mod 2pi", status="ACCEPTED",
    mechanism="the sigma points are passed through the process or measurement function outside the transform; the transform then computes the output mean as the Wm-weighted sum of the transformed points (or a caller-supplied circular mean for angles), and the output covariance as the Wc-weighted sum of outer products of the residuals plus an additive noise covariance; a residual function lets states that are not closed under subtraction (angles, quaternions) define their own difference so the covariance is correct on the manifold",
    input="transformed sigma points, the weights, an optional noise covariance", output="a mean and covariance", state="none", update="per transform", assumptions=["the weighted sums reproduce the true transformed moments to second order; manifold states need custom mean/residual to avoid wraparound errors"],
    fitness_value_in_ancestor="the same transform serves the predict and the update of the UKF; the manifold hooks are why FilterPy is used for attitude and heading filters", failure_landscape="UNKNOWN by run", human_prior="Julier & Uhlmann 1997", evidence_ref=U + ":60-110", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="unscented_transform",
    coverage={"input_topology": "SET", "output_topology": "MATRIX", "state_amount": "NONE", "stochasticity": "DETERMINISTIC", "update_topology": "SWEEP"})

c.reject("kalman_filter.py (the linear KF), UKF.py (the filter loop that calls these two organs), the EKF, the particle filter, the g-h and least-squares filters, stats.py, the discretisation helpers, the tests", reason="OTHER", evidence="NOT READ; residue", note="UKF.py is where the two organs compose into a filter; a DEEP pass would read it; the atlas's tinyekf-levy is the EKF cousin and simple-kalman the non-Kalman impostor")
c.reject("'Kalman library' as one organ", reason="NAME_HAS_NO_EXECUTABLE_BOUNDARY", evidence="the sigma set, the transform, and the filter loop are separable; the library exposes each")

c.edge(sig, ut, "feeds", note="the transform consumes the sigma set")

c.pressure("a_nonlinear_dynamical_state_must_be_estimated_from_noisy_measurements_without_computing_jacobians_when_the_nonlinearity_is_strong_and_some_state_components_live_on_a_circle_not_a_line",
    condition="an organism tracks a state through nonlinear process and measurement functions; linearisation (the EKF) is inaccurate; some components are angles that wrap; the score is estimate error and consistency against a linear-Gaussian ground truth where one exists", resource_or_constraint="2n+1 function evaluations per step; a covariance square root",
    failure_condition="divergence on strong nonlinearity (EKF's failure), or a covariance corrupted by treating angular residuals as linear", world_punishes="a Jacobian-based filter on a non-smooth map; naive subtraction of angles", world_rewards="deterministic sigma points and weighted-moment recovery with manifold-aware mean/residual",
    observable_consequence="RMS error and filter consistency (NEES) on a bearings-only or reentry tracking problem for the EKF vs the UKF, and with vs without the angular residual function; exact match to the KF on a linear-Gaussian system", vacuity_condition="a linear-Gaussian system (the UKF reduces to the KF)", trivial_shortcuts="the true Jacobian where it exists (the EKF's best case, which the world uses as a control)",
    cheat_control="on a linear-Gaussian system the UKF must equal the exact Kalman filter to round-off; the EKF must diverge on a strongly nonlinear map where the UKF holds; the angular residual removed must corrupt the heading covariance: the world must show all three", cost_class="CPU-scale",
    source_evidence="sigma_points.py; unscented_transform.py; the record's example systems", purpose="PURPOSE: reference Bayesian filters (Labbe 2014-, with the book)")

c.ancestry("reimplementation_of", "Julier & Uhlmann 1997 / Wan & van der Merwe 2000 (the unscented/scaled sigma-point filter); Kalman 1960 for the linear base; the atlas's tinyekf-levy and simple-kalman are the family", note="from the docstrings and the record")
c.residue("PARTIALLY_EXPLAINED", ["the filter loops (UKF/EKF/KF) and the other filters unread", "nothing ran; M3-RUNNABLE PACKET CANDIDATE with a linear-Gaussian system as an exact oracle"], note="the two reusable UKF mechanisms are located; the filter that composes them is the residue")
c.save(state="COARSE")
