"""Cut: glpk-5.0 (Makhorin's GLPK; Stage A COARSE, narrow by the 2026-09-18 directive (no deepening of large bodies); SOURCE_READ on
M3; position 81 of the 2026-09-17 NOT_CUT order). Read: src/simplex/ file list; spxprim.c 22-120 (the common storage area: phases,
beta, reduced costs d, pricing block SPXSE); spxchuzc.c function signatures (spx_chuzc_sel / std / pse). NOT read: the pivoting
bodies, the basis factorisation (bflib), the dual simplex (spydual.c), the interior-point method, branch-and-cut (intopt), MathProg,
the 500 other files. Nothing ran (C; no compiler on M3).
"""
from nyx.atlas.author import Cut

P = "vault:glpk-5.0/upstream/tree/glpk-5.0/src/simplex/spxprim.c"; C_ = "vault:glpk-5.0/upstream/tree/glpk-5.0/src/simplex/spxchuzc.c"
c = Cut("glpk-5.0", mode="ANCESTRY_AWARE", inspected=["src/simplex file list", "spxprim.c 22-120", "spxchuzc.c signatures"], evidence=[("SOURCE_READ", P + ":22-120"), ("SOURCE_READ", C_ + ":53-260")],
        note="the primal simplex as GLPK organises it: a common storage area holding the current basis, the primal values of the basic variables (beta), the reduced costs of the non-basic ones (d), a two-phase flag (feasibility first, then optimality), and a pluggable pricing block (textbook, projected steepest edge, Devex); column choice and row choice (the ratio test) are separate modules with several strategies each. An inventory cut: the mechanisms are located by data structure and module, not read")

spx = c.organ("two_phase_primal_simplex_over_a_basis_with_cached_primal_values_and_reduced_costs_each_carrying_a_freshness_status_and_a_pluggable_pricing_block", human_name="spxprim.c struct csa (40-120): phase 0/1/2; beta[] with beta_st (undefined / just computed / updated); d[] with d_st; SPXSE se (projected steepest edge and Devex); orig_c / orig_l / orig_u copies; SPXAT / SPXNT sparse row-wise forms of A and of the non-basic columns N", status="CANDIDATE",
    mechanism="phase 1 searches a primal feasible basis by minimising infeasibility, phase 2 the optimum; the basic solution and the reduced costs are cached and marked as freshly computed or incrementally updated so the iteration recomputes them only when the status demands; the pricing block scores non-basic columns by a reference-framework steepest-edge weight (or Devex's approximation) rather than the textbook most-negative reduced cost; the constraint matrix is kept both as A and as the non-basic part N in sparse row form for the two directions of multiplication",
    input="an LP in standard form with bounds", output="an optimal basis or a status", state="the csa: basis, beta, d, pricing weights", update="per iteration", assumptions=["recomputing beta and d from scratch every iteration is the cost; updating them and refreshing periodically is the standard trade (Chvatal); steepest-edge pricing reduces iterations enough to pay for its weights"],
    fitness_value_in_ancestor="a free simplex competitive on medium problems; the organisation every commercial code shares", failure_landscape="by reading: numerical drift in the updated beta/d is why the status flags and periodic refactorisation exist; degeneracy handling (perturbation) not read", human_prior="Dantzig 1947; Forrest & Goldfarb 1992 (steepest edge); Harris 1973 (Devex)", evidence_ref=P + ":40-120; " + C_ + ":53-260", confidence="MEDIUM", portability="YES", compatibility="UNKNOWN", utility="UNKNOWN", source_boundary="spxprim.c and the chuzc/chuzr modules; CANDIDATE because bodies were not read",
    coverage={"input_topology": "MATRIX", "output_topology": "VECTOR", "state_amount": "LINEAR_IN_INPUT", "stochasticity": "DETERMINISTIC", "update_topology": "SINGLE_STEP"})

c.reject("the basis factorisation library (bflib: LU with Forrest-Tomlin / Schur-complement updates), the dual simplex (spydual.c, spychuzc/chuzr), the interior-point solver, branch-and-cut (intopt), preprocessing (npp), MathProg (mpl), the API, the bundled MiniSat and AMD/COLAMD orderings", reason="OTHER", evidence="NOT READ; residue", note="the directive of 2026-09-18 s1: no deepening of large COARSE bodies without a downstream question; bflib's basis update is the item if one arrives")
c.reject("'LP solver' as one organ", reason="NAME_HAS_NO_EXECUTABLE_BOUNDARY", evidence="two simplex variants, an interior-point method and a MIP layer share nothing but the problem object")

c.pressure("a_linear_program_must_be_solved_to_a_vertex_optimum_when_the_number_of_pivots_depends_on_the_choice_of_entering_column_and_the_cached_solution_drifts_numerically", condition="an organism pivots among bases of a sparse LP; the score is pivots to optimality and correctness of the final basis under floating point", resource_or_constraint="a factorised basis; per-iteration updates",
    failure_condition="cycling or an exponential pivot count (bad pricing), or a wrong optimum from drifted values", world_punishes="textbook pricing; never refreshing", world_rewards="steepest-edge weights; status-tracked recomputation", observable_consequence="pivot count and final residual on netlib LPs for textbook vs PSE vs Devex pricing, with refresh on and off", vacuity_condition="a problem whose first basis is optimal", trivial_shortcuts="an interior-point method (which the body also has; the world compares them)",
    cheat_control="an organism given the optimal basis must verify it in one iteration; textbook pricing must show more pivots on the degenerate netlib instances; no-refresh must show residual growth: the world must show all three", cost_class="CPU-scale", source_evidence="spxprim.c csa; spxchuzc.c", purpose="PURPOSE: linear programming (Makhorin 2000-)")

c.ancestry("algorithm_from", "Dantzig 1947 (simplex); Forrest & Goldfarb 1992; Harris 1973", note="from the record")
c.residue("LARGE_RESIDUE", ["one CANDIDATE organ from data-structure comments; nothing read in depth", "nothing ran"], note="inventory only, by the directive; the body is preserved for a downstream question that has not arrived")
c.save(state="COARSE")
