"""Cut: gnu-prolog-1.5.0 (Diaz's GNU Prolog; ancestry-aware, Stage A COARSE; SOURCE_READ on M3; position 68 of the 2026-09-17 NOT_CUT
order). Read: the source tree (src/Pl2Wam, Wam2Ma, Ma2Asm, EnginePl, EngineFD, BipsPl, BipsFD, Linedit, TopComp), Pl2Wam/pl2wam.pl header,
the Pl2Wam module names (code_gen, first_arg, indexing, reg_alloc, inst_codif), Wam2Ma/wam2ma.c and Ma2Asm/ma2asm.c sizes and the per-
architecture mapper files, EnginePl/wam_inst.c function inventory (the switch-table constructors). NOT read: any function body; the WAM
instruction semantics; the finite-domain solver (EngineFD, Fd2C); the builtins. Nothing ran (C + a bootstrapped compiler; not on M3).
"""
from nyx.atlas.author import Cut

PW = "vault:gnu-prolog-1.5.0/upstream/tree/gprolog-1.5.0/src/Pl2Wam/pl2wam.pl"; WI = "vault:gnu-prolog-1.5.0/upstream/tree/gprolog-1.5.0/src/EnginePl/wam_inst.c"
W2 = "vault:gnu-prolog-1.5.0/upstream/tree/gprolog-1.5.0/src/Wam2Ma/wam2ma.c"; M2 = "vault:gnu-prolog-1.5.0/upstream/tree/gprolog-1.5.0/src/Ma2Asm/ma2asm.c"
c = Cut("gnu-prolog-1.5.0", mode="ANCESTRY_AWARE", inspected=["src tree", "Pl2Wam/pl2wam.pl 1-60 + module names", "Wam2Ma, Ma2Asm file lists", "EnginePl/wam_inst.c inventory"], evidence=[("SOURCE_READ", PW + ":1-60"), ("SOURCE_READ", WI + ":80-180"), ("SOURCE_READ", W2 + ":1-40"), ("SOURCE_READ", M2 + ":1-40")],
        note="a Prolog that compiles rather than interprets: clauses go through a compiler written in Prolog (Pl2Wam: clause translation, first-argument indexing, register allocation, instruction encoding) to WAM instructions as text, then through a C translator (Wam2Ma) to a small machine-independent assembly (MA: about a dozen instruction kinds), then through per-architecture mappers (Ma2Asm: x86, x86_64, arm32, arm64, ppc, sparc, mips, alpha) to native assembly that links against the C runtime (EnginePl), which supplies the WAM's stacks, unification and the first-argument switch tables; a finite-domain constraint solver (EngineFD) is compiled the same way. The SWI-Prolog cut in this atlas holds the rival design: a VM interpreted in C")

pipeline = c.organ("prolog_compiled_in_four_stages_prolog_to_wam_in_prolog_wam_to_a_machine_independent_mini_assembly_in_c_mini_assembly_to_native_assembly_per_architecture_linked_against_a_c_runtime", human_name="Pl2Wam (pl2wam.pl, code_gen.pl, first_arg.pl, indexing.pl, reg_alloc.pl, inst_codif.pl: ~2,500 lines of Prolog, shipped also as .wam for bootstrap); Wam2Ma (wam2ma.c 2,416 lines); Ma2Asm (ma2asm.c + x86_64_any.c, arm64_any.c, ...); EnginePl (engine.c, wam_inst.c, unify.c, the stacks)", status="ACCEPTED",
    mechanism="the compiler is a Prolog program that reads clauses, generates WAM code with first-argument indexing (switch on term type, constant, structure) and allocates registers, and emits the instructions as text; the .wam files beside each .pl are the compiler's own compiled form, so a C-compiled runtime plus the .wam bootstraps the system; wam2ma expands each WAM instruction into MA instructions (calls into the runtime, jumps, register moves) and ma2asm emits native assembly through one mapper file per target; the result links with the runtime's unification, trail, choice-point and switch-table code",
    input="Prolog source", output="a native executable", state="none at compile time", update="per compilation", assumptions=["a small MA instruction set is enough to express the WAM's control flow, so porting is one mapper file; native code beats a VM for Prolog's call-heavy execution"],
    fitness_value_in_ancestor="native-code Prolog with a portable back end; the finite-domain solver reuses the same pipeline", failure_landscape="by reading: every port is a mapper file that must track the platform's calling convention (the src/Ma2Asm list shows eleven); compilation is slower than loading into a VM", human_prior="the WAM (Warren 1983); wamcc (Codognet & Diaz 1995) as the predecessor that compiled to C; GNU Prolog compiles to assembly instead", evidence_ref=PW + ":1-60; " + W2 + ":1-40; " + M2 + ":1-40", confidence="MEDIUM", portability="YES", compatibility="UNKNOWN", utility="UNKNOWN", source_boundary="the four directories; MEDIUM because bodies were not read",
    coverage={"input_topology": "TREE", "output_topology": "SEQUENCE", "state_amount": "NONE", "stochasticity": "DETERMINISTIC", "representation_sensitivity": "SENSITIVE"})

swt = c.organ("first_argument_indexing_as_runtime_switch_tables_over_atoms_and_functor_arity_pairs_built_by_the_runtime_and_selected_by_compiled_switch_instructions", human_name="wam_inst.c: Pl_Create_Swt_Table, Pl_Create_Swt_Atm_Element, Pl_Create_Swt_Stc_Element (101-180), Pl_Create_Functor_Arity_Tagged (84); Pl2Wam/indexing.pl and first_arg.pl", status="CANDIDATE",
    mechanism="the compiler groups a predicate's clauses by the type and value of their first argument and emits switch instructions; at load time the runtime builds hash tables mapping atoms and (functor, arity) keys to code addresses; a call dereferences the first argument and jumps through the table to the clauses that can match, so clauses that cannot unify are never tried and no choice point is created when only one group matches",
    input="a predicate's clauses; a call's first argument", output="a jump to a clause group", state="the switch tables (per predicate, built once)", update="per call", assumptions=["the first argument is the discriminating one for most predicates (the WAM's classic assumption); a hash on it is cheap"],
    fitness_value_in_ancestor="determinism detection without a cut; the largest single speed-up in WAM compilation", failure_landscape="by reading: predicates discriminated by a later argument get no benefit (JIT indexing in SWI is the rival answer)", human_prior="Warren 1983 (switch_on_term / switch_on_constant / switch_on_structure)", evidence_ref=WI + ":80-180 (constructors); indexing.pl (name only)", confidence="MEDIUM", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="the Swt_* functions and the indexing pass; CANDIDATE because indexing.pl was not read",
    coverage={"input_topology": "TREE", "output_topology": "DECISION", "state_amount": "LINEAR_IN_INPUT", "state_persistence": "PERSISTENT", "stochasticity": "DETERMINISTIC"})

c.reject("the WAM instruction semantics (wam_inst.c bodies, engine.c, unify.c, the stacks), garbage collection, the builtins (BipsPl), the finite-domain solver (EngineFD, Fd2C, BipsFD), the top level and line editor, the Windows GUI console", reason="OTHER", evidence="NOT READ; residue", note="EngineFD (a finite-domain constraint solver compiled through the same pipeline, Diaz & Codognet 1993 'clp(FD)') is a mechanism family of its own")
c.reject("'Prolog' as one organ", reason="NAME_HAS_NO_EXECUTABLE_BOUNDARY", evidence="the compilation pipeline and the indexing are separable; the atlas's swipl-9.2.9 shows the same language with an interpreted VM and JIT indexing")

c.edge(pipeline, swt, "feeds", note="the compiler emits switch instructions the runtime's tables serve")

c.pressure("a_logic_language_must_execute_at_native_speed_across_many_processor_architectures_while_the_compiler_itself_is_written_in_the_language_and_must_bootstrap_from_a_c_runtime",
    condition="an organism implements a language whose programs are call-heavy and nondeterministic; users run on many CPU architectures; the implementation's own compiler is a program of the language; the score is execution speed, the effort per port, and the ability to build from sources on a fresh machine", resource_or_constraint="a C compiler and an assembler per target; one mapper file per architecture",
    failure_condition="a VM's interpretation overhead on call-heavy code, a port that requires rewriting the code generator, or a bootstrap that needs a running instance", world_punishes="direct native code generation per architecture; a compiler without a shipped compiled form", world_rewards="a tiny intermediate assembly with per-target mappers; shipped .wam of the compiler",
    observable_consequence="benchmark speed vs the VM rival (swipl) on the same programs; lines per port in Ma2Asm; a clean bootstrap from sources on a new architecture", vacuity_condition="one architecture", trivial_shortcuts="compiling to C (wamcc's route, slower to compile and dependent on the C compiler's optimiser)",
    cheat_control="an organism given a native compiler per architecture must be fastest and cost the most per port; the VM rival must be slowest on nrev/zebra and cost zero per port; the MA route must sit between on both axes: the world must show all three",
    cost_class="CPU-scale", source_evidence="the src tree; pl2wam.pl; the Ma2Asm mapper list", purpose="PURPOSE: native-code ISO Prolog with constraints (Diaz 1996-)")

c.ancestry("derived_from", "Warren 1983 (WAM); wamcc (Codognet & Diaz 1995); clp(FD) (Diaz & Codognet 1993); rival of swipl-9.2.9 in this atlas", note="from the record and the source headers")
c.residue("LARGE_RESIDUE", ["no function body read; both organs at inventory depth", "the FD solver, GC and builtins unread", "nothing ran"], note="the four-stage pipeline is the mechanism this specimen was preserved for, and it is located at the directory level")
c.save(state="COARSE")
