"""Cut: gnu-apl-2.0 (GNU APL 2.0; ancestry-aware, Stage A COARSE; SOURCE_READ on M3; position 28 of the 2026-09-17 NOT_CUT order).
Read: src/Prefix.cc reduce_statements 900-935 (the shift/reduce loop) and the reduce_* function inventory 1391-3191; src/Prefix.hh
class comment 30-90; the phrase-table header in Prefix.def. NOT read: the reduce_* bodies, Value/Cell (array storage), the
primitive functions and operators (Bif_*), the workspace and I/O. Nothing ran (SOURCE_ONLY on M3; a C++ build).
"""
from nyx.atlas.author import Cut

P = "vault:gnu-apl-2.0/upstream/tree/apl-2.0/src/Prefix.cc"; PH = "vault:gnu-apl-2.0/upstream/tree/apl-2.0/src/Prefix.hh"; PD = "vault:gnu-apl-2.0/upstream/tree/apl-2.0/src/Prefix.def"
c = Cut("gnu-apl-2.0", mode="ANCESTRY_AWARE", inspected=["src/Prefix.cc 900-935 + reduce_* inventory", "src/Prefix.hh 30-90", "src/Prefix.def header"], evidence=[("SOURCE_READ", P + ":900-935"), ("SOURCE_READ", P + ":1391-3191"), ("SOURCE_READ", PH + ":30-90"), ("SOURCE_READ", PD + ":1-20")],
        note="APL's right-to-left evaluation with no operator precedence is implemented as a shift/reduce parser over token CLASSES (A value, F function, M monadic operator, D dyadic operator, V variable, ASS assignment, brackets, END) with a generated phrase table; the reduction rules ARE the language's semantics")

sr = c.organ("shift_reduce_over_token_classes_with_a_generated_phrase_table_matched_against_the_stack_top", human_name="Prefix::reduce_statements (900-935): grow (shift) / reduce; MAX_REDUCTION_LEN = 6; the phrase table (Prefix.def, generated by tools/phrase_gen)", status="ACCEPTED",
    mechanism="tokens of a statement are pushed right to left onto a stack; after each shift the top up to six token classes are looked up in a phrase table (hash or search tree, a compile-time choice); a matching phrase's reduce_* function replaces the matched tokens with one result token and returns an R_action (retry matching, shift, or done); the loop continues until the statement reduces to a single value or an error; the table is generated from a phrase list, not hand-written",
    input="a token string (the compiled statement)", output="a value token or an error with the PC rewound to the statement start", state="the token stack; the PC into the body", update="per token",
    assumptions=["APL's grammar is decidable on token CLASSES with six tokens of lookahead; the class of a name (function vs value) is known at run time, which is why the stack holds classes resolved late"],
    fitness_value_in_ancestor="right-to-left evaluation, operators binding tighter than functions, and bracket indexing all fall out of the phrase order; no precedence table", failure_landscape="by reading: an ambiguity that needs more than six tokens cannot be expressed; the R_action protocol lets a reduction re-classify a token and retry",
    human_prior="LALR(1)-style parsing (the comment says so) applied to a language usually described as 'no parser needed'", evidence_ref=P + ":900-935; " + PD, confidence="HIGH", portability="YES", compatibility="UNKNOWN", utility="UNKNOWN", source_boundary="reduce_statements and the phrase table",
    coverage={"input_topology": "SEQUENCE", "output_topology": "SCALAR", "state_amount": "LINEAR_IN_INPUT", "stochasticity": "DETERMINISTIC", "update_topology": "SINGLE_STEP", "order_sensitivity": "SENSITIVE"})

red = c.organ("reduction_rules_as_named_functions_one_per_phrase_shape", human_name="Prefix::reduce_A_F_B_ (dyadic), reduce_F_B_ (monadic), reduce_A_M_B_ / reduce_F_M__ (operators), reduce_V_ASS_B_ (assignment), reduce_LBRA_* (indexing), reduce_END_* / reduce_*_GOTO_* (statement end, branch), 40 in all", status="ACCEPTED",
    mechanism="each phrase shape has a function: A F B applies function F dyadically to values A and B; F B monadically; an operator M or D with its function operands builds a derived function token before application; V ASS B assigns; the bracket rules build index lists; the END and GOTO rules finish a statement or branch the PC; the rules call into the primitive implementations (Bif_*) and return how to continue",
    input="the matched tokens", output="one token", state="none beyond the stack", update="per reduction", assumptions=["every APL construct is one of ~40 shapes over 6 classes"],
    fitness_value_in_ancestor="the language's semantics are a flat list of 40 cases, each readable in isolation", failure_landscape="UNKNOWN by run", evidence_ref=P + ":1391-3191 (names and first lines)", confidence="MEDIUM", portability="YES", compatibility="UNKNOWN", utility="UNKNOWN", source_boundary="the reduce_* functions; MEDIUM because bodies were not read",
    coverage={"input_topology": "SEQUENCE", "output_topology": "SCALAR", "state_amount": "NONE", "stochasticity": "DETERMINISTIC"})

c.reject("Value/Cell (the array model: shapes, ravel, cell types), the ~200 primitive functions and operators, the workspace (Archive), I/O and the )commands, the emacs/XML tooling", reason="OTHER", evidence="NOT READ (~105,000 lines); residue", note="the array model (Value.cc, 3,244 lines) is the other mechanism family of APL and is unread")
c.reject("'APL interpreter' as one organ", reason="NAME_HAS_NO_EXECUTABLE_BOUNDARY", evidence="the evaluation-order machinery (this cut) and the array primitives (unread) are separable: the same parser could drive a different array model")

c.edge(sr, red, "selects"); c.edge(red, sr, "feeds", note="the result token and the R_action")

c.pressure("an_expression_language_with_late_bound_symbol_classes_must_be_evaluated_right_to_left_by_a_fixed_lookahead_machine_with_no_precedence_table",
    condition="tokens whose grammatical class (value, function, operator) is known only at run time; evaluation is strictly right to left with operators binding tighter than functions; the organism has bounded lookahead", resource_or_constraint="six tokens of lookahead; one phrase table",
    failure_condition="a wrong reduction on an ambiguous prefix, or a construct that needs more lookahead", world_punishes="a precedence table (wrong for APL) and a full parse tree (impossible before classes are known)", world_rewards="shift/reduce on classes with retry",
    observable_consequence="statements evaluated correctly vs a reference interpreter over the ISO APL test corpus, with the lookahead cap varied", vacuity_condition="a language with static classes", trivial_shortcuts="a reference interpreter as oracle (which is what a Stage C run would use)",
    cheat_control="an organism given each token's class in advance must parse with lookahead 3; the ancestor with the class hint removed must need the retry protocol: the world must show the difference",
    cost_class="CPU-scale", source_evidence="Prefix.cc reduce_statements; Prefix.def", purpose="PURPOSE: APL evaluation (GNU APL, Sauermann 2008-)")

c.ancestry("reimplementation_of", "ISO/IEC 13751 APL2; the evaluation scheme is the implementer's", note="from the source and the record's lineage")
c.residue("LARGE_RESIDUE", ["the array model and every primitive unread", "the 40 reduce_* bodies unread", "nothing ran"], note="the evaluation-order mechanism is located; the rest is named")
c.save(state="COARSE")
