"""Cut: go-explore-uber-2022 (Uber's Go-Explore release: robustified/ and policy_based/; ancestry-aware, Stage A COARSE; SOURCE_READ on
M3; position 48 of the 2026-09-17 NOT_CUT order). Read: robustified/goexplore_py/goexplore.py class Cell 167-255, class Explore
(names 353-1021), run_cycle 861-1011 in full, the names of try_split_frames / maybe_split_dynamic_state 464-693; randselectors.py
class WeightedSelector 52-144 (names and the cache; the weight formula NOT read). NOT read: explorers.py (the random / repeat-action
explorer), the Atari and Fetch environments, the robustification phase (imitation learning; not in this directory), policy_based/
(the later Go-Explore with a learned return policy). Nothing ran (needs gym/ALE/mujoco, absent on M3).
"""
from nyx.atlas.author import Cut

G = "vault:go-explore-uber-2022/upstream/tree/robustified/goexplore_py/goexplore.py"; RS = "vault:go-explore-uber-2022/upstream/tree/robustified/goexplore_py/randselectors.py"
c = Cut("go-explore-uber-2022", mode="ANCESTRY_AWARE", inspected=["goexplore.py 167-255, 353-1021 (run_cycle in full)", "randselectors.py 52-144"], evidence=[("SOURCE_READ", G + ":167-255"), ("SOURCE_READ", G + ":861-1011"), ("SOURCE_READ", RS + ":52-144")],
        note="exploration as an archive: states are mapped to coarse cells; each cell remembers the best score, the trajectory length, and a RESTORABLE emulator snapshot; a cycle selects cells by count-based weights, restores each, explores randomly from it, and adds or replaces cells when a trajectory reaches a new cell or the same cell with a better score or a shorter path; the cell representation itself can be re-fitted during the run (dynamic downscaling); robustification (turning the archive's trajectories into a policy) is a separate phase, not in this directory")

arch = c.organ("archive_of_cells_keyed_by_a_coarse_state_representation_each_holding_the_best_score_trajectory_length_restorable_snapshot_and_visit_counts", human_name="class Cell (167-255): score, seen_times, chosen_times, chosen_since_new, action_times, trajectory_len, restore, traj_last, real_cell, cell_frame; self.grid (a dict keyed by the cell key); Discretizer / GridDimension (82-166) for domain-specific keys", status="ACCEPTED",
    mechanism="a cell key is a discretisation of the state (a downscaled, quantised frame, or domain attributes such as room and position); the archive maps keys to Cell records; a record stores the emulator state needed to return to the cell (restore), the best score reached there, the length of the trajectory that reached it, the id of its last experience step (for reconstructing trajectories from the experience arrays), and four counters used by selection and reset on update",
    input="visited states with their emulator snapshots", output="a growing map of cells", state="the grid; the experience arrays", update="per trajectory", assumptions=["returning to a state is possible (a deterministic emulator with save/restore) so exploration never has to re-learn how to get somewhere; a coarse key groups similar states so the archive stays small"],
    fitness_value_in_ancestor="the exploration frontier is stored, not re-discovered; detachment and derailment (the paper's two failure modes of intrinsic motivation) do not arise", failure_landscape="by reading: the archive is only as good as the cell representation; the restore snapshot makes it emulator-bound (the policy_based/ directory exists because of that)",
    human_prior="Ecoffet et al. 2019/2021; the archive is the paper's central object", evidence_ref=G + ":167-255, 82-166", confidence="HIGH", portability="YES", compatibility="UNKNOWN", utility="UNKNOWN", source_boundary="class Cell and the grid",
    coverage={"input_topology": "STREAM", "output_topology": "SET", "state_amount": "UNBOUNDED", "state_persistence": "PERSISTENT", "memory": "ARCHIVE", "stochasticity": "DETERMINISTIC"})

sel = c.organ("cell_selection_by_weights_from_visit_counts_with_cached_per_cell_weights_and_neighbour_invalidation", human_name="randselectors.WeightedSelector (52-144): Weight(weight, power) for seen, chosen, action, room_cells, chosen_since_new; DirWeights; cell_update maintaining all_weights, cell_score, possible_scores and cached_pos_weights; choose_cell(grid, size)", status="CANDIDATE",
    mechanism="each cell's selection weight is a product of terms of the form weight / (count + 1)^power over its counters (seen, chosen, chosen since it last produced a new cell, actions taken from it), optionally with domain terms (neighbouring cells in a direction, level, doors); weights are cached per cell and recomputed only for the cell that changed and for its possible neighbours (by score); a batch of cells is drawn proportionally to weight",
    input="the archive's counters", output="a batch of cell keys", state="the weight caches", update="per cell change", assumptions=["cells visited or chosen less often are more likely to lead somewhere new (a count-based novelty prior); the caches make selection cheap as the archive grows"],
    fitness_value_in_ancestor="exploration effort spread over the frontier rather than concentrated where the score is", failure_landscape="UNKNOWN by run; by reading: the weights' powers and constants are per-game settings (experiment_settings.py, 1,491 lines)", evidence_ref=RS + ":52-144 (the formula lives in get_weight / choose_cell, NOT READ)", confidence="MEDIUM", portability="YES", compatibility="UNKNOWN", utility="UNKNOWN", source_boundary="WeightedSelector; CANDIDATE because the weight formula was not read",
    coverage={"input_topology": "SET", "output_topology": "SET", "state_amount": "LINEAR_IN_INPUT", "memory": "SUMMARY_STATISTIC", "stochasticity": "SEEDED_RANDOM", "update_topology": "PRIORITY"})

cyc = c.organ("return_then_explore_cycle_that_restores_a_chosen_cell_explores_from_it_and_accepts_a_cell_on_a_new_key_or_a_higher_score_or_a_shorter_path_resetting_the_counters_of_updated_cells", human_name="run_cycle (861-1011): selector.choose_cell; POOL.map(process_cell) restores and explores; the trajectory walk with seen_cells; should_accept_cell (1012-1020); the update block (restore, score, trajectory_len, traj_last, cell_frame); reset_cell_on_update", status="ACCEPTED",
    mechanism="per cycle: draw a batch of cells; in worker processes restore each cell's snapshot and run the explorer (random actions) for a bounded number of steps recording every step's cell, reward and snapshot; back in the main process walk each trajectory: increment seen counts (once per cell per trajectory), append to the experience arrays, and when a step lands in a cell that is new, or has a higher score, or the same score with a shorter trajectory, overwrite that cell's record (snapshot, score, length, frame) and zero the start cell's chosen-since-new; optionally zero all counters of updated cells so they are re-explored",
    input="a batch of cells", output="an updated archive and appended experience", state="the archive; frames counters", update="per cycle", assumptions=["exploring from a returned-to state with random actions is enough to find new cells (the 'exploration is easy once you can return' claim); shorter trajectories to the same cell are preferable for later robustification"],
    fitness_value_in_ancestor="Montezuma's Revenge and Pitfall solved by exploration alone (the paper's result); the archive's trajectories are the demonstrations for the second phase", failure_landscape="by reading: the accept rule prefers score, so a longer trajectory with a higher score displaces a shorter one; ignore_death trims the last steps of a trajectory that ended in death",
    human_prior="the paper's Algorithm 1", evidence_ref=G + ":861-1020", confidence="HIGH", portability="YES", compatibility="UNKNOWN", utility="UNKNOWN", source_boundary="run_cycle and should_accept_cell",
    coverage={"input_topology": "SET", "output_topology": "SET", "state_amount": "UNBOUNDED", "feedback": "CLOSED_LOOP", "stochasticity": "SEEDED_RANDOM", "update_topology": "PARALLEL_ROUNDS"})

dyn = c.organ("cell_representation_refitted_during_the_run_by_searching_downscale_parameters_that_make_the_cell_count_distribution_match_a_target", human_name="try_split_frames / maybe_split_dynamic_state (464-693): random_recent_frames, get_dist_score (entropy normalised by a target length), geometric proposals for shape and pixel depth, the grid re-keying with counter carry-over (662-670)", status="CANDIDATE",
    mechanism="a reservoir of recent frames is periodically re-discretised under candidate (shape, pixel-depth) parameters proposed geometrically around the current best; a candidate is scored by the entropy of the induced cell distribution penalised by its distance from a target number of cells; the best parameters replace the current ones and the archive is re-keyed, merging cells and carrying their counters and best records over",
    input="recent frames; the current parameters", output="new parameters and a re-keyed archive", state="the reservoir; the parameters", update="periodically", assumptions=["a good representation splits the visited states into neither too few nor too many cells; entropy against a target size is a usable proxy without domain knowledge"],
    fitness_value_in_ancestor="the domain-agnostic variant of the paper (no hand-made room/position key)", failure_landscape="UNKNOWN by run", evidence_ref=G + ":464-693 (structure; the scoring read at 470-495)", confidence="MEDIUM", portability="YES", compatibility="UNKNOWN", utility="UNKNOWN", source_boundary="the two functions; CANDIDATE because the proposal loop was skimmed",
    coverage={"input_topology": "SET", "output_topology": "VECTOR", "state_amount": "CONSTANT", "stochasticity": "SEEDED_RANDOM", "representation_sensitivity": "SENSITIVE"})

c.reject("explorers.py (random actions with a repeat probability), the game environments (Atari via ALE wrappers, Fetch via mujoco), the process pool and pickling helpers, checkpointing, visualisation", reason="OTHER", evidence="NOT READ; residue")
c.reject("the robustification phase (backward algorithm / imitation from the archive's trajectories) and policy_based/ (a learned goal-conditioned return policy)", reason="OTHER", evidence="NOT in this directory / NOT READ", note="policy_based/ is a second body inside the specimen: the mechanism that replaces 'restore' by 'return by policy'; a DEEP pass should cut it separately")
c.reject("'Go-Explore' as one organ", reason="NAME_HAS_NO_EXECUTABLE_BOUNDARY", evidence="archive, selection, cycle and representation refit are separable; the paper's ablations vary them separately")

c.edge(sel, cyc, "feeds", note="the batch"); c.edge(cyc, arch, "updates"); c.edge(arch, sel, "feeds", note="counters"); c.edge(dyn, arch, "transforms", note="re-keys"); c.edge(cyc, dyn, "feeds", note="recent frames")

c.pressure("a_sparse_reward_environment_with_deceptive_local_rewards_must_be_explored_to_its_far_states_when_the_organism_can_save_and_restore_the_world_but_the_state_space_is_too_large_to_enumerate",
    condition="an organism acts in a deterministic environment with save/restore; rewards are rare and locally misleading; the score is the number of distinct far states reached (and the best score) per environment step; the state space is huge but coarsely clusterable", resource_or_constraint="environment steps; archive memory; the coarseness of the key",
    failure_condition="detachment (forgetting how to reach a frontier) or derailment (failing to return before exploring), or an archive that grows without reaching new places", world_punishes="intrinsic-motivation exploration that must re-traverse; keys too fine (no coverage) or too coarse (no frontier)", world_rewards="an archive with restore, count-based selection, and a representation tuned to a target cell count",
    observable_consequence="cells discovered and best score vs environment steps on Montezuma's Revenge with selection uniform vs count-weighted, and with the key fixed vs refitted", vacuity_condition="dense rewards", trivial_shortcuts="a state enumerator (which the world must make infeasible by size)",
    cheat_control="an organism given the map of far states must reach them in the minimum steps; the archive with restore disabled (must re-traverse) must show derailment; uniform selection must show slower coverage than count-weighted: the world must show all three",
    cost_class="GPU-scale", source_evidence="goexplore.py run_cycle; randselectors.py; the paper's ablations as cited in the README", purpose="PURPOSE: hard-exploration reinforcement learning (Ecoffet et al. 2019-2021)")

c.ancestry("algorithm_from", "Ecoffet, Huizinga, Lehman, Stanley, Clune 2019 (arXiv) / 2021 (Nature); the archive idea descends from novelty search and MAP-Elites (Lehman & Stanley 2011; Mouret & Clune 2015)", note="from the README and the record")
c.residue("LARGE_RESIDUE", ["the selection weight formula and the representation search loop skimmed (two CANDIDATE organs)", "policy_based/ (the second body) unread", "robustification not in the body", "nothing ran (ALE/mujoco absent)"], note="the four mechanisms of the exploration phase are located; this is the operator's POET-adjacent family and a natural comparison for the POET cut when that body lands")
c.save(state="COARSE")
