"""Cut: graphplan-blum-furst-1995 (Graphplan, CMU 1995; ancestry-aware, Stage A DEEP; SOURCE_READ on M3; position 43 of the
2026-09-17 NOT_CUT order). Read: Source/graphplan.c create_graph_layer 371-440, make_graph_piece 860-952; Source/planner.c 1-96
(the completeness comment, do_plan), basicplan 191-330. NOT read: find_all_mutex_ops / find_mutex_facts bodies, the bad_table
hashing (insert_bad / lookup_bad / PARTIALsubset_lookup), can_hope_to_solve (the lower bound), constrict (greedy), the
operator instantiation (do_operator_rec), the lex/yacc front end, utilities.c. Nothing ran (C; no compiler on M3).
"""
from nyx.atlas.author import Cut

G = "vault:graphplan-blum-furst-1995/upstream/tree/Source/graphplan.c"; PL = "vault:graphplan-blum-furst-1995/upstream/tree/Source/planner.c"
c = Cut("graphplan-blum-furst-1995", mode="ANCESTRY_AWARE", inspected=["graphplan.c 371-440, 860-952", "planner.c 1-96, 191-330"], evidence=[("SOURCE_READ", G + ":371-440"), ("SOURCE_READ", G + ":860-952"), ("SOURCE_READ", PL + ":1-96"), ("SOURCE_READ", PL + ":191-330")],
        note="planning as two phases over a layered graph: forward, build alternating fact and action layers (every applicable ground action plus a no-op per fact) and mark pairs that cannot co-occur (mutex), until the layers stop changing; backward, extract a plan by choosing, for each goal at the last layer, an achieving action not mutex with the actions already chosen, recursing to the previous layer; unsolvable goal sets are memoised per layer, and the graph levelling off plus a non-growing memo table proves unsolvability")

layer = c.organ("forward_construction_of_alternating_fact_and_action_layers_with_a_noop_per_fact_placed_first_until_the_fact_layer_stops_changing", human_name="create_graph_layer (371-440): copy facts forward, do_operator per op, make_noop_layer, set_uid, find_all_mutex_ops, find_mutex_facts, same_as_prev_flag / first_full_time; make_graph_piece (860-952) builds one action node with its precondition and effect edges", status="ACCEPTED",
    mechanism="at each time step the facts are copied to the next layer (linked prev/next), every operator is instantiated against the current facts (an action whose preconditions are pairwise mutex is not inserted: 'Avoiding'), a no-op action per fact is inserted FIRST so the planner tries persistence before change, ids are assigned, mutexes computed, and if the fact count and mutex count equal the previous layer's the graph has levelled off and later layers are copies (make_copy)",
    input="ground operators, initial facts", output="fact_table[t], op_table[t] with edges", state="the layered graph (hash tables per layer)", update="per layer", assumptions=["the reachable-fact set and its mutexes are a polynomial-size over-approximation of reachability that tightens the search (the Graphplan insight); levelling off is detectable by counts"],
    fitness_value_in_ancestor="a polynomial forward pass replaces most of the exponential backward search", failure_landscape="by reading: the graph is built on GROUND actions (all instantiations), so large domains blow up here first (MAXNODES); delete effects are stored on the action as strings and consulted only for mutexes",
    human_prior="Blum & Furst 1995/1997 'Fast planning through planning graph analysis'", evidence_ref=G + ":371-440, 860-952", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="create_graph_layer and make_graph_piece",
    coverage={"input_topology": "SET", "output_topology": "GRAPH", "state_amount": "SUPERLINEAR", "state_persistence": "PER_EPISODE", "stochasticity": "DETERMINISTIC", "update_topology": "SWEEP"})

mutex = c.organ("pairwise_mutual_exclusion_between_actions_from_interference_and_competing_needs_and_between_facts_from_all_achievers_being_mutex", human_name="find_all_mutex_ops / find_mutex_facts (called at 415-419; bodies not read); are_mutex; mark_exclusive / unmark_exclusive (planner.c 131-142)", status="CANDIDATE",
    mechanism="two actions at a layer are mutex if one deletes a precondition or effect of the other (interference) or if their preconditions are mutex (competing needs); two facts at a layer are mutex if every pair of their achievers is mutex; the relation is a per-layer bit vector (bvec_len) read by are_mutex; during extraction, choosing an action marks every action mutex with it as unavailable (mark_exclusive) and unmarks on backtrack",
    input="the layer's actions and their precondition/effect/delete lists", output="a symmetric relation per layer", state="bit vectors", update="per layer", assumptions=["binary exclusion captures most of what makes goal sets unachievable; higher-order exclusions are left to the search"],
    fitness_value_in_ancestor="the pruning that makes the backward search feasible and the reason the graph levels off", failure_landscape="UNKNOWN by run", human_prior="the same paper", evidence_ref=G + ":415-419 (calls); " + PL + ":131-142", confidence="MEDIUM", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="the two find_* functions and the marking; CANDIDATE because their bodies were not read",
    coverage={"input_topology": "GRAPH", "output_topology": "SET", "state_amount": "SUPERLINEAR", "stochasticity": "DETERMINISTIC", "update_topology": "SWEEP"})

extract = c.organ("backward_goal_set_extraction_layer_by_layer_choosing_a_non_mutex_achiever_per_goal_with_a_proactive_check_that_remaining_goals_stay_achievable", human_name="basicplan (planner.c 191-330): goals_at[time][cindex]; in_edges loop with IS_MARKED skip; goals_still_possible; used / is_true counters; the undo block; action_set_is_minimal at the layer boundary", status="ACCEPTED",
    mechanism="at a layer, take the next unsatisfied goal (skipping goals already made true by chosen actions), try each achiever (no-ops first) that is not marked mutex with a prior choice: mark its exclusions, check every remaining goal still has an unmarked achiever, add its preconditions to the previous layer's goal set (counting uses so duplicates are shared), recurse to the next goal; when all goals at the layer are served, recurse to the previous layer with the new goal set; undo counters and marks on return; success at time 0",
    input="a goal set at the last layer", output="a plan (the used actions per layer) or failure", state="goals_at arrays, marks, used/is_true counts", update="per choice", assumptions=["the mutex relations in the graph make the chosen action set legal without further checking ('it does no other redundant checking')"],
    fitness_value_in_ancestor="a plan is a set of actions per layer, so parallel actions come for free", failure_landscape="by reading: the search is exponential in the worst case; the memo table and the lower bound (do_lower) are the mitigations; the authors note a smallest-achiever-count goal ordering 'didn't generally help much'",
    human_prior="the same paper", evidence_ref=PL + ":191-330", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="basicplan / runbasicplan",
    coverage={"input_topology": "SET", "output_topology": "SEQUENCE", "state_amount": "LINEAR_IN_INPUT", "stochasticity": "DETERMINISTIC", "update_topology": "RECURSIVE", "recovery": "ROLLS_BACK"})

memo = c.organ("memoisation_of_unsolvable_goal_sets_per_layer_with_a_completeness_proof_from_a_levelled_graph_and_a_non_growing_table", human_name="insert_bad / lookup_bad / PARTIALsubset_lookup (called at basicplan 232-241; bodies not read; random per-fact codes rand1 set at create_graph_layer 407); the completeness comment (planner.c 11-24); can_stop", status="CANDIDATE",
    mechanism="a goal set that fails at a layer is inserted in a per-layer hash table keyed by the sum of random per-fact codes; a later visit of the same set (or, with do_subsets, a superset of a known-bad set) fails immediately; once the graph has levelled off, if a full time step passes in which the table at the levelled layer does not grow, every plan would have to pass through a known-bad set and the problem is declared unsolvable (the argument in the file header)",
    input="failed goal sets", output="a fast 'no', and termination", state="bad_table per layer", update="per failure", assumptions=["goal sets recur across branches (they do: the same subgoals arise from different orderings); the random-code hash is collision-tolerant in practice"],
    fitness_value_in_ancestor="the planner terminates on unsolvable problems, which forward-search planners of the time did not", failure_landscape="UNKNOWN by run", human_prior="the same paper (section on termination)", evidence_ref=PL + ":11-24, 232-241; " + G + ":407", confidence="MEDIUM", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="the bad_table functions and can_stop; CANDIDATE because the table code was not read",
    coverage={"input_topology": "SET", "output_topology": "DECISION", "state_amount": "SUPERLINEAR", "state_persistence": "PER_EPISODE", "memory": "ARCHIVE", "stochasticity": "SEEDED_RANDOM"})

c.reject("do_operator_rec (matching operator parameters against facts and types), the lex/yacc operator and fact readers, useful_facts / delete_useless (irrelevance pruning), the X viewer, constrict (greedy) and build_up_to_plan", reason="OTHER", evidence="NOT READ; residue")
c.reject("'Graphplan' as one organ", reason="NAME_HAS_NO_EXECUTABLE_BOUNDARY", evidence="graph building, mutex, extraction and memoisation are four separable mechanisms; later planners (FF, in this atlas) kept the first and dropped the third")

c.edge(layer, mutex, "feeds"); c.edge(mutex, extract, "gates"); c.edge(layer, extract, "feeds"); c.edge(memo, extract, "gates"); c.edge(extract, memo, "feeds", note="failed sets")

c.pressure("a_goal_must_be_reached_by_a_sequence_of_actions_with_preconditions_and_effects_when_naive_backward_chaining_is_exponential_and_unsolvable_instances_must_be_recognised",
    condition="an organism is given ground actions (preconditions, adds, deletes), an initial state and goals; it must return a valid (possibly parallel) plan or 'unsolvable'; instances include unsolvable ones", resource_or_constraint="time and memory polynomial in the reachable facts for the forward phase; the backward phase is the exponential budget",
    failure_condition="an invalid plan, a solvable instance missed, or non-termination on an unsolvable one", world_punishes="plain backward chaining (no pruning; no termination proof); plain forward search (no goal focus)", world_rewards="a reachability over-approximation with binary exclusions, memoised failures and a termination argument",
    observable_consequence="nodes expanded and plans found on the 1995 benchmark set (rocket, blocks, logistics) with mutexes on/off and memoisation on/off; termination on unsolvable variants", vacuity_condition="a domain with no deletes (the graph is exact and the plan is the first layer where goals appear)", trivial_shortcuts="a domain-specific heuristic (which the world must withhold)",
    cheat_control="an organism given a plan oracle must expand zero nodes; the extraction with mutexes disabled must expand exponentially more on rocket; with memoisation disabled the unsolvable variant must not terminate within the budget: the world must show all three",
    cost_class="CPU-scale", source_evidence="graphplan.c create_graph_layer; planner.c basicplan and the completeness comment", purpose="PURPOSE: STRIPS planning (Blum & Furst 1995)")

c.ancestry("algorithm_from", "Blum & Furst 1995 (AI Journal 1997); the atlas's ff-planner-2.3 cut records FF as the successor that kept the graph as a heuristic and replaced extraction with forward search", note="from the source and the FF cut in this atlas")
c.residue("PARTIALLY_EXPLAINED", ["mutex computation and the memo table read at their call sites only", "the front end and instantiation unread", "nothing ran"], note="the four mechanisms are located; two are CANDIDATE pending a read of their bodies")
c.save(state="DEEP")
