"""Cut: indirect-self-tuning-regulator-liaosteve (a MATLAB script pair reproducing Astrom & Wittenmark's indirect self-tuning regulator;
ancestry-aware, Stage A DEEP; SOURCE_READ on M3; position 58 of the 2026-09-17 NOT_CUT order). Read: main_code.m in full (218 lines:
two experiments, zero-cancelling and non-cancelling), rls_forgetting.m in full (6 lines). Nothing ran (MATLAB absent on M3; the
arithmetic is 20 lines and would port to numpy in an hour: noted as a candidate, not done).
"""
from nyx.atlas.author import Cut

M = "vault:indirect-self-tuning-regulator-liaosteve/upstream/tree/main_code.m"; R = "vault:indirect-self-tuning-regulator-liaosteve/upstream/tree/rls_forgetting.m"
c = Cut("indirect-self-tuning-regulator-liaosteve", mode="ANCESTRY_AWARE", inspected=["main_code.m 1-218", "rls_forgetting.m 1-6"], evidence=[("SOURCE_READ", M + ":1-218"), ("SOURCE_READ", R + ":1-6")],
        note="the indirect adaptive controller in its textbook form: at every sample a recursive least-squares estimator with exponential forgetting updates the plant's four parameters from the last two inputs and outputs; the controller polynomials R, S, T are then re-derived from the estimates by pole placement against a fixed reference model; the control is applied and the loop repeats. The script runs the design twice: cancelling the plant zero (a division by b0, which fails for a non-minimum-phase plant) and not cancelling it (the Diophantine solution with the extra observer pole a0)")

rls = c.organ("recursive_least_squares_with_exponential_forgetting_over_a_regressor_of_the_last_two_outputs_and_inputs", human_name="rls_forgetting.m: k = P phi' / (lambda + phi P phi'); P = (P - k phi P) / lambda; theta = theta + k (y - phi theta); main_code.m: phi = [-y(t), -y(t-1), u(t), u(t-1)], lambda = 0.8, P0 = diag(100, 100, 1, 1), theta0 = [0, 0, 0.01, 0.2]", status="ACCEPTED",
    mechanism="the plant is modelled as y(t+1) = -a1 y(t) - a2 y(t-1) + b0 u(t) + b1 u(t-1); each sample forms the regressor from the last two outputs and inputs, computes the gain from the covariance, corrects the parameter estimate by the prediction error, and shrinks the covariance with a forgetting factor of 0.8 so old data is discounted geometrically; the initial covariance is large on the a's and small on the b's, and b0 starts at 0.01 rather than 0 so the first division in the design is finite",
    input="y(t), u(t) history", output="theta (a1, a2, b0, b1), P", state="theta, P", update="per sample", assumptions=["the plant is linear, second order and slowly varying (forgetting makes the estimator track drift at the price of noise sensitivity); the regressor is persistently excited (the square-wave reference supplies it)"],
    fitness_value_in_ancestor="O(n^2) per step, no matrix inversion; the estimator the textbook builds every adaptive scheme on", failure_landscape="by reading: with lambda = 0.8 and no excitation the covariance grows without bound (estimator wind-up), which the script avoids only because the reference keeps switching; b0 near zero makes the design explode",
    human_prior="Astrom & Wittenmark 1989/1995 Adaptive Control, chapter 2 (RLS with forgetting)", evidence_ref=R + ":1-6; " + M + ":6-20, 28-33", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="rls_forgetting.m and the regressor lines",
    coverage={"input_topology": "SEQUENCE", "output_topology": "VECTOR", "state_amount": "CONSTANT", "memory": "SUMMARY_STATISTIC", "feedback": "CLOSED_LOOP", "stochasticity": "DETERMINISTIC", "update_topology": "SINGLE_STEP", "failure_mode": "DIVERGES"})

design = c.organ("controller_polynomials_re_derived_every_sample_by_pole_placement_against_a_fixed_reference_model_in_two_variants_cancelling_or_keeping_the_plant_zero", human_name="main_code.m experiment 1 (28-33): r1 = b1/b0, s0 = (am1 - a1)/b0, s1 = (am2 - a2)/b0, t0 = bm0/b0 (zero cancelled); experiment 2 (125-140): r1, s0, s1 from the Diophantine identity with the observer pole a0 and t0 = (1 + am1 + am2)/(b0 + b1), a0 re-estimated as (a2 r1 + b1 s1)/am2; the control law u(t+1) = -r1 u(t) + t0 uc(t) [+ t1 uc(t-1)] - s0 y(t) - s1 y(t-1); reference model am1 = -1.3205, am2 = 0.4966, bm0 = 0.1761",
    status="ACCEPTED",
    mechanism="with the estimated plant (A, B) and a desired closed-loop denominator Am (from the reference model), solve for R, S such that A R + B S = Am (times an observer polynomial) and set T so the closed loop's DC gain matches the model; variant 1 cancels the plant zero by dividing by b0 (a one-line design that requires the zero to be stable); variant 2 keeps the zero, adds an observer pole a0 and solves the 2x2 identity in closed form; the estimated a0 is updated from the previous solution; the design runs at every sample from the current estimates (certainty equivalence)",
    input="theta; Am, bm0", output="r1, s0, s1, t0 (t1)", state="a0 in variant 2", update="per sample", assumptions=["the estimates are the truth (certainty equivalence); the reference model's poles are achievable; in variant 1 the plant zero is inside the unit circle"],
    fitness_value_in_ancestor="the closed loop follows the reference model once the estimates converge (the plots in the script show a1, a2, b0, b1 reaching -1.6065, 0.6065, 0.1065, 0.0902, the simulated plant's true values)", failure_landscape="by reading: variant 1 divides by b0, so a small or wrong b0 estimate produces huge gains (the record's 'zero cancellation' caveat); the simulated plant's zero at -0.847 is stable so variant 1 happens to work here",
    human_prior="Astrom & Wittenmark 1995, Example 3.5 (indirect STR with and without zero cancellation)", evidence_ref=M + ":28-33, 125-140, 21-26", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="the design lines of both experiments",
    coverage={"input_topology": "VECTOR", "output_topology": "VECTOR", "state_amount": "CONSTANT", "feedback": "CLOSED_LOOP", "stochasticity": "DETERMINISTIC", "update_topology": "SINGLE_STEP", "representation_sensitivity": "SENSITIVE"})

c.reject("the simulated plant y(t+1) = 1.6065 y(t) - 0.6065 y(t-1) + 0.1065 u(t) + 0.0902 u(t-1) (a discretised first-order-plus-integrator), the square-wave reference, the plotting", reason="OTHER", evidence=M + ":34-45, 60-118", note="the WORLD of the script; its constants are the cheat control (the true theta)")
c.reject("'self-tuning regulator' as one organ", reason="NAME_HAS_NO_EXECUTABLE_BOUNDARY", evidence="the estimator and the design are separable (direct STRs replace the second; other estimators replace the first)")

c.edge(rls, design, "feeds"); c.edge(design, rls, "feeds", note="u(t) enters the next regressor")

c.pressure("a_plant_with_unknown_slowly_varying_parameters_must_be_made_to_follow_a_reference_model_by_a_controller_redesigned_from_online_estimates_when_the_estimates_are_wrong_at_first_and_when_cancelling_the_plant_zero_may_be_unstable",
    condition="an organism controls a second-order plant whose parameters it does not know; a reference model prescribes the closed-loop response to a square wave; the score is tracking error after the transient and the peak control effort; the plant may have a non-minimum-phase zero in some instances", resource_or_constraint="one RLS update and one polynomial solve per sample",
    failure_condition="divergence during the transient (gains from bad estimates), or instability from cancelling an unstable zero", world_punishes="fixed-gain control on a drifting plant; zero cancellation on the non-minimum-phase instance", world_rewards="forgetting-factor estimation with a bounded initial b0 and a design that keeps the zero",
    observable_consequence="tracking error and peak |u| over time for variant 1 vs variant 2 on the script's plant and on a plant with the zero moved outside the unit circle; estimate trajectories against the true theta", vacuity_condition="a known plant", trivial_shortcuts="the true parameters as the initial estimate (the cheat control)",
    cheat_control="an organism initialised at the true theta with lambda = 1 must track the model from the first sample; variant 1 on the unstable-zero plant must diverge; variant 2 must not: the world must show all three",
    cost_class="CPU-scale", source_evidence="main_code.m both experiments; rls_forgetting.m", purpose="PURPOSE: adaptive control (Astrom & Wittenmark 1973-1995), reproduced as a student script")

c.ancestry("reimplementation_of", "Astrom & Wittenmark 1973 (self-tuning regulator); Adaptive Control 1989/1995 Example 3.5", note="from the record and the plot titles")
c.residue("EXPLAINED_BY_CURRENT_CUT", ["nothing unread", "nothing ran; a numpy port of the 20 arithmetic lines would make this an M3-runnable world with the true theta as oracle (candidate, not done)"], note="both mechanisms and the world's constants are located")
c.save(state="DEEP")
