"""Cut: minpack-netlib-1980 (MINPACK-1, Argonne; ancestry-aware, Stage A DEEP; SOURCE_READ on M3; position 36 of the 2026-09-17
NOT_CUT order). Read: lmpar.f in full (264 lines: the Levenberg-Marquardt parameter by a safeguarded Newton iteration on
||D x(par)|| - delta), lmder.f 330-440 (the trust-region step acceptance and delta/par update), dogleg.f 60-175 (the Powell dogleg
step), hybrd.f 208-440 (Broyden rank-one update, the ncsuc/ncfail/nslow monitors). NOT read: qrfac.f, qrsolv.f, r1updt.f, r1mpyq.f
(the linear algebra), lmdif/lmstr variants, chkder, fdjac1/2, the ex/ test drivers and outputs. Nothing ran (Fortran 77; no compiler on M3).
"""
from nyx.atlas.author import Cut

LP = "vault:minpack-netlib-1980/upstream/lmpar.f"; LD = "vault:minpack-netlib-1980/upstream/lmder.f"; DG = "vault:minpack-netlib-1980/upstream/dogleg.f"; HB = "vault:minpack-netlib-1980/upstream/hybrd.f"
c = Cut("minpack-netlib-1980", mode="ANCESTRY_AWARE", inspected=["lmpar.f 1-264", "lmder.f 330-440", "dogleg.f 60-175", "hybrd.f 208-440"], evidence=[("SOURCE_READ", LP + ":1-264"), ("SOURCE_READ", LD + ":330-440"), ("SOURCE_READ", DG + ":60-175"), ("SOURCE_READ", HB + ":208-440")],
        note="two trust-region methods over a shared QR: least squares (LM: the step solves a damped system whose damping is chosen so the scaled step has length ~delta) and nonlinear equations (Powell hybrid: a dogleg between the Gauss-Newton and steepest-descent steps, with the Jacobian updated by Broyden rank-one and re-evaluated only when progress stalls); both accept a step by the ratio of actual to predicted reduction and move delta by fixed factors; the ancestor of scipy's leastsq and fsolve")

lmpar = c.organ("damping_parameter_found_by_a_safeguarded_newton_iteration_on_the_scaled_step_length_minus_the_trust_radius_with_bracketing_bounds", human_name="lmpar (1-264): parl / paru from the Gauss-Newton step and the gradient; the qrsolv iteration; 'abs(dxnorm-delta) .le. 0.1*delta' or 10 iterations", status="ACCEPTED",
    mechanism="first solve the undamped (par = 0) least-squares step from the QR; if its scaled norm is within delta (10 percent slack) accept par = 0; else bracket par: a lower bound from the derivative of the step norm (parl, zero if the Jacobian is rank deficient) and an upper bound from the gradient norm over delta (paru); iterate at most 10 times: solve the damped system by qrsolv (a sequence of Givens rotations on R with sqrt(par) D appended), evaluate fp = ||D x|| - delta, stop if |fp| <= 0.1 delta, else take a Newton correction on 1/||D x||, update the bracket by the sign of fp, and set par = max(parl, par + parc)",
    input="R, the permutation, Q'b, the scaling D, delta, the previous par", output="par, x(par), and the Cholesky factor S", state="none across calls except par as a warm start", update="per outer iteration", assumptions=["||D x(par)|| is decreasing and convex in par (Hebden / More: so the Newton iteration on its reciprocal converges monotonically); 10 iterations and a 10 percent tolerance suffice because the outer loop tolerates an inexact radius"],
    fitness_value_in_ancestor="the trust-region subproblem for least squares solved to 10 percent in a handful of cheap rotations rather than by an eigen-decomposition", failure_landscape="by reading: rank-deficient Jacobians set parl = 0 and the exceptional-case exit accepts a step inside the region; the 10-iteration cap returns 'the best value obtained so far'",
    human_prior="Hebden 1973; More 1978 'The Levenberg-Marquardt algorithm: implementation and theory' (the paper this code implements)", evidence_ref=LP + ":60-264", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="lmpar",
    coverage={"input_topology": "MATRIX", "output_topology": "VECTOR", "state_amount": "CONSTANT", "stochasticity": "DETERMINISTIC", "update_topology": "RECURSIVE", "uncertainty": "POINT"})

tr = c.organ("step_accepted_by_the_ratio_of_actual_to_predicted_reduction_with_the_radius_shrunk_by_an_interpolated_factor_or_doubled", human_name="lmder (330-440): actred, prered, dirder, ratio; 'if (ratio .gt. p25) go to 240'; temp = p5*dirder/(dirder + p5*actred); delta = pnorm/p5 on ratio >= 0.75; the info 1-8 tests", status="ACCEPTED",
    mechanism="after a step p of scaled length pnorm: actual reduction = 1 - (fnorm1/fnorm)^2 (or -1 if the residual grew tenfold); predicted reduction from the linear model = ||J p||^2/fnorm^2 + 2 par pnorm^2/fnorm^2, directional derivative likewise; ratio = actual/predicted; if ratio <= 0.25 shrink delta to temp * min(delta, 10 pnorm) with temp from a quadratic interpolation of the residual along p (clamped to [0.1, 0.5]) and divide par by temp; if ratio >= 0.75 (or par = 0) set delta = 2 pnorm and halve par; accept the step only if ratio >= 1e-4; convergence tests on |actred| and prered (ftol), delta vs xtol ||D x||, and the scaled gradient (gtol); the first iteration caps delta at pnorm",
    input="the step, the residual norms, par", output="accept/reject; new delta and par", state="delta, par", update="per iteration", assumptions=["the quadratic model predicts the reduction well within delta; the actual/predicted ratio is a reliable measure of model quality (the trust-region premise)"],
    fitness_value_in_ancestor="global convergence without a line search; the radius adapts to the model's local accuracy", failure_landscape="by reading: constants (0.25, 0.75, 1e-4, factor 100 for the initial delta) are the paper's; a bad scaling D (mode 1 uses the Jacobian column norms) changes the geometry of delta",
    human_prior="More 1978 section 4; the same acceptance rule is in every later trust-region code", evidence_ref=LD + ":330-440", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="the inner loop of lmder (shared verbatim by lmdif and lmstr)",
    coverage={"input_topology": "VECTOR", "output_topology": "DECISION", "state_amount": "CONSTANT", "feedback": "CLOSED_LOOP", "stochasticity": "DETERMINISTIC", "update_topology": "RECURSIVE", "recovery": "ROLLS_BACK"})

dog = c.organ("dogleg_step_that_takes_the_gauss_newton_point_if_inside_the_region_else_the_cauchy_point_or_a_convex_combination_on_the_boundary", human_name="dogleg (60-175): the Gauss-Newton solve from R packed by rows with a diagonal repair; qnorm <= delta -> return; sgnorm (the Cauchy step length); alpha from the boundary quadratic", status="ACCEPTED",
    mechanism="solve R x = Q'b for the Gauss-Newton step (a zero diagonal entry is replaced by eps times the largest entry in its row: a cheap rank repair); if its scaled norm is within delta take it; else compute the scaled gradient and the Cauchy (steepest-descent minimiser) step length sgnorm; if sgnorm >= delta take the gradient step scaled to delta; else take the point on the segment from the Cauchy point to the Gauss-Newton point that lies on the boundary (alpha from a closed-form quadratic)",
    input="R, Q'b, D, delta", output="a step within the region", state="none", update="per iteration", assumptions=["the piecewise-linear dogleg path approximates the true trust-region minimiser well enough for the ratio test to accept most steps"],
    fitness_value_in_ancestor="one triangular solve and a few norms per step; no damping parameter search", failure_landscape="by reading: the diagonal repair silently changes a singular system; the path is not the exact subproblem minimiser (Powell 1970 argued it need not be)",
    human_prior="Powell 1970 'A hybrid method for nonlinear equations'", evidence_ref=DG + ":60-175", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="dogleg",
    coverage={"input_topology": "MATRIX", "output_topology": "VECTOR", "state_amount": "NONE", "stochasticity": "DETERMINISTIC", "uncertainty": "POINT"})

broy = c.organ("jacobian_kept_by_broyden_rank_one_updates_and_re_evaluated_by_finite_differences_only_after_two_consecutive_failures_or_stalled_progress", human_name="hybrd (208-440): jeval, ncsuc / ncfail, nslow1 / nslow2, 'if (ncfail .eq. 2) go to 290', r1updt / r1mpyq; delta halved on ratio < 0.1, raised to 2 pnorm on ratio >= 0.5 or two successes", status="ACCEPTED",
    mechanism="the Jacobian is formed by forward differences (fdjac1, banded if ml/mu say so) and QR-factored once per outer iteration; inside, each accepted step updates the factored Jacobian by the Broyden secant correction (a rank-one update of R carried through Q by Givens rotations, r1updt/r1mpyq) rather than re-evaluating; the outer loop re-evaluates only when two consecutive steps failed (ncfail = 2); progress monitors count iterations with actual reduction below 0.001 (nslow1, ten -> info 5) and Jacobian evaluations with reduction below 0.1 (nslow2, five -> info 4); delta is halved on ratio < 0.1 and raised on ratio >= 0.5 or after two successes",
    input="function values; the previous factorisation", output="an updated R and Q", state="R, Q, the counters", update="per iteration", assumptions=["secant information from accepted steps is good enough to avoid n function evaluations per iteration; failure to reduce the residual twice means the secant Jacobian has drifted"],
    fitness_value_in_ancestor="n-fold fewer function evaluations per iteration than a finite-difference Newton", failure_landscape="by reading: the monitors terminate with 'not making good progress' rather than diverging; the secant update can make R singular (r1updt reports sing; the dogleg's diagonal repair copes)",
    human_prior="Broyden 1965; Powell 1970's re-evaluation strategy", evidence_ref=HB + ":208-440", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="hybrd's outer/inner loops (hybrj is the analytic-Jacobian twin)",
    coverage={"input_topology": "VECTOR", "output_topology": "MATRIX", "state_amount": "CONSTANT", "memory": "SUMMARY_STATISTIC", "feedback": "CLOSED_LOOP", "stochasticity": "DETERMINISTIC", "update_topology": "RECURSIVE", "failure_mode": "STALLS"})

c.reject("qrfac (Householder QR with column pivoting), qrsolv, r1updt, r1mpyq, qform, enorm (the overflow-safe norm), dpmpar (machine constants)", reason="OTHER", evidence="NOT READ; the linear-algebra substrate; enorm's three-accumulator scaling is a small mechanism of its own, unread")
c.reject("lmdif (finite-difference LM), lmstr (row-wise storage), the *1 driver wrappers, chkder (Jacobian check), fdjac1/fdjac2, the ex/ drivers and file01-23 outputs", reason="OTHER", evidence="NOT READ; residue", note="ex/ holds the test problems and reference outputs: an oracle for a Stage C run")
c.reject("'Levenberg-Marquardt' as one organ", reason="NAME_HAS_NO_EXECUTABLE_BOUNDARY", evidence="the damping search (lmpar) and the acceptance/radius logic (lmder) are separable; the latter is shared with the hybrid method")

c.edge(lmpar, tr, "feeds"); c.edge(tr, lmpar, "feeds", note="delta and par back"); c.edge(dog, broy, "feeds"); c.edge(broy, dog, "feeds", note="the secant R")

c.pressure("a_nonlinear_residual_must_be_minimised_from_a_poor_start_with_a_bounded_number_of_expensive_function_evaluations_and_no_line_search_oracle",
    condition="an organism minimises ||F(x)|| (or solves F(x) = 0) where each F is expensive; the linear model is good only locally; the start may be far from the solution; the score is evaluations to a tolerance and robustness to bad starts", resource_or_constraint="function evaluations; a fixed QR per Jacobian",
    failure_condition="divergence from a poor start (pure Gauss-Newton), or evaluations wasted on a Jacobian that has not changed", world_punishes="full steps regardless of model quality; re-evaluating the Jacobian every iteration", world_rewards="a trust radius adapted by actual/predicted reduction; secant updates with a failure-triggered refresh",
    observable_consequence="function evaluations and success rate over the More-Garbow-Hillstrom problem set (the ex/ drivers) for LM vs Gauss-Newton, and hybrid vs finite-difference Newton, from the standard and 10x starts", vacuity_condition="a linear residual", trivial_shortcuts="a start within the Newton basin",
    cheat_control="an organism given the exact Hessian must reach the tolerance in the fewest iterations; Gauss-Newton without a region must diverge on some 10x starts; the hybrid with re-evaluation every step must use ~n times more evaluations at the same success: the world must show all three",
    cost_class="CPU-scale", source_evidence="lmpar.f; lmder.f 330-440; hybrd.f 208-440; ex/ file01-23", purpose="PURPOSE: nonlinear least squares and equations (More, Garbow, Hillstrom 1980)")

c.ancestry("algorithm_from", "More 1978 (LM implementation); Hebden 1973 (the par iteration); Powell 1970 (hybrid dogleg); Broyden 1965", note="from the source comments and the record")
c.residue("PARTIALLY_EXPLAINED", ["the QR/rotation substrate unread", "lmdif/lmstr/chkder/fdjac unread", "nothing ran; ex/ is the oracle"], note="the four mechanisms that make the two methods robust are located and separated from the linear algebra")
c.save(state="DEEP")
