"""Cut: ncompress-5.0-lzw-1985 (ncompress, the maintained continuation of Unix compress(1); ancestry-aware, Stage A DEEP; SOURCE_READ on
M3; position 90 of the 2026-09-17 NOT_CUT order). Read: compress.c the compress loop 1235-1430 (the LZW dictionary build, variable-code-
width growth, and the ratio-triggered table reset), the constants (CLEAR 256, FIRST, CHECK_GAP 10000, maxbits). NOT read: the decompress
loop, the hash-table probe details, the CLI. Nothing ran (C; no compiler on M3). The atlas's compress-4.2.4-lzw and gzip/zlib cuts are the
compression family; the record grades this LATER_SAME_LINEAGE_RELEASE of the 1985 code.
"""
from nyx.atlas.author import Cut

C_ = "vault:ncompress-5.0-lzw-1985/upstream/tree/ncompress-5.0/compress.c"
c = Cut("ncompress-5.0-lzw-1985", mode="ANCESTRY_AWARE", inspected=["compress.c 1235-1430 + constants"], evidence=[("SOURCE_READ", C_ + ":1235-1340")],
        note="adaptive LZW as Unix compress did it: a dictionary maps a (prefix code, next byte) pair to a new code, built greedily as the input is read; codes start at 9 bits and widen up to maxbits as the dictionary fills; when the dictionary is full the coder does not simply stop adding entries but watches the compression ratio, and when the ratio stops improving it emits a CLEAR code and rebuilds the dictionary from scratch, so a stream whose statistics drift is re-learned rather than coded against a stale table")

lzw = c.organ("lzw_dictionary_built_greedily_from_prefix_plus_byte_with_codes_widening_from_nine_bits_to_maxbits_as_entries_fill", human_name="the compress loop (1258-1430): fcode.e = (ent, c); free_ent from FIRST; extcode = MAXCODE(n_bits); when free_ent >= extcode and n_bits < maxbits widen n_bits and recompute extcode with the bit-boundary alignment of the output", status="ACCEPTED",
    mechanism="the current match is a code 'ent'; the next byte c forms the pair (ent, c); if that pair is in the hash table the match extends (ent becomes the pair's code), else the code for ent is emitted, the pair is added as the next free entry, and ent restarts at c; output codes are packed at the current bit width, which starts at 9 (INIT_BITS) and increases by one whenever the next free entry would exceed the current width's range, up to maxbits; a bit-boundary realignment keeps the packed stream decodable across width changes",
    input="a byte stream", output="a stream of variable-width codes", state="the hash table, free_ent, n_bits", update="per byte", assumptions=["a greedy longest-prefix match against a growing dictionary captures repetition; widening the code only as needed keeps early output small"],
    fitness_value_in_ancestor="the Unix standard compressor before gzip; single-pass, adaptive, no explicit model", failure_landscape="by reading: once the dictionary is full and not reset it codes new data against a stale table (the failure the ratio reset addresses); the LZW patent is why gzip replaced it, not a technical failure", human_prior="Ziv & Lempel 1978 (LZ78); Welch 1984 (LZW); Thomas et al. 1985 (compress)", evidence_ref=C_ + ":1258-1300", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="the dictionary-build and code-width logic",
    coverage={"input_topology": "SEQUENCE", "output_topology": "SEQUENCE", "state_amount": "LINEAR_IN_INPUT", "state_persistence": "PER_EPISODE", "memory": "ARCHIVE", "stochasticity": "DETERMINISTIC", "update_topology": "SWEEP"})

reset = c.organ("block_mode_ratio_monitor_that_clears_and_rebuilds_the_dictionary_when_the_compression_ratio_stops_improving_after_the_table_fills", human_name="the checkpoint block (1299-1340): CHECK_GAP 10000; once stcode is off (table full) and bytes_in crosses checkpoint, compute rat = bytes_in / (bytes_out >> 8); if rat >= ratio keep, else emit CLEAR (256), reset free_ent to FIRST and ratio to 0; BLOCK_MODE bit in the header", status="ACCEPTED",
    mechanism="when the dictionary is full the coder stops adding entries (stcode off) and every CHECK_GAP input bytes computes the running compression ratio using integer arithmetic (a deliberate design note: no floating point); if the ratio has not improved since the last checkpoint the dictionary is discarded via a CLEAR code and rebuilt from the single-byte entries, so the coder adapts to a change in the input's statistics; the header's BLOCK_MODE bit tells the decoder that CLEAR codes may appear",
    input="the running byte counts", output="a CLEAR code and a dictionary reset when warranted", state="ratio, checkpoint, free_ent", update="every CHECK_GAP bytes once full", assumptions=["a falling ratio means the current dictionary no longer fits the data, so rebuilding beats coding against it; integer ratio arithmetic is exact and fast"],
    fitness_value_in_ancestor="a single-pass adaptive coder that recovers when the input changes character partway through", failure_landscape="by reading: the CHECK_GAP and the ratio comparison are heuristics; a slowly drifting stream may reset too late or too often", human_prior="the compress(1) block-compress extension (the record credits the 1985 authors)", evidence_ref=C_ + ":1299-1340", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="the checkpoint / CLEAR block",
    coverage={"input_topology": "SEQUENCE", "output_topology": "EVENT", "state_amount": "CONSTANT", "feedback": "CLOSED_LOOP", "stochasticity": "DETERMINISTIC", "update_topology": "EVENT_DRIVEN", "recovery": "SELF_RESETS"})

c.reject("the decompress loop (the inverse table walk with the KwKwK special case), the hash-table probe (the double hashing), the CLI and file handling, the magic-number header", reason="OTHER", evidence="NOT READ; residue", note="the decode-side KwKwK case is a small mechanism of its own")
c.reject("'LZW compressor' as one organ", reason="NAME_HAS_NO_EXECUTABLE_BOUNDARY", evidence="the dictionary build and the ratio-reset are separable; compress-4.2.4-lzw in this atlas is the same algorithm at another version")

c.edge(lzw, reset, "feeds"); c.edge(reset, lzw, "forgets", note="CLEAR rebuilds the dictionary")

c.pressure("a_stream_must_be_compressed_adaptively_in_one_pass_with_a_bounded_dictionary_when_the_input_statistics_may_change_partway_through_and_no_second_pass_or_floating_point_is_available",
    condition="an organism compresses a stream it sees once, with a fixed maximum dictionary size; the input's character may change (text then binary); the score is compressed size and single-pass, integer-only operation", resource_or_constraint="a dictionary of 2^maxbits entries; integer arithmetic",
    failure_condition="coding a changed input against a stale full dictionary (ratio collapse), or needing a second pass", world_punishes="freezing the dictionary when full; a static model", world_rewards="widening codes as the table fills and clearing it when the ratio stops improving",
    observable_consequence="compressed size on a concatenation of two differently-distributed halves for the freeze-when-full variant vs the ratio-reset variant; ratio over position", vacuity_condition="a stationary stream that fits the dictionary", trivial_shortcuts="a two-pass modeller (which the single-pass requirement forbids)",
    cheat_control="a two-pass optimal coder bounds the size; the freeze-when-full coder must show the ratio collapse on the second half; the ratio-reset coder must recover: the world must show all three", cost_class="CPU-scale",
    source_evidence="compress.c the LZW loop and the checkpoint block", purpose="PURPOSE: adaptive single-pass compression (Welch 1984; compress(1) 1985; ncompress continuation)")

c.ancestry("historical_version_of", "compress(1) (Thomas, McKie, Davies, Turkowski, Woods, Orost 1985) after Welch 1984; ncompress is the maintained continuation; compress-4.2.4-lzw in this atlas is a sibling release", note="from the record and the source")
c.residue("PARTIALLY_EXPLAINED", ["the decoder and the hash probe unread", "nothing ran"], note="the two mechanisms of the encoder are located; a sibling of compress-4.2.4-lzw for a same-algorithm comparison")
c.save(state="DEEP")
