"""Cut: openssl-1.0.1f-heartbleed (OpenSSL 1.0.1f, preserved for the heartbeat defect CVE-2014-0160; Stage A COARSE, narrow to the named
mechanism per the 2026-09-18 directive; SOURCE_READ on M3; position 83 of the 2026-09-17 NOT_CUT order). Read: ssl/t1_lib.c
tls1_process_heartbeat 2554-2611 and ssl/d1_both.c dtls1_process_heartbeat 1455-1475 (the same responder for DTLS). NOT read: anything
else of the 2,254 files. Nothing ran (C; no compiler on M3). This is a fossil of a defect and its repair, not a technique: the cut names
the mechanism (an echo responder), the missing check, and the fix that 1.0.1g added, so the atlas records what integrity property was
absent, not how to abuse its absence.
"""
from nyx.atlas.author import Cut

T = "vault:openssl-1.0.1f-heartbleed/upstream/tree/openssl-1.0.1f/ssl/t1_lib.c"; D = "vault:openssl-1.0.1f-heartbleed/upstream/tree/openssl-1.0.1f/ssl/d1_both.c"
c = Cut("openssl-1.0.1f-heartbleed", mode="ANCESTRY_AWARE", inspected=["ssl/t1_lib.c 2554-2611", "ssl/d1_both.c 1455-1475"], evidence=[("SOURCE_READ", T + ":2554-2611"), ("SOURCE_READ", D + ":1455-1475")],
        note="the TLS/DTLS heartbeat responder (RFC 6520): it takes a request carrying a declared payload length, allocates a response sized from that declared length, and copies that many bytes from the request into the response. In 1.0.1 through 1.0.1f the declared length is used without being compared to the length of the record actually received, so a response can be larger than the request was; 1.0.1g adds two bounds checks (a zero-length guard and a check that the declared payload plus overhead does not exceed the received record) that make the responder ignore any request whose declared length is not backed by received bytes. The cut records the responder as one organ and the missing-check-then-added-check as the fossil's point")

hb = c.organ("heartbeat_responder_that_sizes_and_fills_a_reply_from_a_caller_declared_length_field_whose_validation_against_the_received_record_length_was_absent_and_was_added_in_the_successor_release", human_name="tls1_process_heartbeat (t1_lib.c 2554-2611) / dtls1_process_heartbeat (d1_both.c 1455-...): read hbtype and a 16-bit payload length; on a REQUEST allocate 1 + 2 + payload + 16 and copy payload bytes then random padding, write it back; the 1.0.1g fix adds 'if (1 + 2 + 16 > s->s3->rrec.length) return 0' and 'if (1 + 2 + payload + 16 > s->s3->rrec.length) return 0' before the allocation", status="ACCEPTED",
    mechanism="the responder parses a one-byte type and a two-byte declared payload length from the received record, and for a request builds a response of type, echoed length, echoed payload and 16 bytes of random padding; the read of the payload copies as many bytes as the declared length says; the defect is that nothing tied the declared length to the number of bytes actually received before 1.0.1g, so the response could be assembled from more of the process buffer than the request supplied; the fix is the two comparisons that reject a request whose declared length exceeds the received record",
    input="a received heartbeat record", output="a heartbeat response, or (after the fix) nothing when the declared length is unbacked", state="none beyond the connection buffer", update="per heartbeat", assumptions=["BEFORE the fix: that a peer's declared length is backed by the bytes it sent (an untrusted-input assumption that did not hold); AFTER: the declared length must be validated against the received record"],
    fitness_value_in_ancestor="a keep-alive and path-MTU probe for (D)TLS without renegotiation (RFC 6520)", failure_landscape="the missing bounds check is the failure: a length field consumed as a copy count without validation is the classic input-length-trust defect; the fix and CVE-2014-0160 are the recorded outcome; the DTLS copy carried the same defect, so one fossil holds two instances of the same missing check",
    human_prior="RFC 6520 (Seggelmann et al.); the defect and fix are the CVE-2014-0160 record and the 1.0.1g changelog", evidence_ref=T + ":2554-2611; " + D + ":1455-1475", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="the two heartbeat handlers",
    coverage={"input_topology": "SEQUENCE", "output_topology": "SEQUENCE", "state_amount": "NONE", "stochasticity": "SEEDED_RANDOM", "update_topology": "EVENT_DRIVEN", "failure_mode": "CORRUPTS"})

c.reject("the entire rest of OpenSSL (the TLS state machine, the record layer, the crypto library, the BIO abstraction, the 2,250 other files)", reason="OTHER", evidence="NOT READ; the specimen is preserved for the heartbeat defect only (record)")
c.reject("'TLS library' as one organ", reason="NAME_HAS_NO_EXECUTABLE_BOUNDARY", evidence="the fossil's point is one responder and one missing check, not the library")

c.pressure("a_network_service_that_echoes_a_caller_supplied_length_must_validate_that_length_against_the_bytes_actually_received_before_using_it_to_size_or_fill_a_reply",
    condition="an organism parses an untrusted message containing a length field and produces a reply built from that many bytes of an input buffer; the message's declared length may not match the bytes the peer actually sent; the score is whether the reply ever contains bytes the peer did not supply", resource_or_constraint="one comparison against the received record length",
    failure_condition="a reply assembled from more of the buffer than the request delivered (an over-read), which is the defect", world_punishes="trusting the declared length; sizing a copy from it without a check", world_rewards="comparing the declared length to the received length and rejecting the mismatch (the 1.0.1g fix)",
    observable_consequence="on a differential test between 1.0.1f and 1.0.1g with requests whose declared length exceeds the sent bytes: 1.0.1f produces an over-long response, 1.0.1g returns nothing; this is a present-vs-absent-check comparison, run in a sandboxed test harness, not an extraction against any live service", vacuity_condition="requests whose declared length always equals the bytes sent", trivial_shortcuts="rejecting all heartbeats (which the keep-alive requirement forbids)",
    cheat_control="the fixed release (1.0.1g) is the reference: on the same crafted-length test inputs it must never emit a response longer than the request, where 1.0.1f does; the fossil is the before, the fix is the oracle", cost_class="CPU-scale",
    source_evidence="the two handlers; the 1.0.1g bounds-check diff; RFC 6520", purpose="PURPOSE: (D)TLS heartbeat / keep-alive (RFC 6520), preserved as the CVE-2014-0160 case study")

c.ancestry("historical_version_of", "OpenSSL 1.0.1 series; the defect entered at the heartbeat commit and was repaired in 1.0.1g", note="from the record and the changelog")
c.residue("PARTIALLY_EXPLAINED", ["only the two handlers read; the rest of OpenSSL is out of scope for this fossil", "nothing ran; a present-vs-absent-check differential is an M2 build world (the fix is the oracle)"], note="a defect fossil: the mechanism is an echo responder and the point is the input-length check that was missing and then added")
c.save(state="COARSE")
