"""Cut: picosat-965 (Biere's PicoSAT; ancestry-aware, Stage A COARSE; SOURCE_READ on M3; position 79 of the 2026-09-17 NOT_CUT order).
Read: picosat.c the function inventory (1081-4880 by name), assign_phase 1579-1600 (phase saving with a flip statistic), inc_score
3449-3475 (variable scoring with a heap), need_to_reduce 4810-4813, the restart schedules 4814-4880 (Luby by default, geometric under
NLUBY), decide 5874-5895 (assumptions, then a random-or-scored decision). NOT read: analyze (3518-3767), bcp / propl (4010-4380: the
propagation with head/tail watch lists and binary-clause implication lists), the clause allocator, the proof trace, the ADO
(all-different) extension, simplification. Nothing ran (C; no compiler on M3). Cut as an inventory beside the atlas's minisat cut.
"""
from nyx.atlas.author import Cut

P = "vault:picosat-965/upstream/tree/picosat-965/picosat.c"
c = Cut("picosat-965", mode="ANCESTRY_AWARE", inspected=["picosat.c inventory 1081-4880; 1579-1600; 3449-3475; 4810-4880; 5874-5895"], evidence=[("SOURCE_READ", P + ":1579-1600"), ("SOURCE_READ", P + ":3449-3475"), ("SOURCE_READ", P + ":4810-4880"), ("SOURCE_READ", P + ":5874-5895")],
        note="a CDCL solver of the same family as MiniSat (cut DEEP in this atlas) read for its differences: phase saving is built in with a running statistic of how often the saved phase was flipped; propagation uses head/tail watches with separate implication lists for binary clauses (by inventory: setimpl, connect_head_tail, propl); the variable score is a float in a heap with rescoring on overflow; restarts follow the Luby sequence scaled by 100 conflicts (or a geometric schedule under a compile flag) and the learnt-clause limit grows by its own schedule; the solver can emit a proof trace and handles assumptions and all-different constraints")

phase = c.organ("phase_saving_that_assigns_a_decision_variable_its_last_value_and_tracks_an_exponentially_decayed_count_of_saved_phase_flips", human_name="assign_phase (1579-1600): new_phase from the literal's sign; if the variable was assigned before, sdflips -= sdflips / FFLIPPED and, when the phase differs, the flip statistic is bumped; v->phase saved; decide uses the saved phase (sdecide, not read)", status="ACCEPTED",
    mechanism="whenever a variable is assigned, its polarity is remembered; a later decision on that variable reuses the remembered polarity, so after a restart or a backjump the solver re-enters the region of the search space it was in (progress saving); a decayed counter of how often the saved phase is contradicted is kept as a health statistic",
    input="assignments", output="a saved polarity per variable", state="v->phase, sdflips", update="per assignment", assumptions=["partial assignments found before a restart are worth keeping (Pipatsrisawat & Darwiche 2007); the flip statistic is cheap diagnostics"],
    fitness_value_in_ancestor="restarts stop throwing away work; one of the two changes (with Luby restarts) that made frequent restarting pay", failure_landscape="UNKNOWN by run", human_prior="Pipatsrisawat & Darwiche 2007 (phase saving); MiniSat 2.2's polarity vector is the simpler form", evidence_ref=P + ":1579-1600", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="assign_phase",
    coverage={"input_topology": "EVENT", "output_topology": "VECTOR", "state_amount": "LINEAR_IN_INPUT", "memory": "LAST_VALUE", "stochasticity": "DETERMINISTIC"})

rst = c.organ("luby_restarts_scaled_by_a_hundred_conflicts_with_a_geometric_alternative_and_a_learnt_clause_limit_on_its_own_growth_schedule", human_name="luby (4830-4843), inc_lrestart (4856-4875): delta = 100 * luby(++lubycnt); lrestart = conflicts + delta; NLUBY: inc_drestart / inc_ddrestart geometric by FRESTART percent up to MAXRESTART; need_to_reduce (4810): nlclauses >= reduce_limit_on_lclauses; inc_lreduce (4550)", status="ACCEPTED",
    mechanism="the next restart is scheduled at the current conflict count plus 100 times the next Luby number (1, 1, 2, 1, 1, 2, 4, ...); a compile-time alternative multiplies an interval by a percentage up to a cap (the older geometric scheme); independently, the learnt-clause database is reduced when its size crosses a limit that grows on its own schedule; reports mark the largest Luby deltas",
    input="conflict counts", output="restart and reduce events", state="lubycnt, lrestart, the reduce limit", update="per conflict", assumptions=["Luby's universal schedule bounds the loss from any fixed cutoff; decoupling the reduce schedule from restarts lets each be tuned"],
    fitness_value_in_ancestor="robust performance without per-instance tuning", failure_landscape="by reading: the 100-conflict unit is a constant; Glucose-style dynamic restarts (on LBD) came later", human_prior="Luby, Sinclair & Zuckerman 1993; Huang 2007", evidence_ref=P + ":4810-4880", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="the restart and reduce schedule functions",
    coverage={"input_topology": "SCALAR", "output_topology": "EVENT", "state_amount": "CONSTANT", "stochasticity": "DETERMINISTIC", "update_topology": "EVENT_DRIVEN", "recovery": "SELF_RESETS"})

score = c.organ("variable_scores_as_floats_in_a_heap_bumped_by_a_growing_increment_and_rescaled_on_overflow_with_decisions_taken_from_assumptions_first_then_by_score_or_at_random", human_name="inc_score (3449-3475): r->score = addflt(score, vinc); hup; vrescore (3436), crescore (4436) for clauses; decide (5874-5895): adecide (assumptions), rdecide (random), sdecide (scored)", status="CANDIDATE",
    mechanism="each variable has a rank record with a float score; a bump adds the current increment and sifts the record up the heap; the increment grows per conflict and everything is rescaled when it would overflow (the MiniSat trick in float form); clause activities likewise; a decision first satisfies pending assumptions, else with some probability picks a random variable, else the heap maximum; the saved phase gives the sign",
    input="conflict participation", output="the next decision", state="scores, the heap, vinc", update="per conflict / per decision", assumptions=["VSIDS; assumptions as a decision prefix make incremental solving (solve under assumptions) natural"],
    fitness_value_in_ancestor="incremental SAT for bounded model checking (the author's use)", failure_landscape="UNKNOWN by run", human_prior="Chaff's VSIDS; MiniSat's assumptions interface", evidence_ref=P + ":3449-3475, 5874-5895 (sdecide / rdecide not read)", confidence="MEDIUM", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="the scoring and decide functions; CANDIDATE because sdecide was not read",
    coverage={"input_topology": "EVENT", "output_topology": "DECISION", "state_amount": "LINEAR_IN_INPUT", "memory": "SUMMARY_STATISTIC", "stochasticity": "SEEDED_RANDOM", "update_topology": "PRIORITY"})

c.reject("propagation (bcp, propl, the head/tail watch scheme and binary implication lists: setimpl / connect_head_tail), conflict analysis (analyze, fanalyze), clause minimisation, the clause allocator and garbage collection, the proof trace (RUP / extended resolution output), the ADO extension, simplification, failed-literal probing, the API and the app", reason="OTHER", evidence="NOT READ (~7,500 lines); residue", note="the head/tail watch scheme with binary lists is the propagation variant that distinguishes this lineage from MiniSat's two-watched-literal + blocker; it is the DEEP item to read next")
c.reject("'SAT solver' as one organ", reason="NAME_HAS_NO_EXECUTABLE_BOUNDARY", evidence="the atlas's minisat cut names the five separable policies; this cut records where PicoSAT's differ")

c.edge(phase, score, "feeds", note="the sign of a decision"); c.edge(rst, score, "triggers", note="re-decide after restart")

c.pressure("a_cdcl_solver_used_incrementally_under_assumptions_must_restart_often_without_losing_its_partial_assignments_and_must_emit_a_checkable_proof_of_unsatisfiability",
    condition="an organism answers a sequence of related SAT queries (bounded model checking) each under a set of assumed literals; frequent restarts are needed for heavy tails; an unsatisfiable answer must come with a proof a third party can check; the score is total time over the sequence and proof validity", resource_or_constraint="time; proof size",
    failure_condition="restarts that discard progress (time), or an UNSAT answer without a checkable proof", world_punishes="restarting with fresh polarities; proofs reconstructed after the fact", world_rewards="phase saving, Luby restarts, a trace recorded during search",
    observable_consequence="time over a BMC unrolling sequence with phase saving on and off; proof check success rate on the UNSAT instances", vacuity_condition="one query, satisfiable", trivial_shortcuts="re-solving from scratch per query (correct, slow)",
    cheat_control="an organism given the previous query's model as the initial phase must match phase saving's time; phase saving off must show the time penalty on the sequence; an UNSAT answer with tracing off must fail the proof check: the world must show all three",
    cost_class="CPU-scale", source_evidence="picosat.c assign_phase, the restart functions, decide; the trace functions by name", purpose="PURPOSE: incremental CDCL with proofs (Biere 2007-)")

c.ancestry("shares_ancestor_with", "minisat-2.2.0 (in this atlas): both descend from Chaff / GRASP; PicoSAT's own lineage continues in PrecoSAT and Lingeling", note="from the record and the source")
c.residue("LARGE_RESIDUE", ["propagation, analysis, the proof trace and simplification unread", "the scoring organ is CANDIDATE", "nothing ran"], note="an inventory cut that records the three places this solver differs from the atlas's MiniSat cut; the propagation scheme is the next read")
c.save(state="COARSE")
