"""Cut: picorv32 (Wolf's PicoRV32 RV32IMC core; ancestry-aware, Stage A COARSE; SOURCE_READ on M3; position 62 of the 2026-09-17 NOT_CUT
order). Read: picorv32.v parameters 60-120, the memory interface signals and mem_state 356-640 (structure), the decoder 646-1140
(structure), the CPU state machine localparams 1172-1200 and the fetch state 1491-1578, the launch/irq lines 1400-1450. NOT read: the
exec/shift/ldmem/stmem states in detail, the PCPI mul/div modules, the AXI and Wishbone wrappers, the testbenches, picosoc/, the
firmware and dhrystone. Nothing ran (no Verilog simulator on M3).
"""
from nyx.atlas.author import Cut

V = "vault:picorv32/upstream/tree/picorv32.v"
c = Cut("picorv32", mode="ANCESTRY_AWARE", inspected=["picorv32.v 60-120, 356-640, 646-1140 (structure), 1172-1200, 1400-1578"], evidence=[("SOURCE_READ", V + ":1172-1200"), ("SOURCE_READ", V + ":1491-1578"), ("SOURCE_READ", V + ":356-640"), ("SOURCE_READ", V + ":60-120")],
        note="a deliberately small, slow core: instructions take several cycles through a one-hot state machine (trap, fetch, ld_rs1, ld_rs2, exec, shift, stmem, ldmem) with one memory port shared by fetch and data; the decoder latches instruction fields when fetch data arrives; optional features (multiply/divide via a co-processor interface, compressed instructions, a barrel shifter, a custom interrupt scheme with shadow registers and a timer) are Verilog parameters, so area and speed are chosen per instance")

fsm = c.organ("multi_cycle_execution_through_a_one_hot_state_machine_with_a_single_memory_port_shared_by_instruction_fetch_and_data_access", human_name="localparam cpu_state_* (1172-1180); the case over cpu_state (1487-); mem_do_rinst / mem_do_rdata / mem_do_wdata and mem_state (356-640); latched_branch / latched_store / latched_stalu resolved in the fetch state (1491-1535)", status="ACCEPTED",
    mechanism="each instruction passes through fetch (which also commits the previous instruction's register write and branch, then requests the next instruction word), operand load states (one or two, reading the register file one port at a time), exec (ALU, or the shift state that shifts one or two bits per cycle unless a barrel shifter is enabled), and a memory state for loads or stores; the memory interface is a single valid/ready port whose request kind is set by three flags, and a prefetch of the next word can overlap the tail of the current instruction",
    input="instruction words and data from one memory port", output="register-file writes, memory requests, a program counter", state="cpu_state, the latched decode, the register file", update="per clock", assumptions=["cycles are cheap and gates are not (the design goal is minimal area and high clock rate); a single port suffices because fetch and data never overlap in this pipeline"],
    fitness_value_in_ancestor="a few hundred LUTs on an FPGA at hundreds of MHz; the reference small RISC-V", failure_landscape="by reading: 3-4 cycles per simple instruction and up to 32 for a shift without the barrel shifter; a slow memory stalls everything", human_prior="microcoded / multi-cycle CPU organisation (Patterson & Hennessy's multicycle datapath)", evidence_ref=V + ":1172-1200, 1487-1578, 356-640", confidence="HIGH", portability="YES", compatibility="UNKNOWN", utility="UNKNOWN", source_boundary="the state machine and the memory-interface flags",
    coverage={"input_topology": "STREAM", "output_topology": "STREAM", "state_amount": "CONSTANT", "state_persistence": "PERSISTENT", "stochasticity": "DETERMINISTIC", "update_topology": "SINGLE_STEP", "resource_dependence": "TIME"})

dec = c.organ("decoder_that_latches_instruction_class_flags_when_the_fetched_word_arrives_with_compressed_instructions_expanded_in_the_same_step", human_name="instr_* and is_* registers (646-700); the decode block on mem_do_rinst && mem_done (866-1140); COMPRESSED_ISA expansion (930-1000); instr_trap for unrecognised words (679)", status="ACCEPTED",
    mechanism="when the instruction word lands, one register per instruction (lui, jal, beq, ...) and per useful class (is_lui_auipc_jal, ...) is set from the opcode and function fields; 16-bit compressed forms are recognised and expanded into the same flags; the immediate is decoded into one register by class; a word matching nothing raises a trap flag; the flags, not the word, drive later states, so decoding costs no cycle of its own",
    input="mem_rdata", output="instruction flags and the immediate", state="the flag registers", update="on fetch completion", assumptions=["one register per instruction is cheap and makes the later states' case statements one-hot"],
    fitness_value_in_ancestor="the execution states read flags, never bit fields; compressed support is confined to the decoder", failure_landscape="UNKNOWN by run", evidence_ref=V + ":646-1140", confidence="MEDIUM", portability="YES", compatibility="UNKNOWN", utility="UNKNOWN", source_boundary="the decoder always-block; MEDIUM because the compressed expansion was skimmed",
    coverage={"input_topology": "VECTOR", "output_topology": "VECTOR", "state_amount": "CONSTANT", "stochasticity": "DETERMINISTIC", "update_topology": "EVENT_DRIVEN"})

opts = c.organ("area_speed_trade_offs_as_verilog_parameters_including_a_co_processor_interface_for_multiply_and_divide_and_a_custom_interrupt_scheme", human_name="parameters ENABLE_COUNTERS, TWO_STAGE_SHIFT, BARREL_SHIFTER, ENABLE_MUL / FAST_MUL / DIV, ENABLE_IRQ / IRQ_QREGS / IRQ_TIMER, COMPRESSED_ISA, ENABLE_PCPI (60-120); pcpi_* port and the picorv32_pcpi_mul / fast_mul / div instances (257-300); irq_pending / irq_mask / timer and the irq_state sequence in fetch (1400-1450, 1538-1560)", status="CANDIDATE",
    mechanism="multiply and divide are not in the core: an optional co-processor port (valid, insn, rs1, rs2 out; wr, rd, wait, ready in) lets an external unit claim an instruction, and the shipped mul/div units attach to it; the barrel-shifter and two-stage-shift parameters trade a cycle-per-bit shifter for area; the interrupt scheme is non-standard: a mask, a pending vector, an optional timer instruction, and four extra 'q' registers reached by custom instructions (getq/setq/retirq/maskirq/waitirq) so that an interrupt handler saves state without touching the ISA's registers",
    input="parameters at elaboration; the PCPI port at run time", output="a core variant", state="irq_mask, irq_pending, timer", update="at elaboration / per clock", assumptions=["users know their area budget; a co-processor port is more reusable than a fixed multiplier; RISC-V's standard interrupt model is too large for this core's goal"],
    fitness_value_in_ancestor="one source file yields cores from ~750 to ~2000 LUTs", failure_landscape="by reading: the custom interrupt instructions make binaries non-portable to other RISC-V cores (documented in the README)", evidence_ref=V + ":60-120, 257-300, 1400-1450, 1538-1560", confidence="MEDIUM", portability="YES", compatibility="UNKNOWN", utility="UNKNOWN", source_boundary="the parameter list, the PCPI port and the irq blocks; CANDIDATE because the PCPI units were not read",
    coverage={"input_topology": "MIXED", "output_topology": "MIXED", "state_amount": "CONSTANT", "stochasticity": "DETERMINISTIC", "representation_sensitivity": "SENSITIVE"})

c.reject("the exec / shift / ldmem / stmem states in detail, the ALU, the register file implementation, the PCPI mul/div modules, the AXI4-lite and Wishbone wrappers, the trace port, the formal assertions, picosoc/, testbenches, firmware, dhrystone", reason="OTHER", evidence="NOT READ; residue")
c.reject("'RISC-V core' as one organ", reason="NAME_HAS_NO_EXECUTABLE_BOUNDARY", evidence="the state machine, the decoder and the option set are separable; the same ISA is implemented by pipelines with none of them (biriscv in this atlas holds a branch predictor for a pipelined one)")

c.edge(dec, fsm, "feeds"); c.edge(fsm, dec, "triggers", note="fetch completion"); c.edge(opts, fsm, "gates", note="which states exist")

c.pressure("an_instruction_set_must_be_executed_correctly_in_the_smallest_area_at_the_highest_clock_rate_when_cycles_per_instruction_are_negotiable_and_features_must_be_removable_per_instance",
    condition="an organism implements a fixed ISA on an FPGA; the score is area (LUTs), maximum clock and correctness on the ISA tests; instructions per cycle is not scored; instances differ in which optional features they need", resource_or_constraint="LUTs; one memory port",
    failure_condition="an ISA-test failure, or area above the budget for a feature set", world_punishes="pipelines with hazard logic; fixed multipliers; standard interrupt controllers", world_rewards="a multi-cycle state machine, a co-processor port, parameters",
    observable_consequence="LUT count and maximum clock vs feature set on one FPGA family; ISA test pass count per variant; cycles per Dhrystone", vacuity_condition="unlimited area", trivial_shortcuts="a soft core from the vendor (which fixes the feature set)",
    cheat_control="an organism given a pipelined reference must show more area at higher IPC; the multi-cycle core with the barrel shifter must show more area and fewer cycles on shift-heavy code than the two-stage shifter; both must pass the same tests: the world must show all three",
    cost_class="CPU-scale", source_evidence="picorv32.v parameters, state machine, PCPI port; the README's area figures", purpose="PURPOSE: a small RISC-V soft core (Wolf 2015-)")

c.ancestry("algorithm_from", "the RISC-V RV32I specification (Waterman et al.); multi-cycle datapath organisation", note="from the README and the record")
c.residue("LARGE_RESIDUE", ["execution states, ALU, PCPI units and the SoC unread", "the decoder and option organs are MEDIUM / CANDIDATE", "nothing ran (no simulator; the self-checking testbench is the oracle)"], note="the organisation is located; the datapath detail is not")
c.save(state="COARSE")
