"""Cut: pid-autotune-hirschmann (Hirschmann's Python relay autotuner; ancestry-aware, Stage A DEEP; SOURCE_READ on M3; position 77 of the
2026-09-17 NOT_CUT order). Read: autotune.py in full (240 lines). NOT read: pid.py (a PID), kettle.py and sim.py (the simulated brewing
kettle). Nothing ran; the body is pure Python: an M3-runnable packet candidate with the kettle simulation as its world (recorded in the
residue).
"""
from nyx.atlas.author import Cut

A = "vault:pid-autotune-hirschmann/upstream/tree/autotune.py"
c = Cut("pid-autotune-hirschmann", mode="ANCESTRY_AWARE", inspected=["autotune.py 1-240"], evidence=[("SOURCE_READ", A + ":1-240")],
        note="Astrom-Hagglund relay tuning in one class: the output is switched between initial +step and initial -step whenever the input crosses the setpoint by more than a noise band, which drives the loop into a limit cycle; peaks are detected as local extrema over a look-back window; when five peaks exist and the last four peak-to-peak amplitudes agree within 5 percent the cycle is accepted; the ultimate gain is 4 d / (pi a) from the relay step d and the cycle amplitude a, the ultimate period from the peak timestamps, and PID gains come from a table of divisor triples per named tuning rule")

relay = c.organ("relay_feedback_switching_the_output_by_a_fixed_step_around_an_initial_value_when_the_input_crosses_the_setpoint_outside_a_noise_band", human_name="run() (100-125): STATE_RELAY_STEP_UP / DOWN; switch on input > setpoint + noiseband or < setpoint - noiseband; output = initial +/- outputstep clamped to [out_min, out_max]; sampletime gate", status="ACCEPTED",
    mechanism="at each sample (no more often than the sample time) the state flips from stepping up to stepping down when the input exceeds the setpoint by the noise band, and back when it falls below by the noise band; the output is the initial output plus or minus the step accordingly, clamped to the limits; the hysteresis band prevents chattering on noise",
    input="input_val, the clock", output="the relay output", state="the state, last run time", update="per sample", assumptions=["a process under relay feedback oscillates at the frequency where its phase lag is 180 degrees (the describing-function argument); the oscillation amplitude and period identify the ultimate gain and period without an open-loop step test"],
    fitness_value_in_ancestor="the tuning experiment stays closed-loop and bounded (the process never runs away); the mechanism inside industrial 'autotune' buttons", failure_landscape="by reading: a process with no 180-degree crossing (first order without delay) never cycles; the noise band trades false switching against amplitude bias", human_prior="Astrom & Hagglund 1984", evidence_ref=A + ":100-125", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="the relay branch of run()",
    coverage={"input_topology": "SCALAR", "output_topology": "SCALAR", "state_amount": "CONSTANT", "feedback": "CLOSED_LOOP", "stochasticity": "DETERMINISTIC", "update_topology": "EVENT_DRIVEN"})

peaks = c.organ("peak_detection_as_local_extrema_over_a_look_back_window_with_acceptance_when_four_consecutive_peak_amplitudes_agree_within_five_percent_and_failure_after_twenty_peaks", human_name="run() (126-165): is_max / is_min over the deque of lookback/sampletime inputs; inflection when the extremum type flips; peaks and peak_timestamps deques of 5; induced_amplitude = mean of the last four peak-to-peak differences; amplitude_dev against half the max-min range; PEAK_AMPLITUDE_TOLERANCE 0.05; STATE_FAILED at 20 peaks", status="ACCEPTED",
    mechanism="the last look-back seconds of input are kept; a sample that is the maximum (or minimum) of the window marks a peak type; a change of type is an inflection and the sample is recorded as a peak with its time; once more than four peaks exist, the induced amplitude is the average of the four most recent peak-to-peak swings and is compared with half the total range; if they agree within 5 percent the limit cycle is declared steady (SUCCEEDED); if twenty peaks pass without agreement the tuning FAILS and the output is zeroed",
    input="the input history", output="a, the peak times, a verdict", state="the deques, peak_type, peak_count", update="per sample", assumptions=["a steady limit cycle has equal successive amplitudes; five peaks (two full periods) are enough to judge; a bounded number of peaks bounds the experiment"],
    fitness_value_in_ancestor="the cycle is measured only once it is steady, and the experiment cannot run forever", failure_landscape="by reading: the look-back window must exceed half a period or every sample is an extremum; the 5 percent tolerance and the 20-peak cap are constants", evidence_ref=A + ":126-165", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="the peak block of run()",
    coverage={"input_topology": "SEQUENCE", "output_topology": "DECISION", "state_amount": "CONSTANT", "memory": "WINDOW", "stochasticity": "DETERMINISTIC", "failure_mode": "STALLS"})

rules = c.organ("ultimate_gain_and_period_from_the_relay_step_the_cycle_amplitude_and_the_peak_timestamps_then_pid_gains_from_a_table_of_divisor_triples_per_named_rule", human_name="Ku = 4 outputstep / (induced_amplitude pi); Pu = mean of two peak-to-peak periods from timestamps[1..4]; get_pid_parameters: kp = Ku / d0, ki = kp / (Pu / d1), kd = kp * (Pu / d2); _tuning_rules: ziegler-nichols [34, 40, 160], tyreus-luyben, ciancone-marlin, pessen-integral, some-overshoot, no-overshoot, brewing [2.5, 6, 380]", status="ACCEPTED",
    mechanism="the describing function of a relay of amplitude d driving a cycle of amplitude a gives the ultimate gain 4 d / (pi a); the ultimate period is the average of two full periods measured between alternate peaks; a tuning rule is three divisors applied to Ku and Pu (Ziegler-Nichols' 0.6 Ku, Pu/2, Pu/8 appear here scaled by 100 as 34, 40, 160 for the author's percent-scaled controller), and six other rules are the same shape with other constants",
    input="outputstep, a, the timestamps, a rule name", output="Kp, Ki, Kd", state="none", update="at success", assumptions=["the process is well enough described by its ultimate point for a rule of thumb; different rules trade overshoot against speed"],
    fitness_value_in_ancestor="one experiment, seven tunings; the divisor table is the whole of the tuning knowledge", failure_landscape="by reading: the constants are scaled to the author's percent-output kettle controller and are not the textbook values as written", human_prior="Ziegler & Nichols 1942; Tyreus & Luyben 1992; the relay identification of Astrom & Hagglund 1984", evidence_ref=A + ":27-38, 78-90, 166-175", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="get_pid_parameters and the success branch",
    coverage={"input_topology": "VECTOR", "output_topology": "VECTOR", "state_amount": "NONE", "stochasticity": "DETERMINISTIC", "representation_sensitivity": "SENSITIVE"})

c.reject("pid.py (a PID; the atlas's arduino-pid cut holds a fuller one), kettle.py and sim.py (a first-order kettle with a heater: the WORLD of the script), the logging", reason="OTHER", evidence="NOT READ; residue", note="kettle.py is the natural M3 world for a packet: the kettle's true ultimate point is computable from its parameters (the cheat control)")
c.reject("'autotuner' as one organ", reason="NAME_HAS_NO_EXECUTABLE_BOUNDARY", evidence="the relay, the cycle detector and the rule table are separable (industrial tuners vary each)")

c.edge(relay, peaks, "feeds"); c.edge(peaks, rules, "feeds"); c.edge(peaks, relay, "gates", note="SUCCEEDED / FAILED stop the relay")

c.pressure("a_controller_must_be_tuned_for_an_unknown_process_by_a_bounded_closed_loop_experiment_that_never_lets_the_process_run_away_and_that_recognises_when_no_usable_cycle_appears",
    condition="an organism must find PID gains for a process it does not know, by manipulating the output and watching the input; the process must stay within bounds throughout; noise is present; some processes do not oscillate under relay; the score is the closed-loop performance of the resulting gains and the experiment's duration", resource_or_constraint="a relay step; a peak cap",
    failure_condition="an unbounded excursion during identification, gains from an unsteady cycle, or an experiment that never ends", world_punishes="open-loop step tests on integrating processes; accepting the first two peaks; no cap", world_rewards="relay feedback with hysteresis, steadiness acceptance, a peak cap, a rule table",
    observable_consequence="on the kettle simulation with noise: the identified Ku and Pu vs the analytic values, the experiment length, and the step response of the tuned loop for each rule; a non-oscillating process must reach FAILED", vacuity_condition="a known process", trivial_shortcuts="the process model (the cheat control)",
    cheat_control="an organism given the kettle's parameters must compute Ku and Pu exactly; the tuner with the steadiness check removed must return biased gains on the noisy kettle; the tuner on a first-order process without delay must FAIL within 20 peaks: the world must show all three",
    cost_class="CPU-scale", source_evidence="autotune.py; kettle.py as the world", purpose="PURPOSE: relay auto-tuning (Astrom & Hagglund 1984) as a hobby brewing controller (Hirschmann 2014)")

c.ancestry("reimplementation_of", "Astrom & Hagglund 1984 (relay tuning) and the Ziegler-Nichols family of rules; the author cites Brett Beauregard's Arduino autotune as the source of the structure (the atlas's arduino-pid is the same author's controller)", note="from the README and the record")
c.residue("EXPLAINED_BY_CURRENT_CUT", ["pid.py, kettle.py, sim.py unread (the world)", "nothing ran", "M3-RUNNABLE PACKET CANDIDATE: pure Python with a simulated world whose ultimate point is analytic"], note="240 lines, three mechanisms, all located; the fourth pure-Python candidate of this pass")
c.save(state="DEEP")
