"""Cut: py-vollib-lets-be-rational (py_vollib with Jaeckel's Let's Be Rational; ancestry-aware, Stage A COARSE; SOURCE_READ on M3; position
85 of the 2026-09-17 NOT_CUT order). Read: vollib/black/implied_volatility.py 59-300 (the entry points and the limited-iterations
call), vollib/lets_be_rational/core.py (a compatibility re-export of py_lets_be_rational.lets_be_rational). NOT read: the
py_lets_be_rational.lets_be_rational body (the rational-cubic guess and the Householder step live there, not in this tree), the
Black-Scholes-Merton pricing and greeks, the numerical-greeks module. Nothing ran; the body is pure Python: an M3-runnable packet
candidate (the analytic Black price is the exact oracle; recorded in the residue).
"""
from nyx.atlas.author import Cut

IV = "vault:py-vollib-lets-be-rational/upstream/tree/vollib/black/implied_volatility.py"; CO = "vault:py-vollib-lets-be-rational/upstream/tree/vollib/lets_be_rational/core.py"
c = Cut("py-vollib-lets-be-rational", mode="ANCESTRY_AWARE", inspected=["vollib/black/implied_volatility.py 59-300", "vollib/lets_be_rational/core.py"], evidence=[("SOURCE_READ", IV + ":59-300"), ("SOURCE_READ", CO + ":1-3")],
        note="the inverse of the Black option-pricing formula (given a price, find the volatility) solved to machine precision in a bounded number of steps by Jaeckel's 'Let's Be Rational': normalise the price, form a rational-cubic first guess whose branches are chosen by regime (near the intrinsic value, near the money, deep out of the money), then take one or two Householder (third-order) steps on a transformed objective so that the iteration count does not depend on the input; py_vollib is the packaging that exposes this under the Black and Black-Scholes-Merton conventions")

iv = c.organ("implied_volatility_by_a_rational_cubic_first_guess_per_price_regime_refined_by_householder_steps_on_a_transformed_objective_in_a_bounded_iteration_count", human_name="implied_volatility_of_discounted_option_price / normalised_implied_volatility (implied_volatility.py 59-228); normalised_implied_volatility_from_a_transformed_rational_guess_with_limited_iterations (the N-iteration entry into py_lets_be_rational)", status="ACCEPTED",
    mechanism="the discounted price is undiscounted and normalised by the forward and strike; the normalised Black price is a monotone function of volatility with known asymptotics at zero and infinity, so a rational-cubic interpolant (a Pade-like guess with regime-selected control points) gives a starting volatility close to the root everywhere; a Householder step (using the first three derivatives of the normalised price, which are cheap closed forms) then converges cubically, so one or two steps reach double precision regardless of moneyness; the limited-iterations entry exposes N so a caller can trade a little accuracy for a fixed cost",
    input="a price, forward, strike, time, and call/put flag", output="the implied volatility", state="none", update="per solve", assumptions=["the normalised Black price is monotone and smooth in volatility with analytic derivatives; a good regime-aware first guess makes a fixed small step count enough (Jaeckel 2013/2015)"],
    fitness_value_in_ancestor="implied volatility to machine precision in two iterations, replacing bisection or Newton loops with input-dependent iteration counts", failure_landscape="by reading: prices below the intrinsic value or above the forward have no real volatility; the code has denormalisation/limit branches for those (in the py_lets_be_rational body, not read here)",
    human_prior="Black 1976; Jaeckel 2013 'Let's Be Rational'; the rational-cubic interpolation is Jaeckel's", evidence_ref=IV + ":59-228", confidence="MEDIUM", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="the py_vollib wrappers; the numerics are in py_lets_be_rational (not in this tree); MEDIUM accordingly",
    coverage={"input_topology": "SCALAR", "output_topology": "SCALAR", "state_amount": "NONE", "stochasticity": "DETERMINISTIC", "update_topology": "RECURSIVE", "uncertainty": "POINT"})

c.reject("the Black-Scholes-Merton pricing and analytical/numerical greeks, the ref_python reference implementations, the helper and exception modules", reason="OTHER", evidence="NOT READ; residue", note="the analytical greeks are one formula each")
c.reject("'option pricing library' as one organ", reason="NAME_HAS_NO_EXECUTABLE_BOUNDARY", evidence="the forward price, the greeks and the implied-vol inverse are separable; the fossil's point is the inverse")

c.pressure("the_volatility_implied_by_an_option_price_must_be_recovered_to_machine_precision_in_a_fixed_number_of_steps_across_all_moneyness_regimes_where_a_generic_root_finder_takes_an_input_dependent_number_of_iterations",
    condition="an organism inverts a monotone but stiff price-to-volatility map for a stream of quotes spanning deep in, at, and deep out of the money; the score is accuracy and the worst-case iteration count over the stream", resource_or_constraint="closed-form derivatives of the price; a fixed step budget",
    failure_condition="an iteration count that blows up near the money or in the wings, or a loss of precision at the regime boundaries", world_punishes="bisection (linear, input-dependent); Newton from a fixed guess (diverges in the wings)", world_rewards="a regime-aware rational-cubic guess plus a third-order step",
    observable_consequence="iterations to double precision vs moneyness for bisection, Newton, and the rational-guess Householder method on a grid of forwards/strikes; error at the intrinsic-value boundary", vacuity_condition="at-the-money quotes only", trivial_shortcuts="a lookup table (which the world defeats by spanning the regimes continuously)",
    cheat_control="an organism given the true volatility (invert the analytic Black price of a known vol) must return it to machine precision; bisection must show the input-dependent iteration count; Newton from a flat guess must fail in the wings: the world must show all three",
    cost_class="CPU-scale", source_evidence="implied_volatility.py; the record's 'two iterations' claim", purpose="PURPOSE: implied-volatility inversion (Jaeckel 2013; py_vollib packaging)")

c.ancestry("reimplementation_of", "Black 1976 (the pricing formula) inverted by Jaeckel 2013/2015 (Let's Be Rational); py_vollib packages py_lets_be_rational", note="from the record and the module docstrings")
c.residue("PARTIALLY_EXPLAINED", ["the numerical core (rational-cubic guess and Householder step) is in py_lets_be_rational, not in this tree", "greeks and pricing unread", "nothing ran; M3-RUNNABLE PACKET CANDIDATE with the analytic Black price as an exact oracle"], note="the mechanism is named and located by call; the body it calls is a dependency, flagged for Techne's packet (entry point + dependency)")
c.save(state="COARSE")
