"""Cut: pybreaker-1.2.0 (Nygard's circuit breaker in Python; ancestry-aware, Stage A DEEP; SOURCE_READ on M3; position 80 of the
2026-09-17 NOT_CUT order). Read: src/pybreaker/__init__.py the CircuitBreaker class 71-330 (structure), CircuitBreakerStorage /
CircuitMemoryStorage / the Redis storage 332-560 (names and the opened_at set-if-greater), CircuitBreakerState and the three states
588-812 in full. NOT read: the async and generator call variants' bodies, the listeners, the tests. Nothing ran; the body is pure Python
(the Redis storage is optional): an M3-runnable packet candidate (recorded in the residue).
"""
from nyx.atlas.author import Cut

B = "vault:pybreaker-1.2.0/upstream/tree/pybreaker-1.2.0/src/pybreaker/__init__.py"
c = Cut("pybreaker-1.2.0", mode="ANCESTRY_AWARE", inspected=["src/pybreaker/__init__.py 71-330 (structure), 332-560 (names), 588-812"], evidence=[("SOURCE_READ", B + ":588-812"), ("SOURCE_READ", B + ":71-330"), ("SOURCE_READ", B + ":332-560")],
        note="the circuit breaker as a three-state machine on a failure counter: CLOSED counts consecutive failures (successes reset the count) and trips to OPEN at fail_max; OPEN fails every call immediately until reset_timeout has elapsed since it opened, then moves to HALF-OPEN; HALF-OPEN lets one call through and closes on success or re-opens on failure; the state and counter live in a storage object so that several processes can share one breaker through Redis, where 'opened_at' is written with a set-if-greater so concurrent openers agree on the latest time")

fsm = c.organ("three_state_breaker_closed_counting_consecutive_failures_to_a_threshold_open_failing_fast_for_a_timeout_half_open_admitting_one_probe_call", human_name="CircuitClosedState.on_failure (727-736): counter >= fail_max -> open(); CircuitOpenState.before_call (759-770): if now < opened_at + reset_timeout raise CircuitBreakerError else half_open(); CircuitHalfOpenState (779-812): on_failure -> open(), on_success -> close(); _handle_success resets the counter (622-625); excluded exceptions do not count (204-215)", status="ACCEPTED",
    mechanism="in the closed state each call runs; a failure (an exception not in the excluded list) increments a counter and at fail_max the breaker opens and re-raises wrapped; in the open state every call raises immediately without touching the dependency until the reset timeout has passed since the recorded opening time, at which point the breaker goes half-open and the current call is the probe; a probe success closes the breaker and resets the counter, a probe failure re-opens it and restarts the timeout",
    input="calls and their outcomes", output="pass-through results or fast failures", state="state, counter, opened_at", update="per call", assumptions=["a dependency that has failed fail_max times in a row is down and calling it wastes time and worsens its recovery; one probe per timeout is enough to detect recovery"],
    fitness_value_in_ancestor="the calling system stays responsive while a dependency is down and does not hammer it during recovery (Nygard's Release It!)", failure_landscape="by reading: consecutive failures only (a 1 percent error rate never trips; rate-based trips are a later variant); the probe is the first real call, so it may fail for the caller", human_prior="Nygard 2007; the pattern is older in electrical protection", evidence_ref=B + ":588-812", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="the three state classes",
    coverage={"input_topology": "EVENT", "output_topology": "DECISION", "state_amount": "CONSTANT", "state_persistence": "PERSISTENT", "feedback": "CLOSED_LOOP", "stochasticity": "ENVIRONMENT_RANDOM", "update_topology": "EVENT_DRIVEN", "recovery": "RETRIES"})

store = c.organ("breaker_state_and_counter_held_in_a_pluggable_storage_so_processes_share_one_breaker_with_the_opening_time_written_by_set_if_greater", human_name="CircuitBreakerStorage (332-375: state, counter, opened_at as properties), CircuitMemoryStorage (377-420), the Redis storage (428-560): namespaced keys, increment_counter by INCR, opened_at via a pipeline 'set_if_greater' (547-557)", status="ACCEPTED",
    mechanism="the breaker never holds its state in the object; every read and write goes through a storage interface with an in-memory default; the Redis storage keeps the state string, the counter (atomic increment) and the opening timestamp under namespaced keys, and writes the timestamp only if it is greater than the stored one inside a transaction, so that two processes opening the breaker at nearly the same time agree on the later time and neither shortens the other's timeout",
    input="state reads and writes", output="a shared view of the breaker", state="the store", update="per transition", assumptions=["a breaker per process would let each process discover the outage separately; sharing through a store gives the fleet one decision"],
    fitness_value_in_ancestor="fleet-wide fail-fast from a single-process pattern", failure_landscape="by reading: the Redis round trip is on every call's path; a Redis outage becomes a breaker outage (the code falls back to closed on read errors per the names, not verified)", human_prior="the pattern's distributed variants (Hystrix's per-process design vs shared state)", evidence_ref=B + ":332-560", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="the storage classes",
    coverage={"input_topology": "EVENT", "output_topology": "EVENT", "state_amount": "CONSTANT", "state_persistence": "DURABLE", "stochasticity": "ENVIRONMENT_RANDOM", "competition": "CONTENDS"})

c.reject("the decorator and context-manager sugar (__call__, calling), the async and generator call variants, listeners (before_call / success / failure / state_change hooks), the type annotations, the tests", reason="GENERIC_LANGUAGE_MECHANICS", evidence=B + ":219-330, 565-590")
c.reject("'circuit breaker' as one organ", reason="NAME_HAS_NO_EXECUTABLE_BOUNDARY", evidence="the state machine and the shared store are separable; the atlas's backoff cut holds the complementary retry mechanism the pattern is meant to bound")

c.edge(fsm, store, "stores"); c.edge(store, fsm, "feeds")

c.pressure("a_caller_of_a_failing_dependency_must_stop_calling_it_quickly_keep_its_own_latency_bounded_and_notice_recovery_without_flooding_the_dependency_while_many_callers_decide_independently",
    condition="N organisms call a dependency that goes down for a while and then recovers slowly; each call to a down dependency costs a timeout; the score is the callers' latency during the outage, the load on the dependency during recovery, and the delay in noticing recovery", resource_or_constraint="a counter and a clock per breaker; optionally a shared store",
    failure_condition="callers blocked on timeouts throughout the outage, or a recovery stalled by a flood of retries, or a breaker that never closes", world_punishes="retry-forever; per-process breakers that each probe at once; no half-open state", world_rewards="a failure-count trip, a timeout-gated single probe, shared state",
    observable_consequence="caller latency and dependency load over a simulated outage-and-recovery for no breaker, per-process breakers and a shared breaker; time from recovery to the first closed breaker", vacuity_condition="a dependency that never fails", trivial_shortcuts="an oracle that says when the dependency is up (the cheat control)",
    cheat_control="an organism told the outage interval must show zero timeouts and zero probes; retry-forever must show latency equal to the timeout for the whole outage; N per-process breakers must show N probes per reset period where the shared breaker shows one: the world must show all three",
    cost_class="CPU-scale", source_evidence="the three state classes; the Redis storage's set-if-greater", purpose="PURPOSE: stability pattern for distributed callers (Nygard 2007; pybreaker 2010-)")

c.ancestry("reimplementation_of", "Nygard's circuit breaker (Release It!, 2007); the atlas's backoff-2.2.1 is its complement (retry policy) and redlock-py the other distributed-coordination body in the same order", note="from the record")
c.residue("EXPLAINED_BY_CURRENT_CUT", ["async / generator variants and listeners unread (sugar)", "nothing ran", "M3-RUNNABLE PACKET CANDIDATE: pure Python with the in-memory store; a simulated outage is the world"], note="the fifth pure-Python candidate of this pass; the pattern's two mechanisms are located")
c.save(state="DEEP")
