"""Cut: quadpack-netlib (QUADPACK, Piessens et al. 1983, as served by netlib; ancestry-aware, Stage A COARSE; SOURCE_READ on M3; position
82 of the 2026-09-17 NOT_CUT order). Read: dqagse.f header 1-165 and the call structure (dqk21, dqpsrt, dqelg at 240-390); dqelg.f header
1-60. NOT read: the rule bodies (dqk21 and the other Gauss-Kronrod pairs), the weight-function integrators (qawo, qaws, qawc), the
infinite-range transformation (qagi), the singular-point variant (qagp). Nothing ran (Fortran; no compiler on M3).
"""
from nyx.atlas.author import Cut

S = "vault:quadpack-netlib/upstream/dqagse.f"; E = "vault:quadpack-netlib/upstream/dqelg.f"
c = Cut("quadpack-netlib", mode="ANCESTRY_AWARE", inspected=["dqagse.f 1-165, 240-390 (calls)", "dqelg.f 1-60"], evidence=[("SOURCE_READ", S + ":1-165"), ("SOURCE_READ", S + ":240-390"), ("SOURCE_READ", E + ":1-60")],
        note="adaptive quadrature as three mechanisms: a Gauss-Kronrod pair (21 points) that returns an estimate and an error estimate from the difference of its two rules; globally adaptive bisection that always splits the subinterval with the largest error estimate (a sorted list maintained by dqpsrt) until the total error meets the tolerance or the subdivision limit; and Wynn's epsilon algorithm applied to the sequence of partial results to extrapolate through end-point singularities, with round-off detection that switches extrapolation off")

gk = c.organ("gauss_kronrod_21_point_rule_returning_the_integral_and_an_error_estimate_from_the_difference_with_its_embedded_gauss_rule", human_name="dqk21 (called at 240, 289-290; body not read); result, abserr, resabs, resasc", status="CANDIDATE",
    mechanism="a 21-point Kronrod rule shares its nodes with an embedded 10-point Gauss rule; the two estimates' difference, scaled by the integral of |f - mean| (resasc) with a heuristic power, gives the error estimate; both the value and the error come from one set of 21 function evaluations", input="f on [a, b]", output="the estimate and its error", state="none", update="per subinterval",
    assumptions=["the Kronrod extension of a Gauss rule is the cheapest way to get an error estimate from the same points (Kronrod 1965)"], fitness_value_in_ancestor="one function evaluation set per interval yields value and error", failure_landscape="UNKNOWN by run", human_prior="Kronrod 1965; Piessens' scaling of the error", evidence_ref=S + ":240, 289-290 (call sites)", confidence="MEDIUM", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="dqk21; CANDIDATE because the body was not read",
    coverage={"input_topology": "SCALAR", "output_topology": "SCALAR", "state_amount": "NONE", "stochasticity": "DETERMINISTIC", "uncertainty": "INTERVAL"})

bis = c.organ("globally_adaptive_bisection_of_the_subinterval_with_the_largest_error_estimate_kept_in_descending_order_until_the_summed_error_meets_the_tolerance_or_the_limit", human_name="dqagse.f 250-390: the main loop; dqpsrt (346) maintains the descending order of error estimates; limit; the two-interval error sum; ier codes 1-5 (limit, roundoff, bad integrand behaviour, divergence, invalid input)", status="ACCEPTED",
    mechanism="the interval is split at the midpoint of whichever subinterval currently has the largest error estimate; the two halves are integrated by the rule; the list of subintervals is kept sorted by error estimate (a partial insertion sort that only moves the new entries); the loop stops when the sum of error estimates is within the absolute or relative tolerance, when the subdivision limit is reached, or when round-off is detected (the error estimate stops decreasing as intervals shrink)",
    input="tolerances, limit", output="the integral, the error, an ier code", state="the interval lists (alist, blist, rlist, elist, iord)", update="per bisection", assumptions=["error is concentrated where the integrand is hard, so refining the worst interval is the best use of evaluations"],
    fitness_value_in_ancestor="the general-purpose integrator behind scipy.integrate.quad", failure_landscape="by reading: a smooth integrand with an undetected feature between rule points can pass (ier 0) with a wrong answer; the ier codes are the documented failure landscape", human_prior="Piessens, de Doncker, Uberhuber, Kahaner 1983 (QUADPACK)", evidence_ref=S + ":250-390", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="dqagse's loop and dqpsrt",
    coverage={"input_topology": "SCALAR", "output_topology": "SCALAR", "state_amount": "LINEAR_IN_INPUT", "stochasticity": "DETERMINISTIC", "update_topology": "PRIORITY", "recovery": "DEGRADES_GRACEFULLY"})

eps = c.organ("wynn_epsilon_extrapolation_of_the_sequence_of_partial_integrals_over_the_smallest_intervals_switched_off_on_round_off_detection", human_name="dqelg (called at 384; header read): the condensed epsilon table; numrl2, rlist2, res3la; ier 2 'roundoff error is detected in the extrapolation table'; the 'extrapolation' flag path in dqagse", status="ACCEPTED",
    mechanism="as bisection concentrates on a singular end point, the partial sums over the shrinking intervals form a sequence converging slowly; Wynn's epsilon algorithm (a nonlinear sequence transformation equivalent to Shanks / Pade) is applied to the sequence to estimate its limit and an error; the extrapolated result replaces the plain sum when its error is smaller; the table is limited (limexp) and the routine detects when round-off dominates and stops extrapolating",
    input="the sequence of results", output="an extrapolated result and error", state="the epsilon table and the last three results", update="per extrapolation step", assumptions=["algebraic-logarithmic end-point singularities produce sequences the epsilon algorithm accelerates (de Doncker's analysis)"],
    fitness_value_in_ancestor="integrands with end-point singularities converge in far fewer evaluations; the reason qags is the default in scipy", failure_landscape="by reading: extrapolation can be fooled by non-singular slow convergence; the round-off detector is the guard", human_prior="Wynn 1956; de Doncker 1978", evidence_ref=E + ":1-60; " + S + ":384", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="dqelg and its call",
    coverage={"input_topology": "SEQUENCE", "output_topology": "SCALAR", "state_amount": "CONSTANT", "stochasticity": "DETERMINISTIC", "update_topology": "RECURSIVE"})

c.reject("the other rules (qk15/31/41/51/61), the weight-function integrators (qawo, qaws, qawc, qawf), qagi (infinite range by transformation), qagp (user-given singular points), qng (non-adaptive), the single-precision twins", reason="OTHER", evidence="NOT READ; residue")
c.reject("'numerical integration' as one organ", reason="NAME_HAS_NO_EXECUTABLE_BOUNDARY", evidence="the rule, the adaptive strategy and the extrapolation are separable and separately published")

c.edge(gk, bis, "feeds"); c.edge(bis, eps, "feeds"); c.edge(eps, bis, "gates", note="ier 2 stops extrapolation")

c.pressure("a_definite_integral_must_be_computed_to_a_requested_tolerance_with_the_fewest_evaluations_when_the_integrand_may_have_end_point_singularities_and_the_organism_must_report_when_it_cannot_trust_its_own_error_estimate",
    condition="an organism integrates a black-box f over [a, b]; some integrands are smooth, some have algebraic or logarithmic end-point singularities, some are pathological; the score is evaluations to reach the tolerance and the honesty of the reported error", resource_or_constraint="function evaluations; a subdivision limit",
    failure_condition="a wrong answer reported as converged, or evaluations growing without bound on a singular integrand", world_punishes="uniform refinement; no error estimate; no extrapolation", world_rewards="embedded error estimates, worst-first bisection, sequence extrapolation with round-off detection",
    observable_consequence="evaluations and true error vs reported error on the Piessens test set with extrapolation on and off", vacuity_condition="polynomial integrands", trivial_shortcuts="an integrand-specific change of variables (which the world withholds)",
    cheat_control="an organism given the analytic integral must report zero error; bisection without extrapolation must need orders of magnitude more evaluations on x^-0.5-type integrands; the pathological integrand must return ier != 0 rather than a confident wrong answer: the world must show all three",
    cost_class="CPU-scale", source_evidence="dqagse.f; dqelg.f", purpose="PURPOSE: automatic quadrature (Piessens et al. 1983)")

c.ancestry("algorithm_from", "Kronrod 1965; Wynn 1956; Piessens et al. 1983; the netlib mirror is the authors' channel (record)", note="from the headers")
c.residue("PARTIALLY_EXPLAINED", ["rule bodies and the special-purpose integrators unread", "nothing ran"], note="the three mechanisms of the default integrator are located; the rule itself is CANDIDATE")
c.save(state="COARSE")
