"""Cut: redlock-py-redis-2014 (a Python Redlock, the Redis distributed lock; ancestry-aware, Stage A DEEP; SOURCE_READ on M3; position 86
of the 2026-09-17 NOT_CUT order). Read: redlock/__init__.py in full (132 lines). NOT read: the CLI, the setup, the tests. Nothing ran
(needs a Redis majority; not on M3). Its lineage tag is FAITHFUL_PORT of antirez's algorithm.
"""
from nyx.atlas.author import Cut

R = "vault:redlock-py-redis-2014/upstream/tree/redlock/__init__.py"
c = Cut("redlock-py-redis-2014", mode="ANCESTRY_AWARE", inspected=["redlock/__init__.py 1-132"], evidence=[("SOURCE_READ", R + ":1-132")],
        note="a lease-based distributed mutex over N independent Redis instances: acquire the same key with a unique random value and a TTL on each instance; the lock is held only if a majority acknowledged within a validity window that subtracts the elapsed acquisition time and a clock-drift margin from the TTL; release is a check-and-delete Lua script that deletes the key only if its value still matches the acquirer's, so a lease that already expired and was retaken is never deleted by the old holder")

acq = c.organ("acquire_the_same_key_with_a_unique_value_and_ttl_on_every_instance_holding_the_lock_only_if_a_majority_acked_within_a_validity_window_that_discounts_elapsed_time_and_clock_drift", human_name="Redlock.lock (72-120): val = 22 random chars; drift = ttl * 0.01 + 2; per server SET resource val NX PX ttl; validity = ttl - elapsed - drift; hold if validity > 0 and n >= quorum, else unlock everywhere and retry; quorum = N // 2 + 1", status="ACCEPTED",
    mechanism="a unique value identifies this acquisition; the client sets the key with NX (only if absent) and PX (a millisecond TTL) on each of the N servers, timing the whole round; the lock is granted only if at least a majority set succeeded AND the remaining validity (TTL minus the time the round took minus a drift allowance) is still positive; if either fails the client deletes its value from every server and retries after a delay; the drift margin (1 percent of the TTL plus 2 ms) accounts for clock differences between the client and the servers",
    input="a resource name and a TTL", output="a Lock (validity, resource, value) or False", state="none on the client beyond the returned lock", update="per acquire", assumptions=["a majority of independent, non-colluding Redis instances is available; clocks drift by less than the margin over the lease; the network round trip is much shorter than the TTL (else validity goes negative)"],
    fitness_value_in_ancestor="mutual exclusion without a single point of failure, from plain Redis instances", failure_landscape="by reading: the algorithm was criticised (Kleppmann 2016) because a process pause or clock jump longer than the validity window lets two holders believe they hold the lock; the validity return value is the client's own honest bound, not a guarantee the resource enforces", human_prior="antirez / Sanfilippo, redis.io/topics/distlock 2014",
    evidence_ref=R + ":72-120", confidence="HIGH", portability="YES", compatibility="UNKNOWN", utility="UNKNOWN", source_boundary="Redlock.lock", coverage={"input_topology": "SCALAR", "output_topology": "DECISION", "state_amount": "NONE", "feedback": "CLOSED_LOOP", "stochasticity": "ENVIRONMENT_RANDOM", "update_topology": "PARALLEL_ROUNDS", "competition": "ARBITRATES"})

rel = c.organ("release_by_a_check_and_delete_lua_script_that_deletes_the_key_only_when_its_value_still_equals_the_acquirers_so_an_expired_and_retaken_lease_is_never_deleted_by_the_old_holder", human_name="Redlock.unlock (121-132) and unlock_script: 'if redis.call(get, KEYS[1]) == ARGV[1] then return redis.call(del, KEYS[1]) else return 0'; unlock_instance runs it on every server", status="ACCEPTED",
    mechanism="release runs one Lua script per server that atomically compares the stored value with the acquirer's unique value and deletes the key only on a match; because the compare and delete are one server-side script they cannot interleave, and because the value is unique per acquisition, a holder whose lease already expired (and whose key was retaken by another client with a different value) cannot delete the new holder's lock",
    input="a Lock", output="the key removed where it still belongs to the caller", state="none", update="per release", assumptions=["the get-and-delete must be atomic (hence a script, not two calls); the value must be unpredictable and unique so no other client can forge a release"],
    fitness_value_in_ancestor="safe release even after a lease lapses; the mistake it prevents (a plain DEL that could delete someone else's lock) is the reason for the script", failure_landscape="by reading: if the server is unreachable at release the key lingers until its TTL, which is acceptable; MultipleRedlockException surfaces per-server errors", human_prior="the same distlock note", evidence_ref=R + ":25-70, 121-132", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="unlock_instance and the script",
    coverage={"input_topology": "EVENT", "output_topology": "EVENT", "state_amount": "NONE", "stochasticity": "DETERMINISTIC", "update_topology": "PARALLEL_ROUNDS"})

c.reject("the CLI (cli.py), setup.py, the connection-parsing in __init__ (url / dict / object forms), the retry-count and delay bookkeeping", reason="GENERIC_LANGUAGE_MECHANICS", evidence=R + ":36-70")
c.reject("'distributed lock' as one organ", reason="NAME_HAS_NO_EXECUTABLE_BOUNDARY", evidence="the majority-acquire-with-validity and the check-and-delete release are separable; the atlas's cocagne-plain-paxos and willemt-raft hold the consensus alternatives to a lease")

c.edge(acq, rel, "feeds", note="the unique value ties acquire to release")

c.pressure("a_shared_resource_must_be_held_by_at_most_one_client_at_a_time_using_only_independent_key_value_stores_with_ttls_when_clients_and_stores_can_fail_and_clocks_can_drift",
    condition="N independent stores with expiring keys; many clients race for one resource; stores and clients crash; clocks are imperfect; the score is whether two clients ever both believe they hold the lock, and whether the resource is ever left locked forever", resource_or_constraint="N stores; a TTL; a drift margin",
    failure_condition="two simultaneous holders (a safety violation), or a permanently locked resource after a crash", world_punishes="a single store (a point of failure); a plain DEL release; ignoring elapsed time and drift", world_rewards="majority acquisition, a validity window, unique-value check-and-delete, TTL expiry",
    observable_consequence="the count of double-holds and stuck locks under injected store crashes, client pauses and clock skew, for the majority+validity algorithm vs a single-store lock; the sensitivity of double-holds to a pause longer than the validity", vacuity_condition="one client", trivial_shortcuts="a linearizable consensus service (Raft/Paxos, in this atlas) which the world may offer as the stronger control",
    cheat_control="a Raft-backed lock must show zero double-holds under the same faults; the single-store lock must fail when that store crashes; Redlock must hold except when a pause exceeds the validity (Kleppmann's case): the world must show all three", cost_class="CPU-scale",
    source_evidence="Redlock.lock; the unlock script; the distlock note and Kleppmann's critique (record)", purpose="PURPOSE: distributed mutual exclusion over Redis (antirez 2014)")

c.ancestry("port_of", "antirez's Redlock (redis.io/topics/distlock, 2014); the record notes Kleppmann's 2016 critique", note="from the record and the source")
c.residue("EXPLAINED_BY_CURRENT_CUT", ["connection plumbing and CLI unread", "nothing ran (needs a Redis majority: an M2 world)"], note="a small body; both mechanisms located; a comparison point for the consensus fossils in the atlas")
c.save(state="DEEP")
