"""Cut: souffle-2.4.1 (Souffle, the compiled Datalog engine; ancestry-aware, Stage A COARSE, narrow per the 2026-09-18 directive;
SOURCE_READ on M3; position 18 of the 2026-09-17 NOT_CUT order, deferred until this block). Read: src/ast2ram/seminaive/
UnitTranslator.cpp generateStratum / generateRecursiveStratum / generateStratumPreamble/Postamble 161-490 (the semi-naive loop with
delta / new / reject relations and stratified SCCs), the RAM operation list (src/ram: Loop, Exit, Swap, MergeExtend, Clear, Insert,
IndexScan), the interpreter/index file list (BTreeIndex, BrieIndex, EqrelIndex). NOT read: the AST, the parser, the C++ code generator,
the RAM operation bodies, the provenance layer, the 3,900 other files. Nothing ran (C++; no compiler on M3).
"""
from nyx.atlas.author import Cut

U = "vault:souffle-2.4.1/upstream/tree/souffle-2.4.1/src/ast2ram/seminaive/UnitTranslator.cpp"
c = Cut("souffle-2.4.1", mode="ANCESTRY_AWARE", inspected=["src/ast2ram/seminaive/UnitTranslator.cpp 161-490", "src/ram operation list", "src/interpreter index list"], evidence=[("SOURCE_READ", U + ":161-360"), ("SOURCE_READ", U + ":454-490")],
        note="bottom-up Datalog evaluated semi-naively and compiled: rules are stratified into strongly-connected components evaluated in dependency order; within a recursive component each relation keeps a main store, a delta of the tuples derived in the last round, and a new store for this round; each iteration derives only tuples that use at least one delta tuple (so no derivation is repeated), merges new into main and swaps new into delta, and stops when the delta is empty; the relations are specialised in-memory index structures (B-tree, Brie trie, equivalence-relation) chosen per relation, and the whole thing is either interpreted over a RAM IR or compiled to parallel C++")

seminaive = c.organ("semi_naive_evaluation_that_derives_only_tuples_using_a_delta_tuple_each_round_merging_new_into_main_and_swapping_new_into_delta_until_the_delta_is_empty", human_name="generateRecursiveStratum (303-360): per relation a delta, new and reject store; clear delta; derive clause versions; MergeRelationsWithFilter new -> delta minus reject; clear new; Loop with an Exit on empty delta; generateStratumPreamble/Postamble (454-490) seed and clear the deltas", status="ACCEPTED",
    mechanism="for a recursive component, each relation R has R (all tuples so far), delta-R (tuples new in the previous round) and new-R (tuples derived this round); a round evaluates each recursive rule once per body atom that ranges over the SCC, forcing that atom to read delta while the others read the main relations (the 'delta version' of the clause), so every derived tuple depends on at least one just-derived tuple and nothing is re-derived; new-R minus the existing tuples becomes the next delta, new-R is merged into R, and the loop exits when every delta is empty (the least fixed point is reached)",
    input="a stratified set of rules and the base facts", output="the least model", state="the main/delta/new stores per relation", update="per round", assumptions=["Datalog's monotone rules have a least fixed point reachable bottom-up; restricting each round to delta-touching derivations avoids the naive method's repeated work (Balbin & Ramamohanarao 1987)"],
    fitness_value_in_ancestor="each derivation done once; the standard efficient Datalog evaluation, the base of large-scale static analysis (Doop, ...)", failure_landscape="by reading: stratification must be possible (no recursion through negation or aggregation); the delta/new/reject bookkeeping is intricate and the subsumptive-clause path adds delete relations", human_prior="Balbin & Ramamohanarao 1987 (semi-naive); Bancilhon & Ramakrishnan 1986; Souffle (Scholz et al. 2016)",
    evidence_ref=U + ":303-360", confidence="HIGH", portability="YES", compatibility="UNKNOWN", utility="UNKNOWN", source_boundary="the recursive-stratum generation",
    coverage={"input_topology": "SET", "output_topology": "SET", "state_amount": "SUPERLINEAR", "state_persistence": "PER_EPISODE", "feedback": "CLOSED_LOOP", "stochasticity": "DETERMINISTIC", "update_topology": "PARALLEL_ROUNDS", "recovery": "SELF_RESETS"})

strat = c.organ("rules_stratified_into_strongly_connected_components_evaluated_in_dependency_order_with_non_recursive_components_evaluated_once_and_expired_relations_cleared", human_name="generateStratum (161-196): if the SCC is recursive call generateRecursiveStratum else evaluate the single relation once; generateClearExpiredRelations (196); the SCC ordering from the precedence graph", status="ACCEPTED",
    mechanism="the predicate dependency graph is decomposed into strongly-connected components; a component with no internal recursion is evaluated in one pass, a recursive one by the semi-naive loop; components are run in topological order so a relation's dependencies are complete before it is computed; a relation is cleared once no later stratum needs it, bounding memory",
    input="the dependency graph", output="an evaluation schedule", state="the live relation set", update="per stratum", assumptions=["the program stratifies (negation and aggregation only across component boundaries); computing in dependency order is both correct and memory-bounded"],
    fitness_value_in_ancestor="large programs evaluated with only the currently-needed relations resident", failure_landscape="UNKNOWN by run", human_prior="stratified Datalog (Apt, Blair, Walker 1988); the SCC schedule is standard", evidence_ref=U + ":161-196", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="generateStratum and the expiry",
    coverage={"input_topology": "GRAPH", "output_topology": "SEQUENCE", "state_amount": "LINEAR_IN_INPUT", "stochasticity": "DETERMINISTIC", "update_topology": "SWEEP"})

idx = c.organ("relations_stored_in_specialised_in_memory_index_structures_chosen_per_relation_over_a_ram_ir_that_is_interpreted_or_compiled_to_parallel_c_plus_plus", human_name="src/ram operations (IndexScan, ExistenceCheck, Insert, Loop, Swap, MergeExtend); src/interpreter indexes (BTreeIndex, BrieIndex, EqrelIndex, ProvenanceIndex); the ast2ram -> ram -> interpreter/synthesiser pipeline", status="CANDIDATE",
    mechanism="the semi-naive schedule is emitted as a RAM (relational algebra machine) program of loops, index scans, existence checks and inserts; each relation is backed by a data structure chosen for its access pattern -- a concurrent B-tree for general relations, a Brie (a trie specialised for dense integer tuples), or an equivalence-relation structure for transitive symmetric relations -- and the RAM program is either walked by an interpreter or synthesised to parallel C++ and compiled, so the same evaluation runs interpreted for quick turnaround or compiled for speed",
    input="the RAM program and the relations", output="materialised relations", state="the index structures", update="per RAM operation", assumptions=["the access pattern of each relation is known at compile time, so a specialised index beats a general one; a RAM IR decouples the evaluation strategy from the execution mode"],
    fitness_value_in_ancestor="Datalog at C++ speed on billions of tuples (the record: the engine behind large-scale static analysis)", failure_landscape="UNKNOWN by run", human_prior="Scholz, Jordan, Subotic, Westmann 2016 (Souffle); the Brie is Jordan et al.", evidence_ref="src/ram and src/interpreter file lists", confidence="MEDIUM", portability="YES", compatibility="UNKNOWN", utility="UNKNOWN", source_boundary="the RAM IR and index layer; CANDIDATE because only the file inventory was read",
    coverage={"input_topology": "SET", "output_topology": "SET", "state_amount": "SUPERLINEAR", "state_persistence": "PERSISTENT", "stochasticity": "DETERMINISTIC", "update_topology": "PARALLEL_ROUNDS"})

c.reject("the AST and parser (yacc/flex), the AST->RAM translators other than the seminaive UnitTranslator, the RAM operation bodies, the C++ synthesiser, the provenance / subsumption layer, the profiler, the 3,900 other files", reason="OTHER", evidence="NOT READ; residue", note="the directive of 2026-09-18 s1: no deepening of a large COARSE body without a downstream question; the Brie index and the C++ synthesiser are each a specimen-sized mechanism")
c.reject("'Datalog engine' as one organ", reason="NAME_HAS_NO_EXECUTABLE_BOUNDARY", evidence="the semi-naive fixpoint, the stratification schedule and the index/execution layer are separable; the atlas's clips (Rete, forward) and swipl/gnu-prolog (top-down) are the inference-engine neighbours")

c.edge(strat, seminaive, "feeds", note="recursive components"); c.edge(seminaive, idx, "feeds", note="derivations land in the indexes"); c.edge(idx, seminaive, "feeds", note="scans read delta/main")

c.pressure("a_set_of_recursive_logical_rules_over_a_large_fact_base_must_be_evaluated_to_its_least_model_without_re_deriving_any_tuple_and_without_holding_more_relations_resident_than_the_current_stratum_needs",
    condition="an organism computes the closure of recursive rules (e.g. reachability, points-to) over millions to billions of base facts; the score is time and peak memory; naive evaluation re-derives every tuple every round", resource_or_constraint="memory for the relations and their deltas; index structures",
    failure_condition="re-deriving tuples (naive evaluation's quadratic waste), holding expired relations, or a general index where a specialised one would fit", world_punishes="naive fixpoint; one index type for all relations; interpreting when speed is needed", world_rewards="semi-naive delta evaluation, SCC stratification with expiry, per-relation specialised indexes, optional compilation",
    observable_consequence="time and peak memory on a transitive-closure or points-to benchmark for naive vs semi-naive, and interpreted vs compiled, and general B-tree vs Brie indexes on dense relations", vacuity_condition="non-recursive rules (one pass)", trivial_shortcuts="materialising the full closure by hand (the answer, not a method)",
    cheat_control="an organism given the least model must reproduce it; naive evaluation must show the re-derivation blowup on transitive closure; a single-index build must show the memory/time penalty on dense relations where the Brie wins: the world must show all three", cost_class="CPU-scale",
    source_evidence="UnitTranslator.cpp semi-naive generation; the RAM and index inventory", purpose="PURPOSE: high-performance Datalog for program analysis (Scholz et al. 2016)")

c.ancestry("algorithm_from", "Balbin & Ramamohanarao 1987 (semi-naive); Apt-Blair-Walker 1988 (stratification); Scholz, Jordan, Subotic, Westmann 2016 (Souffle)", note="from the record and the source")
c.residue("LARGE_RESIDUE", ["the parser, the C++ synthesiser, the index bodies and the provenance layer unread; one CANDIDATE organ from the file inventory", "nothing ran (C++ build: an M2 world)"], note="the semi-naive fixpoint and stratification are located; the index/compilation layer is named per the directive's no-deepening line")
c.save(state="COARSE")
