"""Cut: spacewar-pdp1-1962 (Spacewar! version 2B, 25 March 1962, PDP-1 macro assembly listing; Stage A COARSE; SOURCE_READ on M3; position
59 of the 2026-09-17 NOT_CUT order). Read: the section comments and labels of spacewar_2b_25mar62.txt (1,099 lines): the sine-cosine
subroutine 85-135, the outline compiler 295-345, the main control routine 572-782 (object tables, the comparison loop, the calc-routine
dispatch), the torpedo and spaceship calc routines 819-1035 (labels and comments), the star-collision handling 1042-1060. NOT read: the
instruction-level bodies (PDP-1 assembly; read at the level of comments and control flow). Nothing ran (a PDP-1 emulator would be
needed).
"""
from nyx.atlas.author import Cut

S = "vault:spacewar-pdp1-1962/upstream/spacewar_2b_25mar62.txt"
c = Cut("spacewar-pdp1-1962", mode="ANCESTRY_AWARE", inspected=["spacewar_2b_25mar62.txt: comments and labels 1-1099; sections 85-135, 295-345, 572-782, 819-1060 at control-flow level"], evidence=[("SOURCE_READ", S + ":572-782"), ("SOURCE_READ", S + ":819-1060"), ("SOURCE_READ", S + ":85-135"), ("SOURCE_READ", S + ":295-345")],
        note="a real-time simulation in a fixed instruction budget: every active object (two ships, torpedoes, explosions) is a row in parallel tables (x, y, dx, dy, angle, angular velocity, fuel, torpedoes, outline, and a POINTER TO ITS CALC ROUTINE); the main loop walks the tables, compares every pair for collision within an epsilon, then calls each object's calc routine to move and display it, and burns the remaining time budget so a frame takes constant time; an object changes behaviour by having its calc-routine pointer replaced (a ship that collides becomes an explosion with a duration count); the starfield is a background program; gravity toward the central star is a switch-selectable calc term")

tables = c.organ("objects_as_rows_of_parallel_tables_each_carrying_a_pointer_to_its_own_calc_routine_so_behaviour_is_changed_by_swapping_the_pointer", human_name="main control routine 572-631 (the table set-up: mx1 x, my1 y, ma1 count, mb1 instruction count, mdx/mdy, mom angular velocity, mth angle, mal angular acceleration, mas, mfu fuel, mtr torpedoes, mot outline, mco control word, ml1 calc routine); 727-730 'yes, EXPLODE / replace calc routine with explosion / duration of explosion'; 993-998 'search for unused object'", status="ACCEPTED",
    mechanism="nnn object slots hold one entry per table; a slot is active if its calc-routine word is non-zero; the ship, torpedo and explosion behaviours are separate routines and an object's identity IS which routine its slot points to; launching a torpedo finds an unused slot and fills it with the torpedo routine, a position and a life count; a collision overwrites the slot's routine with the explosion routine and sets a duration; when the duration or life count expires the slot is freed",
    input="the tables", output="the tables after one frame", state="the parallel tables (nnn slots)", update="per frame", assumptions=["a small fixed number of objects; dispatch through a stored address is cheaper than a type field and a switch on a 1962 machine"],
    fitness_value_in_ancestor="new object kinds are new routines; the main loop never changes (the comment 'here put more bells and whistles, like hyperspace')", failure_landscape="by reading: no free slot means a halt (998 'hlt / no space for new objects')", human_prior="the earliest known instance of per-object behaviour dispatch in a game; the entity-table pattern", evidence_ref=S + ":572-631, 727-730, 993-998", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="the table definitions and the two pointer-replacement sites",
    coverage={"input_topology": "SET", "output_topology": "SET", "state_amount": "CONSTANT", "state_persistence": "PER_EPISODE", "stochasticity": "DETERMINISTIC", "update_topology": "SWEEP"})

frame = c.organ("fixed_time_frame_that_compares_every_pair_of_objects_for_collision_within_an_epsilon_then_runs_each_calc_routine_and_burns_the_remaining_budget", human_name="683-782: the comparison loop (mx1/mx2 delta x, abs, epsilon me1/me2; 'yes, EXPLODE'), the calc-and-display loop (mq4 'routine for calculating spaceship or other object and displaying it'; mb1 'alter count of number of instructions'), 778-781 'display stars of the heavens / display massive star / use up rest of time of main loop / repeat whole works'", status="ACCEPTED",
    mechanism="per frame: for every active object compare its x and y with every later active object; if both differences are under an epsilon (10000 octal, halved) both become explosions; then for every active object call its calc routine (which moves it, handles controls, draws its outline) and account the instructions it used; then draw the background starfield and the central star and spin in a counted loop until the frame's instruction budget is spent, so the simulation runs at a constant rate regardless of how many objects are active",
    input="the tables; the console switches", output="a drawn frame", state="the frame counter mtc", update="per frame", assumptions=["the machine is fast enough for the worst case within the budget; a constant frame time makes velocities meaningful"],
    fitness_value_in_ancestor="real-time interaction with deterministic physics on a 1962 machine", failure_landscape="by reading: O(n^2) collision checks (fine for nnn objects); a frame that exceeds the budget slows the game rather than dropping objects", human_prior="the fixed-timestep game loop; this is among its first instances", evidence_ref=S + ":683-782", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="the main loop ml0 to 'repeat whole works'",
    coverage={"input_topology": "SET", "output_topology": "EVENT", "state_amount": "CONSTANT", "stochasticity": "DETERMINISTIC", "update_topology": "SWEEP", "resource_dependence": "TIME"})

phys = c.organ("ship_motion_from_thrust_rotation_and_switch_selectable_star_gravity_with_a_table_based_sine_cosine_and_a_finite_torpedo_life", human_name="spaceship calc 838-945 (ss1/ss2; angular velocity, thrust along the heading, 'switch 2 for heavy star' 907, fuel mfu); the sine-cosine subroutine 85-135 (Adams Associates, a polynomial with quadrant folding); torpedo calc 819-835 and 1002-1035 (velocity = ship velocity plus muzzle velocity along the heading; 'life of torpedo' 300 frames; 'permit torp tubes to cool'); star collision 1042-1060 ('spaceship in star'; switch 5 to escape)", status="CANDIDATE",
    mechanism="each frame a ship integrates angular velocity into its heading, adds thrust (fuel permitting) along the heading via sine and cosine of the angle, adds an inverse-square pull toward the central star when the heavy-star switch is on, and integrates velocity into position with wrap-around; a torpedo is launched with the ship's velocity plus a fixed speed along the heading and lives for a fixed count; a ship entering the star is destroyed unless a console switch extracts it; the sine/cosine routine is a shared subroutine with a calling sequence documented in the comments",
    input="control words, the tables", output="new positions and headings", state="per-object rows", update="per frame", assumptions=["first-order Euler integration at the frame rate is stable enough for play; gravity is optional because the 1961 version had none (Edwards added it)"],
    fitness_value_in_ancestor="the orbital mechanics that made the game a game (the record: 'gravity by Dan Edwards')", failure_landscape="UNKNOWN by run", evidence_ref=S + ":838-945, 85-135, 819-835, 1002-1060 (comments and labels; instruction bodies not read)", confidence="MEDIUM", portability="YES", compatibility="UNKNOWN", utility="UNKNOWN", source_boundary="the ship and torpedo calc routines; CANDIDATE because read at comment level",
    coverage={"input_topology": "VECTOR", "output_topology": "VECTOR", "state_amount": "CONSTANT", "stochasticity": "DETERMINISTIC", "update_topology": "SINGLE_STEP"})

c.reject("the outline compiler (295-345: compiles a ship's outline into display instructions), the background starfield (464-521, 'Expensive Planetarium'), the display and console I/O, the random number routine (65-84), the divide subroutine (243-292)", reason="OTHER", evidence="NOT READ beyond comments; the display substrate and utilities", note="the outline compiler is a small code-generation mechanism of its own (it compiles data to code at run time)")
c.reject("'Spacewar' as one organ", reason="NAME_HAS_NO_EXECUTABLE_BOUNDARY", evidence="the entity tables, the frame loop and the physics are separable; hyperspace and gravity were added to the same loop by different people")

c.edge(frame, tables, "updates"); c.edge(tables, frame, "feeds"); c.edge(frame, phys, "feeds", note="calls each calc routine"); c.edge(phys, tables, "updates")

c.pressure("several_interacting_bodies_with_player_input_must_be_simulated_and_drawn_at_a_constant_rate_on_a_machine_whose_entire_instruction_budget_per_frame_is_known_and_small",
    condition="an organism updates and displays n moving objects, some created and destroyed at run time, within a fixed instruction budget per frame; velocities must mean the same thing whatever n is; behaviour differs per object kind", resource_or_constraint="the frame's instruction count; nnn object slots",
    failure_condition="frame time that varies with n (velocities change), or a dispatch cost that grows with the number of kinds", world_punishes="a type switch per object; variable frame time", world_rewards="a stored routine pointer per object and a burned remainder",
    observable_consequence="frame time vs number of active objects, and per-object dispatch cost vs number of kinds, on a PDP-1 emulator", vacuity_condition="one object kind and a fixed n", trivial_shortcuts="a faster machine (which changes the game's speed unless the budget is enforced)",
    cheat_control="an organism with unlimited instructions must show constant frame time at any n; the loop without the burn must show frame time falling as objects explode; a switch-based dispatch must show cost growing with kinds: the world must show all three",
    cost_class="CPU-scale", source_evidence="the main control routine 572-782; the object tables", purpose="PURPOSE: real-time two-player simulation (Russell, Graetz, Wiitanen, Samson, Edwards 1961-62)")

c.ancestry("shares_ancestor_with", "no software ancestor; the earliest entity-table game loop in the atlas", note="from the record; version 2B of 25 March 1962")
c.residue("LARGE_RESIDUE", ["instruction bodies unread (assembly read at comment level; the physics organ is CANDIDATE)", "the outline compiler and starfield unread", "nothing ran (needs a PDP-1 emulator, an M2 world)"], note="the two structural mechanisms (entity tables with routine pointers; the fixed-budget frame) are located from comments and labels, which the listing carries generously")
c.save(state="COARSE")
