"""Cut: spdylay (Tsujikawa's SPDY library; ancestry-aware, Stage A COARSE; SOURCE_READ on M3; position 71 of the 2026-09-17 NOT_CUT
order). Read: lib/spdylay_session.c add_frame 357-420 (priority assignment per frame type), the two outbound priority queues (202-206,
1025-1097), the window-update and flow-control function names (708, 1745-1877, 2359-2382); lib/spdylay_zlib.c 33-60, 229-240 (the
header-compression dictionaries). NOT read: the frame parser (spdylay_frame.c), the stream state machine (spdylay_stream.c), the
receive path (mem_recv 2474-2738), NPN, the tests. Nothing ran (C; needs zlib and OpenSSL; not on M3).
"""
from nyx.atlas.author import Cut

S = "vault:spdylay/upstream/tree/lib/spdylay_session.c"; Z = "vault:spdylay/upstream/tree/lib/spdylay_zlib.c"
c = Cut("spdylay", mode="ANCESTRY_AWARE", inspected=["lib/spdylay_session.c 99-110, 202-206, 357-420, 1025-1097 (structure), 1745-2382 (names)", "lib/spdylay_zlib.c 33-60, 229-240"], evidence=[("SOURCE_READ", S + ":357-420"), ("SOURCE_READ", S + ":1025-1097"), ("SOURCE_READ", Z + ":229-240")],
        note="the three SPDY ideas that HTTP/2 inherited, each visible as a data structure: streams multiplexed on one connection with a per-stream priority that orders a priority queue of outbound frames (control frames such as PING and SETTINGS jump the queue by fixed priorities; SYN_STREAMs keep insertion order at the lowest priority); header compression by deflate with a shared pre-seeded dictionary of common header names and values (one per protocol version); and per-stream plus per-connection flow-control windows updated by WINDOW_UPDATE frames")

pq = c.organ("outbound_frames_ordered_by_a_priority_queue_keyed_on_stream_priority_then_sequence_with_fixed_priorities_for_ping_and_settings_and_a_second_queue_for_stream_openings", human_name="spdylay_session_add_frame (357-420): item->seq, item->pri per frame type (PING SPDYLAY_OB_PRI_PING, SETTINGS -1, SYN_REPLY / RST_STREAM / HEADERS the stream's pri, SYN_STREAM lowest); ob_pq and ob_ss_pq (202-206); spdylay_outbound_item_compar (99); the pop logic 1025-1097", status="ACCEPTED",
    mechanism="every frame to send becomes an outbound item with a sequence number and a priority; the priority is the stream's for frames belonging to an open stream, a fixed high value for PING, a fixed value for SETTINGS, and the lowest for new SYN_STREAMs, which also go to a separate queue so that stream openings are sent in the order requested and never starve data; the sender pops the higher-priority head of the two queues (ties broken by sequence), so a client's priority hints translate directly into transmission order on the single TLS connection",
    input="frames from the application and the protocol", output="an ordered byte stream", state="two priority queues; next_seq", update="per frame", assumptions=["the application's priorities are meaningful; control frames must not wait behind data (a stalled PING would look like a dead connection)"],
    fitness_value_in_ancestor="head-of-line blocking of HTTP/1.1 removed without multiple connections; the priority model HTTP/2 refined into a dependency tree", failure_landscape="by reading: priorities are absolute integers, so a low-priority stream can starve indefinitely behind a busy high one (HTTP/2's weighted tree was the answer); the two-queue split is a workaround for SYN_STREAM ordering",
    human_prior="SPDY draft 2/3 (Google 2009-2012); RFC 7540 section 5.3 for the successor", evidence_ref=S + ":99-110, 202-206, 357-420, 1025-1097", confidence="HIGH", portability="YES", compatibility="UNKNOWN", utility="UNKNOWN", source_boundary="add_frame, the compare function and the pop path",
    coverage={"input_topology": "STREAM", "output_topology": "SEQUENCE", "state_amount": "LINEAR_IN_INPUT", "stochasticity": "DETERMINISTIC", "update_topology": "PRIORITY", "competition": "ARBITRATES"})

hd = c.organ("header_blocks_compressed_by_deflate_with_a_pre_seeded_shared_dictionary_of_common_header_names_and_values_per_protocol_version", human_name="spdylay_zlib.c: spdy2_hd_dict (33), spdy3_hd_dict (48), spdylay_select_hd_dict (229-240); deflate / inflate with SetDictionary", status="ACCEPTED",
    mechanism="each direction of a session keeps a zlib stream for header blocks; the stream is primed with a fixed dictionary containing the header names and values that appear in nearly every request (methods, status codes, common header names, dates), so even the first request's headers compress well; SPDY/2 and SPDY/3 have different dictionaries; the compressor state persists across frames, so repeated headers cost almost nothing",
    input="name/value header blocks", output="compressed bytes", state="the zlib streams (per direction)", update="per header block", assumptions=["headers are highly redundant across requests; a shared prefix dictionary fixes the cold-start cost"],
    fitness_value_in_ancestor="request headers shrink by most of their size; the mechanism HTTP/2 REPLACED (with HPACK) because compressing secrets alongside attacker-controlled bytes leaks them (CRIME, 2012)", failure_landscape="by reading: the compression context is shared across streams of one connection, which is exactly the CRIME side channel; the body predates the fix", human_prior="deflate with a preset dictionary (zlib's deflateSetDictionary)", evidence_ref=Z + ":33-60, 229-240", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="spdylay_zlib.c",
    coverage={"input_topology": "SEQUENCE", "output_topology": "SEQUENCE", "state_amount": "CONSTANT", "state_persistence": "PERSISTENT", "memory": "WINDOW", "stochasticity": "DETERMINISTIC"})

fc = c.organ("per_stream_and_per_connection_flow_control_windows_consumed_by_data_frames_and_replenished_by_window_update_frames", human_name="spdylay_session_on_window_update_received (1877), update_initial_window_size (1745), update_recv_window_size / recv_connection_window_size (2359-2382), predicate_window_update_send (708), add_window_update (2776)", status="CANDIDATE",
    mechanism="each stream carries a send window decremented by the data it sends and a receive window decremented by what it receives; the receiver sends WINDOW_UPDATE when its consumed bytes cross a threshold, and the sender may not send data beyond its window; SPDY/3 added a connection-level window over all streams; a SETTINGS change of the initial window size adjusts every open stream's window by the difference",
    input="DATA frames; WINDOW_UPDATE and SETTINGS frames", output="permission to send", state="window sizes per stream and per session", update="per frame", assumptions=["receiver-driven credit is the right control when many streams share one TCP connection (TCP's own window is per connection, so one slow consumer would stall all)"],
    fitness_value_in_ancestor="one stalled stream no longer blocks the others; the same design in HTTP/2 section 6.9", failure_landscape="UNKNOWN by run", evidence_ref=S + ":708, 1745-1877, 2359-2382, 2776 (names and signatures; bodies not read)", confidence="MEDIUM", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="the window functions; CANDIDATE because read by name",
    coverage={"input_topology": "EVENT", "output_topology": "DECISION", "state_amount": "LINEAR_IN_INPUT", "feedback": "CLOSED_LOOP", "stochasticity": "ENVIRONMENT_RANDOM", "update_topology": "EVENT_DRIVEN"})

c.reject("the frame encoder/decoder (spdylay_frame.c), the stream state machine (spdylay_stream.c), the receive path and its callbacks (mem_recv 2474-2738), NPN negotiation, the map / pq / buffer containers, the shrpx proxy and examples, the tests", reason="OTHER", evidence="NOT READ; residue")
c.reject("'SPDY' as one organ", reason="NAME_HAS_NO_EXECUTABLE_BOUNDARY", evidence="multiplexing with priorities, header compression and flow control are separable and HTTP/2 kept two, replaced one and refined the third")

c.edge(pq, fc, "gates", note="data frames wait for window"); c.edge(hd, pq, "feeds", note="compressed control frames enter the queue")

c.pressure("many_request_response_streams_must_share_one_ordered_connection_such_that_a_slow_or_blocked_stream_does_not_delay_the_others_and_headers_repeated_on_every_request_cost_almost_nothing",
    condition="an organism carries N concurrent request/response exchanges over one reliable ordered byte stream; consumers drain at different rates; each exchange carries hundreds of bytes of mostly repeated headers; the score is page-load latency and bytes on the wire", resource_or_constraint="one connection; a compression context per direction",
    failure_condition="head-of-line blocking (one slow stream delays the rest) or header bytes dominating small requests", world_punishes="one exchange at a time; per-request compression from a cold context", world_rewards="multiplexed frames with priorities, per-stream credit windows, a persistent compressor with a seeded dictionary",
    observable_consequence="page-load time and header bytes for a page of 50 resources over HTTP/1.1 (6 connections) vs SPDY over one connection, with one resource's consumer stalled", vacuity_condition="one resource per page", trivial_shortcuts="many parallel connections (which the world may cap, as browsers did)",
    cheat_control="an organism with unlimited connections must match SPDY's latency at higher connection count; serial HTTP/1.1 must show the head-of-line delay; SPDY with the dictionary removed must show the cold-start header cost: the world must show all three",
    cost_class="CPU-scale", source_evidence="spdylay_session.c add_frame and the queues; spdylay_zlib.c dictionaries; the window functions", purpose="PURPOSE: multiplexed HTTP transport (Google SPDY 2009; spdylay 2012-)")

c.ancestry("algorithm_from", "SPDY drafts 2 and 3 (Google); superseded by HTTP/2 (RFC 7540), whose reference library nghttp2 is this author's successor to this body", note="from the record")
c.residue("LARGE_RESIDUE", ["frame codec, stream states and the receive path unread", "flow control read by name (CANDIDATE)", "nothing ran"], note="the three inherited ideas are located as data structures; the record's point (SPDY as the basis of HTTP/2) is visible in them")
c.save(state="COARSE")
