"""Cut: spin-6.5.2-holzmann (SPIN model checker; ancestry-aware, Stage A COARSE; SOURCE_READ on M3; position 33 of the 2026-09-17
NOT_CUT order). Read, in Src/pangen1.h (the C text of the generated verifier pan.c, stored as string literals): new_state 2614-2780
(the DFS entry and the acceptance-cycle seed comparison), store_state 1380-1480 (BFS variant's store + counting), bstore_mod /
bstore_reg 880-960 (bitstate hashing), the NOREDUCE / SAFETY / BITSTATE conditional structure (grep). Src/pangen2.c proc_is_safe
2251-2330 (which statements are safe under partial-order reduction). NOT read: the Promela parser (spin.y, spinlex.c), the LTL
translator (tl_*.c), pangen2.c's code generation body, pangen6/7 (multi-core, SAFETY/BFS variants), the simulator (run.c, sched.c).
Nothing ran (C + yacc; no compiler on M3).
"""
from nyx.atlas.author import Cut

P1 = "vault:spin-6.5.2-holzmann/upstream/tree/Spin-version-6.5.2/Src/pangen1.h"; P2 = "vault:spin-6.5.2-holzmann/upstream/tree/Spin-version-6.5.2/Src/pangen2.c"
c = Cut("spin-6.5.2-holzmann", mode="ANCESTRY_AWARE", inspected=["Src/pangen1.h 2614-2780, 1380-1480, 880-960 + conditional structure", "Src/pangen2.c 2251-2330"],
        evidence=[("SOURCE_READ", P1 + ":2614-2780"), ("SOURCE_READ", P1 + ":1380-1480"), ("SOURCE_READ", P1 + ":880-960"), ("SOURCE_READ", P2 + ":2251-2330")],
        note="SPIN does not check the model: it GENERATES a C program (pan.c) whose text lives in pangen*.h as string arrays, and the compile-time flags of that program select the algorithm (full state hashing vs BITSTATE supertrace vs MA minimised automaton; SAFETY vs nested-DFS acceptance cycles; NOREDUCE vs partial-order reduction). The cut reads the generated text, so the organs are the verifier's, and the mechanism 'a verifier specialised per model at C-compile time' is the generator's")

gen = c.organ("verifier_generated_as_c_source_per_model_with_the_algorithm_chosen_by_preprocessor_flags", human_name="pangen1.h (the pan.c text as string literals); the BITSTATE / MA / SAFETY / NOREDUCE / BFS / NCORE conditionals inside it", status="ACCEPTED",
    mechanism="the Promela model is compiled into C data (transition tables trans[ot][tt], the state vector struct 'now', the process step functions) spliced into a fixed verifier skeleton; the skeleton carries every algorithm variant under #ifdef, so one C compilation of pan.c with -DBITSTATE or -DSAFETY or -DNOREDUCE fixes the search algorithm; the state vector is a flat byte array (vsize) compared and hashed as bytes",
    input="a Promela model", output="pan.c", state="none at generation", update="per model", assumptions=["specialising the checker to the model (state vector layout, transition tables as data) beats interpreting the model; the algorithm menu is small enough to live under preprocessor flags"],
    fitness_value_in_ancestor="the verifier is a tight C program with the model's state vector as a struct; the whole menu of algorithms ships as one text", failure_landscape="by reading: the skeleton is ~9,000 lines of C inside string literals with nested #ifdef; it is unreadable as a program and only testable as generated output", human_prior="compile-the-model checking (also in Murphi); SPIN's is the 1989 original",
    evidence_ref=P1 + ":1-100 (structure), 2603-2614 (the comment 'new_state() is the main DFS search routine in the verifier')", confidence="HIGH", portability="YES", compatibility="UNKNOWN", utility="UNKNOWN", source_boundary="the pangen*.h texts",
    coverage={"input_topology": "GRAPH", "output_topology": "SEQUENCE", "state_amount": "NONE", "stochasticity": "DETERMINISTIC", "representation_sensitivity": "SENSITIVE"})

dfs = c.organ("depth_first_search_over_a_flat_state_vector_with_a_visited_store_and_an_acceptance_cycle_check_by_seed_state_comparison", human_name="new_state (2614-2780): Down / AllOver / Up; the A_Root seed comparison; store_state (1380-1480) for the BFS variant", status="ACCEPTED",
    mechanism="the search stack is an array of Trail records (one per depth) holding the transition taken and a pointer to the stored predecessor; at each new depth the current state vector 'now' is offered to the store (h_store hash table, b_store bitstate, or g_store minimised automaton): a new state increments nstates and expands, a seen state increments truncs and backtracks; for liveness (not SAFETY) the search is nested: after an accepting state is found the second search sets bit _a_t and a later state equal to the seed A_Root (byte compare from offset S_A+2, skipping the fairness counters) is an acceptance cycle; depth limits, hash resize on nstates > 2^(ssize+1), and periodic snapshots are inline",
    input="the model's transitions", output="an error trail or a state count", state="the visited store; the trail stack (maxdepth records)", update="per state", assumptions=["the state vector as bytes is a canonical state identity (no symmetry reduction by default); a cycle through an accepting state is detectable by re-meeting the seed in the second search"],
    fitness_value_in_ancestor="on-the-fly verification: errors are found before the state space is complete; the nested DFS needs two bits per state, not a strongly-connected-components pass", failure_landscape="by reading: the state store is the limit (hence bitstate and MA); the depth-limit path prints 'max search depth too small' and counts truncs, so a bounded search silently loses states",
    human_prior="Courcoubetis, Vardi, Wolper, Yannakakis 1992 nested DFS; Holzmann's implementation", evidence_ref=P1 + ":2614-2780; 1444-1470", confidence="HIGH", portability="YES", compatibility="UNKNOWN", utility="UNKNOWN", source_boundary="new_state and the store calls",
    coverage={"input_topology": "GRAPH", "output_topology": "DECISION", "state_amount": "UNBOUNDED", "state_persistence": "PER_EPISODE", "memory": "FULL_HISTORY", "stochasticity": "DETERMINISTIC", "update_topology": "RECURSIVE", "resource_dependence": "MEMORY", "failure_mode": "DEGRADES"})

bit = c.organ("bitstate_supertrace_that_stores_each_state_as_hfns_bits_in_a_bit_array_accepting_false_positives_as_lost_coverage", human_name="bstore_reg / bstore_mod (880-960; 'extended hashing, Peter Dillinger, 2004'); d_hash / m_hash", status="ACCEPTED",
    mechanism="the state vector is hashed once to several words; hfns bit positions are derived by stepping x by j1+i (masked to the array) and y by j4 (mod 8); if every bit is already set the state is 'old' (possibly falsely) and the search backtracks; otherwise all hfns bits are set and the state is 'new'; an optional RANDSTOR makes storing probabilistic; the array size is the memory budget, and the search is therefore a lossy exploration whose coverage the tool estimates afterwards",
    input="a state vector", output="old / new", state="the bit array (udmem or 2^ssize bits)", update="per state", assumptions=["a hash collision costs a missed state, never a false error; for large models a partial search with a known-coverage bound is better than no search"],
    fitness_value_in_ancestor="verification of models whose state space does not fit memory, with a coverage estimate", failure_landscape="by reading: coverage degrades as the array fills; hfns (default 3) trades collisions against bits per state; Dillinger's double hashing replaced the 5.1.1 scheme", human_prior="Holzmann's supertrace (1987) is the origin; Bloom filters are the general form",
    evidence_ref=P1 + ":880-960", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="the two bstore functions",
    coverage={"input_topology": "VECTOR", "output_topology": "DECISION", "state_amount": "CONSTANT", "memory": "SUMMARY_STATISTIC", "stochasticity": "SEEDED_RANDOM", "failure_mode": "DEGRADES", "resource_dependence": "MEMORY"})

por = c.organ("partial_order_reduction_by_statically_classifying_statements_as_safe_and_expanding_only_a_safe_process_when_one_exists", human_name="pangen2.c proc_is_safe (2251-2330) and the 'conditionally safe' comments (816-823, 1122-1123); the NOREDUCE-guarded blocks in pangen1.h (1453, 1537-1613, 2909-2960)", status="CANDIDATE",
    mechanism="at generation time each statement is classified: local assignments and local-variable tests are safe; sends and receives on channels declared exclusive (xs/xr) are conditionally safe; anything touching global state is unsafe; the generated DFS, when a process's next statement is safe, expands only that process's moves at this state (a single-successor ample set) and records a proviso bit so that a reduced state closing a cycle on the stack is re-expanded; violations of the xr/xs declarations at run time abort with 'violates po reduction'",
    input="the model's statements and channel declarations", output="a reduced successor set per state", state="the proviso bits in the store", update="per state", assumptions=["independence of local statements is decidable syntactically; the cycle proviso restores completeness"],
    fitness_value_in_ancestor="exponential reduction of interleavings on models with local computation", failure_landscape="UNKNOWN by run (the reduction's soundness depends on the user's xr/xs declarations, which the run-time check partially polices)", human_prior="Holzmann & Peled 1994 (static POR); Godefroid's persistent sets",
    evidence_ref=P2 + ":2251-2330; " + P1 + ":1453-1613 (guards read, bodies skimmed)", confidence="MEDIUM", portability="YES", compatibility="UNKNOWN", utility="UNKNOWN", source_boundary="the safety classification and the NOREDUCE blocks; CANDIDATE because the ample-set expansion body was skimmed, not read",
    coverage={"input_topology": "GRAPH", "output_topology": "SET", "state_amount": "CONSTANT", "stochasticity": "DETERMINISTIC", "order_sensitivity": "PARTIALLY"})

c.reject("the Promela front end (spin.y, spinlex.c, sym.c, structs.c, vars.c), the simulator (run.c, sched.c, dstep.c), guided/replay, the MSC/Tcl GUI", reason="OTHER", evidence="NOT READ; residue")
c.reject("the LTL-to-Buchi translator (tl_*.c, ~5,000 lines)", reason="OTHER", evidence="NOT READ", note="a distinct mechanism family (Gerth-Peled-Vardi-Wolper 1995 on-the-fly tableau); should be its own specimen or a DEEP pass")
c.reject("the minimised-automaton store (MA), multi-core (NCORE > 1, pangen6/7), the BFS and swarm variants, hash-compact", reason="OTHER", evidence="guards seen in pangen1.h; bodies NOT READ")
c.reject("'model checker' as one organ", reason="NAME_HAS_NO_EXECUTABLE_BOUNDARY", evidence="generation, search, store and reduction are separable and separately flagged in the generated text")

c.edge(gen, dfs, "feeds", note="the generated text IS the DFS"); c.edge(bit, dfs, "gates", note="old/new"); c.edge(por, dfs, "gates", note="successor set")

c.pressure("a_reachability_or_cycle_question_over_an_exponential_interleaving_space_must_be_answered_within_fixed_memory_with_a_known_loss_of_completeness",
    condition="an organism explores a product of asynchronous processes; the number of interleavings is exponential; memory is fixed; the score is errors found and (when none) the fraction of the space covered", resource_or_constraint="the state store's memory; time",
    failure_condition="a reachable error missed, or memory exhausted before the question is answered", world_punishes="exploring every interleaving; storing every state fully", world_rewards="independence-based pruning (POR), lossy stores with coverage estimates (bitstate), on-the-fly cycle detection",
    observable_consequence="states stored and errors found vs memory budget on a family of models with a planted error at increasing depth; coverage estimate vs true coverage under bitstate", vacuity_condition="a single sequential process", trivial_shortcuts="a model small enough to store completely",
    cheat_control="an organism given the interleaving-independence oracle (the POR classification) must find the planted error with the fewest states; the full-store organism must exhaust memory on the largest family member; a bitstate organism must report a coverage estimate that brackets the truth: the world must show all three",
    cost_class="CPU-scale", source_evidence="pangen1.h new_state / bstore; pangen2.c proc_is_safe", purpose="PURPOSE: protocol verification (SPIN, Holzmann 1989-)")

c.ancestry("derived_from", "Holzmann's earlier Pan / supertrace (1980s); nested DFS from Courcoubetis et al. 1992; static POR Holzmann-Peled 1994; bitstate hashing revised by Dillinger 2004", note="from the source comments and the record")
c.residue("LARGE_RESIDUE", ["the front end, simulator and LTL translator unread", "MA / multi-core / BFS / swarm variants unread", "the generated text was read as a program with its variants collapsed; nothing ran"], note="the four mechanisms that define the tool are located in the generated text; the tool itself (generation) is the fifth")
c.save(state="COARSE")
