"""Cut: tinyscheme-1.42 (TinyScheme, from Moriwaki's MiniScheme; ancestry-aware, Stage A COARSE; SOURCE_READ on M3; position 89 of the
2026-09-17 NOT_CUT order). Read: scheme.c OP_EVAL / OP_E0ARGS / OP_APPLY dispatch 2568-2720 (the eval/apply loop), the dump-stack frame
and s_save / _s_return 2362-2410, gc 1251-1300 (mark-and-sweep). NOT read: the reader, the ~200 other opcodes (opdefines.h), the numeric
tower, call/cc's continuation capture in full, dynload, init.scm. Nothing ran (C; no compiler on M3). The atlas's femtolisp and
lisp-1-5 cuts are the family.
"""
from nyx.atlas.author import Cut

S = "vault:tinyscheme-1.42/upstream/tree/tinyscheme-1.42/scheme.c"
c = Cut("tinyscheme-1.42", mode="ANCESTRY_AWARE", inspected=["scheme.c 2362-2410, 2568-2720, 1251-1300"], evidence=[("SOURCE_READ", S + ":2568-2720"), ("SOURCE_READ", S + ":2362-2410"), ("SOURCE_READ", S + ":1251-1300")],
        note="a Scheme interpreter as a single dispatch loop over opcodes with an explicit continuation stack instead of C recursion: eval either looks a symbol up, dispatches a syntax form, or saves a frame and evaluates the operator then the arguments; apply binds a closure's parameters in a new environment and jumps to the body; the continuation is a heap 'dump' stack of (op, args, code, env) frames, so tail calls do not grow the C stack and call/cc is a copy of that stack; a mark-and-sweep collector reclaims cons cells, rebuilding a sorted free list")

loop = c.organ("eval_apply_as_a_single_dispatch_loop_where_evaluation_saves_continuation_frames_and_jumps_by_opcode_rather_than_recursing_in_c", human_name="OP_EVAL (2568-2599): symbol lookup, syntax dispatch, else s_save(OP_E0ARGS) and eval the operator; OP_APPLY (2640-2708): foreign call, or bind closure params in new_frame_in_env and s_goto(OP_BEGIN), or restore a continuation's dump; s_goto / s_return macros", status="ACCEPTED",
    mechanism="the interpreter is a loop that reads the current opcode and branches; OP_EVAL resolves a symbol from the environment, or if the form is a pair dispatches on a syntactic keyword or saves an OP_E0ARGS continuation and recurses (via the loop, not C) into the operator; OP_APPLY, once the operator and arguments are values, either calls a built-in, or extends the closure's captured environment with the bound parameters and jumps to its body via OP_BEGIN, or (for a captured continuation) replaces the dump stack; s_goto sets the next opcode and s_return pops a frame, so control flow is data",
    input="an expression and an environment", output="a value", state="the registers (code, args, envir, value) and the dump stack", update="per opcode", assumptions=["representing the continuation explicitly on the heap makes proper tail calls and call/cc natural and bounds the C stack (the trampoline / CPS-by-hand technique)"],
    fitness_value_in_ancestor="a full R5RS-ish Scheme with tail calls and first-class continuations in one C file", failure_landscape="by reading: every intermediate value must be reachable from the registers or the dump or the GC frees it (the push_recent_alloc guard around foreign calls exists for this)", human_prior="the SICP metacircular evaluator made iterative; MiniScheme (Moriwaki 1989)", evidence_ref=S + ":2568-2720", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="the opexe dispatch for eval/apply",
    coverage={"input_topology": "TREE", "output_topology": "MIXED", "state_amount": "LINEAR_IN_INPUT", "state_persistence": "PER_EPISODE", "stochasticity": "DETERMINISTIC", "update_topology": "RECURSIVE"})

dump = c.organ("continuation_as_a_heap_dump_stack_of_op_args_code_env_frames_so_tail_calls_reuse_the_stack_and_call_cc_copies_it", human_name="struct dump_stack_frame (2362); s_save (2371-2389) pushes a frame; _s_return (2391-2408) pops; dump_stack_reset / initialize / free (2410-2423); OP_APPLY's continuation branch sets sc->dump = cont_dump(code)", status="ACCEPTED",
    mechanism="the return continuation is an array of frames each holding the opcode to resume, the pending args, the code and the environment; a non-tail subexpression pushes a frame before recursing and pops it on return; a tail call pushes nothing, so iteration in constant space falls out; call/cc captures the current dump array as a first-class object and invoking a continuation restores it, making non-local control a stack swap",
    input="control-flow points", output="saved/restored continuations", state="the dump array", update="per save/return", assumptions=["a reified continuation stack is cheaper and more general than C recursion; copying it for call/cc is acceptable at Scheme scale"],
    fitness_value_in_ancestor="proper tail calls and call/cc, the two features that distinguish Scheme from a toy Lisp", failure_landscape="UNKNOWN by run", human_prior="continuation-passing made concrete; the dump register of the SECD machine", evidence_ref=S + ":2362-2423", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="the dump-stack functions",
    coverage={"input_topology": "EVENT", "output_topology": "EVENT", "state_amount": "LINEAR_IN_INPUT", "state_persistence": "PER_EPISODE", "stochasticity": "DETERMINISTIC", "update_topology": "RECURSIVE", "recovery": "ROLLS_BACK"})

c.reject("gc (mark-and-sweep from the registers, dump and oblist, rebuilding a sorted free list: 1251-1300) as a separate organ", reason="BELOW_MEANINGFUL_GRAIN", evidence=S + ":1251-1300", note="a textbook mark-sweep; the sorted free list (for vector allocation) is its one wrinkle; counted here, not split out, per the directive's no-deepening line")
c.reject("the s-expression reader, the ~200 opcodes in opdefines.h, the numeric tower, ports and I/O, dynload, init.scm, the FFI", reason="OTHER", evidence="NOT READ; residue")
c.reject("'Scheme interpreter' as one organ", reason="NAME_HAS_NO_EXECUTABLE_BOUNDARY", evidence="the dispatch loop and the reified continuation are separable; the atlas's femtolisp compiles to bytecode instead of dispatching over s-expressions")

c.edge(loop, dump, "feeds", note="eval saves frames"); c.edge(dump, loop, "feeds", note="return resumes an opcode")

c.pressure("a_lexically_scoped_functional_language_with_proper_tail_calls_and_first_class_continuations_must_be_interpreted_in_bounded_c_stack_from_one_small_file",
    condition="an organism interprets a language whose programs recurse deeply and use tail recursion for iteration and call/cc for non-local control; the score is correct tail-call space behaviour, working call/cc, and code size", resource_or_constraint="the C stack (must not grow on tail calls); one file",
    failure_condition="C-stack overflow on a tail-recursive loop, or call/cc that cannot re-enter a past control point", world_punishes="a C-recursive evaluator (grows the stack); a language without reified continuations", world_rewards="an iterative dispatch loop with a heap continuation stack",
    observable_consequence="C-stack depth on a million-iteration named-let loop, and the behaviour of a generator built from call/cc, for the dispatch-loop interpreter vs a C-recursive one", vacuity_condition="programs without recursion or continuations", trivial_shortcuts="a host language with tail calls and continuations (which C is not)",
    cheat_control="an organism given a host with proper tail calls must show constant stack; a C-recursive Scheme must overflow on the loop; call/cc removed must fail the generator: the world must show all three", cost_class="CPU-scale",
    source_evidence="scheme.c eval/apply loop; the dump stack", purpose="PURPOSE: a small embeddable Scheme (Moriwaki 1989; Shapiro et al. 2000-)")

c.ancestry("derived_from", "MiniScheme (Moriwaki 1989); the SICP metacircular evaluator and the SECD machine; the atlas's femtolisp (bytecode) and lisp-1-5 (the origin) are the family", note="from the README and the record")
c.residue("LARGE_RESIDUE", ["the reader, most opcodes, the numeric tower and call/cc capture-in-full unread", "gc folded into a reject", "nothing ran"], note="the two mechanisms that make it Scheme rather than Lisp are located")
c.save(state="COARSE")
