"""Cut: umdhmm-kanungo-1.02 (Kanungo's UMDHMM, Rabiner's HMM algorithms in C; ancestry-aware, Stage A DEEP; SOURCE_READ on M3;
position 54 of the 2026-09-17 NOT_CUT order). Read: baum.c in full (176 lines: BaumWelch, ComputeGamma, ComputeXi), viterbi.c
(Viterbi, ViterbiLog), forward.c (the scaling lines), esthmm.c (the driver: seed, init, DELTA). NOT read: backward.c, hmmutils.c
(I/O), genseq.c, nrutil.c, sequence.c. Nothing ran (C; no compiler on M3).
"""
from nyx.atlas.author import Cut

B = "vault:umdhmm-kanungo-1.02/upstream/tree/baum.c"; V = "vault:umdhmm-kanungo-1.02/upstream/tree/viterbi.c"; F = "vault:umdhmm-kanungo-1.02/upstream/tree/forward.c"; E = "vault:umdhmm-kanungo-1.02/upstream/tree/esthmm.c"
c = Cut("umdhmm-kanungo-1.02", mode="ANCESTRY_AWARE", inspected=["baum.c 1-176", "viterbi.c 1-144", "forward.c 50-90", "esthmm.c 25-160"], evidence=[("SOURCE_READ", B + ":1-176"), ("SOURCE_READ", V + ":1-144"), ("SOURCE_READ", F + ":50-90"), ("SOURCE_READ", E + ":25-160")],
        note="the three HMM algorithms of Rabiner's tutorial in their plainest form: forward/backward with per-step scaling (so the log-likelihood is a sum of log scale factors), Baum-Welch re-estimation from gamma and xi with a floor of 0.001 on every re-estimated probability, iterated until the log-likelihood gain is below 0.001, and Viterbi in both product and log forms")

scale = c.organ("forward_backward_with_per_step_scaling_so_the_log_likelihood_is_the_sum_of_log_scale_factors", human_name="ForwardWithScale (forward.c 50-90): scale[t] = sum_i alpha[t][i]; alpha /= scale[t]; logprob = sum log scale[t]; BackwardWithScale uses the same scale", status="ACCEPTED",
    mechanism="at each time step the forward variables are normalised to sum to one and the normaliser is stored; the backward pass divides by the same normalisers so gamma and xi come out correctly without underflow; the log-likelihood of the sequence is the sum of the logs of the normalisers",
    input="an HMM (pi, A, B) and an observation sequence", output="scaled alpha, beta, scale[], log P(O | model)", state="none", update="per sequence", assumptions=["unscaled alphas underflow after a few hundred steps in double precision; scaling by the column sum keeps every quantity O(1) (Rabiner 1989 section V.A)"],
    fitness_value_in_ancestor="sequences of any length; the likelihood in log space for free", failure_landscape="UNKNOWN by run", human_prior="Rabiner 1989; Levinson, Rabiner & Sondhi 1983 for the scaling", evidence_ref=F + ":50-90", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="the two *WithScale functions",
    coverage={"input_topology": "SEQUENCE", "output_topology": "MATRIX", "state_amount": "LINEAR_IN_INPUT", "stochasticity": "DETERMINISTIC", "update_topology": "SWEEP", "failure_mode": "NONE_KNOWN"})

bw = c.organ("baum_welch_re_estimation_from_gamma_and_xi_with_a_0_001_floor_on_every_probability_iterated_until_the_log_likelihood_gain_is_below_0_001", human_name="BaumWelch (baum.c 24-88): pi = .001 + .999 gamma[1]; A[i][j] = .001 + .999 sum xi / sum gamma; B[i][k] = .001 + .999 (sum gamma where O = k) / sum gamma; do ... while (delta > DELTA), DELTA 0.001; ComputeGamma / ComputeXi (89-140)", status="ACCEPTED",
    mechanism="from the scaled forward/backward pass compute gamma (state posterior per step) and xi (transition posterior per step); re-estimate the initial distribution, transitions and emissions as expected counts over expected occupancies; every re-estimated probability is a convex mix of the estimate (0.999) and a floor (0.001) so nothing becomes exactly zero; repeat while the log-likelihood improves by more than 0.001 nats; the initial model is random (InitHMM with a seed) or read from a file",
    input="O, an initial model", output="a model and the initial and final log-likelihoods", state="the model; logprobprev", update="per EM iteration", assumptions=["EM increases the likelihood monotonically (Baum et al. 1970); the floor prevents the well-known collapse where a zero probability can never recover"],
    fitness_value_in_ancestor="the reference re-estimator that toolkits cite; the floor is the implementation's practical addition", failure_landscape="by reading: a single observation sequence only (no multiple-sequence training); the stopping rule is an absolute gain, not relative; local optima depend on the seed (the driver exposes the seed for that reason)",
    human_prior="Baum et al. 1970; Rabiner 1989 equations 40a-c", evidence_ref=B + ":24-140", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="baum.c",
    coverage={"input_topology": "SEQUENCE", "output_topology": "MATRIX", "state_amount": "CONSTANT", "feedback": "CLOSED_LOOP", "stochasticity": "SEEDED_RANDOM", "update_topology": "RECURSIVE", "failure_mode": "STALLS"})

vit = c.organ("viterbi_decoding_in_product_and_log_forms_with_backpointers_and_a_huge_negative_sentinel", human_name="Viterbi (viterbi.c 20-72): delta[t][j] = max_i delta[t-1][i] A[i][j] times B[j][O[t]]; psi; backtrack q[t] = psi[t+1][q[t+1]]; ViterbiLog (73-144): the same over log pi, log A, log B[i][O[t]] precomputed as biot, with -VITHUGE (1e11) as minus infinity", status="ACCEPTED",
    mechanism="dynamic programme over states: the best-path score to each state at t is the max over predecessors of the previous score times the transition, times the emission; the argmax is stored; the best final state is found and the path read back through the pointers; the log form replaces products by sums and precomputes the emission logs per step to avoid repeated log calls; a large negative constant stands in for log 0",
    input="a model and O", output="the most likely state sequence and its (log) probability", state="delta, psi (T x N)", update="per sequence", assumptions=["the log form is needed for the same underflow reason as scaling; the product form is kept for short sequences"],
    fitness_value_in_ancestor="decoding in O(T N^2)", failure_landscape="by reading: the log form takes log of zero-probability entries without a guard (log(0) = -inf in C, which happens to work), and the sentinel 1e11 is finite", human_prior="Viterbi 1967; Forney 1973; Rabiner 1989", evidence_ref=V + ":20-144", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="viterbi.c",
    coverage={"input_topology": "SEQUENCE", "output_topology": "SEQUENCE", "state_amount": "LINEAR_IN_INPUT", "stochasticity": "DETERMINISTIC", "update_topology": "SWEEP"})

c.reject("hmmutils.c (reading and printing models), sequence.c, genseq.c (sampling a sequence from a model), nrutil.c (Numerical Recipes allocation), backward.c (the mirror of forward.c), the test drivers", reason="GENERIC_LANGUAGE_MECHANICS", evidence="NOT READ in full; I/O and allocation", note="genseq is the natural cheat-control generator for a Stage C world (sample from a known model, re-estimate, compare)")
c.reject("'HMM' as one organ", reason="NAME_HAS_NO_EXECUTABLE_BOUNDARY", evidence="scaling, re-estimation and decoding are three files with three separable algorithms; the atlas's viterbi-hmm-xukmin turned out to hold only a convolutional decoder, so this is the atlas's first true Viterbi-over-HMM")

c.edge(scale, bw, "feeds"); c.edge(bw, scale, "feeds", note="the re-estimated model"); c.edge(scale, vit, "competes", note="posterior vs best path")

c.pressure("a_hidden_markov_model_must_be_learned_from_one_long_observation_sequence_and_decoded_without_underflow_when_zero_probabilities_are_absorbing_and_the_likelihood_surface_has_local_optima",
    condition="an organism sees a discrete observation sequence generated by an unknown HMM with N states and M symbols; it must estimate the model and decode states; sequences are long (thousands of steps); the score is held-out log-likelihood and decoding accuracy against the generating model", resource_or_constraint="O(T N^2) per iteration; double precision",
    failure_condition="underflow to zero likelihood, a parameter stuck at exactly zero, or convergence to a poor local optimum", world_punishes="unscaled recursions; unfloored re-estimation; a single random start", world_rewards="scaling, a probability floor, restarts over seeds",
    observable_consequence="held-out log-likelihood and state accuracy vs T for scaled vs unscaled recursions, and the fraction of seeds reaching within 1 percent of the generating model's likelihood with and without the floor", vacuity_condition="a one-state model", trivial_shortcuts="the generating model as the initial model (which the cheat control uses)",
    cheat_control="an organism initialised at the generating model must not move (one iteration, gain below DELTA); the unscaled recursion must return zero likelihood past a few hundred steps; the unfloored re-estimator must lock a zero on a sequence missing one symbol: the world must show all three",
    cost_class="CPU-scale", source_evidence="baum.c; forward.c scaling; esthmm.c seed handling; genseq.c as generator", purpose="PURPOSE: HMM estimation and decoding (Kanungo 1998 after Rabiner 1989)")

c.ancestry("algorithm_from", "Baum et al. 1970; Viterbi 1967; Rabiner 1989 (the tutorial this code implements section by section)", note="from the source headers and the record")
c.residue("EXPLAINED_BY_CURRENT_CUT", ["backward.c and the I/O unread (mirrors and plumbing)", "nothing ran; the body ships test models and sequences (test.hmm, t2.*.seq) as an oracle"], note="a small body fully accounted for; the record's 'complements the vault's viterbi-hmm-xukmin' is corrected: that body is a convolutional decoder, this one is the HMM")
c.save(state="DEEP")
