"""Cut: verilog-generic-fifo (Rudolf Usselmann's OpenCores generic FIFOs: dual-clock, dual-clock gray, single-clock a/b, LFSR-addressed;
ancestry-aware, Stage A DEEP on the dual-clock core; SOURCE_READ on M3; position 70 of the 2026-09-17 NOT_CUT order). Read: rtl/verilog/
generic_fifo_dc.v in full (281 lines: the header's interface and timing notes, pointers, synchronisers, flags, thresholds, the
overrun/underrun error flags). NOT read: generic_fifo_dc_gray.v (the gray-coded pointer variant, 324 lines), the single-clock variants,
generic_fifo_lfsr.v and lfsr.v, the testbench. Nothing ran (no Verilog simulator on M3).
"""
from nyx.atlas.author import Cut

F = "vault:verilog-generic-fifo/upstream/tree/rtl/verilog/generic_fifo_dc.v"
c = Cut("verilog-generic-fifo", mode="ANCESTRY_AWARE", inspected=["rtl/verilog/generic_fifo_dc.v 1-281"], evidence=[("SOURCE_READ", F + ":1-281")],
        note="a first-in-first-out buffer between two clock domains: write and read pointers one bit wider than the address so that full and empty are distinguished by the extra bit when the address parts are equal; each pointer is sampled into the other clock domain through one register stage; the flags are computed in the domain that uses them from the local pointer and the sampled foreign pointer, with a one-entry look-ahead so a flag is correct on the very cycle it matters; threshold flags (full_n, empty_n) come from a registered pointer difference; the header states the two-cycle status latency and that a binary pointer crossing is only safe with the gray-coded variant, which is a separate file")

ptr = c.organ("pointers_one_bit_wider_than_the_address_so_that_full_and_empty_are_told_apart_by_the_wrap_bit_when_the_addresses_coincide", human_name="reg [aw:0] wp, rp (68-70); wp_pl1 / rp_pl1; empty <= (wp_s == rp) | (re & (wp_s == rp_pl1)) (109); full <= (wp[aw-1:0] == rp_s[aw-1:0]) & (wp[aw] != rp_s[aw]) | ... (111)", status="ACCEPTED",
    mechanism="the write and read pointers count modulo twice the depth; the low bits address the memory and the top bit records the wrap parity; the FIFO is empty when the pointers are equal in full and full when the address bits are equal but the wrap bits differ; each flag also looks one operation ahead (the pointer plus one under a read or write enable) so that it asserts on the cycle the last entry is consumed or the last slot filled, avoiding a cycle of illegal access",
    input="we, re", output="full, empty", state="wp, rp", update="per clock in each domain", assumptions=["one extra bit is cheaper than a separate count register or a 'last operation' flag; the look-ahead term costs one adder per flag"],
    fitness_value_in_ancestor="the standard flag discipline of every hardware FIFO", failure_landscape="by reading: the header warns that writing when full or reading when empty puts the FIFO in an undefined state; the design detects it after the fact (the overrun/underrun bits at 128-133) rather than preventing it", human_prior="Cummings & Alfke 2002 (simulation and synthesis techniques for asynchronous FIFO design)", evidence_ref=F + ":68-113", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="the pointer and flag lines",
    coverage={"input_topology": "EVENT", "output_topology": "DECISION", "state_amount": "LOG", "state_persistence": "PERSISTENT", "stochasticity": "DETERMINISTIC", "update_topology": "EVENT_DRIVEN"})

sync = c.organ("each_pointer_sampled_into_the_other_clock_domain_through_a_register_with_the_flags_computed_in_the_consuming_domain_from_the_local_pointer_and_the_sampled_foreign_one", human_name="always @(posedge rd_clk) wp_s <= wp; always @(posedge wr_clk) rp_s <= rp (106-107); empty in rd_clk from wp_s and rp; full in wr_clk from wp and rp_s; the header: 'there is a 2 cycle' latency; DC_FIFO_ASYNC_RESET", status="ACCEPTED",
    mechanism="the write pointer is registered on the read clock and the read pointer on the write clock; each domain computes its own flag from its own pointer (exact) and the sampled other pointer (stale by up to two cycles); staleness is safe in one direction only: a stale foreign pointer can make empty or full assert late-to-clear but never assert false-negative in the dangerous direction, so the FIFO is conservative rather than wrong; the header notes a binary multi-bit pointer can be sampled inconsistently and points to the gray-coded file for that case",
    input="the foreign pointer", output="a domain-local copy", state="wp_s, rp_s", update="per clock", assumptions=["metastability on a multi-bit binary bus is the user's risk here (the gray variant exists for it); the conservative direction of staleness is what makes a stale flag acceptable"],
    fitness_value_in_ancestor="two clock domains decoupled with two registers and no handshake", failure_landscape="by reading: a single register stage is not a two-flop synchroniser; a binary pointer sampled mid-transition can read an intermediate value (the reason the gray file exists)", human_prior="Cummings' async FIFO papers; the gray-code pointer is the standard remedy", evidence_ref=F + ":92-111, 27-30", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="the two sampling registers and the flag domains",
    coverage={"input_topology": "VECTOR", "output_topology": "VECTOR", "state_amount": "CONSTANT", "stochasticity": "ENVIRONMENT_RANDOM", "update_topology": "EVENT_DRIVEN", "failure_mode": "CORRUPTS"})

thr = c.organ("threshold_and_level_flags_from_a_registered_pointer_difference_with_look_ahead_on_the_enable", human_name="assign diff = wp - rp (113); diff_r1 / diff_r2 registered per domain; empty_n <= (diff_r1 < n) | ((diff_r1 == n) & (re | re_r)) (119); full_n <= (diff_r2 > max_size - n) | ((diff_r2 == max_size - n) & (we | we_r)) (125); level (two bits of occupancy quarter)", status="ACCEPTED",
    mechanism="the occupancy is the pointer difference (correct modulo the wrap thanks to the wide pointers); it is registered in each domain and compared with a threshold n to produce 'at least n entries' and 'room for n more', with the same one-operation look-ahead on the enable (and its registered copy) so the flag tracks the boundary exactly; a two-bit level output reports the occupancy quarter",
    input="the pointers, n", output="empty_n, full_n, level", state="diff_r1, diff_r2, re_r, we_r", update="per clock", assumptions=["consumers want to batch transfers (start when n are available) rather than react to every entry"],
    fitness_value_in_ancestor="burst-friendly flow control from the same pointers", failure_landscape="by reading: the difference uses a foreign pointer that is itself stale, so thresholds inherit the latency", evidence_ref=F + ":113-127", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="the diff and threshold lines",
    coverage={"input_topology": "VECTOR", "output_topology": "DECISION", "state_amount": "CONSTANT", "stochasticity": "DETERMINISTIC", "update_topology": "EVENT_DRIVEN"})

c.reject("generic_fifo_dc_gray.v (the gray-coded pointer crossing), the single-clock variants (sc_a, sc_b), generic_fifo_lfsr.v and lfsr.v (an LFSR as the address counter to save an incrementer), the memory macro instance, the testbench", reason="OTHER", evidence="NOT READ; residue", note="the gray variant is the safe form of organ 2 and should be read next; the LFSR addressing is a small mechanism of its own")
c.reject("'FIFO' as one organ", reason="NAME_HAS_NO_EXECUTABLE_BOUNDARY", evidence="pointer encoding, domain crossing and threshold logic are separable and the file set varies them independently")

c.edge(ptr, sync, "feeds"); c.edge(sync, ptr, "feeds", note="the sampled pointer enters the flag"); c.edge(ptr, thr, "feeds")

c.pressure("data_must_cross_between_two_unrelated_clocks_without_loss_or_duplication_with_flow_control_that_stalls_the_producer_and_starves_the_consumer_correctly_even_though_every_status_signal_is_stale_by_up_to_two_cycles",
    condition="a producer and a consumer run on independent clocks; a bounded buffer sits between them; the score is zero lost or duplicated words under every rate ratio, and throughput; status signals crossing domains are delayed and may be sampled mid-transition", resource_or_constraint="one memory; a few registers per domain",
    failure_condition="a write when full or a read when empty (corruption), or a false full/empty that halves throughput", world_punishes="flags computed from a foreign pointer without the wrap bit; binary pointers sampled across domains at speed", world_rewards="wide pointers, domain-local flags with conservative staleness, gray-coded crossing",
    observable_consequence="lost/duplicated words and throughput over rate ratios and clock phases in simulation, for the binary-pointer file vs the gray-pointer file, with metastability injected at the crossing", vacuity_condition="one clock", trivial_shortcuts="a handshake per word (correct, slow)",
    cheat_control="an organism with a global clock must show zero errors at full throughput; the binary-pointer FIFO with injected mid-transition samples must corrupt; the gray-pointer FIFO under the same injection must not: the world must show all three",
    cost_class="CPU-scale", source_evidence="generic_fifo_dc.v 68-133 and its header notes", purpose="PURPOSE: clock-domain-crossing buffer (Usselmann 2000-2002)")

c.ancestry("reimplementation_of", "the asynchronous FIFO design pattern (Cummings & Alfke 2002 as the canonical description); OpenCores generic FIFO collection", note="from the record and the header")
c.residue("PARTIALLY_EXPLAINED", ["the gray-coded, single-clock and LFSR variants unread", "nothing ran (a simulator would run the testbench; an M2 world with iverilog)"], note="the dual-clock core is fully read; its three mechanisms and its known hazard are located")
c.save(state="DEEP")
