"""Cut: walksat-v56 (Kautz's WalkSAT, the Walksat_v53 source in the v56 tree; ancestry-aware, Stage A DEEP; SOURCE_READ on M3; position
72 of the 2026-09-17 NOT_CUT order). Read: walksat.c the heuristic table 358-372, flipatom 463-610 (the incremental break/make counts),
pickbest 1666-1691, picknovelty 1918-1965, the adaptive-noise options 214-218 / 723-734. NOT read: pickrnovelty, picktabu, pickgsat,
the freebie list, the hamming-distance instrumentation, the other programs in the tree. Nothing ran (C; no compiler on M3).
"""
from nyx.atlas.author import Cut

W = "vault:walksat-v56/upstream/tree/Walksat-master/Walksat_v53/walksat.c"
c = Cut("walksat-v56", mode="ANCESTRY_AWARE", inspected=["walksat.c 358-372, 463-610, 1666-1691, 1918-1965, 214-218, 723-734"], evidence=[("SOURCE_READ", W + ":463-610"), ("SOURCE_READ", W + ":1666-1691"), ("SOURCE_READ", W + ":1918-1965")],
        note="stochastic local search for SAT as three mechanisms: pick an unsatisfied clause at random and flip one of its variables; choose the variable by a heuristic over two incrementally maintained counts per variable (how many clauses a flip would break, how many it would make), with a noise probability of a random choice; and keep the counts exact after every flip by touching only the clauses containing the flipped variable. Novelty adds a tie-break on the variable's age so the search does not undo its last move")

inc = c.organ("break_and_make_counts_per_variable_kept_exact_by_updating_only_the_clauses_containing_the_flipped_variable", human_name="flipatom (463-610): breakcount[] and makecount[] (166-167); for each clause of the flipped literal: a clause going true or false, or changing its number of true literals, adjusts the counts of the variables involved; the freebie list of variables with breakcount 0 and makecount > 0", status="ACCEPTED",
    mechanism="each clause knows how many of its literals are true and which one is the sole true literal when that number is one; flipping a variable walks its occurrence lists: a clause that becomes false increments the makecount of all its variables and removes the flipped one from breakcounts; a clause that goes from one true literal to two releases the break responsibility of the previously critical variable; a clause that goes from two to one makes the remaining true variable critical (its breakcount rises); variables with zero break and positive make are kept on a 'freebie' list because flipping them is always an improvement",
    input="the variable to flip", output="updated counts and the unsatisfied-clause list", state="numtruelit per clause, breakcount, makecount, the false-clause list, the freebie list", update="per flip", assumptions=["a variable's effect on the clause count is a local function of the clauses it occurs in; maintaining it incrementally makes a flip O(occurrences) rather than O(clauses)"],
    fitness_value_in_ancestor="millions of flips per second; the reason local search became competitive on random and structured instances", failure_landscape="UNKNOWN by run", human_prior="GSAT's score maintenance (Selman, Levesque, Mitchell 1992); the break/make split is WalkSAT's", evidence_ref=W + ":463-610", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="flipatom and the count arrays",
    coverage={"input_topology": "SCALAR", "output_topology": "SET", "state_amount": "LINEAR_IN_INPUT", "state_persistence": "PER_EPISODE", "stochasticity": "DETERMINISTIC", "update_topology": "EVENT_DRIVEN"})

skc = c.organ("walksat_skc_flip_rule_choosing_from_a_random_unsatisfied_clause_the_variable_with_minimum_break_count_or_with_probability_p_a_random_variable_unless_a_zero_break_flip_exists", human_name="pickbest (1666-1691): tofix = false[random]; bestvalue = min breakcount over the clause; if (nofreebie || bestvalue > 0) and random < p then a random variable of the clause, else a random best", status="ACCEPTED",
    mechanism="an unsatisfied clause is chosen uniformly; among its variables the ones with the smallest breakcount are collected; if some variable breaks nothing it is taken (a free move), otherwise with probability p (the noise) a uniformly random variable of the clause is flipped and with 1 - p one of the best; the clause is thereby satisfied at every step and the damage elsewhere is minimised or randomised",
    input="the false-clause list and the counts", output="a variable to flip", state="none", update="per flip", assumptions=["always satisfying the chosen clause focuses the walk; break count alone (not net gain) is the right score; noise is needed to escape local minima and the free-move exception costs nothing"],
    fitness_value_in_ancestor="the SKC rule (Selman, Kautz, Cohen 1994) that made WalkSAT beat GSAT and complete solvers on hard random 3-SAT", failure_landscape="by reading: the optimal noise p depends on the instance (the reason the adaptive option exists); it cannot prove unsatisfiability", human_prior="Selman, Kautz & Cohen 1994", evidence_ref=W + ":1666-1691", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="pickbest",
    coverage={"input_topology": "SET", "output_topology": "SCALAR", "state_amount": "NONE", "stochasticity": "SEEDED_RANDOM", "update_topology": "SINGLE_STEP"})

nov = c.organ("novelty_rule_scoring_by_make_minus_break_and_refusing_the_most_recently_flipped_variable_unless_a_coin_at_p_says_otherwise_with_a_forced_random_walk_every_hundred_flips", human_name="picknovelty (1918-1965): diff = makecount - breakcount; best and second best with age (changed[var]) as tie-break; youngest; 'if best != youngest return best; else with probability p second_best'; plus_flag (Novelty+: a 1 percent random walk) vs numflip % 100", status="ACCEPTED",
    mechanism="in the chosen unsatisfied clause, variables are scored by net gain (make minus break), ties broken toward the older variable; if the best variable is not the one flipped most recently in the clause it is taken; if it is, the second best is taken with probability p; independently a random variable is taken every hundredth flip (or with probability 1 percent in the Novelty+ variant), which is what makes the walk provably able to leave any region",
    input="the counts and the flip ages", output="a variable", state="changed[] (the last flip time per variable)", update="per flip", assumptions=["flipping the variable just flipped back is the dominant failure of greedy walks; an age tie-break plus a probabilistic refusal is cheaper than a tabu list"],
    fitness_value_in_ancestor="Novelty (McAllester, Selman, Kautz 1997) and Novelty+ (Hoos 1999) outperform SKC on structured instances", failure_landscape="by reading: without the periodic random walk Novelty can loop (Hoos's finding, which the plus variant fixes)", human_prior="McAllester, Selman & Kautz 1997; Hoos 1999", evidence_ref=W + ":1918-1965", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="picknovelty",
    coverage={"input_topology": "SET", "output_topology": "SCALAR", "state_amount": "LINEAR_IN_INPUT", "memory": "LAST_VALUE", "stochasticity": "SEEDED_RANDOM", "update_topology": "SINGLE_STEP"})

adapt = c.organ("noise_adjusted_during_the_search_from_the_number_of_unsatisfied_clauses_with_two_rates", human_name="-adaptive PHI THETA (214-218, 723-734): last_adaptive_objective, adaptive_phi 0.2, adaptive_theta 0.2; the update sites not read", status="CANDIDATE",
    mechanism="starting at zero noise, the search watches the number of unsatisfied clauses; if it has not improved for a while (theta times the clause count) the noise is raised by phi of the remaining range, and on an improvement it is lowered faster; so the walk is greedy while progress is made and random when stuck", input="the objective over time", output="the noise p", state="last_adaptive_objective, p", update="per flip", assumptions=["the best static noise is instance-dependent and unknowable in advance; the objective's stagnation is a usable signal"],
    fitness_value_in_ancestor="removes the noise parameter from the user's hands (Hoos 2002)", failure_landscape="UNKNOWN by run", human_prior="Hoos 2002 (adaptive noise)", evidence_ref=W + ":214-218, 723-734 (the option; the update code not read)", confidence="MEDIUM", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="the adaptive option; CANDIDATE because the update site was not read",
    coverage={"input_topology": "SCALAR", "output_topology": "SCALAR", "state_amount": "CONSTANT", "feedback": "CLOSED_LOOP", "stochasticity": "DETERMINISTIC"})

c.reject("pickrnovelty, picktabu, pickgsat, pickalternate, pickbigflip, the freebie list details, the hamming-distance instrumentation, the solution / statistics printing, the other programs in the v56 tree", reason="OTHER", evidence="NOT READ; residue")
c.reject("'local search' as one organ", reason="NAME_HAS_NO_EXECUTABLE_BOUNDARY", evidence="the count maintenance, the flip rules and the noise control are separable and separately published")

c.edge(inc, skc, "feeds"); c.edge(inc, nov, "feeds"); c.edge(skc, inc, "triggers", note="flipatom"); c.edge(nov, inc, "triggers"); c.edge(adapt, skc, "updates", note="p"); c.edge(adapt, nov, "updates")

c.pressure("a_satisfying_assignment_must_be_found_for_large_satisfiable_formulas_where_complete_search_is_too_slow_and_the_landscape_has_local_minima_that_a_greedy_walk_revisits",
    condition="an organism searches assignments of a satisfiable CNF by flipping variables; the score is time to a model over a suite of random and structured instances; unsatisfiable instances may be present (the organism cannot prove them, only time out)", resource_or_constraint="flips per second; a noise setting",
    failure_condition="cycling between the same assignments, or flips that cost O(clauses) each", world_punishes="pure greedy (GSAT without noise); recomputing scores from scratch; flipping back the last move", world_rewards="incremental counts, clause-focused random walk with noise, age-aware refusal, adaptive noise",
    observable_consequence="median flips to a model on uf250 random 3-SAT and on a structured family, for GSAT, SKC at fixed p, Novelty+ and adaptive noise; the fraction of runs that cycle without the periodic random walk", vacuity_condition="2-SAT or instances solved by unit propagation", trivial_shortcuts="a complete solver on small instances (the world uses instances where CDCL is slower)",
    cheat_control="an organism given a model must verify it in one pass; GSAT with zero noise must get stuck on the structured family where SKC succeeds; Novelty without the periodic walk must show cycling that Novelty+ removes: the world must show all three",
    cost_class="CPU-scale", source_evidence="walksat.c flipatom, pickbest, picknovelty, the adaptive option", purpose="PURPOSE: incomplete SAT solving by local search (Selman, Kautz, Cohen 1994; Kautz's distribution 2004-)")

c.ancestry("algorithm_from", "GSAT (Selman, Levesque, Mitchell 1992); WalkSAT (Selman, Kautz, Cohen 1994); Novelty (McAllester et al. 1997); Novelty+ and adaptive noise (Hoos 1999, 2002); the atlas's minisat-2.2.0 and picosat-965 hold the complete rivals", note="from the source and the record")
c.residue("PARTIALLY_EXPLAINED", ["the other flip rules and the adaptive update site unread", "nothing ran"], note="the four mechanisms are located; a three-solver world (WalkSAT, MiniSat, PicoSAT) is now readable in this atlas")
c.save(state="DEEP")
