"""Cut: xv6-riscv (MIT's xv6 for RISC-V; ancestry-aware, Stage A DEEP on three subsystems; SOURCE_READ on M3; position 63 of the 2026-09-17
NOT_CUT order). Read: kernel/proc.c scheduler 428-478, sched / yield / forkret (names), sleep_prepare / sleep / wakeup / kkill 547-640;
kernel/log.c in full at structure level (initlog, install_trans, read_head, write_head, recover_from_log, begin_op, end_op, write_log,
commit, log_write); kernel/param.h. NOT read: vm.c (page tables), trap.c / trampoline.S (traps and system calls), fs.c (inodes and
directories), bio.c (the buffer cache), exec.c, pipe.c, kalloc.c, spinlock.c, the user programs, mkfs. Nothing ran (no RISC-V toolchain
or QEMU on M3).
"""
from nyx.atlas.author import Cut

P = "vault:xv6-riscv/upstream/tree/kernel/proc.c"; L = "vault:xv6-riscv/upstream/tree/kernel/log.c"; PA = "vault:xv6-riscv/upstream/tree/kernel/param.h"
c = Cut("xv6-riscv", mode="ANCESTRY_AWARE", inspected=["kernel/proc.c 428-478, 547-640", "kernel/log.c 1-200 (structure)", "kernel/param.h"], evidence=[("SOURCE_READ", P + ":428-478"), ("SOURCE_READ", P + ":547-640"), ("SOURCE_READ", L + ":1-200"), ("SOURCE_READ", PA + ":9-11")],
        note="three mechanisms of a teaching kernel, each the simplest correct form: a per-CPU scheduler that scans the process table round-robin holding each candidate's lock across the context switch (the switched-to process releases it); sleep/wakeup on an address with a two-step protocol (register the channel under the process lock, then sleep only if no wakeup cleared it) that closes the lost-wakeup window; and a write-ahead log with group commit where each file-system call reserves its worst-case block count before starting and the last caller out commits the batch with one header write as the atomic point")

sched = c.organ("per_cpu_round_robin_scan_of_the_process_table_holding_the_chosen_process_lock_across_the_context_switch_so_the_lock_is_released_by_the_process_that_was_switched_to", human_name="scheduler (proc.c 428-478): the for(;;) over proc[]; acquire(&p->lock); p->state = RUNNING; swtch(&c->context, &p->context); release; wfi when nothing is runnable; sched() / yield() / forkret as the return paths", status="ACCEPTED",
    mechanism="each CPU loops over the fixed process table; for each RUNNABLE process it acquires that process's lock, marks it RUNNING, and switches registers to it; the process runs until it calls sched() (from yield on a timer interrupt, from sleep, or from exit) with its own lock held and its state changed, which switches back into the scheduler loop where the lock is released; interrupts are briefly enabled at the top of each loop so a pending interrupt can make something runnable; with nothing runnable the CPU executes wfi",
    input="the process table; timer interrupts", output="CPU time assigned", state="c->proc, per-process state and context", update="per switch", assumptions=["the invariant 'p->lock is held across swtch by whoever changes p->state' is what makes the scheduler correct on many CPUs without a global lock (the xv6 book's chapter 7)"],
    fitness_value_in_ancestor="a multiprocessor scheduler in fifty lines whose correctness argument fits in a paragraph", failure_landscape="by reading: O(NPROC) per scheduling decision; no priorities; a CPU may scan the whole table between useful switches", human_prior="Sixth Edition Unix's scheduler; the lock-handoff idiom is xv6's own", evidence_ref=P + ":428-478", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="scheduler, sched, yield, forkret",
    coverage={"input_topology": "SET", "output_topology": "EVENT", "state_amount": "CONSTANT", "state_persistence": "PERSISTENT", "stochasticity": "ENVIRONMENT_RANDOM", "update_topology": "SWEEP", "competition": "ARBITRATES"})

slp = c.organ("sleep_and_wakeup_on_an_address_with_a_two_step_protocol_that_registers_the_channel_before_sleeping_and_sleeps_only_if_no_wakeup_has_cleared_it", human_name="sleep_prepare(chan) (sets p->chan under p->lock), sleep() (if p->chan != 0 then SLEEPING and sched()), wakeup(chan) (clears p->chan for every matching process and makes SLEEPING ones RUNNABLE), kkill (547-640)", status="ACCEPTED",
    mechanism="a waiter first records the channel it will wait on under its own lock, then re-checks the condition it is waiting for, then calls sleep, which goes to sleep only if the channel is still set; a waker clears the channel of every process registered on it and wakes those already asleep; so a wakeup that lands between the registration and the sleep is not lost (it clears the channel and sleep returns immediately); kill wakes a sleeping victim so it can notice the flag",
    input="a channel address", output="a blocked or resumed process", state="p->chan, p->state", update="per wait/wake", assumptions=["the lost-wakeup race is the central hazard of sleep/wakeup; registering the channel under the process lock is enough to close it without holding the condition's lock across the switch"],
    fitness_value_in_ancestor="condition synchronisation with no condition-variable object; the classic Unix primitive made race-free", failure_landscape="by reading: wakeup scans the whole table (O(NPROC)); spurious wakeups are possible and callers loop", human_prior="Unix V6 sleep/wakeup; the two-step form differs from the classic xv6 sleep(chan, lock) (this is a later revision of the body)", evidence_ref=P + ":547-640", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="the four functions",
    coverage={"input_topology": "EVENT", "output_topology": "EVENT", "state_amount": "CONSTANT", "stochasticity": "ENVIRONMENT_RANDOM", "update_topology": "EVENT_DRIVEN", "failure_mode": "NONE_KNOWN"})

log = c.organ("write_ahead_log_with_group_commit_where_each_call_reserves_its_worst_case_blocks_before_starting_the_last_caller_commits_with_one_header_write_and_recovery_replays_the_header", human_name="log.c: begin_op (waits while committing or while log.lh.n + (outstanding + 1) * MAXOPBLOCKS > LOGBLOCKS), log_write (absorbs a block already in the log), end_op (outstanding -= 1; commit when zero), commit (write_log; write_head = the atomic point; install_trans; clear the header), recover_from_log; param.h MAXOPBLOCKS 10, LOGBLOCKS 30", status="ACCEPTED",
    mechanism="a file-system call declares itself by begin_op, which blocks until the log has room for its worst case (10 blocks) beyond every other outstanding call's; modified blocks are recorded in the in-memory header (a block already listed is absorbed, not duplicated); when the last outstanding call ends, the batch is committed: data blocks are copied to the log area, the header (block list and count) is written in one block write (the commit point), the blocks are installed to their home locations, and the header count is zeroed; at boot the header is read and any listed blocks are re-installed, so a crash before the header write loses the batch cleanly and a crash after it is replayed",
    input="block writes from file-system calls", output="an atomic batch on disk", state="the in-memory header, outstanding, committing", update="per call and per commit", assumptions=["a single block write is atomic (the header); worst-case reservation avoids deadlock on log space; batching many calls per commit amortises the double write"],
    fitness_value_in_ancestor="crash consistency in 200 lines; every later journaling file system has this shape", failure_landscape="by reading: the log is 30 blocks, so at most three concurrent calls; every data block is written twice; no ordering guarantees across batches beyond the commit point", human_prior="write-ahead logging (Gray 1978); the xv6 book chapter 8", evidence_ref=L + ":1-200; " + PA + ":9-11", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="log.c",
    coverage={"input_topology": "SEQUENCE", "output_topology": "SET", "state_amount": "CONSTANT", "state_persistence": "DURABLE", "stochasticity": "DETERMINISTIC", "update_topology": "EVENT_DRIVEN", "recovery": "ROLLS_BACK", "failure_mode": "NONE_KNOWN"})

c.reject("vm.c (page-table construction, kernel and user address spaces), trap.c and trampoline.S (the trap entry, system calls, timer interrupts), fs.c and bio.c (inodes, directories, the buffer cache), exec.c, pipe.c, kalloc.c, spinlock.c / sleeplock.c, the user programs and mkfs", reason="OTHER", evidence="NOT READ (~5,000 lines); residue", note="each is a mechanism the xv6 book devotes a chapter to; the buffer cache (LRU over bufs) and the trampoline page are the next two to cut")
c.reject("'operating system' / 'Unix' as one organ", reason="NAME_HAS_NO_EXECUTABLE_BOUNDARY", evidence="scheduler, synchronisation and logging are three files with three separable invariants")

c.edge(slp, sched, "feeds", note="sleep calls sched"); c.edge(sched, slp, "feeds", note="wakeup makes RUNNABLE"); c.edge(log, slp, "feeds", note="begin_op waits on &log")

c.pressure("many_processes_on_several_cpus_must_share_the_machine_and_the_disk_such_that_no_wakeup_is_lost_no_lock_is_held_across_a_switch_by_the_wrong_thread_and_a_crash_at_any_instruction_leaves_the_file_system_consistent",
    condition="an organism runs N processes on M CPUs; processes block on conditions and on disk; the power may fail at any instruction; the score is liveness (no lost wakeups, no deadlock) and crash consistency (the file system is a prefix of committed batches after any crash), with code size as a secondary score", resource_or_constraint="a fixed process table; a 30-block log",
    failure_condition="a process that sleeps forever after a wakeup it missed; a lock handed across CPUs incorrectly; a file system with a half-applied operation after a crash", world_punishes="check-then-sleep without registration; releasing the process lock before the switch; in-place metadata writes", world_rewards="the two-step sleep, the lock-handoff invariant, worst-case reservation with a single-block commit point",
    observable_consequence="lost-wakeup count under a stress test with many CPUs; consistency check after crashes injected at every block write of a batch (the test-xv6.py suite and a crash-injecting disk)", vacuity_condition="one CPU, one process, no crashes", trivial_shortcuts="a global kernel lock and a synchronous file system (correct but scores poorly on the secondary metrics)",
    cheat_control="an organism with crash injection disabled must pass every consistency check; the log with the header write moved before write_log must fail the injected-crash check; sleep without sleep_prepare must lose wakeups under the stress test: the world must show all three",
    cost_class="CPU-scale", source_evidence="proc.c scheduler / sleep / wakeup; log.c; param.h", purpose="PURPOSE: a teaching kernel (MIT PDOS 2006-)")

c.ancestry("reimplementation_of", "Sixth Edition Unix (1975) for RISC-V; the logging layer follows the xv6 book's design (Cox, Kaashoek, Morris)", note="from the README and the record")
c.residue("LARGE_RESIDUE", ["virtual memory, traps, the file system proper, pipes and exec unread", "nothing ran (needs riscv64 gcc and qemu: an M2 world)"], note="three subsystems located DEEP; the kernel's other five chapters are in the residue")
c.save(state="DEEP")
