"""Cut: zlib-1.3.1 (Gailly & Adler's zlib, the reference DEFLATE; ancestry-aware, Stage A DEEP; SOURCE_READ on M3; position 88 of the
2026-09-17 NOT_CUT order). Read: deflate.c the configuration table 93-127, deflate_slow 1905-2005 (lazy matching), longest_match
1348-1425 (hash-chain search). NOT read: deflate_fast, deflate_rle/huff/stored, trees.c (the Huffman construction), inflate.c and
inffast.c (decoding), the checksums. Nothing ran (C; no compiler on M3). The atlas's gzip and compress/ncompress cuts hold the LZ family.
"""
from nyx.atlas.author import Cut

D = "vault:zlib-1.3.1/upstream/tree/zlib-1.3.1/deflate.c"
c = Cut("zlib-1.3.1", mode="ANCESTRY_AWARE", inspected=["deflate.c 93-127, 1348-1425, 1905-2005"], evidence=[("SOURCE_READ", D + ":93-127"), ("SOURCE_READ", D + ":1348-1425"), ("SOURCE_READ", D + ":1905-2005")],
        note="LZ77 matching plus Huffman coding, read for its two engineering mechanisms: a hash-chain search for the longest earlier match of the current position, bounded by a per-level chain-length cap and a nice-match early exit; and lazy matching, which defers emitting a match by one byte to see whether the next position has a longer one, choosing the literal-plus-later-match when it does. A ten-row configuration table indexed by compression level sets the four knobs (good/lazy/nice length, max chain), so 'level' is a point in a speed/ratio trade space")

lm = c.organ("longest_match_by_walking_a_hash_chain_of_earlier_positions_with_a_chain_length_cap_a_nice_match_early_exit_and_a_cheap_end_byte_prefilter", human_name="longest_match (1348-1425): chain_length = max_chain_length (quartered if prev_length >= good_match); best_len; scan_end prefilter; stop at limit (strstart - MAX_DIST) or when a match reaches nice_match", status="ACCEPTED",
    mechanism="positions with the same 3-byte hash are linked in a chain; the search walks the chain from the most recent, and for each candidate first compares the two bytes at the current best length (a cheap reject) before a full compare, keeping the longest match found; the walk stops after max_chain_length steps, when a candidate is older than the window (MAX_DIST), or when a match reaches nice_match; if the previous position already had a good match the chain length is quartered (spend less effort when a match is already in hand)",
    input="the current position and the hash chain", output="the best match length and position", state="the hash chains, the window", update="per position", assumptions=["recent positions are the likely matches, so most-recent-first with a cap gives most of the benefit at bounded cost; the end-byte prefilter skips most full compares"],
    fitness_value_in_ancestor="the LZ77 match search whose cost the level knobs control; the heart of DEFLATE's speed/ratio dial", failure_landscape="by reading: the chain cap trades ratio for speed; long runs of one byte make chains degenerate (the reason for the caps)", human_prior="Ziv & Lempel 1977 (LZ77); the hash-chain implementation is Gailly's", evidence_ref=D + ":1348-1425", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="longest_match",
    coverage={"input_topology": "SEQUENCE", "output_topology": "SCALAR", "state_amount": "LINEAR_IN_INPUT", "stochasticity": "DETERMINISTIC", "update_topology": "SWEEP", "resource_dependence": "TIME"})

lazy = c.organ("lazy_matching_that_defers_a_match_by_one_byte_to_check_whether_the_next_position_yields_a_longer_one_emitting_the_literal_plus_later_match_when_it_does", human_name="deflate_slow (1905-2005): keep prev_length/prev_match; find match at strstart; if prev_length >= MIN_MATCH and match_length <= prev_length emit the previous match (as a literal at strstart-1 plus the run) else defer the literal; TOO_FAR discards a short far match; match_available", status="ACCEPTED",
    mechanism="at each position the matcher records the current match but does not emit it; it advances one byte and finds the match there; if the earlier (deferred) match is at least as long as the new one it is emitted, otherwise the byte between them is emitted as a literal and the new, longer match is deferred in turn; a length-3 match whose distance exceeds TOO_FAR is discarded as not worth its code; this one-byte lookahead recovers matches that greedy matching would miss",
    input="the match at each position", output="the chosen sequence of literals and matches", state="prev_length, prev_match, match_available", update="per position", assumptions=["a one-position lookahead captures most of the gain of optimal parsing at a fraction of the cost; the greedy choice is often but not always best"],
    fitness_value_in_ancestor="a few percent better ratio than greedy at levels 4 and up; the default deflate strategy", failure_landscape="by reading: only one byte of lookahead, so it is not optimal parsing; the fast levels (deflate_fast) skip it entirely for speed", human_prior="lazy evaluation of LZ matches (Gailly); the fuller form is optimal parsing (zopfli, later)", evidence_ref=D + ":1905-2005, 93-127", confidence="HIGH", portability="YES", compatibility="YES", utility="UNKNOWN", source_boundary="deflate_slow and the configuration table",
    coverage={"input_topology": "SEQUENCE", "output_topology": "SEQUENCE", "state_amount": "CONSTANT", "stochasticity": "DETERMINISTIC", "update_topology": "SWEEP"})

c.reject("deflate_fast (greedy, no lazy step), deflate_rle / deflate_huff / deflate_stored, trees.c (dynamic and static Huffman code construction, the block emit), inflate.c and inffast.c (the decoder), adler32 and crc32", reason="OTHER", evidence="NOT READ; residue", note="trees.c (the Huffman half) is the second mechanism family and a DEEP item; the atlas's gzip cut holds the same deflate at a different version")
c.reject("'DEFLATE' / 'compression' as one organ", reason="NAME_HAS_NO_EXECUTABLE_BOUNDARY", evidence="the LZ match search, the parse strategy and the Huffman coder are separable and separately tunable")

c.edge(lm, lazy, "feeds"); c.edge(lazy, lm, "triggers", note="finds the match at each position")

c.pressure("a_byte_stream_must_be_compressed_near_its_lz_entropy_at_a_caller_chosen_point_on_the_speed_ratio_curve_where_the_match_search_cost_and_the_parse_greediness_are_both_tunable",
    condition="an organism compresses data at a requested level; the score is compressed size and time; the level must span from fast/low-ratio to slow/high-ratio; the format (the decoded output) must be identical regardless of level", resource_or_constraint="the match-search budget (chain length); one byte of parse lookahead",
    failure_condition="a level that is slower without being smaller, or a parse that misses easy longer matches (pure greedy)", world_punishes="an unbounded chain search; greedy parsing at high levels", world_rewards="a chain cap plus nice-match exit, and lazy one-byte lookahead",
    observable_consequence="compressed size and time across levels on the Calgary/Silesia corpus for greedy (deflate_fast) vs lazy (deflate_slow), and vs an optimal parser (zopfli) as the upper control; identical decompression at every level", vacuity_condition="incompressible input", trivial_shortcuts="storing uncompressed (deflate_stored, a valid level-0 control)",
    cheat_control="an optimal parser must give the smallest size at the highest cost; greedy must be fastest and largest; lazy must sit between on both axes at identical decoded output: the world must show all three", cost_class="CPU-scale",
    source_evidence="deflate.c longest_match, deflate_slow, the configuration table", purpose="PURPOSE: reference DEFLATE (Gailly & Adler 1995-)")

c.ancestry("algorithm_from", "Ziv & Lempel 1977 (LZ77); Huffman 1952; Deutsch RFC 1951 (DEFLATE); the atlas's gzip and ncompress/compress cuts are the LZ family", note="from the record and the source")
c.residue("PARTIALLY_EXPLAINED", ["the Huffman coder (trees.c), the fast strategy and the decoder unread", "nothing ran"], note="the LZ match-and-parse mechanisms are located; the entropy stage is the residue")
c.save(state="DEEP")
