"""
Noesis v2 — Tensor Train Completion

Use TensorLy for tensor decomposition and completion on the damage × hub matrix.
The 11-primitive basis constrains the rank — if mathematical transformations are
generated by 11 moves, the interaction tensor has low rank.

Strategy:
1. Build the full 3D tensor: damage_op × hub × resolution_features
2. Mask the empty cells
3. TT decomposition on the known entries
4. Reconstruct the full tensor
5. Empty cells with high reconstructed values = predicted discoveries
"""
import numpy as np
import json
import sys
from pathlib import Path

sys.stdout.reconfigure(encoding='utf-8')

try:
    import tensorly as tl
    from tensorly.decomposition import tucker, parafac, non_negative_tucker
    from tensorly.tenalg import multi_mode_dot
    HAS_TENSORLY = True
except ImportError:
    HAS_TENSORLY = False

DAMAGE_OPS = ["DISTRIBUTE", "CONCENTRATE", "TRUNCATE", "EXTEND", "RANDOMIZE", "HIERARCHIZE", "PARTITION"]
PRIMITIVES = ["COMPOSE", "MAP", "EXTEND", "REDUCE", "LIMIT", "DUALIZE",
              "LINEARIZE", "STOCHASTICIZE", "SYMMETRIZE", "BREAK_SYMMETRY", "COMPLETE"]


def load_matrix():
    matrix = np.load("noesis/v2/damage_hub_matrix.npy")
    with open("noesis/v2/tensor_output.json") as f:
        meta = json.load(f)
    return matrix, meta["hubs"], meta["damage_ops"]


def build_feature_tensor(matrix, hubs):
    """Expand 2D matrix to 3D by adding feature dimensions.

    Axis 0: damage operators (7)
    Axis 1: hubs (20)
    Axis 2: structural features (derived from hub properties)

    Features per hub:
    - Which primitives appear in its structural pattern
    - Number of known resolutions
    - Domain category encoding
    """
    n_damage = matrix.shape[0]
    n_hubs = matrix.shape[1]
    n_features = len(PRIMITIVES) + 3  # 11 primitives + resolution_count + domain_cats

    tensor = np.zeros((n_damage, n_hubs, n_features), dtype=np.float32)

    # Load hub metadata
    import duckdb
    db = duckdb.connect("noesis/v2/noesis_v2.duckdb", read_only=True)

    for h_idx, hub_id in enumerate(hubs):
        row = db.execute(
            "SELECT primitive_sequence, chain_count FROM abstract_compositions WHERE comp_id = ?",
            [hub_id]
        ).fetchone()

        if row:
            prim_seq, chain_count = row
            # Encode which primitives appear
            prim_vec = np.zeros(len(PRIMITIVES))
            if prim_seq:
                for i, p in enumerate(PRIMITIVES):
                    if p in prim_seq.upper():
                        prim_vec[i] = 1.0

            # For each damage operator that's present, set the full feature vector
            for d_idx in range(n_damage):
                if matrix[d_idx, h_idx] > 0:
                    tensor[d_idx, h_idx, :len(PRIMITIVES)] = prim_vec
                    tensor[d_idx, h_idx, len(PRIMITIVES)] = min(chain_count / 10.0, 1.0)
                    # Damage operator self-encoding
                    tensor[d_idx, h_idx, len(PRIMITIVES) + 1] = 1.0
                    tensor[d_idx, h_idx, len(PRIMITIVES) + 2] = d_idx / len(DAMAGE_OPS)

    db.close()
    return tensor


def tt_complete_2d(matrix):
    """Low-rank matrix completion on the 2D damage × hub matrix.
    Use SVD-based completion (simplest TT for 2D = truncated SVD)."""

    mask = (matrix > 0).astype(np.float32)

    # Iterative SVD completion
    filled = matrix.copy()
    # Initialize empty cells with row/column means
    row_means = np.where(mask.sum(axis=1) > 0,
                         (matrix * mask).sum(axis=1) / mask.sum(axis=1),
                         0.5)
    col_means = np.where(mask.sum(axis=0) > 0,
                         (matrix * mask).sum(axis=0) / mask.sum(axis=0),
                         0.5)

    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            if mask[i, j] == 0:
                filled[i, j] = (row_means[i] + col_means[j]) / 2

    best_rank = 3  # Low rank assumption from 11-primitive basis

    # Iterate: SVD project then restore known entries
    for iteration in range(100):
        U, s, Vt = np.linalg.svd(filled, full_matrices=False)
        # Truncate to rank
        U_r = U[:, :best_rank]
        s_r = s[:best_rank]
        Vt_r = Vt[:best_rank, :]
        reconstructed = U_r @ np.diag(s_r) @ Vt_r

        # Restore known entries
        new_filled = reconstructed.copy()
        new_filled[mask > 0] = matrix[mask > 0]

        # Check convergence
        change = np.abs(new_filled - filled).sum()
        filled = new_filled
        if change < 1e-6:
            break

    return reconstructed, filled


def tucker_complete_3d(tensor, mask_3d):
    """Tucker decomposition completion on 3D tensor."""
    if not HAS_TENSORLY:
        print("[WARN] TensorLy not available for Tucker decomposition")
        return None

    # Initialize empty cells
    filled = tensor.copy()
    filled[mask_3d == 0] = 0.5

    rank = [3, 5, 5]  # Low rank per mode

    for iteration in range(50):
        try:
            core, factors = tucker(tl.tensor(filled), rank=rank)
            reconstructed = tl.tucker_to_tensor((core, factors))
            reconstructed = np.array(reconstructed)

            new_filled = reconstructed.copy()
            new_filled[mask_3d > 0] = tensor[mask_3d > 0]

            change = np.abs(new_filled - filled).sum()
            filled = new_filled
            if change < 1e-4:
                break
        except Exception as e:
            print(f"  Tucker iteration {iteration} failed: {e}")
            break

    return reconstructed


def main():
    print("=" * 70)
    print("NOESIS v2 — TENSOR TRAIN COMPLETION")
    print("=" * 70)

    matrix, hubs, damage_ops = load_matrix()
    hub_short = [h.replace("IMPOSSIBILITY_", "")[:25] for h in hubs]

    # ================================================================
    # Method 1: SVD-based 2D completion
    # ================================================================
    print("\n--- METHOD 1: LOW-RANK SVD COMPLETION (2D) ---\n")

    reconstructed, filled = tt_complete_2d(matrix)

    # Find highest-scoring empty cells
    mask = (matrix > 0).astype(np.float32)
    empty_scores = []
    for d_idx, d_op in enumerate(DAMAGE_OPS):
        for h_idx, hub in enumerate(hubs):
            if mask[d_idx, h_idx] == 0:
                score = reconstructed[d_idx, h_idx]
                empty_scores.append({
                    "damage_op": d_op,
                    "hub": hub_short[h_idx],
                    "hub_full": hub,
                    "score": round(float(score), 4),
                })

    empty_scores.sort(key=lambda x: -x["score"])

    print("Top 25 predictions (empty cells with highest reconstructed values):")
    print(f"{'Rank':>4s}  {'Score':>6s}  {'Damage Op':15s}  {'Hub':30s}")
    print("-" * 60)
    for i, c in enumerate(empty_scores[:25], 1):
        confidence = "HIGH" if c["score"] > 0.7 else "MEDIUM" if c["score"] > 0.5 else "LOW"
        print(f"{i:4d}  {c['score']:6.4f}  {c['damage_op']:15s}  {c['hub']:30s}  [{confidence}]")

    # ================================================================
    # Method 2: Tucker 3D completion (if TensorLy available)
    # ================================================================
    if HAS_TENSORLY:
        print("\n--- METHOD 2: TUCKER 3D COMPLETION ---\n")

        tensor_3d = build_feature_tensor(matrix, hubs)
        mask_3d = np.zeros_like(tensor_3d)
        for d in range(tensor_3d.shape[0]):
            for h in range(tensor_3d.shape[1]):
                if matrix[d, h] > 0:
                    mask_3d[d, h, :] = 1.0

        print(f"3D tensor shape: {tensor_3d.shape}")
        print(f"Known entries: {int(mask_3d.sum())} / {mask_3d.size} ({100*mask_3d.sum()/mask_3d.size:.1f}%)")

        reconstructed_3d = tucker_complete_3d(tensor_3d, mask_3d)

        if reconstructed_3d is not None:
            # Score empty cells by reconstructed magnitude
            tucker_scores = []
            for d_idx, d_op in enumerate(DAMAGE_OPS):
                for h_idx, hub in enumerate(hubs):
                    if mask[d_idx, h_idx] == 0:
                        # Average reconstructed value across features
                        score = float(np.mean(np.abs(reconstructed_3d[d_idx, h_idx, :])))
                        tucker_scores.append({
                            "damage_op": d_op,
                            "hub": hub_short[h_idx],
                            "score": round(score, 4),
                        })

            tucker_scores.sort(key=lambda x: -x["score"])

            print("\nTucker Top 25 predictions:")
            print(f"{'Rank':>4s}  {'Score':>6s}  {'Damage Op':15s}  {'Hub':30s}")
            print("-" * 60)
            for i, c in enumerate(tucker_scores[:25], 1):
                print(f"{i:4d}  {c['score']:6.4f}  {c['damage_op']:15s}  {c['hub']:30s}")

            # Compare methods — find consensus predictions
            print("\n--- CONSENSUS (appear in top 15 of BOTH methods) ---\n")
            svd_top = set((c["damage_op"], c["hub"]) for c in empty_scores[:15])
            tucker_top = set((c["damage_op"], c["hub"]) for c in tucker_scores[:15])
            consensus = svd_top & tucker_top

            if consensus:
                for d_op, hub in sorted(consensus):
                    svd_score = next(c["score"] for c in empty_scores if c["damage_op"] == d_op and c["hub"] == hub)
                    tucker_score = next(c["score"] for c in tucker_scores if c["damage_op"] == d_op and c["hub"] == hub)
                    print(f"  {d_op:15s} x {hub:30s}  SVD={svd_score:.4f}  Tucker={tucker_score:.4f}")
            else:
                print("  No consensus in top 15 — methods are finding different patterns")

    # ================================================================
    # Save results
    # ================================================================
    output = {
        "method": "svd_completion_rank3",
        "matrix_shape": list(matrix.shape),
        "filled_cells": int(mask.sum()),
        "empty_cells": int((1 - mask).sum()),
        "fill_rate": round(float(mask.sum() / mask.size), 4),
        "predictions": empty_scores[:30],
        "hubs": hubs,
        "damage_ops": DAMAGE_OPS,
    }

    with open("noesis/v2/tt_completion_results.json", "w") as f:
        json.dump(output, f, indent=2)

    print(f"\nResults saved to noesis/v2/tt_completion_results.json")
    print(f"Matrix: {matrix.shape}, fill rate: {100*mask.sum()/mask.size:.1f}%")
    print(f"Predictions: {len(empty_scores)} empty cells scored")


if __name__ == "__main__":
    main()
