"""One packet template for every residue-carrying arm. Isomorphism by construction.

RULING (2026-08-25, REDESIGN): *"If F-generic can be identified against F-null/F-prom from
packet shape alone, then the controller is not a controller. Make the packets syntactically
isomorphic before another arm call. That is prior to the 300-row question."*

The previous design let each arm render itself. F-null and F-prom happened to share a template;
F-generic was free prose, and a decidable check separated it by shape alone. Checking for
isomorphism after the fact is the weaker discipline — the check has to be remembered, and it was
added only after two exit reviews died on shape confounds. Here every arm calls **one**
renderer, so the arms cannot diverge in shape without editing this file.

Timing note: this changes the packet format, which is free right now and would not be later —
no arm rows exist yet. The band read is F0-only (cold, no packet), so nothing collected is
invalidated.

WHAT VARIES BETWEEN ARMS: the slot contents only — the source slug and the item list.
WHAT DOES NOT: the literal frame, field order, punctuation, the redaction markers, and the
trailing sparsity block. The source token is IDENTICAL across arms (`probe_pool`), because a
differing literal is readable even when the shape matches.
"""
import re

#: Shared across every arm — a per-arm pool token would be a readable label.
POOL = "nearmiss_mix"

#: The single frame. Every residue-carrying arm renders through this and only this.
TEMPLATE = (
    "[probe_pool:{slug} p[COUNT-REDACTED]_prepass#[COUNT-REDACTED]]\n"
    "prior attempt applied (method projection; prose withheld - measured diffuse answer "
    "leakage): {items}\n"
    "  (not recorded: diagnosis)\n"
    "\n"
    "{sparsity}"
)

#: The modal block. NOT a casual default: the real sparsity VARIES (3 of 60 sampled tasks
#: carry an extra `attempt_text` line), so freezing it would have silently rewritten
#: residue content on ~5% of tasks while appearing to only fix shape.
MODAL_SPARSITY = ("SPARSITY (what the substrate did not record - shipped as measured):\n"
                  "  diagnosis: absent in [COUNT-REDACTED]/[COUNT-REDACTED] records (100.0%)")

#: Slug format is fixed so the id cannot carry arm identity through its *shape* either.
_SLUG_RE = re.compile(r"^[a-z0-9_]+-[A-Z]\d+-\d{5}$")


def render(slug, items, sparsity=None):
    """Render a packet. `items` is a list of tokens; `slug` must match the frozen id shape.

    Raises rather than coercing: a slug of the wrong shape is exactly the leak this file
    exists to prevent, and silently reformatting it would hide the caller's bug.
    """
    if not _SLUG_RE.match(slug):
        raise ValueError(
            f"slug {slug!r} does not match the frozen packet id shape "
            "<pool>-<RUNG>-<5 digits>; a differently-shaped id is an arm label")
    if not items:
        raise ValueError("empty item list: an arm that carries no items must not carry a packet")
    return TEMPLATE.format(slug=slug, items=", ".join(items),
                           sparsity=sparsity or MODAL_SPARSITY)


def slug_for(uid):
    """`nearmiss_mix-M30-00007` -> `nearmiss_mix-M30-00007` (already correct shape)."""
    return uid


def synthetic_slug(rung, index, pool=None):
    """A slug for arms with no task provenance (generic, method-hint).

    CAUGHT ON THE FIRST TEST OF THIS FILE: my initial version took a `pool` argument and
    produced `generic_pool-M30-00007`. The *shape* matched a real id, so the framing check
    passed — and the literal token `generic_pool` is a plain-text arm label readable by any
    reader. That is precisely the leak this module claims to prevent, written into the module
    itself, and the framing check could never have caught it because framing checks erase
    words by design.

    So the pool token is now FIXED and shared: every arm's slug is indistinguishable from a
    real task id. The index is drawn from the arm's own sequence, so it carries nothing about
    the target task.
    """
    if pool is not None:
        raise ValueError(
            "a per-arm pool token is an arm label in plain text; the pool is fixed and shared")
    return f"{POOL}-{rung}-{index % 100000:05d}"


def template_regex():
    """The template as an exact matcher, built FROM the template so the two cannot drift.

    Supersedes the `framing_skeleton` heuristic for this purpose. That abstraction erased
    words to compare shape and could not tell a one-item list from a five-item one, so arms
    whose item counts were distributed differently looked shape-different when they were
    generated by the identical template. Matching the template directly is decidable and
    needs no abstraction: either the packet came from this frame, or it did not.
    """
    head, rest = TEMPLATE.split("{slug}")
    mid, tail = rest.split("{items}")
    pre, post = tail.split("{sparsity}")
    pat = (re.escape(head)
           + "(?P<slug>[^ \\]]+)"
           + re.escape(mid)
           + "(?P<items>[^\\n]+)"
           + re.escape(pre)
           + "(?P<sparsity>.*)"
           + re.escape(post))
    return re.compile(pat, re.S)


def matches_template(payload):
    """True iff `payload` was produced by TEMPLATE. Returns (ok, slots)."""
    m = template_regex().fullmatch(payload.strip())
    return (m is not None), (m.groupdict() if m else {})
