"""Extract the legacy post-processing helpers from agents/hephaestus/src/hephaestus.py
by AST, byte-for-byte, into legacy_helpers.py -- WITHOUT importing that module
(importing it opens a FileHandler on agents/hephaestus/hephaestus.log, which
would write into the frozen 1.0 corpus).

Run from the worktree root: python hephaestus/xpol_2026/build_legacy_helpers.py
"""
from __future__ import annotations
import ast, hashlib, subprocess, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "agents/hephaestus/src/hephaestus.py"
OUT = Path(__file__).resolve().parent / "legacy_helpers.py"
WANT = ["_IMPORT_FIXES", "_sanitize_unicode", "_inject_missing_imports", "_fix_common_errors"]


def main() -> None:
    text = SRC.read_text(encoding="utf-8")
    tree = ast.parse(text)
    lines = text.splitlines(keepends=True)
    pieces = {}
    for node in tree.body:
        name = None
        if isinstance(node, ast.FunctionDef):
            name = node.name
        elif isinstance(node, ast.Assign) and len(node.targets) == 1 and isinstance(node.targets[0], ast.Name):
            name = node.targets[0].id
        elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            name = node.target.id
        if name in WANT:
            pieces[name] = "".join(lines[node.lineno - 1: node.end_lineno])
    missing = [w for w in WANT if w not in pieces]
    if missing:
        sys.exit(f"missing {missing}")
    sha = hashlib.sha256(text.encode("utf-8")).hexdigest()
    try:
        blob = subprocess.run(["git", "rev-parse", "HEAD"], cwd=ROOT, capture_output=True, text=True, timeout=30).stdout.strip()
    except Exception:
        blob = "?"
    header = (
        '"""Legacy Hephaestus 1.0 post-processing helpers, extracted verbatim by AST from\n'
        f"agents/hephaestus/src/hephaestus.py (sha256 {sha[:16]}, tree {blob[:12]}).\n"
        "Generated by build_legacy_helpers.py; do not edit by hand. The source module is\n"
        "not imported because its import opens a log FileHandler inside the frozen corpus.\n"
        '"""\n'
        "from __future__ import annotations\n\n"
    )
    OUT.write_text(header + "\n\n".join(pieces[w] for w in WANT) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({len(pieces)} objects) from {SRC.name} sha256 {sha[:16]}")


if __name__ == "__main__":
    main()
