"""Legacy Hephaestus 1.0 post-processing helpers, extracted verbatim by AST from
agents/hephaestus/src/hephaestus.py (sha256 5359d8a6750cd811, tree 542f31b91586).
Generated by build_legacy_helpers.py; do not edit by hand. The source module is
not imported because its import opens a log FileHandler inside the frozen corpus.
"""
from __future__ import annotations

_IMPORT_FIXES: dict[str, str] = {
    "List": "from typing import List",
    "Dict": "from typing import Dict",
    "Tuple": "from typing import Tuple",
    "Set": "from typing import Set",
    "Optional": "from typing import Optional",
    "Union": "from typing import Union",
    "Any": "from typing import Any",
    "Callable": "from typing import Callable",
    "Sequence": "from typing import Sequence",
    "defaultdict": "from collections import defaultdict",
    "Counter": "from collections import Counter",
    "deque": "from collections import deque",
    "dataclass": "from dataclasses import dataclass",
    "field": "from dataclasses import field",
    "ABC": "from abc import ABC",
    "abstractmethod": "from abc import abstractmethod",
}


def _sanitize_unicode(code: str) -> str:
    """Replace non-ASCII characters that crash Windows cp1252 encoding.

    LLMs frequently emit Unicode math symbols (≥, ≈, →, ∈, etc.) in
    strings and comments. These crash on Windows when written to files
    or printed to console with cp1252 encoding.
    """
    replacements = {
        "\u2248": "~=",   # ≈
        "\u2265": ">=",   # ≥
        "\u2264": "<=",   # ≤
        "\u2260": "!=",   # ≠
        "\u2192": "->",   # →
        "\u2190": "<-",   # ←
        "\u2208": "in",   # ∈
        "\u2209": "not in",  # ∉
        "\u221e": "inf",  # ∞
        "\u00d7": "*",    # ×
        "\u00f7": "/",    # ÷
        "\u2212": "-",    # −
        "\u03b1": "alpha",  # α
        "\u03b2": "beta",   # β
        "\u03b3": "gamma",  # γ
        "\u03b4": "delta",  # δ
        "\u03b5": "epsilon",  # ε
        "\u03bb": "lambda_",  # λ
        "\u03c0": "pi",   # π
        "\u03c3": "sigma",  # σ
        "\u03c4": "tau",   # τ
        "\u2026": "...",  # …
        "\u201c": '"',    # "
        "\u201d": '"',    # "
        "\u2018": "'",    # '
        "\u2019": "'",    # '
    }
    for char, replacement in replacements.items():
        code = code.replace(char, replacement)
    # Catch any remaining non-ASCII in string literals/comments
    # (leave actual Python identifiers alone)
    return code


def _inject_missing_imports(code: str) -> str:
    """Scan generated code for bare names used without import and prepend them.

    Only injects safe stdlib/typing imports. If the code already imports the
    name (directly or via wildcard), it is left alone.  Consolidates multiple
    names from the same module into a single import line.

    Also injects 'import numpy as np' if 'np.' is used without an existing
    numpy import, and similar for other allowed third-party libraries.
    """
    import re

    # --- Aliased third-party + stdlib module imports ---
    _ALIAS_FIXES = [
        (r'\bnp\.', "import numpy as np", "numpy"),
        (r'\bnx\.', "import networkx as nx", "networkx"),
        (r'\bscipy\.', "import scipy", "scipy"),
        (r'\bsympy\.', "import sympy", "sympy"),
        # Stdlib modules commonly used bare
        (r'\bre\.', "import re", "re"),
        (r'\bmath\.', "import math", "math"),
        (r'\bjson\.', "import json", "json"),
        (r'\bitertools\.', "import itertools", "itertools"),
        (r'\bfunctools\.', "import functools", "functools"),
        (r'\bcollections\.', "import collections", "collections"),
        (r'\bzlib\.', "import zlib", "zlib"),
        (r'\bstring\.', "import string", "string"),
        (r'\brandom\.', "import random", "random"),
        (r'\bcopy\.', "import copy", "copy"),
        (r'\boperator\.', "import operator", "operator"),
    ]
    alias_lines = []
    for pattern, import_line, module in _ALIAS_FIXES:
        if re.search(pattern, code) and import_line not in code and f"import {module}" not in code:
            alias_lines.append(import_line)

    # --- Stdlib/typing name imports ---
    by_module: dict[str, list[str]] = {}  # module -> [names]
    for name, import_line in _IMPORT_FIXES.items():
        if import_line in code:
            continue
        module = import_line.split("from ")[-1].split(" import")[0]
        if f"import {module}" in code and f"from {module}" not in code:
            continue
        if re.search(rf'\b{name}\b', code):
            by_module.setdefault(module, []).append(name)

    stdlib_lines = []
    for module in sorted(by_module):
        names = sorted(by_module[module])
        stdlib_lines.append(f"from {module} import {', '.join(names)}")

    all_injections = alias_lines + stdlib_lines
    if not all_injections:
        return code

    return "\n".join(all_injections) + "\n\n" + code


def _fix_common_errors(code: str) -> str:
    """Fix common LLM code-gen errors that cause gate failures.

    Applied after import injection and Unicode sanitization. Handles:
    1. Missing confidence() method — inject a default stub
    2. Confidence returning None/bad type — append a safe wrapper
    3. Evaluate returning None — append a safe wrapper
    """
    import re as _re
    import ast

    if "class ReasoningTool" not in code:
        return code

    try:
        tree = ast.parse(code)
    except SyntaxError:
        return code  # Can't fix what won't parse

    for node in ast.walk(tree):
        if isinstance(node, ast.ClassDef) and node.name == "ReasoningTool":
            method_names = [
                n.name for n in node.body
                if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef))
            ]

            # 1. Missing confidence() — inject a default that delegates to evaluate()
            if "confidence" not in method_names and "evaluate" in method_names:
                stub = '''
    def confidence(self, prompt: str, answer: str) -> float:
        """Default confidence via evaluate()."""
        try:
            results = self.evaluate(prompt, [answer])
            if results:
                return max(0.0, min(1.0, float(results[0].get("score", 0.5))))
        except Exception:
            pass
        return 0.5
'''
                # Find end of class body and insert
                lines = code.split('\n')
                class_end = len(lines)
                indent_level = None
                in_class = False
                for i, line in enumerate(lines):
                    if 'class ReasoningTool' in line:
                        in_class = True
                        indent_level = len(line) - len(line.lstrip())
                        continue
                    if in_class and indent_level is not None and line.strip():
                        if not line[0:1].isspace() and i > 0:
                            class_end = i
                            break
                lines.insert(class_end, stub)
                code = '\n'.join(lines)

            # 2. Wrap confidence() to guarantee float return in [0,1]
            # Appended after the class — catches None returns, exceptions, out-of-range
            if "confidence" in method_names or "confidence" not in method_names:
                wrapper = '''

# --- Auto-fix: ensure confidence() returns float in [0, 1] ---
_orig_confidence = ReasoningTool.confidence
def _safe_confidence(self, prompt, answer):
    try:
        result = _orig_confidence(self, prompt, answer)
        if result is None:
            return 0.5
        return max(0.0, min(1.0, float(result)))
    except (TypeError, ValueError):
        return 0.5
ReasoningTool.confidence = _safe_confidence
'''
                if "_safe_confidence" not in code:
                    code = code.rstrip() + "\n" + wrapper

            # 3. Wrap evaluate() to guarantee list[dict] return
            eval_wrapper = '''

# --- Auto-fix: ensure evaluate() returns list[dict] ---
_orig_evaluate = ReasoningTool.evaluate
def _safe_evaluate(self, prompt, candidates):
    try:
        result = _orig_evaluate(self, prompt, candidates)
        if result is None:
            return [{"candidate": c, "score": 0.5, "reasoning": "fallback"} for c in candidates]
        if not isinstance(result, list):
            return [{"candidate": c, "score": 0.5, "reasoning": "fallback"} for c in candidates]
        return result
    except Exception:
        return [{"candidate": c, "score": 0.5, "reasoning": "error"} for c in candidates]
ReasoningTool.evaluate = _safe_evaluate
'''
            if "_safe_evaluate" not in code:
                code = code.rstrip() + "\n" + eval_wrapper
            break

    return code

