"""Generate the commit benchmark CB-200 (PAN-31): queries Pan did not write.

Rule (frozen 2026-10-09, before any v2 run):
  population  commits reachable from the catalog SHA, committed on or after
              2026-08-01, single parent, 1..6 files changed, whose subject has
              >= 30 characters after stripping a leading "Word[...]:" or
              "Word:" prefix, and which touched at least one file that still
              exists at the catalog SHA with n_chunks > 0 and kind NOT IN
              (journal, status) -- the answer set
  query       the stripped subject, verbatim
  answers     those touched, still-existing, chunked, non-journal/status files
  sample      200 commits ordered by md5(sha || 'pan-cb200-2026-10-09')
Metric: recall@10 = any answer path in the top 10 artifacts. Run v1 and v2 on
the same 200 queries (paired). The subject was written by the committing seat,
not by Pan; the task is "find the files of the change described".

python -m pan.tests.make_commit_bench  -> pan/tests/commit_bench_cb200.json
"""
import json
import os
import re
from pathlib import Path

PREFIX = re.compile(r"^\s*[A-Za-z][A-Za-z0-9_-]*(\[[^\]]*\])?\s*:\s*")


def main():
    os.environ.setdefault("EW_DB_HOST", "192.168.1.202")
    from pan import db
    with db.cursor() as cur:
        cur.execute("""
          with c as (
            select sha, subject from pan.commit
            where committed_at >= '2026-08-01' and array_length(parents, 1) = 1 and n_files between 1 and 6),
          ans as (
            select c.sha, c.subject, array_agg(distinct cf.path order by cf.path) as answers
            from c join pan.commit_file cf on cf.sha = c.sha
            join pan.artifact a on a.source = 'git' and a.path = cf.path
            where a.n_chunks > 0 and a.kind not in ('journal', 'status')
            group by c.sha, c.subject)
          select sha, subject, answers from ans
          order by md5(sha || 'pan-cb200-2026-10-09')""")
        rows = cur.fetchall()
        cur.execute("select git_sha from pan.run where kind='inventory' and status='OK' order by started_at desc limit 1")
        sha = cur.fetchone()[0]
    out = []
    for h, subj, answers in rows:
        q = PREFIX.sub("", subj, count=1).strip()
        if len(q) < 30:
            continue
        out.append(dict(id="C" + h[:9], type="commit", q=q, answers=answers, commit=h))
        if len(out) == 200:
            break
    spec = {"_prereg": [
        "CB-200, generated by pan/tests/make_commit_bench.py (rule in its docstring) on 2026-10-09 BEFORE",
        "any v2 run, against the catalog at {}. Queries are commit subjects written by other seats.".format(sha),
        "Paired comparison v1 vs v2 on the same queries; report recall@10 for each and the discordant counts.",
        "No pass bar is claimed from this set; it measures, it does not certify."],
        "eligible_population": len(rows), "queries": out}
    p = Path(__file__).resolve().parent / "commit_bench_cb200.json"
    p.write_text(json.dumps(spec, indent=1, ensure_ascii=True) + "\n", encoding="utf-8", newline="\n")
    print("eligible", len(rows), "written", len(out), "->", p)


if __name__ == "__main__":
    main()
