"""Amendment A (prereg v3 s0/s4.1): the BEE fixture pack for the production world of r004041 (BYTECODE32 -> L = 32, SEPARATED
layout: region (0,16) then (16,32), budget 128 each, no COPYALL; frozen VM git 16fc6c2a).

Each fixture is an exact pre-execution memory image, with EXPECTED labels written here by hand from the fixture's semantics (not
generated by the tracer). Validation, all executed on the frozen VM:
  (1) the reference tracer (bee_ref_tracer.py) reproduces every expected label and property;
  (2) the per-byte flip test passes on every written MOVE locus;
  (3) mutation testing: every mutant tracer fails at least one applicable fixture.
Inapplicable in this world, with the reason: K3, K16, K24, K25 (the PC is confined to the writer's own half-regions in SEPARATED,
so no partner/input/window code executes); K10-COPYALL, K27 (no COPYALL in BYTECODE32); K9, K18, K19 (world-level mutation,
ordering and structural moves: the owner's fixtures, not VM images); K20, K21, K28-K30 (NPE only).
    python -m archaeon.attribution.bee_fixtures      (prints the validation table; exit 1 on any failure)
"""
from __future__ import annotations

import sys

from archaeon.attribution import bee_ref_tracer as T

WORLD = {"L": 32, "layout": "SEPARATED", "budget": 256, "allow_copyall": False}
L = 32


def V():
    return T.vm16()


def image(code1, code2=b"", occ=None, inputs=(7,)):
    """writer = code1 padded to 16 (region 1) + code2 padded to 16 (region 2); padding is HALT so region 2 does nothing unless
    code2 is given; occupant bytes are fixed (not random) so expectations are exact."""
    v = V()
    w = bytes(code1) + bytes([v.HALT]) * (16 - len(code1)) + bytes(code2) + bytes([v.HALT]) * (16 - len(code2))
    assert len(w) == 32
    o = bytes(occ) if occ is not None else bytes((0x90 + i) & 0xFF for i in range(L))   # 0x90.. are undefined opcodes (NOP)
    m = bytearray(256); m[:L] = w; m[L:2 * L] = o
    for k, x in enumerate(inputs): m[v.IN_BASE + k] = x
    return m, list(inputs)


def E(e, i): return ("E", e, i)


def fixtures():
    v = V(); F = {}
    # K1 exact self-copy
    m, x = image([v.LD_S_n, 0, v.LD_T_n, 32, v.LD_C_n, 32, v.LDIR])
    F["K1_exact_self_copy"] = (m, x, {"data": {i: E("W", i) for i in range(32)}, "identified": list(range(32))})
    # K2 scratch copy: partner[0:8] -> scratch 0x80 -> window[8:16]
    m, x = image([v.LD_S_n, 32, v.LD_T_n, 0x80, v.LD_C_n, 8, v.LDIR, v.LD_S_n, 0x80, v.LD_T_n, 40, v.LD_C_n, 8, v.LDIR])
    F["K2_scratch_copy"] = (m, x, {"data": {**{i: E("P", i - 8) for i in range(8, 16)}, **{i: E("P", i) for i in range(0, 8)}},
                                   "written": list(range(8, 16)), "unwritten": list(range(0, 8)) + list(range(16, 32))})
    # K4 shifted copy by 4
    m, x = image([v.LD_S_n, 0, v.LD_T_n, 36, v.LD_C_n, 28, v.LDIR])
    F["K4_shift4"] = (m, x, {"data": {**{i: E("W", i - 4) for i in range(4, 32)}, **{i: E("P", i) for i in range(4)}},
                             "written": list(range(4, 32))})
    # K5 self-painter: store own operand (locus 1) into window[0:16]
    m, x = image([v.LD_A_n, 0x5A, v.LD_T_n, 32, v.LD_B_n, 16, v.LD_pT_A, v.INC_T, v.DJNZ_d, 0xFC])
    F["K5_self_painter"] = (m, x, {"data": {i: E("W", 1) for i in range(16)}, "identified": list(range(16))})
    # K6 computed byte: window[0] = partner[1] + partner[2]
    m, x = image([v.LD_S_n, 33, v.LD_A_pS, v.LD_B_A, v.LD_S_n, 34, v.LD_A_pS, v.ADD_A_B, v.LD_T_n, 32, v.LD_pT_A])
    F["K6_computed"] = (m, x, {"data": {0: ("COMPUTED", frozenset({E("P", 1), E("P", 2)}))}, "written": [0]})
    # K7 retention: write half the window
    m, x = image([v.LD_S_n, 0, v.LD_T_n, 32, v.LD_C_n, 16, v.LDIR])
    F["K7_retention"] = (m, x, {"data": {**{i: E("W", i) for i in range(16)}, **{i: E("P", i) for i in range(16, 32)}},
                                "written": list(range(16)), "unwritten": list(range(16, 32))})
    # K8 literal equal to the occupant's byte 0 -> the writer's operand locus (1), not the occupant
    occ = bytes((0x90 + i) & 0xFF for i in range(L))
    m, x = image([v.LD_A_n, occ[0], v.LD_T_n, 32, v.LD_pT_A], occ=occ)
    F["K8_value_coincidence"] = (m, x, {"data": {0: E("W", 1)}, "written": [0]})
    # K10 overlapping LDIR (T = S+1): window[1..16] all smear partner locus 0
    m, x = image([v.LD_S_n, 32, v.LD_T_n, 33, v.LD_C_n, 16, v.LDIR])
    F["K10_overlap_ldir"] = (m, x, {"data": {i: E("P", 0) for i in range(1, 17)}, "written": list(range(1, 17))})
    # K11 control-flow copy: A counts up to partner[0] via DJNZ (partner[0] = 5)
    occ = bytes([5]) + bytes((0x90 + i) & 0xFF for i in range(1, L))
    m, x = image([v.LD_S_n, 32, v.LD_A_pS, v.LD_B_A, v.LD_A_n, 0, v.INC_A, v.DJNZ_d, 0xFD, v.LD_T_n, 33, v.LD_pT_A], occ=occ)
    F["K11_control_flow_copy"] = (m, x, {"value": {1: 5}, "data_kind": {1: "COMPUTED_FROM"}, "ctrl_has": {1: E("P", 0)},
                                         "not_identified": [1]})
    # K12 translation table: window[1] = writer[partner[0]] with partner[0] = 20
    occ = bytes([20]) + bytes((0x90 + i) & 0xFF for i in range(1, L))
    m, x = image([v.LD_S_n, 32, v.LD_A_pS, v.LD_S_A, v.LD_A_pS, v.LD_T_n, 33, v.LD_pT_A], occ=occ)
    F["K12_translation_table"] = (m, x, {"data": {1: E("W", 20)}, "addr_has": {1: E("P", 0)}, "not_identified": [1]})
    # K13 input laundering: writer locus 15 -> input byte 0xE0 -> IN A -> window[0]
    m, x = image([v.LD_S_n, 15, v.LD_A_pS, v.LD_T_n, 0xE0, v.LD_pT_A, v.IN_A, v.LD_T_n, 32, v.LD_pT_A])
    F["K13_input_laundering"] = (m, x, {"data": {0: E("W", 15)}, "written": [0]})
    # K14 OUT store read back: partner[0] -> OUT -> read 0xF0 -> window[1]
    m, x = image([v.LD_S_n, 32, v.LD_A_pS, v.OUT_A, v.LD_S_n, 0xF0, v.LD_A_pS, v.LD_T_n, 33, v.LD_pT_A])
    F["K14_out_readback"] = (m, x, {"data": {1: E("P", 0)}, "written": [1]})
    # K15 uninitialised register -> RESET
    m, x = image([v.LD_T_n, 32, v.LD_pT_A])
    F["K15_reset_register"] = (m, x, {"data": {0: ("RESET", "A")}, "not_identified": [0]})
    # K17 LDIR source wrap: S = 0xF8 .. 0x07 -> window[0:8] OTHER 0xF8.., window[8:16] writer 0..7
    m, x = image([v.LD_S_n, 0xF8, v.LD_T_n, 32, v.LD_C_n, 16, v.LDIR])
    F["K17_ldir_wrap"] = (m, x, {"data": {**{i: ("OTHER", 0xF8 + i) for i in range(8)}, **{i: E("W", i - 8) for i in range(8, 16)}}})
    # K22 guard NOT taken: CP partner[0] with 0xFF (not equal) -> JZ not taken -> copy happens; ctrl has partner 0
    m, x = image([v.LD_S_n, 32, v.LD_A_pS, v.CP_A_n, 0xFF, v.JZ_n, 15, v.LD_S_n, 0, v.LD_T_n, 32, v.LD_C_n, 16, v.LDIR])
    F["K22_guard_not_taken"] = (m, x, {"data": {i: E("W", i) for i in range(16)}, "ctrl_has": {i: E("P", 0) for i in range(16)},
                                       "not_identified": list(range(16))})
    # K23 operand cipher: window[0] = partner[0] + 0x40 (operand at writer locus 4)
    m, x = image([v.LD_S_n, 32, v.LD_A_pS, v.ADD_A_n, 0x40, v.LD_T_n, 32, v.LD_pT_A])
    F["K23_operand_cipher"] = (m, x, {"data": {0: ("COMPUTED", frozenset({E("P", 0), E("W", 4)}))}})
    # K26 LDIR C=0 over its own executing region: copies OTHER 0x40.. into 0.., then window 0x20.. gets OTHER 0x60..
    m, x = image([v.LD_S_n, 0x40, v.LD_T_n, 0, v.LD_C_n, 0, v.LDIR])
    F["K26_ldir_self_overwrite"] = (m, x, {"data": {i: ("OTHER", 0x60 + i) for i in range(32)}})
    return F


def check_one(name, m, x, exp, bug=None):
    """returns a list of failure strings (empty = pass)."""
    fails = []
    _, recs, info = T.trace_world(m, WORLD, x, bug=bug)
    child = T.vm_world(bytearray(m), WORLD, x)[L:2 * L]
    for i, d in exp.get("data", {}).items():
        if recs[i]["data"] != d: fails.append("%s locus %d data %r != %r" % (name, i, recs[i]["data"], d))
    for i, k in exp.get("data_kind", {}).items():
        if recs[i]["data"][0] != k: fails.append("%s locus %d kind %s != %s" % (name, i, recs[i]["data"][0], k))
    for i, val in exp.get("value", {}).items():
        if child[i] != val: fails.append("%s locus %d value %d != %d" % (name, i, child[i], val))
    for key, f in (("ctrl_has", "ctrl"), ("addr_has", "addr")):
        for i, b in exp.get(key, {}).items():
            if b not in recs[i][f]: fails.append("%s locus %d %s lacks %r" % (name, i, f, b))
    for i in exp.get("written", []):
        if not recs[i]["written"]: fails.append("%s locus %d not written" % (name, i))
    for i in exp.get("unwritten", []):
        if recs[i]["written"]: fails.append("%s locus %d written" % (name, i))
    for i in exp.get("identified", []):
        if not T.identified(recs[i]): fails.append("%s locus %d not identified" % (name, i))
    for i in exp.get("not_identified", []):
        if T.identified(recs[i]): fails.append("%s locus %d identified" % (name, i))
    # every fixture's written loci must name the writer in exec (the executed code is the writer's in SEPARATED)
    for i, r in recs.items():
        if r["written"] and not any(b[0] == "E" and b[1] == "W" for b in r["exec"]): fails.append("%s locus %d exec lacks the writer" % (name, i))
    return fails, recs, info


MUTANTS = ["loc0", "reverse", "memmove", "ptrlabel", "noexec", "noctrl_untaken"]


def main():
    F = fixtures(); ok = True; rows = []
    for name, (m, x, exp) in F.items():
        fails, recs, info = check_one(name, m, x, exp)
        ft = T.flip_test(m, WORLD, x, recs, info["fetched"])
        cp = T.completeness(m, WORLD, x, recs, info["fetched"])
        unnamed = {a: v["unnamed_loci"] for a, v in cp.items() if v["unnamed_loci"]}
        good = not fails and ft["pass"] == ft["tested"] and not unnamed
        ok &= good
        rows.append((name, "PASS" if good else "FAIL", "flip %d/%d (skipped %d)" % (ft["pass"], ft["tested"], ft["skipped_code_and_data"]),
                     "completeness-unnamed %s" % (unnamed or "none"), fails[:3]))
    for r in rows: print(*r)
    print("\nmutation testing (each mutant must fail >= 1 fixture):")
    for bug in MUTANTS:
        caught = [n for n, (m, x, exp) in F.items() if check_one(n, m, x, exp, bug=bug)[0]]
        print("  %-15s caught by %s" % (bug, caught[:4] if caught else "NONE -- not detectable in this world"))
        if not caught and bug != "memmove": ok = False
    print("\nALL PASS" if ok else "\nFAILURES")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
