"""Render NURSERY.jsonl to NURSERY.md (reader), validate required fields, and report status counts.
Usage: python -m alien_circuitry.nursery.build_nursery_md   (writes NURSERY.md beside the JSONL; exits non-zero on schema error)
"""
from __future__ import annotations
import collections, json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
REQUIRED = ["id", "name", "status", "origin", "observed_tension", "candidate_mechanism", "consequential_claim", "verified_invariants", "boring_explanations",
            "failure_geometry", "cheapest_kill_experiment", "oracle_verifier", "expected_cost", "promotion_condition", "kill_condition", "descendant_if_positive",
            "descendant_if_negative", "relation_to_existing", "orthogonality", "provenance"]
STATUS_VOCAB = {"candidate", "specimen", "organ", "primitive-candidate", "killed", "parked"}


def load():
    rows = []
    with open(os.path.join(HERE, "NURSERY.jsonl"), encoding="utf-8") as f:
        for i, line in enumerate(f, 1):
            line = line.strip()
            if not line: continue
            r = json.loads(line)
            missing = [k for k in REQUIRED if k not in r]
            if missing: raise SystemExit(f"line {i} ({r.get('id')}): missing {missing}")
            for tok in str(r["status"]).replace(",", " ").replace("-in-AC01", "").replace("-elsewhere", "").split():
                if tok not in STATUS_VOCAB: raise SystemExit(f"line {i} ({r['id']}): status token {tok!r} not in {sorted(STATUS_VOCAB)}")
            rows.append(r)
    # append-only ledger: a later row with the same id supersedes the earlier one (must carry "supersedes"); the reader shows the latest
    latest = {}
    for r in rows:
        if r["id"] in latest and "supersedes" not in r: raise SystemExit(f"duplicate id {r['id']} without 'supersedes'")
        latest[r["id"]] = r
    return list(latest.values())


def render(rows):
    out = ["# Prometheus nursery (AC-01 harvest, 2026-09-13)", "",
           "Source of truth: `NURSERY.jsonl` (append-only; edit by adding a superseding row, never by rewriting history). This file is",
           "generated by `build_nursery_md.py`. Status vocabulary: candidate / specimen / organ / primitive-candidate / killed / parked.",
           "Evidence levels inside entries: OBSERVED (numbers in a committed file) / INFERRED / HYPOTHESIZED / UNTESTED.", "",
           "Charter constraints honoured: every entry names an oracle and a consumer-facing descendant; failure kinds stay distinct;",
           "no nursery measure is a fitness criterion; primitive promotion goes through `techne/registry/primitive_candidates/`, never a",
           "direct registry write.", ""]
    counts = collections.Counter(r["status"] for r in rows)
    out += ["## Status counts", ""] + [f"- {k}: {v}" for k, v in sorted(counts.items())] + [""]
    out += ["## Index", "", "ID       Name                                        Status", "-------  ------------------------------------------  -----------------------------"]
    for r in rows: out.append(f"{r['id']:8} {r['name']:42} {r['status']}")
    out.append("")
    for r in rows:
        out += [f"## {r['id']} {r['name']}", "", f"Status: {r['status']}", ""]
        o = r["origin"]; out += ["Origin: " + json.dumps(o, ensure_ascii=False), ""]
        for k in ("observed_tension", "candidate_mechanism", "consequential_claim"):
            out += [f"**{k.replace('_', ' ')}.** {r[k]}", ""]
        for k in ("verified_invariants", "boring_explanations", "failure_geometry", "relation_to_existing"):
            out += [f"**{k.replace('_', ' ')}.**"] + [f"- {x}" for x in r[k]] + [""]
        for k in ("cheapest_kill_experiment", "oracle_verifier", "expected_cost", "promotion_condition", "kill_condition", "descendant_if_positive", "descendant_if_negative", "orthogonality"):
            out += [f"**{k.replace('_', ' ')}.** {r[k]}", ""]
        for k in ("new_evidence", "verdict", "supersedes", "recorded"):
            if k in r: out += [f"**{k.replace('_', ' ')}.** {r[k]}", ""]
        out += ["Provenance: " + json.dumps(r["provenance"], ensure_ascii=False), ""]
    return "\n".join(out)


if __name__ == "__main__":
    rows = load()
    with open(os.path.join(HERE, "NURSERY.md"), "w", encoding="utf-8") as f: f.write(render(rows))
    print(f"ok: {len(rows)} entries; statuses {dict(collections.Counter(r['status'] for r in rows))}")
