#!/bin/bash
# Usage from ELSA/M2: ssh jcraig@<ip> "bash -s" < node_inventory.sh   (provision_node.sh runs it at the end)
# Read-only node inventory. Prints key=value lines; never prints secret values.
kv() { printf '%s=%s\n' "$1" "$2"; }
kv hostname "$(hostname)"
kv model "$(cat /sys/class/dmi/id/sys_vendor /sys/class/dmi/id/product_version 2>/dev/null | tr '\n' ' ')"
kv os "$(. /etc/os-release; echo $PRETTY_NAME)"
kv kernel "$(uname -r)"
kv uptime "$(uptime -p)"
kv cpu "$(nproc) threads"
kv ram "$(free -h | awk '/Mem:/{print $2" total, "$7" avail"}')"
kv disk_root "$(df -h / | awk 'NR==2{print $2" size, "$5" used"}')"
kv lv_free "$(sudo -n vgs --noheadings -o vg_free 2>/dev/null | tr -d ' ')"
kv net "$(ip -br -4 a | grep -v '^lo' | awk '{print $1":"$2":"$3}' | tr '\n' ' ')"
kv temp_max_C "$(cat /sys/class/thermal/thermal_zone*/temp 2>/dev/null | sort -n | tail -1 | awk '{print $1/1000}')"
kv reboot_required "$([ -f /var/run/reboot-required ] && echo yes || echo no)"
kv apt_upgradable "$(apt list --upgradable 2>/dev/null | grep -c upgradable)"
kv sudo_nopasswd "$(sudo -n true 2>/dev/null && echo yes || echo no)"
kv lid "$(cat /etc/systemd/logind.conf.d/10-server-lid.conf 2>/dev/null | grep -c ignore) ignore-lines"
kv battery_limit "$(cat /sys/class/power_supply/BAT0/charge_control_start_threshold 2>/dev/null)/$(cat /sys/class/power_supply/BAT0/charge_control_end_threshold 2>/dev/null)"
kv battery_svc "$(systemctl is-enabled battery-charge-limit.service 2>/dev/null)"
kv battery_pct "$(cat /sys/class/power_supply/BAT0/capacity 2>/dev/null)%"
kv wifi_ps_svc "$(systemctl list-unit-files 'wifi-powersave-off*' --no-legend 2>/dev/null | awk '{print $1":"$2}' | tr '\n' ' ')"
kv linger "$(loginctl show-user jcraig -p Linger --value 2>/dev/null)"
kv claude "$(~/.local/bin/claude --version 2>/dev/null)"
kv claude_logged_in "$([ -s ~/.claude/.credentials.json ] && echo yes || echo no)"
kv claude_env_file "$([ -f ~/.config/prometheus/claude.env ] && echo "present, vars: $(grep -o '^[A-Z_]*' ~/.config/prometheus/claude.env | tr '\n' ' ')" || echo absent)"
kv rc_services "$(systemctl --user list-units 'claude-rc*' --all --no-legend 2>/dev/null | awk '{print $1":"$3"/"$4}' | tr '\n' ' ')"
kv rc_enabled "$(systemctl --user list-unit-files 'claude-rc*' --no-legend 2>/dev/null | awk '{print $1":"$2}' | tr '\n' ' ')"
kv user_units "$(ls ~/.config/systemd/user/ 2>/dev/null | tr '\n' ' ')"
kv user_timers "$(systemctl --user list-timers --all --no-legend 2>/dev/null | awk '{print $(NF-1)}' | tr '\n' ' ')"
kv tmux_sessions "$(tmux ls 2>/dev/null | cut -d: -f1 | tr '\n' ' ')"
kv scripts_home "$(ls ~/*.sh ~/bin 2>/dev/null | tr '\n' ' ')"
kv repo_head "$(git -C ~/Prometheus log -1 --format='%h %cs' 2>/dev/null)"
kv repo_branch "$(git -C ~/Prometheus branch --show-current 2>/dev/null)"
kv repo_dirty "$(git -C ~/Prometheus status --porcelain 2>/dev/null | wc -l) files"
kv repo_behind "$(git -C ~/Prometheus fetch -q 2>/dev/null; git -C ~/Prometheus rev-list --count HEAD..@{u} 2>/dev/null)"
kv git_user "$(git config --global user.name) <$(git config --global user.email)>"
kv git_pullff "$(git config --global pull.ff)"
kv gh "$(gh --version 2>/dev/null | head -1 | awk '{print $3}')"
kv gh_auth "$(gh auth status 2>&1 | grep -o 'Logged in to github.com account [a-z0-9]*' )"
kv gh_cred_helper "$(git config --global --get-all credential.https://github.com.helper | tr '\n' ' ')"
kv authorized_keys "$(awk '{print $NF}' ~/.ssh/authorized_keys | tr '\n' ' ')"
kv ssh_keys_own "$(ls ~/.ssh/*.pub 2>/dev/null | xargs -n1 basename 2>/dev/null | tr '\n' ' ')"
kv EW_DB_HOST "$(bash -lc 'echo $EW_DB_HOST')"
kv python "$(python3 --version 2>&1)"
kv node "$(node --version 2>/dev/null || echo none)"
kv pkgs "$(for p in git curl htop tmux iw gh jq python3-venv python3-pip postgresql-client; do dpkg -s $p >/dev/null 2>&1 && printf '%s ' $p || printf '!%s ' $p; done)"
kv unattended_upgrades "$(systemctl is-enabled unattended-upgrades 2>/dev/null)"
kv timezone "$(timedatectl show -p Timezone --value)"
kv ntp_synced "$(timedatectl show -p NTPSynchronized --value)"
kv swap "$(swapon --show=SIZE --noheadings | tr '\n' ' ')"
kv failed_units "$(systemctl --failed --no-legend | awk '{print $2}' | tr '\n' ' ')"
