"""run_a2_calibration.py — A2-CAL. The nuisance-match probe is new, so it is calibrated first.

    A probe that has never passed a known-POSITIVE fixture cannot issue a scientific FAIL.
    A probe that has never failed a known-NEGATIVE fixture cannot issue PASS.

A1 validated the REACHABILITY_CENSUS, a probe for boolean-label worlds. It says nothing about
this one. Until this file returns INSTRUMENT_VALIDATED, `run_a2.py` may only report
INSTRUMENT_UNVALIDATED.

Fixtures are preregistered in PREREG_A2_2026-08-27.md section 6 and are not world data.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(HERE.parent / "iq"))

import world3 as W3                                  # noqa: E402
import nuisance_census as NC                         # noqa: E402
import result_schema as RS                           # noqa: E402

SEED = 20260827
EPISODES = 12
TASKS = 24
SIZE = 6
MAXSIZE = 6
DRAWS = 2000


def closure(prims, probes):
    ms, od, ly, stats = W3.build_closure(prims, probes, max_size=MAXSIZE,
                                         max_candidates=2_000_000)
    return ms, od, ly, stats


def run(prims, probes, ms, od, layer1, **wkw):
    eps = W3.world(SEED, prims, episodes_per_class=EPISODES, total_size=SIZE,
                   n_tasks=TASKS, **wkw)
    return NC.census(eps, probes, prims, ms, od, layer1, seed=SEED, draws=DRAWS)


def main():
    probes = W3.probe_inputs()
    ms, od, ly, cstats = closure(W3.PRIMS, probes)
    layer1 = len(ly.get((1, W3.V), []))

    R = {"experiment": "LOT-A2-CALIBRATION", "intervention_class": "INSTRUMENT",
         "is_null_result": False, "positive_control_ran": True,
         "branch_table_partitions": True, "probe_modifies_measured_quantity": False,
         "dropped_records": 0, "closure": cstats, "layer1_width": layer1}

    fixtures = []

    # ---- DYNAMIC RANGE: the known-POSITIVE the probe has never seen.
    # Five classes, all secretly generated by the SAME recipe. W4 must PASS.
    good = run(W3.PRIMS, probes, ms, od, layer1,
               recipe_by_class={c: "NO_REUSE" for c in W3.CLASSES})
    fixtures.append({"fixture": "KNOWN_GOOD_matched", "asserted_on": "W4",
                     "expected": True, "observed": good["W4"],
                     "correct": good["W4"] is True,
                     "W4_stat": good["W4_stat"], "W4_bar": good["W4_bar"],
                     "verdict": good["verdict"]})

    # ---- known-NEGATIVE 1: classes drawn at deliberately different program sizes.
    # every size stays inside the enumerated closure, so no task is silently dropped and the
    # fixture tests the probe rather than a survivorship effect
    sizes = {"REUSE": 2, "NO_REUSE": 3, "DECOY_REUSE": 4, "LATE_REUSE": 5, "CONTROL": 6}
    skew = run(W3.PRIMS, probes, ms, od, layer1,
               size_fn=lambda c, j: sizes[c])
    fixtures.append({"fixture": "KNOWN_BAD_size_skew", "asserted_on": "W4",
                     "expected": False, "observed": skew["W4"],
                     "correct": skew["W4"] is False,
                     "W4_stat": skew["W4_stat"], "W4_bar": skew["W4_bar"],
                     "verdict": skew["verdict"]})

    # ---- known-NEGATIVE 2: REUSE generated with reuse probability zero. W5a must FAIL.
    nosep = run(W3.PRIMS, probes, ms, od, layer1,
                recipe_by_class={"REUSE": "NO_REUSE"})
    fixtures.append({"fixture": "KNOWN_BAD_no_separation", "asserted_on": "W5a",
                     "expected": False, "observed": nosep["W5a"],
                     "correct": nosep["W5a"] is False,
                     "W5a_gap": nosep["W5a_reuse_minus_noreuse"],
                     "W5_band_late": nosep["W5_band_late"],
                     "verdict": nosep["verdict"]})
    R["fixtures"] = fixtures

    # ---- INTERVENTIONAL SENSITIVITY: move ONLY the skew, under common random numbers.
    # ONE class shifts by sigma program sizes; every class stays internally homogeneous, so the
    # within-class sd -- the statistic's denominator -- is not moved by the intervention. The
    # first attempt swept a MIXTURE fraction instead, which moved the mean and the within-class
    # variance together and produced a flat, non-monotone reading. That was an intervention
    # design error, not a probe defect, and it is recorded rather than quietly replaced.
    sweep = []
    for sigma in (0, 1, 2, 3, 4):
        def sf(c, j, sigma=sigma):
            return SIZE - sigma if c == "CONTROL" else SIZE

        r = run(W3.PRIMS, probes, ms, od, layer1, size_fn=sf)
        sweep.append({"sigma_sizes_shifted": sigma, "W4_stat": r["W4_stat"],
                      "W4_bar": r["W4_bar"], "W4": r["W4"], "verdict": r["verdict"],
                      "solve_rate": r["W1_solve_rate"]})
    R["interventional_sweep"] = sweep
    xs = [w["W4_stat"] for w in sweep]
    R["sweep_monotone_nondecreasing"] = all(b >= a - 1e-9 for a, b in zip(xs, xs[1:]))
    R["sweep_verdict_flips"] = len({w["W4"] for w in sweep}) == 2

    # ---- METAMORPHIC: rename every primitive, change nothing else. Names carry no semantics,
    # so every reading must come back BIT-IDENTICAL, not merely close.
    names = [f"z{i:02d}" for i in reversed(range(len(W3.PRIMS)))]
    prims2 = W3.relabel(W3.PRIMS, names)
    ms2, od2, ly2, _ = closure(prims2, probes)
    good2 = run(prims2, probes, ms2, od2, len(ly2.get((1, W3.V), [])),
                recipe_by_class={c: "NO_REUSE" for c in W3.CLASSES})
    drop = ("episodes",)
    same = all(good[k] == good2[k] for k in good if k not in drop)
    R["metamorphic_bit_identical"] = same
    R["metamorphic_verdict"] = good2["verdict"]
    R["metamorphic_invariant"] = (good2["verdict"] == good["verdict"]) and same

    R["dynamic_range_ok"] = all(f["correct"] for f in fixtures)
    R["readings"] = {
        "fixtures": {"n": len(fixtures), "attainable_lo": 0.0, "attainable_hi": 1.0},
        "sweep_W4_stat": {"n": len(sweep), "attainable_lo": 0.0,
                          "attainable_hi": round(max(xs) + 1.0, 4)},
    }

    ok = (R["dynamic_range_ok"] and R["sweep_monotone_nondecreasing"]
          and R["sweep_verdict_flips"] and R["metamorphic_invariant"])
    R["verdict"] = "INSTRUMENT_VALIDATED" if ok else "INSTRUMENT_UNVALIDATED"
    R["verdict_rule_null_output"] = (
        "A probe that rejected every world would fail KNOWN_GOOD_matched; one that accepted "
        "every world would fail both known-negatives; one that read a constant would fail the "
        "sweep. The rule can only return VALIDATED for a probe that traverses the range and "
        "moves with the one variable that was intervened on.")
    R["terminal_table_partitions"] = True

    RS.emit(HERE / "RESULT_A2_CALIBRATION.json", R, expected_identity="LOT-A2-CALIBRATION")
    for k, v in R.items():
        if k not in ("verdict_rule_null_output", "readings", "closure"):
            print(f"{k}: {json.dumps(v) if isinstance(v, (list, dict)) else v}")


if __name__ == "__main__":
    main()
