"""Gauge group for the polymul tensor T over F_2 with n = 3.

We use a discrete combinatorial subgroup of Aut(T) generated by three
involutions:

  SUB    — substitution x -> x + 1.
           Acts as (Ma, Mb, Mc) = ((M3^{-1})^T, (M3^{-1})^T, M5)
           where Mi[r, c] = C(c, r) is the lower-triangular Pascal matrix
           mod 2 in dimension i. Verified to preserve T.
  REV    — index reversal (anti-diagonal J).
           Acts as (J3, J3, J5). Verified to preserve T.
  SWAP   — commutativity p <-> q.
           Swaps modes 0 and 1 of T (and hence A <-> B in any decomp).
           Verified to preserve T.

SUB and REV do NOT commute. Their composition has order 3 on each mode,
so <SUB, REV> = D_3 (dihedral, order 6). SWAP commutes with everything
(it permutes the two identical input modes). The full group is therefore

  G = D_3 x Z_2 = order 12.

We enumerate all 12 elements explicitly by closing the generator set
under multiplication and verifying each preserves T.

Plus:
  S_r    — column permutation. Quotiented out by sorting columns.

Over F_2 the per-column scaling gauge (lambda*a, mu*b, lambda*mu*c) is
trivial since F_2^* = {1}. So the canonicalizer enumerates 12 group
elements, applies each, sorts columns, and takes lex-min serialization.

Why this gauge (and not a bigger one)
-------------------------------------
Aut(T) for polymul includes substitution x -> x + a for any a in F (over
F_2 only a in {0, 1} so 2 elements). The substitution x -> x + 1 generator
is an involution whose composition with reversal is the order-3 element
"swap and shift" (a hidden 3-fold symmetry of polymul over F_2 at n=3).
We do NOT include arbitrary GL_n(F_2) actions — those generally do NOT
preserve the polymul tensor (matmul does, polymul does not, because
polymul has the diagonal i+j=k structure which is broken by general
basis change).
"""
from __future__ import annotations
import itertools
import numpy as np
from math import comb

from .core import (
    POLYMUL_T, DIM_AB, DIM_C, N, is_polymul_decomp, sort_columns,
    decomp_to_bytes, column_keys,
)


# -----------------------------------------------------------------------------
# Generators
# -----------------------------------------------------------------------------

def _pascal(d: int) -> np.ndarray:
    """Pascal matrix M[j, i] = C(i, j) mod 2 (lower-triangular when written this way).

    Columns of M[j, i] indexed by i give (x+1)^i in y-basis.
    """
    M = np.zeros((d, d), dtype=np.int64)
    for i in range(d):
        for j in range(i + 1):
            M[j, i] = comb(i, j) & 1
    return M


def _inv_F2(M: np.ndarray) -> np.ndarray:
    """Inverse of an integer matrix mod 2 by Gauss-Jordan."""
    n = M.shape[0]
    aug = np.hstack([M.copy().astype(np.int64) & 1,
                     np.eye(n, dtype=np.int64)])
    for c in range(n):
        piv = None
        for r in range(c, n):
            if aug[r, c] & 1:
                piv = r
                break
        if piv is None:
            raise ValueError("not invertible mod 2")
        aug[[c, piv]] = aug[[piv, c]]
        for r in range(n):
            if r != c and (aug[r, c] & 1):
                aug[r] = (aug[r] ^ aug[c]) & 1
    return aug[:, n:].astype(np.uint8)


# Substitution generator
_M3_pascal = _pascal(DIM_AB).astype(np.uint8)
_M5_pascal = _pascal(DIM_C).astype(np.uint8)
_M3_inv_T = _inv_F2(_M3_pascal).T & 1   # action on input modes a, b
_M5_sub = _M5_pascal & 1                # action on output mode c

# Reversal generator (anti-diagonal)
_J3 = np.eye(DIM_AB, dtype=np.uint8)[::-1].copy()
_J5 = np.eye(DIM_C, dtype=np.uint8)[::-1].copy()


# -----------------------------------------------------------------------------
# Build full group (8 elements)
# -----------------------------------------------------------------------------

def _matmul_F2(X: np.ndarray, Y: np.ndarray) -> np.ndarray:
    return (X.astype(np.int64) @ Y.astype(np.int64) & 1).astype(np.uint8)


def _action_on_T(M_a: np.ndarray, M_b: np.ndarray, M_c: np.ndarray,
                 swap: bool) -> bool:
    """Check whether the action (M_a, M_b, M_c) (with optional p<->q swap)
    preserves the polymul tensor T."""
    T = POLYMUL_T.astype(np.int64)
    Tp = np.einsum('Ii,Jj,Kk,ijk->IJK',
                   M_a.astype(np.int64),
                   M_b.astype(np.int64),
                   M_c.astype(np.int64),
                   T) & 1
    if swap:
        Tp = Tp.transpose(1, 0, 2)
    return np.array_equal(Tp.astype(np.uint8), POLYMUL_T)


def build_gauge_actions():
    """Enumerate the 12-element gauge group D_3 x Z_2 by closing the
    generators {SUB, REV, SWAP} under multiplication.

    SUB and REV are involutions with composition of order 3, so <SUB, REV>
    = D_3 of order 6. SWAP commutes with both (since SUB and REV act
    identically on modes 0 and 1, swapping the two has no effect on the
    pair). Total: 6 * 2 = 12.

    Each element is encoded as (M_a, M_b, M_c, swap, label).
    """
    I3 = np.eye(DIM_AB, dtype=np.uint8)
    I5 = np.eye(DIM_C, dtype=np.uint8)

    # Atomic non-swap generators on (input_mode, output_mode).
    SUB = (_M3_inv_T, _M3_inv_T, _M5_sub)
    REV = (_J3, _J3, _J5)

    def _compose(g1, g2):
        """Compose two non-swap actions (M_a1, M_b1, M_c1) o (M_a2, M_b2, M_c2)
        meaning: apply g2 first then g1.
        """
        return (_matmul_F2(g1[0], g2[0]),
                _matmul_F2(g1[1], g2[1]),
                _matmul_F2(g1[2], g2[2]))

    # BFS-close the non-swap generators (SUB, REV) into a list of triples.
    seen = {}
    identity = (I3, I3, I5)
    queue = [(identity, "I")]
    seen[(identity[0].tobytes(), identity[1].tobytes(), identity[2].tobytes())] = identity

    def _key(g):
        return (g[0].tobytes(), g[1].tobytes(), g[2].tobytes())

    closed = [(identity, "I")]
    frontier = [(identity, "I")]
    gens = [(SUB, "S"), (REV, "R")]
    while frontier:
        new_frontier = []
        for g, lab in frontier:
            for gen, glab in gens:
                # Multiply gen * g (apply g first, then gen).
                ng = _compose(gen, g)
                nk = _key(ng)
                if nk not in seen:
                    seen[nk] = ng
                    closed.append((ng, lab + glab))
                    new_frontier.append((ng, lab + glab))
        frontier = new_frontier

    assert len(closed) == 6, (
        f"<SUB, REV> closure expected 6 elements (D_3); got {len(closed)}"
    )

    # Cross with swap: each non-swap action gets paired with swap=False, swap=True.
    actions = []
    for (g, lab) in closed:
        for swap_bit in (0, 1):
            M_a, M_b, M_c = g
            actions.append((M_a, M_b, M_c, bool(swap_bit), (lab, swap_bit)))
    return actions


GAUGE_ACTIONS = build_gauge_actions()
GAUGE_SIZE = len(GAUGE_ACTIONS)
assert GAUGE_SIZE == 12, f"gauge group size = 12 expected, got {GAUGE_SIZE}"

# Validate: every gauge element preserves T.
for (M_a, M_b, M_c, swap, label) in GAUGE_ACTIONS:
    assert _action_on_T(M_a, M_b, M_c, swap), (
        f"gauge element {label} fails to preserve polymul tensor"
    )


# -----------------------------------------------------------------------------
# Apply / canonicalize
# -----------------------------------------------------------------------------

def apply_gauge(U: np.ndarray, V: np.ndarray, W: np.ndarray, idx: int):
    """Apply the idx-th gauge element to a CP decomposition (U, V, W)."""
    M_a, M_b, M_c, swap, _ = GAUGE_ACTIONS[idx]
    U2 = _matmul_F2(M_a, U)
    V2 = _matmul_F2(M_b, V)
    W2 = _matmul_F2(M_c, W)
    if swap:
        U2, V2 = V2, U2
    return U2, V2, W2


def canonicalize(U: np.ndarray, V: np.ndarray, W: np.ndarray):
    """Compute canonical form under <SUB, REV, SWAP> x S_r.

    For each of 8 gauge elements: apply, drop zero columns, sort columns,
    serialize. Take lex-smallest.
    """
    best_bytes = None
    best_tuple = None
    for idx in range(GAUGE_SIZE):
        U2, V2, W2 = apply_gauge(U, V, W, idx)
        # Drop columns where any of {a, b, c} is identically zero
        # (such columns contribute zero to the tensor).
        nz = ~((U2.sum(0) == 0) | (V2.sum(0) == 0) | (W2.sum(0) == 0))
        U2 = U2[:, nz]
        V2 = V2[:, nz]
        W2 = W2[:, nz]
        if U2.shape[1] == 0:
            continue
        U2, V2, W2 = sort_columns(U2, V2, W2)
        b = decomp_to_bytes(U2, V2, W2)
        if best_bytes is None or b < best_bytes:
            best_bytes = b
            best_tuple = (U2.copy(), V2.copy(), W2.copy())
    return best_tuple, best_bytes


def effective_rank(U: np.ndarray, V: np.ndarray, W: np.ndarray) -> int:
    """Number of non-trivially-contributing columns."""
    nz = ~((U.sum(0) == 0) | (V.sum(0) == 0) | (W.sum(0) == 0))
    return int(nz.sum())


def orbit_size(U: np.ndarray, V: np.ndarray, W: np.ndarray) -> int:
    """Distinct canonical-sorted forms over the 8-element gauge."""
    seen = set()
    for idx in range(GAUGE_SIZE):
        U2, V2, W2 = apply_gauge(U, V, W, idx)
        nz = ~((U2.sum(0) == 0) | (V2.sum(0) == 0) | (W2.sum(0) == 0))
        U2 = U2[:, nz]; V2 = V2[:, nz]; W2 = W2[:, nz]
        if U2.shape[1] == 0:
            continue
        U2, V2, W2 = sort_columns(U2, V2, W2)
        seen.add(decomp_to_bytes(U2, V2, W2))
    return len(seen)


def stabilizer_order(U: np.ndarray, V: np.ndarray, W: np.ndarray) -> int:
    """|Stab(decomp)| in the 8-element gauge group, computed as
    |Iso| / |orbit| via orbit-stabilizer.
    """
    sz = orbit_size(U, V, W)
    if sz == 0:
        return 0
    return GAUGE_SIZE // sz
