"""
Build INDEX.md for the frontier campaign.

The corpus is now large enough that nobody will read it end to end. The index
is what makes it usable: one row per dossier with the numbers that decide
whether to open it, plus the cross-cutting tallies.

Everything here is COMPUTED from the artefacts, never asserted. If a number
appears in INDEX.md it came from a file on disk, so the index cannot drift
from the corpus the way a hand-maintained one would.

    python aporia/docs/frontier_campaign_69/build_index.py
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from validate import check  # noqa: E402

DOSSIERS = HERE / "dossiers"
REFIRES = HERE / "refires"
INVENTORY = HERE / "software_inventory.jsonl"

FIELD_RE = re.compile(r"^# Prompt \d+:\s*(.+?)\s*$", re.M)
VERDICT_RE = re.compile(
    r"\b(REPRODUCIBLE_WITH_EFFORT|NOT_REPRODUCIBLE|UNCERTAIN|REPRODUCIBLE)\b")
P5_RE = re.compile(r"^#*\s*PART 5\.", re.M)
P6_RE = re.compile(r"^#*\s*PART 6\.", re.M)


def field_of(path: Path) -> str:
    t = path.read_text(encoding="utf-8")
    m = FIELD_RE.search(t)
    return m.group(1) if m else path.stem[3:].replace("_", " ")


def recipe_len(path: Path) -> int:
    t = path.read_text(encoding="utf-8")
    a = P5_RE.search(t)
    if not a:
        return 0
    b = P6_RE.search(t, a.end())
    return len(t[a.end(): b.start() if b else len(t)].strip())


def main() -> int:
    rows = []
    for p in sorted(DOSSIERS.glob("*.md"), key=lambda q: int(q.name.split("_")[0])):
        r = check(p)
        rows.append({
            "n": int(p.name.split("_")[0]),
            "field": field_of(p),
            "file": p.name,
            "kb": len(p.read_text(encoding="utf-8")) // 1024,
            "ids": r["arxiv"] + r["doi"],
            "urls": r["urls"],
            "unk": r["unknown"],
            "recipe": recipe_len(p),
            "loss": len(r["value_loss"]),
        })

    refires = []
    for p in sorted(REFIRES.glob("*.md")):
        t = p.read_text(encoding="utf-8")
        m = VERDICT_RE.search(t)
        refires.append({
            "n": int(p.name.split("_")[0]),
            "file": p.name,
            "verdict": m.group(1) if m else "NO VERDICT FOUND",
            "kb": len(t) // 1024,
        })

    inv = {"MAINTAINED": 0, "DORMANT": 0, "ABANDONED": 0}
    entries = 0
    if INVENTORY.exists():
        for line in INVENTORY.read_text(encoding="utf-8").splitlines():
            if not line.strip():
                continue
            for e in json.loads(line)["entries"]:
                inv[e["verdict"]] = inv.get(e["verdict"], 0) + 1
                entries += 1

    out = []
    A = out.append
    A("# Frontier campaign — INDEX")
    A("")
    A("Generated by `build_index.py`. Every number below is computed from the")
    A("artefacts on disk, never asserted, so this file cannot drift from the")
    A("corpus. Re-run it after any new dossier lands.")
    A("")
    A("## What this corpus is")
    A("")
    A("One Deep Research dossier per field, asking what a practitioner would")
    A("read, install, download, reproduce and build to run frontier")
    A("experiments in 2026 — deliberately unshaped by the SFE bench, which is")
    A("what made the mined templates thin. Eight parts each; three are")
    A("load-bearing: software with liveness verdicts, one reproduction recipe")
    A("with a published number to check against, and negative results.")
    A("")
    A(f"**{len(rows)} dossiers. {len(refires)} reproducibility audits.**")
    A("")
    A("## Cross-cutting results")
    A("")
    A(f"- **Software inventory: {entries} entries** — "
      f"{inv['MAINTAINED']} MAINTAINED, {inv['DORMANT']} DORMANT, "
      f"{inv['ABANDONED']} ABANDONED. The dead fraction is "
      f"{100*(inv['DORMANT']+inv['ABANDONED'])//max(entries,1)}%, and it held "
      f"steady from 18 dossiers through the full sweep across five unrelated "
      f"tiers — a property of the tooling, not of the ordering.")
    A(f"- **Bracket damage: {sum(r['loss'] for r in rows)} candidate losses** "
      f"across the corpus; adjudicated in `bracket_losses.jsonl`, 2 real, the "
      f"rest inserted markers. Real losses are never repaired from inference.")
    A(f"- **Honest refusals: {sum(r['unk'] for r in rows)} IDENTIFIER "
      f"UNKNOWN** — the no-invention instruction is live, which is what makes "
      f"a refusal elsewhere meaningful.")
    A("")
    A("## Reproducibility audits")
    A("")
    A("These re-fire the ten Tier 5 fields whose original dossier gave a")
    A("recipe for a *different* system than the one asked about. The verdict")
    A("is the first line of each report.")
    A("")
    for r in refires:
        A(f"- **{r['verdict']}** — `{r['file']}` ({r['kb']}KB)")
    A("")
    A("## Dossiers")
    A("")
    A("`ids` = arXiv + DOI count. `unk` = honest refusals. `recipe` = PART 5")
    A("length in characters. A short recipe is worth checking by hand.")
    A("")
    for r in rows:
        A(f"- **{r['n']:02d} {r['field']}** — `{r['file']}` · {r['kb']}KB · "
          f"{r['ids']} ids · {r['urls']} urls · {r['unk']} unk · "
          f"recipe {r['recipe']}")
    A("")
    A("## How to use PART 5, and the caveat that must travel with it")
    A("")
    A("**A recipe is usable only when checked against the field the prompt")
    A("named.** Ten of 22 Tier 5 dossiers gave a complete recipe for a")
    A("different system, so the check is cheap, necessary, and one nobody")
    A("would think to run without this measurement. See")
    A("`PREREGISTRATION_recipe_hatch.md` for the count and the rule it was")
    A("filed under.")
    A("")
    A("Second caveat, from the campaign itself: **a dossier that AGREES with")
    A("its anchor is weaker evidence than one that CORRECTS it.** Every")
    A("anchor asserts what I believed the mechanism was, so agreement may be")
    A("my own framing returned. The corrections are the load-bearing returns.")

    (HERE / "INDEX.md").write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"wrote INDEX.md — {len(rows)} dossiers, {len(refires)} audits, "
          f"{entries} software entries")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
