"""
Tier oracle adapter -- lets Icarus climb Harmonia_M2_B's testable reasoning
ladder instead of the toy arithmetic tier tests.

Per James (2026-05-29): use the externally-authored ladder for climbing.
This is a strict upgrade over Icarus's hand-written tier tests + holdout:

  - The probes are PROCEDURALLY GENERATED (harmonia/experiments/reasoning_phase0.py),
    4 versions each (clean/iso/adversarial/transfer), so a held-out seed gives a
    blind oracle the Generator literally cannot memorize. (Solves Q9 + Q10.)
  - Grading is DETERMINISTIC and non-LLM via the verifier lens
    (harmonia/experiments/verifier_lens.py, z3+sympy, fails-closed, cross-
    validated 0 disagreements across 3 frontier models). (Solves IC-8.)
  - The ladder was authored by a DIFFERENT agent than Icarus's Generator,
    satisfying the blind-oracle-authored-elsewhere discipline. (SW-2.)
  - The reference reasoners (template->procedural->careful->falsifier) define a
    real, discriminating staircase, so "reached R_k" finally means something.
    (Solves IC-9 -- the toy tier tests all-passed on bootstrap; these don't.)

This module READS from the Harmonia harness; it never edits it (same boundary
the verifier lens declares).

Reasoner interface Icarus must conform to:
    reasoner(probe) -> (answer, trace_dict)
where `probe` is a harmonia reasoning_phase0.Probe.

FIXED infrastructure -- Icarus does NOT modify this module.
"""
from __future__ import annotations

import random
import sys
from collections import Counter
from pathlib import Path
from typing import Callable, Optional

_REPO_ROOT = Path(r"D:\Prometheus")
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from harmonia.experiments import reasoning_phase0 as rp0
from harmonia.experiments import verifier_lens

# Tiers the adapter exposes, in ladder order. (R4/R8-R12 not yet generated by
# the harness; R5/R7 added 2026-05-29.)
TIERS = ["R0", "R1", "R2", "R3", "R5", "R6", "R7"]

_GENERATORS = {
    "R0": rp0.gen_R0, "R1": rp0.gen_R1, "R2": rp0.gen_R2, "R3": rp0.gen_R3,
    "R5": rp0.gen_R5, "R6": rp0.gen_R6, "R7": rp0.gen_R7,
}

# Kinds the deterministic verifier lens can certify. For others (invariant,
# proof_repair) we fall back to the harness's deterministic grade().
_VERIFIER_KINDS = {"linear", "quadratic", "sqrt", "rational", "conjecture"}


def generate_probes(tier: str, seed: int, n_per: Optional[int] = None) -> list:
    """Procedurally generate the 4-version probe battery for a tier at a given
    seed. A held-out seed (different from any the Generator saw) gives the
    blind oracle."""
    if tier not in _GENERATORS:
        raise ValueError(f"unknown tier {tier}; have {list(_GENERATORS)}")
    rng = random.Random(seed)
    # rp0.N_PER controls probes-per-version; allow a smaller battery for speed.
    if n_per is not None:
        orig = rp0.N_PER
        rp0.N_PER = n_per
        try:
            probes = _GENERATORS[tier](rng)
        finally:
            rp0.N_PER = orig
        return probes
    return _GENERATORS[tier](rng)


# Trace-dict keys the grader (reasoning_phase0.grade) reads per tier. The
# reasoner must SET these in its returned trace, not just produce the right
# answer -- a correct boolean with an unset trace key still loses the feature.
# Surfacing them prevents the silent "right answer, missing trace" failure.
TIER_TRACE_KEYS = {
    "R2": ["domain_constraints_detected", "invalid_operations_attempted",
           "rejected_extraneous"],
    "R3": ["domain_constraints_detected", "invalid_operations_attempted"],
    "R5": ["invariant_named"],
    "R6": ["searched_counterexample", "found_counterexample", "overgeneralized"],
}

# Fields that live INSIDE probe.data but ARE the answer key (or a witness to it).
# probe.ground_truth is already withheld from the schema; these are the same kind
# of cheat-vector hiding one level down. R6 conjecture probes carry the ground
# truth ('truth') and the harness counterexample ('cex') in data -- surfacing
# them turns "derive the answer" into "copy the answer key" (and once the schema
# samples enough probes to reveal the full cid enum, it would expose every
# counterexample). Strip them; the Generator must derive truth/witness itself.
_CHEAT_DATA_FIELDS = {"truth", "cex"}


def probe_schema(tier: str, seed: int = 20260529) -> dict:
    """Return the probe.data schema for a tier so the Generator knows which
    fields to read. Different tiers carry different keys (R0/R1 use 'expr';
    R2 uses 'a','b','eq'; R3 uses 'num','den','rhs','excluded'; etc.). Failing
    to read the right key is a silent KeyError -- surfacing the schema makes
    the failure emit direction (and prevents the schema-guess entirely).

    Aggregates DISTINCT sample values across all four versions (clean / iso /
    adversarial / transfer) AND across several seeds at n_per>1 -- enum-valued
    fields vary two different ways: BY VERSION (e.g. R5 'invariant' is
    color_parity on clean but area_parity / none on others) and BY RANDOM DRAW
    (e.g. R6 'cid' is drawn once per iteration and SHARED by all four versions,
    so n_per=1 surfaces exactly one conjecture while the real battery spans a
    whole family). Sampling only the clean n_per=1 probe is what let cycle 16
    return None for R5's 'none' case and cycle 20 return None for every R6 cid
    except the one it was shown. Cheat fields (truth/cex) are stripped. Also
    surfaces the grader's trace-key contract for the tier."""
    # Sample a BATTERY across seeds so per-draw categorical fields reveal their
    # full enum, not just the one value a single draw happens to pick.
    schema_seeds = [seed, seed + 1, seed + 2, 20240601]
    probes: list = []
    try:
        for s in schema_seeds:
            probes.extend(generate_probes(tier, s, n_per=8))
    except Exception as e:
        return {"tier": tier, "error": str(e)}
    if not probes:
        return {"tier": tier, "error": "no_probes"}
    # Aggregate distinct values per field across every probe (capped so a
    # high-cardinality field like 'expr' cannot bloat the schema -- 12 distinct
    # samples is plenty to reveal an enum).
    fields: dict = {}
    versions: list = []
    for p in probes:
        if p.version not in versions:
            versions.append(p.version)
        for k, v in p.data.items():
            if k in _CHEAT_DATA_FIELDS:
                continue
            rep = repr(v)[:80]
            entry = fields.setdefault(
                k, {"type": type(v).__name__, "samples": []})
            if rep not in entry["samples"] and len(entry["samples"]) < 12:
                entry["samples"].append(rep)
    # We surface the INPUT structure only. We deliberately do NOT expose
    # probe.ground_truth: (1) it is a cheat-vector (the Generator must derive
    # the answer, not mimic it), and (2) for some tiers the ground_truth field
    # is descriptive and differs from the answer token the grader expects
    # (R3's grader wants the string "all_x_except_excluded", not the
    # {identity_except: r} ground_truth) -- showing it actively misleads.
    # The required OUTPUT format lives in the tier description (tier_challenge),
    # which is the legitimate place for it.
    return {
        "tier": tier,
        "kind": probes[0].kind,
        "versions": versions,
        "data_fields": fields,
        "grader_trace_keys": TIER_TRACE_KEYS.get(tier, []),
    }


def _grade_probe(probe, answer, trace: dict) -> tuple[bool, Optional[str]]:
    """Grade one (probe, answer) deterministically. Prefer the verifier lens
    (substitution/eval, hard to fool); fall back to the harness grader for
    kinds the lens does not cover (invariant, proof_repair)."""
    if probe.kind in _VERIFIER_KINDS:
        v = verifier_lens.verify(probe, answer)
        valid = v.get("valid")
        if valid is True:
            return True, None
        if valid is False:
            return False, v.get("kill_pattern")
        # valid is None -> unverifiable (true universal). Defer to harness grade
        # which knows the harness's intended ground truth for these.
    vec, correct = rp0.grade(probe, answer, trace or {})
    return bool(correct), vec.get("_kill_pattern")


def score_reasoner(
    reasoner: Callable,
    tier: str,
    seed: int,
    n_per: int = 10,
) -> dict:
    """Run a reasoner against a tier's 4-version probe battery; return a
    deterministic scorecard.

    reasoner: probe -> (answer, trace_dict)
    Returns:
      {
        tier, seed, n_probes,
        accuracy (overall),
        per_version: {clean/iso/adversarial/transfer: acc},
        kill_patterns: {pattern: count},
        passed_tier: bool,   # accuracy across ALL versions >= threshold
      }
    """
    probes = generate_probes(tier, seed, n_per=n_per)
    by_version: dict[str, list[bool]] = {}
    kills: Counter = Counter()
    n_ok = 0
    for p in probes:
        try:
            ans, tr = reasoner(p)
        except Exception as e:
            ans, tr = None, {"reasoner_error": str(e)}
        ok, kp = _grade_probe(p, ans, tr)
        by_version.setdefault(p.version, []).append(ok)
        if ok:
            n_ok += 1
        elif kp:
            kills[kp] += 1
    n = len(probes)
    per_version = {v: (sum(r) / len(r) if r else 0.0) for v, r in by_version.items()}
    accuracy = n_ok / max(1, n)
    # A tier is "passed" only if it survives ALL four versions at >=0.8 -- a
    # single clean pass is not evidence of the tier (the harness's core stance).
    passed = all(acc >= 0.8 for acc in per_version.values()) and len(per_version) >= 3
    return {
        "tier": tier, "seed": seed, "n_probes": n,
        "accuracy": round(accuracy, 3),
        "per_version": {k: round(v, 3) for k, v in per_version.items()},
        "kill_patterns": dict(kills.most_common()),
        "passed_tier": passed,
    }


def capability_frontier(reasoner: Callable, seed: int, n_per: int = 10) -> dict:
    """Score a reasoner across the whole ladder; report the highest contiguous
    tier passed (the honest capability frontier) + the full scorecard."""
    cards = {}
    frontier = None
    for tier in TIERS:
        card = score_reasoner(reasoner, tier, seed, n_per=n_per)
        cards[tier] = card
        if card["passed_tier"]:
            frontier = tier
        # do not break -- non-monotonic ladders (basis behavior) are informative
    return {
        "frontier_contiguous": _contiguous_frontier(cards),
        "highest_passed": frontier,
        "scorecards": cards,
    }


def _contiguous_frontier(cards: dict) -> Optional[str]:
    """Highest tier R_k such that R0..R_k are ALL passed (the strict ladder
    reading). Returns None if R0 itself is not passed."""
    last = None
    for tier in TIERS:
        if cards.get(tier, {}).get("passed_tier"):
            last = tier
        else:
            break
    return last


def holdout_score(reasoner: Callable, tier: str, train_seed: int, n_per: int = 10) -> dict:
    """Blind-oracle score: grade on a HELD-OUT seed distinct from the one the
    Generator was shown. Procedural generation means these are fresh instances
    of the same tier, impossible to memorize."""
    holdout_seed = (train_seed * 2654435761 + 12345) & 0x7FFFFFFF
    return score_reasoner(reasoner, tier, holdout_seed, n_per=n_per)


if __name__ == "__main__":
    # Validation: reproduce the template->falsifier staircase THROUGH the Icarus
    # adapter (using the deterministic verifier lens for grading), proving Icarus
    # can consume the Harmonia B ladder.
    print("Icarus tier_oracle validation -- reference reasoners on the real ladder")
    print("(grading via deterministic verifier lens; R5/R7 via harness grader)\n")
    print(f"{'reasoner':12s} " + " ".join(f"{t:>6s}" for t in TIERS) + "   frontier")
    for rn, fn in rp0.REASONERS.items():
        accs = []
        for t in TIERS:
            card = score_reasoner(fn, t, seed=20260529, n_per=10)
            accs.append(card["accuracy"])
        front = _contiguous_frontier(
            {t: score_reasoner(fn, t, seed=20260529, n_per=10) for t in TIERS}
        )
        print(f"{rn:12s} " + " ".join(f"{a:6.2f}" for a in accs) + f"   {front}")
