"""TOOL_P_CLASS_FIELD_TOWER — p-Hilbert class field tower.

Extends TOOL_HILBERT_CLASS_FIELD with restriction to a p-Sylow subgroup.

Mathematical background
-----------------------
The Hilbert class field H(K) of a number field K is the maximal unramified
abelian extension; Gal(H/K) ≅ Cl(K) by class field theory. The
**p-Hilbert class field** H_p(K) is the maximal unramified abelian
p-extension of K, with

    Gal(H_p(K) / K) ≅ Cl(K)[p^∞]

(the p-Sylow of Cl(K)). Iterating yields the **p-class-field tower**

    K = K_0 ⊂ K_1 ⊂ K_2 ⊂ ...,    K_{n+1} = H_p(K_n).

By a theorem of Golod and Shafarevich (1964), this tower may be infinite;
when it terminates at depth d, K_d has trivial p-class group and is its
own p-Hilbert class field.

References
----------
* Cohen, "A Course in Computational Algebraic Number Theory", §6.3.4.
* Washington, "Introduction to Cyclotomic Fields", 2nd ed., §10.3.

Implementation
--------------
PARI's `bnrclassfield(bnr, subgroup, flag)` computes the abelian extension
of K cut out by the subgroup `subgroup` of the ray-class group. With
modulus 1 (unramified) the ray-class group is the ideal class group, with
structure `bnf.cyc = [c_1, ..., c_k]`. The p-Sylow subgroup of Cl(K) is
the quotient by the **p'-part subgroup** generated by `(p^{v_p(c_i)})_i`;
passing this subgroup to `bnrclassfield` returns the p-Hilbert class field
in absolute form.

Forged: 2026-04-25 | Project #29 Phase 1 | Tier 1 (cypari wrapper).
"""
from __future__ import annotations

from typing import Optional, Union

import cypari


_pari = cypari.pari

# Default 1.5 GB PARI stack; iterated p-HCF on degree-12 base fields can
# exceed 4 GB at depth 2-3. We auto-grow on overflow up to _MAX_STACK_BYTES.
_DEFAULT_STACK_BYTES = 1_500_000_000
_MAX_STACK_BYTES = 4_000_000_000
try:
    _pari.allocatemem(_DEFAULT_STACK_BYTES)
except cypari._pari.PariError:
    pass


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _coerce_poly(polynomial, var: str = 'x') -> str:
    """Convert polynomial input to a PARI-parseable string.

    Variable can be swapped to 'y' for use as a base field in a relative
    extension (PARI requires base variables to have lower priority than
    relative variables).
    """
    if isinstance(polynomial, str):
        if var != 'x':
            return polynomial.replace('x', var)
        return polynomial
    coeffs = list(polynomial)
    if not coeffs:
        raise ValueError("polynomial coefficient list is empty")
    deg = len(coeffs) - 1
    terms = []
    for i, c in enumerate(coeffs):
        power = deg - i
        if c == 0:
            continue
        if power == 0:
            terms.append(f"({int(c)})")
        elif power == 1:
            terms.append(f"({int(c)})*{var}")
        else:
            terms.append(f"({int(c)})*{var}^{power}")
    if not terms:
        raise ValueError("polynomial is identically zero")
    return "+".join(terms)


def _safe_call(fn, *, max_retries: int = 3):
    """Run a PARI thunk; on stack overflow, double the stack and retry."""
    last_err: Optional[Exception] = None
    for _ in range(max_retries + 1):
        try:
            return fn()
        except cypari._pari.PariError as e:
            if 'stack overflows' not in str(e):
                raise
            last_err = e
            new_size = min(2 * _pari.stacksize(), _MAX_STACK_BYTES)
            if new_size <= _pari.stacksize():
                break
            _pari.allocatemem(new_size)
    if last_err is not None:
        raise last_err


def _validate_prime(p) -> int:
    """Validate p is a rational prime, return as int."""
    if not isinstance(p, int) or p < 2:
        raise ValueError(f"p must be a rational prime >= 2; got {p!r}")
    if not _pari(f"isprime({p})"):
        raise ValueError(f"p = {p} is not prime")
    return p


def _p_adic_valuation(n: int, p: int) -> int:
    """Largest k with p^k | n. v_p(0) := 0 (only used for cyc entries)."""
    if n == 0:
        return 0
    n = abs(int(n))
    k = 0
    while n % p == 0:
        n //= p
        k += 1
    return k


def _polynomial_degree(pol_str: str) -> int:
    """Return PARI's poldegree of a polynomial string."""
    return int(_pari(f"poldegree({pol_str})"))


def _p_part_subgroup_matrix(cyc: list[int], p: int) -> str:
    """Return PARI subgroup matrix for the p'-part of Cl(K) (kernel of p-Sylow).

    For cyc = [c_1, ..., c_k] with c_i = p^{a_i} * m_i (gcd(m_i, p) = 1),
    the p'-part of Z/c_i is generated by p^{a_i} (an element of order m_i),
    so the p'-part subgroup of (Z/c_1) x ... x (Z/c_k) is generated by
    p^{a_i} * e_i. As a column-matrix in PARI:

        diag(p^{a_1}, ..., p^{a_k})

    Passing this as `subgroup` to `bnrclassfield` returns the field cut
    out by the quotient (Cl(K) / p'-part) = p-Sylow of Cl(K).

    Edge cases:
      * cyc = [] -> matid(0) (empty matrix), trivial class group.
      * any a_i = 0 (p ∤ c_i) -> diagonal entry 1, that factor contributes
        no p-part and the row is fully in the subgroup.
    """
    if not cyc:
        return "matid(0)"
    diag = [p ** _p_adic_valuation(c, p) for c in cyc]
    return f"matdiagonal({list(diag)})"


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def p_hilbert_class_field(K_polynomial, p: int,
                          max_class_number_p: int = 64) -> dict:
    """Compute the p-Hilbert class field H_p(K) of K = Q[x]/(f(x)).

    H_p(K) is the maximal unramified abelian p-extension of K; by class
    field theory Gal(H_p(K)/K) ≅ Cl(K)[p^∞] (the p-Sylow of Cl(K)).

    Parameters
    ----------
    K_polynomial : str | list[int]
        Defining polynomial of K. May contain x as the variable.
    p : int
        Rational prime.
    max_class_number_p : int, default 64
        Guard: if |Cl(K)[p^∞]| exceeds this, raise ValueError instead of
        attempting bnrclassfield (memory-prohibitive for huge p-parts).

    Returns
    -------
    dict
        {
          'abs_poly': str,         # absolute defining polynomial (polredabs)
          'rel_poly': str,         # relative polynomial over K (PARI form)
          'degree_rel': int,       # [H_p(K) : K] = h_p(K)
          'degree_abs': int,       # [H_p(K) : Q]
          'disc': int,             # discriminant of H_p(K) (absolute)
          'class_number_p_K': int, # |Cl(K)[p^∞]| = h_p(K)
          'p': int,                # echo input
          'is_trivial': bool,      # True iff h_p(K) = 1
        }

    Raises
    ------
    ValueError
        Invalid p, malformed polynomial, or h_p > max_class_number_p.

    Examples
    --------
    >>> r = p_hilbert_class_field('x^2+23', 3)
    >>> r['degree_rel'], r['degree_abs']
    (3, 6)
    >>> r['is_trivial']
    False

    >>> r = p_hilbert_class_field('x^2+5', 3)  # 3 doesn't divide h=2
    >>> r['is_trivial']
    True
    """
    p = _validate_prime(p)

    base_str = _coerce_poly(K_polynomial, var='y')
    base_deg = _polynomial_degree(base_str)

    # Trivial case: K = Q (degree <= 1).
    if base_deg <= 1:
        return {
            'abs_poly': 'x',
            'rel_poly': 'x',
            'degree_rel': 1,
            'degree_abs': 1,
            'disc': 1,
            'class_number_p_K': 1,
            'p': p,
            'is_trivial': True,
        }

    K = _safe_call(lambda: _pari(f'bnfinit({base_str})'))
    cyc_raw = _safe_call(lambda: _pari(f'bnfinit({base_str}).cyc'))
    n_factors = int(_pari(f'#({cyc_raw})'))
    cyc = [int(cyc_raw[i]) for i in range(n_factors)]

    # Compute h_p = product of p^{v_p(c_i)}
    h_p = 1
    for c in cyc:
        h_p *= p ** _p_adic_valuation(c, p)

    # Trivial p-part: H_p(K) = K.
    if h_p == 1:
        K_poly = str(_safe_call(lambda: _pari.polredabs(_pari(
            base_str.replace('y', 'x')))))
        K_disc = int(_safe_call(lambda: _pari(f'nfinit({base_str}).disc')))
        return {
            'abs_poly': K_poly,
            'rel_poly': 'x',
            'degree_rel': 1,
            'degree_abs': base_deg,
            'disc': K_disc,
            'class_number_p_K': 1,
            'p': p,
            'is_trivial': True,
        }

    if h_p > max_class_number_p:
        raise ValueError(
            f"h_p = {h_p} exceeds max_class_number_p = {max_class_number_p}; "
            f"absolute degree would be {h_p * base_deg}. Raise the cap if "
            f"you have the memory.")

    # Build subgroup matrix for the p'-part (kernel of the p-Sylow).
    H_str = _p_part_subgroup_matrix(cyc, p)

    bnr = _safe_call(lambda: _pari.bnrinit(K, 1))
    H = _pari(H_str)

    # Flag 2: t_POL, absolute defining polynomial of H_p(K) over Q.
    abs_poly = _safe_call(lambda: _pari.bnrclassfield(bnr, H, 2))
    # Flag 0: t_VEC of relative polynomials over K (one per cyclic factor).
    rel_polys = _safe_call(lambda: _pari.bnrclassfield(bnr, H, 0))

    n_rel = int(_pari.length(rel_polys))
    if n_rel == 0:
        rel_poly_str = 'x'
    elif n_rel == 1:
        rel_poly_str = str(rel_polys[0])
    else:
        rel_poly_str = '; '.join(str(rel_polys[i]) for i in range(n_rel))

    canonical = _safe_call(lambda: _pari.polredabs(abs_poly))
    abs_str = str(canonical)
    disc = int(_pari.poldisc(canonical))
    deg_abs = int(_pari.poldegree(canonical))

    return {
        'abs_poly': abs_str,
        'rel_poly': rel_poly_str,
        'degree_rel': h_p,
        'degree_abs': deg_abs,
        'disc': disc,
        'class_number_p_K': h_p,
        'p': p,
        'is_trivial': False,
    }


def p_class_field_tower(K_polynomial, p: int, max_depth: int = 3,
                        max_total_degree: int = 24,
                        max_class_number_p: int = 64) -> dict:
    """Iterate p_hilbert_class_field starting from K.

    Builds the p-class-field tower K = K_0 ⊂ K_1 ⊂ ... up to max_depth
    iterations, stopping when h_p(K_n) = 1 (terminated) or a degree /
    stack guard fires.

    Parameters
    ----------
    K_polynomial : str | list[int]
    p : int
    max_depth : int, default 3
        Maximum number of HCF iterations to perform.
    max_total_degree : int, default 24
        Cap on cumulative absolute degree [K_n : Q]. PARI's bnfinit on
        degree > 24 fields is prohibitively slow / memory-hungry. If a
        layer would exceed this cap we stop with terminated=False.
    max_class_number_p : int, default 64
        Per-layer h_p guard.

    Returns
    -------
    dict
        {
          'tower': list[str],              # K_0, K_1, ..., K_d (abs polys, polredabs)
          'depths': list[int],             # [0, 1, ..., d]
          'degree_progression': list[int], # [[K_n : Q] for n in depths]
          'h_p_progression': list[int],    # h_p(K_n) at each layer
          'terminated': bool,              # h_p(K_d) = 1
          'terminated_depth': int | None,  # depth at which h_p hit 1, or None
          'max_depth_reached': int,        # how many layers we computed
          'p': int,
          'reason': str,                   # 'terminated' | 'max_depth' | 'degree_cap'
                                           #  | 'h_p_cap' | 'stack_overflow'
        }

    Raises
    ------
    ValueError
        Invalid p, malformed polynomial, or max_depth < 0.

    Examples
    --------
    >>> t = p_class_field_tower('x^2+23', 3, max_depth=3)
    >>> t['terminated']
    True
    >>> t['terminated_depth']
    1
    >>> t['degree_progression'][:2]
    [2, 6]
    """
    p = _validate_prime(p)
    if not isinstance(max_depth, int) or max_depth < 0:
        raise ValueError(f"max_depth must be a non-negative int; got {max_depth!r}")

    base_str = _coerce_poly(K_polynomial, var='x')
    base_deg = _polynomial_degree(base_str)

    # Initial state.
    K0_canonical = str(_safe_call(lambda: _pari.polredabs(_pari(base_str))))
    tower = [K0_canonical]
    depths = [0]
    degree_progression = [base_deg]
    h_p_progression: list[int] = []

    # Trivial K = Q.
    if base_deg <= 1:
        h_p_progression.append(1)
        return {
            'tower': tower,
            'depths': depths,
            'degree_progression': degree_progression,
            'h_p_progression': h_p_progression,
            'terminated': True,
            'terminated_depth': 0,
            'max_depth_reached': 0,
            'p': p,
            'reason': 'terminated',
        }

    current_poly = K0_canonical
    terminated = False
    terminated_depth: Optional[int] = None
    reason = 'max_depth'

    for depth in range(max_depth + 1):
        # Compute p-HCF of current layer.
        try:
            hcf = p_hilbert_class_field(current_poly, p,
                                        max_class_number_p=max_class_number_p)
        except cypari._pari.PariError as e:
            if 'stack overflows' in str(e):
                reason = f'stack_overflow_at_depth_{depth}'
            else:
                reason = f'pari_error_at_depth_{depth}: {e}'
            break
        except ValueError as e:
            if 'max_class_number_p' in str(e):
                reason = f'h_p_cap_at_depth_{depth}'
            else:
                raise
            break

        h_p_progression.append(hcf['class_number_p_K'])

        if hcf['is_trivial']:
            terminated = True
            terminated_depth = depth
            reason = 'terminated'
            break

        if depth == max_depth:
            reason = 'max_depth'
            break

        next_deg = hcf['degree_abs']
        if next_deg > max_total_degree:
            reason = f'degree_cap_at_depth_{depth+1} (would be {next_deg} > {max_total_degree})'
            break

        # Step into next layer.
        current_poly = hcf['abs_poly']
        tower.append(current_poly)
        depths.append(depth + 1)
        degree_progression.append(next_deg)

    return {
        'tower': tower,
        'depths': depths,
        'degree_progression': degree_progression,
        'h_p_progression': h_p_progression,
        'terminated': terminated,
        'terminated_depth': terminated_depth,
        'max_depth_reached': len(tower) - 1,
        'p': p,
        'reason': reason,
    }


def tower_terminates_p(K_polynomial, p: int, max_depth: int = 4,
                       **kwargs) -> bool:
    """Convenience: did the p-class-field tower terminate within max_depth?

    Returns True iff some K_d in the tower (d <= max_depth) has trivial
    p-class group. Returns False if the depth cap or a degree/h_p guard
    fired before termination.
    """
    result = p_class_field_tower(K_polynomial, p, max_depth=max_depth, **kwargs)
    return bool(result['terminated'])


def p_tower_signature(K_polynomial, p: int, max_depth: int = 3,
                      **kwargs) -> tuple[int, ...]:
    """Compact summary of the p-class-field tower: degree progression as tuple.

    Returns ([K_0:Q], [K_1:Q], ..., [K_d:Q]) where d = max depth reached.

    Examples
    --------
    >>> p_tower_signature('x^2+23', 3, max_depth=2)
    (2, 6)
    >>> p_tower_signature('x^2+5', 2, max_depth=2)
    (2, 4)
    >>> p_tower_signature('x', 5, max_depth=3)
    (1,)
    """
    result = p_class_field_tower(K_polynomial, p, max_depth=max_depth, **kwargs)
    return tuple(result['degree_progression'])


__all__ = [
    "p_hilbert_class_field",
    "p_class_field_tower",
    "tower_terminates_p",
    "p_tower_signature",
]
