# Writes rows_groupC.csv. Values are transcribed from rederive_groupC.py output (rederive_groupC.out.txt).
import csv, os
here = os.path.dirname(os.path.abspath(__file__))
H = "claim_id,doc,location,claim_text,source_report,report_value,raw_path,rederived_value,status,denominator,denominator_ok,wording_exceeds,notes".split(",")
WL = "roles/Ananke/research/workers/W-L"
WK = "roles/Ananke/research/workers/W-K"
DE = "roles/Ananke/research/designed_echoes"
JC = "roles/Ananke/research/joint_carrier"
rows = [
["2a", "BACKLOG_V2.md; SYNTHESIS_2026-09-28_ARC3.md", "BACKLOG T-RET-2 row (T-RET-EVO); ARC3 s3",
 "retention IS reachable when rewarded (4/8 searches, carrier S, local)", f"{WL}/REPORT.md",
 "4/8 pass frozen criterion; n=1 2/4, n=2 2/4; zero_comm = normal", f"{WL}/out/search_n*_s*.json (held_5F3)",
 "4/8 (n1_s0,n1_s3,n2_s1,n2_s2); recomputed lo99>.60 & diff_lo99>0 agrees with SUCCESS flag 10/10; |zero_comm-acc| <= .0008",
 "MATCH", "8 searches = n in {1,2} x 4 seeds, pop96 gens36, M2 physics, 64 held-out worlds 0x5F3", "yes", "yes",
 "Count verified. 'when rewarded' is not isolated: the UNREWARDED n=0 HOLD control n0_s0 reaches the same integrator (held .672, lo99 .637 > .60 = criterion a). W-L says criterion (a) cannot tell retention from integration and the integrator reading is post hoc. 2 of the 4 successes are n=2 runs that pass only by integrating (lag-2 selectivity < 0)."],
["2b", "BACKLOG_V2.md; SYNTHESIS_2026-09-28_ARC3.md", "BACKLOG T-RET-2 row; ARC3 s3",
 "carrier S (only site state S carries the bit in every SUCCESS champion)", f"{WL}/REPORT.md",
 "S swap .32-.39 vs normal ~.60; formal verdict CHANCE; other arms exactly NO-EFFECT", f"{WL}/out/carriers_champs.json",
 "S swap acc .323/.344/.385/.385 (successes), .406 (n1_s2); all <= 1-normal; Kp,w,inbox,channel_all,pay0,pay1 NO-EFFECT; recorded verdict CHANCE 5/5",
 "PARTIAL", "5 champions (4 SUCCESS + n1_s2), 64-world swap design", "yes", "no",
 "Recorded verdict is CHANCE, not FLIP; 'carrier S' at report time rested on an informal 1-normal reading. Supported later by W-N's re-run at 512 worlds (FLIP on all 5; workers/W-N/REPORT.md). That is a RE-EVALUATION of frozen champions, not part of the W-L search. The ARC3 CORRECTION blocks record this."],
["2c", "SYNTHESIS_2026-09-28_ARC3.md; BACKLOG_V2.md", "ARC3 s3; BACKLOG T-RET-2",
 "Selective lag-2 storage was not reached (0/4 at n=2)", f"{WL}/REPORT.md", "0/4; no n=2 champion prefers lag 2",
 f"{WL}/out/lagprofile.json", "lag2 minus max(other lags) = -.015,-.015,-.015,-.032 for n2_s0..s3 -> 0/4 selective",
 "MATCH", "4 n=2 seeds, pop96 gens36; lag profile on 256 worlds, no CI, post hoc", "partial", "no",
 "Selectivity criterion is post hoc (not preregistered). n2_s0 and n2_s2 have identical lag profiles to 3 dp (possibly the same program)."],
["2d", "SYNTHESIS_2026-09-28_ARC3.md; BACKLOG_V2.md", "ARC3 s3 'although a 16-line plant solves it'; BACKLOG T-RET-2",
 "a 16-line plant solves selective lag-2 at the same physics and prog_len", f"{WL}/REPORT.md",
 "P2S 16 lines, 1.000 [1.000,1.000] both namespaces", f"{WL}/out/checks.json (plants); carriers_plants.json",
 "P2S n=2 lines 16 acc 1.0 lo99 1.0 analysis+held; physics prog_len 16; swap S FLIP, reset_S -> .50",
 "MATCH", "1 hand plant, 2 namespaces", "yes", "no", "Hand-built positive control; consistent with the claim."],
["2e", "BACKLOG_V2.md; SYNTHESIS_2026-09-28_ARC3.md",
 "BACKLOG T-RET-2 'Even the HOLD control evolved an integrator'; ARC3 s2 'The search builds integrators even on HOLD'",
 "Even the HOLD control evolved an integrator", f"{WL}/REPORT.md", "n0_s0 is an integrator (post hoc lag profile)",
 f"{WL}/out/lagprofile.json; search_n0_s*.json",
 "n0_s0 flat .619-.650 (range .031; PLANT_INTEGRATOR .629-.651); n0_s1 at chance .497-.510 (no integrator)",
 "MATCH", "1 of 2 HOLD-control seeds", "no", "yes",
 "ARC3 s2 turns 1/2 seeds into 'The search builds integrators even on HOLD'. Corrected: 'one of two HOLD-control searches (n0_s0) evolved an integrator; the other reached nothing'."],
["2f", "SYNTHESIS_2026-09-28_ARC3.md",
 "s1 H6 bullet 'selective retention is never evolved though a plant solves it (W-L)'; s3 'what evolves is INTEGRATION'",
 "selective retention is never evolved", f"{WL}/REPORT.md",
 "'No champion built a selective lag-n store like P1S or P2S'; n1_s2 lag-selective but failed; n1_s3 weighted integrator with a lag-1 peak",
 f"{WL}/out/lagprofile.json",
 "n=1: n1_s2 lag1 .635 vs max other .513 (sel +.122; failed, lo99 .581); n1_s3 lag1 .694 vs .603 (sel +.091; a SUCCESS); 2/4 n=1 runs have lag-1 selectivity > .05",
 "PARTIAL", "8 rewarded searches at one budget (pop96 gens36)", "no", "yes",
 "'never evolved' is contradicted at n=1: one SUCCESS (n1_s3) and one near-miss (n1_s2) have clear lag-1 peaks (256-world profile, SE ~.03). Supported: 'selective lag-2 retention was not reached (0/4 n=2 searches at one budget); at n=1, partial lag selectivity appeared in 2/4 runs (one passing), mixed with integration'."],
["2g", "SYNTHESIS_2026-09-28_ARC3.md", "s1 H6 'Four independent lines'; s3",
 "W-L shows the limit is search reachability, not physics", f"{WL}/REPORT.md",
 "'At this budget that is a search-reachability limit, not a physics limit'", f"{WL}/out/search_*.json",
 "a single budget (pop96/gens36), 4 seeds per arm; no budget-scaling run in out/",
 "REPORT_ONLY", "4 seeds x 1 budget", "no", "yes",
 "The reachability reading rests on one budget. W-L proposed budget scaling, which was not run. 'Search reachability bounds PTE' is an interpretation at one search configuration."],
["2h", "SYNTHESIS_2026-09-28_ARC3.md", "CORRECTION (W-N) block",
 "W-L swap CHANCE was a sample-size effect: at 512 worlds the absolute rule gives FLIP on every W-L champion", "workers/W-N/REPORT.md",
 "FLIP on S and site_all of 5 W-L champions at M=512; W-L design reproduced (n1_s0 normal .583, swap .323)",
 f"{WL}/out/carriers_champs.json (64-world side only)",
 "64-world side reproduced: n1_s0 normal .583, swap .323, CHANCE. The 512-world values were not recomputed (out of group C scope).",
 "PARTIAL", "5 W-L champions", "yes", "no",
 "A re-evaluation of frozen champions, correctly labelled as a correction, not as a search outcome."],
["12a", "SYNTHESIS_2026-09-28_ARC3.md", "s8",
 "There is no universal check (W-K, 21 fixtures x 16 checks with valid twins)", f"{WK}/REPORT.md",
 "21 fixtures (10 BROKEN, 11 VALID), 16 checks", f"{WK}/out/matrix.json",
 "21 fixtures: 10 broken, 11 valid (all with a twin field), 16 checks; max J .70 (K2) < 1, so no universal check",
 "MATCH", "10 broken / 11 valid hand-built fixtures, one specimen each, one author", "yes", "no",
 "'valid twins': 8 are true twins of broken fixtures; 3 are V0 true-null fixtures. One author built both the fixtures and the checks (not independent; report Limits)."],
["12b", "SYNTHESIS_2026-09-28_ARC3.md; BACKLOG_V2.md", "ARC3 s8 'Best single check ... (J .70, 0 false alarms)'",
 "must-flip PLANT through the arm's own code: J .70, 0 false alarms", f"{WK}/REPORT.md", "K2 caught 7/10, FA 0/11, J 0.70",
 f"{WK}/out/matrix.json",
 "K2 caught 7/10, FA 0/11, J = .70 (recomputed from FLAG statuses; lenient: NA = not flagged); scores.json K2 J .70",
 "MATCH", "10 broken, 11 valid", "yes", "no",
 "Small n (10/11) and perfect-solver plants give degenerate CIs (report Limits). 'Best single check' is scoped to this fixture set."],
["12c", "SYNTHESIS_2026-09-28_ARC3.md", "s8",
 "Minimum zero-false-alarm cover: {plant, applied count, could-fail counter-plant}", f"{WK}/REPORT.md",
 "{K2,K4d,K7}; equal-size alternatives {K1g,K2,K7} and {K2,K7,K9}", f"{WK}/out/matrix.json",
 "brute force: size-3 covers {K1g,K2,K7}, {K2,K4d,K7}, {K2,K7,K9}; no cover of size <= 2",
 "MATCH", "10 broken fixtures", "yes", "no",
 "ARC3 names only the cheapest cover; it is one of three equal-size covers. Per the report, K4d's zero FA is partly vacuous (only hook arms count their own hits)."],
["12d", "SYNTHESIS_2026-09-28_ARC3.md", "s2 falsified 'Identical arm => the intervention never took'",
 "Identical outputs also describe true nulls (W-K)", f"{WK}/REPORT.md", "K3/K3b false-alarm on V0-WIN and V0-RULE (2/11)",
 f"{WK}/out/matrix.json", "K3 FA 2/11 (V0-WIN, V0-RULE); K3b FA 2/11", "MATCH", "11 valid fixtures", "yes", "no", ""],
["6a", "SYNTHESIS_2026-09-28_ARC3.md; BACKLOG_V2.md", "ARC3 s6; BACKLOG T-DE-1",
 "7/7 designs FIT (MAE .012-.023), including a deliberate failure at the trained gap and comb-shaped intervals", f"{DE}/RESULT.md",
 "7/7 FIT; MAE .012-.023; E4 gap 8 .53, hi99 .59", f"{DE}/predictions.json; engine.json",
 "MAE .0119-.0232 over gaps 2-16 (15 points each); 7/7 have MAE <= .07 and INTERVAL-HOLDS (+-1); E4 gap 8 .526, hi99 .590 <= .60",
 "MATCH", "7 hand-designed specimens x 15 gaps, 64 worlds", "yes", "no",
 "The FIT bar is MAE <= .07 (W-A's rule); all seven are far inside it."],
["6b", "SYNTHESIS_2026-09-28_ARC3.md; BACKLOG_V2.md",
 "ARC3 s6 'The instruments read the designed channel -> site trajectory at the right time'; BACKLOG 'instruments 2/3'",
 "instruments 2/3", f"{DE}/RESULT.md", "2/3 held (E1 HELD, arrival HELD, E2 FAILED)",
 f"{DE}/instruments.json; PLAN.md lines 29-39",
 "E1 held; arrival mean lag E1 -1.49 vs E2 -5.49 (shift 3.99, predicted ~4) held; E2 compound prediction failed (site part held, transit part failed) -> 2/3",
 "MATCH", "3 committed predictions", "yes", "yes",
 "ARC3 s6 'read ... at the right time' overstates it: the one tick-TIMING prediction (E2 in transit at -6/-4) is the one that FAILED. Better: 'the instruments read channel-then-site in the designed order; the predicted handoff tick was wrong (2/3)'."],
["6c", "SYNTHESIS_2026-09-28_ARC3.md; BACKLOG_V2.md",
 "ARC3 s1 'the echo model designs mechanisms search never produced (T-DE-1)'; BACKLOG T-REACH-GAP 'the model designs what search never found'",
 "the echo model designs mechanisms that search never produced", f"{DE}/RESULT.md",
 "RESULT: 'calibration, NOT emergence: every specimen is hand-built'; T-REDISCOVER NOT queued", f"{DE}/*.json",
 "no search was run on designed tasks (gaps 11-15, pipeline designs); designed_echoes holds engine evaluations of hand-built genomes only",
 "UNDERIVABLE", "0 searches", "no", "yes",
 "T-DE-1 tested the model, not search, so 'search never produced' has no search denominator (ARC3 s6 itself says T-REDISCOVER was not queued). Corrected: 'the model designs mechanisms (pipeline depth, combs) not observed among existing champions; whether search can reach them is untested'. It is still counted as one of the four 'independent lines' for H6."],
["6d", "SYNTHESIS_2026-09-28_ARC3.md", "s2 (retraction of the designed-echo 'mixture signature')",
 "CHANCE/CHANCE at the handoff reproduces W-F's phase-mixture signature (claim retracted)", f"{DE}/RESULT.md",
 "retracted by CORRECTION (W-I identity); W-M later found lag -6 is a real per-trial mixture", f"{DE}/instruments.json",
 "E2 lag -6: site_all CHANCE, channel_all CHANCE, pay1 CHANCE (raw consistent)", "MATCH", "1 tick of 1 design", "yes", "no",
 "The retraction is correctly carried into ARC3 s2."],
["JCa", "SYNTHESIS_2026-09-28_ARC2.md", "s3",
 "4781b0a1 is SOURCE-LATCHED REGENERATION; the 5 sensors latch the cue and keep firing", f"{JC}/RESULT.md",
 "erasing S at the sensors kills (.50); actuator/others .79 = normal; Kp/w/inbox irrelevant; preset-rule verdict UNRESOLVED",
 f"{JC}/out_j5.json; out_j_probe.json",
 "J5a sensors .500, actuator .790, others .790 (normal .790); Kp erase diff exactly 0; w diff 0",
 "PARTIAL", "1 specimen, 64 worlds", "yes", "yes",
 "The raw data support 'the necessary S is at the sensors'. 'Latch and keep firing' is a reading of the program. The preregistered verdict was UNRESOLVED (no hypothesis met its rule), and ARC2 names the mechanism without that caveat. The count '5' sensors comes from the env (n_maj); it is not counted in out/."],
["JCb", "SYNTHESIS_2026-09-28_ARC2.md", "s3",
 "the bit is at the source until the transmission deadline (~readout minus max delay) and in the channel after it", f"{JC}/RESULT.md",
 "erase_S kills through t0+9, recovers t0+10 (.62), harmless t0+11..14; flush worst at t0+12..13", f"{JC}/out_j5.json (J5b)",
 "erase_S exactly .50 at t0+1..8, .56 at t0+9, .62 at t0+10, .70-.79 at t0+11..14, .645 at t0+15; flush .50 at t0+1..2, .60-.62 at t0+3..11, .535/.546 at t0+12..13, .745 at t0+15",
 "PARTIAL", "1 specimen, 15 ticks, 64 worlds", "yes", "no",
 "The profile matches RESULT, except that t0+9 is a partial kill (.56). 'Readout minus max delay' cannot be computed from raw (no readout or delay values in out/). The H-HAND preset rule failed (8-tick overlap where both carriers are necessary), and ARC2 does not mention it."],
["JCc", "SYNTHESIS_2026-09-28_ARC2.md", "s3",
 "The single-swap ~0.5 was a conflict between two pipeline stages holding the same bit", f"{JC}/RESULT.md",
 "mid-interval single swaps ~0.5; joint swap FLIP; J4 pre-cue joint swap no effect (.78)", f"{JC}/out_j_probe.json",
 "t0+8: S .582, site .486, channel .516, pay1 .516 (all CHANCE); joint .221 FLIP; J4 t0-1 joint .779 NO-EFFECT",
 "PARTIAL", "1 specimen, 1 tick", "yes", "yes",
 "The numbers match. 'Conflict, not synergy' is an interpretation. W-I later showed that site+chan ~1 is a mirror-pair identity, so ~0.5 single swaps cannot by themselves tell conflict from mixture."],
["JCd", "PTE_ENGINE_CARD.md", "KNOWN FAILURE MODES: PRESENT-BUT-UNUSED",
 "4781b0a1 pay0: decoder 0.85, swap no effect", f"{JC}/RESULT.md", "pay0 decodes at .85 out of sample; swap has no effect; pay1 swap -> .52",
 f"{JC}/out_j_probe.json (J3, swap t0+8)",
 "pay0 decoder .848 [.802,.889]; pay0 swap NO-EFFECT (= normal .766); pay1 swap .516 CHANCE",
 "MATCH", "1 specimen, 1 tick", "yes", "no",
 "RESULT's W-C cross-check notes that pay0's decodability may be presence leaking into content (F7)."],
["JCe", "PTE_ENGINE_CARD.md", "MEMORY: 'a JOINT channel+site carrier (MAJ 4781b0a1)'",
 "a JOINT channel+site carrier (MAJ 4781b0a1)", f"{JC}/RESULT.md",
 "verdict UNRESOLVED; reading = source-latched regeneration, the same bit at two stages, 'not a synergistic code'", f"{JC}/out_j_probe.json",
 "joint swap FLIP (.221) while single swaps are CHANCE at t0+8: 'joint' only in the swap sense",
 "PARTIAL", "1 specimen", "yes", "yes",
 "The engine-card label (currency 09-27) predates the joint_carrier RESULT and ARC2 s3 ('No genuinely synergistic carrier observed'). Suggested: 'a source-latch -> channel handoff carrier (both stages necessary at mid-interval; not shown to be a synergistic code)'. Later BACKLOG lines (W-M era) call it a clean JOINT carrier again; that is outside group C."],
]
with open(os.path.join(here, "rows_groupC.csv"), "w", newline="", encoding="utf-8") as f:
    w = csv.writer(f)
    w.writerow(H)
    w.writerows(rows)
print(len(rows), "rows written to rows_groupC.csv")
