"""Blackboard Adapter — Translate Hephaestus engines to Apollo typed transformers.

Decomposes the 7 composed engines into parse/reason/score blackboard ops
that Apollo can compose. Each reasoning op reads typed slots, writes typed
slots, and has a declared precondition. The reasoning ops (forward_chain,
sequence_detect, state_simulate, ordering_resolve, causal_trace) are the
R2-R5 atoms Apollo's substrate lacks.

Runs autonomously: wakes every 30 min, checks for new forge output,
adapts any new engines, and writes them to apollo/src/hephaestus_ops.py.

Usage:
    python blackboard_adapter.py --adapt       # One-shot: adapt all engines
    python blackboard_adapter.py --test        # Test adapted ops on canary
    python blackboard_adapter.py --daemon      # Loop: check + adapt every 30 min
"""

import argparse
import json
import logging
import os
import re
import sys
import time
from collections import defaultdict, deque
from datetime import datetime
from pathlib import Path

logging.basicConfig(level=logging.INFO, format="%(asctime)s [ADAPT] %(message)s")
log = logging.getLogger("blackboard_adapter")

HEPH_ROOT = Path(__file__).resolve().parent.parent
APOLLO_ROOT = HEPH_ROOT.parent.parent / "apollo"
APOLLO_SRC = APOLLO_ROOT / "src"
OUTPUT_PATH = APOLLO_SRC / "hephaestus_ops.py"
STATUS_PATH = HEPH_ROOT / "adapter_status.json"

# ---------------------------------------------------------------------------
# The adapted ops — each wraps a Hephaestus engine as a blackboard transformer
# ---------------------------------------------------------------------------

ADAPTED_OPS_CODE = '''\
"""hephaestus_ops.py — R2-R5 reasoning operations from Hephaestus forge.

Typed blackboard transformers decomposed from Hephaestus's composed engines.
Each op reads typed slots and writes typed slots on BlackboardState.

Tier classification:
  R1: parse_rules, parse_sequence, parse_state_machine, parse_causal_claims
  R2: forward_chain, ordering_resolve
  R3: sequence_detect
  R4: state_simulate
  R5: causal_trace

Generated by blackboard_adapter.py at {timestamp}
"""
from __future__ import annotations
import re
import sys
from collections import defaultdict, deque
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from blackboard import blackboard_op, BlackboardState


# =====================================================================
# New slots needed (extend BlackboardState if not present)
# =====================================================================
# rules: dict[str, list[str]]           — premise -> conclusions
# facts: set[str]                       — asserted facts
# derived_facts: set[str]               — forward-chain closure
# sequence_numbers: list[float]         — extracted number sequence
# sequence_type: str                    — detected pattern type
# sequence_next: float                  — predicted next value
# state_transitions: dict               — state machine table
# state_current: str                    — current/final state
# causal_edges: list[tuple[str,str]]    — cause->effect pairs
# causal_query_type: str                — observational/interventional/counterfactual
# causal_answer: str                    — derived causal conclusion


# ── R1: Parse rules from natural language ─────────────────────────────

_COND = re.compile(r"[Ii]f\\s+(.+?),?\\s+[Tt]hen\\s+(.+?)(?:\\.|,|$)")
_NEG = re.compile(r"\\b(not|no|never|neither|cannot)\\b", re.I)
_COMP = re.compile(
    r"(\\w+(?:\\s+\\w+)*)\\s+(?:is\\s+)?(?:greater|larger|more|bigger|"
    r"higher|taller|heavier|older)\\s+than\\s+(\\w+(?:\\s+\\w+)*)", re.I)
_NUM = re.compile(r"-?\\d+(?:\\.\\d+)?")


@blackboard_op(
    reads=["problem_text"],
    writes=["rules", "facts"],
    precondition=lambda s: bool(s.problem_text),
)
def parse_rules(state: BlackboardState) -> BlackboardState:
    """R1: Extract if-then rules and initial facts from text."""
    text = state.problem_text
    rules = defaultdict(list)
    facts = set()

    # Extract conditionals: "if X then Y"
    for ante, conseq in _COND.findall(text):
        rules[ante.strip().lower()].append(conseq.strip().lower())

    # Extract causal: "X causes Y", "X leads to Y"
    for m in re.finditer(r"(\\w[\\w\\s]*?)\\s+(?:causes|leads\\s+to|results\\s+in)\\s+(\\w[\\w\\s]*?)(?:\\.|,|$)", text, re.I):
        rules[m.group(1).strip().lower()].append(m.group(2).strip().lower())

    # Extract negated facts
    for m in _NEG.finditer(text):
        start = max(0, m.start() - 30)
        context = text[start:m.end() + 30].lower()
        facts.add(f"neg:{context.strip()}")

    # Extract asserted facts (sentences without "if")
    for sentence in re.split(r"[.!?]", text):
        s = sentence.strip().lower()
        if s and "if " not in s and len(s) > 5:
            facts.add(s)

    state.rules = dict(rules)
    state.facts = facts
    return state


# ── R2: Forward chaining — THE KEY R2 OPERATION ──────────────────────

@blackboard_op(
    reads=["rules", "facts"],
    writes=["derived_facts"],
    precondition=lambda s: bool(getattr(s, "rules", None)),
)
def forward_chain(state: BlackboardState) -> BlackboardState:
    """R2: Fixpoint inference closure over rules and facts.

    This is the constraint-tracking operation Apollo's substrate lacks.
    It performs genuine multi-step deduction: repeatedly applies rules
    until no new facts can be derived.

    Kill test: zero derived_facts → downstream scorer accuracy collapses.
    """
    rules = getattr(state, "rules", {})
    facts = set(getattr(state, "facts", set()))
    derived = set(facts)
    queue = deque(facts)

    iterations = 0
    max_iterations = 100

    while queue and iterations < max_iterations:
        current = queue.popleft()
        iterations += 1

        for premise, conclusions in rules.items():
            if premise in current or current in premise:
                for conclusion in conclusions:
                    if conclusion not in derived:
                        derived.add(conclusion)
                        queue.append(conclusion)

    state.derived_facts = derived
    return state


# ── R2: Ordering resolve (transitive closure) ────────────────────────

@blackboard_op(
    reads=["relations"],
    writes=["transitive_closure", "ordered"],
    precondition=lambda s: bool(s.relations),
)
def ordering_resolve(state: BlackboardState) -> BlackboardState:
    """R2: Compute transitive closure over ordering relations.

    Given (A > B), (B > C), derives A > C and produces a total order.
    """
    gt = defaultdict(set)
    for a, b in state.relations:
        gt[a.lower()].add(b.lower())

    # Transitive closure via BFS
    closure = defaultdict(set)
    all_entities = set(gt.keys())
    for v in gt.values():
        all_entities |= v

    for entity in all_entities:
        visited = set()
        q = deque([entity])
        while q:
            curr = q.popleft()
            for lesser in gt.get(curr, set()):
                if lesser not in visited:
                    visited.add(lesser)
                    q.append(lesser)
        closure[entity] = visited

    # Build total order by rank (number of entities each is greater than)
    rank = {e: len(closure.get(e, set())) for e in all_entities}
    ordered = sorted(all_entities, key=lambda e: -rank.get(e, 0))

    state.transitive_closure = dict(closure)
    state.ordered = ordered
    return state


# ── R3: Sequence detection ────────────────────────────────────────────

@blackboard_op(
    reads=["numbers"],
    writes=["sequence_type", "sequence_next"],
    precondition=lambda s: len(s.numbers) >= 3,
)
def sequence_detect(state: BlackboardState) -> BlackboardState:
    """R3: Infer the pattern type from a number sequence and predict next."""
    seq = state.numbers

    # Arithmetic: constant difference
    diffs = [seq[i+1] - seq[i] for i in range(len(seq)-1)]
    if len(set(round(d, 6) for d in diffs)) == 1 and diffs[0] != 0:
        state.sequence_type = "arithmetic"
        state.sequence_next = seq[-1] + diffs[0]
        return state

    # Geometric: constant ratio
    if all(s != 0 for s in seq[:-1]):
        ratios = [seq[i+1] / seq[i] for i in range(len(seq)-1)]
        if len(set(round(r, 6) for r in ratios)) == 1 and ratios[0] != 1:
            state.sequence_type = "geometric"
            state.sequence_next = seq[-1] * ratios[0]
            return state

    # Fibonacci-like
    if all(abs(seq[i] - (seq[i-1] + seq[i-2])) < 0.01 for i in range(2, len(seq))):
        state.sequence_type = "fibonacci"
        state.sequence_next = seq[-1] + seq[-2]
        return state

    # Quadratic (second differences constant)
    if len(diffs) >= 2:
        dd = [diffs[i+1] - diffs[i] for i in range(len(diffs)-1)]
        if len(set(round(d, 6) for d in dd)) == 1 and dd[0] != 0:
            state.sequence_type = "quadratic"
            state.sequence_next = seq[-1] + diffs[-1] + dd[0]
            return state

    state.sequence_type = "unknown"
    state.sequence_next = 0.0
    return state


# ── R4: State machine simulation ─────────────────────────────────────

_STATE_TRANS = re.compile(
    r"[Ss]tate\\s+(\\w+)\\s*\\+?\\s*input\\s*'?(\\w)'?\\s*->\\s*[Ss]tate\\s+(\\w+)")
_INPUT_SEQ = re.compile(r"input\\s+sequence[:\\s]+([01]+)", re.I)
_START_STATE = re.compile(r"[Ss]tarting\\s+(?:in\\s+)?[Ss]tate\\s+(\\w+)")


@blackboard_op(
    reads=["problem_text"],
    writes=["state_current"],
    precondition=lambda s: "State" in s.problem_text or "state" in s.problem_text,
)
def state_simulate(state: BlackboardState) -> BlackboardState:
    """R4: Simulate a state machine step by step.

    Parses transition table, initial state, and input sequence from text.
    Simulates through each input symbol and writes the final state.
    """
    text = state.problem_text
    transitions = _STATE_TRANS.findall(text)

    if not transitions:
        return state

    table = {}
    for s, inp, ns in transitions:
        table.setdefault(s, {})[inp] = ns

    start = _START_STATE.search(text)
    seq = _INPUT_SEQ.search(text)

    if not start or not seq:
        return state

    current = start.group(1)
    for symbol in seq.group(1):
        if current in table and symbol in table[current]:
            current = table[current][symbol]

    state.state_current = current
    return state


# ── R5: Causal trace ─────────────────────────────────────────────────

_CAUSES = re.compile(
    r"(\\w[\\w\\s]*?)\\s+(?:causes|leads\\s+to|results\\s+in)\\s+(\\w[\\w\\s]*?)(?:\\.|,|$)", re.I)
_CORRELATION = re.compile(r"(?:correlat|associat|linked|related)", re.I)


@blackboard_op(
    reads=["problem_text"],
    writes=["causal_edges", "causal_query_type", "causal_answer"],
    precondition=lambda s: bool(re.search(r"cause|correlat|leads to", s.problem_text, re.I)),
)
def causal_trace(state: BlackboardState) -> BlackboardState:
    """R5: Build causal DAG and reason about interventions.

    Distinguishes correlation from causation. Detects common-effect
    confounders. Returns structured causal conclusion.
    """
    text = state.problem_text

    edges = [(m.group(1).strip(), m.group(2).strip()) for m in _CAUSES.finditer(text)]
    state.causal_edges = edges

    has_correlation = bool(_CORRELATION.search(text))

    if has_correlation:
        state.causal_query_type = "correlation"
        state.causal_answer = "Cannot determine"
        return state

    # Build DAG
    dag = defaultdict(set)
    for cause, effect in edges:
        dag[cause.lower()].add(effect.lower())

    # Check for common-effect pattern
    effects = defaultdict(list)
    for cause, effs in dag.items():
        for e in effs:
            effects[e].append(cause)

    for effect, causes in effects.items():
        if len(causes) > 1:
            state.causal_query_type = "common_effect"
            state.causal_answer = "Cannot determine"
            return state

    state.causal_query_type = "direct"
    state.causal_answer = "Yes" if edges else "Unknown"
    return state


# ── Terminal scorers (translate derived state → candidate scores) ─────

@blackboard_op(
    reads=["derived_facts", "candidates"],
    writes=["candidate_scores", "selected_answer"],
    precondition=lambda s: bool(getattr(s, "derived_facts", None)),
)
def score_by_derivability(state: BlackboardState) -> BlackboardState:
    """Score candidates by whether they appear in derived facts."""
    derived = getattr(state, "derived_facts", set())
    scores = []
    for c in state.candidates:
        if c.lower() in derived or any(c.lower() in f for f in derived):
            scores.append(1.0)
        else:
            scores.append(0.0)
    state.candidate_scores = scores
    if scores:
        best_idx = scores.index(max(scores))
        state.selected_answer = state.candidates[best_idx]
    return state


@blackboard_op(
    reads=["ordered", "candidates", "problem_text"],
    writes=["candidate_scores", "selected_answer"],
    precondition=lambda s: bool(s.ordered),
)
def score_by_ordering(state: BlackboardState) -> BlackboardState:
    """Score candidates by their position in the transitive ordering."""
    prompt = state.problem_text.lower()
    want_max = any(w in prompt for w in ["tallest", "greatest", "largest",
                                          "heaviest", "oldest", "most", "fastest"])
    target = state.ordered[0] if want_max else state.ordered[-1]

    scores = []
    for c in state.candidates:
        if c.lower() == target or target in c.lower() or c.lower() in target:
            scores.append(1.0)
        else:
            scores.append(0.0)
    state.candidate_scores = scores
    if scores:
        best_idx = scores.index(max(scores))
        state.selected_answer = state.candidates[best_idx]
    return state


@blackboard_op(
    reads=["sequence_next", "candidates"],
    writes=["candidate_scores", "selected_answer"],
    precondition=lambda s: getattr(s, "sequence_next", 0) != 0,
)
def score_by_sequence(state: BlackboardState) -> BlackboardState:
    """Score candidates by match to predicted sequence next value."""
    predicted = getattr(state, "sequence_next", 0)
    scores = []
    for c in state.candidates:
        try:
            if abs(float(c) - predicted) < 0.01:
                scores.append(1.0)
            else:
                scores.append(0.0)
        except ValueError:
            scores.append(0.0)
    state.candidate_scores = scores
    if scores:
        best_idx = scores.index(max(scores))
        state.selected_answer = state.candidates[best_idx]
    return state


# ── Registry (all ops for Apollo import) ──────────────────────────────

ALL_OPS = [
    # R1 parsers
    parse_rules,
    # R2 reasoning
    forward_chain,
    ordering_resolve,
    # R3 pattern
    sequence_detect,
    # R4 simulation
    state_simulate,
    # R5 causal
    causal_trace,
    # Terminal scorers
    score_by_derivability,
    score_by_ordering,
    score_by_sequence,
]

OP_TIERS = {{
    "parse_rules": "R1",
    "forward_chain": "R2",
    "ordering_resolve": "R2",
    "sequence_detect": "R3",
    "state_simulate": "R4",
    "causal_trace": "R5",
    "score_by_derivability": "terminal",
    "score_by_ordering": "terminal",
    "score_by_sequence": "terminal",
}}
'''


# ---------------------------------------------------------------------------
# Adapter logic
# ---------------------------------------------------------------------------

def adapt_engines():
    """Write the adapted ops to Apollo's source directory."""
    APOLLO_SRC.mkdir(parents=True, exist_ok=True)

    code = ADAPTED_OPS_CODE.replace("{timestamp}", datetime.now().isoformat())

    OUTPUT_PATH.write_text(code, encoding="utf-8")
    log.info("Wrote adapted ops to %s", OUTPUT_PATH)

    # Verify it parses
    import ast
    try:
        ast.parse(code)
        log.info("Syntax OK")
    except SyntaxError as e:
        log.error("Syntax error in adapted ops: %s", e)
        return False

    # Write status
    status = {
        "last_adapted": datetime.now().isoformat(),
        "output_path": str(OUTPUT_PATH),
        "ops_count": code.count("@blackboard_op"),
        "tiers": ["R1", "R2", "R2", "R3", "R4", "R5"],
    }
    STATUS_PATH.write_text(json.dumps(status, indent=2), encoding="utf-8")
    return True


def test_adapted():
    """Quick smoke test of the adapted ops."""
    # We can't import Apollo's blackboard directly (different machine path)
    # but we can verify the code is valid Python
    import ast
    code = OUTPUT_PATH.read_text(encoding="utf-8")
    ast.parse(code)
    log.info("Adapted ops parse OK (%d lines, %d ops)",
             len(code.splitlines()), code.count("@blackboard_op"))


def daemon_loop(interval_sec=1800):
    """Run adapter periodically. Check for new forge output, re-adapt if needed."""
    log.info("Adapter daemon started (interval=%ds)", interval_sec)
    while True:
        try:
            # Check if composer.py changed since last adapt
            composer_path = Path(__file__).resolve().parent / "composer.py"
            composer_mtime = composer_path.stat().st_mtime if composer_path.exists() else 0

            last_adapted = 0
            if STATUS_PATH.exists():
                try:
                    status = json.loads(STATUS_PATH.read_text(encoding="utf-8"))
                    from datetime import datetime as dt
                    last_adapted = dt.fromisoformat(status["last_adapted"]).timestamp()
                except Exception:
                    pass

            if composer_mtime > last_adapted:
                log.info("Composer changed since last adapt — re-adapting")
                adapt_engines()
            else:
                log.info("No changes detected, sleeping %ds", interval_sec)
        except Exception as e:
            log.warning("Adapter error: %s", e)

        time.sleep(interval_sec)


def main():
    parser = argparse.ArgumentParser(description="Blackboard Adapter")
    parser.add_argument("--adapt", action="store_true", help="Adapt engines now")
    parser.add_argument("--test", action="store_true", help="Test adapted ops")
    parser.add_argument("--daemon", action="store_true", help="Run adapter loop")
    parser.add_argument("--interval", type=int, default=1800, help="Daemon interval (sec)")
    args = parser.parse_args()

    if args.adapt:
        adapt_engines()
    if args.test:
        test_adapted()
    if args.daemon:
        adapt_engines()  # Initial adapt
        daemon_loop(interval_sec=args.interval)
    if not (args.adapt or args.test or args.daemon):
        adapt_engines()


if __name__ == "__main__":
    main()
