"""Write HEPHAESTUS_HANDOFF.txt (charter §21): everything a Master Smith needs to start cold."""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from hephaestus.src import packet as P  # noqa: E402


def main() -> None:
    packets = list(P.iter_packets())
    ready = [p for p in packets if p["STATUS"] == "READY-FOR-DEEP-MINT"]
    testing = [p for p in packets if p["STATUS"] in ("APPRENTICE-TESTING", "APPRENTICE-EXHAUSTED", "CANDIDATE-PRODUCED")]
    last_deep = None
    dm = P.HEPH / "deep_mint_sessions"
    if dm.exists():
        ms = sorted(dm.glob("*/manifest.json"))
        if ms:
            last_deep = json.loads(ms[-1].read_text(encoding="utf-8"))
    L = []
    L.append("HEPHAESTUS_HANDOFF  (regenerated by hephaestus.src.handoff; charter s21)  " + P.now_iso())
    L.append("")
    L.append("CURRENT MISSION")
    L.append("  Prepare Mint Packets for reasoning-mechanism walls the frozen substrate cannot express;")
    L.append("  cheap models scout continuously (Apprentice Forge); a capable agent mints ONLY when the")
    L.append("  operator invokes it (Master Smith). Nothing here auto-escalates to premium models.")
    L.append("")
    L.append("READ FIRST, IN ORDER")
    L.append("  1. roles/Hephaestus/CHARTER_AMENDMENT_2026-09-01_forge_queue_master_smith.md  (governing)")
    L.append("  2. stations/M3_STATUS.md (newest section first)  3. hephaestus/TOP_READY_MINTS.txt")
    L.append("  4. hephaestus/mint_queue/<MINT_ID>/packet.md for each target, then attempts/ (THE SCRAP, s16)")
    L.append("  5. primitive registry: agents/hephaestus/src/forge_primitives.py (25 fns) + apollo/src/blackboard_evolve.py REGISTRY (27 ops)")
    L.append("  6. hephaestus/counterfeit_museum/README.md   7. admission rules (below)")
    L.append("")
    L.append(f"QUEUE  ({len(packets)} packets)  ready-for-deep-mint: {len(ready)}   in apprentice: {len(testing)}")
    for p in packets:
        L.append(f"  {p['MINT_ID']}  {p['STATUS']:<22} {str(p.get('FAILURE_FAMILY'))[:80]}")
    L.append("")
    if ready or testing:
        p = (ready or testing)[0]
        L.append(f"HIGHEST-RANKED TARGET: {p['MINT_ID']} [{p['STATUS']}]")
        L.append(f"  interface: {json.dumps(p['DESIRED_TYPED_INTERFACE'].get('signature')) if isinstance(p.get('DESIRED_TYPED_INTERFACE'), dict) else '-'}")
        L.append(f"  reproducer: {p.get('MINIMAL_REPRODUCER')}")
        L.append(f"  cheap attempts: {len(p.get('CHEAP_MODEL_ATTEMPTS') or [])}  failure families: "
                 f"{', '.join(f['family'] for f in (p.get('CHEAP_MODEL_FAILURES') or [])) or '-'}")
        bf = p.get("BEST_FAILED_CANDIDATE") or {}
        L.append(f"  best failed candidate: {bf.get('file', '-')}  holdout {bf.get('holdout_acc', '-')}  families {bf.get('failure_families', '-')}")
        ie = p.get("INDEPENDENT_EVALUATOR") or {}
        L.append(f"  independent evaluator: {ie.get('status', '-') if isinstance(ie, dict) else ie}")
        L.append("")
    L.append("CURRENT EVALUATOR")
    L.append("  dev harness: hephaestus/src/wall_<wall>.py (Hephaestus-authored; development only).")
    L.append("  independent held-out: roles/Charon/apollo_e9/charon_battery_E9.json (Charon, blind) -- DO NOT READ FOR DEVELOPMENT.")
    L.append("  frozen Apollo evaluator: aporia/iq (IQ-PORT-1 configuration, hash 10fa10db...). Post-E9 evaluator of record: NOT YET NAMED by Apollo.")
    L.append("")
    L.append("ADMISSION RULES (the smith does not inherit admission authority; charter s14)")
    L.append("  - knockout (op removed -> effect vanishes); counterfeit controls (constant / keyword / order mutants);")
    L.append("  - held-out construction by a seat that did not write the op; cross-world eval where appropriate;")
    L.append("  - independence chain: supplier != prereg author != prompt author != grader != adjudicator;")
    L.append("  - Ergon admission criterion: executable, contribution measurable by exact execution under a metered budget")
    L.append("    against a frozen comparator (roles/Ergon/CHARTER_2026-08-30_memory_metabolism.md:83-85).")
    L.append("  - delta class fixed BEFORE execution: dE_port / dE_synth / dE_discover (aporia/docs/DOCTRINE_counterfeit_battery_and_ladder_2026-08-25.md).")
    L.append("")
    L.append("AFTER A DEEP MINT SESSION (charter s22) write hephaestus/deep_mint_sessions/<stamp>/manifest.json +")
    L.append("  candidates/, failed/, traces/, counterexamples.md, knockout.json, RECOMMENDED_NEXT_STATE.txt; then run")
    L.append("  python -m hephaestus.src.refine && python -m hephaestus.src.rank && python -m hephaestus.src.handoff")
    L.append("")
    L.append(f"LAST DEEP-MINT RESULT: {json.dumps(last_deep)[:300] if last_deep else 'none yet (no Master Smith session has been invoked)'}")
    L.append("")
    L.append("STANDING RULINGS (Addendum 1, 2026-09-01)")
    L.append("  - Do NOT summon a Master Smith for MINT-0001: reclassified Level-1 composition (semantic-only closure test,")
    L.append("    frozen primitives synthesise the kernel at depth 1) + a REPRESENTATION adapter problem, routed out of the mint path.")
    L.append("  - Every packet must answer 'if perfect semantic state were injected, what is still missing?' (SEMANTIC_KERNEL_SPEC /")
    L.append("    REPRESENTATION_ADAPTER_SPEC) before leaving TRIAGE. 'Almost nothing' => not a mint.")
    L.append("  - Results are two coordinates (coverage, conditional correctness); abstention is never folded into a scalar.")
    L.append("  - A dev pass without mechanism coverage is PASS_DEV_WITH_UNTESTED_COMPONENT / PASS_DEV_UNVERIFIED_COVERAGE, not PASS_DEV.")
    L.append("  - A smith cycle ends in at least one new executed discriminating observation; five cycles per invocation.")
    L.append("")
    L.append("KNOWN BLOCKERS")
    L.append("  - Independent held-out generator for vacuous_truth (Aporia TRANSFER-1 prerequisite) does not exist; Apollo's canary is degenerate (Yes 5/5).")
    L.append("  - Apollo's 0.833 ceiling retracted (E9); no post-E9 evaluator of record named.")
    L.append("  - Operator no-touch (2026-08-24) scope unresolved (Lexis decision #4).")
    L.append("  - Cheap endpoints on M3: nvidia NIM free tier + local ollama/phi3 only; gemini/groq/openrouter/deepseek keys dead here.")
    L.append("")
    L.append("ENV: PYTHONPATH=C:\\prometheus ; keys.py shim at repo root (gitignored) resolves NVIDIA/GITHUB from agents/hephaestus/.env ; python 3.11")
    (P.HEPH / "HEPHAESTUS_HANDOFF.txt").write_text("\n".join(L) + "\n", encoding="utf-8")
    print("\n".join(L))


if __name__ == "__main__":
    main()
