"""
Lean 4 verification pipeline for Rhea's self-improving loop.

The loop:
1. Evolved model generates reasoning chains for math problems
2. Chains are translated to Lean 4 proof sketches
3. Lean 4 verifies them (binary: compiles or doesn't)
4. Verified chains become training data for next generation seed
5. No frontier model in the loop — prevents suppression propagation

This module handles steps 2-3: translating model output to Lean 4
and running verification. Step 4 (training data generation) is in
proof_corpus.py.

Requires: Lean 4 installed via elan (https://github.com/leanprover/elan)
"""

import subprocess
import tempfile
import json
from pathlib import Path
from dataclasses import dataclass


@dataclass
class VerificationResult:
    """Result of attempting to verify a reasoning chain in Lean 4."""
    problem: str
    model_answer: str
    lean_code: str
    verified: bool
    error_message: str | None
    compile_time_ms: float


# === Simple arithmetic proof templates ===
# These map trap-style problems to Lean 4 theorem statements.
# For the initial pipeline, we use decide/native_decide for
# decidable arithmetic — no proof search needed.

LEAN_ARITHMETIC_TEMPLATE = """
-- Auto-generated by Rhea proof pipeline
-- Problem: {problem}
-- Model answer: {answer}

theorem rhea_check : {lean_statement} := by decide
"""

LEAN_HEADER = """
-- Rhea verification corpus
-- Generated: {timestamp}
"""


def arithmetic_to_lean(problem: str, answer: str) -> str | None:
    """
    Translate a simple arithmetic problem + answer to a Lean 4 theorem.

    Returns Lean 4 source code, or None if the problem type isn't supported.

    Supported patterns:
      "What is 7 + 8?" answer="15"  →  theorem: 7 + 8 = 15
      "What is 13 - 7?" answer="6"  →  theorem: 13 - 7 = 6
      "What is 6 × 4?" answer="24"  →  theorem: 6 * 4 = 24
    """
    import re

    # Try to parse "What is X op Y?"
    patterns = [
        (r"(\d+)\s*\+\s*(\d+)", "+"),
        (r"(\d+)\s*-\s*(\d+)", "-"),
        (r"(\d+)\s*[×x\*]\s*(\d+)", "*"),
        (r"(\d+)\s*[÷/]\s*(\d+)", "/"),
    ]

    for pattern, op in patterns:
        match = re.search(pattern, problem)
        if match:
            a, b = match.group(1), match.group(2)
            try:
                expected = int(answer.strip())
            except ValueError:
                return None

            lean_statement = f"{a} {op} {b} = {expected}"
            return LEAN_ARITHMETIC_TEMPLATE.format(
                problem=problem,
                answer=answer,
                lean_statement=lean_statement,
            )

    return None


def comparison_to_lean(problem: str, answer: str) -> str | None:
    """
    Translate comparison/ordering problems to Lean 4.

    "Is 9.11 larger than 9.9?" answer="No"
    → theorem: ¬(9.11 > 9.9)  (using rational arithmetic)
    """
    # For now, handle simple integer comparisons
    # Decimal/fraction comparisons need Lean's Rat type
    import re

    # "Is X larger than Y?" patterns
    match = re.search(r"Is\s+(\d+)\s+larger than\s+(\d+)", problem)
    if match:
        a, b = int(match.group(1)), int(match.group(2))
        ans = answer.strip().lower()
        if ans in ("no", "false"):
            return LEAN_ARITHMETIC_TEMPLATE.format(
                problem=problem, answer=answer,
                lean_statement=f"¬({a} > {b})" if a <= b else f"{a} > {b}",
            )
        elif ans in ("yes", "true"):
            return LEAN_ARITHMETIC_TEMPLATE.format(
                problem=problem, answer=answer,
                lean_statement=f"{a} > {b}",
            )

    return None


def logic_to_lean(problem: str, answer: str) -> str | None:
    """
    Translate simple logic problems to Lean 4.

    "If A = B and B = C, does A = C?" → theorem using Eq.trans
    """
    if "A = B and B = C" in problem and "A = C" in problem:
        ans = answer.strip().lower()
        if ans in ("yes", "true"):
            return """
-- Problem: {problem}
-- Model answer: {answer}

theorem rhea_transitivity (A B C : Nat) (h1 : A = B) (h2 : B = C) : A = C :=
  Eq.trans h1 h2
""".format(problem=problem, answer=answer)

    return None


def verify_lean_code(lean_code: str, timeout_seconds: int = 30) -> VerificationResult:
    """
    Write Lean 4 code to a temp file and attempt to compile it.

    Returns VerificationResult with verified=True if compilation succeeds.
    """
    import time

    with tempfile.NamedTemporaryFile(mode="w", suffix=".lean", delete=False) as f:
        f.write(lean_code)
        temp_path = f.name

    t0 = time.time()
    try:
        result = subprocess.run(
            ["lean", temp_path],
            capture_output=True,
            text=True,
            timeout=timeout_seconds,
        )
        elapsed_ms = (time.time() - t0) * 1000

        if result.returncode == 0:
            return VerificationResult(
                problem="", model_answer="", lean_code=lean_code,
                verified=True, error_message=None,
                compile_time_ms=elapsed_ms,
            )
        else:
            return VerificationResult(
                problem="", model_answer="", lean_code=lean_code,
                verified=False, error_message=result.stderr[:500],
                compile_time_ms=elapsed_ms,
            )

    except subprocess.TimeoutExpired:
        elapsed_ms = (time.time() - t0) * 1000
        return VerificationResult(
            problem="", model_answer="", lean_code=lean_code,
            verified=False, error_message="TIMEOUT",
            compile_time_ms=elapsed_ms,
        )
    except FileNotFoundError:
        return VerificationResult(
            problem="", model_answer="", lean_code=lean_code,
            verified=False, error_message="lean not found — install via elan",
            compile_time_ms=0,
        )
    finally:
        Path(temp_path).unlink(missing_ok=True)


def verify_trap_answer(trap, model_answer: str) -> VerificationResult | None:
    """
    Attempt to verify a model's answer to a trap using Lean 4.

    Returns VerificationResult if the trap type is supported, None otherwise.
    """
    translators = [
        arithmetic_to_lean,
        comparison_to_lean,
        logic_to_lean,
    ]

    for translator in translators:
        lean_code = translator(trap.prompt, model_answer)
        if lean_code is not None:
            result = verify_lean_code(lean_code)
            result.problem = trap.prompt
            result.model_answer = model_answer
            return result

    return None  # trap type not yet supported for Lean verification


def batch_verify(traps, model_answers: dict[str, str]) -> list[VerificationResult]:
    """
    Verify a batch of trap answers.

    Args:
        traps: list of Trap objects
        model_answers: dict mapping trap.name -> model's answer string

    Returns:
        list of VerificationResult (only for supported trap types)
    """
    results = []
    for trap in traps:
        answer = model_answers.get(trap.name)
        if answer is None:
            continue
        result = verify_trap_answer(trap, answer)
        if result is not None:
            results.append(result)
    return results
