"""Batch 06 of the fossil harvest (2026-09-13): UNLOCK, FAILURE MACHINERY, PRESSURE, CULTURES -- records.

    python -m techne.fossils.batches.batch06

Charter: roles/Techne/prompts/2026-09-12_batch06/OPERATOR_CHARTER.md. Records added incrementally
as each phase lands; every "loser" / "known-bad" label is the human record's verdict, cited.
"""
from __future__ import annotations

from .. import record

S = []


def spec(sid, **kw):
    S.append(record.skeleton(sid, **kw))


TUHS = "https://www.tuhs.org/Archive/Distributions/UCB/4BSD/%s/%s"


def tape(version):
    files = ["FORMAT", "stand.gz", "miniroot.gz", "rootdump.gz", "usr.tar.gz"]
    return {"artifacts": [{"kind": "url", "url": TUHS % (version, f), "filename": f, "extract": False} for f in files]}


# ============================ PHASE 1 / TECHNE-69: the historical TCP world ====================
_tape_common = dict(
    domain=["operating-system", "networks", "TCP", "historical-toolchain", "distribution-tape", "vax"],
    source_type="HISTORICAL_ARCHIVE_MIRROR",
    license={"spdx": "BSD-4-Clause", "status": "permissive (original BSD licence; Caldera 2002 grant covers 32V-derived code); AT&T-derived portions were released by Caldera/SCO 2002", "evidence": "TUHS archive terms; Caldera licence 2002"},
    language=["C (4BSD kernel and userland)", "VAX assembler"],
    build_system="none: a distribution TAPE (stand / miniroot / rootdump / usr.tar as tape files)",
    compiler_or_interpreter="a VAX-11/780 -- emulated by SIMH vax780 (docker world prometheus-fossil-simh)",
    dependencies=["SIMH vax780 (Debian simh 3.8.1)", "a .tap image built from the tape files (Techne mktape, record sizes per FORMAT/notes)", "an RP06 disk image", "expect (console automation)"],
    recovered_status="NOT_RECOVERED_SOURCE_IS_ORIGINAL",
    environment={"runner": "docker", "image": "prometheus-fossil-simh:bookworm"},
)
spec("bsd-4.2-distribution-tape-1983",
    canonical_name="4.2BSD distribution tape (August 1983): stand, miniroot, root dump, usr.tar -- the bootable system whose TCP is bsd-tcp-4.2-1983",
    aliases=["4.2BSD tape", "4.2 BSD VAX"],
    lineage="The 4.2BSD release as shipped to VAX sites: the standalone boot programs, the miniroot filesystem, a dump of the root filesystem (with /vmunix) and the /usr tree. Preserved so that the kernel in bsd-tcp-4.2-1983 can be BOOTED under an emulated VAX-11/780 rather than only read. Transcribed from the physical 9-track tape into the TUHS archive.",
    era="1983",
    version="4.2BSD (Aug 1983); TUHS Archive/Distributions/UCB/4BSD/4.2BSD (stand, miniroot, rootdump, usr.tar; FORMAT)",
    source_origin=tape("4.2BSD"),
    source_identity={"archive": "tuhs.org/Archive/Distributions/UCB/4BSD/4.2BSD", "tape_files": "1 stand (199x512), 2 miniroot (205x10240), 3 rootdump (383x10240), 5 usr.tar (2148x10240)"},
    entry_points=["SIMH: boot ts0 -> standalone boot -> copy miniroot to hp(0,1) -> boot hp(0,1)vmunix -> newfs/restore root -> boot hp(0,0)vmunix"],
    example={"command": "python -m techne.fossils.harvest run bsd-4.2-distribution-tape-1983", "input": "the four tape files assembled into a .tap image", "output": "a booted 4.2BSD kernel on an emulated VAX-11/780 (stage of the install reached is the receipt)"},
    upstream_docs=["Installing and Operating 4.2BSD on the VAX (Leffler, Joy, Fabry; 1983)", "TUHS FORMAT file"],
    human_capability_summary={"built_to": "install a complete 4.2BSD system on a VAX from one magnetic tape", "pressure": "1983 hardware: a 9-track drive, an RP06 disk, a console; and the Internet that this release's TCP was about to collapse", "success_means": "the kernel boots multi-user from disk and its TCP answers on lo0"},
    known_human_problem_solved="distribution and installation of a research operating system",
    human_environmental_pressure="1983 media and hardware; the network stack shipped here had no congestion control",
    human_failure_condition="a bad tape or disk geometry stops the install; historically, its TCP collapsed under congestion",
    behavioral_entry_point="boot the installed disk under SIMH; netstat -s on the guest before/after a loopback transfer",
    acquisition_tags=["batch06", "phase1", "unlock", "depth:tcp", "historical_world"],
    lineage_relations=[{"relation": "shares_ancestor_with", "to": "bsd-tcp-4.2-1983", "note": "this tape CONTAINS the kernel whose netinet/tcp_* files are preserved as that specimen"}],
    **_tape_common)
spec("bsd-4.3-distribution-tape-1986",
    canonical_name="4.3BSD distribution tape (June 1986): stand, miniroot, root dump, usr.tar -- the last pre-slow-start BSD TCP, bootable",
    aliases=["4.3BSD tape", "4.3 BSD VAX"],
    lineage="Plain 4.3BSD (1986) predates Jacobson's slow start / congestion avoidance (which arrived in 4.3BSD-Tahoe, 1988): its TCP is the 4.2 design with two years of fixes -- a BEFORE point for the congestion lineage that, unlike the Tahoe tape (usr.tar cut short in the archive), is COMPLETE and installable. The classic SIMH-installable BSD.",
    era="1986",
    version="4.3BSD (Jun 1986); TUHS Archive/Distributions/UCB/4BSD/4.3BSD (stand, miniroot, rootdump, usr.tar; FORMAT)",
    source_origin=tape("4.3BSD"),
    source_identity={"archive": "tuhs.org/Archive/Distributions/UCB/4BSD/4.3BSD", "tape_files": "1 stand, 2 miniroot, 3 rootdump, 4 usr.tar"},
    entry_points=["SIMH: boot ts0 -> : ts(0,1)copy -> : hp(0,1)vmunix -> newfs / restore -> boot hp(0,0)vmunix"],
    example={"command": "python -m techne.fossils.harvest run bsd-4.3-distribution-tape-1986", "input": "the four tape files assembled into a .tap image", "output": "a booted 4.3BSD on an emulated VAX-11/780; netstat -s TCP counters around a loopback transfer"},
    upstream_docs=["Installing and Operating 4.3BSD on the VAX (Karels, Leffler, McKusick, Joy; 1986)", "Jacobson, Congestion Avoidance and Control, 1988 (what this release lacks)"],
    human_capability_summary={"built_to": "install a complete 4.3BSD system on a VAX from one tape", "pressure": "the 1986 congestion collapse happened on THIS release's TCP", "success_means": "boots multi-user; TCP answers; netstat -s shows the retransmission counters"},
    known_human_problem_solved="distribution and installation of 4.3BSD",
    human_environmental_pressure="the Internet of 1986: shared scarce links, loss as the only signal, no congestion window yet",
    human_failure_condition="congestion collapse (historical); install failure (tape/disk)",
    behavioral_entry_point="netstat -s before/after a loopback transfer; a second emulated VAX over a lossy Ethernet relay is the boundary (see record notes)",
    acquisition_tags=["batch06", "phase1", "unlock", "depth:tcp", "historical_world", "known_bad_lineage"],
    lineage_relations=[{"relation": "historical_version_of", "to": "bsd-tcp-4.2-1983", "note": "4.3's TCP = 4.2's design + fixes, still no congestion window"},
                       {"relation": "superseded", "to": "bsd-tcp-4.3-tahoe-1988", "note": "Tahoe added slow start / congestion avoidance"}],
    **_tape_common)
spec("bsd-4.3-reno-distribution-tape-1990",
    canonical_name="4.3BSD-Reno distribution tape (June 1990): stand, miniroot, root dump, usr.tar -- fast retransmit / fast recovery TCP, bootable",
    aliases=["4.3BSD-Reno tape", "Reno VAX"],
    lineage="The bootable system containing the Reno TCP (bsd-tcp-4.3-reno-1990): slow start, congestion avoidance, fast retransmit and fast recovery. With the 4.3BSD tape this makes the congestion-control lineage's BEFORE and AFTER both installable under one emulated VAX-11/780; the Tahoe tape between them is cut short in the archive.",
    era="1990",
    version="4.3BSD-Reno (Jun 1990); TUHS Archive/Distributions/UCB/4BSD/4.3BSD-Reno (stand, miniroot, rootdump, usr.tar; FORMAT)",
    source_origin=tape("4.3BSD-Reno"),
    source_identity={"archive": "tuhs.org/Archive/Distributions/UCB/4BSD/4.3BSD-Reno", "tape_files": "1 stand, 2 miniroot, 3 rootdump, 4 usr.tar"},
    entry_points=["SIMH: boot ts0 -> standalone boot -> copy miniroot -> boot -> newfs / restore -> boot hp(0,0)vmunix"],
    example={"command": "python -m techne.fossils.harvest run bsd-4.3-reno-distribution-tape-1990", "input": "the four tape files assembled into a .tap image", "output": "a booted Reno on an emulated VAX; the same loopback pressure as the 4.3 tape"},
    upstream_docs=["4.3BSD-Reno release notes (CSRG, 1990)", "Fall & Floyd 1996 (Tahoe/Reno/SACK comparison)"],
    human_capability_summary={"built_to": "install 4.3BSD-Reno on a VAX from one tape", "pressure": "high bandwidth-delay paths and isolated losses (the Reno redesign's motive)", "success_means": "boots; TCP recovers from a single loss without draining the pipe"},
    known_human_problem_solved="distribution and installation of 4.3BSD-Reno",
    human_environmental_pressure="isolated loss on long fat pipes",
    human_failure_condition="multiple losses in one window still collapse the window (NewReno/SACK pressure)",
    behavioral_entry_point="the same controlled pressure as the 4.3 tape, so the two kernels' netstat -s counters can be set side by side (interpretation is Nyx's)",
    acquisition_tags=["batch06", "phase1", "unlock", "depth:tcp", "historical_world", "successor"],
    lineage_relations=[{"relation": "shares_ancestor_with", "to": "bsd-tcp-4.3-reno-1990", "note": "this tape CONTAINS that kernel"}],
    **_tape_common)


# ============================ PHASE 2: REAL CONCURRENT FAILURE ================================
spec("go-runtime-deadlock-fixtures-1.22",
    canonical_name="Go runtime deadlock regression fixtures (src/runtime/testdata/testprog/deadlock.go, go1.22.0): SimpleDeadlock, LockedDeadlock, LockedDeadlock2, GoexitDeadlock, InitDeadlock",
    aliases=["testprog deadlock.go", "all goroutines are asleep"],
    lineage="The Go runtime's own regression programs for its deadlock detector (checkdead(): 'fatal error: all goroutines are asleep - deadlock!'), kept since Go 1.x and run by runtime/crash_test.go on every release. Each program is a REAL concurrent deadlock -- goroutines blocked on channels/mutexes with no runnable goroutine left -- preserved as the runtime team wrote it; the runtime is the detector, not the fix. The failing programs are not repaired.",
    domain=["concurrency", "deadlock", "failure", "regression-fixture", "runtime", "go"],
    era="2014- (fixtures; Go 1.22.0 = Feb 2024)",
    version="golang/go tag go1.22.0, files src/runtime/testdata/testprog/{deadlock.go,main.go}",
    source_origin={"artifacts": [{"kind": "url", "url": "https://raw.githubusercontent.com/golang/go/go1.22.0/src/runtime/testdata/testprog/deadlock.go", "filename": "deadlock.go", "extract": False},
                                 {"kind": "url", "url": "https://raw.githubusercontent.com/golang/go/go1.22.0/src/runtime/testdata/testprog/main.go", "filename": "main.go", "extract": False},
                                 {"kind": "url", "url": "https://raw.githubusercontent.com/golang/go/go1.22.0/src/runtime/crash_test.go", "filename": "crash_test.go", "extract": False}]},
    source_type="ORIGINAL_AUTHORITATIVE_RELEASE", source_identity={"repo": "github.com/golang/go", "tag": "go1.22.0", "path": "src/runtime/testdata/testprog"},
    license={"spdx": "BSD-3-Clause", "status": "permissive", "evidence": "Go LICENSE"},
    language=["Go"], build_system="go run (module-less package main)", compiler_or_interpreter="go 1.22 (docker golang:1.22-bookworm)",
    dependencies=["a Go toolchain"],
    entry_points=["go run . SimpleDeadlock | LockedDeadlock | LockedDeadlock2 | GoexitDeadlock ; crash_test.go names the expected output per case"],
    example={"command": "go run . SimpleDeadlock", "input": "the named fixture", "output": "fatal error: all goroutines are asleep - deadlock! + goroutine dump (exit 2); crash_test.go's expectation is the ORACLE"},
    environment={"runner": "docker", "image": "golang:1.22-bookworm"},
    upstream_docs=["src/runtime/crash_test.go (TestSimpleDeadlock etc.)", "Go runtime proc.go checkdead()"],
    human_capability_summary={"built_to": "keep the runtime's deadlock detector honest: each program must still be recognised as a deadlock on every release",
                              "pressure": "concurrent programs that block forever; a runtime that must tell 'everyone is waiting' from 'someone is still working'",
                              "success_means": "the runtime aborts with the deadlock diagnosis instead of hanging silently"},
    known_human_problem_solved="detection of whole-program deadlock in a concurrent runtime",
    human_environmental_pressure="many actors blocking on each other; no external observer",
    human_failure_condition="a hung program that never terminates and never explains why",
    behavioral_entry_point="run each named case; compare the goroutine dump; edit nothing (the fixtures are the fossil)",
    acquisition_tags=["batch06", "phase2", "deadlock", "executes_concurrency", "regression_fixture"],
    lineage_relations=[{"relation": "shares_ancestor_with", "to": "spin-pathfinder-priority-inversion-1997", "note": "a deadlock found by execution + runtime detector vs one found by model checking"}])

spec("valgrind-helgrind-fixtures-3.19",
    canonical_name="Valgrind 3.19.0 helgrind regression fixtures: tc01_simple_race, tc05_simple_race, tc09_bad_unlock, tc13_laog1 (lock-order inversion), tc19_shadowmem -- real pthread programs with their expected detector output",
    aliases=["helgrind tests", "tc01_simple_race.c", "tc13_laog1.c"],
    lineage="Valgrind's thread-error detector Helgrind (Nethercote/Seward, 2007-) ships regression programs that each commit a specific concurrency error -- unsynchronised access (a RACE), unlocking a lock the thread does not hold, acquiring locks in inconsistent order (the classic DEADLOCK precursor, reported via the lock-order acquisition graph) -- together with the .stderr.exp files the detector must reproduce. Preserved as the failing programs plus the expected traces; run under the detector.",
    domain=["concurrency", "race", "deadlock", "lock-order", "failure", "regression-fixture", "pthreads"],
    era="2007- (fixtures; 3.19.0 = 2022)",
    version="valgrind-3.19.0.tar.bz2 (sourceware), helgrind/tests/",
    source_origin={"artifacts": [{"kind": "url", "url": "https://sourceware.org/pub/valgrind/valgrind-3.19.0.tar.bz2", "filename": "valgrind-3.19.0.tar.bz2"}]},
    source_type="ORIGINAL_AUTHORITATIVE_RELEASE", source_identity={"archive": "sourceware.org/pub/valgrind", "file": "valgrind-3.19.0.tar.bz2", "path": "helgrind/tests"},
    license={"spdx": "GPL-2.0", "status": "copyleft", "evidence": "COPYING"},
    language=["C (pthreads)"], build_system="gcc -pthread per fixture; run under the distribution's valgrind --tool=helgrind", compiler_or_interpreter="gcc 12 + valgrind 3.19 (Debian bookworm, apt)",
    dependencies=["valgrind (the detector; Debian's 3.19.0-1 matches the fixture version)", "pthreads"],
    entry_points=["helgrind/tests/tc01_simple_race.c (race), tc05_simple_race.c, tc09_bad_unlock.c, tc13_laog1.c (lock order), tc19_shadowmem.c; *.stderr.exp"],
    example={"command": "gcc -pthread tc13_laog1.c && valgrind --tool=helgrind ./a.out", "input": "the fixture", "output": "Helgrind's report ('Thread #N: lock order ... violated' / 'Possible data race'); compared with the shipped .stderr.exp (the ORACLE, modulo addresses)"},
    environment={"runner": "docker", "image": "prometheus-fossil-c:bookworm"},
    upstream_docs=["Valgrind manual, Helgrind chapter", "helgrind/tests/*.stderr.exp"],
    human_capability_summary={"built_to": "make each class of thread error reproducible so the detector's report for it never regresses",
                              "pressure": "races and lock-order bugs are timing-dependent and invisible in normal runs; a detector must find them from one execution",
                              "success_means": "helgrind reports the planted error in the planted place, matching the expected trace"},
    known_human_problem_solved="detection of data races and lock-order deadlocks in pthread programs",
    human_environmental_pressure="nondeterministic scheduling, shared memory without discipline",
    human_failure_condition="silent corruption (race) or an eventual deadlock (lock order) in production, not in test",
    behavioral_entry_point="run a fixture natively (usually 'works') and under helgrind (the error is reported): the same binary, two observers",
    acquisition_tags=["batch06", "phase2", "race", "deadlock", "executes_concurrency", "regression_fixture"],
    lineage_relations=[{"relation": "shares_ancestor_with", "to": "go-runtime-deadlock-fixtures-1.22", "note": "two runtimes' regression corpora for concurrency failure"}])

spec("glibc-rwlock-writer-starvation-2.36",
    canonical_name="glibc 2.36 pthread_rwlock (nptl/pthread_rwlock_common.c): reader-preferring default and the documented writer STARVATION it permits",
    aliases=["pthread_rwlock_common.c", "PTHREAD_RWLOCK_PREFER_READER_NP", "writer starvation"],
    lineage="POSIX read-write locks as glibc implements them: the default kind PTHREAD_RWLOCK_PREFER_READER_NP lets a continuous stream of readers hold a writer off indefinitely -- documented in pthread_rwlockattr_setkind_np(3) ('may result in writer starvation') and in glibc bug reports; the alternative kind PREFER_WRITER_NONRECURSIVE_NP is the corrected behaviour the caller must opt into. Preserved: the 2.36 source of the lock (the machinery), and a harness that drives Debian's glibc (the same version) under reader pressure with both kinds. The lock is not modified.",
    domain=["concurrency", "starvation", "fairness", "failure", "readers-writer-lock", "glibc"],
    era="2017- (this rwlock rewrite, Torvald Riegel); glibc 2.36 = 2022",
    version="glibc tag glibc-2.36: nptl/pthread_rwlock_common.c, nptl/pthread_rwlock_wrlock.c (source); Debian bookworm libc6 2.36 (the running library)",
    source_origin={"artifacts": [{"kind": "url", "url": "https://sourceware.org/git/?p=glibc.git;a=blob_plain;f=nptl/pthread_rwlock_common.c;hb=glibc-2.36", "filename": "pthread_rwlock_common.c", "extract": False},
                                 {"kind": "url", "url": "https://sourceware.org/git/?p=glibc.git;a=blob_plain;f=nptl/pthread_rwlock_wrlock.c;hb=glibc-2.36", "filename": "pthread_rwlock_wrlock.c", "extract": False},
                                 {"kind": "url", "url": "https://sourceware.org/git/?p=glibc.git;a=blob_plain;f=nptl/pthread_rwlock_rdlock.c;hb=glibc-2.36", "filename": "pthread_rwlock_rdlock.c", "extract": False}]},
    source_type="ORIGINAL_AUTHORITATIVE_RELEASE", source_identity={"repo": "sourceware.org/git/glibc.git", "tag": "glibc-2.36", "path": "nptl/"},
    license={"spdx": "LGPL-2.1-or-later", "status": "copyleft (library)", "evidence": "file headers"},
    language=["C"], build_system="none (the running glibc is Debian's 2.36; the source is preserved to read)", compiler_or_interpreter="gcc 12 + glibc 2.36 (docker bookworm)",
    dependencies=["glibc 2.36 (system)", "pthreads"],
    entry_points=["pthread_rwlock_rdlock/wrlock with PTHREAD_RWLOCK_PREFER_READER_NP (default) vs PREFER_WRITER_NONRECURSIVE_NP; harness/starve.c"],
    example={"command": "gcc -O2 -pthread starve.c; ./a.out reader 2; ./a.out writer 2", "input": "8 readers re-acquiring continuously for 2 s; 1 writer trying", "output": "writer acquisitions per second under each kind (the STARVATION shows as ~0 under reader preference)"},
    environment={"runner": "docker", "image": "prometheus-fossil-c:bookworm"},
    upstream_docs=["pthread_rwlockattr_setkind_np(3): 'Setting the value read-write lock kind to PTHREAD_RWLOCK_PREFER_READER_NP ... may result in writer starvation'", "glibc nptl/pthread_rwlock_common.c header comment (the algorithm)"],
    human_capability_summary={"built_to": "let many readers share a structure while excluding writers, with a policy choice the standard leaves to the implementation",
                              "pressure": "continuous reader arrivals; a writer whose progress is not guaranteed by the default policy",
                              "success_means": "readers proceed concurrently; a writer eventually acquires -- 'eventually' being the documented weakness"},
    known_human_problem_solved="readers-writer mutual exclusion",
    human_environmental_pressure="asymmetric contention (many readers, few writers)",
    human_failure_condition="writer starvation: updates never land while readers keep arriving",
    behavioral_entry_point="vary reader count and hold time; switch the kind attribute; measure writer acquisitions",
    acquisition_tags=["batch06", "phase2", "starvation", "executes_concurrency", "documented_pathology"],
    lineage_relations=[{"relation": "shares_ancestor_with", "to": "concurrencykit-0.7.2", "note": "ck_rwlock / ck_brlock are rival readers-writer designs with different fairness"}])


# ============================ PHASE 3: DISTRIBUTED SURVIVAL MACHINERY =========================
spec("dmtcp-3.1.2",
    canonical_name="DMTCP 3.1.2 -- Distributed MultiThreaded CheckPointing: transparent user-space checkpoint/restart of unmodified Linux processes (Cooperman, Ansel, Arya et al.)",
    aliases=["dmtcp", "dmtcp_launch", "dmtcp_restart"],
    lineage="Checkpoint/restart as a SURVIVAL mechanism: a coordinator signals every process in a computation; each writes its full memory image and reopens its files/sockets on restart, with no kernel module and no source change (the successor of BLCR-style and Condor-style checkpointing; used on HPC clusters). Crash-only assumption: the process may die at any instant after a checkpoint and continue from it.",
    domain=["distributed-systems", "checkpoint-restart", "fault-tolerance", "recovery", "hpc"],
    era="2007-",
    version="v3.1.2 (2024)",
    source_origin={"artifacts": [{"kind": "url", "url": "https://github.com/dmtcp/dmtcp/archive/refs/tags/v3.1.2.tar.gz", "filename": "dmtcp-3.1.2.tar.gz"}]},
    source_type="ORIGINAL_AUTHORITATIVE_RELEASE", source_identity={"repo": "github.com/dmtcp/dmtcp", "tag": "v3.1.2"},
    license={"spdx": "LGPL-3.0-or-later", "status": "copyleft (library)", "evidence": "COPYING"},
    language=["C++", "C"], build_system="./configure && make", compiler_or_interpreter="g++ 12 (docker bookworm)",
    dependencies=["a C++ compiler; LD_PRELOAD-able target"],
    entry_points=["dmtcp_coordinator; dmtcp_launch <prog>; dmtcp_command -c (checkpoint) -q (quit); dmtcp_restart ckpt_*.dmtcp"],
    example={"command": "dmtcp_launch ./counter & ...; dmtcp_command -c; kill the process; dmtcp_restart ckpt_counter_*.dmtcp", "input": "a counting program", "output": "the count resumes from the checkpointed value, not from zero (the ORACLE)"},
    environment={"runner": "docker", "image": "prometheus-fossil-c:bookworm"},
    upstream_docs=["Ansel, Arya, Cooperman, DMTCP: Transparent Checkpointing for Cluster Computations and the Desktop, IPDPS 2009"],
    human_capability_summary={"built_to": "let a long computation survive the death of its process or node by saving and restoring its entire state, without changing the program",
                              "pressure": "node failure, preemption, job time limits on shared clusters",
                              "success_means": "the restarted process continues exactly where the checkpoint left it"},
    known_human_problem_solved="fault tolerance for long-running computations",
    human_environmental_pressure="partial failure, time-limited resources",
    human_failure_condition="hours of computation lost at a crash; or a restart that silently diverges",
    behavioral_entry_point="checkpoint at count N, kill, restart: the first printed count after restart is the observation",
    acquisition_tags=["batch06", "phase3", "checkpoint_restart", "crash_only"],
    lineage_relations=[])

spec("hashicorp-memberlist-0.5.4",
    canonical_name="hashicorp/memberlist 0.5.4 -- SWIM-style gossip membership and failure detection (the machinery under Consul, Nomad, Serf)",
    aliases=["memberlist", "SWIM"],
    lineage="Das, Gupta, Motivala's SWIM (2002): scalable weakly-consistent membership by randomized probing (ping, ping-req through k peers, suspect, dead) with gossip dissemination -- the asynchronous, timeout-based failure detector that Serf (2013), Consul and Nomad run on. Lifeguard extensions (2018). Distinct assumptions from Raft: no leader, no log, eventual membership agreement, suspicion timeouts instead of quorum.",
    domain=["distributed-systems", "failure-detector", "gossip", "membership", "heartbeat-timeout"],
    era="2002 (SWIM); 2013- (memberlist)",
    version="v0.5.4 (2024)",
    source_origin={"artifacts": [{"kind": "url", "url": "https://github.com/hashicorp/memberlist/archive/refs/tags/v0.5.4.tar.gz", "filename": "memberlist-0.5.4.tar.gz"}]},
    source_type="ORIGINAL_AUTHORITATIVE_RELEASE", source_identity={"repo": "github.com/hashicorp/memberlist", "tag": "v0.5.4"},
    license={"spdx": "MPL-2.0", "status": "weak copyleft", "evidence": "LICENSE"},
    language=["Go"], build_system="go test", compiler_or_interpreter="go 1.22 (docker golang:1.22-bookworm; modules fetched at run time, recorded)",
    dependencies=["Go modules (go.sum pinned in the tree)"],
    entry_points=["memberlist.Create(config); Join; the probe loop (state.go: probeNode, suspect, dead); go test -run 'TestMemberlist_(Probe|Suspect|Gossip)'"],
    example={"command": "go test -run 'TestMemberlist_ProbeNode|TestMemberlist_SuspectNode|TestMemberlist_Gossip' -v", "input": "in-process members over loopback with deliberately unreachable peers", "output": "the suspect -> dead transitions the tests assert (the ORACLE)"},
    environment={"runner": "docker", "image": "golang:1.22-bookworm"},
    upstream_docs=["Das, Gupta, Motivala, SWIM: Scalable Weakly-consistent Infection-style Process Group Membership Protocol, DSN 2002", "Dadgar, Phanishayee, Lifeguard: Local Health Awareness for More Accurate Failure Detection, 2018"],
    human_capability_summary={"built_to": "let every node in a cluster learn who is alive and who has died, without a coordinator, tolerating message loss and slow nodes",
                              "pressure": "asynchronous network: lost probes, slow peers, partitions; false positives cost as much as misses",
                              "success_means": "a dead node is declared dead within the suspicion timeout; a slow-but-alive node is refuted via indirect probes"},
    known_human_problem_solved="scalable failure detection and membership",
    human_environmental_pressure="message loss, asynchrony, scale",
    human_failure_condition="a partition splits membership; a live node is wrongly declared dead and evicted",
    behavioral_entry_point="the tests' unreachable peers and timeouts; shrink ProbeTimeout / SuspicionMult and watch false positives",
    acquisition_tags=["batch06", "phase3", "failure_detector", "asynchronous", "timeout_based"],
    lineage_relations=[{"relation": "algorithm_from", "to": "Das, Gupta, Motivala 2002 (SWIM)", "note": ""},
                       {"relation": "shares_ancestor_with", "to": "willemt-raft", "note": "two answers to 'who is alive': gossip suspicion vs leader heartbeats"}])

spec("redlock-py-redis-2014",
    canonical_name="Redlock (antirez, 2014) as redlock-py, with Debian's redis-server as the lock store -- a lease-based distributed mutex, and the design Kleppmann's 2016 analysis argued is unsafe for correctness-critical use",
    aliases=["Redlock", "redlock-py", "distributed lock"],
    lineage="A LEASE-based distributed mutex: acquire a key with a TTL on a majority of N independent Redis instances within a validity window; release by a check-and-delete script. Proposed by Antirez (redis.io/topics/distlock, 2014); criticised by Martin Kleppmann ('How to do distributed locking', 2016) for depending on bounded clock drift and process pauses, with Antirez's reply ('Is Redlock safe?'). Preserved as a runnable lease mechanism AND as a documented contested design (Phase 9: incorrect timing assumption).",
    domain=["distributed-systems", "distributed-mutex", "lease", "timeout-based", "contested-design"],
    era="2014-",
    version="github.com/SPSCommerce/redlock-py master as of 2026-09-13 (commit in hashes); redis-server 7.0 (Debian bookworm) at run time",
    source_origin={"artifacts": [{"kind": "git", "url": "https://github.com/SPSCommerce/redlock-py", "commit": "HEAD"}]},
    source_type="FAITHFUL_PORT", source_identity={"repo": "github.com/SPSCommerce/redlock-py", "algorithm": "redis.io/docs/manual/patterns/distributed-locks"},
    license={"spdx": "MIT", "status": "permissive", "evidence": "LICENSE"},
    language=["Python", "Lua (release script)"], build_system="pip install . + apt redis-server", compiler_or_interpreter="python 3.11 + redis 7 (docker python:3.11-slim with apt redis-server)",
    dependencies=["redis-py", "one or more redis-server instances"],
    entry_points=["Redlock([{host,port}...]).lock(resource, ttl_ms) -> Lock(validity, resource, key) | False; unlock(lock)"],
    example={"command": "three redis instances on loopback; two clients contend for one resource", "input": "contending acquirers, a TTL", "output": "exactly one holder at a time; the second acquires only after release or TTL expiry (the ORACLE); the lease's validity window printed"},
    environment={"runner": "docker", "image": "python:3.11-slim"},
    upstream_docs=["Sanfilippo, Distributed locks with Redis (Redlock), redis.io 2014", "Kleppmann, How to do distributed locking, 2016-02-08", "Sanfilippo, Is Redlock safe?, 2016-02-09"],
    human_capability_summary={"built_to": "grant one client at a time exclusive access to a resource across machines, with a lease so a crashed holder cannot block forever",
                              "pressure": "crashes of holders, network delay, clock drift, process pauses (GC) -- the last two are exactly the contested assumptions",
                              "success_means": "mutual exclusion while the lease is valid; liveness after a holder dies"},
    known_human_problem_solved="distributed mutual exclusion with liveness",
    human_environmental_pressure="partial failure, unbounded delay, unsynchronised clocks",
    human_failure_condition="two holders at once after a pause or clock jump (Kleppmann's scenario); or permanent blocking without a lease",
    behavioral_entry_point="shorten the TTL below the holder's work time and observe the second client acquire while the first still believes it holds the lock",
    acquisition_tags=["batch06", "phase3", "phase9", "lease", "distributed_mutex", "contested_design"],
    lineage_relations=[{"relation": "shares_ancestor_with", "to": "willemt-raft", "note": "lease-based exclusion vs consensus-based"}])

spec("cocagne-plain-paxos",
    canonical_name="Plain Paxos (Tom Cocagne) -- the essential Paxos roles (Proposer, Acceptor, Learner) and a practical variant with heartbeats and leadership, in Python, with its unit tests",
    aliases=["plain paxos", "essential paxos", "cocagne/paxos"],
    lineage="Lamport's Paxos (1989/1998) -- quorum-based, asynchronous, single-decree consensus -- written as small readable classes (essential.py) plus a 'practical' layer (heartbeat-driven leader acquisition, message retransmission, durable state) and a 'functional' variant, each with tests. NOT Raft: no log, no explicit leader term, safety from quorum intersection alone. Widely read as the reference Python Paxos (the Java twin lives in src/).",
    domain=["distributed-systems", "consensus", "quorum", "leader-election", "heartbeat-timeout"],
    era="1989 (algorithm); 2012- (this code)",
    version="github.com/cocagne/paxos master as of 2026-09-13 (commit in hashes)",
    source_origin={"artifacts": [{"kind": "git", "url": "https://github.com/cocagne/paxos", "commit": "HEAD"}]},
    source_type="PSEUDOCODE_PLUS_REFERENCE_IMPL", source_identity={"repo": "github.com/cocagne/paxos"},
    license={"spdx": "MIT", "status": "permissive", "evidence": "LICENSE"},
    language=["Python", "Java"], build_system="none (python -m unittest discover test)", compiler_or_interpreter="python 3.11 (docker python:3.11-slim); tests written for Python 2/3",
    dependencies=["none"],
    entry_points=["paxos/essential.py (Proposer/Acceptor/Learner), paxos/practical.py (Node, heartbeat leader), paxos/functional.py; test/test_essential.py etc."],
    example={"command": "python -m unittest discover -s test -p 'test_*.py' -v", "input": "the shipped message-passing tests (prepare/promise/accept/accepted, contention, leader loss)", "output": "the assertions (the ORACLE)"},
    environment={"runner": "docker", "image": "python:3.11-slim"},
    upstream_docs=["Lamport, Paxos Made Simple, 2001", "README.md (in the tree)"],
    human_capability_summary={"built_to": "let a majority of unreliable nodes agree on one value despite crashes and message loss, and keep agreeing when a leader dies",
                              "pressure": "asynchrony, crash failures, duelling proposers (livelock is Paxos's known liveness hazard, which the practical layer's leader heartbeats exist to suppress)",
                              "success_means": "no two learners learn different values; a value is learned once a quorum is available"},
    known_human_problem_solved="fault-tolerant consensus",
    human_environmental_pressure="partial failure, message loss, competing proposers",
    human_failure_condition="duelling proposers never decide (liveness), or -- if the quorum rule is broken -- two values decided (safety)",
    behavioral_entry_point="the tests' contention cases; drop acceptor replies and watch proposal numbers climb",
    acquisition_tags=["batch06", "phase3", "consensus", "quorum_based", "leader_election"],
    lineage_relations=[{"relation": "shares_ancestor_with", "to": "willemt-raft", "note": "Raft (2014) is a redesign of Paxos for understandability; this is the ancestor family"}])


# ============================ PHASE 4: ADAPTIVE CONTROL =======================================
spec("pid-autotune-hirschmann",
    canonical_name="pid-autotune (Hirschmann) -- Astrom-Hagglund relay-feedback autotuner with Ziegler-Nichols / Tyreus-Luyben / Pessen rules, on a simulated brewing kettle",
    aliases=["pid-autotune", "relay autotuner", "PIDAutotune"],
    lineage="Astrom & Hagglund's relay auto-tuning (Automatica 1984): put the loop under a relay, measure the induced limit cycle's amplitude and period (ultimate gain and period), then compute PID gains by a tuning rule -- the mechanism inside industrial PID controllers' 'autotune' buttons. This implementation (2016-) drives a first-order thermal kettle model (volume, heater power, ambient loss) and prints the gains each rule yields; used by home-brewing controllers (CraftBeerPi lineage).",
    domain=["control", "adaptive", "self-tuning", "relay-feedback", "PID", "small-mechanism"],
    era="1984 (method); 2016- (code)",
    version="github.com/hirschmann/pid-autotune master as of 2026-09-13 (commit in hashes)",
    source_origin={"artifacts": [{"kind": "git", "url": "https://github.com/hirschmann/pid-autotune", "commit": "HEAD"}]},
    source_type="PSEUDOCODE_PLUS_REFERENCE_IMPL", source_identity={"repo": "github.com/hirschmann/pid-autotune"},
    license={"spdx": "MIT", "status": "permissive", "evidence": "LICENSE.md"},
    language=["Python"], build_system="none", compiler_or_interpreter="python 3.11 (docker python:3.11-slim; matplotlib only if plotting)",
    dependencies=["none for the autotune path (matplotlib for --plot only)"],
    entry_points=["autotune.py PIDAutotune(setpoint, out_step, sampletime, lookback, ...).run(input); get_pid_parameters(rule); sim.py autotune <args>"],
    example={"command": "python sim.py autotune --volume 40 ... ; python sim.py autotune --volume 10 ...", "input": "two different kettles (plants)", "output": "different Kp/Ki/Kd per rule for each plant: the CHANGING PLANT -> ADAPTATION -> ALTERED PARAMETERS chain"},
    environment={"runner": "docker", "image": "python:3.11-slim"},
    upstream_docs=["Astrom & Hagglund, Automatic tuning of simple regulators with specifications on phase and amplitude margins, Automatica 20(5), 1984", "README.md (in the tree)"],
    human_capability_summary={"built_to": "let a controller find its own gains from the plant it is attached to, by provoking a controlled oscillation and measuring it",
                              "pressure": "unknown plant dynamics (kettle size, heater power), a user who cannot hand-tune",
                              "success_means": "the measured limit cycle yields gains that regulate the plant; a different plant yields different gains"},
    known_human_problem_solved="PID controller auto-tuning",
    human_environmental_pressure="unknown/varying plant, noisy temperature sensor, slow thermal dynamics",
    human_failure_condition="no limit cycle detected (tuning fails) or gains that oscillate the real plant",
    behavioral_entry_point="change --volume / --heater-power / --ambient-temp and compare the tuned gains and the limit-cycle period",
    acquisition_tags=["batch06", "phase4", "adaptive", "self_tuning", "small_mechanism"],
    lineage_relations=[{"relation": "algorithm_from", "to": "Astrom & Hagglund 1984", "note": ""},
                       {"relation": "shares_ancestor_with", "to": "arduino-pid", "note": "the PID this tunes; the vault's fixed-gain PID beside a gain-finding mechanism"}])

spec("indirect-self-tuning-regulator-liaosteve",
    canonical_name="Indirect self-tuning regulator (Astrom & Wittenmark, Adaptive Control ch. 3): RLS with forgetting factor estimates the plant online, pole-placement (R,S,T) recomputed every step -- a MATLAB implementation, run under Octave",
    aliases=["indirect STR", "self-tuning regulator", "RLS + pole placement"],
    lineage="The self-tuning regulator (Astrom & Wittenmark 1973; textbook Adaptive Control 1989/1995, Example 3.5-style: model-following with zero cancellation): a recursive-least-squares estimator with forgetting tracks the plant's a1,a2,b0,b1; the controller polynomials R,S,T are re-derived from the estimates each sample so the closed loop follows the reference model Am/Bm. This is a student's faithful implementation of the textbook algorithm (MATLAB, 2020) with the true plant's parameters drawn as reference lines -- the ORACLE the estimates converge to (a1=-1.6065, a2=0.6065, b0=0.1065, b1=0.0902).",
    domain=["control", "adaptive", "self-tuning-regulator", "recursive-least-squares", "pole-placement"],
    era="1973 (algorithm); 2020 (code)",
    version="github.com/LiaoSteve/Adaptive-control---Indirect-Self-Tuning-Regulator master (commit in hashes): main_code.m, rls_forgetting.m",
    source_origin={"artifacts": [{"kind": "git", "url": "https://github.com/LiaoSteve/Adaptive-control---Indirect-Self-Tuning-Regulator", "commit": "HEAD"}]},
    source_type="PSEUDOCODE_PLUS_REFERENCE_IMPL", source_identity={"repo": "github.com/LiaoSteve/Adaptive-control---Indirect-Self-Tuning-Regulator", "textbook": "Astrom & Wittenmark, Adaptive Control, 2nd ed., ch. 3"},
    license={"spdx": "MIT", "status": "permissive", "evidence": "LICENSE"},
    language=["MATLAB"], build_system="none (interpreted)", compiler_or_interpreter="GNU Octave 7.3 (docker prometheus-fossil-octave:bookworm); plot calls shadowed by harness no-ops",
    dependencies=["Octave; no toolboxes"],
    entry_points=["main_code.m (the loop: RLS update -> R,S,T -> control law -> plant step); rls_forgetting.m"],
    example={"command": "octave --no-gui -p $HARNESS main_code.m; then print theta(:,end)", "input": "square-wave reference uc, unknown plant simulated inside the script", "output": "theta converging to the true plant (the dashed reference lines in the script); u and y traces"},
    environment={"runner": "docker", "image": "prometheus-fossil-octave:bookworm"},
    upstream_docs=["Astrom & Wittenmark, On self-tuning regulators, Automatica 1973", "Astrom & Wittenmark, Adaptive Control, Addison-Wesley 1995, ch. 3"],
    human_capability_summary={"built_to": "control a plant whose parameters are unknown by identifying them online and redesigning the controller at every step",
                              "pressure": "unknown/drifting plant, the need for the closed loop to match a specified reference model",
                              "success_means": "the estimated parameters converge to the plant's and the output follows the reference model"},
    known_human_problem_solved="adaptive pole-placement control of an unknown plant",
    human_environmental_pressure="parameter uncertainty; excitation must be rich enough for identification",
    human_failure_condition="estimator divergence or controller bursting when excitation vanishes (the known STR hazard)",
    behavioral_entry_point="the forgetting factor lambda (0.8 in the script) and the initial covariance p: the adaptation speed knob",
    acquisition_tags=["batch06", "phase4", "adaptive", "self_tuning_regulator", "octave"],
    lineage_relations=[{"relation": "algorithm_from", "to": "Astrom & Wittenmark 1973", "note": ""},
                       {"relation": "shares_ancestor_with", "to": "padasip-1.2.2", "note": "RLS identification is the estimator inside this controller"}])

spec("l1-adaptive-control-basics-xkhainguyen",
    canonical_name="L1 adaptive control basic simulation (Hovakimyan & Cao's L1 architecture on a first-order plant with unknown parameters), MATLAB, run under Octave",
    aliases=["L1AC", "L1 adaptive control"],
    lineage="L1 adaptive control (Cao & Hovakimyan, 2006-; book 2010): a state predictor, a fast projection-based adaptation law, and a low-pass filter on the control channel that decouples adaptation rate from robustness -- the adaptive architecture flown on NASA's AirSTAR and in quadrotor augmentation. This is a minimal simulation of the architecture (MATLAB, 2022) whose author later published L1 augmentation for geometric quadrotor control.",
    domain=["control", "adaptive", "L1", "state-predictor", "robustness"],
    era="2006 (architecture); 2022 (code)",
    version="github.com/xkhainguyen/L1AC-Basics main (commit in hashes): MainL1_ODE1_v1.m, MainL1_ODE1_v2.m",
    source_origin={"artifacts": [{"kind": "git", "url": "https://github.com/xkhainguyen/L1AC-Basics", "commit": "HEAD"}]},
    source_type="PSEUDOCODE_PLUS_REFERENCE_IMPL", source_identity={"repo": "github.com/xkhainguyen/L1AC-Basics", "theory": "Hovakimyan & Cao, L1 Adaptive Control Theory, SIAM 2010"},
    license={"spdx": "MIT", "status": "permissive", "evidence": "LICENSE"},
    language=["MATLAB"], build_system="none (interpreted)", compiler_or_interpreter="GNU Octave 7.3 (docker prometheus-fossil-octave:bookworm); plot calls shadowed",
    dependencies=["Octave"],
    entry_points=["MainL1_ODE1_v1.m (predictor + adaptation + filter loop)"],
    example={"command": "octave --no-gui -p $HARNESS MainL1_ODE1_v1.m; print the final tracking error and adapted parameter", "input": "unknown plant parameter, reference signal", "output": "the adapted estimate and the tracking error trace"},
    environment={"runner": "docker", "image": "prometheus-fossil-octave:bookworm"},
    upstream_docs=["Hovakimyan & Cao, L1 Adaptive Control Theory: Guaranteed Robustness with Fast Adaptation, SIAM 2010"],
    human_capability_summary={"built_to": "adapt fast to an unknown plant without the high-gain fragility of classical MRAC, by filtering the adaptive control signal",
                              "pressure": "unknown/time-varying plant with robustness requirements (flight control)",
                              "success_means": "the plant tracks the reference; the adaptive estimate moves; the filtered control stays smooth"},
    known_human_problem_solved="fast, robust adaptive control",
    human_environmental_pressure="parametric uncertainty under a hard robustness margin",
    human_failure_condition="loss of robustness under fast adaptation (the MRAC failure L1 was designed against; Rohrs 1985)",
    behavioral_entry_point="the adaptation gain Gamma and the filter bandwidth in the script",
    acquisition_tags=["batch06", "phase4", "adaptive", "L1", "octave"],
    lineage_relations=[{"relation": "algorithm_from", "to": "Cao & Hovakimyan 2006", "note": ""}])

# ============================ PHASE 5: INFERENCE GAPS =========================================
spec("libdai-mooij",
    canonical_name="libDAI (0.3 line, 2012 mirror) -- a C++ library of approximate inference on factor graphs: (loopy) belief propagation, junction tree, mean field, TreeEP, Gibbs, and more (Joris Mooij)",
    aliases=["libDAI"],
    lineage="Pearl's belief propagation (1982/1988) and its loopy generalisation, exact junction-tree inference, and a dozen approximate methods, in one reference library (JMLR MLOSS 2010) with the standard examples (sprinkler network) and unit tests. The canonical open BELIEF-PROPAGATION implementation; the vault's ldpc-codes does BP only for decoding.",
    domain=["inference", "belief-propagation", "factor-graphs", "graphical-models", "approximate-inference"],
    era="2006-2015 (0.3.2 = 2015)",
    version="github.com/dbtsai/libDAI master (a 2012 mirror of the libdai.org 0.3 line; exact version from ChangeLog in the tree; commit in hashes)",
    source_origin={"artifacts": [{"kind": "git", "url": "https://github.com/dbtsai/libDAI", "commit": "HEAD"}]},
    source_type="HISTORICAL_ARCHIVE_MIRROR", source_identity={"original": "libdai.org (Joris Mooij), 0.3 line", "mirror": "github.com/dbtsai/libDAI"},
    license={"spdx": "BSD-2-Clause", "status": "permissive (relicensed from GPL at 0.3)", "evidence": "COPYING / README"},
    language=["C++"], build_system="make (Makefile.LINUX -> Makefile.conf; boost, gmp)", compiler_or_interpreter="g++ 12 (docker bookworm) with libboost-dev, libgmp-dev, libgmpxx (apt at run time, recorded)",
    dependencies=["boost (program_options, test)", "gmp/gmpxx"],
    entry_points=["examples/example_sprinkler.cpp (exact + BP marginals on the sprinkler network); tests/testdai; examples/example.cpp with a .fg factor graph"],
    example={"command": "make examples; ./examples/example_sprinkler", "input": "the sprinkler Bayesian network", "output": "P(Sprinkler|WetGrass) etc. by exact inference and by BP -- BP equals exact on this tree (the ORACLE)"},
    environment={"runner": "docker", "image": "prometheus-fossil-c:bookworm"},
    upstream_docs=["Mooij, libDAI: A Free and Open Source C++ Library for Discrete Approximate Inference in Graphical Models, JMLR 11, 2010", "Pearl, Probabilistic Reasoning in Intelligent Systems, 1988"],
    human_capability_summary={"built_to": "compute marginals and MAP states on graphical models by passing messages along factor-graph edges, exactly on trees and approximately on loopy graphs",
                              "pressure": "exact inference is exponential on loopy graphs; loopy BP may not converge",
                              "success_means": "on a tree, BP marginals equal the exact ones; on loopy graphs, convergence and accuracy are reported"},
    known_human_problem_solved="probabilistic inference on graphical models",
    human_environmental_pressure="combinatorial state spaces, loops",
    human_failure_condition="loopy BP oscillates or converges to wrong marginals",
    behavioral_entry_point="run BP on a loopy .fg (tests/ ships several) with different damping/update schedules and record convergence",
    acquisition_tags=["batch06", "phase5", "belief_propagation", "inference"],
    lineage_relations=[{"relation": "algorithm_from", "to": "Pearl 1982/1988", "note": ""},
                       {"relation": "shares_ancestor_with", "to": "ldpc-codes-neal-2001", "note": "BP as a decoder vs BP as a general inference engine"}])


# ============================ PHASE 7: NEGLECTED COMPUTATIONAL CULTURES =======================
spec("gnu-apl-2.0",
    canonical_name="GNU APL 2.0 -- a free interpreter for the array language APL (ISO 13751), by Juergen Sauermann",
    aliases=["GNU APL", "apl"],
    lineage="APL (Iverson, 1962; 'A Programming Language'): a notation that computes on whole arrays with a dense set of primitive functions and operators, no explicit loops -- the founding array-language culture (ancestor of J, K, kdb+, and of array thinking in NumPy). GNU APL (2013-) is a complete ISO-standard interpreter in C++. The vault's first array language; a genuinely different execution model (rank-polymorphic whole-array operations) from every other specimen.",
    domain=["language", "array-language", "APL", "legacy-culture", "interpreter"],
    era="1962 (APL); 2013- (GNU APL); 2.0 = 2017",
    version="GNU APL 2.0 (ftp.gnu.org/gnu/apl/apl-2.0.tar.gz)",
    source_origin={"artifacts": [{"kind": "url", "url": "https://ftp.gnu.org/gnu/apl/apl-2.0.tar.gz", "filename": "apl-2.0.tar.gz"}]},
    source_type="ORIGINAL_AUTHORITATIVE_RELEASE", source_identity={"archive": "ftp.gnu.org/gnu/apl", "file": "apl-2.0.tar.gz"},
    license={"spdx": "GPL-3.0-or-later", "status": "copyleft", "evidence": "COPYING"},
    language=["C++"], build_system="./configure && make", compiler_or_interpreter="g++ 12 (docker prometheus-fossil-c:bookworm)",
    dependencies=["a C++ compiler; readline optional"],
    entry_points=["src/apl --script (read APL from stdin); primitives + . / rho iota etc."],
    example={"command": "apl --silent --script < table.apl", "input": "sum of 1..100 and a 5x5 outer-product multiplication table", "output": "5050 and the table -- computed with no loops (the ORACLE)"},
    environment={"runner": "docker", "image": "prometheus-fossil-c:bookworm"},
    upstream_docs=["Iverson, A Programming Language, Wiley 1962", "GNU APL info manual"],
    human_capability_summary={"built_to": "express computation as operations on whole arrays in a compact notation, without explicit iteration",
                              "pressure": "the human problem of concise mathematical/array notation; APL's terseness and non-ASCII glyphs are the cost",
                              "success_means": "an array expression yields the same result a looped program would, in one line"},
    known_human_problem_solved="array-oriented computation",
    human_environmental_pressure="notational density; whole-array thinking versus element-at-a-time",
    human_failure_condition="rank/shape errors (LENGTH ERROR, RANK ERROR) when arrays do not conform",
    behavioral_entry_point="reshape (rho) an array to a non-conforming shape and watch the error; vary the outer-product operator's function",
    acquisition_tags=["batch06", "phase7", "culture", "array_language", "outside_queue"],
    lineage_relations=[{"relation": "algorithm_from", "to": "Iverson 1962 (APL)", "note": "the founding array language; ancestor of J/K and of array programming generally"}])


def main():
    from .. import record as R
    for rec in S:
        try:
            old = R.load(rec["specimen_id"])
            for k in ("run_classification", "test_classification", "receipts", "hashes", "acquisition_date",
                      "observability", "nyx_handoff"):
                if old.get(k):
                    rec[k] = old[k]
        except FileNotFoundError:
            pass
        probs = R.validate(rec)
        R.save(rec)
        print("%-40s %s" % (rec["specimen_id"], "ok" if not probs else probs))
    print(len(S), "records")


if __name__ == "__main__":
    main()
