"""Batch 01 of the computational fossil harvest (2026-09-12): the record definitions.

    python -m techne.fossils.batches.batch01          # writes/refreshes record.json for each

Records are context for Nyx, not decomposition. Every specimen here was chosen for lineage
diversity across era, language and problem pressure, subject to being buildable on this
host today (WSL2 Ubuntu 24.04 gcc 13; WinLibs gfortran 15.2 on Windows; docker in WSL for
anything that needs an older or fuller world). What was NOT chosen is not a judgement.
"""
from __future__ import annotations

from .. import record

GP = "https://www.cs.cmu.edu/afs/cs.cmu.edu/usr/avrim/Planning/Graphplan/"
NL = "https://www.netlib.org/minpack/"
MINPACK_FILES = ["readme", "disclaimer", "chkder.f", "dogleg.f", "dpmpar.f", "enorm.f", "fdjac1.f", "fdjac2.f",
                 "hybrd.f", "hybrd1.f", "hybrj.f", "hybrj1.f", "lmder.f", "lmder1.f", "lmdif.f", "lmdif1.f",
                 "lmpar.f", "lmstr.f", "lmstr1.f", "qform.f", "qrfac.f", "qrsolv.f", "r1mpyq.f", "r1updt.f",
                 "rwupdt.f"] + ["ex/file%02d" % i for i in range(1, 24)]

SPECIMENS = [
    record.skeleton("linpackd-netlib-1979",
        canonical_name="LINPACK benchmark, double precision (linpackd) -- Dongarra, Bunch, Moler, Stewart",
        aliases=["linpackd", "LINPACK 100", "linpack benchmark"],
        lineage="LINPACK (1979, Argonne / U New Mexico / Sandia / Michigan): LU factorisation with partial pivoting (DGEFA/DGESL) over the BLAS-1 kernels (DAXPY, DDOT, DSCAL, IDAMAX); the benchmark that defined machine performance for two decades",
        domain=["numerical-linear-algebra", "benchmark", "scientific-computing"], era="1979",
        version="netlib.org/benchmark/linpackd as served 2026-09-12 (file carries its own 'linpack benchmark' revision comments)",
        source_origin={"artifacts": [{"kind": "url", "url": "https://www.netlib.org/benchmark/linpackd", "filename": "linpackd.f", "extract": False}]},
        source_type="HISTORICAL_ARCHIVE_MIRROR",
        source_identity={"archive": "netlib.org (the authors' own distribution channel since 1985)", "path": "benchmark/linpackd"},
        license={"spdx": "public-domain (netlib LINPACK; no licence text in file)", "status": "netlib distribution, no restriction stated", "evidence": "file header"},
        language=["Fortran 77"], build_system="single file, gfortran", compiler_or_interpreter="gfortran (WinLibs GCC 15.2, Windows native)",
        dependencies=[], entry_points=["PROGRAM (main) in linpackd.f: factor and solve a 100x100 system, report residual and MFLOPS"],
        example={"command": "gfortran -O2 -std=legacy -o linpackd linpackd.f && ./linpackd", "input": "none (self-generating matrix)", "output": "norm. resid / resid / machep / x(1) / x(n) lines then the timing table"},
        environment={"runner": "native Windows, WinLibs gfortran 15.2"},
        upstream_docs=["Dongarra, Bunch, Moler, Stewart, LINPACK Users' Guide, SIAM 1979", "netlib.org/benchmark/"],
        human_capability_summary={"built_to": "solve dense systems of linear equations Ax=b reliably on the machines of the late 1970s, and (as the benchmark) measure how fast a machine does it",
                                  "pressure": "numerical stability under floating-point round-off (partial pivoting), and portability across vendors' Fortran compilers",
                                  "success_means": "a small normalised residual on the solved system; for the benchmark, MFLOPS on the 100x100 problem"},
        known_human_problem_solved="dense linear solve with pivoting; the LINPACK MFLOPS number"),
    record.skeleton("minpack-netlib-1980",
        canonical_name="MINPACK-1 (double precision) -- More, Garbow, Hillstrom, Argonne",
        aliases=["minpack", "MINPACK-1", "lmder", "hybrd"],
        lineage="MINPACK (1980, Argonne National Laboratory): Levenberg-Marquardt least squares (LMDER/LMDIF/LMSTR) and Powell hybrid dogleg for nonlinear equations (HYBRD/HYBRJ), with CHKDER Jacobian checking; ancestor of scipy.optimize.leastsq/fsolve",
        domain=["nonlinear-least-squares", "nonlinear-equations", "optimization", "scientific-computing"], era="1980",
        version="netlib.org/minpack as served 2026-09-12 (25 routine files + 23 ex/ test files)",
        source_origin={"artifacts": [{"kind": "url", "url": NL + f, "filename": f, "extract": False} for f in MINPACK_FILES]},
        source_type="HISTORICAL_ARCHIVE_MIRROR",
        source_identity={"archive": "netlib.org/minpack (Argonne's distribution)", "files": len(MINPACK_FILES)},
        license={"spdf": "", "spdx": "Minpack Copyright Notice (1999) University of Chicago -- BSD-like, see disclaimer", "status": "redistribution permitted with notice (netlib disclaimer)", "evidence": "upstream file 'disclaimer'"},
        language=["Fortran 77"], build_system="none upstream; Techne recipe compiles the test drivers in ex/ against the routines", compiler_or_interpreter="gfortran (WinLibs GCC 15.2, Windows native)",
        dependencies=[], entry_points=["ex/file09 (test driver: nonlinear equations, HYBRD/HYBRJ)", "ex/file13 (CHKDER test)", "ex/file17 (least squares, LMDER/LMDIF/LMSTR)", "lmder1/lmdif1/hybrd1 (easy drivers)"],
        example={"command": "see recipe.json", "input": "ex/ data files", "output": "the drivers' problem-by-problem tables"},
        environment={"runner": "native Windows, WinLibs gfortran 15.2"},
        upstream_docs=["More, Garbow, Hillstrom, User Guide for MINPACK-1, ANL-80-74 (1980)", "netlib.org/minpack/readme"],
        human_capability_summary={"built_to": "find x minimising sum of squares of m nonlinear functions, or solving n nonlinear equations, from a user function with or without an analytic Jacobian",
                                  "pressure": "ill-conditioned Jacobians, expensive function evaluations, users who cannot write a correct derivative (hence CHKDER)",
                                  "success_means": "convergence to a solution within the user's tolerances with a bounded number of function evaluations; the ANL-80-74 test set"},
        known_human_problem_solved="curve fitting and root finding for nonlinear models, robustly, in 1980 Fortran"),
    record.skeleton("clips-6.4.2-nasa",
        canonical_name="CLIPS 6.4.2 (C Language Integrated Production System), NASA Johnson lineage",
        aliases=["CLIPS", "clipsrules"],
        lineage="CLIPS (1985, NASA JSC, Gary Riley): forward-chaining production-rule system with a Rete pattern matcher, later with COOL objects; the public-domain expert-system shell",
        domain=["expert-systems", "production-rules", "symbolic-ai", "pattern-matching"], era="1985 (this release 2024)",
        version="6.4.2 core source (sourceforge clipsrules, clips_core_source_642.zip)",
        source_origin={"artifacts": [{"kind": "url", "url": "https://sourceforge.net/projects/clipsrules/files/CLIPS/6.4.2/clips_core_source_642.zip/download", "filename": "clips_core_source_642.zip"}]},
        source_type="ORIGINAL_AUTHORITATIVE_RELEASE",
        source_identity={"project": "sourceforge.net/projects/clipsrules", "release": "6.4.2"},
        license={"spdx": "public-domain (CLIPS is released into the public domain; see the release notes)", "status": "unrestricted", "evidence": "clipsrules project description; verify in the zip's docs"},
        language=["C"], build_system="makefile (core/)", compiler_or_interpreter="gcc 13 (WSL2 Ubuntu 24.04)",
        dependencies=["libm"], entry_points=["core/clips (REPL and -f2 batch)"],
        example={"command": "./clips -f2 <rules.clp>", "input": "a .clp file asserting facts and defining rules", "output": "the rules' printouts"},
        environment={"runner": "wsl"},
        upstream_docs=["CLIPS Reference Manual (clipsrules.net)", "Giarratano & Riley, Expert Systems: Principles and Programming"],
        human_capability_summary={"built_to": "let domain experts encode knowledge as if-then rules over facts and have the machine chain them forward to conclusions, without writing procedural code",
                                  "pressure": "NASA needed portable, embeddable, verifiable expert systems in the mid-1980s when Lisp machines were expensive; Rete makes rule matching incremental",
                                  "success_means": "the right rules fire on the right facts, in a defensible order (salience, conflict resolution), fast enough for real-time use"},
        known_human_problem_solved="encoding and executing expert knowledge as production rules"),
    record.skeleton("minisat-2.2.0",
        canonical_name="MiniSat 2.2.0 -- Een and Sorensson",
        aliases=["minisat", "MiniSat"],
        lineage="MiniSat (2003-2010, Chalmers; Niklas Een, Niklas Sorensson): minimal CDCL SAT solver with two-watched literals, VSIDS, conflict-clause learning and restarts; the reference from which most modern SAT solvers descend",
        domain=["sat", "logic", "search", "constraint-solving"], era="2003 (2.2.0 released 2010)",
        version="2.2.0 tarball from minisat.se (the authors' site)",
        source_origin={"artifacts": [{"kind": "url", "url": "http://minisat.se/downloads/minisat-2.2.0.tar.gz", "filename": "minisat-2.2.0.tar.gz"}]},
        source_type="ORIGINAL_AUTHORITATIVE_RELEASE",
        source_identity={"site": "minisat.se", "release": "2.2.0"},
        license={"spdx": "MIT", "status": "permissive", "evidence": "LICENSE in the tarball"},
        language=["C++"], build_system="make (mtl/ core/ simp/)", compiler_or_interpreter="g++ 13 (WSL2)",
        dependencies=["zlib (headers) -- if absent in WSL the recipe falls back to docker"], entry_points=["core/minisat <cnf>", "simp/minisat <cnf>"],
        example={"command": "core/minisat_release input.cnf", "input": "DIMACS CNF", "output": "SATISFIABLE / UNSATISFIABLE + statistics on stderr"},
        environment={"runner": "wsl or docker"},
        upstream_docs=["Een, Sorensson, An Extensible SAT-solver, SAT 2003", "minisat.se"],
        human_capability_summary={"built_to": "decide propositional satisfiability of large CNF formulas and, when satisfiable, produce a model",
                                  "pressure": "industrial verification instances with millions of clauses; the need for a small, readable, extensible solver others could build on",
                                  "success_means": "correct SAT/UNSAT answers (models checkable, UNSAT trusted or proof-logged) fast on competition and industrial benchmarks"},
        known_human_problem_solved="propositional satisfiability at industrial scale, in ~1000 lines"),
    record.skeleton("spin-6.5.2-holzmann",
        canonical_name="SPIN 6.5.2 model checker -- Gerard Holzmann",
        aliases=["spin", "Spin", "Promela"],
        lineage="SPIN (1989-, Bell Labs / JPL, Gerard Holzmann): explicit-state model checker for Promela; on-the-fly LTL verification via nested depth-first search, partial-order reduction, bitstate hashing",
        domain=["model-checking", "verification", "concurrency", "protocols", "search"], era="1989 (6.5.2 released 2020)",
        version="git tag version-6.5.2, github.com/nimble-code/Spin (the author's repository)",
        source_origin={"artifacts": [{"kind": "url", "url": "https://github.com/nimble-code/Spin/archive/refs/tags/version-6.5.2.tar.gz", "filename": "Spin-version-6.5.2.tar.gz"}]},
        source_type="ORIGINAL_AUTHORITATIVE_RELEASE",
        source_identity={"repo": "github.com/nimble-code/Spin", "tag": "version-6.5.2"},
        license={"spdx": "BSD-3-Clause (Spin's LICENSE since 6.5)", "status": "permissive", "evidence": "LICENSE in the tarball"},
        language=["C", "yacc"], build_system="make in Src/ (needs yacc/bison)", compiler_or_interpreter="gcc + bison (docker debian:bookworm image, see environment/)",
        dependencies=["bison or yacc", "gcc for the generated verifier pan.c"], entry_points=["spin -a model.pml -> pan.c; gcc -o pan pan.c; ./pan", "spin -run model.pml"],
        example={"command": "spin -run Examples/... or a Techne smoke model", "input": "Promela model", "output": "verification result: errors: 0 or a counterexample trail"},
        environment={"runner": "docker", "image": "prometheus-fossil-c:bookworm (techne/fossils/environment/fossil-c-toolchain.Dockerfile)"},
        upstream_docs=["Holzmann, The SPIN Model Checker: Primer and Reference Manual, 2003", "spinroot.com"],
        human_capability_summary={"built_to": "prove that a concurrent protocol or program model satisfies safety and liveness properties, or produce a concrete counterexample execution",
                                  "pressure": "state explosion in asynchronous systems; telephony and spacecraft software whose bugs are interleaving-dependent",
                                  "success_means": "an exhaustive (or bitstate-approximate) search reporting no errors, or a trail that reproduces a violation"},
        known_human_problem_solved="finding concurrency bugs by exhaustive state-space search"),
    record.skeleton("graphplan-blum-furst-1995",
        canonical_name="Graphplan -- Avrim Blum and Merrick Furst (CMU), C implementation",
        aliases=["graphplan", "Graphplan"],
        lineage="Graphplan (1995, CMU): STRIPS planning by building a layered planning graph with mutual-exclusion relations and extracting a plan by backward search; the redesign that made classical planning fast",
        domain=["planning", "search", "symbolic-ai", "strips"], era="1995",
        version="CMU AFS distribution as served 2026-09-12 (Source.tar.gz + domain files)",
        source_origin={"artifacts": [{"kind": "url", "url": GP + "Source.tar.gz", "filename": "Source.tar.gz"},
                                     {"kind": "url", "url": GP + "BW.tar.gz", "filename": "BW.tar.gz", "extract": False},
                                     {"kind": "url", "url": GP + "README", "filename": "README", "extract": False}]
                                    + [{"kind": "url", "url": GP + f, "filename": "domains/" + f, "extract": False}
                                       for f in ("rocket_ops", "rocket_facts2", "rocket_facts4", "monkey_ops", "monkey_facts1",
                                                 "blocks_ops", "blocks_facts4", "logistics_ops", "logistics_facts4", "fixit_ops", "fixit_facts1")]},
        source_type="ORIGINAL_AUTHORITATIVE_RELEASE",
        source_identity={"site": "www.cs.cmu.edu/~avrim/graphplan.html", "path": "afs/cs.cmu.edu/usr/avrim/Planning/Graphplan/"},
        license={"spdx": "unstated (academic distribution; README)", "status": "UNRESOLVED -- read README", "evidence": "README in the vault"},
        language=["C", "lex/yacc (generated lex.yy.c, y.tab.c shipped)"], build_system="Makefile", compiler_or_interpreter="gcc 13 (WSL2)",
        dependencies=[], entry_points=["./graphplan -o <ops> -f <facts>"],
        example={"command": "./graphplan -o domains/rocket_ops -f domains/rocket_facts2", "input": "STRIPS operators and facts/goals files", "output": "a plan by time step, or 'problem not solvable'"},
        environment={"runner": "wsl"},
        upstream_docs=["Blum, Furst, Fast Planning Through Planning Graph Analysis, AIJ 90 (1997); IJCAI 1995", GP + "README"],
        human_capability_summary={"built_to": "find a parallel plan (sequence of action sets) from an initial state to a goal in STRIPS domains",
                                  "pressure": "exponential blow-up of plan-space and state-space planners on modest problems (rocket, logistics, blocks)",
                                  "success_means": "a valid plan with minimal number of time steps, found orders of magnitude faster than 1994 planners"},
        known_human_problem_solved="classical STRIPS planning via planning graphs"),
    record.skeleton("tscp-1.81-kerrigan-1997",
        canonical_name="TSCP 1.81 -- Tom Kerrigan's Simple Chess Program",
        aliases=["tscp", "TSCP"],
        lineage="TSCP (1997-, Tom Kerrigan): the didactic chess engine -- 0x88-free mailbox board, alpha-beta with iterative deepening, quiescence, killer moves, history heuristic, simple evaluation",
        domain=["games", "chess", "alpha-beta-search", "game-tree-search"], era="1997 (1.81 released 2001)",
        version="tscp181.zip from tckerrigan.com (the author's site)",
        source_origin={"artifacts": [{"kind": "url", "url": "http://www.tckerrigan.com/Chess/TSCP/tscp181.zip", "filename": "tscp181.zip"}]},
        source_type="ORIGINAL_AUTHORITATIVE_RELEASE",
        source_identity={"site": "tckerrigan.com/Chess/TSCP", "release": "1.81"},
        license={"spdx": "custom (author permits use for learning; see the source header)", "status": "read the header before redistribution", "evidence": "header comment in main.c / readme"},
        language=["C"], build_system="none (gcc *.c)", compiler_or_interpreter="gcc 13 (WSL2)",
        dependencies=[], entry_points=["./tscp (interactive: 'st <sec>', 'sd <depth>', moves in coordinate notation, 'go', 'bench')"],
        example={"command": "printf 'sd 4\\ngo\\nquit\\n' | ./tscp", "input": "commands on stdin", "output": "the engine's move and search statistics"},
        environment={"runner": "wsl"},
        upstream_docs=["tckerrigan.com/Chess/TSCP/"],
        human_capability_summary={"built_to": "play legal, reasonable chess with the smallest readable code, so people could learn how chess programs search",
                                  "pressure": "the branching factor of chess: search must prune (alpha-beta), order moves (killers, history) and resolve tactics (quiescence)",
                                  "success_means": "playing strength on a clock; here, deterministic best-move output at a fixed depth"},
        known_human_problem_solved="game-tree search for a two-player zero-sum game"),
    record.skeleton("ldpc-codes-neal-2001",
        canonical_name="LDPC-codes -- Radford M. Neal's software for low density parity check codes",
        aliases=["LDPC-codes", "ldpc"],
        lineage="Neal LDPC software (2001-2012, U Toronto): construction of sparse parity-check matrices, encoding via dense/mixed/sparse methods, channel simulation, and belief-propagation (sum-product) decoding; a reference implementation for Gallager/MacKay-Neal codes",
        domain=["error-correcting-codes", "coding-theory", "belief-propagation", "inference"], era="2001 (last revision 2012)",
        version="github.com/radfordneal/LDPC-codes default branch as of 2026-09-12 (recorded commit in hashes)",
        source_origin={"artifacts": [{"kind": "git", "url": "https://github.com/radfordneal/LDPC-codes", "commit": "HEAD"}]},
        source_type="ORIGINAL_AUTHORITATIVE_RELEASE",
        source_identity={"repo": "github.com/radfordneal/LDPC-codes"},
        license={"spdx": "custom permissive (Neal: free for any purpose with notice; see index.html/COPYRIGHT)", "status": "permissive", "evidence": "the tree's COPYRIGHT / index.html"},
        language=["C"], build_system="make (Makefile; make test)", compiler_or_interpreter="gcc 13 (WSL2)",
        dependencies=[], entry_points=["make-ldpc, make-gen, encode, transmit, decode, verify, extract (pipeline of CLI tools)"],
        example={"command": "make && make test", "input": "the shipped test scripts (random codes, BSC/AWGN channels)", "output": "decoding error rates per test"},
        environment={"runner": "wsl"},
        upstream_docs=["radfordneal.github.io/LDPC-codes/", "MacKay & Neal, Near Shannon limit performance of low density parity check codes, 1996"],
        human_capability_summary={"built_to": "correct transmission errors with sparse-graph codes decoded by iterative probabilistic message passing",
                                  "pressure": "approach the Shannon limit with practical decoding complexity",
                                  "success_means": "block/bit error rate after decoding, at a given channel noise, near the code's threshold"},
        known_human_problem_solved="near-capacity error correction by belief propagation"),
    record.skeleton("sqlite-3.49.1-amalgamation",
        canonical_name="SQLite 3.49.1 amalgamation -- D. Richard Hipp",
        aliases=["sqlite", "sqlite3"],
        lineage="SQLite (2000-, Hipp): embedded transactional SQL database in one C file -- bytecode VM (VDBE), B-tree pager with rollback/WAL journaling, cost-based query planner, full ACID in-process",
        domain=["databases", "query-planning", "b-tree", "transactions", "storage-engine", "virtual-machine"], era="2000 (3.49.1 released 2025)",
        version="3.49.1 amalgamation (sqlite.org/2025/sqlite-amalgamation-3490100.zip)",
        source_origin={"artifacts": [{"kind": "url", "url": "https://sqlite.org/2025/sqlite-amalgamation-3490100.zip", "filename": "sqlite-amalgamation-3490100.zip"}]},
        source_type="ORIGINAL_AUTHORITATIVE_RELEASE",
        source_identity={"site": "sqlite.org", "release": "3.49.1", "form": "amalgamation (generated from the canonical Fossil tree; not the source tree with the TCL tests)"},
        license={"spdx": "public-domain (blessing)", "status": "unrestricted", "evidence": "sqlite.org/copyright.html; header of sqlite3.c"},
        language=["C"], build_system="none (gcc shell.c sqlite3.c)", compiler_or_interpreter="gcc 13 (WSL2)",
        dependencies=["libm", "libpthread", "libdl (optional)"], entry_points=["./sqlite3 (shell)", "sqlite3.h C API"],
        example={"command": "./sqlite3 :memory: < smoke.sql", "input": "SQL", "output": "query results"},
        environment={"runner": "wsl"},
        upstream_docs=["sqlite.org/arch.html", "sqlite.org/vdbe.html", "sqlite.org/fileformat2.html"],
        human_capability_summary={"built_to": "give any program a full relational database with transactions in a single file, no server, no configuration",
                                  "pressure": "crash safety on power loss, tiny footprint, portability, and correctness under concurrent readers",
                                  "success_means": "SQL executed correctly and durably; the project's own TH3/TCL test suites (not in the amalgamation) at 100% branch coverage"},
        known_human_problem_solved="embedded ACID storage and SQL query execution",
        versions_preserved=[{"note": "sqlite-2.8.17 (2005) queued as the pre-3.0 file-format lineage; not yet acquired"}]),
    record.skeleton("ncompress-5.0-lzw-1985",
        canonical_name="ncompress 5.0 -- the Unix compress(1) LZW lineage (Spencer Thomas et al., 1984-85)",
        aliases=["compress", "ncompress", "LZW"],
        lineage="compress(1) (1984-85, Spencer Thomas, Jim McKie, Steve Davies, Ken Turkowski, James Woods, Joe Orost): adaptive LZW dictionary coding, the 4.3BSD/Unix standard before gzip; ncompress is the maintained continuation of the same code",
        domain=["compression", "dictionary-coding", "lzw"], era="1984 (5.0 released 2021)",
        version="git tag v5.0, github.com/vapier/ncompress",
        source_origin={"artifacts": [{"kind": "url", "url": "https://github.com/vapier/ncompress/archive/refs/tags/v5.0.tar.gz", "filename": "ncompress-5.0.tar.gz"}]},
        source_type="LATER_SAME_LINEAGE_RELEASE",
        source_identity={"repo": "github.com/vapier/ncompress", "tag": "v5.0", "ancestry": "compress 4.x (1985) -> ncompress 4.2 (1992) -> 5.0"},
        license={"spdx": "public-domain / permissive per the source headers", "status": "see LICENSE in tarball", "evidence": "tarball"},
        language=["C"], build_system="make", compiler_or_interpreter="gcc 13 (WSL2)",
        dependencies=[], entry_points=["./compress, ./compress -d (uncompress)"],
        example={"command": "./compress -c input > out.Z; ./compress -dc out.Z | cmp - input", "input": "any file", "output": "identical bytes after the round trip"},
        environment={"runner": "wsl"},
        upstream_docs=["Welch, A Technique for High-Performance Data Compression, IEEE Computer 1984", "compress.c header history"],
        human_capability_summary={"built_to": "shrink files losslessly with an adaptive dictionary that needs no side information",
                                  "pressure": "1980s disk and modem bandwidth; the patent history of LZW is why gzip displaced it",
                                  "success_means": "exact reconstruction after decompression, with a good compression ratio on text"},
        known_human_problem_solved="lossless adaptive dictionary compression"),
    record.skeleton("tinyscheme-1.42",
        canonical_name="TinyScheme 1.42 -- Dimitrios Souflis et al.",
        aliases=["tinyscheme", "TinyScheme"],
        lineage="TinyScheme (2000-, from Atsushi Moriwaki's MiniScheme 1989): a small R5RS-ish Scheme interpreter in one C file -- s-expression reader, eval/apply on a dispatch loop, mark-and-sweep GC, call/cc, tail calls",
        domain=["languages", "interpreters", "lisp", "garbage-collection"], era="1989/2000 (1.42 released 2021)",
        version="tinyscheme-1.42.tar.gz (sourceforge)",
        source_origin={"artifacts": [{"kind": "url", "url": "https://sourceforge.net/projects/tinyscheme/files/tinyscheme/tinyscheme-1.42/tinyscheme-1.42.tar.gz/download", "filename": "tinyscheme-1.42.tar.gz"}]},
        source_type="ORIGINAL_AUTHORITATIVE_RELEASE",
        source_identity={"project": "sourceforge.net/projects/tinyscheme", "release": "1.42"},
        license={"spdx": "BSD-3-Clause", "status": "permissive", "evidence": "COPYING in tarball"},
        language=["C", "Scheme"], build_system="makefile", compiler_or_interpreter="gcc 13 (WSL2)",
        dependencies=["libm", "libdl (optional)"], entry_points=["./scheme (REPL; reads init.scm)", "./scheme file.scm"],
        example={"command": "echo '(display (+ 1 2))' | ./scheme", "input": "Scheme expressions", "output": "3"},
        environment={"runner": "wsl"},
        upstream_docs=["tinyscheme.sourceforge.net", "Manual.txt in tarball"],
        human_capability_summary={"built_to": "embed a complete, tiny Scheme in a C program as a scripting/extension language",
                                  "pressure": "memory and code-size limits of embedded and scripting hosts; correctness of tail calls and continuations in little code",
                                  "success_means": "R5RS programs evaluate correctly within a few hundred kilobytes"},
        known_human_problem_solved="a minimal, embeddable Lisp interpreter"),
    record.skeleton("c-cmaes-hansen",
        canonical_name="c-cmaes -- Nikolaus Hansen's C reference implementation of CMA-ES",
        aliases=["cmaes", "CMA-ES", "c-cmaes"],
        lineage="CMA-ES (1996-, Hansen & Ostermeier): evolution strategy with covariance matrix adaptation and cumulative step-size adaptation; this is the author's own ANSI C code (cmaes.c), the ancestor of every pycma-style port",
        domain=["optimization", "evolutionary-computation", "black-box-optimization", "stochastic-search"], era="1996 (C code 2003-2014)",
        version="github.com/CMA-ES/c-cmaes default branch as of 2026-09-12 (commit in hashes)",
        source_origin={"artifacts": [{"kind": "git", "url": "https://github.com/CMA-ES/c-cmaes", "commit": "HEAD"}]},
        source_type="ORIGINAL_AUTHORITATIVE_RELEASE",
        source_identity={"repo": "github.com/CMA-ES/c-cmaes"},
        license={"spdx": "custom permissive (Hansen: 'may be used, modified, redistributed' with notice)", "status": "see cmaes.c header / LICENSE", "evidence": "tree"},
        language=["C"], build_system="makefile (example1, example2)", compiler_or_interpreter="gcc 13 (WSL2)",
        dependencies=["libm"], entry_points=["./evo1 (example1.c: optimise a test function from cmaes_initials.par)"],
        example={"command": "make && ./evo1", "input": "cmaes_initials.par (dimension, initial x, sigma, seed)", "output": "iteration log and the best-ever solution"},
        environment={"runner": "wsl"},
        upstream_docs=["Hansen, The CMA Evolution Strategy: A Tutorial, arXiv:1604.00772", "cmaes.c comments"],
        human_capability_summary={"built_to": "minimise a black-box, possibly noisy and ill-conditioned objective in continuous space without derivatives",
                                  "pressure": "non-separable, badly scaled landscapes where gradient methods fail or are unavailable",
                                  "success_means": "reaching the optimum's function value within tolerance in a small multiple of the dimension's evaluations"},
        known_human_problem_solved="derivative-free continuous optimisation with learned search-distribution geometry"),
]


def main():
    for rec in SPECIMENS:
        # keep run/test state and receipts from an earlier write if present
        try:
            old = record.load(rec["specimen_id"])
            for k in ("run_classification", "test_classification", "receipts", "hashes", "acquisition_date", "environment"):
                if old.get(k):
                    rec[k] = old[k] if k != "environment" else {**rec["environment"], **old["environment"]}
        except FileNotFoundError:
            pass
        probs = record.validate(rec)
        record.save(rec)
        print("%-32s %s" % (rec["specimen_id"], "ok" if not probs else probs))


if __name__ == "__main__":
    main()
