"""Batch 04 of the fossil harvest (2026-09-12): MACHINERY UNDER PRESSURE. records.

    python -m techne.fossils.batches.batch04

Preferentially machinery shaped by scarcity / contention / delay / failure / uncertainty /
noise / memory limits / feedback / hidden state / competition. Each record carries the batch-04
pressure fields (human_environmental_pressure, human_failure_condition, behavioral_entry_point)
-- context and a way to perturb, never a decomposition. Nyx chops.
"""
from __future__ import annotations

from .. import record

S = []


def spec(sid, **kw):
    S.append(record.skeleton(sid, **kw))


# ============================ AXIS 1: CONTENTION / RETRY / RECOVERY ==========================
spec("willemt-raft",
    canonical_name="willemt/raft -- a C implementation of the Raft consensus algorithm",
    aliases=["raft", "willemt-raft"],
    lineage="Raft (2014, Ongaro & Ousterhout): understandable distributed consensus -- leader election, log replication, and safety across crashing/partitioning nodes; willemt/raft is a widely-used embeddable C library of the core state machine",
    domain=["distributed-systems", "consensus", "leader-election", "replication", "recovery", "fault-tolerance"],
    era="2014-",
    version="github.com/willemt/raft master as of 2026-09-12 (commit in hashes)",
    source_origin={"artifacts": [{"kind": "git", "url": "https://github.com/willemt/raft", "commit": "HEAD"}]},
    source_type="ORIGINAL_AUTHORITATIVE_RELEASE", source_identity={"repo": "github.com/willemt/raft"},
    license={"spdx": "BSD-3-Clause", "status": "permissive", "evidence": "LICENSE"},
    language=["C"], build_system="make tests", compiler_or_interpreter="gcc 12 (docker bookworm)",
    dependencies=["a C compiler; the repo bundles its test deps"],
    entry_points=["the raft state machine (raft_periodic, raft_recv_appendentries, raft_recv_requestvote); make tests"],
    example={"command": "make tests", "input": "the unit + fuzz tests of election and log replication", "output": "test pass/fail counts"},
    environment={"runner": "docker", "image": "prometheus-fossil-c:bookworm"},
    upstream_docs=["Ongaro & Ousterhout, In Search of an Understandable Consensus Algorithm (Raft), USENIX ATC 2014"],
    human_capability_summary={"built_to": "keep a replicated log consistent across a cluster of machines that crash, restart, and get partitioned -- by electing a leader and replicating entries only when a majority acknowledges",
                              "pressure": "partial failure: nodes die, messages are lost or delayed, the network splits; the system must never present two leaders' conflicting histories as committed",
                              "success_means": "a single consistent committed log despite up to (N-1)/2 failures; safety never violated, liveness restored when a majority reconnects"},
    known_human_problem_solved="fault-tolerant distributed consensus",
    human_environmental_pressure="partial failure, message loss/delay, network partition, competing would-be leaders",
    human_failure_condition="split-brain: two leaders commit conflicting entries; the replicated state diverges and data is lost or corrupted",
    behavioral_entry_point="in the tests, drop/delay AppendEntries or RequestVote messages, or kill the leader, and watch election + log reconciliation",
    lineage_relations=[{"relation": "algorithm_from", "to": "Ongaro & Ousterhout 2014", "note": "Raft; itself a redesign of Paxos for understandability"}])

spec("linux-tcp-congestion",
    canonical_name="Linux TCP congestion control -- CUBIC and BBR (the congestion-avoidance lineage under pressure)",
    aliases=["tcp_cubic", "tcp_bbr", "TCP congestion control"],
    lineage="TCP congestion control (1988-, Van Jacobson onward): Tahoe -> Reno -> NewReno -> CUBIC (2008, loss-based, the Linux default) -> BBR (2016, Google, model-based rate/RTT). Each redesign was forced by a changed network: higher bandwidth-delay products, then bufferbloat. Preserved here as the actual Linux kernel modules tcp_cubic.c and tcp_bbr.c.",
    domain=["networks", "congestion-control", "feedback-control", "adaptation", "contention"],
    era="1988- (cubic 2008, bbr 2016)",
    version="linux v6.6 net/ipv4/tcp_cubic.c + tcp_bbr.c (pinned tag)",
    source_origin={"artifacts": [{"kind": "url", "url": "https://raw.githubusercontent.com/torvalds/linux/v6.6/net/ipv4/tcp_cubic.c", "filename": "tcp_cubic.c", "extract": False},
                                 {"kind": "url", "url": "https://raw.githubusercontent.com/torvalds/linux/v6.6/net/ipv4/tcp_bbr.c", "filename": "tcp_bbr.c", "extract": False}]},
    source_type="ORIGINAL_AUTHORITATIVE_RELEASE", source_identity={"repo": "torvalds/linux", "tag": "v6.6", "files": ["net/ipv4/tcp_cubic.c", "net/ipv4/tcp_bbr.c"]},
    license={"spdx": "GPL-2.0", "status": "copyleft", "evidence": "SPDX header in each file"},
    language=["C (Linux kernel)"], build_system="none standalone (kernel module context)", compiler_or_interpreter="Linux kernel build (NOT built standalone)",
    dependencies=["the Linux kernel TCP stack (struct tcp_sock, the congestion_ops interface)"],
    entry_points=["struct tcp_congestion_ops: .cong_avoid / .ssthresh / .cong_control (cubic); the BBR state machine (STARTUP/DRAIN/PROBE_BW/PROBE_RTT)"],
    example={"command": "SOURCE ONLY -- read cubic's window growth vs bbr's rate/RTT model; a live run needs a kernel + netem", "input": "n/a", "output": "n/a"},
    environment={"runner": "none this pass -- SOURCE pinned; a runnable comparison needs a kernel with tc/netem injecting loss and delay (RUNNABLE_EMULATED candidate via a VM)"},
    upstream_docs=["Ha, Rhee, Xu, CUBIC: A New TCP-Friendly High-Speed TCP Variant, 2008", "Cardwell et al., BBR: Congestion-Based Congestion Control, 2016", "Jacobson, Congestion Avoidance and Control, 1988"],
    human_capability_summary={"built_to": "regulate a TCP sender's transmission rate so it uses available bandwidth without collapsing the shared network -- inferring congestion from loss (CUBIC) or from a bandwidth/RTT model (BBR)",
                              "pressure": "a shared link of unknown, varying capacity with many competing senders; too fast causes loss and congestion collapse, too slow wastes the link",
                              "success_means": "high throughput, low queueing delay, and fairness to other flows across a range of bandwidth-delay products and loss rates"},
    known_human_problem_solved="congestion avoidance on a shared network",
    human_environmental_pressure="bandwidth scarcity, packet loss, variable RTT, bufferbloat, competing flows",
    human_failure_condition="congestion collapse (1986): everyone retransmits into a saturated link and useful throughput drops toward zero",
    behavioral_entry_point="the two files ARE the before/after of a documented redesign: CUBIC's loss-triggered cubic window vs BBR's explicit bandwidth+RTT probing. Read them side by side; a live study injects loss/delay with netem.",
    versions_preserved=[{"version": "CUBIC (2008)", "role": "TRANSITION -- loss-based, replaced Reno/BIC as the Linux default"},
                        {"version": "BBR (2016)", "role": "AFTER -- model-based, a paradigm change from loss-triggered to rate/RTT estimation"},
                        {"note": "BEFORE (Tahoe/Reno/NewReno, 1988-1999) referenced but not preserved here; queued from historical BSD"}],
    lineage_relations=[{"relation": "superseded", "to": "TCP Reno/NewReno", "note": "CUBIC replaced Reno-family as Linux default"},
                       {"relation": "algorithm_from", "to": "Jacobson 1988", "note": "the congestion-avoidance lineage all descend from"}])

# ============================ AXIS 2: CONTROL / FEEDBACK =====================================
spec("arduino-pid",
    canonical_name="Arduino PID Library -- Brett Beauregard",
    aliases=["arduino-pid", "PID_v1", "br3ttb PID"],
    lineage="Beauregard PID (2011-): a widely-copied, carefully-engineered PID controller -- proportional/integral/derivative feedback with anti-windup, derivative-on-measurement, and bumpless mode switching; the reference small feedback controller of the maker world",
    domain=["control", "feedback-control", "pid", "regulation"], era="2011-",
    version="github.com/br3ttb/Arduino-PID-Library master as of 2026-09-12 (commit in hashes)",
    source_origin={"artifacts": [{"kind": "git", "url": "https://github.com/br3ttb/Arduino-PID-Library", "commit": "HEAD"}]},
    source_type="ORIGINAL_AUTHORITATIVE_RELEASE", source_identity={"repo": "github.com/br3ttb/Arduino-PID-Library"},
    license={"spdx": "MIT", "status": "permissive", "evidence": "LICENSE"},
    language=["C++"], build_system="compile PID_v1.cpp with a Techne Arduino-shim + a plant simulator", compiler_or_interpreter="g++ 12 (docker bookworm)",
    dependencies=["an Arduino.h shim providing millis() (Techne harness supplies a minimal one)"],
    entry_points=["PID::Compute() -- run each control step on (Input, Setpoint) -> Output"],
    example={"command": "Techne harness: a first-order plant + PID, step the setpoint, log the response", "input": "setpoint + disturbance", "output": "the controlled variable converging to setpoint"},
    environment={"runner": "docker", "image": "prometheus-fossil-c:bookworm"},
    upstream_docs=["Beauregard, Improving the Beginner's PID (blog series)", "Astrom & Hagglund, PID Controllers"],
    human_capability_summary={"built_to": "drive a measured process variable to a setpoint by feeding back the error through proportional, integral and derivative terms, robustly, on a tiny microcontroller",
                              "pressure": "actuator limits (windup), noisy measurements (derivative kick), and mode changes (bumpless transfer) in a real physical loop with lag",
                              "success_means": "the process variable reaches and holds the setpoint with acceptable overshoot/settling despite disturbances and saturation"},
    known_human_problem_solved="closed-loop regulation of a physical process",
    human_environmental_pressure="actuator lag and saturation, measurement noise, load disturbance, setpoint changes",
    human_failure_condition="oscillation or runaway: bad gains make the loop unstable; integral windup overshoots; the controlled machine overheats/crashes/breaks",
    behavioral_entry_point="change the setpoint (step), inject a load disturbance, or set aggressive gains (Kp/Ki high) to drive it UNSTABLE -- the harness does the last as a pathological-behavior receipt")

spec("python-control",
    canonical_name="python-control -- the Python Control Systems Library",
    aliases=["python-control", "control"],
    lineage="python-control (2010-, Murray et al., Caltech): LTI systems, state-space and transfer functions, LQR/LQE optimal control, pole placement, frequency response; the open reference implementing the classical/modern control toolbox in Python",
    domain=["control", "optimal-control", "state-feedback", "lqr", "feedback-control"], era="2010-",
    version="github.com/python-control/python-control main as of 2026-09-12 (commit in hashes)",
    source_origin={"artifacts": [{"kind": "git", "url": "https://github.com/python-control/python-control", "commit": "HEAD"}]},
    source_type="ORIGINAL_AUTHORITATIVE_RELEASE", source_identity={"repo": "github.com/python-control/python-control"},
    license={"spdx": "BSD-3-Clause", "status": "permissive", "evidence": "LICENSE"},
    language=["Python"], build_system="pip install . (numpy+scipy)", compiler_or_interpreter="CPython 3.11 + numpy/scipy (docker python:3.11-slim, pip at run time)",
    dependencies=["numpy", "scipy"],
    entry_points=["control.lqr / control.ss / control.forced_response -- design an LQR gain and simulate the closed loop"],
    example={"command": "Techne harness: build a 2-state plant, design an LQR gain, simulate to the origin from a perturbed state", "input": "a state-space plant + cost matrices Q,R", "output": "the closed-loop state trajectory driven to zero"},
    environment={"runner": "docker", "image": "python:3.11-slim"},
    upstream_docs=["python-control.readthedocs.io", "Astrom & Murray, Feedback Systems"],
    human_capability_summary={"built_to": "design and simulate controllers for linear dynamical systems -- compute an optimal state-feedback gain (LQR) that trades control effort against state error, and simulate the resulting closed loop",
                              "pressure": "a multivariable plant with coupled states where hand-tuning fails; the controller must stabilise and optimise a quadratic cost",
                              "success_means": "the closed-loop system is stable and drives the state to the target with the intended effort/error trade-off"},
    known_human_problem_solved="model-based optimal control design (LQR and friends)",
    human_environmental_pressure="coupled multivariable dynamics, control-effort limits, the effort-vs-error trade-off",
    human_failure_condition="an unstable or badly-tuned gain lets the state diverge; in a physical plant that is a crash",
    behavioral_entry_point="change Q/R (cheap vs expensive control), perturb the initial state, or add a disturbance to the simulated plant and watch the LQR response")

spec("do-mpc",
    canonical_name="do-mpc -- Model Predictive Control toolbox (TU Dortmund)",
    aliases=["do-mpc", "MPC"],
    lineage="do-mpc (2016-, Fiedler/Lucia et al.): nonlinear and robust Model Predictive Control -- at each step solve a finite-horizon optimal-control problem over a model, apply the first input, re-solve (receding horizon); built on CasADi/IPOPT",
    domain=["control", "model-predictive-control", "optimization", "receding-horizon", "feedback-control"], era="2016-",
    version="github.com/do-mpc/do-mpc master as of 2026-09-12 (commit in hashes)",
    source_origin={"artifacts": [{"kind": "git", "url": "https://github.com/do-mpc/do-mpc", "commit": "HEAD"}]},
    source_type="ORIGINAL_AUTHORITATIVE_RELEASE", source_identity={"repo": "github.com/do-mpc/do-mpc"},
    license={"spdx": "LGPL-3.0", "status": "copyleft", "evidence": "LICENSE"},
    language=["Python"], build_system="pip install do-mpc casadi (heavy; NOT built this pass)", compiler_or_interpreter="CPython + CasADi + IPOPT (deferred)",
    dependencies=["casadi", "numpy", "an NLP solver (IPOPT)"],
    entry_points=["do_mpc.controller.MPC over a do_mpc.model; the receding-horizon loop"],
    example={"command": "SOURCE ONLY this pass -- the CasADi/IPOPT stack is a heavy install deferred", "input": "a model + horizon + constraints", "output": "the predicted-optimal input sequence, first step applied"},
    environment={"runner": "none this pass -- SOURCE pinned; CasADi/IPOPT build deferred (RUNNABLE_CONTAINER candidate)"},
    upstream_docs=["do-mpc.com", "Rawlings, Mayne, Diehl, Model Predictive Control: Theory, Computation, and Design"],
    human_capability_summary={"built_to": "control a constrained dynamical system by repeatedly solving, at each step, a finite-horizon optimisation over a model of the plant and applying only the first move -- anticipating the future and respecting constraints",
                              "pressure": "hard constraints (actuator/state limits) and a plant where greedy feedback violates them; the controller must look ahead and re-plan as reality diverges from the model",
                              "success_means": "constraint-respecting control that optimises a horizon cost and re-plans fast enough to run in real time"},
    known_human_problem_solved="constrained predictive control by receding-horizon optimisation",
    human_environmental_pressure="hard state/actuator constraints, model mismatch, a real-time solve deadline",
    human_failure_condition="the horizon optimisation is infeasible or too slow -> the controller stalls or violates a constraint (a physical limit is breached)",
    behavioral_entry_point="tighten a constraint or shorten the solve deadline until the receding-horizon problem becomes infeasible")

# ============================ AXIS 3: HIDDEN STATE / ESTIMATION ==============================
spec("simple-kalman-denyssene",
    canonical_name="SimpleKalmanFilter -- a compact scalar Kalman filter (Denys Sene)",
    aliases=["SimpleKalmanFilter", "kalman"],
    lineage="Kalman filter (1960, Rudolf Kalman): recursive least-squares estimation of hidden state from noisy measurements via predict/update; this is a minimal scalar C++ reference for embedded sensor smoothing",
    domain=["estimation", "kalman-filter", "state-estimation", "sensor-fusion", "signal-reconstruction"], era="1960 (this impl modern)",
    version="github.com/denyssene/SimpleKalmanFilter master as of 2026-09-12 (commit in hashes)",
    source_origin={"artifacts": [{"kind": "git", "url": "https://github.com/denyssene/SimpleKalmanFilter", "commit": "HEAD"}]},
    source_type="PSEUDOCODE_PLUS_REFERENCE_IMPL", source_identity={"repo": "github.com/denyssene/SimpleKalmanFilter"},
    license={"spdx": "MIT", "status": "permissive", "evidence": "LICENSE"},
    language=["C++"], build_system="compile the .cpp with a Techne driver", compiler_or_interpreter="g++ 12 (docker bookworm)",
    dependencies=[], entry_points=["SimpleKalmanFilter::updateEstimate(measurement) -> filtered estimate"],
    example={"command": "Techne harness: a constant true value + Gaussian measurement noise; check the filtered variance << raw variance", "input": "noisy measurements of a hidden constant", "output": "an estimate whose error variance is far below the measurement noise"},
    environment={"runner": "docker", "image": "prometheus-fossil-c:bookworm"},
    upstream_docs=["Kalman, A New Approach to Linear Filtering and Prediction Problems, 1960"],
    human_capability_summary={"built_to": "recover a hidden true value from a stream of noisy measurements by recursively combining a prediction with each new observation, weighted by their uncertainties",
                              "pressure": "measurement noise and the impossibility of observing the true state directly; a naive average lags, a raw reading is jittery",
                              "success_means": "an estimate that tracks the true state with error variance far below the raw measurement noise"},
    known_human_problem_solved="optimal recursive estimation of hidden state under noise",
    human_environmental_pressure="noisy observation, hidden (unobservable) true state",
    human_failure_condition="a mistuned filter either lags reality (over-smooths) or passes the noise through (under-smooths); a navigation estimate drifts and the vehicle mislocates",
    behavioral_entry_point="raise the measurement-noise level, or feed a step change in the hidden value, and watch the estimate's lag/variance trade-off")

spec("filterpy-labbe",
    canonical_name="FilterPy -- Bayesian filtering library (Roger Labbe)",
    aliases=["filterpy", "Kalman-and-Bayesian-Filters"],
    lineage="FilterPy (2014-, Labbe): reference implementations of the Kalman family (KF/EKF/UKF), particle filters, and other Bayesian filters, written for clarity alongside the book 'Kalman and Bayesian Filters in Python'; carries example systems (a noisy nonlinear plant) AND the estimators that recover their hidden state",
    domain=["estimation", "particle-filter", "kalman-filter", "unscented-kalman", "bayesian-inference", "state-estimation"], era="2014-",
    version="github.com/rlabbe/filterpy master as of 2026-09-12 (commit in hashes)",
    source_origin={"artifacts": [{"kind": "git", "url": "https://github.com/rlabbe/filterpy", "commit": "HEAD"}]},
    source_type="ORIGINAL_AUTHORITATIVE_RELEASE", source_identity={"repo": "github.com/rlabbe/filterpy"},
    license={"spdx": "MIT", "status": "permissive", "evidence": "LICENSE"},
    language=["Python"], build_system="pip install . (numpy+scipy)", compiler_or_interpreter="CPython 3.11 + numpy/scipy (docker python:3.11-slim)",
    dependencies=["numpy", "scipy"],
    entry_points=["filterpy.kalman.KalmanFilter / UnscentedKalmanFilter; filterpy.monte_carlo (systematic_resample) for the particle filter"],
    example={"command": "Techne harness: a 1-D constant-velocity target with process+measurement noise, estimated by a KF; check RMSE below the raw sensor", "input": "noisy position measurements", "output": "a filtered track with RMSE < the sensor noise"},
    environment={"runner": "docker", "image": "python:3.11-slim"},
    upstream_docs=["Labbe, Kalman and Bayesian Filters in Python (the book)", "rlabbe.github.io/Kalman-and-Bayesian-Filters-in-Python"],
    human_capability_summary={"built_to": "estimate the hidden state of a dynamical system from noisy measurements across the whole Bayesian-filter family -- linear (KF), nonlinear (EKF/UKF), and non-Gaussian (particle filter)",
                              "pressure": "nonlinearity and non-Gaussian noise where the plain Kalman filter fails; hidden state that must be tracked through a noisy, possibly multimodal posterior",
                              "success_means": "a state estimate that tracks truth with low error and calibrated uncertainty, even when the system is nonlinear or the posterior is multimodal"},
    known_human_problem_solved="Bayesian state estimation across the filter family",
    human_environmental_pressure="noisy observation, nonlinear dynamics, non-Gaussian / multimodal uncertainty, hidden state",
    human_failure_condition="a diverged filter (EKF linearisation error) or a degenerate particle set (all weight on one particle) loses the track entirely",
    behavioral_entry_point="ADVERSARIAL PAIR within this repo: the example systems GENERATE process+measurement noise (the pressure) and the filters RECOVER the state (the response). Raise noise, add nonlinearity, or drop measurements to break the estimator; force particle degeneracy by shrinking the particle count.")

spec("viterbi-hmm-xukmin",
    canonical_name="Viterbi / HMM decoder (compact C++ reference, Min Xu)",
    aliases=["viterbi", "hmm-viterbi"],
    lineage="The Viterbi algorithm (1967) over a Hidden Markov Model (Rabiner 1989): find the most-likely hidden state path for an observation sequence by dynamic programming over the trellis; this is a small, tested C++ reference of the HMM + Viterbi decode",
    domain=["estimation", "hidden-markov-model", "viterbi", "dynamic-programming", "sequence-modelling", "hidden-state"],
    era="1967/1989 lineage; this impl modern",
    version="github.com/xukmin/viterbi master as of 2026-09-12 (commit in hashes)",
    source_origin={"artifacts": [{"kind": "git", "url": "https://github.com/xukmin/viterbi", "commit": "HEAD"}]},
    source_type="PSEUDOCODE_PLUS_REFERENCE_IMPL", source_identity={"repo": "github.com/xukmin/viterbi"},
    license={"spdx": "see repo LICENSE.md", "status": "read before redistribution", "evidence": "repo"},
    language=["C++"], build_system="make (ships viterbi_test.cpp + viterbi_main.cpp)", compiler_or_interpreter="g++ 12 (docker bookworm)",
    dependencies=[], entry_points=["Viterbi decode over an HMM (states, transition, emission, observations) -> most-likely state path; the shipped test + main"],
    example={"command": "make && ./viterbi_test (and ./viterbi < a sample HMM+observation)", "input": "an HMM (transition/emission) + an observation sequence", "output": "the most-likely hidden state path"},
    environment={"runner": "docker", "image": "prometheus-fossil-c:bookworm"},
    upstream_docs=["Viterbi, Error bounds for convolutional codes..., 1967", "Rabiner, A Tutorial on Hidden Markov Models, 1989"],
    human_capability_summary={"built_to": "recover the most-likely sequence of hidden states that produced an observed sequence, by dynamic programming over the HMM trellis (predict-then-max at each step)",
                              "pressure": "the true state sequence is never observed, only noisy emissions; the number of possible paths is exponential in sequence length",
                              "success_means": "the decoded path matches the true generating states on the test HMM; likelihood computed correctly"},
    known_human_problem_solved="most-likely-path inference in a hidden Markov model (Viterbi)",
    human_environmental_pressure="hidden state, noisy/ambiguous emissions, exponential path space",
    human_failure_condition="a wrong transition/emission model yields a wrong decoded path -- a speech recogniser or gene finder built on it makes systematic errors",
    behavioral_entry_point="perturb the emission or transition probabilities, or make two states' emissions overlap, and watch the decoded path change; the shipped test is the oracle",
    versions_preserved=[{"note": "the richer historical GHMM (Baum-Welch training + forward-backward, MPI-MG, autotools C) is queued as a heavier same-lineage companion"}])

# ============================ AXIS 4: MEMORY UNDER SCARCITY ==================================
spec("lru-cache-goldsborough",
    canonical_name="lru-cache -- a C++ LRU cache (Peter Goldsborough)",
    aliases=["lru-cache"],
    lineage="LRU (least-recently-used) eviction: when a bounded cache is full, discard the entry unused for longest; a hash-map + intrusive list, the standard caching mechanism across CPUs, OSes and databases",
    domain=["memory-management", "cache", "replacement-policy", "data-structures", "scarcity"], era="LRU 1960s-; this impl modern",
    version="github.com/goldsborough/lru-cache master as of 2026-09-12 (commit in hashes)",
    source_origin={"artifacts": [{"kind": "git", "url": "https://github.com/goldsborough/lru-cache", "commit": "HEAD"}]},
    source_type="PSEUDOCODE_PLUS_REFERENCE_IMPL", source_identity={"repo": "github.com/goldsborough/lru-cache"},
    license={"spdx": "MIT", "status": "permissive", "evidence": "LICENSE"},
    language=["C++"], build_system="header-only; compile a Techne driver", compiler_or_interpreter="g++ 12 (docker bookworm)",
    dependencies=[], entry_points=["LRU::Cache<K,V> insert/find/contains with a capacity bound"],
    example={"command": "Techne driver: fill past capacity, verify the least-recently-used key is the one evicted; then a THRASH pattern (working set > capacity) showing near-zero hit rate", "input": "an access sequence", "output": "hit/miss counts; the evicted key on overflow"},
    environment={"runner": "docker", "image": "prometheus-fossil-c:bookworm"},
    upstream_docs=["Denning, The Working Set Model, 1968"],
    human_capability_summary={"built_to": "keep the most useful bounded subset of data in fast memory by evicting the least-recently-used entry when capacity is exceeded",
                              "pressure": "memory/cache far smaller than the data; every miss costs a slow fetch, so the eviction choice determines performance",
                              "success_means": "a high hit rate on workloads with temporal locality, within a fixed capacity"},
    known_human_problem_solved="bounded-capacity caching by recency",
    human_environmental_pressure="bounded memory, a working set larger than capacity, temporal-locality (or its absence)",
    human_failure_condition="cache thrashing: when the working set exceeds capacity and locality is poor, the hit rate collapses toward zero and the cache is pure overhead",
    behavioral_entry_point="access a working set LARGER than the capacity (the harness does this) to induce thrashing -- a pathological-behavior receipt")

spec("buddy-alloc-spaskalev",
    canonical_name="buddy_alloc -- a header-only buddy memory allocator (Stanislav Paskalev)",
    aliases=["buddy_alloc", "buddy allocator"],
    lineage="Buddy allocation (Knowlton 1965, Knuth): split memory into power-of-two blocks, merge free 'buddies' on release; the allocator behind many kernels' page allocators, trading internal fragmentation for O(log n) alloc/free and fast coalescing",
    domain=["memory-allocation", "operating-systems", "buddy-system", "resource-management", "scarcity"], era="1965 (this impl modern)",
    version="github.com/spaskalev/buddy_alloc master as of 2026-09-12 (commit in hashes)",
    source_origin={"artifacts": [{"kind": "git", "url": "https://github.com/spaskalev/buddy_alloc", "commit": "HEAD"}]},
    source_type="PSEUDOCODE_PLUS_REFERENCE_IMPL", source_identity={"repo": "github.com/spaskalev/buddy_alloc"},
    license={"spdx": "0BSD", "status": "permissive", "evidence": "LICENSE"},
    language=["C"], build_system="header-only; compile a Techne driver (or the repo's own tests)", compiler_or_interpreter="gcc 12 (docker bookworm)",
    dependencies=[], entry_points=["buddy_init / buddy_malloc / buddy_free over a fixed arena"],
    example={"command": "the repo's own tests, or a Techne driver: allocate/free within a fixed arena, exercise buddy split/merge, check no overlap and successful coalescing", "input": "an allocation workload in a bounded arena", "output": "all blocks valid; the arena coalesces back to free"},
    environment={"runner": "docker", "image": "prometheus-fossil-c:bookworm"},
    upstream_docs=["Knowlton, A Fast Storage Allocator, CACM 1965", "Knuth, TAOCP Vol 1"],
    human_capability_summary={"built_to": "allocate and free memory from a FIXED arena in power-of-two blocks, merging freed buddies so large blocks become available again -- fast coalescing under a hard capacity bound",
                              "pressure": "a fixed, bounded arena (no asking the OS for more) where fragmentation must be fought or large requests fail while small free blocks litter the arena",
                              "success_means": "requests satisfied while any contiguous block of the size exists, with bounded internal fragmentation and O(log n) operations"},
    known_human_problem_solved="fixed-arena allocation with fast coalescing (the buddy system)",
    human_environmental_pressure="a fixed memory arena, fragmentation, mixed allocation sizes",
    human_failure_condition="fragmentation defeats it: a large request fails though enough total memory is free (just not contiguous); the kernel/embedded system runs out of usable memory",
    behavioral_entry_point="allocate many small blocks then a large one, freeing in an adversarial order, to induce fragmentation failure in the bounded arena")

# ============================ AXIS 5: HARDWARE DECISION MACHINERY ============================
spec("verilog-rr-arbiter",
    canonical_name="Round-robin arbiter (Verilog, freecores)",
    aliases=["round_robin_arbiter", "rr-arbiter"],
    lineage="Round-robin arbitration: when several requesters compete for one shared resource, grant fairly in rotation so none starves; the arbiter is a small finite-state DECISION machine at the heart of buses, NoCs and schedulers",
    domain=["hardware", "arbiter", "contention", "finite-state-machine", "fairness", "verilog"], era="classic (this Verilog impl)",
    version="github.com/freecores/round_robin_arbiter master as of 2026-09-12 (commit in hashes)",
    source_origin={"artifacts": [{"kind": "git", "url": "https://github.com/freecores/round_robin_arbiter", "commit": "HEAD"}]},
    source_type="ORIGINAL_AUTHORITATIVE_RELEASE", source_identity={"repo": "github.com/freecores/round_robin_arbiter (OpenCores)"},
    license={"spdx": "see repo (OpenCores; often LGPL/BSD)", "status": "read before redistribution", "evidence": "repo"},
    language=["Verilog"], build_system="iverilog + a Techne testbench driving request vectors", compiler_or_interpreter="Icarus Verilog (docker prometheus-fossil-hw)",
    dependencies=["iverilog"], entry_points=["the arbiter module: request[] in, grant[] out, with a rotating priority pointer"],
    example={"command": "Techne testbench: assert several request lines at once across cycles, capture which gets the grant each cycle", "input": "per-cycle request bit-vectors", "output": "the grant sequence -- fair rotation, no starvation"},
    environment={"runner": "docker", "image": "prometheus-fossil-hw:bookworm"},
    upstream_docs=["Dally & Towles, Principles and Practices of Interconnection Networks"],
    human_capability_summary={"built_to": "decide, each clock, which of several simultaneous requesters gets a shared resource, rotating priority so every requester is served and none is starved",
                              "pressure": "more requesters than resources, arriving simultaneously; a fixed-priority scheme starves low-priority requesters under load",
                              "success_means": "every requester eventually granted (no starvation), with bounded waiting, at one grant per cycle"},
    known_human_problem_solved="fair arbitration of a shared hardware resource",
    human_environmental_pressure="resource contention: simultaneous competing requests for one grant",
    human_failure_condition="starvation: a requester never gets the resource; or a grant collision (two grants at once) corrupts the shared bus",
    behavioral_entry_point="drive all request lines high every cycle and confirm the grant rotates; hold one requester high forever and confirm others still progress")

spec("verilog-generic-fifo",
    canonical_name="Generic synchronous/async FIFO (Verilog, freecores)",
    aliases=["generic_fifos", "fifo"],
    lineage="A FIFO with full/empty flags and (in the async case) gray-coded pointers is the standard backpressure/flow-control element between two clock or rate domains -- it holds state and asserts 'full' to stall a fast producer",
    domain=["hardware", "fifo", "backpressure", "flow-control", "sequential-logic", "verilog"], era="classic (this Verilog impl)",
    version="github.com/freecores/generic_fifos master as of 2026-09-12 (commit in hashes)",
    source_origin={"artifacts": [{"kind": "git", "url": "https://github.com/freecores/generic_fifos", "commit": "HEAD"}]},
    source_type="ORIGINAL_AUTHORITATIVE_RELEASE", source_identity={"repo": "github.com/freecores/generic_fifos (OpenCores)"},
    license={"spdx": "see repo (OpenCores)", "status": "read before redistribution", "evidence": "repo"},
    language=["Verilog"], build_system="iverilog + a Techne testbench exercising fill/drain and the full/empty flags", compiler_or_interpreter="Icarus Verilog (docker prometheus-fossil-hw)",
    dependencies=["iverilog"], entry_points=["the FIFO module: push/pop with full/empty/level outputs"],
    example={"command": "Techne testbench: push until 'full' asserts (backpressure), pop until 'empty', check no overflow/underflow and correct FIFO order", "input": "push/pop sequences", "output": "the full/empty flag timeline; in-order data out"},
    environment={"runner": "docker", "image": "prometheus-fossil-hw:bookworm"},
    upstream_docs=["Cummings, Simulation and Synthesis Techniques for Asynchronous FIFO Design"],
    human_capability_summary={"built_to": "buffer data between a producer and consumer running at different rates, asserting 'full' to stall the producer and 'empty' to stall the consumer -- flow control in hardware",
                              "pressure": "a producer and consumer with mismatched, bursty rates; without backpressure a fast producer overruns and data is lost",
                              "success_means": "no overflow or underflow, in-order delivery, correct flags across the rate mismatch"},
    known_human_problem_solved="rate-decoupling and backpressure between hardware blocks",
    human_environmental_pressure="rate mismatch and burstiness between producer and consumer; bounded buffer depth",
    human_failure_condition="overflow (fast producer, ignored 'full') drops data; underflow (consumer reads 'empty') reads garbage -- silent corruption downstream",
    behavioral_entry_point="push faster than you pop until 'full' asserts, then confirm the producer is stalled and no data is lost; the flags are the observable decisions")

spec("verilog-uart2bus",
    canonical_name="UART-to-bus protocol controller (Verilog, freecores)",
    aliases=["uart2bus", "uart controller"],
    lineage="A UART receiver/transmitter with a bus-interface FSM: it synchronises to an asynchronous serial line (start-bit detection, mid-bit sampling, framing), a protocol state machine coping with timing and framing errors -- classic sequential control under timing pressure",
    domain=["hardware", "protocol-controller", "finite-state-machine", "serial", "synchronization", "verilog"], era="classic (this Verilog impl)",
    version="github.com/freecores/uart2bus master as of 2026-09-12 (commit in hashes)",
    source_origin={"artifacts": [{"kind": "git", "url": "https://github.com/freecores/uart2bus", "commit": "HEAD"}]},
    source_type="ORIGINAL_AUTHORITATIVE_RELEASE", source_identity={"repo": "github.com/freecores/uart2bus (OpenCores)"},
    license={"spdx": "see repo (OpenCores)", "status": "read before redistribution", "evidence": "repo"},
    language=["Verilog"], build_system="iverilog + a Techne testbench feeding serial frames", compiler_or_interpreter="Icarus Verilog (docker prometheus-fossil-hw)",
    dependencies=["iverilog"], entry_points=["the UART RX/TX FSM + the bus-command interpreter"],
    example={"command": "Techne testbench: drive a serial byte at the configured baud, capture the received byte and framing-error flag", "input": "a bit-timed serial waveform", "output": "the decoded byte(s); framing error on a corrupted stop bit"},
    environment={"runner": "docker", "image": "prometheus-fossil-hw:bookworm"},
    upstream_docs=["OpenCores uart2bus documentation"],
    human_capability_summary={"built_to": "receive asynchronous serial data with no shared clock -- detect the start bit, sample each bit at mid-period, check framing -- and turn decoded bytes into bus read/write commands",
                              "pressure": "no shared clock between sender and receiver, clock drift, and line noise that corrupts bit timing and framing",
                              "success_means": "correctly decoded bytes across clock drift, with framing errors flagged rather than silently mis-decoded"},
    known_human_problem_solved="clock-domain-crossing serial reception and bus control",
    human_environmental_pressure="no shared clock, clock drift, line noise, tight bit-timing",
    human_failure_condition="mis-sampling a bit (drift/noise) silently corrupts the byte, or a missed start bit desynchronises the whole stream",
    behavioral_entry_point="skew the serial baud slightly from the receiver's, or corrupt a stop bit, and watch the framing-error flag / mis-decode")

# ============================ AXIS 6: CONNECTIONIST / ADAPTIVE HISTORY =======================
spec("genann",
    canonical_name="genann -- a minimal feedforward neural network in C (Lewis Van Winkle)",
    aliases=["genann"],
    lineage="The perceptron/MLP lineage (Rosenblatt 1958 -> Rumelhart backprop 1986): genann is a tiny ANSI C multilayer perceptron trained by backpropagation -- the connectionist update rule and forward pass in a few hundred readable lines",
    domain=["connectionist", "neural-network", "perceptron", "backpropagation", "adaptation", "learning"], era="1958/1986 lineage; this impl 2015",
    version="github.com/codeplea/genann master as of 2026-09-12 (commit in hashes)",
    source_origin={"artifacts": [{"kind": "git", "url": "https://github.com/codeplea/genann", "commit": "HEAD"}]},
    source_type="PSEUDOCODE_PLUS_REFERENCE_IMPL", source_identity={"repo": "github.com/codeplea/genann"},
    license={"spdx": "Zlib", "status": "permissive", "evidence": "LICENSE"},
    language=["C"], build_system="make (its own examples + tests)", compiler_or_interpreter="gcc 12 (docker bookworm)",
    dependencies=[], entry_points=["genann_init / genann_train (backprop) / genann_run (forward); the shipped XOR + IRIS examples"],
    example={"command": "make; run the XOR example -- train a 2-2-1 net by backprop until it learns exclusive-or", "input": "the XOR truth table", "output": "the trained net outputs ~0/1 correctly on all four inputs"},
    environment={"runner": "docker", "image": "prometheus-fossil-c:bookworm"},
    upstream_docs=["Rosenblatt, The Perceptron, 1958", "Rumelhart, Hinton, Williams, Learning representations by back-propagating errors, 1986"],
    human_capability_summary={"built_to": "learn a nonlinear input-output mapping from examples by adjusting connection weights via gradient descent (backpropagation) through a layered network",
                              "pressure": "a mapping (like XOR) that no single linear unit can represent; the network must distribute the function across hidden units and learn the weights from data alone",
                              "success_means": "the trained network generalises the target function (e.g. learns XOR, classifies IRIS) from examples"},
    known_human_problem_solved="supervised learning of nonlinear functions by a connectionist network",
    human_environmental_pressure="a nonlinearly-separable task, learning from examples only (no programmed rule)",
    human_failure_condition="failure to converge (bad learning rate / local minimum) or overfitting -- the net memorises noise and does not generalise",
    behavioral_entry_point="change the learning rate or hidden-layer size, or corrupt the training labels, and watch convergence/generalisation change")

spec("minisom",
    canonical_name="MiniSom -- a minimal Self-Organizing Map in Python (Giuseppe Vettigli)",
    aliases=["minisom", "SOM", "Kohonen map"],
    lineage="The Self-Organizing Map (Kohonen 1982): an unsupervised connectionist network whose neurons arrange on a grid and adapt so that nearby neurons respond to similar inputs -- competitive learning that forms a topology-preserving map of the data",
    domain=["connectionist", "self-organizing-map", "unsupervised-learning", "competitive-learning", "adaptation", "clustering"], era="1982 lineage; this impl 2015",
    version="github.com/JustGlowing/minisom master as of 2026-09-12 (commit in hashes)",
    source_origin={"artifacts": [{"kind": "git", "url": "https://github.com/JustGlowing/minisom", "commit": "HEAD"}]},
    source_type="PSEUDOCODE_PLUS_REFERENCE_IMPL", source_identity={"repo": "github.com/JustGlowing/minisom"},
    license={"spdx": "MIT", "status": "permissive", "evidence": "LICENSE"},
    language=["Python"], build_system="single file minisom.py (numpy)", compiler_or_interpreter="CPython 3.11 + numpy (docker python:3.11-slim)",
    dependencies=["numpy"], entry_points=["MiniSom(x,y,input_len).train() then winner()/quantization_error()"],
    example={"command": "Techne harness: train a small SOM on clustered 2-D points, check the quantization error drops and nearby cells map nearby clusters", "input": "clustered feature vectors", "output": "a trained map; quantization error decreasing over training"},
    environment={"runner": "docker", "image": "python:3.11-slim"},
    upstream_docs=["Kohonen, Self-Organized Formation of Topologically Correct Feature Maps, 1982"],
    human_capability_summary={"built_to": "learn, without labels, a low-dimensional (grid) representation of high-dimensional data where neighbouring grid cells respond to similar inputs -- competitive, neighbourhood-cooperative weight adaptation",
                              "pressure": "unlabelled high-dimensional data with unknown structure; the map must discover clusters and topology by competition alone",
                              "success_means": "a topology-preserving map: similar inputs excite nearby neurons, and quantization error falls as it self-organises"},
    known_human_problem_solved="unsupervised topology-preserving mapping (Kohonen SOM)",
    human_environmental_pressure="unlabelled, high-dimensional data; no supervisory signal",
    human_failure_condition="a bad learning rate/neighbourhood schedule leaves the map twisted or collapsed -- it fails to separate the clusters",
    behavioral_entry_point="shrink the neighbourhood radius or learning-rate schedule, or feed non-clustered noise, and watch the map fail to organise")

spec("hopfield-takyamamoto",
    canonical_name="Hopfield Network (Python reference, Takuya Yamamoto)",
    aliases=["hopfield", "Hopfield-Network"],
    lineage="The Hopfield network (Hopfield 1982): a recurrent associative memory where patterns are stored as attractors of an energy function; presented a corrupted pattern, the dynamics descend the energy landscape and recall the nearest stored memory",
    domain=["connectionist", "hopfield-network", "associative-memory", "attractor-dynamics", "recurrent", "recovery"], era="1982 lineage; this impl modern",
    version="github.com/takyamamoto/Hopfield-Network master as of 2026-09-12 (commit in hashes)",
    source_origin={"artifacts": [{"kind": "git", "url": "https://github.com/takyamamoto/Hopfield-Network", "commit": "HEAD"}]},
    source_type="PSEUDOCODE_PLUS_REFERENCE_IMPL", source_identity={"repo": "github.com/takyamamoto/Hopfield-Network"},
    license={"spdx": "see repo LICENSE", "status": "read before redistribution", "evidence": "repo"},
    language=["Python"], build_system="python (numpy); the repo's own demo", compiler_or_interpreter="CPython 3.11 + numpy (docker python:3.11-slim)",
    dependencies=["numpy", "matplotlib (for the demo plots; a headless run skips them)"],
    entry_points=["train (Hebbian weight matrix from patterns); predict (async/sync update to an attractor)"],
    example={"command": "Techne harness: store a few binary patterns, present a NOISE-corrupted one, iterate the dynamics, check it recalls the correct stored pattern", "input": "a corrupted version of a stored pattern", "output": "the recovered (denoised) stored pattern; energy decreasing"},
    environment={"runner": "docker", "image": "python:3.11-slim"},
    upstream_docs=["Hopfield, Neural networks and physical systems with emergent collective computational abilities, 1982"],
    human_capability_summary={"built_to": "store patterns as stable attractors and RECALL the nearest stored pattern from a noisy or partial cue by iterating recurrent dynamics that minimise an energy function",
                              "pressure": "recall from corrupted/partial input, and a hard capacity limit (~0.14N patterns) beyond which memories interfere and recall fails",
                              "success_means": "a corrupted cue converges to the correct stored pattern; the network denoises and completes"},
    known_human_problem_solved="content-addressable (associative) memory with error correction by attractor dynamics",
    human_environmental_pressure="noisy/partial input, bounded storage capacity, spurious attractors",
    human_failure_condition="above capacity (or with correlated patterns) it converges to a spurious/wrong attractor -- recalls a memory that was never stored",
    behavioral_entry_point="raise the corruption level of the cue, or store MORE patterns than ~0.14N, and watch recall fail into spurious attractors")


def main():
    from .. import record as R
    for rec in S:
        try:
            old = R.load(rec["specimen_id"])
            for k in ("run_classification", "test_classification", "receipts", "hashes", "acquisition_date"):
                if old.get(k):
                    rec[k] = old[k]
        except FileNotFoundError:
            pass
        probs = R.validate(rec)
        R.save(rec)
        print("%-28s %s" % (rec["specimen_id"], "ok" if not probs else probs))


if __name__ == "__main__":
    main()
