#!/usr/bin/env python3
"""
H101 extension to invariant trace field (iTrF).

Original H101 reverse test substituted shape z into Salem polys. iTrF is a
different object -- it's the number field generated by {tr²(ρ(γ)) : γ ∈ π₁(M)}.
Neumann-Reid shows the iTrF is generated by squared traces of meridian/longitude
images, which for a shape z contains z² - z (and z + 1/z for real trace).

Simplest iTrF test: substitute u = z² - z into each Salem poly. If |p(u)| < tol,
then u is a root of p, i.e. iTrF contains the Salem-poly root.

Output: ergon/results/h101_itrf.json
"""
import json
import sys
import time
from pathlib import Path

from mpmath import mp, mpf, mpc

ROOT = Path(__file__).resolve().parent.parent
FP_JSON = ROOT / "ergon" / "results" / "shape_fingerprints.json"
OUT = ROOT / "ergon" / "results" / "h101_itrf.json"

SALEM_POLYS = [
    ("10.2.1332031009.1", [1, -1, 0, 1, -1, 1, -1, 1, 0, -1, 1], 10, 1332031009, 1.17628),
    ("10.2.1487567761.1", [1, 0, 0, 0, -1, -1, -1, 0, 0, 0, 1], 10, 1487567761, 1.21639),
    ("10.2.2932315445.1", [1, 0, 0, -1, 0, -1, 0, -1, 0, 0, 1], 10, 2932315445, 1.23039),
    ("10.2.6656764921.1", [1, 0, -1, 0, 0, -1, 0, 0, -1, 0, 1], 10, 6656764921, 1.26123),
    ("8.2.11489547.1",    [1, 0, 0, -1, -1, -1, 0, 0, 1], 8, 11489547, 1.28064),
]


def parse_complex_str(s):
    s = s.replace(" ", "").replace("*I", "j")
    import re
    m = re.match(r"^(?P<re>[+-]?(\d+\.?\d*|\.\d+)(e[+-]?\d+)?)(?P<im>[+-](\d+\.?\d*|\.\d+)(e[+-]?\d+)?)j?$", s)
    if m:
        return mpc(mpf(m.group('re')), mpf(m.group('im')))
    try:
        c = complex(s)
        return mpc(c.real, c.imag)
    except Exception:
        return None


def eval_poly_at(coeffs, z):
    n = len(coeffs) - 1
    acc = mpf(coeffs[n])
    for k in range(n - 1, -1, -1):
        acc = acc * z + mpf(coeffs[k])
    return acc


def main():
    print("H101 iTrF extension: Salem polys vs (z^2 - z)", flush=True)
    t0 = time.time()

    with open(FP_JSON) as f:
        data = json.load(f)
    fingerprints = data["fingerprints"]
    print(f"Loaded {len(fingerprints)} fingerprints", flush=True)

    mp.prec = 250
    THRESH = mpf('1e-40')

    # Three candidate iTrF generators to test:
    # u1 = z^2 - z  (Neumann-Reid for trace-of-squared-meridian)
    # u2 = z + 1/z  (real part of trace; algebraic over shape)
    # u3 = 2*z - 1 (trace of meridian in its own right)
    # We substitute each into Salem polys.
    gen_names = ['z_sq_minus_z', 'z_plus_inv_z', 'two_z_minus_1']

    hits_by_gen = {g: [] for g in gen_names}
    evaluated = 0
    hyper = 0
    for idx, fp in enumerate(fingerprints):
        if not fp.get("shapes"):
            continue
        hyper += 1
        name = fp["name"]
        for shape_str in fp["shapes"]:
            z = parse_complex_str(shape_str)
            if z is None:
                continue
            # Compute 3 candidate iTrF generators
            try:
                u1 = z*z - z
                u2 = z + (mpc(1) / z) if abs(z) > 0 else None
                u3 = 2*z - 1
            except Exception:
                continue
            evaluated += 1
            for u, gname in zip([u1, u2, u3], gen_names):
                if u is None:
                    continue
                for label, coeffs, deg, disc_abs, M in SALEM_POLYS:
                    val = eval_poly_at(coeffs, u)
                    if abs(val) < THRESH:
                        hits_by_gen[gname].append({
                            'knot': name, 'shape': shape_str[:60],
                            'salem_label': label, 'salem_M': M,
                            'u_value': str(u)[:120],
                            'residue': str(abs(val)),
                        })
        if (idx + 1) % 2000 == 0:
            print(f"  [{idx+1}/{len(fingerprints)}]  {hyper} hyp  "
                  f"{evaluated} evals  "
                  + "  ".join(f'{g}: {len(h)}' for g, h in hits_by_gen.items())
                  + f"  {time.time()-t0:.0f}s", flush=True)

    elapsed = time.time() - t0
    print(f"\nDone in {elapsed:.0f}s. {evaluated} evaluations.", flush=True)
    for gname, hits in hits_by_gen.items():
        print(f"  {gname}: {len(hits)} hits", flush=True)
        for h in hits[:5]:
            print(f"    {h['knot']} ~= {h['salem_label']} (M={h['salem_M']}) residue={h['residue']}", flush=True)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT, 'w') as f:
        json.dump({
            'salem_targets': [{'label': p[0], 'coeffs': p[1]} for p in SALEM_POLYS],
            'n_fingerprints': len(fingerprints),
            'n_hyperbolic': hyper,
            'n_evaluations': evaluated,
            'generators_tested': gen_names,
            'threshold': str(THRESH),
            'mp_prec_bits': mp.prec,
            'hits_by_generator': hits_by_gen,
            'elapsed_seconds': round(elapsed, 1),
        }, f, indent=1, default=str)
    print(f"Saved {OUT}", flush=True)


if __name__ == "__main__":
    main()
