CREATE TABLE a(id INTEGER PRIMARY KEY, v TEXT);
CREATE TABLE b(aid INTEGER REFERENCES a(id), w INTEGER);
CREATE INDEX b_aid ON b(aid);
INSERT INTO a VALUES (1,'x'),(2,'y'),(3,'z');
INSERT INTO b VALUES (1,10),(1,11),(3,30);
BEGIN; INSERT INTO a VALUES (4,'rolled-back'); ROLLBACK;
SELECT a.v, sum(b.w) FROM a JOIN b ON b.aid=a.id GROUP BY a.v ORDER BY a.v;
SELECT count(*) FROM a;
EXPLAIN QUERY PLAN SELECT * FROM b WHERE aid=1;
