# generated by answer_slice.py -- do not edit
D = ['candidates', 'comparison', 'counts', 'derived_facts', 'extreme_number', 'facts', 'max_entity', 'max_value', 'names', 'numbers', 'ordered', 'problem_text', 'quantities', 'question_target', 'relations', 'rules', 'selected_answer']
