"""Build HCA_NEUTRAL_NETWORK_ROWS.jsonl - lane HC-L01 (neutral genotype network literature).

Rows follow the schema of HISTORY_CONDITIONED_ACCESSIBILITY_REGISTRY.jsonl.
Written 2026-09-03. Every row reflects material actually read; access field records the limit.
"""
import json

rows = [
    {
        "specimen_id": "spec-wagner-2008-rna-paradox",
        "field": "RNA genotype-phenotype map / neutral networks",
        "year": 2008,
        "source": "Wagner A, 'Robustness and evolvability: a paradox resolved', Proc R Soc B 275(1630):91-100",
        "access": "FULL_TEXT_READ (automated extraction over the PMC full text, not raw paragraph-by-paragraph reading) https://pmc.ncbi.nlm.nih.gov/articles/PMC2562401/",
        "substrate": "RNA secondary structure, minimum-free-energy fold, sequence length n=30",
        "present_state_matching_available": True,
        "present_state_note": "sequences are sampled from the SAME neutral network by inverse folding, so phenotype is identical by construction and fitness is identical by the flat-neutral-network assumption",
        "machinery_class_matched": True,
        "machinery_note": "single substrate, single folding model, no on/off asymmetry of any machinery class",
        "identical_variation_operator": True,
        "identical_variation_note": "point mutation; the full 1-neighbourhood (3n neighbours) is enumerated for each sampled sequence",
        "history_differs": True,
        "history_note": "position on the neutral network is the only thing that differs, but it is NOT the product of a tracked history - sequences are drawn by inverse folding, not evolved to that position",
        "future_distribution_measured": True,
        "future_distribution_how": "ENUMERATED all one-mutant neighbours (3n per sequence) for 7.5e4 inverse-folded sequences of length 30. E_G = number of distinct novel structures in the 1-neighbourhood; overlap statistic Q compares the novel-structure sets of two sequences drawn from the same neutral network",
        "subsequent_acquisition_measured": False,
        "subsequent_acquisition_note": "populations of N=500 were simulated under mutation plus selection confined to the neutral network for up to 10 generations, and the CUMULATIVE count of unique accessible structures was tracked. That is accumulation of accessibility, not acquisition of an innovation, and it is never regressed on earlier position",
        "causal_intervention": False,
        "conditioned_on_cheap_state": False,
        "conditioned_result": "NOT ATTEMPTED for acquisition. The paper does report the cheap-state relation itself: genotype robustness is strongly NEGATIVELY correlated with genotype evolvability, Spearman s = -0.64, p < 1e-17, and states 'the greater a sequence's robustness, the lesser its evolvability'",
        "surviving_artifacts": "none identified; Vienna RNA package is the only tool dependency",
        "reconstruction_feasibility": "HIGH. Inverse folding plus exhaustive 1-neighbourhood enumeration at n=30 is cheap on current hardware. The missing arm - evolve, then measure position, then measure subsequent innovation - is a straightforward extension",
        "confounds": [
            "sequences are inverse-folded, not evolved, so 'position' carries no history and the paper cannot speak to history-conditioning at all",
            "the neutral network is treated as flat/equal-fitness by assumption rather than by measurement"
        ],
        "evidence_tier": "HCL01_LANE_FULL_TEXT_EXTRACTION",
        "H_level": "H2",
        "H_level_note": "Clean H2 on the matched-phenotype criterion: 'most structures found near two or more sequences sampled from the same neutral network are different from each other', median overlap Q = 0.6. No acquisition arm, so H3 is neither reached nor attempted",
        "relation_to_HC_T01": "Supplies the matched-phenotype natural control HC-T01 lacked, in a substrate with no machinery on/off asymmetry - but stops exactly where HC-T01 failed, at the acquisition link",
        "verdict": "H2 ESTABLISHED, H3 NOT ATTEMPTED"
    },
    {
        "specimen_id": "spec-draghi-2010-SI6",
        "field": "population genetics of robustness and evolvability / RNA validation",
        "year": 2010,
        "source": "Draghi JA, Parsons TL, Wagner GP, Plotkin JB, 'Mutational robustness can facilitate adaptation', Nature 463:353-355, AND Supplementary Information sections 6.1 and 6.2 read verbatim",
        "access": "FULL_TEXT_READ. Main text PDF https://draghi.biol.vt.edu/wp-content/uploads/2019/10/draghi_parsons_wagner_plotkin_2010.pdf ; Supplementary Information PDF (33 pp) https://media.springernature.com/original/springer-static/esm/art%3A10.1038%2Fnature08694/MediaObjects/41586_2010_BFnature08694_MOESM297_ESM.pdf",
        "substrate": "abstract Moran-model genotype-phenotype map parameterised by q (robustness), K (phenotypic neighbourhood size), P (total phenotypes), f (fraction of neighbourhood redrawn per neutral mutation); RNA secondary structure used for parameter estimation and for a Wright-Fisher validation, Vienna RNA 1.6.1",
        "present_state_matching_available": False,
        "present_state_note": "DECISIVE LIMITATION of SI 6.2. Verbatim: 'each replicate begins from a potentially unique genotype', and the chosen fold becomes that replicate's wild-type phenotype. Fitness is matched trivially (all wild-types viable, all non-target alternatives inviable) but PHENOTYPE IS NOT MATCHED across replicates, and phenotype identity is precisely the confound Cowperthwaite 2008 established",
        "machinery_class_matched": True,
        "machinery_note": "single RNA folding model throughout; no machinery class is switched on or off",
        "identical_variation_operator": True,
        "identical_variation_note": "point mutation; 24-nt sequences; Wright-Fisher discrete generations, N=500, mu=0.0002, Vienna 1.6.1 folded at 37C with dangles=2",
        "history_differs": False,
        "history_note": "founders are randomly drawn, not historically produced. Robustness q is a MEASURED property of each random founder, not the outcome of a tracked history",
        "future_distribution_measured": True,
        "future_distribution_how": "SI 6.1 estimates effective K and P by sampling 100,000 random viable genotypes per sequence length L and recording phenotypes of random non-neutral mutants; f is estimated from p_neighbor, the probability that a non-neutral mutant of genotype x has the same phenotype as a non-neutral mutant produced from a NEUTRAL NEIGHBOUR of x. Results: K_e ~ 19, P_e > 60,000, f_e ~ 0.26-0.34 for L=20-40. SI 6.2 additionally measures, per founder, the probability of being pre-adapted (K/P), the mutation rate of pre-adapted genotypes to high-fitness types (1/K), and the probability that a non-pre-adapted founder has a pre-adapted NEIGHBOUR (f)",
        "subsequent_acquisition_measured": True,
        "subsequent_acquisition_note": "YES, and genuinely longitudinal at the founder level: adaptation time = number of Wright-Fisher generations until the first high-fitness phenotype arises, N=500, mu=0.0002, M=500 or M=200 designated high-fitness structures, plotted against the founder's robustness q (Supplementary Figure 12)",
        "causal_intervention": False,
        "causal_note": "q is measured on each random founder, not manipulated. The authors criticise Ancel and Fontana for having 'did not manipulate robustness to test its effect on adaptation' - but Draghi et al. did not manipulate it either; they stratified on a measured value",
        "conditioned_on_cheap_state": False,
        "conditioned_result": "FAILS BY CONSTRUCTION, and this is the most important single finding of the lane. The accessibility parameters were not tested against robustness as competing predictors - they were MODELLED AS FUNCTIONS OF IT. Verbatim: 'the mutation rate to high-fitness types declined monotonically with q in the RNA data, and so we used a linear regression of this relationship in our analytic predictions.' Accessibility and the cheap current-state variable are therefore collinear by design, and no independent accessibility contribution can be read off Supplementary Figure 12",
        "surviving_artifacts": "Supplementary Information PDF (URL above); simulation code described as C/C++ with GSL 1.9 but NOT deposited; no data repository",
        "reconstruction_feasibility": "MODERATE-HIGH. SI 6.2 fully specifies the design (24-nt sequences, Vienna 1.6.1, dangles=2, N=500, mu=0.0002, M=500/200), so it is directly re-runnable. The fix is to hold the founder PHENOTYPE fixed and to enter measured accessibility and q as competing predictors instead of nesting one inside the other",
        "confounds": [
            "founder phenotype varies across replicates, and phenotype abundance is known to drive reachability (Cowperthwaite 2008)",
            "the abstract model explicitly assumes phenotypic neighbourhoods are redrawn independently, i.e. it deliberately does NOT represent real network position",
            "accessibility parameters regressed on q, hence collinear with the cheap state"
        ],
        "evidence_tier": "HCL01_LANE_FULL_TEXT_VERBATIM",
        "H_level": "H2",
        "H_level_note": "SI 6.1 is a solid H2 on MATCHED phenotype: neutral neighbours (identical fold) have significantly different accessible-phenotype sets, f_e ~ 0.3, i.e. roughly 30 per cent of the neighbourhood is redrawn by ONE neutral mutation, from 100,000 sampled genotypes per length. Their words: 'the phenotypic neighbourhoods of neutral neighbors differ significantly'. SI 6.2 adds a real longitudinal acquisition arm but on UNMATCHED phenotypes and with accessibility nested inside q, so H3 is not reached",
        "relation_to_HC_T01": "ANSWERS THE DIRECTIVE'S SPECIFIC QUESTION. A longitudinal accessibility-and-acquisition measurement on evolving populations DOES appear in SI section 6.2 - but it is stratified on robustness with the accessibility terms derived from robustness by regression, so it cannot separate the accessibility contribution from the cheap state. A near-miss of exactly the kind HC-T01 needs, and re-runnable",
        "verdict": "H2 ESTABLISHED (SI 6.1); LONGITUDINAL ACQUISITION ARM PRESENT (SI 6.2) BUT COLLINEAR WITH ROBUSTNESS, H3 NOT REACHED"
    },
    {
        "specimen_id": "spec-wagner-2023-EE-mutations",
        "field": "empirical fitness landscapes / evolution of evolvability",
        "year": 2023,
        "source": "Wagner A, 'Evolvability-enhancing mutations in the fitness landscapes of an RNA and a protein', Nature Communications 14:3624",
        "access": "FULL_TEXT_READ https://www.nature.com/articles/s41467-023-39321-8.pdf (open access, extracted to text and read)",
        "substrate": "two combinatorially complete EMPIRICAL fitness landscapes: ParD3 antitoxin protein of Mesorhizobium opportunistum expressed in E. coli, 3 randomised amino-acid positions, 7882 of 8000 genotypes, fitness = in vivo growth rate; and a yeast S. cerevisiae tRNA landscape, 4176 genotypes, 10 nucleotides",
        "present_state_matching_available": False,
        "present_state_note": "CRITICAL. Only BENEFICIAL evolvability-enhancing mutations are studied, so mutant and wild-type differ in present fitness. Wagner DEFINES the matched-fitness case - a neutral EE mutation, his Equation 1, mean neighbour fitness of the mutant background exceeding that of the wild-type background at delta-w = 0 - and then declines to study it. Verbatim: 'I define but do not explicitly study neutral EE mutations further here, because such mutations cannot be reliably identified in large populations with today's technology to measure fitness.' That sentence is the sharpest available statement of why this programme's target level is unoccupied",
        "machinery_class_matched": True,
        "machinery_note": "one landscape at a time; no representation class switched on or off",
        "identical_variation_operator": True,
        "identical_variation_note": "single point mutation; the same operator generates the neighbourhoods being compared and the steps of the adaptive walks",
        "history_differs": True,
        "history_note": "'history' here is one fixed mutation creating a genetic background, not an evolved trajectory",
        "future_distribution_measured": True,
        "future_distribution_how": "ENUMERATED. Because the landscapes are combinatorially complete, the FULL fitness distribution of all 1-mutant neighbours is available for both the wild-type background and the mutant background, for every pair. 681 beneficial EE mutations in the protein landscape (0.39 per cent of mutations); 2983 wild-type/mutant pairs in the RNA landscape (5.7 per cent)",
        "subsequent_acquisition_measured": True,
        "subsequent_acquisition_note": "1e4 stochastic adaptive walks per landscape, maximum 10 steps, Kimura fixation probability, N=1e8 (protein) and 7.8e6 (RNA), founders drawn from the bottom 5 per cent of the fitness distribution. At step three: protein mean w = 0.81 with at least one EE mutation vs 0.75 without, +7.7 per cent, P = 8e-151, two-sided Mann-Whitney U = 7390352, n = 6778; RNA 0.51 vs 0.48, +7.0 per cent, P = 2.2e-39, U = 10237878, n = 4109. Dose response: protein Spearman r = 0.27, P = 1.2e-161; RNA r = 0.15, P = 8.7e-52. Trapping: protein 19.8 vs 10.2 per cent survive to 10 steps, P = 1e-34; RNA 5.7 vs 0.04 per cent, P = 4.4e-30",
        "causal_intervention": False,
        "causal_note": "no physical perturbation. Controls are (a) a permutation null - 100 randomisations of the landscape's fitness values; the protein landscape has >300x more beneficial EE mutations than randomised (0.39 vs 0.0013 per cent), RNA 3.1x (5.7 vs 1.8 per cent), both P < 0.01; and (b) the EE=0 vs EE>0 contrast within simulation",
        "conditioned_on_cheap_state": True,
        "conditioned_result": "CLEARED, in two independent ways. (1) BY DEFINITION: for a beneficial mutation, Equation 2 requires the neighbourhood improvement to EXCEED the mutation's own fitness benefit, w-bar(n_m) - w-bar(n_wt) > delta-w, equivalently w-bar(n_m) - w(m) > w-bar(n_wt) - w(wt). The additive expectation from the current-state change is explicitly subtracted, so EE status is a residual rather than a fitness proxy. (2) THE REMAINING CONFOUND RUNS THE RIGHT WAY: 'in the protein landscape the fitness benefit of beneficial EE mutations is similar to that of non-EE mutations. In contrast, in the RNA landscape, the fitness benefit of EE mutations is smaller than that of non-EE mutations.' So in the protein the direct effect is matched, and in the RNA it runs AGAINST the observed advantage",
        "surviving_artifacts": "code https://github.com/andreas-wagner-uzh/EE_mutations ; protein landscape data NCBI GEO GSE153897 ; RNA landscape data Supplementary Table S1 of the source landscape paper ; Source Data file with the paper ; structure pdb 5CEG",
        "reconstruction_feasibility": "VERY HIGH. Code and both landscapes survive. The missing neutral-EE arm can be attempted on these same landscapes by binning delta-w near zero within measurement error - a re-analysis, not a new experiment",
        "confounds": [
            "only beneficial EE mutations studied, so present state is not matched - the object of interest (neutral EE) is defined and then set aside",
            "acquisition is a SIMULATED adaptive walk on a static empirical landscape, not measured innovation in an evolving population",
            "'acquisition' is fitness gain, not a novel phenotype",
            "adaptive walks use normalised fixation probabilities, which the paper notes discards the real time scale"
        ],
        "evidence_tier": "HCL01_LANE_FULL_TEXT",
        "H_level": "H3 on the acquisition-and-conditioning axes, but the H1/H2 matched-present-state precondition is NOT met",
        "H_level_note": "DO NOT COLLAPSE. This work satisfies the H3 test - an accessibility-shaped variable predicts subsequent acquisition with the cheap current-state contribution subtracted or running against it - while failing the matched-present-state precondition that H1 and H2 assert, because the mutations studied are beneficial. The levels are not nested here. It is the closest published work to what this programme wants, and its own author names the missing piece",
        "relation_to_HC_T01": "The single most useful specimen this lane found. It supplies a worked, published, artifact-backed template for the conditioning step HC-T01 failed (K7), including the correct way to subtract the additive current-state contribution before claiming an accessibility effect",
        "verdict": "H3-GRADE CONDITIONING ACHIEVED ON AN UNMATCHED PRESENT STATE; THE MATCHED-FITNESS CASE IS DEFINED AND EXPLICITLY DECLINED"
    },
    {
        "specimen_id": "spec-zheng-2019-cryptic-YFP",
        "field": "experimental protein evolution / cryptic genetic variation",
        "year": 2019,
        "source": "Zheng J, Payne JL, Wagner A, 'Cryptic genetic variation accelerates evolution by opening access to diverse adaptive peaks', Science 365(6451):347-353",
        "access": "FULL_TEXT_READ (main text, all 6 pages) https://websites.umich.edu/~zhanglab/clubPaper/07_31_2019.pdf . Supplementary Materials NOT obtained - science.org returned HTTP 403 for both the suppl_file PDF and the DC1 index",
        "substrate": "yellow fluorescent protein evolved by directed evolution in E. coli; phenotype = fluorescence emission spectrum and intensity by flow cytometry",
        "present_state_matching_available": True,
        "present_state_note": "STRONG but not fully verifiable. Phase I applied stringent STABILIZING selection keeping only the ~20 per cent of cells whose yellow fluorescence lay in a narrow interval around the ANCESTRAL median, so present phenotype in the old environment is matched to the ancestor by construction. NOT VERIFIABLE from the main text: whether green fluorescence at the START of phase II was equal across arms - that is the cheap current-state variable in the NEW environment, and figure S2A which would settle it sits behind the 403",
        "machinery_class_matched": True,
        "machinery_note": "same protein, same PCR mutagenesis, same sorting apparatus in both arms; no machinery class switched on or off. The arms differ in accumulated standing variation, not in permitted machinery",
        "identical_variation_operator": True,
        "identical_variation_note": "phase II is four generations of identical stringent directional selection for green fluorescence (0.01 per cent survival) applied to both arms; PCR mutagenesis at 0.84 amino-acid-changing mutations per molecule per generation",
        "history_differs": True,
        "history_note": "VC arm: four generations of stabilizing selection on yellow, accumulating cryptic variation. V0 control arm: initially identical ancestral YFP molecules, no phase I at all",
        "future_distribution_measured": True,
        "future_distribution_how": "MEASURED CAUSALLY BY ENGINEERING, not by sampling. Every constituent mutation of the three typical (T1-T3) and four alternative (A1-A4) high-fluorescence genotypes was engineered into the ancestor and into intermediate backgrounds and green fluorescence measured, classifying each single mutational step as accessible (significantly fitness-increasing) or inaccessible. Results: at least one third of paths to typical genotypes are accessible; A2 is reachable by only 3.3 per cent of paths; A1 by ZERO accessible paths",
        "subsequent_acquisition_measured": True,
        "subsequent_acquisition_note": "YES. Green fluorescence fold-change across four phase-II generations (VC significantly higher in three of four; ~3x faster in generation 1; at the end point 3 of 4 VC populations significantly exceeded all four V0 populations, two-way ANOVA F(7,16) = 46.5, P = 1.99e-9, post hoc Tukey P < 0.05), plus SMRT sequencing of ~500-1000 variants per population per generation tracking which genotypes rose",
        "causal_intervention": True,
        "causal_note": "THREE interventions. (a) Removing the history: the V0 arm has no phase I, and both the traversed accessible set and the outcome change. (b) Site-directed engineering of every path step to establish accessibility. (c) A no-selection directed-evolution control showing 14 of 15 adaptive variants had NOT risen faster than mutation pressure alone during phase I, i.e. they accumulated cryptically rather than being positively selected",
        "conditioned_on_cheap_state": False,
        "conditioned_result": "NOT DEMONSTRATED. No analysis pits the path-accessibility measure against a current-state variable as competing predictors. The nearest thing is the phase-I no-positive-selection control, which rules out that cryptic variants were selected for incipient green function - but that is not the same as showing accessibility outpredicts starting green fluorescence or standing genetic diversity",
        "surviving_artifacts": "custom code GitHub via Zenodo doi 10.5281/zenodo.3233964 ; SMRT sequencing data DDBJ/EMBL/GenBank accession KCZY00000000 ; Supplementary Materials figs S1-S12 and tables S1-S24 (paywalled, 403)",
        "reconstruction_feasibility": "LOW for the wet-lab arm; HIGH for re-analysis, since sequence data and code are deposited. The specific missing analysis - does path accessibility beat starting green fluorescence and beat standing diversity - may be answerable from the deposited data alone",
        "confounds": [
            "STRONGEST ALTERNATIVE: the VC arm simply carries more standing genetic variation (more mutations per molecule, broader distribution, greater diversity - all reported), so faster adaptation may be a mutation-supply/variance effect rather than a positional accessibility effect. The paper's diversity measurements document the confound but no analysis separates supply from position",
            "unverified whether phase-II starting green fluorescence was matched across arms",
            "N = 4 replicate populations per arm"
        ],
        "evidence_tier": "HCL01_LANE_FULL_TEXT (main text); SUPPLEMENT INACCESSIBLE",
        "H_level": "H4 on the causal-perturbation criterion; H3 NOT reached",
        "H_level_note": "DO NOT COLLAPSE. Removing the historical organisation (the V0 arm) demonstrably changes BOTH which genotypes are reachable and what is subsequently acquired, which is the H4 pattern, and the accessibility side is established causally by engineering rather than by inference. But H3 - the accessibility term outpredicting matched current-state variables - is never tested, so this is an H4-shaped result resting on an unconditioned association. Standing genetic variance is the untested rival explanation",
        "relation_to_HC_T01": "The best available experimental template for a machinery-matched, identical-probe, history-only contrast with a real ablation arm. It also shows the trap: a causal design can be strong and still leave the H3 conditioning entirely unaddressed",
        "verdict": "H4-SHAPED CAUSAL RESULT WITH THE H3 CONDITIONING UNTESTED; STANDING-VARIANCE CONFOUND OPEN"
    },
    {
        "specimen_id": "spec-hayden-2011-cryptic-ribozyme",
        "field": "experimental RNA evolution / cryptic genetic variation",
        "year": 2011,
        "source": "Hayden EJ, Ferrada E, Wagner A, 'Cryptic genetic variation promotes rapid evolutionary adaptation in an RNA enzyme', Nature 474:92-95",
        "access": "ABSTRACT_ONLY for the main text body, PLUS FULL SUPPLEMENTARY INFORMATION READ. Abstract https://www.nature.com/articles/nature10083 ; Supplementary Information PDF read in full, 14 pp, all figure legends and Supplementary Table 1 https://media.springernature.com/original/springer-static/esm/art%3A10.1038%2Fnature10083/MediaObjects/41586_2011_BFnature10083_MOESM60_ESM.pdf . Main text blocked: ZORA copy https://www.zora.uzh.ch/id/eprint/59818/1/Hayden_Ferrada_Wagner_cryptic_Nature_revised.pdf returns an Anubis proof-of-work challenge; scispace mirror returned HTTP 202 with an empty body",
        "substrate": "Azoarcus group I intron ribozyme, ~1e13 variants per generation, in vitro selection for substrate cleavage and ligation; phenotype = catalytic activity",
        "present_state_matching_available": False,
        "present_state_note": "PARTIALLY FAILS, and the paper's own data show why. Lines A and B both underwent 10 generations of selection for NATIVE activity, but Supplementary Figures 4-6 show the Azo* mutations (C32U, G53A, C89U, G179C) rose FASTER than the mutation rate in line A and confer significantly HIGHER native activity than wild-type - so line A adapted and its present state is not matched. Only line B is genuinely cryptic: 'in the line B data only, the rate of change is not significantly different from the expected rate of mutation accumulation'",
        "machinery_class_matched": True,
        "machinery_note": "one ribozyme, one selection apparatus; no machinery class switched on or off",
        "identical_variation_operator": True,
        "identical_variation_note": "the three New lines (New-A, New-B, New-wt) all receive the identical environmental change - selection on a phosphorothioate substrate - for 8 generations",
        "history_differs": True,
        "history_note": "New-A and New-B are founded from the 10-generation native-selected populations; New-wt is founded from the ORIGINAL population that started A and B. That is a clean remove-the-history control arm",
        "future_distribution_measured": False,
        "future_distribution_how": "NO enumeration of a one-mutant reachable-phenotype distribution. The accessibility surrogate is SEQUENCE-SPACE PROXIMITY: Supplementary Figure 7 builds a network graph of all sequences from B10, New-B1 and New-wt1, clusters at 96 per cent identity, connects clusters within 10 nucleotides, marks which clusters contain the adaptive Azo* genotype, and adds a maximum-likelihood tree of the Azo*-proximal sequences. Proximity to a known adaptive genotype is not the same object as the distribution of reachable phenotypes",
        "subsequent_acquisition_measured": True,
        "subsequent_acquisition_note": "YES - relative adaptation rate on the new phosphorothioate substrate over 8 generations, cryptic lines vs New-wt. The abstract states the cryptic populations 'adapt more rapidly to a new substrate than a population without cryptic variation'. The frequently quoted 6-to-8-fold figure comes from a SECONDARY source, not from anything read here, and is NOT verified",
        "causal_intervention": True,
        "causal_note": "the New-wt arm removes the accumulated history while keeping the substrate, the ribozyme and the selection identical",
        "conditioned_on_cheap_state": False,
        "conditioned_result": "CANNOT BE ASSESSED from what was read. The main text body was not obtainable, so any claim about conditioning would be unsourced. Recorded as NOT VERIFIED rather than NO",
        "surviving_artifacts": "Supplementary Information PDF (URL above) including Supplementary Table 1 mutational co-occurrence data (D, D-prime, r-squared, chi-square for hundreds of mutation pairs); ribozyme crystal structure pdb 1ZZN; no code or sequence-data deposition identified from the SI",
        "reconstruction_feasibility": "LOW for the wet-lab arm. FIRST ACTION IS CHEAP: obtain the main text (institutional access or author request) before spending anything else on this specimen",
        "confounds": [
            "standing genetic DIVERSITY vs positional accessibility is unseparated, the same confound as Zheng 2019",
            "line A is not present-state matched (Azo* raises native activity and rose under selection), so only the B / New-B contrast is clean",
            "the accessibility measure is sequence-space proximity to one known adaptive genotype, which presupposes the answer"
        ],
        "evidence_tier": "HCL01_LANE_ABSTRACT_PLUS_FULL_SUPPLEMENT",
        "H_level": "H2 at best on what could actually be read; the design supports a stronger claim that could not be verified",
        "H_level_note": "HONEST FLOOR. The design documented in Supplementary Figure 1c is H4-shaped (history arm, remove-history arm, identical probe, acquisition measured), and Supplementary Figure 7 supplies a genotype-space position measurement. But the main text was not read, the accessibility object is a proximity proxy rather than a reachable-phenotype distribution, and the conditioning step is unverified. Do not cite this above H2 until the main text is in hand",
        "relation_to_HC_T01": "Potentially the closest natural-substrate analogue of the HC-T01 design with a proper remove-the-history arm. Blocked on access, and access is cheap to fix",
        "verdict": "ACCESS-LIMITED. H2 VERIFIED, H3/H4 UNRESOLVED PENDING MAIN TEXT"
    }
]

with open("HCA_NEUTRAL_NETWORK_ROWS.jsonl", "w", encoding="utf-8") as fh:
    for r in rows:
        fh.write(json.dumps(r, ensure_ascii=True) + "\n")
print("wrote", len(rows), "rows")
