"""Build the HC-R01 registries Q, R, S from evidence held at build time.

Every row carries evidence_tier and evidence_source. Rows sourced from the
Ergon lane are marked as such and were verified by that seat from primary
source; this seat has read the Ergon deliverables but not all of the underlying
PDFs. Rows this seat verified itself are marked PRIMARY_SOURCE_READ_BY_HERAKLES.

No row is populated from model recall. Directive section 4.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))

# ------------------------------------------------------------------ Q
Q = [
 {"specimen_id": "spec-toussaint-exploration",
  "field": "evolutionary computation / genetic representations",
  "year": 2003,
  "source": "Toussaint, PhD thesis, Ruhr-Universitaet Bochum, sections 1.5.3-1.5.4",
  "substrate": "variable-length symbol string with rewrite operators, 25-symbol phenotype",
  "present_state_matching_available": True,
  "phenotype_matching_available": True,
  "machinery_class_matched": False,
  "machinery_note": "DECISIVE DEFECT: beta=0 populations cannot construct rewrite operators at all. One arm was permitted a class of machinery the other was not.",
  "identical_variation_operator": True,
  "history_differs": True,
  "future_distribution_measured": True,
  "future_distribution_how": "Monte Carlo, 2000 offspring per individual per generation, population-wide, both probe settings on the same frozen population",
  "subsequent_acquisition_measured": True,
  "causal_intervention": True,
  "conditioned_on_cheap_state": True,
  "conditioned_result": "FAILED. Current best fitness predicted subsequent gain at least as well as every accessibility statistic. K7 fired.",
  "surviving_artifacts": "16 hashed publications + 6 code artifacts + 324 run files, herakles/specimens/spec-toussaint-exploration/",
  "reconstruction_feasibility": "DONE. Executed 2026-09-03.",
  "confounds": ["machinery-presence asymmetry", "detector/outcome coupling, a property of the whole experimental family per the Ergon lane"],
  "evidence_tier": "PRIMARY_SOURCE_READ_BY_HERAKLES + EXECUTED",
  "H_level": "H2",
  "H_level_note": "H2 established at 24 to 108 times estimator noise, including at identical phenotype and identical fitness. H3 NOT established. H4 not attempted.",
  "relation_to_HC_T01": "IS HC-T01",
  "verdict": "HC_T01_WEAK_SIGNAL_ONLY per HC_T01_CORRECTION_2026-09-03.md"},

 {"specimen_id": "spec-kounios-2016",
  "field": "evolutionary computation / developmental organisation",
  "year": 2016,
  "source": "Kounios, Clune, Kouvaris, Wagner, Pavlicev, Weinreich, Watson, arXiv 1612.05955",
  "substrate": "gene regulatory network, 16 real genes, recurrent development",
  "present_state_matching_available": None,
  "phenotype_matching_available": None,
  "machinery_class_matched": False,
  "machinery_note": "SHARES HC-T01's DEFECT. The ablation is a one-to-one genotype-phenotype map against an evolving GRN. Turning development off is turning off the machinery that biases variation. Not a cure for our confound.",
  "identical_variation_operator": True,
  "identical_variation_note": "verified by the Ergon lane: a single randomly chosen trait of G is mutated every step by adding a uniform draw in plus or minus 0.1, identical in both arms",
  "history_differs": True,
  "future_distribution_measured": True,
  "future_distribution_how": "GLOBAL, not local: developmental basin of attraction, the number of G vectors mapping to the target phenotype, tracked over 1600 evolutionary episodes",
  "subsequent_acquisition_measured": True,
  "causal_intervention": True,
  "conditioned_on_cheap_state": False,
  "surviving_artifacts": "arXiv PDF; author code exists per the Ergon lane under handle variants",
  "reconstruction_feasibility": "UNASSESSED",
  "confounds": ["same machinery-presence asymmetry as HC-T01", "basin detector measured in a single unablated condition, so the composition is not assembled"],
  "evidence_tier": "ERGON_LANE_VERIFIED_FROM_PRIMARY_SOURCE",
  "H_level": "H1",
  "H_level_note": "the accessibility quantity is a global pre-image size, not a same-probe one-step neighbourhood, and it is not measured in the ablated arm",
  "relation_to_HC_T01": "CLOSEST SIBLING. Predates the HC-T01 directive by four months and was invisible to this seat's descendants search, which was seeded on Toussaint's citation graph."},

 {"specimen_id": "spec-tiso-2024",
  "field": "evolutionary biology / mutational transformers",
  "year": 2024,
  "source": "Tiso, PhD thesis chapter 3, 'The evolution of mutational transformers', University of Groningen, defended 23 January 2024",
  "substrate": "gene regulatory network with varying architecture and transfer function",
  "present_state_matching_available": None,
  "phenotype_matching_available": None,
  "machinery_class_matched": None,
  "machinery_note": "arms are GRN architecture crossed with transfer function, with environment and selection HELD FIXED. This is a representational manipulation and NOT selection-side, which is rare and valuable. Whether the arms count as the same machinery class is the open question for HC-R01: architecture is assigned, not evolved, so the difference may be design-conditioned rather than history-conditioned.",
  "identical_variation_operator": True,
  "history_differs": True,
  "future_distribution_measured": True,
  "future_distribution_how": "A-LOCAL: 1000 mutations at each locus of the best-performing GRN at a given time point, per the Ergon lane's direct quotation from page 67",
  "subsequent_acquisition_measured": True,
  "causal_intervention": True,
  "conditioned_on_cheap_state": False,
  "surviving_artifacts": "thesis PDF, 182 pages, recovered at ergon/kouvaris2017/original/tiso2024_thesis_groningen.pdf",
  "reconstruction_feasibility": "PROMISING, unassessed by this seat",
  "confounds": ["the detector is NOT run in the negative-control arm, the trivial network where time-to-adaptation does not improve; a detector absent from the control arm cannot support a contrast",
                "the within-run link is descriptive, n=1, a representative simulation, with no statistic relating detector state at t to time-to-adaptation at t+n",
                "never published"],
  "evidence_tier": "ERGON_LANE_VERIFIED_FROM_PRIMARY_SOURCE",
  "H_level": "H2 established, H3 attempted but descriptive",
  "H_level_note": "the nearest thing to HC-T01 that exists anywhere per the Ergon lane. Its three defects are exactly what leaves HC-T01 a rigour cell.",
  "relation_to_HC_T01": "SUPERSEDES HC-T01's missing-cell claim about the wider literature. Missed by this seat."},

 {"specimen_id": "spec-petak-2025",
  "field": "evolutionary biology / variability of evolvability",
  "year": 2025,
  "source": "Petak et al., 'The variability of evolvability: Properties of dynamic fitness landscapes determine how phenotypic variation evolves', PNAS, PMC12745803",
  "substrate": "dynamic fitness landscapes, 15 landscape pairs",
  "present_state_matching_available": None,
  "phenotype_matching_available": None,
  "machinery_class_matched": True,
  "machinery_note": "STRONGEST FEATURE FOR HC-R01: the intervention is static versus variable environment. Both arms have identical genomes, identical machinery and an identical mutation operator, and differ ONLY in environmental history. This is the machinery-matched case HC-T01 could not supply.",
  "identical_variation_operator": True,
  "identical_variation_note": "verified quotation via the Ergon lane: offspring were generated with the same mutation operation used in the evolutionary runs",
  "history_differs": True,
  "future_distribution_measured": True,
  "future_distribution_how": "A-LOCAL with the REAL operator: 2500 clones for robustness, 10000 mutated clones for phenotypic variability, longitudinal across environmental changes",
  "subsequent_acquisition_measured": True,
  "causal_intervention": True,
  "conditioned_on_cheap_state": False,
  "conditioned_note": "OPEN AND HIGH VALUE: the predictor relationship is a correlation across the 15 landscape pairs. Whether it survives conditioning on current fitness is, as far as we know, untested. If the raw data survive this is a cheap HCA-2 test on published data.",
  "surviving_artifacts": "PNAS open access, Europe PMC full-text XML; data availability unassessed by this seat",
  "reconstruction_feasibility": "UNASSESSED; possibly unnecessary if raw data survive",
  "confounds": ["selection-side intervention, so it does not test an operator-side mechanism", "arm-level rather than within-run acquisition link"],
  "evidence_tier": "ERGON_LANE_VERIFIED_FROM_PRIMARY_SOURCE",
  "H_level": "H2 established with proper replication, H3 arm-level only",
  "H_level_note": "strictly stronger than Kouvaris 2017 on the detector and its longitudinality, and properly replicated with 95 percent CIs over 15 replicates",
  "relation_to_HC_T01": "THE MACHINERY-MATCHED ANALOGUE. Highest-priority follow-up for HC-R01 question 2. Missed by this seat."},

 {"specimen_id": "spec-evca-density",
  "field": "evolving cellular automata / density classification",
  "year": "1993-1995",
  "source": "EvCA programme, six genomes recovered and verified by execution; 13 hashed publications",
  "substrate": "1D binary cellular automaton, radius 3, 128-entry rule table, density classification",
  "present_state_matching_available": True,
  "phenotype_matching_available": True,
  "machinery_class_matched": True,
  "machinery_note": "BEST AVAILABLE ON THIS AXIS. Every rule is a 128-entry binary table under the same bit-flip operator. No arm can build machinery another cannot. The HC-T01 confound cannot arise.",
  "identical_variation_operator": True,
  "history_differs": True,
  "history_note": "particle1 and particle2 come from DIFFERENT genetic-algorithm runs and sit 0.009 to 0.013 apart in measured performance: a naturally occurring matched-performance pair with different histories",
  "future_distribution_measured": False,
  "future_distribution_how": "NOT YET. But the one-step neighbourhood is EXACTLY 128 rules and is fully enumerable, so the detector needs no Monte Carlo estimate of which variants exist.",
  "subsequent_acquisition_measured": False,
  "causal_intervention": False,
  "conditioned_on_cheap_state": False,
  "surviving_artifacts": "herakles/specimens/spec-evca-density/, six genomes verified by execution, rule tables re-derived from first principles matching all 32 published hex digits for two calibration rules",
  "reconstruction_feasibility": "GATE-1 ALREADY OPEN for this specimen",
  "confounds": ["cannot separate history from location on the six recovered genomes, because rule-table content is part of the present state; see EVCA_HCA1_HCA2_DESIGN_NOTE.md section 3"],
  "evidence_tier": "PRIMARY_SOURCE_READ_BY_HERAKLES, artifacts verified by execution",
  "H_level": "H0 as it stands; H1 and H2 reachable by Stage 0 archaeology alone",
  "relation_to_HC_T01": "THE INTENDED SECOND SUBSTRATE. Design note written, run NOT authorised."},
]

# ------------------------------------------------------------------ R
R = [
 {"specimen_id": "spec-toussaint-exploration",
  "source": "HC-T01, executed by this seat 2026-09-03",
  "accessibility_effect": "PRESENT AND LARGE. Same-probe modular-degree difference of +0.52 to +2.41, 24 to 108 times the estimator noise, persisting at identical phenotype and identical fitness in 12 of 12 run pairs at generations 2000 and 3000.",
  "acquisition_link": "ABSENT. Current best fitness predicted subsequent acquisition gain at Spearman rho -1.000 over generations 100 to 500 and -0.686 to -0.987 over 50 to 200, matching or beating every accessibility statistic. avgfit, the historical positive control, also matched or beat the modular degree.",
  "why_it_is_a_background_not_a_particle": "the accessibility difference is real, robust and well resolved, and adds no independent predictive value for acquisition beyond a free measurement",
  "kill_condition": "K7",
  "evidence_tier": "PRIMARY, EXECUTED, rows committed",
  "note": "This is the programme's first entry in the background column and it is our own experiment. A collider needs backgrounds."},
]

# ------------------------------------------------------------------ S
S = [
 {"detector_id": "DP-TOUSSAINT-XI-SIGMA",
  "historical_name": "phenotypic exploration distribution, three features",
  "first_source": "Toussaint 2003 thesis section 1.5.3; earlier form in arXiv physics/0102009 (2001)",
  "mathematical_object": "distribution over the phenotype of one offspring of a fixed parent under the full variation operator",
  "estimator": "Monte Carlo, 2000 samples per individual per generation, population-wide",
  "sampling_cost": "2000x the evolution it observes; measured 2.3M samples/s in our reimplementation",
  "locality": "LOCAL, one variation step, real operator",
  "longitudinal_capability": "YES, per generation, and it was used that way in one experiment",
  "substrate_generality": "the modular degree is hand-tailored to a period-5 target of length 25 and does NOT transfer; neutral degree and the mutual-information matrix are substrate-general given a discrete positional phenotype",
  "causal_interpretability": "none alone; requires a frozen cross-operator probe, which HC-T01 supplied",
  "predictive_power_beyond_current_fitness": "TESTED BY US AND FAILED. Did not beat current best fitness or avgfit.",
  "estimator_noise_at_historical_settings": {"modular_degree": 0.02115, "neutral_degree": 0.000946, "mi_aligned": 0.001867, "avgfit": 0.000955},
  "evidence_tier": "PRIMARY_SOURCE_READ_BY_HERAKLES + REIMPLEMENTED + NOISE-QUALIFIED"},

 {"detector_id": "DP-TOUSSAINT-AVGFIT",
  "historical_name": "avgfit, unreported",
  "first_source": "recovered source 02-stringRuleJTB/main.cpp, Internet Archive capture of the 2003 Bochum site; appears in NO figure of any of the 16 recovered publications",
  "mathematical_object": "mean fitness of the sampled offspring of a parent",
  "estimator": "same 2000 samples, free rider on the same sampling",
  "sampling_cost": "zero marginal cost given the above",
  "locality": "LOCAL",
  "longitudinal_capability": "YES, computed every generation for every individual",
  "substrate_generality": "fully general wherever fitness exists",
  "causal_interpretability": "same as above",
  "predictive_power_beyond_current_fitness": "TESTED BY US. Matched or beat the structured accessibility statistics, and is therefore a BASELINE rather than a detector. This is the single most useful negative in the stack.",
  "evidence_tier": "PRIMARY, recovered from author code, executed by us"},

 {"detector_id": "DP-KOUVARIS-COMPUTEM",
  "historical_name": "computeM.m / evalMutCorr.m, unreported",
  "first_source": "recovered Kouvaris author code circa 2016 per the Ergon lane; appears in no publication and zero times in 159 pages of the author's thesis",
  "mathematical_object": "mutational variance and mutational correlations over a population",
  "estimator": "300 single mutations applied to every individual in the population, mutant phenotypes differenced",
  "sampling_cost": "300 evaluations per individual per reading",
  "locality": "LOCAL, one step, population-wide, same probe",
  "longitudinal_capability": "capable; unknown whether it was used that way",
  "substrate_generality": "general for real-vector phenotypes",
  "causal_interpretability": "unassessed",
  "predictive_power_beyond_current_fitness": "NEVER TESTED, because the instrument was never reported",
  "evidence_tier": "ERGON_LANE_VERIFIED_FROM_RECOVERED_CODE",
  "note": "Second of two instances in which recovering author code found a working detector absent from the publication record. Grounds for the standing rule that 'nobody measured X' is a claim about reporting."},

 {"detector_id": "DP-KOUNIOS-BASIN",
  "historical_name": "developmental basin of attraction",
  "first_source": "Kounios et al. 2016, arXiv 1612.05955, figure 8",
  "mathematical_object": "the number of genotype vectors that map into a target phenotype, a pre-image size",
  "estimator": "counting over the genotype space",
  "sampling_cost": "unassessed; global coverage",
  "locality": "GLOBAL, not a one-step neighbourhood",
  "longitudinal_capability": "YES, tracked over 1600 evolutionary episodes",
  "substrate_generality": "requires an enumerable or samplable genotype space and a target phenotype",
  "causal_interpretability": "the ablation exists but the basin detector was measured in a SINGLE UNABLATED CONDITION, so the composition is not assembled",
  "predictive_power_beyond_current_fitness": "NOT TESTED",
  "evidence_tier": "ERGON_LANE_VERIFIED_FROM_PRIMARY_SOURCE"},

 {"detector_id": "DP-TISO-PERLOCUS",
  "historical_name": "distribution of phenotypic effects of mutations, per locus",
  "first_source": "Tiso 2024 thesis chapter 3, page 67 and figure 5C",
  "mathematical_object": "distribution of phenotypic effects of single mutations, resolved by locus",
  "estimator": "1000 mutations at each locus of the best-performing individual at a time point",
  "sampling_cost": "1000 x number of loci per reading",
  "locality": "LOCAL, one mutation at a time, from the actual current best individual",
  "longitudinal_capability": "YES, reported at four time points within a run",
  "substrate_generality": "general for locus-structured genotypes",
  "causal_interpretability": "the arms are representational and selection is held fixed, which is rare; but the detector is NOT run in the negative-control arm",
  "predictive_power_beyond_current_fitness": "NOT TESTED. The within-run link is descriptive with n=1.",
  "evidence_tier": "ERGON_LANE_VERIFIED_FROM_PRIMARY_SOURCE",
  "note": "Per-locus resolution is a capability none of our other detectors have, and it is what let Tiso identify a single sensitive locus."},

 {"detector_id": "DP-PETAK-OFFSPRING-BETTER",
  "historical_name": "percentage of offspring with higher fitness than the parent, and phenotypic variability of clones",
  "first_source": "Petak et al. 2025, PNAS, figure 4C",
  "mathematical_object": "fraction of one-step offspring that improve on the parent, plus phenotypic variability over mutated clones",
  "estimator": "2500 clones for robustness, 10000 mutated clones for variability, using the SAME mutation operator as the evolutionary runs",
  "sampling_cost": "12500 evaluations per reading",
  "locality": "LOCAL, real operator",
  "longitudinal_capability": "YES, slopes taken after each environmental change over time",
  "substrate_generality": "fully general",
  "causal_interpretability": "selection-side intervention only",
  "predictive_power_beyond_current_fitness": "NOT TESTED as a conditional. The relationship is a correlation across 15 landscape pairs. THIS IS THE CHEAPEST AVAILABLE HCA-2 TEST if the raw data survive.",
  "evidence_tier": "ERGON_LANE_VERIFIED_FROM_PRIMARY_SOURCE",
  "note": "Properly replicated, 95 percent CIs over 15 replicates, published. The best-engineered local longitudinal detector in the stack so far."},

 {"detector_id": "DP-EVCA-ENUMERATED-NEIGHBOURHOOD",
  "historical_name": "not historical; proposed",
  "first_source": "EVCA_HCA1_HCA2_DESIGN_NOTE.md, this seat, 2026-09-03",
  "mathematical_object": "the complete set of behaviours reachable in one bit flip of a 128-entry rule table",
  "estimator": "EXACT ENUMERATION of all 128 one-bit neighbours; no sampling error in the mutation step at all",
  "sampling_cost": "128 x initial conditions per reading; at 10000 ICs that is 1.28M lattice simulations",
  "locality": "LOCAL, exact",
  "longitudinal_capability": "YES",
  "substrate_generality": "applies wherever the genotype is a short fixed-length table",
  "causal_interpretability": "high; no mechanical component to subtract because the operator is identical in all arms by construction",
  "predictive_power_beyond_current_fitness": "UNTESTED. Testing it is the point of the proposed design.",
  "evidence_tier": "PROPOSED, NOT RUN"},
]


def write(name, rows):
    p = os.path.join(HERE, name)
    with open(p, "w", encoding="utf-8") as f:
        for r in rows:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")
    print("%-58s %d rows" % (name, len(rows)))


if __name__ == "__main__":
    write("HISTORY_CONDITIONED_ACCESSIBILITY_REGISTRY.jsonl", Q)
    write("ACCESSIBILITY_WITHOUT_ACQUISITION_NEGATIVES.jsonl", R)
    write("HCA_DETECTOR_COMPARISON.jsonl", S)
