"""HARM-55 -- score Harmonia's preserved rollouts through ASAL's ORIGINAL observer path (Flax CLIP),
from the SAME frames, and write flax_scores.json in the shape harm55_compare.py reads:
    {"identity": {...}, "scores": {"<stage>_<idx>": score, ...}}

Frames: Harmonia's preserved sets are (8, 128, 128) float32 greyscale in [0, 1]
(roles/Harmonia/science/asal_ruler/out/run_2026-09-18/search/top20/<key>_frames128.npy; the full 395
are regenerated by Harmonia on request). They are turned into 224x224x3 exactly as the seven-arm
fixture did (grey -> RGB, bilinear upsample), then embedded and scored.

Two observer paths, both from the pinned ASAL body in the vault (specimen asal-sakana-2024):
  --path flax   ASAL's own foundation_models/clip.py (FlaxCLIPModel openai/clip-vit-base-patch32) and
                ASAL's own asal_metrics.calc_open_endedness_score -- needs jax/flax/transformers on a
                host with AVX (jaxlib refuses to load on GANDALF/M3). THIS is the HARM-55 deliverable.
  --path torch  the torch CLIP of techne107_asal_observer.py + the numpy metric: a SELF-CHECK that the
                frame handling here reproduces Harmonia's rows.jsonl scores on the same frames.
Identity written: jax/flax/transformers/torch versions, weights sha256 (Flax: the HF snapshot files;
torch: ~/.cache/clip/ViT-B-32.pt), preprocessing constants, body commit.
Run:  python techne/scripts/harm55_flax_score.py --frames-dir <dir of *_frames128.npy> --path flax --out flax_scores.json
"""
from __future__ import annotations

import argparse
import hashlib
import json
import pathlib
import platform
import sys
import time

import numpy as np

HERE = pathlib.Path(__file__).resolve()
sys.path.insert(0, str(HERE.parents[2]))
sys.path.insert(0, str(HERE.parent))


def to_rgb224(frames_grey: np.ndarray) -> np.ndarray:
    import techne107_asal_observer as port
    return np.stack([port.grey_to_rgb(f.astype(np.float64)) for f in frames_grey])


def load_frames(frames_dir: pathlib.Path, npz: pathlib.Path | None) -> dict[str, np.ndarray]:
    out = {}
    if npz is not None:
        z = np.load(npz)
        for k in z.files:
            out[k] = z[k]
    for p in sorted(frames_dir.glob("*_frames128.npy")) if frames_dir else []:
        out[p.name.replace("_frames128.npy", "")] = np.load(p)
    return out


def flax_observer():
    """ASAL's own observer + metric, imported from the pinned body (not re-implemented)."""
    from techne.fossils import vault
    body = vault.body_dir("asal-sakana-2024") / "upstream" / "tree"
    sys.path.insert(0, str(body))
    import jax, jaxlib, flax, transformers                       # noqa: F401  (AVX host only)
    from foundation_models.clip import CLIP                      # ASAL's wrapper
    import asal_metrics                                          # ASAL's metric (jax)
    import jax.numpy as jnp
    fm = CLIP()
    ident = {"path": "flax", "jax": jax.__version__, "jaxlib": jaxlib.__version__, "flax": flax.__version__,
             "transformers": transformers.__version__, "model": "openai/clip-vit-base-patch32 (FlaxCLIPModel)",
             "preprocessing": "foundation_models/clip.py embed_img: resize to 224 if needed, (img-mean)/std, get_image_features, L2 norm",
             "metric": "asal_metrics.calc_open_endedness_score (the body's own jax implementation)",
             "body_commit": json.loads((vault.specimen_dir("asal-sakana-2024") / "record.json").read_text(encoding="utf-8"))["source_origin"]["artifacts"][0].get("commit_resolved"),
             "weights_files_sha256": _hf_snapshot_hashes("openai/clip-vit-base-patch32")}

    def score(frames_rgb224: np.ndarray) -> float:
        z = jnp.stack([fm.embed_img(jnp.asarray(f, dtype=jnp.float32)) for f in frames_rgb224])
        return float(asal_metrics.calc_open_endedness_score(z))
    return ident, score


def _hf_snapshot_hashes(repo_id: str) -> dict:
    try:
        from huggingface_hub import scan_cache_dir
        for r in scan_cache_dir().repos:
            if r.repo_id == repo_id:
                out = {}
                for rev in r.revisions:
                    for f in rev.files:
                        if f.file_name.endswith((".msgpack", ".safetensors", ".bin")):
                            out[f.file_name] = hashlib.sha256(open(f.file_path, "rb").read()).hexdigest()
                return out
    except Exception as e:                                       # noqa: BLE001
        return {"error": str(e)[:100]}
    return {}


def torch_observer():
    import techne107_asal_observer as port
    obs = port.Observer()
    ident = {"path": "torch (self-check, NOT the HARM-55 deliverable)", "torch": obs.torch.__version__,
             "model": "openai clip ViT-B/32 via the `clip` package", "weights_sha256": obs.weights_sha256,
             "metric": "numpy port of asal_metrics.py:53 (techne107_asal_observer.open_endedness_score)"}

    def score(frames_rgb224: np.ndarray) -> float:
        return port.open_endedness_score(obs.embed(frames_rgb224))
    return ident, score


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--frames-dir", default=None); ap.add_argument("--npz", default=None)
    ap.add_argument("--path", choices=["flax", "torch"], required=True); ap.add_argument("--out", required=True)
    ap.add_argument("--rows", default=None, help="Harmonia's rows.jsonl: when given, the torch self-check reports the max |score - row score|")
    a = ap.parse_args()
    frames = load_frames(pathlib.Path(a.frames_dir) if a.frames_dir else None, pathlib.Path(a.npz) if a.npz else None)
    if not frames:
        raise SystemExit("no frames found")
    ident, score = (flax_observer if a.path == "flax" else torch_observer)()
    ident.update({"host": platform.node(), "python": platform.python_version(), "frames_input": "(8,128,128) float32 greyscale -> grey_to_rgb bilinear 224 (as the seven-arm fixture)",
                  "n_rollouts": len(frames), "written_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())})
    scores, shapes = {}, {}
    t0 = time.time()
    for k, fr in frames.items():
        fr = np.asarray(fr)
        if fr.ndim != 3 or fr.shape[0] != 8:
            shapes[k] = list(fr.shape); continue
        scores[k] = score(to_rgb224(fr))
    ident["seconds"] = round(time.time() - t0, 1)
    ident["skipped_bad_shape"] = shapes
    out = {"schema": "techne.harm55.flax_scores/1", "identity": ident, "scores": scores}
    if a.rows:
        rows = {"%s_%s" % (r["stage"], r["idx"]): r for r in (json.loads(l) for l in open(a.rows, encoding="utf-8")) if r.get("score") is not None}
        common = [k for k in scores if k in rows]
        if common:
            diffs = {k: abs(scores[k] - float(rows[k]["score"])) for k in common}
            out["self_check_vs_rows"] = {"n": len(common), "max_abs_diff": max(diffs.values()), "per_key": diffs}
    pathlib.Path(a.out).write_text(json.dumps(out, indent=1) + "\n", encoding="utf-8")
    print(json.dumps({k: round(v, 6) for k, v in list(scores.items())[:8]}), "... n=%d" % len(scores))
    if "self_check_vs_rows" in out:
        print("self-check vs rows.jsonl: n=%d max|diff|=%.3g" % (out["self_check_vs_rows"]["n"], out["self_check_vs_rows"]["max_abs_diff"]))
    print("wrote", a.out)


if __name__ == "__main__":
    main()
