"""Generator 22: Subgraph / Clique.

Per pivot/erebos_g22_subgraph_clique_research_2026-05-27.md.
Operates on the graph of Erebos compositions: finds a dense clique
of claims sharing payload-field overlap, posits a single Master
Property M that generates the whole clique.

Erebos Implementation Spec:
- Input / Provenance: At least MIN_CLIQUE_SIZE Erebos compositions
  with shared payload-field overlap >= MIN_JACCARD.
- Transformation: Hand-rolled greedy clique detection over
  payload-key Jaccard. Master property = intersection of
  composition_payload keys across the clique.
- Output Claim: "Clique of N Erebos compositions is generated by
  shared property M (intersection of payload coordinates)."
- Falsification Route: Find an object satisfying M but breaking
  one sub-claim.
- Expected Kill Pattern: counterexample_breaks_master_unification.
- Loader Feasibility: Tier A (hand-rolled clique; no networkx dep).
- Reasoning Tier: R3 (abstraction).
"""
from __future__ import annotations

from typing import Optional

from charon.agents.erebos.generators._base import (
    ComposedClaim,
    SwarmState,
)


MIN_CLIQUE_SIZE = 3
MIN_JACCARD = 0.40


def _payload_keys(row: dict) -> frozenset:
    """Extract composition_payload keys from an Erebos row."""
    extras = row.get("extras", {}) or {}
    payload = extras.get("composition_payload", {}) or {}
    return frozenset(payload.keys())


def _jaccard(a: frozenset, b: frozenset) -> float:
    if not (a or b):
        return 0.0
    return len(a & b) / max(1, len(a | b))


def _find_greedy_clique(
    rows: list[dict], min_size: int, min_jaccard: float
) -> list[dict]:
    """Greedy clique-detection: anchor on the row with most edges
    above threshold; extend by adding nodes adjacent to ALL current
    members; return list of clique members (empty if no clique meets
    min_size)."""
    if len(rows) < min_size:
        return []
    keys = [_payload_keys(r) for r in rows]
    n = len(rows)
    # Compute adjacency by Jaccard >= threshold
    adj: list[set[int]] = [set() for _ in range(n)]
    for i in range(n):
        for j in range(i + 1, n):
            if _jaccard(keys[i], keys[j]) >= min_jaccard:
                adj[i].add(j)
                adj[j].add(i)
    # Pick the most-connected node as anchor
    anchor = max(range(n), key=lambda i: len(adj[i]))
    if len(adj[anchor]) < min_size - 1:
        return []
    # Greedy extension
    clique = [anchor]
    candidates = set(adj[anchor])
    while candidates:
        # Pick candidate connected to all current clique members
        best = None
        for c in candidates:
            if all(c in adj[m] for m in clique):
                if best is None or len(adj[c]) > len(adj[best]):
                    best = c
        if best is None:
            break
        clique.append(best)
        candidates = candidates & adj[best]
    if len(clique) < min_size:
        return []
    return [rows[i] for i in clique]


class SubgraphCliqueGenerator:
    id = "g22_subgraph_clique"
    name = "Subgraph / Clique"
    spec_phase = 5
    feasibility_tier = "A"
    reasoning_tier = "R3"
    expected_kill_pattern = "counterexample_breaks_master_unification"

    def _find_clique(self, state: SwarmState) -> list[dict]:
        return _find_greedy_clique(
            state.erebos_self_ledger, MIN_CLIQUE_SIZE, MIN_JACCARD
        )

    def applicable(self, state: SwarmState) -> bool:
        clique = self._find_clique(state)
        if not clique:
            return False
        # Tried-pair key: sorted tuple of record_ids
        clique_key = "|".join(sorted(r.get("record_id", "") for r in clique))
        full_key = f"{self.id}|{clique_key}"
        return full_key not in state.tried_pairs

    def generate(self, state: SwarmState) -> Optional[ComposedClaim]:
        clique = self._find_clique(state)
        if not clique:
            return None
        clique_key = "|".join(sorted(r.get("record_id", "") for r in clique))
        full_key = f"{self.id}|{clique_key}"
        if full_key in state.tried_pairs:
            return None
        return self._build_claim(clique)

    def _build_claim(self, clique: list[dict]) -> ComposedClaim:
        n = len(clique)
        ids = [r.get("record_id", "?") for r in clique]
        clique_short = "_".join(rid[:8] for rid in ids[:3])
        composed_id = f"EREBOS-G22-clique_n{n}-{clique_short}"

        # Master property = intersection of payload keys
        master_keys = set.intersection(
            *(set(_payload_keys(r)) for r in clique)
        ) if clique else set()
        master_keys = sorted(master_keys)

        # Plugin distribution within clique (substrate-grade observation)
        from collections import Counter
        plugin_counts = Counter(
            (r.get("claim_payload") or {}).get("plugin_id", "?")
            for r in clique
        )

        composition_text = (
            f"Clique-master-property claim {composed_id}: "
            f"a clique of {n} Erebos compositions "
            f"(plugins: {dict(plugin_counts)}) shares the payload "
            f"keys {master_keys} as a common substrate. Hypothesis: "
            f"the Master Property M = `the joint presence of "
            f"{master_keys} in the composition payload` generates "
            f"the entire clique. Falsification: find any Erebos "
            f"composition outside the clique whose payload contains "
            f"{master_keys} but which fails one of the clique "
            f"members' sub-claims (or, conversely, an object that "
            f"satisfies M but breaks any clique member when "
            f"battery-tested)."
        )

        return ComposedClaim(
            plugin_id=self.id,
            composed_id=composed_id,
            input_provenance={
                "clique_size": n,
                "clique_record_ids": ids,
                "clique_plugin_distribution": dict(plugin_counts),
                "master_property_keys": master_keys,
                "min_jaccard_threshold": MIN_JACCARD,
                "min_clique_size_threshold": MIN_CLIQUE_SIZE,
            },
            transformation_description=(
                f"Build payload-key Jaccard graph over Erebos "
                f"self-ledger; greedy clique-detection with "
                f"min_jaccard={MIN_JACCARD}, min_size={MIN_CLIQUE_SIZE}; "
                f"intersect clique members' payload keys to derive "
                f"Master Property M = {master_keys}."
            ),
            output_claim_text=composition_text,
            falsification_route=(
                f"Counterexample search. Composition-aware Stygian "
                f"loader scans non-clique Erebos compositions for "
                f"those whose payload contains {master_keys}; if any "
                f"such composition's sub-claim FAILS battery when "
                f"the clique members' sub-claims PASS, the master-"
                f"property generalization is broken. Alternatively, "
                f"generate a synthetic object satisfying M and run "
                f"battery on each clique member; first failure "
                f"breaks unification."
            ),
            expected_kill_pattern="counterexample_breaks_master_unification",
            loader_feasibility_note=(
                "Tier A: clique detection runs in Erebos itself (no "
                "external dep). Composition-aware loader for the "
                "counterexample search reuses the parent loaders of "
                "each clique member; coordinator must orchestrate "
                "the N parallel battery calls."
            ),
            parent_record_ids=ids,
            composition_payload={
                "master_property_keys": master_keys,
                "clique_size": n,
                "min_jaccard_used": MIN_JACCARD,
            },
            extras={
                "plugin_distribution_in_clique": dict(plugin_counts),
                "clique_detection_version": "g22_v0.9_greedy",
            },
        )
