"""
Aporia — Fourth math expansion: from Wikipedia category listing + misc.
"""

import json, pathlib, re

ROOT = pathlib.Path(__file__).resolve().parent.parent
MATH_JSONL = ROOT / "mathematics" / "questions.jsonl"

def load_existing():
    existing = []
    if MATH_JSONL.exists():
        with open(MATH_JSONL, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line:
                    existing.append(json.loads(line))
    return existing

def normalize(t):
    t = t.lower().strip()
    t = re.sub(r"[^a-z0-9 ]", "", t)
    return re.sub(r"\s+", " ", t)

def next_id(existing):
    max_num = 0
    for q in existing:
        m = re.match(r"MATH-(\d+)", q["id"])
        if m: max_num = max(max_num, int(m.group(1)))
    return max_num

def q(counter, subdomain, title, statement, **kw):
    counter[0] += 1
    return {
        "id": f"MATH-{counter[0]:04d}", "title": title, "domain": "mathematics",
        "subdomain": subdomain, "statement": statement,
        "status": kw.get("status", "open"), "importance": kw.get("importance", ""),
        "year_posed": kw.get("year_posed", None), "posed_by": kw.get("posed_by", ""),
        "sources": kw.get("sources", []), "tags": kw.get("tags", []),
        "related_ids": [], "papers": [], "notes": kw.get("notes", ""),
    }

def new_questions(counter):
    qs = []
    def m(sub, title, stmt, **kw):
        qs.append(q(counter, sub, title, stmt, **kw))

    W = "https://en.wikipedia.org/wiki/"

    # From Wikipedia category: Unsolved problems in mathematics
    m("topology", "Bing-Borsuk conjecture", "Is every n-dimensional homogeneous ANR a topological manifold?", sources=[W+"Bing%E2%80%93Borsuk_conjecture"])
    m("number_theory", "Büchi's problem", "Does there exist a positive integer M such that every sequence of M consecutive squares has no non-trivial common difference?", sources=[W+"B%C3%BCchi%27s_problem"])
    m("group_theory", "Burnside problem (general)", "Is every finitely generated group of finite exponent necessarily finite?", sources=[W+"Burnside_problem"])
    m("combinatorics", "Discrepancy of hypergraphs", "Determine tight bounds for the discrepancy of set systems.", sources=[W+"Discrepancy_of_hypergraphs"])
    m("operator_algebra", "Dixmier problem", "Is every non-commutative C*-algebra with only one irreducible representation isomorphic to compact operators?", sources=[W+"Dixmier_problem"])
    m("analytic_number_theory", "Generalized Riemann hypothesis", "All non-trivial zeros of Dirichlet L-functions have real part 1/2.", sources=[W+"Generalized_Riemann_hypothesis"])
    m("analytic_number_theory", "Grand Riemann hypothesis", "All automorphic L-functions have non-trivial zeros only on the critical line.", sources=[W+"Grand_Riemann_hypothesis"])
    m("analytic_number_theory", "Hilbert-Polya conjecture", "The Riemann hypothesis follows from the existence of a self-adjoint operator whose eigenvalues are the zeta zeros.", sources=[W+"Hilbert%E2%80%93P%C3%B3lya_conjecture"])
    m("algebra", "Kurosh problem", "Is every algebraic algebra over a field locally finite?", sources=[W+"Kurosh_problem"])
    m("number_theory", "Magic square of squares", "Does a 3x3 magic square exist using nine distinct perfect squares?", sources=[W+"Magic_square#Magic_square_of_squares"])
    m("algebra", "Matrix mortality problem", "Is it decidable whether the zero matrix is in the semigroup generated by a given set of matrices?", sources=[W+"Matrix_mortality_problem"])
    m("quantum_information", "Mutually unbiased bases", "Do d+1 mutually unbiased bases exist in all dimensions d?", sources=[W+"Mutually_unbiased_bases"])
    m("symplectic_topology", "Nearby Lagrangian conjecture", "Every closed exact Lagrangian submanifold of a cotangent bundle is Hamiltonian isotopic to the zero section.", sources=[W+"Nearby_Lagrangian_conjecture"])
    m("number_theory", "Prouhet-Tarry-Escott problem", "Find ideal solutions to the system of equations where sums of k-th powers match.", sources=[W+"Prouhet%E2%80%93Tarry%E2%80%93Escott_problem"])
    m("combinatorics", "Snake-in-the-box problem", "Determine the longest induced path in a hypercube graph.", sources=[W+"Snake-in-the-box"])
    m("model_theory", "Tarski's exponential function problem", "Is the theory of the real field with exponentiation decidable?", sources=[W+"Tarski%27s_exponential_function_problem"])
    m("discrete_geometry", "Thomson problem", "Determine the minimum energy configuration of N electrons on a sphere.", sources=[W+"Thomson_problem"])
    m("topology", "Thurston's 24 questions", "Collection of 24 problems in 3-manifold topology and geometry; several still open.", year_posed=1982, posed_by="William Thurston", sources=[W+"Thurston%27s_24_questions"])
    m("differential_algebra", "Jacobi bound problem", "Does the Jacobi bound hold for the order of a system of differential equations?", sources=[W+"Jacobi_bound_problem"])
    m("queueing_theory", "M/G/k queue", "Determine the exact waiting time distribution for the multi-server queue with general service times.", sources=[W+"M/G/k_queue"])
    m("number_theory", "Eternity II puzzle", "Find a solution to the 256-piece edge-matching puzzle.", sources=[W+"Eternity_II_puzzle"], notes="$2M prize; combinatorial search problem")

    # Additional topology
    m("topology", "Borel conjecture (topology)", "Aspherical closed manifolds are topologically rigid: homotopy equivalent implies homeomorphic.", sources=[W+"Borel_conjecture"])
    m("topology", "Cannon conjecture", "Every Gromov hyperbolic group with 2-sphere boundary acts geometrically on hyperbolic 3-space.", sources=[W+"Cannon_conjecture"])
    m("topology", "Wall conjecture", "Every finitely dominated connected CW complex is homotopy equivalent to a finite CW complex.", sources=[W+"Wall%27s_conjecture"])
    m("topology", "Baum-Connes with coefficients", "The assembly map with coefficients is an isomorphism for all groups and all coefficient algebras.", sources=[W+"Baum%E2%80%93Connes_conjecture"])

    # Additional number theory from various
    m("number_theory", "Ankeny-Artin-Chowla conjecture", "For primes p = 1 mod 4, the fundamental unit of Q(sqrt(p)) has specific divisibility properties.", sources=[W+"Ankeny%E2%80%93Artin%E2%80%93Chowla_conjecture"])
    m("number_theory", "Cramér-Granville conjecture", "Refines Cramér's conjecture on prime gaps using Maier's theorem.", sources=[W+"Cram%C3%A9r%27s_conjecture"])
    m("number_theory", "Density hypothesis (Riemann zeta)", "N(sigma, T) << T^{2(1-sigma)+epsilon} for the zero-density of the Riemann zeta.", sources=[W+"Density_hypothesis"])
    m("number_theory", "Grimm's conjecture", "If n+1, ..., n+k are all composite, then they can be assigned distinct prime divisors.", sources=[W+"Grimm%27s_conjecture"])
    m("number_theory", "Guy's unsolved problems: friendly numbers", "Are there odd amicable pairs? Do all amicable pairs share a common factor?", sources=[W+"Amicable_numbers"])

    return qs


def main():
    existing = load_existing()
    existing_titles = {normalize(q["title"]) for q in existing}
    start_num = next_id(existing)
    counter = [start_num]
    new = new_questions(counter)

    added = []
    skipped = 0
    for nq in new:
        nt = normalize(nq["title"])
        if nt in existing_titles:
            skipped += 1
            continue
        existing_titles.add(nt)
        added.append(nq)

    all_questions = existing + added
    with open(MATH_JSONL, "w", encoding="utf-8") as f:
        for entry in all_questions:
            f.write(json.dumps(entry, ensure_ascii=False) + "\n")

    print(f"  Existing: {len(existing)}")
    print(f"  New candidates: {len(new)}")
    print(f"  Skipped (duplicate): {skipped}")
    print(f"  Added: {len(added)}")
    print(f"  Total: {len(all_questions)}")


if __name__ == "__main__":
    main()
